### ISSUE TITLE
GMod Wiki Category Addition Request

### ISSUE THREAD

**Issue by Servius** [Facepunch/garrysmod-requests#1001]
https://developer.valvesoftware.com/wiki/$maxeyedeflection
The above is a qc command. Little to no explanation on what it actually does. Could someone explain its purpose? 

Also:
Since gmod deals with a **ton** of model importing I can only guess that most of the modelers working on gmod could rapidly fill in any answers that  others may have. The Valve wiki isnt the most reliable resource for things like qc commands. A similar not so greatly documented but frequently frustration inducing item would be the server.cfg commands. A unique category for documentation on the gmod wiki would allow the community to ask questions and contribute to help produce unique content and also reduce the amount of self inflicted issues being reported by servers.

**Comment by robotboy655** [comment]
Valve Developer Community is not GMod Wiki and is not associated with Facepunch.

Valve wiki *IS* the most reliable resource for things like qc commands.

**Comment by Servius** [comment]
@robotboy655 I do agree that the valve wiki is the current most reliable resource **however** I have found it lacking information on several topics. There is a large quantity of stuff that is specific to the gmod server and player environment that would benefit from an expanded gwiki resource for qc and server.cfg commands.

**Comment by Kefta** [comment]
The Valve wiki can be edited

**Comment by Servius** [comment]
I doubt the guys that do csgo modding want to see a ton of gmod specific information. Im talking two categories. One for QC commands. Another for server.cfg commands. Currently, if there isn't a 100% solid definition of what something actually does and has an effect on most people just poke it and guess what it does. Generally this "poke it till I think I know what it does" process results in a underperforming server/client environment.

**Comment by Servius** [comment]
Not to mention the fact that the configuration for a gmod server is very different than that of a css, csgo, etc. server. Theres even a pretty radical difference in configuration when it comes to large pop and small pop gmod servers.

**Comment by Kefta** [comment]
I see the argument for server.cfg, and maybe a single page for Garry's Mod-specific map and model information, but the GMod wiki shouldn't wholly act as an alternative to the Valve wiki in the way you've described it.

**Comment by robotboy655** [comment]
There's literally nothing different in GMod to any other Source Engine in relation to .qc commands.

Pretty much same goes for server.cfg. It's just a file that runs console commands. There is nothing about it that is different to any other source engine game.

**Comment by Servius** [comment]
https://maurits.tv/data/garrysmod/wiki/wiki.garrysmod.com/indexebfc.html#Common_Server_Configuration_cvars

^Would something like the above being reintegrated into the wiki not be helpful?
