### ISSUE TITLE
Add Entity:GetSaveValue(string key)

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#1002]
More efficient than getting the entire savetable every time.

**Comment by robotboy655** [comment]
GetInternalVariable

**Comment by Kefta** [comment]
They are different. https://github.com/Facepunch/garrysmod-issues/issues/2721

I guess changing GetInternalVariable works too.

**Comment by ZehMatt** [comment]
I'm constantly running into this situation where the whole save table is just a waste for getting a single value. I would love to actually see GetSaveValue since there is also the opposite of SetSaveValue
