### ISSUE TITLE
Give more information on physics crash

### ISSUE THREAD

**Issue by Shendow** [Facepunch/garrysmod-requests#1003]
On some maps such as gmt_virus_dust03 and gmt_virus_hospital204 I've encountered random physics crashes when spawning props with **absolutely nothing** printed in console even with developer 3. I am not using a ShouldCollide hook as that's the only way I'm aware of that can cause a physics crash. It's a shot in the dark, but I think the crash may occur during a game.CleanUpMap() call after which this code is called (physics may still crash without this code):
```
	for _, v in ipairs (ents.GetAll()) do
		local cls = v:GetClass()

		if (v:IsWeapon() or cls:StartWith("item_")) then
			v:Remove()
		elseif (cls:StartWith("prop_physics")) then
			local phys = v:GetPhysicsObject()
			if (IsValid(phys)) then
				-- phys:Sleep()
				-- phys:EnableMotion(false)
				v:PhysicsDestroy()
			end
		end
	end
```

I am not able to reliably reproduce the issue but it happens roughly every 5-10 map clean ups so having (more) information as to why physics crash may help developers find what's wrong with the map/code.

**Comment by robotboy655** [comment]
You know that thing where we can't change vphysics, and as a result, fix anything physics related?

There is no info to give, we know as much as you do.
