### ISSUE TITLE
steamworks | RequestPlayerInfo() and GetPlayerName() for serverside

### ISSUE THREAD

**Issue by GitSparTV** [Facepunch/garrysmod-requests#1005]
Hello.
I am requesting for making Steamworks Library supports the serverside.
Maybe, i didn't find the reasons why it can't be realised, if it's true, a would like to know what exactly preventing to do this.

Thanks.

**Comment by robotboy655** [comment]
Why exactly you need this?

**Comment by GitSparTV** [comment]
Oh, yeah, I have looked for wiki, and understand that i summarize my request with all library.
My request is about:
[steamworks.RequestPlayerInfo()](http://wiki.garrysmod.com/page/steamworks/RequestPlayerInfo)
and then [steamworks.GetPlayerName()](http://wiki.garrysmod.com/page/steamworks/GetPlayerName) 
I founded one request there about [steamworks.GetPlayerSummary](https://github.com/Facepunch/garrysmod-requests/issues/68),  i think it will be good there too.

**Comment by GitSparTV** [comment]
For example, ULX fix that problem partially by JSON table of players who has joined to server. It stores they SteamID and last nickname. I have idea to ask about GetPlayerName by net.Send message to player. But i will not work when there's no players on the server. [On facepunch somebody found the solution by HTTP request](https://facepunch.com/showthread.php?t=1397907&p=44962399&viewfull=1#post44962399), but it's the way big and hard.

**Comment by robotboy655** [comment]
Why would you need a name of a player that is not on a server though?

**Comment by GitSparTV** [comment]
Actually, no

**Comment by robotboy655** [comment]
What?

**Comment by GitSparTV** [comment]
Yes i need to use it for getting name from SteamID. Even though player is not on the server and never joined to it.

**Comment by robotboy655** [comment]
Why you need to do this? WHY? What is it that you are trying to do?

**Comment by GitSparTV** [comment]
The same question why these functions are exist for client. For my case i use for fetching player Nickname. That's all.

**Comment by robotboy655** [comment]
They exist on client to make the Workshop stuff work. Nothing else.

I don't see why you need a name of a player that is not on a server.

**Comment by GitSparTV** [comment]
I'm using it for uninque IDs. Function helps me get latest nickname of Steam User instead of SteamID/64.
My deal is to suggest an idea/request.
Closed.
