### ISSUE TITLE
Add Lua Function Entity:GetSequenceMovement()

### ISSUE THREAD

**Issue by GameMaster85** [Facepunch/garrysmod-requests#1006]
GetSequenceMoveDist is nice and all, but what happened to GetSequenceMovement from [here](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/baseanimating.h#L249) in the SDK? It allows people to get much more accurate sequence movement (from x to y Cycle) instead of a fixed sequence movement. (From 0 to 1 Cycle). This allows for some really neat animation movement overrides such as the ones from Blade Symphony where most of their movement comes from the animations, and allows model's animations to actually dictate movement in the game very accurately.

I'm dumb though, so it might not be possible or something.

**Comment by bizzclaw** [comment]
Wow, I just came on here to request the exact same thing. This would be hugely useful now that using custom animations is becoming more prevalent.

Specifically, it would be nice if the function returned vector for the current speed on the specified frame. This could be translated in to forcing an entity's to move to the left if it's a player or nextbot.

**Comment by ballerfuturistic** [comment]
It would be extremely useful to just have more animation-related things in general in GMod honestly, and this would indefinitely improve the workflow for working with them.

**Comment by wiltOS** [comment]
I agree. This would be amazing and open up a lot of new possibilities for things

**Comment by TheLegend2Evan** [comment]
If it helps devs create better content then I dont see why this shouldn't be added back in.

**Comment by ethan277** [comment]
I would love to see this come back, since I just got into custom animations in Garry's mod thanks to some very nice mods, and I want to see those mods be able to grow and add more features since they're so much fun to use.

**Comment by Kefta** [comment]
Just to clarify, this was never binded in the GMod Lua API -- it just exists in the Source SDK.

**Comment by EdgyWeeaboo** [comment]
+1 need it back

**Comment by robotboy655** [comment]
Added Entity.GetSequenceMovement

http://wiki.garrysmod.com/page/Entity/GetSequenceMovement

**Comment by bizzclaw** [comment]
Is there no way to make it a shared method? Making it serverside only means it can't be predicted when used on players.

**Comment by Kefta** [comment]
It looks like there's a number of functions in CBaseAnimating that aren't available in the clientside counterpart. GetSequenceMovement in particular could be defined shared since Studio_SeqMovement is in client.dll, but I'm not sure why Valve didn't do so in the first place.

**Comment by GameMaster85** [comment]
I'd like to make a note to the above comments that prediction will probably be very important in this case, so it's probably a good idea to push for that. I actually assumed when I saw this that it was already shared.

**Comment by robotboy655** [comment]
Is now shared on Dev

**Comment by bizzclaw** [comment]
Thank you!
