### ISSUE TITLE
Allow binding keys through lua with client confirmation

### ISSUE THREAD

**Issue by bizzclaw** [Facepunch/garrysmod-requests#1009]
With the latest update, players are now prompted with a choice dialogue when gmod lua attempts to open a website, this is great because it allows developers to still give people access to websites through lua, but also ensures that servers can't force users on to malicious websites. 

I believe this could be applied to more than just websites, there are many commands in source that are blocked when attempting to run them on players, a big example is binding keys. There are some gamemodes that have a lot of bindings players have to bind on their own or use chat commands to trigger, but allowing developers to bind keys for players, either through a menu or when they initialize would be a huge help, and just like when opening websites, players would get a prompt telling them "Confirm Binding: A script is attempting to bind X key to Y command. Is this okay? y/n/remember my choice for this server.

I know I could write my own custom bind system that automatically hooks in to when players press down certain keys using input.IsKeyDown, but you have to do checks for that every frame because there's no API bindings like KeyPress or BindPress, on top of that it just seems counter intuitive to have two separate binding systems.

**Comment by Kefta** [comment]
This would override custom user binds too, and it wouldn't be cross-server compatible if it's a custom command. This is really unnecessary.
