### ISSUE TITLE
Add a EyeFOV function to be used in 3D rendering contexts.

### ISSUE THREAD

**Issue by raubana** [Facepunch/garrysmod-requests#1014]
It was mentioned that EyePos, EyeVector, and EyeAngles (the global functions) were meant to be used in 3D rendering contexts to get the camera's origin and angles, but there doesn't seem to be one for getting the field of view. I think it'd be really useful to know.

**Comment by raubana** [comment]
NeatNit used this as reference to this fact.

https://github.com/Facepunch/garrysmod-issues/issues/2516#issuecomment-213853034

**Comment by TiberiumFusion** [comment]
https://github.com/Facepunch/garrysmod-requests/issues/1588#issuecomment-908369096
Rubat creates `render.GetViewSetup()` instead of `EyeFOV()` and other distinct functions.
