### ISSUE TITLE
Port entities from other source engine games 

### ISSUE THREAD

**Issue by KabusIblis** [Facepunch/garrysmod-requests#1017]
https://developer.valvesoftware.com/wiki/Fog_volume

https://developer.valvesoftware.com/wiki/Linked_portal_door

fog_volume is pretty useful, allows you to control fog as desired and not be limited to one global map fog

linked_portal_door allows for some mindfuck maps + 'larger' maps, used a lot in the stanley parable

**Comment by Kefta** [comment]
The sources for these aren't available to Facepunch iirc

**Comment by Havch1k92** [comment]
https://github.com/Sandern/aswscratch/blob/master/src/game/server/fogvolume.cpp

Portal 2 branch code is under NDA, so linked_portal_door cannot be added.
