### ISSUE TITLE
More Lua exposure to NavMesh editing

### ISSUE THREAD

**Issue by Luabee** [Facepunch/garrysmod-requests#1018]
Usage of nextbots is largely limited by the inability to dynamically alter the navmesh in minor ways.

Being able to split, create, and delete navareas on the fly would make it possible to develop much more intricate nextbot functions.

**Proposal:**
The simplest and most incomplete solution would be to add a function called `navmesh.SetCursorPos(vector)`. This would allow the navmesh editing cursor to be manually placed by the server and would offer full usage of the existing navmesh editing console commands without manual interaction by a player.

A more complicated and complete solution would be to bind Lua functions directly to the many navmesh editing commands, such as `navarea:Delete()` or a `NavArea()` constructor or `CNavArea:Connect(CNavArea)` etc.

**Comment by Luabee** [comment]
The following file defines navarea functionality in C++. Binding these functions could be extremely helpful.

https://github.com/ValveSoftware/source-sdk-2013/blob/55ed12f8d1eb6887d348be03aee5573d44177ffb/mp/src/game/server/nav_area.cpp

**Comment by robotboy655** [comment]
* Added CNavArea.Remove
* Added CNavArea.SetCorner( int corner, Vector v )
* Added CNavLadder.Remove
* Added CNavArea.ConnectTo( CNavArea/CNavLadder )
* Added CNavArea.Disconnect( CNavArea/CNavLadder )
* Added CNavArea.PlaceOnGround( int corner )
* Added navmesh.CreateNavArea( Vector corner, Vector opposite_corner )
