### ISSUE TITLE
cvars.AddChangeCallback argument order unconventional

### ISSUE THREAD

**Issue by JamesxX** [Facepunch/garrysmod-requests#1019]
A small one that I have just noticed, the argument order for [cvars.AddChangeCallback](http://wiki.garrysmod.com/page/cvars/AddChangeCallback) has the identifier string as it's 3rd argument, and not its second argument like most other callback functions.

https://github.com/Facepunch/garrysmod/blob/784cd57576d85712fa13a7cea3a9523b4df966b0/garrysmod/lua/includes/modules/cvars.lua#L56-L82

One option is to deprecate the current ordering of arguments, throwing a soft error whenever the current order is used, but none the less allowing continued functionality as expected.

Another option is to leave it as it is, as it's probably not worth changing.

**Comment by Kefta** [comment]
The solution to string.Explode having improper argument order was to create a new function, string.Split. I don't think it's worth creating another function just to fix the argument order, nor do I think deprecating the current order is either in this case.

If there ever is another major API update for GMod, that would be the time to fix it.

**Comment by JamesxX** [comment]
I agree, I don't think it's worth the effort, but I think it is worth pointing it out, even if it doesn't result in anything.

**Comment by robotboy655** [comment]
The reason for this is because that argument didn't use to exist. Nothing to be done about it now.
