### ISSUE TITLE
Add a way to randomize / shuffle tables.

### ISSUE THREAD

**Issue by Acecool** [Facepunch/garrysmod-requests#102]
So, I found that you can, but can NOT shuffle a "deck of cards" / array / table using function( a, b ) local _rand = math.Rand( 0, 1 ); _rand > 0.5; end as listed in the old wiki.
It seemed to sometimes work ( read as about 0.1% of the time; sometimes during auto-refresh it would work, but most of the time it would fail ), but for the most part gave an error of invalid sort operation. So, I've been working on a shuffle algorithm for my playing cards class ( which I'm planning on releasing. )

As for what this is about, I'm going to submit a pull request with a new feature:
table.Shuffle( _table, _times );

It should be pretty straight forward due to the name. It randomizes a table with an optional var _times which is how many times it should repeat the process.

This code is done, I'm adding the pull request now.

**Comment by robotboy655** [comment]
https://wiki.facepunch.com/gmod/table.Shuffle
