### ISSUE TITLE
Add lua bindings for CBaseEntity::Teleport

### ISSUE THREAD

**Issue by ZehMatt** [Facepunch/garrysmod-requests#1023]
This function is different to SetPos as SetPos is not reliable under some circumstances such as calling it between prediction which causes the new position to be overwritten. The Source SDK already provides a function that ensures the object or player will land on the specified position when using Teleport. There is also far more going on under the hood and this should be the recommended function to move entities instantly to a new position.

**Comment by Vinzuerio** [comment]
Was actually expecting this too

**Comment by ZehMatt** [comment]
Any words on this?

**Comment by robotboy655** [comment]
`Entity:SetPos` already calls `CBaseEntity::Teleport` if the entity has a physics object and a movetype other than `MOVETYPE_NONE`. It has been this way since before 2014.
