### ISSUE TITLE
Add FCVAR_USERINFO flag to gmod_language cvar

### ISSUE THREAD

**Issue by sanny-io** [Facepunch/garrysmod-requests#1025]
This would allow serverside scripts to easily determine what language clients are using.

```lua
local lang = ply:GetInfo("gmod_language")
```
http://wiki.garrysmod.com/page/Player/GetInfo

**Comment by Kefta** [comment]
In the meantime, you can manually network the result when the user changes it

**Comment by sanny-io** [comment]
Any chance this could be added @Kefta?

**Comment by robotboy655** [comment]
Done.
