### ISSUE TITLE
Bind NPC->GetCurSchedule

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#1027]
https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/ai_basenpc.h#L671

Schedule pointer will probably have to be converted to a local schedule before sending it to Lua. The current alternative is to loop through NPC:IsCurrentSchedule for all schedule enums, but having a way to directly get it would be much more efficient.

**Comment by robotboy655** [comment]
Added
