### ISSUE TITLE
Add Incremental and decremental operators to lua

### ISSUE THREAD

**Issue by Pluto01** [Facepunch/garrysmod-requests#1031]
Just to make my life ever so slightly easier.
Basically if anyone reading this doesn't know what I mean in languages like C++ there's an easy way to add 1 to a variable

instead of doing 
a = 1
a = a + 1
you can just do
a = 1
a++

or a-- for taking away 1

**Comment by Kefta** [comment]
-- are used for comments in Lua. += and the sort would be great, though.

**Comment by robotboy655** [comment]
I agree that Lua syntax sucks balls, but this is a no go.
