### ISSUE TITLE
Make IsSpeaking and VoiceVolume shared

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#1034]
Current method for seeing if a player is speaking serverside is hijacking a PlayerCanHearPlayersVoice hook and guessing the times between hook calls, which is not ideal. I personally need this to manage the number of people speaking at once in a server.

**Comment by cannon** [comment]
yes do this

I investigated this a while ago and I think PlayerCanHearPlayersVoice is called even if the player isn't speaking, it could have changed though

**Comment by robotboy655** [comment]
Added a faked Player.IsSpeaking (returns true within 0.1 seconds of the last voice packet per player), but VoiceVolume simply cannot happen without decoding voice on the server which will reduce performance.
