### ISSUE TITLE
Add PlayerDroppedWeapon hook 

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#1037]
SWEPs have an OnDrop hook, but this can't be used for engine weapons.

**Comment by moat7** [comment]
The non-existence of this hook keeps minorities and women out of programming.

**Comment by robotboy655** [comment]
Added, the "quirks" of this hook are on the wiki:
http://wiki.garrysmod.com/page/GM/PlayerDroppedWeapon

**Comment by Kefta** [comment]
Thank you!
