### ISSUE TITLE
Change PlayerBindPress to callback all concommands

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#1038]
The hook's current behaviour of only being called for bind presses essentially makes it useless since the commands can be manually input into console. Alternatively, a separate hook for the desired behaviour would also be satisfactory, but I don't see much of a point of duplicating the same purpose.

**Comment by ThatLing** [comment]
Bump, this would be really useful.

**Comment by robotboy655** [comment]
That's not what this hook is for.
