### ISSUE TITLE
Comment out false sharing debug counters

### ISSUE THREAD

**Issue by Havch1k92** [Facepunch/garrysmod-requests#1039]
https://github.com/ValveSoftware/source-sdk-2013/pull/436

**Comment by robotboy655** [comment]
Added it to the Dev branch, do tell if it makes a difference.

**Comment by ryandmaclean** [comment]
For the largest contrast I suggest comparing with outdoor maps (light_environment ambient lighting does lots of sampling with -final) as it will spend a large fraction of its time in the ray tracer. 

For hardware - largest performance improvements are seen with machines that have a large number of hardware threads (and/or crap cache performance like AMD FX CPUs, or split cache topologies like Ryzen, or dual-socket - particularly with low interconnect bandwidth like SandyBridge-EN processors and prior).
