### ISSUE TITLE
Add FileWatcher after doing lua_openscript

### ISSUE THREAD

**Issue by gonzalologorg** [Facepunch/garrysmod-requests#1043]
If there's something that we were lacking (after adding reload_legacy_addons) were the capability of adding new Lua files after we started the game

Normally you can open the scripts and those will work! But Lua autorefresh won't work on those files although you can keep reloading your files with lua_openscript

Can this behavior be changed? Or at least a way to read all files again without File Not Found lua error?

**Comment by robotboy655** [comment]
This report is old, and I am not sure what exactly is the "Not Found" lua error, but I have made opening new autorun files be handled properly by autorefresh.

This applies only to files paths that would normally be autorefreshed, such as `autorun/`, `vgui/`, etc. 

"FileWatcher" was always watching changes to such files, the autorefresh system just does not know how to properly autorefresh such files.
