### ISSUE TITLE
Doors disappears due november update

### ISSUE THREAD

**Issue by hanm13** [Facepunch/garrysmod-requests#1044]
Screenshot : https://steamuserimages-a.akamaihd.net/ugc/879753787847730433/5BC288C505740BDE561486B4DF5B8DE3B88E08BC/

Console error :

Error Vertex File for 'props_c17/door01_left.mdl' checksum 972034250 should be 145318345

**Comment by robotboy655** [comment]
It's not related to the recent update, its a problem with the previous maps you loaded in the same game session.
