### ISSUE TITLE
Add a combine shotgunner playermodel

### ISSUE THREAD

**Issue by TotallyARussian** [Facepunch/garrysmod-requests#1046]
i really want this combine shotgunner playermodel
![combine shotgunner](https://user-images.githubusercontent.com/33379461/32978577-aca36cae-cc66-11e7-8d04-d74f564e8f22.jpg)

**Comment by robotboy655** [comment]
Its already in the game as a skin.

**Comment by TotallyARussian** [comment]
But the skin is the prisonshotgunner not this

**Comment by robotboy655** [comment]
No, there is no prison shotgunner skin in any half life games.

The shotgunner skin may only be available in the Dev branch, I am not sure.

**Comment by TotallyARussian** [comment]
But will you add it?

**Comment by TotallyARussian** [comment]
from the dev branch

**Comment by Kefta** [comment]
It'll eventually be in the main game if it's on the dev branch.

**Comment by TotallyARussian** [comment]
i hope so because i really want it

**Comment by TotallyARussian** [comment]
but can i check out the dev branch?

**Comment by Kefta** [comment]
Yes: https://wiki.garrysmod.com/page/Dev_Branch

**Comment by TotallyARussian** [comment]
yes he in there

**Comment by TotallyARussian** [comment]
so as i understand he is going to be in the next update?

**Comment by Kefta** [comment]
Yes

**Comment by TotallyARussian** [comment]
cool

**Comment by TotallyARussian** [comment]
thank you

**Comment by TotallyARussian** [comment]
i also found a problem with the normal map of this skin

**Comment by TotallyARussian** [comment]
basically it uses the same normal map as the original combine

**Comment by TotallyARussian** [comment]
but maybe its because its in development

**Comment by robotboy655** [comment]
That is the case of the model in Half-Life 2: Episode 2 as well.

Also please refrain from spamming unnecessary messages like "cool".
This isn't an instant messenger. This is a bug tracker.

**Comment by TotallyARussian** [comment]
do you have any information when that update is going to be released?

**Comment by TotallyARussian** [comment]
okay sorry

**Comment by TotallyARussian** [comment]
well i'll leave you alone thanks for telling me
