### ISSUE TITLE
p2p support back to SRCDS. 

### ISSUE THREAD

**Issue by kem008** [Facepunch/garrysmod-requests#1047]
Some Routers well block srcds and forwarding and dmz wont work. Really need this support.
I remember srcds had that function for a short time then removed p2p_enabled or something.

**Comment by robotboy655** [comment]
I am pretty sure this is already a thing. You need to use the -p2p launch parameter.

**Comment by kem008** [comment]
I give you a surprise for me it is not working. My server is up to date.

**Comment by willox** [comment]
It's only available in the dev branch. There's no easy way to get the p2p address you need to connect to, so I'll add some console print for it in a few minutes.

**Comment by kem008** [comment]
Ah okay. Ty. P2P is really useful if your router is terrible.

**Comment by kem008** [comment]
Request: @willox are you going to add a command to request the p2p address on server console. Because it only prints out one time then no more. 

Question: I checked p2p address for me and always generate same maybe depends on my IP thats why always same p2p address I get?
