### ISSUE TITLE
make female combine elite playermodel?

### ISSUE THREAD

**Issue by TotallyARussian** [Facepunch/garrysmod-requests#1049]
i know its weird maybe but could you do the female combine elite  playermodel?
maybe just resize the bones a bit so it will look like female combine elite like you did with the female metrocop

**Comment by TotallyARussian** [comment]
or just make female combine assasin a playermodel in game

**Comment by robotboy655** [comment]
No

**Comment by TotallyARussian** [comment]
oh ok

**Comment by TotallyARussian** [comment]
but what if i will tell maxofs2d and he would agree to make it?
