### ISSUE TITLE
Make serverlist.PlayerList shared

### ISSUE THREAD

**Issue by Velkon** [Facepunch/garrysmod-requests#1051]
This would allow for things like checking other server's playercount (serversdide) or just using it for a redirect menu for players that want to join other servers.

http://wiki.garrysmod.com/page/serverlist/PlayerList

**Comment by meepdarknessmeep** [comment]
not shared - menu and server. People can abuse this clientside to get ddos filtered by other networks.

**Comment by edgarasf123** [comment]
@meepdarknessmeep You can achieve that using http functions.

**Comment by meepdarknessmeep** [comment]
Yes but not with source server themselves. No need to do allow this even worse than it is already.

**Comment by edgarasf123** [comment]
You could still get flagged, I can keep sending HTTP queries to source server port, and the IP will get flagged as DDOS attempt.

**Comment by meepdarknessmeep** [comment]
No you can't, because HTTP is TCP and Source is UDP.

**Comment by meepdarknessmeep** [comment]
However you can ban yourself for rcon attempts from every server in existance.

**Comment by Velkon** [comment]
Make it serverside then

**Comment by robotboy655** [comment]
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/818
