### ISSUE TITLE
TestCollision add mask information

### ISSUE THREAD

**Issue by edgarasf123** [Facepunch/garrysmod-requests#1055]
Provided TestCollision trace information is not enough, a trace mask (and perhaps collision group at the same time) would be extremely useful. This would be useful to determine what kind of collision this is, basically allowing to "set" CONTENT flags for scripted entities.

For instance, if collision trace is originating from player physics, it will have CONTENTS_PLAYERCLIP flag set, and I could disable/enable entity physics only for players but nothing else.

**Comment by robotboy655** [comment]
Done. It's the 5th argument.
