### ISSUE TITLE
Binary form of floating point numbers

### ISSUE THREAD

**Issue by edgarasf123** [Facepunch/garrysmod-requests#1057]
`math.FloatToBin( number float ) `
`math.BinToFloat( string string )`
`math.DoubleToBin( number double )`
`math.BinToDouble( string string )`

These would be useful to have, especially if you want to store floating point numbers in files in their exact form without losing precision.

**Comment by robotboy655** [comment]
You can create such functions with Lua on your own.

**Comment by edgarasf123** [comment]
You can?

**Comment by Kefta** [comment]
http://sandbox.mc.edu/~bennet/cs110/flt/dtof.html

I'll submit a PR to the GMod repo with the functions if someone else doesn't do it.

**Comment by robotboy655** [comment]
It's just logic. You have binary library even for bit shifting.

@Kefta I don't think its a good idea, These are way too niche in my mind.

**Comment by edgarasf123** [comment]
@robotboy655 double's mantissa is 52 bit long, binary library only supports up to 32 bits.

**Comment by edgarasf123** [comment]
Ideally I would prefer StringStream implemented in gmod (as suggested in https://github.com/Facepunch/garrysmod-requests/issues/1050) , rather these functions themselves. As I could then use it to convert floating values without huge effort.

A string of 0's and 1's is also not really easy or efficient to use, I would rather like to see the raw binary string or hex string. 

The reason I want this implemented is so that I could store precise floating values(like in JSON or SQL) without any rounding errors. One example where precise values are really important are plane equations, where slight change in plane values could have drastic change 10,000 units away from origin.

**Comment by sannysc** [comment]
>A string of 0's and 1's is also not easy or efficient to use, I would rather like to see the raw binary string or hex string.

You can put bytes in strings. `"\0"` is null.

**Comment by edgarasf123** [comment]
I'm aware.

**Comment by meepdarknessmeep** [comment]
Rubat what's the harm of putting in new native faster features that are a
lot more conmplicated to do in lua than in c? I know I have had to copy the
functions that do what this request asks for for at least 9 different uses.

**Comment by edgarasf123** [comment]
I kinda managed to write it, but it involves a lot of iterations and its big in general. Where in C, same could be achieved using `int encodedfloat = *(int *)&somefloat;` without any iterations (other than generating the output itself).

Also current `DoubleToBin` computes wrong last bits of mantissa.
```lua
function IntToBin( num )
	local num = math.abs( math.floor(num) )

	local ret = ""
	while num >= 1 do
		if num % 2 == 0 then
			ret = "0" .. ret
			num = num/2
		else
			ret = "1" .. ret
			num = (num-1)/2
		end
	end
	return ret
end

function BinToDouble( bin )
    assert( #bin == 64, "Binary string must be at length of 64." )
    local s, e, m = string.match( bin, "^([01])([01][01][01][01][01][01][01][01][01][01][01])([01]+)$" )
    assert( s, "Unable to parse binary string.")

    s = s == "1" and -1 or 1
    e = tonumber( e, 2 ) - 1023

    -- Special cases
    if e == 1024 then
    	if string.find( m, "1" ) then
    		return 0/0 -- nan
    	end
    	return s * math.huge
    elseif e == 0 then
    	if not string.find( m, "1" ) then
    		return s * 0
    	end
    end

    e = 2^e
    local ret = e
    m:gsub(".", function(c)
		e = e / 2
		if c == "1" then
			ret = ret + e 
		end
	end)
    
    return s*ret
end

function DoubleToBin( num )
	local s = num < 0 and "1" or "0"
	local n = math.abs(num)

	if n ~= n then return "0111111111111111111111111111111111111111111111111111111111111111" end
	if n == math.huge then return s.."111111111110000000000000000000000000000000000000000000000000000" end
	if n == 0 then return s.."000000000000000000000000000000000000000000000000000000000000000" end

	local p
	local frac = false
	local m = ""
	if n >= 1 then
		m = IntToBin(n)
		p = #m - 1
		
		m = m:sub(1,53)
		n = (n%1)
	else
		p = 0
		while n < 1 do
			n = n * 2
			p = p - 1
		end
	end

	while n%1 ~= 0 and #m < 53 do
		if n >= 1 then
			m = m.."1"
			n = n - 1
		else
			m = m.."0"
		end
		n = n * 2
	end
    
	if n ~= 0 then -- TODO: <--------------------------------

	end
	
	m = m:sub(2, #m)
	m = m .. ("0"):rep(52 - #m)
	e = IntToBin(p+1023)
	e = ("0"):rep(11 - #e) .. e

	return s..e..m
end

function BinToByte( bin )
	local bin = ("0"):rep(8-#bin)..bin
	local ret = {}
	for b in string.gmatch( bin, "(%d%d%d%d%d%d%d%d)" ) do
		ret[#ret + 1] = string.char( tonumber( b, 2 ) )
	end
	return table.concat(ret):reverse()
end

print("<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<")
print("<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<")

for i=1, 10000 do
	print("===========================")
	local n = math.random(-10e15,10e15) + math.random()
	local b = DoubleToBin(n)
	--print(b)
	local n2 = BinToDouble(b )
	if n ~= n2 then
		print(string.format( "%f", n) ) 
		print(string.format( "%f", n2) )

	end
end
```

**Comment by meepdarknessmeep** [comment]
That function you just wrote is shit

**Comment by edgarasf123** [comment]
Write better one then.

**Comment by thegrb93** [comment]
There's no good way to do this in lua, meep. You're just being an ass for the sake of being an ass.

**Comment by Kefta** [comment]
@thegrb93 meep as usual

**Comment by meepdarknessmeep** [comment]
https://github.com/notcake/glib/blob/841798635f7cfb86bfaa0cdb056e3c3ddac2f597/lua/glib/bitconverter.lua#L188-L215
tada you guys are idiots assuming im always stupid

**Comment by Kefta** [comment]
No one is saying you're stupid - you just refuse to give constructive criticism, which would be fine if you didn't replace it with an extremely toxic attitude

**Comment by meepdarknessmeep** [comment]
I refuse to give constructive criticism when the whole function is just wrong and I'm on a phone.

**Comment by robotboy655** [comment]
Definitely don't want functions that convert into/from "01011" stings. An addition to the File object or some kind of binary buffer would make a lot more sense.

**Comment by meepdarknessmeep** [comment]
#594 ???

**Comment by edgarasf123** [comment]
One issue with bf_read/bf_write is that it has fixed size. It would be better approach just to create new buffer class which can expand dynamically.

**Comment by meepdarknessmeep** [comment]
You can reallocate and move data when you need to...

**Comment by edgarasf123** [comment]
But its not efficient, especially when working with large buffers.

**Comment by meepdarknessmeep** [comment]
Its more efficient than a constantly reallocating buffer like you are
suggesting...

**Comment by meepdarknessmeep** [comment]
And if it is iimplemented without memory management it will be the exact
same as what I said but just internal

**Comment by thegrb93** [comment]
Both can and should be done, no sense arguing which should be done.

**Comment by edgarasf123** [comment]
By "expand dynamically" I meant new space allocated in chunks and linked to last chunk.

**Comment by meepdarknessmeep** [comment]
Why would you ever link multiple allocated blocks together?! The way c
programs expand is by reallocation and copying! And there's only one way
this can be implemented, but it can be done in two areas. Lua and C.

**Comment by edgarasf123** [comment]
Because storing buffer as 1 continuous block has following issues:
- Copying big chunk of data has high performance cost.
- Causes external fragmentation, more likely to have "Out of memory" error.
- If you implement by doubling the buffer size, it will also have internal fragmentation too.

**Comment by meepdarknessmeep** [comment]
Look, you literally cannot argue for segmenting blocks of a packet when you implement an already existant class, especially when it's not even possible or performant to do. 

Your first point is void because you literally need to have a continuous chunk of data to send the data in the first place in the source engine. It's also not a high performance cost because when you allocate data for your packet you choose a reasonable first allocation size, then increase it if you need more room (overflow)

Your second point (external fragmentation) does not make ANY sense, because what you are doing now is fragmenting the way the data is laid out and how it is written and how it is read. This will quite literally destroy the performance of the engine data structure instantly.

And still no, doubling the buffer size will not have significant fragmentation of data because the packet won't exist forever and will free the data after using an older packet buffer.

**Comment by edgarasf123** [comment]
> Your first point is void because you literally need to have a continuous chunk of data to send the data in the first place in the source engine. It's also not a high performance cost because when you allocate data for your packet you choose a reasonable first allocation size, then increase it if you need more room (overflow)

You know buffers have other uses than networking? There is no reasonable allocation size, buffers can contain be 10 bytes or 100MB.

> Your second point (external fragmentation) does not make ANY sense, because what you are doing now is fragmenting the way the data is laid out and how it is written and how it is read. This will quite literally destroy the performance of the engine data structure instantly.

Fragmentation vs performance are completely 2 different things. Also it will have small impact on performance if you are smart on how you implement it. 

> And still no, doubling the buffer size will not have significant fragmentation of data because the packet won't exist forever and will free the data after using an older packet buffer.

Once again, buffers have other uses than networking. There could be buffers that are stored for longer period of times, and more than 1 buffer.

**Comment by meepdarknessmeep** [comment]
They aren't writing a new class, they are using an existing class. As such, they aren't going to do new ideas.

Buffers have more uses than networking, but when you create a buffer you generally know a reasonable allocation size. That's how Valve does it and it has not hurt them at all. Your idea is needlessly overcomplicating a simple bitbuffer class that already exists and is fine in its current state.

**Comment by Mijyuoon** [comment]
> Fragmentation vs performance are completely 2 different things. _Also it will have small impact on performance if you are smart on how you implement it._

It will have quite noticeable impact on performance due to this little thing called CPU cache. You see, CPU cache can only efficiently handle contiguous blocks of memory, and doing linked list type of bullshit can actually degrade the performance quite a lot if there are too many separate blocks.
