### ISSUE TITLE
BaseAnimatingOverlay functions should error on invalid entities

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#1058]
The wiki states [here](https://wiki.garrysmod.com/page/BaseAnimatingOverlay) that the listed gesture/layer functions can only be used on NextBots and Players; when used on other entities, the function will just silently fail without error. It would be more useful to throw an error so devs know when they can't use those functions on the target entity. 

Also, sent_anim was never switched back to BaseAnimatingOverlay:

![kgaruku](https://user-images.githubusercontent.com/4593679/33525379-ec54355c-d7f3-11e7-8954-f8ff9bb4dc82.png)

**Comment by robotboy655** [comment]
This goes for any function in the entire game that requires a specific entity or panel. Making them all error all of a sudden will fuck everything up.

As for sent_anim, it will be switched after the December update, as it requires the network protocol to be changed.

**Comment by Kefta** [comment]
I don't think allowing them to continue to silently error would abe beneficial - it will just lead to people not knowing when they're using the functions incorrectly.

**Comment by uRandomAlex** [comment]
You can just throw an ErrorNoHalt I think

**Comment by Kefta** [comment]
This can be done in Lua - I'm sure adding extra errors, halting or not, will never be added.
