### ISSUE TITLE
Add unsigned number metamethods for file objects

### ISSUE THREAD

**Issue by edgarasf123** [Facepunch/garrysmod-requests#1059]
`File:WriteULong( number int32 )`
`File:WriteUShort( number int16 )`
`File:ReadULong( )`
`File:ReadUShort( )`

Right now I use separate Lua functions to do conversion between signed and unsigned numbers when writing and reading files and its slightly hard to read the code when you have something like `fl:WriteLong(unsigned_w(num, 4))` and `num = unsigned_r(fl:ReadLong(), 4)`. Ideally I would prefer the suggested methods to be implemented.

**Comment by robotboy655** [comment]
Added.
