### ISSUE TITLE
Add a way to prevent demoui from opening

### ISSUE THREAD

**Issue by Noiwex** [Facepunch/garrysmod-requests#1062]
Currently, when you press Shift+F2 (like, running and trying to access gamemode feature on F2 key) a demoui panel will open. Not only that it opens, but it also **grabs your inputs** and requires you to close it manually with mouse. Same thing may happen with Shift+F1 (which is debugsystemui, but it's a cheat command).

I know that I can prevent demoui from happening just by typing this console command
```
alias demoui "echo nope"
```
But aliases are unavailable from GLua.

**Can you add a hook to prevent demoui from opening?** I can't think of other ways to work around this issue.

**Comment by Noiwex** [comment]
_demoui_ command never appears in _PlayerBindPress_ hook, if you wondering.

**Comment by Noiwex** [comment]
Please 😢

**Comment by robotboy655** [comment]
Disabled the key combo in multiplayer, as I don't think it can be used for anything but loading demos, which would get you off the server anyway.

It still works in singleplayer, I can't imagine it being as big of a problem in singleplayer.
