### ISSUE TITLE
Add a user became Admin hook.

### ISSUE THREAD

**Issue by redsigma** [Facepunch/garrysmod-requests#1065]
I need a hook that detects if the current player gets demoted or promoted to admin.
So far i am using LocalPlayer():IsAdmin in a Think hook to constatly check if the current player is admin.

I dont know exactly how gmod handles promoting and demoting users but such a Hook might be handy as it would optimize a lot of code.

**Comment by thegrb93** [comment]
http://wiki.garrysmod.com/page/GM/EntityNetworkedVarChanged

**Comment by robotboy655** [comment]
Won't really be a thing because every admin mod out there does it differently, and GMod's built in stuff doesn't persist across sessions.

I don't see why this would be necessary anyway, the status shouldn't change at all unless you manually change it.

**Comment by redsigma** [comment]
I see, well I'll stick to old way then. Thanks anyway.
