### ISSUE TITLE
Make it so that water extinguishes fire

### ISSUE THREAD

**Issue by TotallyARussian** [Facepunch/garrysmod-requests#1067]
So only recently i found out that water doesn't put out the fire for example if you are on fire and you will jump into the water you will still be on fire same goes for props so please fix that

**Comment by Kefta** [comment]
You can do this yourself by unigniting any entities underwater in a Tick hook or something similar.

**Comment by TotallyARussian** [comment]
But im no programmer

**Comment by Kefta** [comment]
Free of charge

```
-- Run serverside (ex. lua/autorun/server)
local CurTime = CurTime
local ents_GetAll = ents.GetAll
local flNextCheckTime = 0

hook.Add("Tick", "WaterExtinguish", function()
	local flCurTime = CurTime()
	
	if (flNextCheckTime <= flCurTime) then
		flNextCheckTime = flCurTime + 0.2 -- Check every 0.2 seconds..
		
		local tEntities = ents_GetAll()
		
		for i = 1, #tEntities do
			if (tEntities[i]:IsOnFire() and tEntities[i]:WaterLevel() == 3) then
				tEntities[i]:Extinguish()
			end
		end
	end
end)
```

**Comment by mcNuggets1** [comment]
There should be a hook, when a entity changes its waterlevel state tho.

**Comment by Kefta** [comment]
@mcNuggets1 https://github.com/Facepunch/garrysmod-requests/issues/841
