### ISSUE TITLE
util.Base64Decode

### ISSUE THREAD

**Issue by edgarasf123** [Facepunch/garrysmod-requests#1076]
Add `util.Base64Decode`. Function to encode base64 exist(`util.Base64Encode`), but no function exist to decode base64.

**Comment by robotboy655** [comment]
If only you'd bother to search first.

Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/109

**Comment by edgarasf123** [comment]
I did look it up, maybe I made grammar mistake or went blind or something. Sorry.
