### ISSUE TITLE
Hashing functions

### ISSUE THREAD

**Issue by h3xcat** [Facepunch/garrysmod-requests#1077]
* `util.CRC32( data, crc )`
Should return number. IMO, `util.CRC` should be renamed to `util.CRC32`(obviously leave `util.CRC` for backward compatibily). The current implementation of this also missing crc argument. This one is most important one, since a lot binary files use  CRC32 checksum
  * zip
  * gzip
  * gma (I know gmod doesn't check CRC, but still)
  * png
* `util.CRC64( data, crc )` 
Should return hex string
* `util.SHA256( data )`
Should return hex string
* `util.SHA1( data )` 
Should return hex string
* `util.MD5( data)` 
Should return hex string

And perhaps at the same time, implement same hashing functions for File object. To avoid creating large strings in Lua state.
`File:CRC32( len, crc )`, `File:CRC64( len, crc )`, `File:SHA256( len )`, `File:SHA1( len )`, `File:MD5( len )`

Hashing functions could be used by Lua scripts that cache data in clients, and check if current cache is up to date and is valid.

**Comment by birdbrainswagtrain** [comment]
glua.team needs this for our gmod cryptojacking activities, +1

**Comment by Kefta** [comment]
Source even has a native MD5 library in tier1

**Comment by WilliamVenner** [comment]
bump, should be an easy implementation and this is really needed

**Comment by robotboy655** [comment]
Added util.MD5/SHA1/SHA256

SHA256 is from `picosha2`, the other 2 are from the SE implementation.

Don't really know what you mean by the CRC32 comment.

**Comment by The-Lord-of-Owls** [comment]
Could we possibly get a util.SHA512 added along with these? I even took the liberty to find a c++ implementation of it that had a license file that grants free use for commercial purposes. https://github.com/pr0f3ss/SHA

This would be quite nice to have as it would make the hashing options available pretty much complete, atleast as far as I'm aware.
