### ISSUE TITLE
Lua function for checking if player has steam overlay open

### ISSUE THREAD

**Issue by BigCoderGmod** [Facepunch/garrysmod-requests#1081]
Would act like gui.IsGameUIVisible()

**Comment by Kefta** [comment]
Why do you need this, just out of curiosity?

**Comment by neico** [comment]
Loud noises whenever someone wants to look up something, ha

imo the overlay is outside-of-game content, and should stay that way, there's no direct interaction needed really.

**Comment by sannysc** [comment]
Does ```render.Capture``` still capture the overlay? I can see this being abused.

**Comment by Kefta** [comment]
@sannysc It still does in PostRender iirc

**Comment by robotboy655** [comment]
Pretty much agree with @neico.  I don't see why you'd need this either.

**Comment by BigCoderGmod** [comment]
Some C++ cheats have their overlay in the steam overlay menu. This would help combating them.

**Comment by Kefta** [comment]
How would knowing the overlay is open be able to combat them? Also, this could easily be changed in the cheat.

**Comment by BigCoderGmod** [comment]
When requesting render.Capture cheats return render.RenderView. If you see there in steam overlay but it doesn't show steam overlay you can conclude they are cheating.

**Comment by edgarasf123** [comment]
If they can override `render.Capture`, then they could also override your `gui.IsGameUIVisible`. Also I doubt any cheats use steam overlay.

**Comment by BigCoderGmod** [comment]
If they override render.Caputre then you will not see the steam overlay since render.RenderView, I believe, is not able to see it. gui.IsGameUIVisible is irrlevant.

**Comment by Kefta** [comment]
They can easily falsify the render.Capture to include the Steam overlay - think of more permanent solutions to the cheat issue if it's so prevalent in your eyes.
