### ISSUE TITLE
Official weapon drop feature

### ISSUE THREAD

**Issue by BreakinBenny** [Facepunch/garrysmod-requests#1084]
I don't know for how long this feature hasn't been officially included in Garry's Mod, but being able to drop your weapon without needing addons would be festive. We already have the **DropPrimary** console command leftover from Half-Life 2's development, after Valve decided not to limit how many weapons you could carry, so what's gonna stop you guys from "re-implementing" it here?

**Comment by edgarasf123** [comment]
This would break so many gamemodes, unless there was a convar set default to 0

**Comment by robotboy655** [comment]
That's a no, because many gamemodes and mods rely on weapons not being droppable. Weapons such as "Fists", and mods that use weapons for first person movement animations, etc.

**Comment by BreakinBenny** [comment]
How disappointing, then. It would've been alright if DropPrimary was tied to a setting for allowing players to drop their weapons… but I fully understand.

**Comment by robotboy655** [comment]
If we make an option for it, we can't make it enabled by default for reasons above, and if we make it disabled by default then what's the point at all, and how that would be different from installing a mod to do it?

**Comment by BreakinBenny** [comment]
"No difference" seems to be the answer.

**Comment by Kefta** [comment]
It already doesn't exist, but it still shows up in autocomplete for some reason

**Comment by BreakinBenny** [comment]
@Kefta Then I'm sure the command has to be removed in the other places, too.
