### ISSUE TITLE
TestCollision without overriding trace result

### ISSUE THREAD

**Issue by h3xcat** [Facepunch/garrysmod-requests#1085]
Basically the idea is when you return `true`, it would make the trace collide normally, without needing to calculate new `HitPos`.

This would allow to "set" CONTENT flags for entity. I don't believe this would be as hard to implement as https://github.com/Facepunch/garrysmod-requests/issues/208, so this could possibly work. 
```lua
local sent_contents = CONTENTS_PLAYERCLIP + CONTENTS_MONSTERCLIP

function ENT:TestCollision( startpos, delta, isbox, extents, mask )
	if bit.band( mask, sent_contents ) ~= 0 then
		return true
	end
	return nil
end
```

**Comment by robotboy655** [comment]
Dunno if it works the way you want it to, but this now gives me a promising result:
```
local sent_contents = CONTENTS_GRATE
function ENT:TestCollision( startpos, delta, isbox, extents, mask )
	if bit.band( mask, sent_contents ) ~= 0 then return true end
end
```

Which is that you can shoot through, yet stand on the entity and pick it up with physics gun.
