### ISSUE TITLE
util.Base64Decode()

### ISSUE THREAD

**Issue by Mwr247** [Facepunch/garrysmod-requests#109]
We have util.Base64Encode(), but no util.Base64Decode().

This would be quite useful for decoding binary data encoded in base64 for transmission to the server or client.

And because someone will inevitably argue "just write the function yourself where you need it" (as they always do for these sorts of things), I would like to point out that util.Base64Encode() already exists natively, and thus it stands to reason that some method of decoding should be natively supported as well.

**Comment by Noiwex** [comment]
What the hell, if you can encode something, then you should be able to decode it. Add this function.

**Comment by Grocel** [comment]
Garry's reasons for this incomplete future are probably the worst I have ever heard. Where you can decode something you have to be able encode it too and vice versa.

There are no valid exceptions to it at all and the use case doesn't matter.
In this case there is no "Why?" or "Make it yourself."!
If you don't want or you can't both functions then you shouldn't do any of them...

As GMod is developed by others now, I hope that the decode function can be implemented now.

**Comment by Noiwex** [comment]
https://en.wikibooks.org/wiki/Algorithm_Implementation/Miscellaneous/Base64

Code is in public domain.
