### ISSUE TITLE
Clarify rules on redirecting clients to another server

### ISSUE THREAD

**Issue by BlackCetha** [Facepunch/garrysmod-requests#1091]
I would like to build a system that automatically balances playercounts on my servers. For that I will obviously have to move clients.
I know that servers got blacklisted for using redirection servers.

Please clarify what is allowed in terms of making the clients connect to another server.

**Comment by Kefta** [comment]
I believe Rubat said at one point that as long as the server points to an actual SRCDS instance and has players (not just a passthrough) it's allowed.

**Comment by edgarasf123** [comment]
As long as you are not spoofing player count, you should be fine.

**Comment by Kefta** [comment]
Rubat said in somewhere (may have been Steam chat) that the redirect has to be an actual srcds instance that holds players.

**Comment by CaptainPRICE** [comment]
@BlackCetha I have a similar idea too. Except mine redirect server would serve as a lobby at the same time (where players could use chat, and UI to enter an another server)...

@robotboy655 So, a nice definition of "redirect server" would be nice (to avoid getting a server blacklisted of course).

**Comment by mcNuggets1** [comment]
Why do we have to specify rules, just host a server and don't spoof the ping or player count.
That's it, it's basic fair play.

**Comment by Kefta** [comment]
@mcNuggets1 That doesn't at all clarify redirect servers. Rules should be specified because server hosts have a business to run and don't have the time to guess what will get their server blocked.
