### ISSUE TITLE
Add ents.FindAlongRay

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#1092]
Much like a line trace but this will not stop when one entity is hit. This can be used for more efficient bullet penetration since traces don't have to be restarted for every entity hit, and penetration through the world doesn't have to step through to find an exit.

https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/se2007/game/server/util.h#L275-L279

**Comment by thegrb93** [comment]
I think traces would need to be restarted still to find the enter/exit points but this still seems very useful.

**Comment by maximlahaxim** [comment]
This would be extremely useful. Traces are literally just modified partitions as far as I know, so there's no reason we shouldn't have access to what's essentially their base.

**Comment by robotboy655** [comment]
Added ents.FindAlongRay( vecStart, VecEnd, vecMins=nil, vecMaxs=nil ) = table
