### ISSUE TITLE
Change RunString's default identifier to the executing stack frame's src

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#1093]
The current default identifier of "RunString" is extremely ambiguous when errors occur and the developer didn't bother to put in their own identifier. Making the default identifier the executing file would be a big help in debugging. Example of a Lua fix:
```
local fRunString = RunString

function RunString(sCode, sIdentifier, ...)
	if (sIdentifier == nil) then
		local tStack = debug.getinfo(2, "s")
		
		if (tStack ~= nil) then
			local sSource = tStack.source
			
			if (sSource ~= nil) then
				sIdentifier = sSource
			end
		end
	end	
	
	return fRunString(sCode, sIdentifier, ...)
end
```

**Comment by meepdarknessmeep** [comment]
seems kind of pointless to me in all honesty

**Comment by Kefta** [comment]
In what manner? It prevents server owners and players from having to override RunString to find the source of unidentified errors.

**Comment by CaptainPRICE** [comment]
I'd keep `RunString` as is...
Do I need to mention this change would break existing code?
Codes which choose to omit the 2nd argument, and implicitly rely upon that argument being the default value "RunString"...
Honestly, having RunString use the source of the stack frame above would up more confusing...
No thank you.

**Comment by Kefta** [comment]
It wouldn't break anything - the second argument would still be optional and instead point to the file that called RunString. This only helps as it can be used to identify broken addons using it.

**Comment by CaptainPRICE** [comment]
> It wouldn't break anything

Are you stupi*?
```lua
RunString[[
-- ...
local debugInfo = debug.getinfo(1)
-- Broken!
local runString = _G[string.sub(debugInfo.source, 2)]
runString("")
-- ...
]]
```

> This only helps as it can be used to identify broken addons using it.

No, it does not. Where's the addon name...?
I can proof it if you want.

**Comment by Kefta** [comment]
The first isn't broken, and the second is an extremely specific instance that I can't imagine anyone using.

It helps find the addon by giving you a file path. From there, you can use the whereis concommand to find the physical source.

**Comment by thegrb93** [comment]
I'm guessing he's angry because it could break one of his cheats or something? Honestly don't see any issue

**Comment by CaptainPRICE** [comment]
> I'm guessing he's angry...

I am not angry, just expressing my thoughts in my way.

-----

Part 2:
What if the second argument is explicitly specified to fake an addon erroring?
What if the 2nd argument is explicitly set to `"RunString"`?
The list goes on... :(
Your proposed `RunString` patch is not really helping find the real source of the issue, and it has a possibility of breaking existing code.
Also, do you realize an error will also contain a current line (which is appended after the chunk name), leading to confusion...
What outweighs those downsides for such a little gain (an error message rendering a chunk name of the level above when RunString is called with `nil` as the 2nd argument)?
Do the math.

Conclusion: This is just, pointless, just as @meepen had said.

**Comment by sannysc** [comment]
Wow, you've managed to give an example of the stupidest most convoluted way this change could possibly break a script.

>What if the second argument is explicitly specified to fake an addon erroring?

???
What does that even have to do with this PR? You can already do that.

>What if the 2nd argument is explicitly set to "RunString"?

It would work exactly the way it would if it was given any other identifier. What a shocker.

>Also, do you realize an error will also contain a current line (which is appended after the chunk name), leading to confusion...

Woah, an actual valid criticism you've somehow conjured.

**Comment by Kefta** [comment]
Yeah, the line number would be off; I think it's always -1. Nothing that can be done without adding a way to change it.

**Comment by CaptainPRICE** [comment]
> I think it's always -1.

And I think you are wrong.
It should be the current line number of where an error occurs in a RunString's code.
Which is going to confuse devs, as stated in my (first) comment, since your patched `RunString` will use the chunk name of the stack frame a `RunString` is called from.
In a worst case scenario, devs would go ahead and spend their time tracing down a non-existing problem in a perfectly working addon.

**Comment by CaptainPRICE** [comment]
You could make it less confusing by using a default value as a prefix, but it would still break existing code.

**Comment by Kefta** [comment]
I can guarantee you that current code  wouldn't break over this unless it used the default value to avoid workshop addon parses for RunString calls.

**Comment by TheOldCatcher** [comment]
Hello,Where do i put this code in though?

**Comment by Kefta** [comment]
Run it shared

**Comment by TheOldCatcher** [comment]
XD I am noob at this, so what file do i goto to run it in shared?

**Comment by Kefta** [comment]
lua/autorun/somenewfile.lua
