### ISSUE TITLE
Add CS:S Player Animation Enums

### ISSUE THREAD

**Issue by ghost** [Facepunch/garrysmod-requests#1095]
These are easy to find by decompiling the models and/or checking the Source 2007 code. It'd be super neat if we could add these to the Enum list so people could use the actual player models/animations from CS:S in their gamemodes.

**Comment by Kefta** [comment]
You can add these yourself in Lua. GMod will probably never support them by default.

**Comment by robotboy655** [comment]
If you mean ACT_ enums, https://wiki.facepunch.com/gmod/util.GetActivityIDByName this should fulfill this request.
