### ISSUE TITLE
Improve npcs nodes

### ISSUE THREAD

**Issue by Combine900** [Facepunch/garrysmod-requests#1098]
If its possible improve the npc nodes for garrysmod as for the flying npcs there is no way to make them move around with the hammer nodes.. i saw that construct make it possible somehow but it doesnt work on own maps so what about improve it so that you can use new flags etc in hammer on the info_node_air and info_node_air_hint nodes that can make them able to fly without any heavy lua script?

**Comment by DanilaFoxPro** [comment]
Depends on the NPC's type.

- Birds and scanners use info_node_air, plus birds will fly away to the nearest info_node_air_hint with the type "Crow: Fly to point". 

- Striders use info_node_air_hint too, but with a "Strider node" type.

- Helicopters use info_node_air and can use path_track, gunships use only path_track.

If you want player spawned gunships to fly on your map -- just create a giant trigger with gunship filter that will set gunship's path_track. For any other flying NPCs -- use info_node_air.
