### ISSUE TITLE
Official ammo limit implemented

### ISSUE THREAD

**Issue by BreakinBenny** [Facepunch/garrysmod-requests#1100]
It's probably just me, but I believe the ammo limit being uncapped without using add-ons is a little insane. I feel like we miss the limit built into Half-Life 2 and its various games, though they all use sk_max_%weaponammo% which are probably clientside.

If you add it, be sure to make it disabled by default!

**Comment by robotboy655** [comment]
If we disable something by default, what's the point of adding it? The ammo limit is capped at 9999.

**Comment by BreakinBenny** [comment]
It's mainly for convenience reasons, or proper roleplaying (take that what you will, though). The HL2 limits should be the default, but the admin should also be able to change it serverside.

Of course, it would be pretty fun to just be able to remove all weapons and ammo with a simple click… and optionally, the HEV suit. (Speaking of HEV suit, would you kindly make the suitvolume command work again? That sound is pretty damn annoying and TV Tropes agrees.)

**Comment by Kefta** [comment]
Could ammo limits at least work for ammo types that declare a max?

**Comment by robotboy655** [comment]
From one side I agree, but from another, do we really want to change this behavior? Mods can (and do) implement their own ammo limits if it is necessary, and changing this might bring unexpected behavior to existing mods. What if a Sandbox user wants to have 9999 ammo, and not be limited by a random value set by a modder when it didn't really affect actual maximum ammo count?

**Comment by Kefta** [comment]
Doing it with mods is still not 100% accurate since it does not affect engine calls to GiveAmmo - if there were a hook for that, I could see it replacing ammo limits.

**Comment by robotboy655** [comment]
If we were to add a hook for ammo count change, when should be called? When it is changed from Lua? What about when weapon reloads? Do we add multiple hook for ammo removal? What arguments/return values should it have? What should happen with RemoveAllAmmo()?

**Comment by Kefta** [comment]
One hook, PlayerChangeAmmo( Player pPlayer, number iAmmoAmount, number iAmmoIndex ), which returns a number for the new amount. nil return means stick with iAmmoAmount's value. iAmmoAmount will be positive for ammo gains and negative for losses.

The hook will be called after the iAmmoIndex check in CBaseCombatCharacter::GiveAmmo (the integer index version), after the iCount check in CBaseCombatCharacter::RemoveAmmo, and for every iteration of CBaseCombatCharacter::RemoveAllAmmo (-m_iAmmo[iAmmoIndex] can be used as the value for iAmmoAmount here, and retNum + m_iAmmo[iAmmoIndex] for the m_iAmmo.Set call).

If the hook returns <= 0 in GiveAmmo or >= 0 in RemoveAmmo, the function returns before m_iAmmo is set or any sounds are played. That should allow for every kind of ammo manipulation in Lua, including infinite ammo and max carry limits.

**Comment by robotboy655** [comment]
RemoveAllAmmo() may lose its functionality in this case is my worry.

**Comment by Kefta** [comment]
I guess RemoveAllAmmo could just skip the hook and just strip all ammo unconditionally.

**Comment by robotboy655** [comment]
I am also not sure how useful delta of ammo would be, I am thinking more towards oldValue, newValue where you can just do``` math.min(newValue,game.GetAmmoMax(type))```

**Comment by Kefta** [comment]
Yeah, that would be a bit more intuitive. I just used the delta since GiveAmmo passes it
