### ISSUE TITLE
prop_static + hammer editor feature

### ISSUE THREAD

**Issue by Combine900** [Facepunch/garrysmod-requests#1102]
Hey could we use a newer prop_static version for garrysmod like that which supports colors etc.. as example csgo l4d2, garrysmods current static doesnt allow that and ye that sux as u cant paint static props.. would help alot at mapping as static props are much more optimized than the rest.

also can about the hammer editor for garrysmod can we add "gmod_allowtools & gmod_allowphysgun" to some entities by default? u always have to put them with smartedit and that ye isnt that good. would safe some time

**Comment by robotboy655** [comment]
That's a no for prop_static. Those features are from a newer version of the Source Engine, which we do not have access to.

As for ```gmod_allowtools``` and ```gmod_allowphysgun```, I have added them to some most used entities into the .fgd files, you will only get this if you use the latest version of the GMod's Hammer Editor.

**Comment by mcNuggets1** [comment]
Sad story.

**Comment by piqey** [comment]
> Those features are from a newer version of the Source Engine, which we do not have access to.

Is this still the case?

**Comment by robotboy655** [comment]
@piqey https://github.com/Facepunch/garrysmod-requests/issues/2293
