### ISSUE TITLE
Implement Place functions for CNavAreas

### ISSUE THREAD

**Issue by maximlahaxim** [Facepunch/garrysmod-requests#1103]
This is absolutely a necessity for AI made with NextBot. Having a CNavArea:Set/GetPlace function would be very, very useful to allow bots to move to certain spots in the map, and prevent having to make large tables that contain every single CNavArea you want to be part of a "place". Can these functions be implemented?

**Comment by robotboy655** [comment]
Already discussed here: https://github.com/Facepunch/garrysmod-requests/issues/624
