### ISSUE TITLE
Add CNavLadder:GetTop/Bottom

### ISSUE THREAD

**Issue by maximlahaxim** [Facepunch/garrysmod-requests#1108]
These are two useful ladder-related functions that are absolutely vital for my bot project to function correctly (and need to be used to determine if a player is on a certain ladder) but haven't been implemented. Adding these would open up a lot of possibilities. For the record, the two variables these functions'd return are "m_top" and "m_bottom" respectively. Can it be done?

**Comment by robotboy655** [comment]
Done.
