### ISSUE TITLE
Allow access to gpGlobals->tickcount

### ISSUE THREAD

**Issue by maximlahaxim** [Facepunch/garrysmod-requests#1110]
This would be useful for making certain things run after skipping X ticks as opposed to setting specific time intervals with floats. Can this be added?

**Comment by robotboy655** [comment]
Count them yourself? http://wiki.garrysmod.com/page/GM/Tick

**Comment by meepen** [comment]
Tickcount is not the same as counting ticks

Use CurTime() / engine.TickInterval() but it will get less accurate over
time

**Comment by meepen** [comment]
besides @maximlahaxim's usecase i think it would be great to have a binding to get the tickcount without the unnecessary division for things like manual lag compensation and prediction.

**Comment by ZehMatt** [comment]
Theres also the case of 
```
local accurateCurTime = engine.TickCount * engine.TickInterval()
```

**Comment by robotboy655** [comment]
Added engine.TickCount()
