### ISSUE TITLE
Add binding for CNavMesh::GetGroundHeight

### ISSUE THREAD

**Issue by maximlahaxim** [Facepunch/garrysmod-requests#1113]
This function is incredibly useful for determining a position that might be below the ground's height. Unfortunately it's a very long and complex function so having to rewrite this in Lua would do us no favours; can we get a C++ binding to increase speed and efficiency?

**Comment by robotboy655** [comment]
Added navmesh.GetGroundHeight( pos ) = float height, Vector normal
