### ISSUE TITLE
Add Lua binding that returns the game's process ID

### ISSUE THREAD

**Issue by marceau-maubert** [Facepunch/garrysmod-requests#1115]
Currently, I need this to get Discord Rich Presence working properly.

Right now the only option is to pick a process ID at random and hope that the user doesn't have multiple Rich Presence applications running, otherwise it keeps saying `Garry's Mod - Just started playing` when you switch between them and the presence takes some time to show up again, if it does at all.

Could be named `game.ProcessID` or something like that.

**Comment by Tenrys** [comment]
The other issue that I did not think of now that I just got a complaint about is the fact that the presence does not clear itself once you quit Garry's Mod, requiring to relaod Discord. That's a bother.

**Comment by devSera** [comment]
This would be useful and could potentially solve the implement discord rpc issue w/ a link pointing to tenry's rpc script

**Comment by yupi2** [comment]
@Tenrys In regards to presence not clearing itself on disconnect, could do something awful like this:
```
hook.Add("ShutDown", "HTTP Tests", function()
	http.Post("http://192.168.0.123:8000/")
	local stop_time = SysTime()+0.5 -- lower me a little
	while SysTime() < stop_time do
		-- just halt everything
	end
end)
```

**Comment by Tenrys** [comment]
I've looked around and there doesn't seem to be a way to stop the presence manually, giving an empty activity is forbidden.

**Comment by Tenrys** [comment]
@yupi2 well, found a way around it https://github.com/discordapp/discord-rpc/issues/164

**Comment by robotboy655** [comment]
Not something I am interested in adding. This only ever useful for custom Discord Rich Presence. https://github.com/Facepunch/garrysmod-requests/issues/1041
