### ISSUE TITLE
Add function to return whether a player is in the process of crouching or not

### ISSUE THREAD

**Issue by maximlahaxim** [Facepunch/garrysmod-requests#1116]
Player:IsCrouching and Player:IsFlagSet( FL_DUCKING ) work fine for their intended purpose, but the problem is, they only return true when the player is FULLY ducked, so when their view has fully shifted, they're fully crouched down, etc. There's a variable that's set internally for each player called "m_Local.m_bDucking" that is true when a player is in the process of ducking. Can we get a function that returns that?

**Comment by Effyxo** [comment]
why not check if the player has the control button down?

**Comment by Kefta** [comment]
There are other scenarios in which they'd be in the process of crouching besides holding the key. Key states are also not networked to other players.

**Comment by Kefta** [comment]
It looks like FL_ANIMDUCKING was added for this, but it doesn't actually work.

**Comment by Kefta** [comment]
https://github.com/Facepunch/garrysmod/pull/1231

**Comment by robotboy655** [comment]
Would adding FL_ANIMDUCKING suffice? It will be set just like it is in CS:S - true from start of the ducking to the start of unducking. Assuming this request is to directly address the PR mentioned above.

I am not sure if the flags are networked.

Or do you still want value of m_Local.m_bDucking, in which case, for what other purpose?

**Comment by maximlahaxim** [comment]
@robotboy655 FL_ANIMDUCKING should do. The reason I wanted m_bDucking was because there're various checks used on CS:S bots with it, though I believe they're both set at the same time, so it doesn't really matter.

**Comment by Kefta** [comment]
What method is the flag set in? The 2007 copy still uses m_Local.m_bDucking.

**Comment by robotboy655** [comment]
It is set in the exact same place as m_bDucking, but it is NOT a direct replacement/mirror to it.

**Comment by Kefta** [comment]
I took a look and it seems FL_ANIMDUCKING is networked in CS:S and meant to be used for animations. m_Local is only networked to the local player (and not at all for NPCs), and is the solution to this PR since it's meant to be used for movement logic.

This might be a huge ask, but could method be added to access and set m_Local variables like the save table?

**Comment by robotboy655** [comment]
I guess I will add FL_ANIMDUCKING and we shall see what comes of it. Feel free to create a separate request for m_Local.

**Comment by Kefta** [comment]
How is https://github.com/Facepunch/garrysmod/pull/1231 included in this? I thought all the activity handling was in Lua

**Comment by ZehMatt** [comment]
This is cool stuff, thank you.
