### ISSUE TITLE
Add Lua bindings to retrieve selected/highlighted text of a TextEntry

### ISSUE THREAD

**Issue by marceau-maubert** [Facepunch/garrysmod-requests#1117]
Currently I'm trying to make my own text entry panel off of the default DTextEntry but I've found no way to know what text is selected in it.

Something like `PANEL:GetSelectedText()` that returns the selection's start and end (and maybe the string of the selected text) would be perfect.

**Comment by robotboy655** [comment]
Added on Dev as `Panel.GetSelectedTextRange()`
