### ISSUE TITLE
Half Life 2 Campaign fixes

### ISSUE THREAD

**Issue by Combine900** [Facepunch/garrysmod-requests#1118]
Could we improve and fix this tons of bugs in the hl2 , ep1, ep2 campaign? there are so many animation issues missing sounds scripts and stuff...

**Comment by robotboy655** [comment]
This report is too vague, also in the wrong repo. There are already reports for many if not all of the problems.

**Comment by robotboy655** [comment]
There shouldn't be problems with soundscripts or soundscapes.
