### ISSUE TITLE
Allow a table of entity classes to be passed as a trace filter

### ISSUE THREAD

**Issue by ghost** [Facepunch/garrysmod-requests#1126]
Currently, the only method of making traces that don’t hit certain classes is passing a function that checks the given entity’s class, which is infamously slow. Allowing a table of entity classes that you want the trace to not hit to be passed for a filter should be a lot faster and accomplish the same thing.

**Comment by yupi2** [comment]
http://wiki.garrysmod.com/page/Structures/Trace
Pretty sure that's already a thing: `Things the trace should not hit. Can also be a table of entities or a function with one argument:`

**Comment by robotboy655** [comment]
```or a function with one argument```

You can already implement custom rules

**Comment by robotboy655** [comment]
http://wiki.garrysmod.com/page/util/TraceLine

Even has an example ith class nmes

**Comment by thegrb93** [comment]
He wants it C-implemented. He even says, "Currently, the only method of making traces that don’t hit certain classes is passing a function that checks the given entity’s class, which is infamously slow.".

I don't think adding custom filters like that is viable though. Try creating an array of entities of that class and use that as your filter.

**Comment by Kefta** [comment]
Doing FindByClass/GetAll iterations is still slow, especially when multiple classes are involved. The ideal solution would be to allow string arguments (in a table or not) that represent entity classes as a filter value.

**Comment by robotboy655** [comment]
Done.
