### ISSUE TITLE
Add PlayerChangeAmmo hook

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#1131]
As discussed in https://github.com/Facepunch/garrysmod-requests/issues/1100 for implementing max carry in Lua and to detect ammo changes. Some hook should be called for RemoveAllAmmo for the latter purpose, even if you can't override its value.

**Comment by Tr4ckster** [comment]
Either RemoveAllAmmo, or a hook when ammo changes in generell. Even one bullet less. 
(also might be a good idea to have 2 hooks then, one for loosing ammo, and one for getting ammo)

**Comment by robotboy655** [comment]
Added GM:PlayerAmmoChanged( ply, index, old, new )

It is shared and it is read only, as we now have gmod_maxammo for all your "maxcarry" needs.
Trying to set ammo from this hook will predictably result in an infinite loop.

**Comment by Kefta** [comment]
Can we return to block the change?

**Comment by robotboy655** [comment]
Why? That feels like asking for trouble, when I call RemoveAmmo, I want it gone, not stay the same due to some crappy addon.

**Comment by Kefta** [comment]
For per-ammo type max carry systems since gmod_maxammo applies globally and the ``maxcarry`` key does nothing. I suppose SetAmmo could be called inside the hook with a recursion guard, but it seems awfully inefficient to call all PlayerAmmoChanged hooks every time the ammo needs to be capped.

The best solution would be to have the ammo limits actually respond to the ``maxcarry`` key when its specified for the ammo type.

**Comment by robotboy655** [comment]
Please kindly read the many descriptions of `gmod_maxammo`.

**Comment by Kefta** [comment]
Thank you.
