### ISSUE TITLE
Add a hook for when engine commands are ran

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-requests#1135]
There currently is no hook to check for engine commands being ran.

**Comment by Kefta** [comment]
Or Lua commands for that matter without overriding concommand.Run.

**Comment by Kefta** [comment]
Can be called right in [ConCommand::Dispatch ](https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/src_main/tier1/convar.cpp#L567)- adding a PreCalledConCommand for blocking concommands from being ran on the server or client would be useful too. Would allow https://github.com/Facepunch/garrysmod-requests/issues/1034 to be fulfilled in Lua, leading to serverside management of the number of people talking and slightly more efficient PlayerCanHearPlayersVoice hooks.

**Comment by robotboy655** [comment]
More complete discussion in https://github.com/Facepunch/garrysmod-requests/issues/1135
