### ISSUE TITLE
Add HL2 damage enums

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#1137]
DMG_SNIPER and DMG_MISSILEDEFENSE in shared/hl2/hl2_shareddefs.h.

DMG_SNIPER is used by the SniperRound and SniperPenetratedRound ammo types, and DMG_MISSILEDEFENSE is used by npc_missiledefense, npc_combinegunship, and monster_mortar.

**Comment by robotboy655** [comment]
Done
