### ISSUE TITLE
Raise the value of MAX_AMMO_TYPES and MAX_AMMO_SLOTS

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#1138]
128 is still pretty low for servers that use custom weapon packs. Would be best to use a vector/arraylist so that the limit is removed entirely.

**Comment by mcNuggets1** [comment]
It can't harm to raise these in my opinion.

**Comment by NathanX-S** [comment]
Bump.

**Comment by robotboy655** [comment]
It cannot be removed because ammo counts still need to be networked. Changing this will also require breaking network compatibility.

**Comment by VaasKahnGrim** [comment]
could probably get around it by reimplementing ammo stuff in lua. Its stupid that you'd need to tho but probably alot easier to go about

**Comment by Kefta** [comment]
``It cannot be removed because ammo counts still need to be networked.`` Can you not send the length along with the ammo data? Why does the network payload have to be a static size?

**Comment by robotboy655** [comment]
Normally yeah, but I imagine there's a good reason it is never done like that throughout the engine (or at least I haven't seen anything else done that way), be that for prediction, or for Source's entity networking,

**Comment by Kefta** [comment]
I imagine the reason is purely because of legacy code, the ammodef lib is pretty self-contained and has hardly seen changes since the '03 leak.

**Comment by robotboy655** [comment]
No, I am not talking about ammodef lib, I am talking about any data arrays being sent in an entity's datatable, you know, the ammo counts the player has.

**Comment by Kefta** [comment]
Ah, that would make more sense.

**Comment by robotboy655** [comment]
Doubled.
