### ISSUE TITLE
monster_barnacle changes and fixes

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#1140]
- Apply ai_ignoreplayers fix like npc_barnacle.
- Add EFL_IS_BEING_LIFTED_BY_BARNACLE  flag to enemy when they are picked up. This should fix NPC grabbing behaviour with HL1 barnacles. Should go in the BCC->DispatchInteraction check.
- Don't allow players to be grabbed by a barnacle in a vehicle, or adjust it to act like HL2 - it causes an invalid state where the barnacle is pulling but the player will not move.
- The MOVETYPE_FLY setting for enemies should really be refactored to a constraint like the HL2 barnacle does. It allows players to fly around with HL2DM movement, and can cause players to be stuck with that movetype under specific conditions.

**Comment by Kefta** [comment]
Video of the movement issues here: https://www.youtube.com/watch?v=cpofWYw9avo

**Comment by Kefta** [comment]
https://github.com/ValveSoftware/Source-1-Games/issues/1272 is also an issue.

**Comment by robotboy655** [comment]
Resolved most of these issues.
