### ISSUE TITLE
Add $treeSway support

### ISSUE THREAD

**Issue by WinterPhoenix96** [Facepunch/garrysmod-requests#1146]
Recently, env_wind was fixed. This got me thinking about [$treeSway](https://developer.valvesoftware.com/wiki/$treeSway), a wonderful Source Engine feature that can perform what looks like vertex manipulation, without basically any of the performance impact.

Seeing as that sort of tech could be used in a whole bunch of different ways in GMod, I'd like to make a request for it.

Some potential use case examples here: https://www.youtube.com/watch?v=TTxzH2nl-U0

It should be possible, considering that Alien Swarm's entire Source Code is included in [its SDK](https://developer.valvesoftware.com/wiki/Alien_Swarm_SDK), and that, according to Valve's Developer Wiki...
![Alien Swarm Support](https://winteris.moe/share/2018-05-23_01-43-39.png)

Thank you for your consideration!

**Comment by Nak2** [comment]
This would greatly improve maps and content for servers. Including bringing some life into some of the flat life-less hl2 maps.
+1

**Comment by robotboy655** [comment]
If you must have an answer, if won't be added soon, but it does sound like something interesting. I'd need to find sources for it too, and find information on how to actually compile source shaders

**Comment by neico** [comment]
I guess [this](https://developer.valvesoftware.com/wiki/Source_SDK_2013:_Shader_Authoring) and [this](https://github.com/NicolasDe/AlienSwarm/search?q=treesway&unscoped_q=treesway) might give you a head-start

**Comment by robotboy655** [comment]
![chair](https://user-images.githubusercontent.com/3299036/41087796-4b5378c6-6a46-11e8-927a-fdf1eddec7b3.gif)

Goddamn this took forever to compile.

This is obviously only for VertexLitGeneric (unlit may also work) and only with cl_tree_sway_dir for now.

env_wind support will be added closer to when the update releases, as that requires networking changes and I don't want to break the compatibility with live servers yet.

**Comment by Kefta** [comment]
Legendary

**Comment by Stiffy360** [comment]
It doesn't appear to work with unlitgeneric. In the future would it be possible to add to it?
