### ISSUE TITLE
Add sk_*_dmg_crowbar and sk_*_dmg_stunstick convars

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#1150]
Just like the HL2 versions, their value should be used in ``GetDamageForActivity``.

**Comment by robotboy655** [comment]
Not sure what to do about pvp damage, or whether the convars for other weps even do anything.

**Comment by Kefta** [comment]
What about PVP exactly? The convars are for determining damage by owner, not by target.

**Comment by robotboy655** [comment]
In HL2DM, pvp damage for stunstick is 40, for crowbar its 25.

With this change, pvp damage for stunstick will be 10, and for crowbar it will also be 10.
PLRvNPC and NPCvNPC damage doesn't bother me.

**Comment by Kefta** [comment]
Oh, I see what you mean. Perhaps you could only use the convars' value when the target is a non-player? Otherwise, fallback to the current damage. This would require you to go outside of GetDamageForActivity for the trace tho

**Comment by Kefta** [comment]
Any chance this could be done? It's been more than a year for a relatively simple fix, and the convars still show as non-existent in the startup log. Let me know if you want a code example of how to implement this.

**Comment by robotboy655** [comment]
Solves https://github.com/Facepunch/garrysmod/pull/1618

Since all other weapons are already at NPC damage anyway, making these 2 the same. And you can set the damage to HL2DM values with the convars if you so desire.
