### ISSUE TITLE
Add missing HL1 convars

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#1151]
These convars link to existing NPCs in-game but are missing.
- sk_islave_health
- sk_bullsquid_dmg_spit
- sk_hgrunt_health
- sk_hgrunt_kick
- sk_hgrunt_pellets
- sk_hgrunt_gspeed
- sk_snark_health
- sk_snark_dmg_bite
- sk_snark_dmg_pop
- sk_agrunt_health
- sk_agrunt_dmg_punch
- sk_bigmomma_health_factor
- sk_bigmomma_dmg_slash
- sk_bigmomma_dmg_blast
- sk_bigmomma_radius_blast
- sk_scientist_health
- sk_scientist_heal

**Comment by robotboy655** [comment]
Done
