### ISSUE TITLE
Will there be any improvements on version 21 maps?

### ISSUE THREAD

**Issue by Disposition0** [Facepunch/garrysmod-requests#1153]
Is there any plans to further improve compatibility on version 21 maps? I know it is not a simple task to backport these features so it's not really a request, but is it planned to keep it how it is?

**Comment by Kefta** [comment]
Could you list out what problems there are?

**Comment by Disposition0** [comment]
I've just realized how much of a problem trying to make vscript work in Garry's Mod is so im just gonna close, will move the rest of these to the issues page
