### ISSUE TITLE
Create function CBasePlayer::Get/SetUseContents

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#1155]
A simple function that would set a player variable to alter which CONTENTS_* to use for ``CBasePlayer::FindUseEntity``. [It's currently hardcoded](https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/se2007/game/shared/baseplayer_shared.cpp#L965), resulting in a [hacky fix](https://github.com/Facepunch/garrysmod/blob/master/garrysmod/gamemodes/base/gamemode/player_shd.lua#L109-L116) for HL1 maps. A function to directly change which contents to use for each player would be a more flexible solution. Alternatively, a hook (something like ``GM:GetUseMask``) would work, as well.

**Comment by robotboy655** [comment]
And how is the existing hook and the "hacky fix" not enough?

**Comment by robotboy655** [comment]
The point of the hacky fix is to not override the default mask

**Comment by Kefta** [comment]
The fix doesn't encapsulate FindUseEntity's behaviour of radial searching and just does a simple TraceLine. That's fine for a simple base-gamemode fix for HL1 campaign maps, but replicating exact use-behaviour for CS:S and HL1-styled gamemodes still requires a complete rewrite of ``CBasePlayer::FindUseEntity`` into ``GM:FindUseEntity``. So yes, it is possible, but it's a lot of extra code that could be removed with the addition of the requested function.

**Comment by Kefta** [comment]
I guess there are some other settings that would require a rewrite anyway.
