### ISSUE TITLE
Get ragdoll spawned by hl2mp_ragdoll to update origin and angles

### ISSUE THREAD

**Issue by DreamsOfCyanide** [Facepunch/garrysmod-requests#1157]
A ragdoll spawned by a spawned hl2mp_ragdoll can't update to the given network origin/angles in lua, causing the ragdoll itself to always spawn at the origin of the map.
Video: https://www.youtube.com/watch?v=Q1Tj31IBPx4&feature=youtu.be

**Comment by Kefta** [comment]
(To the devs)
I posted some information [here](https://forum.facepunch.com/f/gmoddev/bsyjp/Getting-hl2mp-ragdoll-s-position-and-angle/1/#postcvkeca) on why updating the position/angles is impossible from Lua. Some possible solutions:
- Update the ragdoll object's position and angles on NetworkOrigin/NetworkAngles data update.
- Add m_hPlayer to the savetable so it can be set from Lua. Setting this manually will bypass m_hRagdoll being set on the player, causing it to never be removed automatically.

**Comment by Kefta** [comment]
Why was this closed?
