### ISSUE TITLE
Proposal for adding functions to repeatedly focused GMODs briefly pointed out.

### ISSUE THREAD

**Issue by IssacKleiner** [Facepunch/garrysmod-requests#1161]
I want you to be able to change the closed caption language with the current version of GMOD. (At the same time, multilingual support on Steam's property tab) Please also make NPC behavior and behavior the same as Half-Life 2.

**Comment by robotboy655** [comment]
Added close captions for all languages supported by Half-Life 2 games. You can change the language with `cc_lang`.
