### ISSUE TITLE
Rich presence for Steam chat beta

### ISSUE THREAD

**Issue by Yashirmare** [Facepunch/garrysmod-requests#1164]
Seeing as the new steam chat beta has access to things like rich presence it would be nice to have it up and running before it goes into full release. (sooner rather than later seeing as there is currently no easy way to join a friends game without it)

**Comment by robotboy655** [comment]
The last Steam SDK update was in January, so I don't think there's anything we can do with the new Steam Chat stuff just yet.

**Comment by Yashirmare** [comment]
The current workaround I've found for it is to just right click their avatar from the game page in the library. Odd that the steamworks API hasn't been updated as the webpage with all the info about the beta says games can now use it to add rich presence.

**Comment by robotboy655** [comment]
Added basic support for this to Dev branch. As far as I can tell joining friends from friends list does work properly.
