### ISSUE TITLE
PhysObj:GetPositionMatrix

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-requests#1166]
Returns a lua VMatrix containing the physobj's angle and position.

**Comment by thegrb93** [comment]
https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/public/vphysics_interface.h#L771

**Comment by Kefta** [comment]
Out of curiosity, what do you need this for?

**Comment by thegrb93** [comment]
Calculating the rotation axis between a target rotation and the entity's current rotation.

https://github.com/thegrb93/MyStarfallScripts/blob/master/CriticalPD.txt#L59

**Comment by robotboy655** [comment]
Why can't you just use GetPos() and GetAngles() they are exactly the same thing, derived from the matrix.

**Comment by Kefta** [comment]
I would imagine it'd be much slower to manually build the matrix, especially if it's something being done every frame.

**Comment by robotboy655** [comment]
Added

**Comment by Kefta** [comment]
Should add the SetPositionMatrix too
