### ISSUE TITLE
Adding back combine soldier's pain sounds

### ISSUE THREAD

**Issue by Akis-02** [Facepunch/garrysmod-requests#1167]
tittle explains it all, is kinda boring that the combine doesnt have pain sounds and i found a way to add them back (i didnt find the original fix all credits go to shiron for making this guide https://steamcommunity.com/app/220/discussions/0/353916184343324908/?ctp=3 and explaining how to add the pain sound back )
in the npc_combine.cpp:
line 2568
change: void CNPC_Combine::PainSound ( void )  to  void CNPC_Combine::PainSound ( const CTakeDamageInfo &info )
and npc_combine.h:
line 129
change: 	void			PainSound( void );  to 	void			PainSound( const CTakeDamageInfo &info );

**Comment by Combine900** [comment]
agree

**Comment by robotboy655** [comment]
Done.
