### ISSUE TITLE
HL:S Apache helicopter and Mega gravity gun

### ISSUE THREAD

**Issue by blablablablablablablablabla** [Facepunch/garrysmod-requests#117]
I would like the NPC from Half Life Source named monster_apache added to the game, by default the Apache is missing from GMOD. Also, if i had a chance to fit in one more request, i would like the Mega Gravity-Gun ( physcannon_mega_enabled 1 ) from HL2 into the game.

**Comment by robotboy655** [comment]
Duplicate of #91
