### ISSUE TITLE
Additional support for Weapons, NPCs, Entities, and Vehicles

### ISSUE THREAD

**Issue by KirbyJoe** [Facepunch/garrysmod-requests#1174]
When I installed many Source engine-based games (Half-Life: Source, Half-Life 2 [with Episode One and Two], Portal, Portal 2), I feel something is missing during the gameplay. For example, when I played a Portal map, the entities from the game is missing. I want to add an additional support for Weapons, NPCs, Entities, and Vehicles from other games in the following list:

- Half-Life: Source (currently NPCs only, add Weapons, Entities, and Vehicles)
- Portal (add Weapons, NPCs, Entities, and Vehicles)
- Portal 2 (add Weapons, NPCs, Entities, and Vehicles)
- Team Fortress 2 (add Weapons, NPCs, Entities, and Vehicles)

I wrote all things to add (Weapons, NPCs, Entities, and Vehicles) but some of them maybe doesn't have any Vehicles.

Please note (for devs) that when you try to add HL1:S weapons, some weapons are may confusing between HL2 and that. When you add the HL1:S weapons, Add "HL1" for both Spawnmenu and HUD for the weapons that are confusing. Do your best, devs!

**Comment by robotboy655** [comment]
No. Portal and Team Fortress 2 entities will most definitely not be added. There is already a request for Half Life Source entities.
