### ISSUE TITLE
Bind C_BaseEntity::AddDecal and C_BaseEntity::RemoveAllDecals

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#1179]
These allow decals to be applied to or removed from the model directly, saving them to the model instance for use with [Entity:SnatchModelInstance()](http://wiki.garrysmod.com/page/Entity/SnatchModelInstance). util.Decal* does not apply decals to the model instance.

**Comment by Kefta** [comment]
Just to note, there are a few roadblocks in the way of functionally matching util.DecalEx, including missing w/h arguments, inability to specify an IMaterial, and no args for selecting the axis and flags for brush decals. I have written some example code on how to overcome these:
https://gist.github.com/Kefta/045c3b839aac8aaae88f9bcb3494c9f6

**Comment by robotboy655** [comment]
`C_BaseEntity::RemoveAllDecals` is already https://wiki.facepunch.com/gmod/Entity:RemoveAllDecals
and
`C_BaseEntity::AddDecal` is already https://wiki.facepunch.com/gmod/util.DecalEx (yes, it does apply the decal to the model instance, if given a model entity)

??

**Comment by Kefta** [comment]
Didn't notice those were added, thanks.
