### ISSUE TITLE
Vehiclescript Edit

### ISSUE THREAD

**Issue by CaMoTraX** [Facepunch/garrysmod-requests#118]
It would be awesome if you make a function to edit the vehiclescript of cars via GLua,
like its done in gmsv_pimpmyride.dll. Unfortunately the pimpmyride module isnt compatible for linux anymore, and i need it for my mod. Please add a function :(

http://gmodmodules.googlecode.com/svn/trunk/gm_pimpmyride/

**Comment by robotboy655** [comment]
#453
