### ISSUE TITLE
Add ENTITY:DoImpactEffects

### ISSUE THREAD

**Issue by Earu** [Facepunch/garrysmod-requests#1180]
Currently only SWEPs can do that see (http://wiki.garrysmod.com/page/WEAPON/DoImpactEffect), however any entity can use the FireBullets method (http://wiki.garrysmod.com/page/Entity/FireBullets).
If you're trying to make a vehicle like me, your entity is a SENT and not a SWEP so you cannot actually change the impact effect at all, at least not in a way that doesnt involve hacks. This really seems like an inconsistency to me.

**Comment by robotboy655** [comment]
Added the hook for ANIM entities.
