### ISSUE TITLE
Don't call PlayerCanHearPlayersVoice unless speaker is speaking

### ISSUE THREAD

**Issue by cannon** [Facepunch/garrysmod-requests#1184]
This is an expensive hook because it is called for every pair of players regardless of if they're speaking.

Also, make IsSpeaking accessible serverside please

**Comment by besenyei** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/1087

**Comment by robotboy655** [comment]
Neither are possible without reworking the voice chat system as far as I can tell, the server has no information on whether a player is speaking or not,

**Comment by Kefta** [comment]
Could you not hook into +voicerecord?

**Comment by robotboy655** [comment]
Perhaps I could, but not going to look into that for now.

I guess this is a duplicate of #1087.

**Comment by mcNuggets1** [comment]
If you ever look into it, consider a new voice codec :d
