### ISSUE TITLE
func_precipitation

### ISSUE THREAD

**Issue by Combine900** [Facepunch/garrysmod-requests#1188]
func_precipitation creates rain, snow etc on your map however is it possible to add these values to garrysmod? or can we already use them?

"maxSpeed", "minSpeed" and "origin"

**Comment by Kefta** [comment]
https://github.com/Facepunch/garrysmod-requests/issues/809

**Comment by Combine900** [comment]
aww right forgot that :/ thanks anyway (i hope gmod get a source 2 upgrade someday)
