### ISSUE TITLE
Add back missing SFX captions

### ISSUE THREAD

**Issue by DreamsOfCyanide** [Facepunch/garrysmod-requests#1191]
While voiceovers work as intended, most SFX captions do not (Weapons, certain NPCs, etc.)
I don't know what the exact reason for this is but I believe it's been broken since GMod 12. What's strange is that certain captions tagged with sfx work fine such as [Antlion Guard Confused], while others don't appear at all such as [Crowbar Swoosh].

**Comment by robotboy655** [comment]
I didn't put in any close captions, only the dialog subtitles, as I don't see why'd need [Crowbar Swoosh] tbh.

**Comment by DreamsOfCyanide** [comment]
And I doubt you'll add them in unless there's a popular demand for them?

**Comment by Kefta** [comment]
I am deaf and would very much like to see when crowbar swooshes happen.

**Comment by DreamsOfCyanide** [comment]
too bad then

**Comment by ATP-Kraken** [comment]
There's also the issue of many scripted things referencing the sound raws, instead of the scripted sound effect, which makes it impossible to subtitle them, unless you manipulate the filename and place it there.

**Comment by robotboy655** [comment]
Apparently the issue was with CC just being commented out in code, I have restored it, lets see if anything fucks up.
