### ISSUE TITLE
Enhance armor system

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-requests#1192]
It should be possible to set max armor. Unfortunately it is not.

There should be some sort of damage handling either:
* A damage enum for not loosing armor, but health is needed
* A hook for determing the reduction of armor on health loss

**Comment by Kefta** [comment]
Just making the armour system less hardcoded in general would prevent a lot of useless HUD code rewrites.

**Comment by dedady157** [comment]
my suggestions would be:
copy the damn health system over, ;C 
Move the Number from a Byte to a UInt16 (so we can have more armor than just 255)
Add in Set-Get-MaxArmor

for an advanced feature add in an armor rating system, IE a single var that says how much dmg the armor blocks.
IE setting it to 0.4 will make the player take 60% of the damage to health.

add a hook for 'OnArmorBreak' when the armor amount hits 0, this can be used to play a sound or do something else.

**Comment by Kefta** [comment]
https://github.com/Facepunch/garrysmod-requests/issues/153

Maybe an OnArmorChanged hook would be better than OnArmorBreak.

**Comment by robotboy655** [comment]
Added `GM:HandlePlayerArmorReduction( ply, dmginfo )` with default implementation moved to Lua (base gamemode).

This should allow you to do whatever you want with the armor system - disable it, change values, add "damage enum for not losing armor" or whatever else you might want.
