### ISSUE TITLE
Enable func_door filters

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#1197]
[Currently restricted to HL1 only](https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/se2007/game/server/doors.cpp#L53-L56), door filters can specify additional entities that cause a door to rise up other than players. This would fix specific door keyvalues in HL1 maps, as well.

**Comment by robotboy655** [comment]
Done
