### ISSUE TITLE
Request Addons Loadouts

### ISSUE THREAD

**Issue by zaKa114** [Facepunch/garrysmod-requests#1199]
This function can make loadouts for addons and name it like weapon loadouts and you can enable and disable it. It easy when you want to play other gamemode like If you want to play Darkrp then select Darkrp Loadout If you want Sandbox then select Sandbox Loadout. (I'm not sure you can understand my english, but I tried my best.)

**Comment by mattlcoud** [comment]
Bump

**Comment by robotboy655** [comment]
This was fulfilled.
