### ISSUE TITLE
Alien Swarm Additions

### ISSUE THREAD

**Issue by CaskoChan** [Facepunch/garrysmod-requests#1201]
### fog volume 
 -Fog volume https://github.com/NicolasDe/AlienSwarm/blob/master/src/game/server/fogvolume.cpp

### Tonemap
Flags
1: Master (Has priority if multiple env_tonemap_controllers exist) (New with Left 4 Dead)

SetBloomExponent  <float> (New with Left 4 Dead)
Sets a custom bloom exponent.
SetBloomSaturation  <float> (New with Left 4 Dead)
Sets a custom bloom saturation.

## env_fire

256: No sound (New with Alien Swarm)
512: No ignite sound (New with Alien Swarm)
1024: No fueling once lit (New with Alien Swarm)
2048: Fast burn think (New with Alien Swarm)

Light Color (LightColor) <color255> (New with Alien Swarm)
Color of dynamic light for this fire.
Light Radius Scale (LightRadiusScale) <float> (New with Alien Swarm)
Multiplier for the glow radius.
Light Brightness (LightBrightness) <integer> (New with Alien Swarm)
Integer exponent for the glow brightness.
Loop sound (LoopSound) <sound> (New with Alien Swarm)
Looping sound to play while this fire is burning.
Ignite sound (IgniteSound) <sound> (New with Alien Swarm)
One shot sound to play when the fire starts.

## Fog controller

HDR Color Scale (HDRColorScale) <float> (New with Left 4 Dead)
Multiplier for fog color when in HDR mode.

SetMaxDensityLerpTo  <float> (New with Left 4 Dead)
Stores a value for Fog Max Density that is set once the StartFogTransition input fires. This one does not have any non-"LerpTo" counterpart.

## projected texture

2: Always Update (moving light) (New with Alien Swarm)

Simple Projection (simpleprojection) <boolean> (New with Alien Swarm) !FGD
Indicates if this is a simple, non-light casting texture projection.
Simple Projection Size (projection_size) <float> (New with Alien Swarm) !FGD
To do: add description
Simple Projection Rotation (projection_rotation) <float> (New with Alien Swarm) !FGD
To do: add description
Brightness Scale (brightnessscale) <float> (New with Alien Swarm)
Scale the light color by this brightness.
Color Transition Time (colortransitiontime) <float> (New with Alien Swarm)
Amount of time it takes for a color change to occur. Higher numbers cause faster transitions.

Input
AlwaysUpdateOn  (New with Alien Swarm)
Turn on per frame updating (for moving lights).
AlwaysUpdateOff  (New with Alien Swarm)
Turn off per frame updating (for moving lights).
LightColor  <color255> (New with Alien Swarm)
Change the Light Color.

~~point spotlight
ForceUpdate  (New with Alien Swarm)
Force an update of the spotlight position and orientation.~~

Other requests related to Alien Swarm
https://github.com/Facepunch/garrysmod-requests/issues/1195
https://github.com/Facepunch/garrysmod-requests/issues/1162
https://github.com/Facepunch/garrysmod-requests/issues/1282
https://github.com/Facepunch/garrysmod-requests/issues/1302

**Comment by CaskoChan** [comment]
I updated the info and requests

**Comment by CaskoChan** [comment]
I updated it again

**Comment by CaskoChan** [comment]
@robotboy655 Will you be able to add some of these entities i suggested?

**Comment by CaskoChan** [comment]
I hope this will be looked at one of these days

**Comment by robotboy655** [comment]
Added point_spotlight features from Alien Swarm - SetColor and ForceUpdate inputs
Added info_target features from Alien Swarm - Spawnflag 2 - always transmit

**Comment by robotboy655** [comment]
beam_spotlight was added
prop_door_rotating and prop_dynamic changes from CS:GO branch are also implemented
More info in the July 2019 blogpost (when it is released)

**Comment by CaskoChan** [comment]
Perfect, many thanks for your hard work Rubat!

**Comment by robotboy655** [comment]
func_button got a new spawnflag - non solid (16384)

**Comment by CaskoChan** [comment]
Excellent work Rubat, what's on your list for porting newer features to Garry's mod?

**Comment by Cthutq295** [comment]
Will fog_volume be added ?
