### ISSUE TITLE
Make util.(De)Compress return an empty string when sent an empty string

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#1203]
The functions currently return nil (Compress) or no value (Decompress) when sent an empty string. That means any function that compresses some arbitrary string has to do extra inline value guards to prevent nil from floating around, which isn't commonly done from the code I've seen, meaning it will throw unexpected errors if an empty string is ever sent in. If an empty string was returned, instead, the function could be properly used inline. Ex.

```
local data = util.Compress(SomeString) or ""
net.WriteData(data, #data)
```

versus

```
local data = util.Compress(SomeString)
net.WriteData(data, #data)
```

This exact fix was made for util.Base64Encode in https://github.com/Facepunch/garrysmod-issues/issues/3450.

**Comment by Kefta** [comment]
Can you still type check the first argument instead of allowing no value? It will allow code like this to pass by without error:

```
local SomeCompressedString = util.Compress("foo")

-- Code

print(util.Decompress(SomeCompresedString)) -- Notice the misspelling
```

**Comment by robotboy655** [comment]
Done
