### ISSUE TITLE
Add Entity:GetPoseParameterID(string PoseName)

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#1205]
The opposite of Entity:GetPoseParameterName(number ID). My personal use case is retrieving pose parameter ranges for pose names with GetPoseParameterRange, which only takes IDs.

**Comment by robotboy655** [comment]
Honestly `GetPoseParameterRange` should've just taken the names and converted to IDs internally like Set/GetPoseParameter do.

Gonna add this either way as `Entity.LookupPoseParameter()` so you can easily and clearly test if a model has a given pose parameter or not.
