### ISSUE TITLE
Add a gmod.GetVersion function

### ISSUE THREAD

**Issue by Lexicality** [Facepunch/garrysmod-requests#1206]
A function that returns the output of the `version` concommand would be very handy.
```
] version
Protocol version 24
Exe version 18.02.07 (garrysmod)
Exe build: 15:14:47 May 22 2018 (7136) (4000)
```

**Comment by robotboy655** [comment]
What does this give you that VERSION and VERSIONSTR doesn't give you?

**Comment by bigdogmat** [comment]
They're already on the wiki [here](http://wiki.garrysmod.com/page/Global_Variables).
