### ISSUE TITLE
Bring back IMaterial:SetShader or make a function to override brush material

### ISSUE THREAD

**Issue by somethingwild** [Facepunch/garrysmod-requests#1210]
I wanted to play around with changing brush materials in real-time in GMod, however, when I looked at Garry's Mod Wiki, I found out that the majority of functions / alternatives were either broken, deprecated, or non-existent. 

What I wanted was to re-render world geometry using a different material / shader and nothing more. 

So please, bring back IMaterial:SetShader or add a function that would be able to override brush material.

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/3591#issuecomment-418664899 ?

**Comment by somethingwild** [comment]
I guess this can  now be marked as closed.
