### ISSUE TITLE
Add search and name sorting to the gamemode browser

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#1211]
Search box to be put in the same place as the server menu.
![](https://i.imgur.com/zVh6AgH.png)
![](https://i.imgur.com/f3cdQ4M.png)

**Comment by robotboy655** [comment]
Added in https://github.com/Facepunch/garrysmod/commit/2d5111556fb1c4833e09dbceb7d38997557a1f40
