### ISSUE TITLE
Entity:RemoveInternalConstraints/ConstraintNum (code provided)

### ISSUE THREAD

**Issue by Ramalayha** [Facepunch/garrysmod-requests#1217]
[Code](https://pastebin.com/YEnA2Nqf)

Removes all/some of the internal constraints of a ragdoll.

([Entity:EnableConstraints](http://wiki.garrysmod.com/page/Entity/EnableConstraints) does nothing btw)

**Comment by robotboy655** [comment]
Made EnableConstraints( false ) delete the constrains (for now)

**Comment by robotboy655** [comment]
Added Entity.RemoveInternalConstraint( num ), if you give it nothing it will remove all
