### ISSUE TITLE
Add the ability to set the render size of a spawnicon 

### ISSUE THREAD

**Issue by aStonedPenguin** [Facepunch/garrysmod-requests#1220]
SpawnIcons [look pretty terrible](https://i.imgur.com/veRPI1c.png) if you want to make them bigger than 64px however they're the easiest and most performant way to display a lot of models.

**Comment by robotboy655** [comment]
Set the spawnicon itself to be the desired size just before rendering, that should work.

**Comment by aStonedPenguin** [comment]
I guess it's a bug then.

Calling `SpawnIcon:RebuildSpawnIcon()` seems to reset it to 64px and spawnicons that are already cached override the icon if you try to make one that's a bigger size.

**Comment by aStonedPenguin** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/3636
