### ISSUE TITLE
Any plans to upgrade to Ultralight?

### ISSUE THREAD

**Issue by LoganDark** [Facepunch/garrysmod-requests#1223]
[Ultralight](https://ultralig.ht/) is basically the newer incarnation of Awesomium (the in-game HTML viewer). Are there any plans to add it to Garry's Mod?

**Comment by thegrb93** [comment]
Chromium was what was being added last I saw. You'd probably need to prove that Ultralight has all the features chromium has and is easier to add in order for anyone to look into it.

**Comment by thegrb93** [comment]
Yeah, I mean someone would have to determine its usefulness. Seeing that it's advertised as super light, I think it might be missing a lot of features that people want.

**Comment by robotboy655** [comment]
No, and there's the thing:
Both Ultralight and Awesomium are geared more towards building UI (i.e. Discord, Slack, Skype, VS Code, apps like that), not rendering normal websites per se.
And they do work for UI, but that's not what people want in Garry's Mod.
What people want is a browser replacement (mostly to watch YouTube and whatnot in GMod which I will never understand) which Ultralight and Awesomium is not really about.

I can see Ultralight being outdated in terms of its HTML/CSS standard support as time goes on, and that's assuming that they can match Chromium even right now which I'd imagine isn't the case already.
That of course my speculation from the information on the webpage you linked.

**Comment by LoganDark** [comment]
I'm not recommending Ultranight because its support of HTML/CSS is better - I don't know what it is. I'm simply proposing it as the successor to Awesomium because it is.

So, basically what you're saying is that it would be too much to integrate something to replace and/or deprecate something that already serves needs well and is rarely used anyway(?). Which I completely understand.

**Comment by thegrb93** [comment]
He's saying that it doesn't have required features.

**Comment by LoganDark** [comment]
I think Ultralight and Awesomium are pretty much the same in terms of features (in fact Ultralight may have more), but the reasoning doesn't really matter in this case - it was denied.

**Comment by thegrb93** [comment]
Awesomium doesn't have required features either. I think that's why they are going with chromium instead.
