### ISSUE TITLE
Scripted Entities Using Ragdoll Models

### ISSUE THREAD

**Issue by kklouzal** [Facepunch/garrysmod-requests#1229]
Allow scripted entities to use ragdoll models.

For instance, I have a beautiful looking turret model which we have compiled as a ragdoll. It has a tripod with a gun mounted on top. The tripod is stationary (as it should be) and the gun is moved via pose-parameters. We have it compiled as a ragdoll so the entire model can obtain an accurate physics mesh.

![cannon_1](https://user-images.githubusercontent.com/2928845/47524517-aa8a3380-d84f-11e8-9228-11fd414f9a34.png)

As far as I know the only way to get an accurate physics mesh here is to use a ragdoll model.

Currently, calling `SetModel()` on an entity and specifying a ragdoll-model completely screws up the physics. The only alternative here is to use static collisions and throwing a huge cylindar or half-sphere or something around the entire mesh to use for collisions.

Please allow scripted entities to use ragdoll models!

**Comment by thegrb93** [comment]
A ragdoll SENT would require an entirely new scripted SENT implementation I think.

Your best option is to separate the gun and tripod and constraint.AdvBallsocket them.

**Comment by thegrb93** [comment]
Actually no, just have your SENT ents.Create a prop_ragdoll and then control the ragdoll accordingly.

**Comment by robotboy655** [comment]
```Please allow scripted entities to use ragdoll models!```
You can already do that!

What you want isn't physics of prop_ragdoll (visual bones following the physics objects), what you want is prop_dynamic's bone followers (physics objects following visual bones).

And even then, I'd highly recommend going the TF2 way and just use a box for physics, its better for both gameplay and server performance/bandwidth.

If you REALLY must use ragdoll physics, just use prop_ragdoll.

**Comment by robotboy655** [comment]
Added basic support for bone followers on "anim" type SENTs - Entity.CreateBoneFollowers (Call after SetModel, you dont need to init physics), Entity.UpdateBoneFollowers (pmuch call every tick), Entity.DestroyBoneFollowers (All serverside only)

This should allow you to achieve what you wanted to.
