### ISSUE TITLE
Remove permanently displayed heart icon at 'Favourite' maps tag

### ISSUE THREAD

**Issue by ElHyperion** [Facepunch/garrysmod-requests#123]
Whenever you hover over a map in Sandbox or any other tag, a heart appears and you can add it to favourites. And then the icon at it stays (under the tag where it previously was), as it should. But why all maps in Favourites have the hearts on them, even if I don't hover my mouse over the maps? It's a bit obvious that they are favourited already, so no need for the hearts to obscure the beautiful thumbnails I have there ;)

**Comment by robotboy655** [comment]
```But why all maps in Favourites have the hearts on them, even if I don't hover my mouse over the maps? It's a bit obvious that they are favourited already, so no need for the hearts to obscure the beautiful thumbnails I have there ;)```

For consistency with each category.
