### ISSUE TITLE
Add PLAYER.Set/GetWalkSlowSpeed

### ISSUE THREAD

**Issue by WinterPhoenix** [Facepunch/garrysmod-requests#1231]
There's PLAYER.Set/GetWalkSpeed, PLAYER.Set/GetRunSpeed, and even PLAYER.Set/GetCrouchedWalkSpeed, but there is not apparently a way to set/get "Walk Slow" speed.

That is, when players hold ALT, +walk, or otherwise use IN_WALK. Please let me know if I'm just missing something and this function already exists, but I'm fairly certain it doesn't.

**Comment by robotboy655** [comment]
Added in the next update which ships tomorrow.
