### ISSUE TITLE
Increase VBSP Limits

### ISSUE THREAD

**Issue by kklouzal** [Facepunch/garrysmod-requests#1234]
https://developer.valvesoftware.com/wiki/Brush
Limits: 8192 brushes
> 	It is possible to compile a custom build of VBSP with these limits changed or removed, but the engine's behaviour is undefined.

Large, _**well optimized**_, _**well engineered**_, city maps suffer from this seemingly low brush count. I suppose the limits were imposed back when the source 1 engine was released and based around current hardware at that time. Hardware has dramatically improved and given a highly skilled map maker who knows how to properly optimize and engineer his/her map this specific limit seems arbitrarily low.

Someone uneducated in Hammer and how visleafs work to remove non-visible geometry might make a large open cube, as large as the map max size, and fill it with hundreds of buildings. A brush limit of 8192 makes sense in this scenario because it saves our uneducated map maker from completely stressing out the engine.
A highly skilled and educated map maker will properly optimize their map, place area portals, hints, skips, and generally lay the map out so that the player is only rendering an extremely low percentage of the entire map geometry at once thus a limit of 8192 brushes can be frustratingly low.

Please increase this limit, if not directly then add a runtime option to VBSP to allow a user to directly specify their desired brush limit at compile time.

**Comment by kklouzal** [comment]
Or this.. #648 💯

**Comment by kklouzal** [comment]
Or this.. #648

**Comment by robotboy655** [comment]
I have increased the limit to 16k, but be aware, the real limit will be lower because of BSP file format limitations. (MAX_BRUSHSIDES limit)
