### ISSUE TITLE
Add NPC:GetWeapon and GetWeapons

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#1237]
Already exists for players. Currently, the only weapon you can get on NPCs is their active one.

**Comment by meepen** [comment]
Can they actually hold multiple weapons? I haven't played hl2 in forever to
remember any scenes with NPCs with multiple weapons

**Comment by Kefta** [comment]
Yep
```
> pMyNPC = Entity(1):GetEyeTrace().Entity...
> print(pMyNPC:GetActiveWeapon(), pMyNPC:GetClass())...
Weapon [193][weapon_357]	npc_monk
> pNPCWeapon = Entity(193) -- The weapon...
> pMyNPC:Give("weapon_smg1")...
> print(pMyNPC:GetActiveWeapon())...
Weapon [123][weapon_smg1]
> print(pNPCWeapon:GetOwner())...
NPC [180][npc_monk]
```

**Comment by robotboy655** [comment]
Fixed NPC.Give() being able to give the NPC multiple copies of the same weapon, now returns the existing copy
Added NPC.GetWeapons(), NPC.GetWeapon( class ), NPC.SelectWeapon( class/ent )

NPC:PickupWeapon no longer drops the active weapon
