### ISSUE TITLE
Entity:GetBrushSize(i) and Entity:GetBrushAngle(i)

### ISSUE THREAD

**Issue by Nak2** [Facepunch/garrysmod-requests#1241]
Increase the brush support so we can read the brush size and angle
This will be useful, as the current way would require to decompile the map. (See [Jazztronaunts](https://github.com/Foohy/jazztronauts) ).

It would also be nice if you could add a function to read some brush-data. e.g; texture, water .. ect

EDIT: Entity/GetBrushContents(id) 		-> Returns the contents bitflag.

**Comment by robotboy655** [comment]
Shouldn't GetModelBounds already do what you want for size?

Also what would "brush angle" even be?

**Comment by robotboy655** [comment]
Added Entity.GetModelContents

**Comment by Nak2** [comment]
> 
> 
> Shouldn't GetModelBounds already do what you want for size?
> 
> Also what would "brush angle" even be?
I originally thought that Entity/GetBrushPlane would return the brush itself.
However, after reading and creating my BSP parser, I now understand the “Plane” part.

I'm looking for a way to locate the brushes on the map, allowing to detect the body of water and whatnot.

**Comment by robotboy655** [comment]
Water is not an entity so this request already doesn't do what you want it to do.

**Comment by Kefta** [comment]
I think pushing all the brush vectors will solve everyone's problems. I suppose Valve didn't expose this to the modelinfo API publicly since there are already vcollide/IClientRenderable structures for their purposes, but either way, modelinfo->GetBrushModelPlane was only made for [view fulcrum testing](https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/src_main/game/client/c_func_reflective_glass.cpp#L68), not to identify specific dimensions. Considering this will most likely not be the last request for model_t/modelinfo, it be more beneficial to start putting these functions in a common model object (https://github.com/Facepunch/garrysmod-requests/issues/1172).

```
#include "ModelInfo.h"
#include "gl_model_private.h"

LL_FUNCTION(modelinfo_GetBrushVertexes)
{
	LUA->CheckType(1, GarrysMod::Type::ENTITY);
	const double nBrushIndex = LUA->CheckNumber(2);
	
	const CBaseEntity *pEntity = LUA->GetUserType<CBaseEntity>(1, GarrysMod::Type::ENTITY);
	
	if (pEntity == NULL)
	{
		LUA->CreateTable();
		return 1;
	}
	
	const model_t *pModel = pEntity->GetModel();
	
	if (pModel == NULL || modelinfo->GetModelType(pModel) != mod_brush)
	{
		LUA->CreateTable();
		return 1;
	}
	
	// Check limits against the double before casting to prevent overflowing errors
	// with numbers out-of-range of integer bounds
	if (nBrushIndex < 0 || nBrushIndex > modelinfo->GetBrushModelPlaneCount(pModel))
	{
		LUA->CreateTable();
		return 1;
	}
	
	const int iBrushIndex = (int)nBrushIndex;
	const worldbrushdata_t *pBrushData = pModel->brush.pShared;
	SurfaceHandle_t brushID = SurfaceHandleFromIndex(pModel->brush.firstmodelsurface, pBrushData) + iBrushIndex;
	
	int iVerts = MSurf_VertCount(brushID);
	int iCurVert = MSurf_FirstVertIndex(brushID);
	
	// Any reason GMod's Lua API can't specify table sizes?
	lua_createtable(LUA->GetState(), iVerts, 0);
	
	for (int i = 1; i <= iVerts; ++i)
	{
		LUA->PushNumber(i);
		LUA->PushVector(pBrushData->vertexes[pBrushData->vertindices[iCurVert++]].position);
		LUA->SetTable(-3);
	}
	
	return 1;
}
```

**Comment by Nak2** [comment]
> 
> 
> Water is not an entity so this request already doesn't do what you want it to do.
> 
> And you didn't answer my question(s).

I know water is not an entity, that is the reason why I'm asking for a way to return the brush info.

> 
> 
> Considering this will most likely not be the last request for model_t/modelinfo, it'd be more beneficial to start putting these functions in a common model object instead of keeping everything in the entity metatable (#1172).

Exactly. The position, size and content of the map brushes, would be super helpful.

**Comment by Kefta** [comment]
Why label this as invalid when I provided code to fulfil the request? @robotboy655

**Comment by robotboy655** [comment]
Because your code has nothing to do with the original request or anything discussed later?

**Comment by Kefta** [comment]
``i`` is the brush index. It is the second argument of the code I posted. Though GetBrushAngle doesn't make sense, that was from a lack of understanding of how brushes work - the request is still asking for information of how brushes are sized, positioned, and angled, which is what my code fulfills directly and indirectly. Though it doesn't matter now, Willox has already redone all of it.

**Comment by Kefta** [comment]
This was fulfilled by http://wiki.garrysmod.com/page/SurfaceInfo/GetVertices.
