### ISSUE TITLE
Remove LDR support

### ISSUE THREAD

**Issue by B-Xerxes** [Facepunch/garrysmod-requests#1242]
Both CS:GO and Left 4 Dead 2 no longer have support for LDR,
compiling a map with -both requires two lots of lightmaps to be compiled,
one for HDR and LDR,
this can bloat a maps filesize far more than necessary,
a lot of people think HDR can hamper performance but nowadays its impact on fps is so small its negligible.

removing it would help reduce map filesize and with the amount of maps on the workshop that people might want this is something worth considering

**Comment by Kefta** [comment]
Isn't the LDR lightmap already optional in compilation?

**Comment by CaskoChan** [comment]
I think garry's mod still has shaders for dx6-dx8, im assume that no one uses those dx levels nowadays.

**Comment by meepen** [comment]
You'd be wrong.

**Comment by Raox2** [comment]
Ludicrous request, quite frankly.

**Comment by robotboy655** [comment]
I don't think there's any point in removing it, you are not obligated to compile your maps with LDR (```vrad.exe -hdr``` for HDR only compile), even some base game Half-Life 2 maps don't.
