### ISSUE TITLE
Add third parameter 'requester' for Payer:SetFOV

### ISSUE THREAD

**Issue by ZehMatt** [Facepunch/garrysmod-requests#1243]
Currently its not possible to have a different FOV owner other than the player otherwise SetFOV will not function. It would be cool to have the requester as a third parameter and when its nil it will use the player like currently. I need this in order to recreate env_zoom in Lua to add multiplayer support.

**Comment by robotboy655** [comment]
env_zoom should have better multiplayer support since this request was made, but I added the optional argument anyway.
