### ISSUE TITLE
Make MarkupObject metatable accessible

### ISSUE THREAD

**Issue by CaptainPRICE** [Facepunch/garrysmod-requests#1244]
Currently, `MarkupObject` metatable is not accessible:

```lua
] lua_run_cl print(FindMetaTable("MarkupObject") == nil)
true

] lua_run_cl print(debug.getregistry().MarkupObject == nil)
true
```

https://wiki.garrysmod.com/page/Category:MarkupObject
https://wiki.garrysmod.com/page/Enums/TYPE
https://github.com/Facepunch/gmod-module-base/blob/master/include/GarrysMod/Lua/Types.h

**Comment by Kefta** [comment]
MarkupObjects are fully Lua so the last two links are irrelevant.

**Comment by Kefta** [comment]
@robotboy655 This can be closed
