### ISSUE TITLE
Add functions to create proper prop_static and prop_dynamic

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-requests#1248]
Currently you can't create proper prop_static props and proper prop_dynamic props.
I tried recreating one in lua, but lua entities seem to run even worse than a physics prop renderwise.

A way to create/edit hammer objects which cannot be retrieved using ents.Get* would be nice.

**Comment by robotboy655** [comment]
What exactly are you asking for here? prop_static's aren't actually entities, i.e. you can't use CBaseEntity/Lua Entity methods on them. You being able to "see" them from Lua won't get you anything, without also creating methods to manipulate them from scratch. (i.e. duplicating some the Entity.* functions for static props)

You can already create "proper" prop_dynamics.

**Comment by Kefta** [comment]
I was going to request bindings to the static prop manager a while back, but accessing useful data is tricky. Static props are internally stored as ``CStaticProp``s which have a lot of methods in common with ``CBaseEntity``s, but the static prop manager only provides references to them as ``ICollideable``s.

The interfaces are all huge messes and will require some refactoring to be at all useful.
