### ISSUE TITLE
Increase MAX_MAP_DISPINFO like CSGO

### ISSUE THREAD

**Issue by gonzalologorg** [Facepunch/garrysmod-requests#1249]
Today CSGO released a battle royale mod, it map got big, really big.
Right now you can't load this map in Garry's Mod because you will get this error:

https://i.imgur.com/tbKDtxJ.png

I really would love to get that map working since it's pure gold for creating a cool Battle Royale, not only for me, but whoever is playing the update right now it's looking for this

**Comment by Kefta** [comment]
Also, this kind of error shouldn't exit the game. Just eject the player to the main menu if it can't load the map.

**Comment by robotboy655** [comment]
It's not as simple as just increasing that, there's a lot more changed about the map format for that map.

**Comment by gonzalologorg** [comment]
I understand if this doesn't/won't have priority, but was thing change bigger than the one tf2 got with lightmaps updates and such new features like compression? Or something new like bsp v20 to v21

**Comment by robotboy655** [comment]
I don't know what's up fully yet, but they have also changed staticproplump version and something else about displacements. Will try to look into it next week.

**Comment by gonzalologorg** [comment]
Yeah, iirc de_dust2 from csgo made a game change by making almost everything a displacement, valve has something in hand regarding them vs brushes lately

This can always means something awesome for gmod's map future, although this would require new tools right? I wouldn't mind starting to build with csgo sdk

Thanks for taking your time and no pressures at all

**Comment by CaskoChan** [comment]
Rubat, isn't valve supposed to let you guys see the csgo source code, since you paid for the license?

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/49699474-78078080-fbda-11e8-9f80-1d7748540d41.png)

So it almost sort of works..? (This is with fixed up displacement materials)

**Comment by gonzalologorg** [comment]
Holy! Working at Sundays? My cheers

**Comment by robotboy655** [comment]
It will be on Dev shortly, but it still has problems, which maybe won't be ever solved.
