### ISSUE TITLE
Add "distance to camera" button for func_areaportal's FadeStartDist/FadeDist to Hammer

### ISSUE THREAD

**Issue by UAVXP** [Facepunch/garrysmod-requests#1251]
Now it looks like this, and it's very uncomfortable to guess what distance I should put in the textbox:
![image](https://user-images.githubusercontent.com/3075683/49944309-cb3b4500-fef2-11e8-977b-aa0dbd37681e.png)

Normally feature that I'm requesting looks something like this grey camera button near the textbox:
![image](https://user-images.githubusercontent.com/3075683/49944384-f7ef5c80-fef2-11e8-9edf-1e072e02ceb7.png)

**Comment by UAVXP** [comment]
It can be enabled via alternating the first line of func_areaportalwindow describing in base.fgd:
`@SolidClass base(Targetname) color(0 128 255) sphere(FadeStartDist) sphere(FadeDist) = func_areaportalwindow : `

**Comment by UAVXP** [comment]
Also maybe you should make FadeStartDist and FadeDist as floats in fgd too
`FadeStartDist(float) : "Fade Start Distance" : 128 : "..."`
`FadeDist(float) : "Fade End Distance"   : 512 : "..."`

That's because they are described as floats in source code

**Comment by robotboy655** [comment]
Added the buttons but didn't change the KVs to floats as it doesn't appear to make any difference when I tested it
