### ISSUE TITLE
Most stuff like Ignite etc doesn't have an Add kill count for scoreboard!

### ISSUE THREAD

**Issue by BleueBear** [Facepunch/garrysmod-requests#1256]
Most stuff like Ignite etc doesn't have an Add kill count for scoreboard, it goes to the entity flame instead and we get -1 score to the scoreboard and it says entityflame instead of attackers name!

e.g Player [1][Nyaaa]	Entity [108][entityflame]	Entity [108][entityflame]

**Comment by thegrb93** [comment]
SetOwner on the flame entity to give credit I think. Or hook its damage maybe if that doesn't work.

**Comment by Nyaaaa** [comment]
Yeah but i am doing that, but it should be embedded like inflictor should be flame attacker should be player
