### ISSUE TITLE
A way to edit env_wind's wind angle.

### ISSUE THREAD

**Issue by Nak2** [Facepunch/garrysmod-requests#1259]
I created two functions to control the wind and gust of env_wind.
```Lua
function game.SetWind(min,max)
	local ent = ents.FindByClass("env_wind")[1]
	if not ent then return end
	ent:SetKeyValue("minwind",min)
	ent:SetKeyValue("maxwind",max)
end
function game.SetWindGust(min,max)
	local ent = ents.FindByClass("env_wind")[1]
	if not ent then return end
	ent:SetKeyValue("mingust",min)
	ent:SetKeyValue("maxgust",max)
end
```
But there are currently no way to control the angle of wind, as it [saves the angle on init](https://github.com/pmrowla/hl2sdk-csgo/blob/49e950f3eb820d88825f75e40f56b3e64790920a/game/shared/env_wind_shared.cpp#L125).

The only way to get dynamic wind, is to delete env_wind and use cl_tree_sway_dir x y.
But its not as fluent and you can't change the angle or create wind gusts, without the trees being 'choppy'.

**Comment by Kefta** [comment]
Can you change the ``m_iWindDir`` key in the env_wind's savetable?

**Comment by Nak2** [comment]
> 
> 
> Can you change the `m_iWindDir` key in the env_wind's savetable? I doubt it will update on the client, though.

I sadly need the variable changed on the client. The entity seems to cache the variable on init.

**Comment by robotboy655** [comment]
Added SetWindDir (int) input to env_wind, it seems to work in my tests.
