### ISSUE TITLE
Add support for +attack3 command

### ISSUE THREAD

**Issue by homonovus** [Facepunch/garrysmod-requests#1265]
There is an unused +attack command in gmod not utilized by lua.
I suggest pushing IN_ATTACK3 to lua, and potentially adding another function for SWEPs to call when +attack3 is being held.

**Comment by ItsEris** [comment]
+1 this would be rad for sweps and I have needed it in the past

**Comment by Roachdaripper** [comment]
+1

**Comment by Invalid-Vertex** [comment]
Technically, you can already use this if you define the IN_ enumeration like so
`local IN_ATTACK3 = 33554432`

But a function for sweps would definitely be useful as well (SWEP:TertiaryAttack()?)

**Comment by Roachdaripper** [comment]
> Technically, you can already use this if you define the IN_ enumeration like so
> `local IN_ATTACK3 = 33554432`
> 
> But a function for sweps would definitely be useful as well (SWEP:TertiaryAttack()?)

This works?

**Comment by Kefta** [comment]
I believe so but you have to make sure the IN_ enum is a unique power of 2. You can't just define it to an arbitrary number.

**Comment by Invalid-Vertex** [comment]
Yeah, it can't be just any number. In this case, 33554432 is the decimal value returned by CUserCmd:GetButtons() when +attack3 is called.

**Comment by Kefta** [comment]
Yep you're right, 33554432 is 2^25 which is IN_GRENADE2 * 2.

**Comment by VaasKahnGrim** [comment]
would be quite nice to have this feature in sweps. would make things interesting and allow more than just an alt fire option.

imagine a primary fire being a smg, having a scope attached to it for secondary fire, and then for the third fire a undermounted grenade launcher.

would go greate with a SWEP:Ammo3() and a Clip3() functions aswell
