### ISSUE TITLE
Support for greater rendering quality via DirectX 11/12 or Vulkan

### ISSUE THREAD

**Issue by wixyer** [Facepunch/garrysmod-requests#1267]
This question goes directly to Garry's Mod developers (Rubat, Willox..):

Will Garry's Mod provide support for fancier graphics rendering such as using DirectX 11/12, or perhaps Vulkan?

It is possible to force Source engine to run at DirectX 11 (`mat_dxlevel 110` from console, or `-dxlevel 110` from launch options).
But, it is a bad idea to force it beyond v9,  because Garry's Mod (Source engine) is not utilizing it, means it will drain more CPU/GPU (energy) usage for no reason.

It would be an interesting patch if this would ever happen.
I'm seeking out for some change in renderer quality, because DirectX 9 feels old even when tuned to ultra/very high configuration/settings (using console variables).

This is **not** proposing to drop support for DirectX 8/9.

Also, see [forum thread](https://forum.facepunch.com/gmoddev/buuzu/Will-there-be-support-for-DirectX-11-12-or-Vulkan/1/).

Regards, wixyer ;)

**Comment by mcNuggets1** [comment]
Theres no support for Direct X8

**Comment by Kefta** [comment]
There is, there are just some outstanding bugs with < DX9.

**Comment by wixyer** [comment]
> There is, there are just some outstanding bugs with < DX9.

Yeah, there is. And yeah, I have noticed that too, such as materials does not even work. DX8 is cool if you have an ancient computer.

**Comment by wixyer** [comment]
Quote from forum thread (@robotboy655):
> No.

I guess it means never.. 😞 
/closing
