### ISSUE TITLE
Check if using chromium/beta

### ISSUE THREAD

**Issue by 51italian** [Facepunch/garrysmod-requests#1270]
Hello,

Sorry to bother you all. Since Facepunch/garrysmod-issues#3119 implies that efforts to replace Awesomium has hit a roadblock, it would be nice if you might consider adding a simple global Lua function in the client realm to tell whether they are using chromium or what beta/branch they are running.

I've been running into a few issues with slightly different behaviors causing problems. Between that and wanting to easily and automatically notify and provide instructions for switching to the branch, I think this would be helpful to be myself and others.

I apologize if I have made a mistake and I'm wasting your time. I appreciate your time and consideration.

Thanks,
Vince

**Comment by robotboy655** [comment]
https://wiki.garrysmod.com/page/Global_Variables
