### ISSUE TITLE
Hammer & Ingame requests

### ISSUE THREAD

**Issue by Combine900** [Facepunch/garrysmod-requests#1274]
Hammer,
edit_fog is a "OBSOLETE" entity in hammer can we may give it a face? ^^,

Hammer,
edit_sky can we add a "renderamt" support for it or something to hide the entity ingame if you placed it with hammer?

Hammer,
Can we have a support for the flowing water stuff from l4d2?

Hammer,
Can we set the hammer compile window too the windows cmd like it is on csgo, l4d2 etc?

Ingame / Engine,
Garrysmod... its getting older and older but i never saw this as an official option ingame -> a borderless window setting

Ingame,
Can we have something like checkboxes for npcs that drop items? like health stuff or weapons that we can decide if they drop it or not.

thats it so far sorry if there are dupes.

**Comment by robotboy655** [comment]
1. edit_fog is not an entity meant to be used or spawned in Hammer. You have the default env_fog_controller entity.
2. Same for edit_sky.
3. Already requested
4. What for?
5. That's the only legitimate request here. One request per post/issue.
6. That's for mods to add or whatever
