### ISSUE TITLE
Allow Nextbots to use ENT:HandleAnimEvent()

### ISSUE THREAD

**Issue by Roachdaripper** [Facepunch/garrysmod-requests#1275]
The dev branch to gmod recently added functionality for Nextbots to use FireAnimationEvent... Only problem is that it's a clientside only hook, which means that serversided events of any form are still out of bounds to Nextbots, is it possible to add HandleAnimEvent functionality too? Thanks.

**Comment by robotboy655** [comment]
Can you or anyone provide me with a model that has them?

**Comment by Roachdaripper** [comment]
Any of [Silverlan's](https://steamcommunity.com/id/silverlan) Models or more recently [Mayhem](https://steamcommunity.com/id/Mayhem926) both exclusively use SNPCs that use events that fire off inputs to the NPC whereupon code can be run through it.
I was trying to recreate this using Nextbot, only for neither AcceptInput() nor any of the other functions to, well... function. Which is why I started this chain of Github threads.

However for a model, try this:
[exported_c2400.zip](https://github.com/Facepunch/garrysmod-requests/files/2818933/exported_c2400.zip)

**Comment by Roachdaripper** [comment]
I should also note that while my own example only uses the events for footsteps, Mayhem and Silverlan's examples show that events can be used to program an NPC entirely using inputs fired from their animations, using them for things like when an attack should hit, etc.

**Comment by robotboy655** [comment]
Added
