### ISSUE TITLE
Uninstall All but my addons button! So i don't have to waste time uninstalling all addons but mine! Or have settings when you click uninstall and we can choose!

### ISSUE THREAD

**Issue by Nyaaaa** [Facepunch/garrysmod-requests#1276]
Uninstall All but my addons button! So i don't have to waste time uninstalling all addons but mine! Or have settings when you click uninstall and we can choose!

Click Uninstall
Settings:
[ ] Your addons
[x] Other peoples addons

Will uninstall only the ones with x ticked!

**Comment by Nyaaaa** [comment]
Uninstall All but my addons button! So i don't have to waste time uninstalling all addons but mine! Or have settings when you click uninstall and we can choose!

Like Click Uninstall
[ ] Your addons
[x] Other peoples addons

Will uninstall only the ones with x ticked!

**Comment by robotboy655** [comment]
Uninstall all isn't something you are meant to use regularly. 

That being said, make a collection of the addons you want to keep and just press subscribe to all on it.
