### ISSUE TITLE
Add support for Model Renderer, Blob Renderer to Particle Editor

### ISSUE THREAD

**Issue by copperwarrior** [Facepunch/garrysmod-requests#1279]
As someone who uses the particle editor extensively for all forms of visual effects in my addon I find that many effects I want to create would not look the way I need them to look without some models. 

https://developer.valvesoftware.com/wiki/Particle_System_Renderers#render_blobs

**Comment by copperwarrior** [comment]
I saw that render_models is in the dev branch now. Will render_blobs be following soon?

**Comment by Kefta** [comment]
Rubat said he didn't find the blob renderer useful: https://github.com/Facepunch/garrysmod-requests/issues/2100

Perhaps he'll reconsider

**Comment by copperwarrior** [comment]
I have a particular use case; I have two entities that frequently move around in a lifelike manner, one is made of a thick goo and one is made out of water. Blob render would be useful for creating visual effects of splashes and drops coming off of these entities.

**Comment by robotboy655** [comment]
`render_blobs` is not an option as we do not have the complete source code for it.
