### ISSUE TITLE
Add ELights

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#1281]
ELights are drawn after DLights, are stored in a separate array, and are used in the engine for entity-related light events such as muzzleflash. They still use dlight_t for data so a new type object wouldn't have to be added. GMod should use ELights instead of DLights for [lights](https://github.com/Facepunch/garrysmod/blob/394ae745df8f8f353ea33c8780f012fc000f4f56/garrysmod/gamemodes/sandbox/entities/entities/gmod_light.lua#L67) and the [camera flash](https://github.com/Facepunch/garrysmod/blob/394ae745df8f8f353ea33c8780f012fc000f4f56/garrysmod/gamemodes/sandbox/entities/effects/camera_flash.lua#L7) since they are tracked by entity index.

Engine code: https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/src_main/engine/cl_main.cpp#L1697-L1705

**Comment by Kefta** [comment]
Any chance in adding this before next update? Doesn't require any new types, its just a single method binding.

**Comment by robotboy655** [comment]
Testing this I noticed ELights cannot light the world, which makes them unsuitable for Light tool and arguably the camera flash as well. Do you think this is still useful?

**Comment by Kefta** [comment]
You're right, I had only tested them on props. What would be better would be for the ``noworld`` key in DynamicLight's constructor to actually [allocate an ELight instead of a DLight](https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/se2007/game/client/c_dynamiclight.cpp#L140-L142) as done in[ >EP1](https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/se2007/game/client/c_dynamiclight.cpp#L26).

**Comment by robotboy655** [comment]
We are apparently already doing that!

**Comment by Kefta** [comment]
It looks like the Lua binding isn't using the method above if in-fact GMod is currently using that.

![8ke7IgK](https://user-images.githubusercontent.com/4593679/58107430-71306100-7baf-11e9-892b-633009a156c6.png)

Here I have a single gmod_light with the entity property "Don't light world" set sitting on top of a prop. Behind it are 32 gmod_lights on the wall that are set to light the world. Here's the same picture with 31 world-lighting gmod_lights.

![A8JyW25](https://user-images.githubusercontent.com/4593679/58107655-e3a14100-7baf-11e9-8bf7-4b4fd48c8958.png)

**Comment by robotboy655** [comment]
You do understand ```noworld ``` can only be set after ```DynamicLight``` is called? ```DynamicLight``` does not use C_DynamicLight internally.

**Comment by Kefta** [comment]
It's called every frame for gmod_lights: https://github.com/Facepunch/garrysmod/blob/394ae745df8f8f353ea33c8780f012fc000f4f56/garrysmod/gamemodes/sandbox/entities/entities/gmod_light.lua#L67

**Comment by Kefta** [comment]
![eaarRfJ](https://user-images.githubusercontent.com/4593679/58181106-cd0eee80-7c70-11e9-9187-c53bc1df3c8e.png)

I still believe this should be tied to the ``noworld`` parameter. There is no reason for the Lua state to have any knowledge of elights, nor do dlights have to be used if they don't have to light the world.

**Comment by robotboy655** [comment]
It cannot be automated without completely changing how `DynamicLight` works, `noworld` parameter is set **after** ```CL_AllocDlight``` is called.

**Comment by Kefta** [comment]
Epic

**Comment by neico** [comment]
Well we could also get rid of those static arrays and use something like `std::vector` that can grow as much as there's memory (and then limiting it by a simple `size()` check when creating an instance)

Tough `CUtlVector` is probably the better alternative unless you already use C++ standard classes (Because Valve's classes are highly outdated nowadays)

A lot of the engine is highly behind the time, there's no reason to not choose a smarter solution over what's already there... (And memory can't be this low on today's computers to not be able to sustain a vector doing its thing)

**Comment by Kefta** [comment]
It would be better to use a hashtable or dictionary since the lights are stored by arbitrary integer key.
