### ISSUE TITLE
Support for an portal 2 entity

### ISSUE THREAD

**Issue by Combine900** [Facepunch/garrysmod-requests#1282]
could we may get a support for this entity from portal 2? -> env_sprite_clientside

why? clientside stuff is always great and would be rly useful for bigger maps that are using many sprites

Entity description [valve dev forum]
An entity that controls the drawing of a sprite in the world, created clientside so cannot be parented to moving things and will use up no network bandwidth or CPU. (Doesn’t use edicts)

**Comment by robotboy655** [comment]
Why making one with Lua is not an option?

**Comment by thegrb93** [comment]
Many mappers aren't lua programmers.

**Comment by thegrb93** [comment]
I think you could ship your map with a script that inserts the sprites on load though.

**Comment by Combine900** [comment]
> 
> 
> Why making one with Lua is not an option?

agree on thegrb93, if it take u too much time just close this thread and say no i can deal with it without getting myself a gun.. nvm you know what i mean.

**Comment by Kefta** [comment]
``env_sprite_clientside`` is just a copy of ``env_sprite`` but [only declared serverside](https://github.com/NicolasDe/AlienSwarm/blob/c5a2d3fa853c726d040032ff2c7b90c8ed8d5d84/src/game/shared/swarm/asw_fx_shared.cpp#L24-L27) - it appears in dumpentityfactories serverside on Alien Swarm so the wiki description is definitely wrong. This can't be solved in Lua without https://github.com/Facepunch/garrysmod-requests/issues/1308.

**Comment by Kefta** [comment]
This is covered in https://github.com/Facepunch/garrysmod-requests/issues/1577.

**Comment by Combine900** [comment]
@robotboy655 Any plan too add this entity yet? if no i can close this thread.

**Comment by GitSparTV** [comment]
Rubat answered you abs code referenced an issue, what do you want more?

**Comment by robotboy655** [comment]
This will be included in the next update, just not right now because it's a new entity and all that.

**Comment by robotboy655** [comment]
Added.
