### ISSUE TITLE
game.GetAmmoTypes

### ISSUE THREAD

**Issue by Tripperful** [Facepunch/garrysmod-requests#1284]
A 'legal' version of game.BuildAmmoTypes for non-internal usage for retrieving all registered ammo types

**Comment by Kefta** [comment]
This could be solved in Lua by just copying game.BuildAmmoTypes but an engine implementation to get an actual list of registered ammo types would be more accurate.

**Comment by robotboy655** [comment]
Do you want just a list of all ammo types, or the actual data too? If the latter, why do you need all the data at the same time?

**Comment by robotboy655** [comment]
Would https://github.com/Facepunch/garrysmod-requests/issues/646 be sufficient if you want the data?

**Comment by Tripperful** [comment]
I want a list of all registered ammo types, so that if I want to get any data for a specific type I can do it as well

**Comment by robotboy655** [comment]
Added game.GetAmmoTypes()
