### ISSUE TITLE
Add a hook to reliably get when the entity is created

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#1290]
As the new description of [OnEntityCreated](https://wiki.garrysmod.com/page/GM/OnEntityCreated) implies, it should not be reliably used to detect entity creation. Can a hook be added for that? If you're worried about performance, implement it as a gameevent so it can be optionally listened to.

If a new hook is added, I'd recommend naming it EntityCreated to have consistency with EntityRemoved.

**Comment by robotboy655** [comment]
Why would you want this as a new hook rather than changing OnEntityCreated?

**Comment by thegrb93** [comment]
I assume they would behave differently. He did say 'if' though so either would be fine probably.

**Comment by robotboy655** [comment]
I changed when OnEntityCreated is called on both server and client, this should be reliable now in my tests. It should also catch ALL entities on client.
