### ISSUE TITLE
Add support for Vertexlitgeneric on prop_detail

### ISSUE THREAD

**Issue by Stiffy360** [Facepunch/garrysmod-requests#1295]
prop_detail, an entity spawned by vbsp if a model is specified in detail.vbsp currently only supports unlitgeneric as a shader. This severely limits its usefulness when it comes to detailing environments and makes models spawned look rather bad in many cases.

**Comment by robotboy655** [comment]
Dev branch got cl_detail_allow_vertex_lighting 1/0, use that to test for now.

**Comment by Stiffy360** [comment]
Been testing it a good amount and it works near flawlessly. The only issue I've found is that flashlight does not affect it one bit. All the vertexlitgeneric shaders I've tested so far work including $treesway.

**Comment by Stiffy360** [comment]
The only issue I've found so far is the vertex coloring applied to the models makes them brighter/darker than what they're supposed to be since it's being almost double applied.

**Comment by robotboy655** [comment]
I will be defaulting the cvar to 1 on `dev` beta and in the upcoming update.
