### ISSUE TITLE
Add non-english HL2 files and translate HL2 strings with language setting

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#1297]
All located in ~/hl2/resource. You'll probably have to change sv/cl_language usage to gmod_language, or better yet, tie their values to one another (aliases). Related to https://github.com/Facepunch/garrysmod-requests/issues/652 and https://github.com/Facepunch/garrysmod-requests/issues/1159.

**Comment by Kefta** [comment]
Now related to https://github.com/Facepunch/garrysmod-issues/issues/4110.

**Comment by robotboy655** [comment]
Basically duplicate of https://github.com/Facepunch/garrysmod-issues/issues/4110

All the files are already shipped with the game, but are unused because the engine does not support live language changes
