### ISSUE TITLE
Don't remove ] from custom error calls

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#1300]
I know this is intentional to strip away the "[ERROR]" part of the message but it should not affect the user's input. Use a substring or hardcoded check of the error string's first character to prevent the incorrect message from showing.

**Comment by robotboy655** [comment]
Undone this behavior completely, let me know if anything breaks, but in my tests it doesn't affect anything.

MAYBE errors from workshop addons.
