### ISSUE TITLE
Readd r_portalscloseall with FCVAR_CHEAT

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#1301]
Doesn't draw through any area portals, opposite of ``r_portalsopenall``. Declared [here](https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/se2007/engine/r_areaportal.cpp#L561). See https://github.com/Facepunch/garrysmod-requests/issues/1299#issuecomment-468993833.

**Comment by CaskoChan** [comment]
Why is it that source 2007 has more features in general than source 2013? I always see you post these and it really gets me thinking.

**Comment by robotboy655** [comment]
Done. (it was simply hidden)
