### ISSUE TITLE
Add "Shoot" and "ShootBright" input events to hunter_flechette

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#1304]
Inputs to call [Flechette::Shoot](https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/se2007/game/server/episodic/npc_hunter.cpp#L854) - the arg should be interpreted as a vector. Simply spawning a hunter_flechette does not create sprite trails nor setup the correct Think context, ~~causing the error ``Bad sequence (-2 out of 2 max) in GetSequenceLinearMotion() for model 'weapons\Hunter_flechette.mdl'!``. Adding this and applying it to the flechette gun will fix the errors when shooting.~~

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod/commit/9e00928fe9f6d544afdd41eed9a8da83e64e8456

**Comment by Kefta** [comment]
That still doesn't fix the ability to have sprite trails.

**Comment by robotboy655** [comment]
If the entity is spawned through Lua, it will have the equivalent of Shoot() executed on it, It has been this way forever. Test it yourself, just remember to call ```Activate()```

**Comment by Kefta** [comment]
It still doesn't have the sprite trail from Shoot like normal flechettes - compare the current dev branch flechette gun's projectiles with one that [hunter_shoot_flechette](https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/se2007/game/server/episodic/npc_hunter.cpp#L413-L438) instead: https://www.youtube.com/watch?v=RMztDrUKIOg

**Comment by robotboy655** [comment]
Huh, it definitely has the particles on my end. Maybe the .pcf doesn't load on your end for some reason? Can you check your console for particle loading errors?

**Comment by robotboy655** [comment]
Looking into this, there's some fuckery going on with the effect itself, it is being blocked when fired from the weapon, it works perfectly fine if ran from console command. Adding the inputs will not solve the problem.
