### ISSUE TITLE
Add function to set a CCrossbowBolt’s damage

### ISSUE THREAD

**Issue by Kinyom** [Facepunch/garrysmod-requests#1307]
The bolt entity shot by the default crossbow has an “m_iDamage” variable (handles the damage it does; also used in calculating the force it applies to a target it hits) that can’t be accessed in any way by Lua. It’d be nice to, at the very least, have this set to a DEFINE_KEYFIELD so it could be exposed to Entity:GetSaveTable, or have a function created to get/set it. Currently, the only way around this is to either recreate the whole entity in Lua or hook into EntityTakeDamage and manually set the damage and force it should apply; however this method, for some reason, prevents the blood splatter decals/effects it should make from appearing (at least on NPCs; I haven’t tried it on players yet).

**Comment by robotboy655** [comment]
Added as "SetDamage" input on the entity.
```
concommand.Add( "bolt", function( ply )
		local e = ents.Create( "crossbow_bolt" )
		e:SetPos( ply:GetShootPos() )
		e:SetAngles( ply:GetAngles() )
		e:SetOwner( ply )
		e:Spawn()
		e:Fire("SetDamage", 100 )
		e:SetVelocity( ply:GetAimVector() * 1000 )
	end )
```

**Comment by thegrb93** [comment]
Is that documented somewhere or will it be a hidden feature?

**Comment by robotboy655** [comment]
I do suppose a wiki page for extra inputs is in order, but someone did document some of the gmod only inputs and stuff on VDC

**Comment by robotboy655** [comment]
https://wiki.garrysmod.com/page/Custom_Entity_Inputs_And_Outputs

Here it is

**Comment by thegrb93** [comment]
Nice
