### ISSUE TITLE
Add SurfaceFlags and DispFlags keys to TraceResult

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#1309]
Returns the (DISP)SURF enums of the hit surface.
https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/src_main/public/trace.h#L57
https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/src_main/public/cmodel.h#L54

Also the [DISPSURF enums](https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/src_main/public/trace.h#L24-L29) themselves.

**Comment by robotboy655** [comment]
Added
