### ISSUE TITLE
net.BytesRemaining

### ISSUE THREAD

**Issue by WilliamVenner** [Facepunch/garrysmod-requests#1312]
This could be useful when doing complex net message stuff, such as reading & writing compressed data. The function should just return how many bytes have not been read yet in the current net message.

Each `net.ReadWhatever` would subtract from a value containing the total size of the net message.

This function would also make "optional"/conditional reads in a single net message easier (e.g. `if net.BytesRemaining() > 0 then ...`)

**Example use**

```lua
net.Receive("msg", function(len)
    local str = net.ReadString() -- subtract #str from remaining bytes value
    local int = net.ReadUInt(16) -- subtract 2 bytes from remaining bytes value

    local remaining_bytes = net.BytesRemaining() -- returns len - #str - (16 / 8) (the remaining bytes value)
    local data = util.Decompress(net.ReadData(remaining_bytes))
    print("cool beans " .. data)
end)
```

In this case, this removes the need to send the size of the compressed data with the net message (reducing bandwidth usage) and/or abstracts & simplifies manually subtracting from the total net message size after every `net.ReadWhatever` operation, which is difficult code to refactor when necessary.

**Comment by robotboy655** [comment]
> In this case, this removes the need to send the size of the compressed data with the net message (reducing bandwidth usage)

But you don't need to either way. You know length of the message and you know the length of the first 2 read calls.

**Comment by WilliamVenner** [comment]
> > In this case, this removes the need to send the size of the compressed data with the net message (reducing bandwidth usage)
> 
> But you don't need to either way. You know length of the message and you know the length of the first 2 read calls.

Yes:

>[..] abstracts & simplifies manually subtracting from the total net message size after every net.ReadWhatever operation, which is difficult code to refactor when necessary.

**Comment by thegrb93** [comment]
Would be good if we got one as well for the underlying reliable channel per player so we know we aren't about to overflow them.

**Comment by thegrb93** [comment]
Nevermind, unrelated to the topic, I just read it.

**Comment by robotboy655** [comment]
added net.BytesLeft, only because BytesWritten already exists.
