### ISSUE TITLE
Add Cycle to Entity.GetSequenceGroundSpeed()

### ISSUE THREAD

**Issue by Roachdaripper** [Facepunch/garrysmod-requests#1314]
GetSequenceGroundSpeed seems to only fetch the animation's speed during the first frame, which for animations that aren't walking/running (attacking animations for instance) is often 0 or close to, would it be possible to add the animation cycle as an argument just like with GetSequenceMovement, or if possible add an argument for a specific frame of animation (which you'd get using HLMV)

**Comment by robotboy655** [comment]
https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/shared/animation.cpp#L541

It calculates the entire sequence, not just the first frame
