### ISSUE TITLE
Table functions for size comparison.

### ISSUE THREAD

**Issue by end360** [Facepunch/garrysmod-requests#1319]
With the recent table.IsEmpty addition I think there should also be an addition for functions that determine if a table has a certain amount of elements (for non sequential tables). Something like (ideally better named) table.HasN(tab, amt) which would return true as soon as it hit amt elements in a table. It would make sense to also add functions for the other comparison operators. 

Here's two instances that I found in base GMod that would benefit from it.

1. [TTT clientside](https://github.com/Facepunch/garrysmod/blob/49cf1fc9f8a507263728d206e3f4ff859f921e51/garrysmod/gamemodes/terrortown/gamemode/cl_awards.lua#L148)
2. [Duplicator](https://github.com/Facepunch/garrysmod/blob/394ae745df8f8f353ea33c8780f012fc000f4f56/garrysmod/gamemodes/sandbox/entities/weapons/gmod_tool/stools/duplicator/icon.lua#L20)

**Comment by willox** [comment]
We could take this a step further and merge multiple operations into a single call such as: `table.GenerateComparator( table.HasGT( 5 ), table.HasLT( 10 ) )( myTab )`  to check if a table contains 6, 7, 8, or 9 elements.

The comparator could be cached and reused multiple times, of course.

**Comment by thegrb93** [comment]
For the duplicator one you can just add a counter to the loop below it.

**Comment by thegrb93** [comment]
Keep it simple, stupid

**Comment by end360** [comment]
> 
> 
> Keep it simple, stupid

Guess we didn't need a table.IsEmpty function either, considering someone could implement that in one line. (I do agree with your optimization though)

**Comment by willox** [comment]
Oh I missed that you mentioned the idea is just trying to avoid iterating more times that necessary. I think it's a little too specific and I dislike the idea of it requiring multiple functions.
