### ISSUE TITLE
Add a variable for the attacked entity in DamageInfo()

### ISSUE THREAD

**Issue by Roachdaripper** [Facepunch/garrysmod-requests#1320]
Would this be a possibility? It'd be used for the OnTakeDamage hook if anything, since you aren't always able to grab the entity being attacked when hooking it in, if you're not hooking it to an entity, or if you're hooking it to an entity and you want to grab a specific entity that it's attacking.

**Comment by robotboy655** [comment]
There's a gamemode hook that is called for all entities attacked. You can also use it to detect when a certain entity attacks if you give the DamageInfo() proper info (attacker, inflictor, etc)

https://wiki.garrysmod.com/page/GM/EntityTakeDamage
