### ISSUE TITLE
Hud changing to Full HL2 one(and also textures)

### ISSUE THREAD

**Issue by Flo4rmint** [Facepunch/garrysmod-requests#1327]
**In the latest versions of Garrys Mod we still cannot observe some hud elements from HL2 such** as: 
 1) AmmoHud  Icons in the right botton part of the screen 

2)Changing name of the weapons (For example Gravity gun in hl2 is called Zero-Point energy Manipulator, SMG is called Submachine Gun, RPG is Rocket Proppeled Grenade, ect.

3)The glow of Gravity gun in Hl2 is brighter than in Garry's mod.

4)Weapon ammo Pick up history is more clear in hl2.

5)Some things like for instance poison indicator is enabled but stilled not as clear as in Hl2 and episodes.

6)In hl2ep2 you can see your flashlight hud in the botton of the screen.

7)The rocket launcher laser beam is more clear and nice in hl2.

Please tell me how should I replace or even add anything from this list to HL2 game files to observe it in the game.

**Comment by Kefta** [comment]
Most of these were denied in https://github.com/Facepunch/garrysmod-requests/issues/789 and https://github.com/Facepunch/garrysmod-requests/issues/846 since you can replicate them in Lua.

**Comment by Flo4rmint** [comment]
thanks

**Comment by robotboy655** [comment]
Once again, Garry's Mod is not Half-Life.

Garry's Mod is by its nature is very customizable, if you do not like something, either change it yourself using the modding tools provided or find a mod that does it for you if such mod exists.

Another thing is that Garry's Mod is not based on Half-Life 2, it is based on Half-Life 2: Deathmatch, which is where all the weapons and default HUD are coming from.

Some of the effects on the weapons being buggy is already reported.

**Comment by thegrb93** [comment]
Very difficult to get a exact replication with all the hud effects. Valve put a lot of detail into it. I wonder if anyone managed to accomplish it yet.
