### ISSUE TITLE
Bindings for CBasePlayer::GetUseEntity and CBasePlayer::SetUseEntity?

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [Facepunch/garrysmod-requests#1329]
https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/player.h#L1274-L1282

**Comment by Kefta** [comment]
Does m_hUseEntity not show up in the savetable?

**Comment by YuRaNnNzZZ** [comment]
only serverside but yes

**Comment by robotboy655** [comment]
What do want to do with this anyway? If you want to override which entity the player's use activates, this isn't what you need, you need the already existing ```GM:Use``` hook

**Comment by YuRaNnNzZZ** [comment]
I'd like to use the GetUseEntity for blocking SWEP-base specific actions (while using combine turret, for example).
Syncing the save value from server to client is indeed possible but isn't it better to have a binding for that instead?

**Comment by robotboy655** [comment]
Since it's already networked I will add a getter for this. I will name it ```Entity.GetEntityInUse``` to avoid confusion, to me ```GetUseEntity``` implies it returns the entity that would be used if player presses +use keybind, which is not what the function returns.
