### ISSUE TITLE
Player specific FastDL function, or a GM:ContentDownload hook

### ISSUE THREAD

**Issue by VaasKahnGrim** [Facepunch/garrysmod-requests#1334]
Essentially a hook that would allow for server owners and gamemode creators to have specific content download only for specific players when they join.

Example: Players joining who are a simple user will download maps, materials, models and sounds as normal. Players who are say moderator/admin/superadmin will download that stuff but also download any admin related stuff aswell.

Reason for this feature: Better control over content downloading based on player rank. Alot of admin tools seem to use content packs for the specific admin tool. several of these such packs could add up over time for users downloading the addons needed. if only staff are downloading it this would mean non-staff players would likely get ingame alot sooner.

Side question: If I have multiple feature requests should I put them into a single issue or separate them into multiple?

**Comment by robotboy655** [comment]
What possible use this would have? The only thing I can think of is UI textures for admin tools but that is such a tiny thing its not worth going through the trouble of doing this.

Besides, we already have game.MountGMA which can be used to achieve this.

That being said, this is still a silly idea in my mind.

> Alot of admin tools seem to use content packs for the specific admin tool. several of these such packs could add up over time for users downloading the addons needed. if only staff are downloading it this would mean non-staff players would likely get ingame alot sooner.

What makes you think these content packs are meant only for the staff? I have never seed admin mods with separate content packs anyway. What makes you think non staff players would likely get in game A LOT sooner? Because they won't, its a difference one ONE addon to download at best.

**Comment by Kefta** [comment]
I think the better request here would be a way to download files while in-game without Steam workshop. That would be well suited for minigame and lobby servers.

**Comment by VaasKahnGrim** [comment]
Serverguard, OAS, anything made by nordhal(I can't spell it right still), and alot of things on gmodstore require additional addon content from workshop in them. but only staff ever see the menus that the content is used in.

Possibly other things could be achieved aswell with this. for example, in starwarsrp you have alot of different genre aswell as different styles of playermodels. Clonewars specifically has the CGI style of models and the BF2 style of models. If this kind of hook was there you could have a default model style set for the server but allow players to choose what style they see in game. 

Example:
`function GM:ContentDownload(ply)
    if(ply:GetModelMode() == "CGI")then
        resource.AddWorkshop('CGI MODELS ADDON')
    else
        resource.AddWorkshop('BF2 MODELS ADDON')
    end
end`

it would be alot faster for players to only download one set of playermodels as default first and then get in game and be told they can switch styles if they want to. this would mean a community didn't have to choose between what style they wanted to see ingame, instead people choose what they wanted to see for themselves without downloading twice as much content just to get ingame the first time joining.

But if game.MountGMA would be better how would accomplish this anyways could I get an example by chance?

**Comment by robotboy655** [comment]
I don't think that 0.025 MB of ServerGuard Content, or any other "admin only" content is going to make a difference. It's a pretty narrow use case, and it has an even narrower problem of people becoming admins while already on the server. And then, what if a players stops being an admin? Now they have wasted space with that content!

Anyway, you do realize that file downloading happens before the player actually spawns on the server? This means that the hook you want cannot exist. Not to mention that ```resource.AddWorkshop``` makes files downloadable for ALL clients, not magically the certain clients you are thinking of in your head.

If you are looking for help with ```game.MountGMA```, please visit the official wiki.

**Comment by VaasKahnGrim** [comment]
well I know resource,AddWorkshop is still sending info of what addons are to be downloaded to clients. the only difference is what is sent to specific clients. and I already looked at game.MountGMA on the wiki but the issue is that would just download the addon while the player is already in game which would just kill client performance.

would be better to be able to simply control resource.AddWorkshop() more precisely or something like that.

**Comment by neico** [comment]
This can also be problematic, at loading the client has the IP it's connecting from and at most the server-session specific client ID,
with some luck the SteamID was already transferred which you can use to identify the client properly then.
But I doubt this happens before the loading of resources is done (`Sending Client Info` should be the loading step at where the SteamID is being sent I believe, which is the very last one before joining in-game)

Not to mention that the download stringtable isn't really prepared to handle such a special case (maybe using the optional userdata), but the correct identification of the client is still outstanding at that point.

**Comment by VaasKahnGrim** [comment]
any way to use that game.MountGMA without it causing the game to become unstable? like a way to throttle it to a percentage of bandwidth maybe? or possibly have it run on a separate thread like the loading screen does?

because the only time I've ever seen that used was for ingame downloader scripts but they always have issues with performance. if theres a way to use MountGMA before the player is fully in and without destroying performance then that would pretty much be perfect instead of a GM:ContentDownload() hook. but so far the wiki page doesn't really have much info on the function, it does have an example tho.

**Comment by Kefta** [comment]
>or possibly have it run on a separate thread like the loading screen does?

The loading screen doesn't run in its own thread. There's unfortunately no way to delegate any Lua tasks to another thread, and the performance hit with MountGMA is unavoidable. I'll restate my request from earlier:  being able to dynamically download files in-game is the best of both worlds as you can specify certain files for each user to download, and you can add each file over time avoiding the performance toll. Please consider this @robotboy655

**Comment by joeyjumper94** [comment]
let me write some hook examples
the values of the table could be strings that correspond to workshop IDs or strings that point to files
---------------------------------
--string steamID64, string ipAddress, string SteamName, table downloads
hook.Add("ContentDownload","example",function(SteamID64,IPAddress,SteamName,list)
    if SomeFunctionSaysHeIsAnAdmin(SteamID64) then
        for k,v in pairs(table_listing_more_stuff_like_admin_gui_materials)do
            table.insert(list,v)
        end
    end
end)

**Comment by VaasKahnGrim** [comment]
I sorta opted for using steamworks.Download() clientside instead and removing the server from the situation a while back after opening this. The only issue being I have no idea if it redownloads each time or if it verifies the file being there first. never bothered to check. but so far its worked well for player secific content downloads

**Comment by robotboy655** [comment]
This hook request is not happening.
