### ISSUE TITLE
Add HandleAnimEvent to SNPC class(ai entity type)

### ISSUE THREAD

**Issue by arkayden** [Facepunch/garrysmod-requests#1335]
Sorry for my english.
Without this hook it is not possible to make the correct handle animations (attacks, movements, etc.).
This function only works for anim and nextbot entity types. For example, in the source SDK, the antlion has this function. I would like to writted on lua SNPC also support this function.

Just in case.

https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/game/server/hl2/npc_antlion.cpp
**line 1054**

https://wiki.garrysmod.com/page/ENTITY/HandleAnimEvent

**Comment by robotboy655** [comment]
Done
