### ISSUE TITLE
Make it so gameserver accounts persists across the "favorites" feature

### ISSUE THREAD

**Issue by CryptAlchemy** [Facepunch/garrysmod-requests#1336]
I noticed that when someone favorites a server, they cannot return to the server by means of the "favorites" tab in both the regular menus and the Legacy Browser.

I'd like to request this as a feature.

Implementation Idea:
- When a player adds a server to their favorites, save the server's Steam ID.
- Instead of using the IP to fetch the favorites, use the server's Steam ID to find it.

**Comment by robotboy655** [comment]
I am confused. Are you saying the server favorites feature doesn't work at all or what?

**Comment by CryptAlchemy** [comment]
@robotboy655 
I've created a Steam Gameserver token with the App ID of 4000 for Garry's Mod.
I logged in and it assigned my server a proper Steam ID.

I added the server to my Garry's Mod's favorites in the Legacy Browser, and that shows up in the Favorites option in the menus.

I made sure to refresh and it was there.

I then swapped the IP address of the server, and it was gone from my favorites.
I tried restarting Gmod, restarting the server, and I made sure that the server was up by means of pinging it and directly connecting to it via IP address.

**Comment by robotboy655** [comment]
The favorites list is handled entirely by Steam ( SteamMatchmaking()->AddFavoriteGame ), if you are having problems with the Steam's Persistent Game Server Accounts feature, perhaps you should contact Steam Support instead.

You should also check the Steam Server Browser in your tests, but the result will probably be the same.

**Comment by CryptAlchemy** [comment]
@robotboy655 
Update:
It turns out that it takes a few hours of uptime for the server to persist across the Steam network.
I checked just now and they are all showing up in my favorites.

Thank you for your assistance, and we can consider this one closed.
