### ISSUE TITLE
Check Task Status Before NextTask (TaskStatus_e)

### ISSUE THREAD

**Issue by ts-co** [Facepunch/garrysmod-requests#1337]
### TaskStatus_e
This is sort of an issue, but it seems like it was never added to `base_ai` to begin with. 
When you make a schedule, tasks _do_ run incrementally, but they get fired without checking to see if the previous task is finished. An example I use:
```lua
function ENT:doUse(target)
	self:SetTarget(target)
	local schedule = ai_schedule.New("UseSomething")
	schedule:EngTask("TASK_SCRIPT_RUN_TO_TARGET", 0)
	schedule:EngTask("TASK_FACE_TARGET", 0)
	schedule:AddTask("Use")
	self:StartSchedule(schedule)
end

function ENT:TaskStart_Use(data) end
function ENT:Task_Use(data)
	local target = self:GetTarget()
	target:Use(self, self, USE_TOGGLE, 1)
	self:TaskComplete()
end
```
What happens is that the NPC runs to the target, faces the target, and uses it all in one go, without checking to see if it finished running to target or facing it.

It seems as though there's supposed to be task status checking to see if the previous task is finished, found [here in ai_task.h](https://github.com/ValveSoftware/source-sdk-2013/blob/55ed12f8d1eb6887d348be03aee5573d44177ffb/mp/src/game/server/ai_task.h#L69-L76)

From my understanding someone made schedules work incrementally [here](https://github.com/Facepunch/garrysmod/blob/394ae745df8f8f353ea33c8780f012fc000f4f56/garrysmod/gamemodes/base/entities/entities/base_ai/schedules.lua#L108-L124), but this function only makes it work in the correct order as if it were running a for loop, but it doesn't actually check to see if the previous task is completed. The only thing it does is check to see if it was the last task in a list and then finish the schedule.

### Proposal
I'm not exactly sure how source engine things get added to Garrysmod, but NextTask should get the status of the previous task before moving onto the next task. Maybe a while loop for TaskStatus_e?

**Comment by ts-co** [comment]
After researching the problem more, it could be that the biggest issue is that `TASK_SCRIPT_RUN_TO_TARGET` doesn't have a TaskID and thus isn't able to work with functions like Task:Run where it checks to see if it finished or not.

**Comment by robotboy655** [comment]
No, you are just doing it wrong. Use TASK_WAIT_FOR_MOVEMENT to wait for the movement to finish.

You can find the source code for all the tasks here:
https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/game/server/ai_basenpc_schedule.cpp

https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/game/server/ai_basenpc_schedule.cpp#L1102-L1187
You will notice that the task does what it meant to do: Sets the target to run to and completes.
