### ISSUE TITLE
CLuaLocomotion:GetNextBot

### ISSUE THREAD

**Issue by Dragoteryx** [Facepunch/garrysmod-requests#1344]
NextBots have a CLuaLocomotion object bound to them accessible via the `.loco` property, however there is no way to access the NextBot via the CLuaLocomotion object. That would be useful if for example you want to overwrite specific CLuaLocomotion methods without breaking other nextbots.

For example if your nextbot can climb using Lua, you might want to overwrite the `IsClimbingOrJumping` function.
```lua
local locoMETA = FindMetaTable("CLuaLocomotion")
local old_IsClimbingOrJumping = locoMETA.IsClimbingOrJumping
function locoMETA:IsClimbingOrJumping()
    if self:GetNextBot().IsCool then -- check whether or not this CLuaLocomotion is bound to your NextBot
        -- return your own value here
    else return old_IsClimbingOrJumping(self) end -- return the defaut value to avoid compatibility issues
end
```

**Comment by robotboy655** [comment]
Done
