### ISSUE TITLE
Clientside option for disabling Loading Screens from playing audio

### ISSUE THREAD

**Issue by VaasKahnGrim** [Facepunch/garrysmod-requests#1349]
Basically a way to turn of annoying loading screens that spam dubstep or terribly written rap music that has the bass so high its not even music anymore. Preferably also prevent this from being overridden by any addons what so ever.

A good reason for this being School Shooter Simulator killing my ears should be justified enough

**Comment by Kefta** [comment]
https://github.com/Facepunch/garrysmod/pull/1427 has been open for over a year now.

**Comment by robotboy655** [comment]
That PR was merged and this request is not really feasible with Awesomium.

Ideally the loading screen volume should be tied to the `volume` convar as well as obey `snd_mute_losefocus` as anyone would expect, not yet another convar.
