### ISSUE TITLE
Please help community fighting with cheaters

### ISSUE THREAD

**Issue by WillDxx** [Facepunch/garrysmod-requests#1351]
For last 10 years, Garrysmod community had one big problem.. cheaters.
It's not a big deal on all gamemodes, but such unfair adventages shouldn't be allowed.

In Past community Dev's were playing game with cheaters by finding explotis, methods to fight with unfair players.
You, as garrysmod developers should help us with that fight.
Now, after a lot of updates, our hands are tied and it's nearly impossible to detect most cheats.
We can only catch players using cheats written in lua but everything else is beyond our capabilities.
Cheaters using cheats written in C, binary modules are nearly undetectable.
Don't get me wrong, I don't want you to block binary modules, they are great way for expanding gmod features.
Please, provide us with feature to check clients or make it as your job to fight with them.

If it still isn't enough for you:
Did you know that Gmod cheats are sold on external websites?
Known example: https://citizenhack.me

Do something about it, It maybe isn't the most important feature but why should we give some players unfair adventages.

And finally I want to point a problem for another day: "hackers" which have been using Lua/C methods to crash or steal data on community servers.
I know that not everything what I said was 100% correct but you get what i wanted to tell, maybe more experienced members will make their stand.

Thanks for supporting our awesome game for such a long time but please, help us keep it alive.

**Comment by meepen** [comment]
You can detect almost all cheats with ingenuity, and as long as games exist
there will be cheats. The developers can't keep up and most likely won't
because of Garry's stance on this game being a sandbox game.

**Comment by michak89** [comment]
Yes, almost every lua cheat can be easily detected. However ingenuity won't help You much with injected hax, try first. It's possible to calculate many things like % of headshots if hitboxes are correctly set. Cac had a lot of ideas like that. Anyway !cac died, hac was also good rip. 

Players and coders can do sheet about c hax only game dev can help and should do it. I found similar request from 2015 - it was closed without any explanation, why can't they use vac? I know that blacklisting bad modules is hard work but I can't see any better way to make game safe. 

If binary module is in lua/bin - we can see it, read, check, ban user etc.
Please do something about injecting binaries 👍

**Comment by meepen** [comment]
You can definitely fight c cheats with Lua.

**Comment by michak89** [comment]
As I said You can calculate many things. Try to calculate wallhack, gl
Any examples of c hax detection in lua? :D  I mean hack detection, not cheating detection.

**Comment by meepen** [comment]
Wall hacking could be prevented better if there were more support for pvs
stuff in lua, such as hooks we could enable for pvs like we have for custom
collisions. I can't provide any help with detecting other types of cheating
but you just need to think about what cheats do that normal players can't.
VAC would be nice but vac also takes a ton of work for the developers to
implement to detect cheats, it's not a light switch which will ban all
cheaters. Enabling vac also runs the risk of banning innocent people that
just want to run modules, if any cheats use public code.

**Comment by thegrb93** [comment]
Either way, this is a useless+duplicate+old issue

**Comment by michak89** [comment]
@thegrb93, useless for? Fair players?  Server owners? Community? Useless for Facepunch, no extra cash on building ac system, this is sad. I'm sure They won't do anything - normal. But You can't say it's useless.

**Comment by WillDxx** [comment]
You can't say that something is useless without giving arguments, that's not how disscusion works.
Duplicate? Maybe but previous ones still didn't get answers.
Old issuse? So why still nothing changed in the case, old but not outdated.
VAC isn't that easy to implement and I think we don't need that.
We just need feature to fight with them.
Either Gmod Devs should give us oportunity or make it on their own.

**Comment by thegrb93** [comment]
The only chance you 'might' get your cause considered is if you know exactly what feature is needed and can prove that no issues can arise from its addition.

**Comment by VaasKahnGrim** [comment]
is there any way to see what modules are loaded into the games process without having it see outside of the game process or be able to do anything other than simply get info about it?

Like for example, see all files loaded into the game process, their file size, and the file path. But not necessarily see the contents or interact with said files? I can imagine making a whitelist for client side files with this you could maybe determine if somebody were to have possibly injected some C++ cheats(assuming you could tell if the dll is loaded into the game)

If something like that were possible it would be potentially useful I'd think. Maybe a way to perform a crc check to make sure that its not simple a renamed file pretending to be something its not.

**Comment by thegrb93** [comment]
Nope. That's why external processes such as easy-anticheat have to running seperately.

**Comment by michak89** [comment]
This idea is half good and half bad, cheater can override any function and fake clean process, also crc check - any function.

**Comment by VaasKahnGrim** [comment]
Any way to prevent injections in the first place? Preferably without also killing the include function clientside. Maybe a means of retrieving a list of functions that exist in C++ along with the CRC michak89 mentioned.

You could have a pre-built list containing all C++ functions that should exist and be able to verify then with a CRC check. and if say the list returns a function that shouldn't exist it could simply boot the player from the server. maybe saying something like "Mismatch CFunction Table, remove any loaded C++ modules and rejoin."

The only issue I could think is maybe doing alot of CRC checks like this would probably take time and probably delay load time for players joining. that or if you need to scan again later it might be a bit intensive going through every C function in the game and verifying it.

So probably not the best idea but it is still an IDEA atleast. The Injection Detection/Prevention might be a better choice tho. I have no other ideas to share tho unfortunately.

**Comment by michak89** [comment]
"The Injection Detection/Prevention" what about prevention? Can process look for significant changes in itself and shutdown if found? I don't have answer to this one but making injections impossible would be a great option too. 

I'm sure the idea is here (or will be) and we can handle this problem together.
It will change Gmod forever.

**Comment by thegrb93** [comment]
Not to mention, anyone injecting a dll can just override any new lua function the devs add with the purpose of listing dlls to hide itself.

**Comment by michak89** [comment]
Yeah, without injecting we can detect all cheats by file.Read(), forced convars, functions crcs and @meepen 's ingenuity.  Not to mention, the point is to keep C code secure, lua easy peasy.

**Comment by michak89** [comment]
Simple solution to mentioned false positive is to deactivate whole system when server says it is unnecessary. (or allows client to load some binaries) But now we have another problem, how to send this information in secure way. Cheater could simply turn off protection by simulating such information about deactivated ac on secured servers   :I :cactus:

**Comment by GrandpaTroll** [comment]
> Tried to silently record demo on client and use it like overwatch - good idea, but time wasting process of watching demos... minus infinity for this one. Player/cheater can allways delete .dem files and sending them to server via net or http isn't very comfortable.

The one rule you should always do is **NEVER TRUST THE CLIENT**.

Anyways just get an anticheat that detect lua cheats while have admins to use their brains (sometimes unreliable) to detect c++ cheats.

**Comment by michak89** [comment]
There is one way. Serverside demo, overwatch feature. And lua functions to controll it. Server owner could decide if he wants to protect server and write simple reporting system. 

Months of thinking and boom - solution.

**Comment by VaasKahnGrim** [comment]
that solution probably won't work well. I can imagine it having alot of CPU usage on the server pretty easily.

the only real way I can think to catch cheaters effectivly is to use somethin with C++ clientside(which won't happen since facepunch is paranoid with security) or simply designing your gamemode files in a way where cheating is irrelevent in most cases(aimbot is pointless if your not supposed to be shooting other players or if your shooting somebody who's logically not visible, aka don't let players do damage for people behind walls and stuff)

**Comment by michak89** [comment]
Notice how cpu usage changes while recording clientside demo, and if you pause it and fly around You will also notice that whole map is recorded with even voicechat (not only 
 your point of view). I think it depends on demo tickrate.. Anyway, Your solution is not a solution just an idea of *something* I tried to project very long time with no effect. 

And about that "the only real way I can think to catch cheaters effectivly is to use somethin with C++ clientside" this is not 100% possible as we discovered in previous posts. Why do You think cs:go overwatch exists if magic code could catch them all.

**Comment by VaasKahnGrim** [comment]
overwatch is a thing because valve doesn't want the drama that comes from having a intrusive anti-cheat in their product and they make hell of bank of cheaters who get a new account and get their skins back with cash. its more profitable for them and doesn't hurt their image.

However imo the only effective anticheat is an intrusive one.

Tho it would be nice having SourceTV as an option too even if not used for anti-cheats and catching cheaters

**Comment by michak89** [comment]
I can't imagine any intrusive anticheat working with require(). This feature would only be avaliable for coders and server owners, small % of people. They won't waste months to invent such thing :/


Let's ask for something real, like SourceTv support. 
I fully agree with you, it's a great thing :)

**Comment by thegrb93** [comment]
You realize you won't see any cheats with sourcetv, right? The only hint you'll get is their view jerking around, which you can do already by spectating the player.

**Comment by VaasKahnGrim** [comment]
I mean overwatch would be useful for something competetive like TTT or something like that. tho personally I like the idea of using source TV for other things than cheat detection(mainly because why are people going to bother cheating on a roleplay server)

**Comment by thegrb93** [comment]
IIrc, people use cheats to sniff out the money printers and other goodies

**Comment by VaasKahnGrim** [comment]
yea but money printers are only in things like DarkRP and maybe Prison RP :p I've not seen a starwarsrp server or millrp server use them. but even then those things can usually be heard through walls so kinda a useless sniffer imo

**Comment by michak89** [comment]
Custom made printers usually kill such cheats, you can log every income and income sources. I'm not sure but it was a thing years ago. DarkRp creators has sv_allowcslua set to 1 in their gamemode by default and still only small % knows about it.

**Comment by Kefta** [comment]
This can be closed, this isn't really a specific feature request.
