### ISSUE TITLE
Next Update Thread

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-requests#1352]
Can we get a new next update thread to discuss GMod updates, please?

**Comment by CaskoChan** [comment]
Yes please

**Comment by VaasKahnGrim** [comment]
https://wiki.garrysmod.com/changelist/

**Comment by Kefta** [comment]
https://knockout.chat/thread/767

**Comment by mcNuggets1** [comment]
This was hard to find, thanks.
