### ISSUE TITLE
Possibility of getting something newer than DX9 for the game?

### ISSUE THREAD

**Issue by VaasKahnGrim** [Facepunch/garrysmod-requests#1355]
Been seeing a few github repos here and there about Vulkan and an SDK for it lately. I'd imagine theres also repos for DX12 aswell too. With some time the game could be updated to use the newer APIs. Given how old DX9 is I'd imagine a major boost would be gained from this.

Even if it needs testing still it could atleast be attempted in the x64 branch or as its own branch like Chromium.

**Comment by meepen** [comment]
The benefits of vulkan would be removed unless they finally implemented
multicore in the options menu. That's probably a block before this will
ever be considered.

**Comment by neico** [comment]
The entire engine is a blocker for Vulkan support...

**Comment by VaasKahnGrim** [comment]
what of DX12 or a newer version than DX9 atleast?

**Comment by robotboy655** [comment]
This has been discussed multiple times already (https://github.com/Facepunch/garrysmod-requests/issues/1267, https://github.com/Facepunch/garrysmod-requests/issues/802)

It would not give any benefit without redoing some if not all of the rendering engine to take advantage of new APIs.

More detailed answer:
https://web.archive.org/web/20190406220122/https://forum.facepunch.com/gmoddev/buuzu/Will-there-be-support-for-DirectX-11-12-or-Vulkan/1/
