### ISSUE TITLE
ENTITY:IsNextBot()

### ISSUE THREAD

**Issue by Dragoteryx** [Facepunch/garrysmod-requests#1356]
I know the current way to detect if an entity is a nextbot is to use ent.Type == "nextbot", but sadly a lot of people don't and because of this a lot of addons aren't compatible with nextbots. (because developers don't know how to tell if an entity is a nextbot or not, or assume IsNPC will return true on them)

And since updating ENTITY:IsNPC() to return true on nextbots would break a lot of addons, I think creating a new function called ENTITY:IsNextBot() is the best thing to do in that situation.

**Comment by SupinePandora43** [comment]
sometime i'm reimplement ENTITY:IsNPC() to return true if it's nextbot! lots of errors!
i think if addon developers will use NextBot base's (like Sean's NextBots), it will be easier for understanding other nextbots.

**Comment by Kefta** [comment]
``IsClientsideEntity`` would also be nice. They can be implemented in the meantime in Lua with

```
local ENTITY = FindMetaTable("Entity")

if (SERVER) then
	local NEXTBOT = FindMetaTable("NextBot")
	
	function ENTITY:IsNextBot()
		return getmetatable(self) == NEXTBOT
	end
else
	local CSENT = FindMetaTable("CSEnt")
	
	function ENTITY:IsClientside()
		return getmetatable(self) == CSEnt
	end
end
```

**Comment by robotboy655** [comment]
Added

**Comment by Kefta** [comment]
It should be IsNextBot to match player.CreateNextBot

**Comment by robotboy655** [comment]
It is NextBot, i just prefer typing Nextbot
