### ISSUE TITLE
Other entity outline/halo system

### ISSUE THREAD

**Issue by ShadowBonnieRUS** [Facepunch/garrysmod-requests#1357]
Maybe you know that standard halo system greatly reduces FPS if called many times for example for other colors on entities. And halo looks like glow. I make other system with better performance and looks like outline, not like glow (and still greatly visible on big distance).

Some screenshots:
![gm_construct0001](https://user-images.githubusercontent.com/49488893/59908739-6109dc80-940e-11e9-9f4d-63d22f5a407e.jpg)
![gm_construct0002](https://user-images.githubusercontent.com/49488893/59908745-6404cd00-940e-11e9-86ef-49438ddbb4f9.jpg)
![gm_construct0003](https://user-images.githubusercontent.com/49488893/59908749-66672700-940e-11e9-9e56-5daf3903a82e.jpg)

I can give code if you will like that idea.

**Comment by Dragoteryx** [comment]
You should probably make a pull request on the garrysmod github repo.

**Comment by ShadowBonnieRUS** [comment]
Okay
