### ISSUE TITLE
GM:OnPhysgunDropped()

### ISSUE THREAD

**Issue by WilliamVenner** [Facepunch/garrysmod-requests#1360]
`GM:OnPhysgunPickup()` is getting added to match `GM:GravGunOnPickedUp()`, so why not add `GM:OnPhysgunDropped()` to reflect `GM:GravGunOnDropped()`?

![](http://i.venner.io/brave_2019-06-29_12-35-42.png)

**Comment by robotboy655** [comment]
Because https://wiki.garrysmod.com/page/GM/PhysgunDrop already exists.

Yes I know the name consistency is garbage, nothing I can do about it.

**Comment by WilliamVenner** [comment]
Oh, my mistake. Thanks for this addition, by the way 👍👍👍👍
