### ISSUE TITLE
Disable the use of weapons with WorldClicker

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-requests#1361]
I used a nastyw orkaround to make weapons not do anything, while in WorldClicker mode, but it was patched.

Now a hook, function or anything to make weapons stop working in WorldClicker would be alright for me.

In multiplayer it can easily be abused, that's the reason I disabled it first hand.

**Comment by robotboy655** [comment]
> In multiplayer it can easily be abused, that's the reason I disabled it first hand.
Care to elaborate?

**Comment by mcNuggets1** [comment]
Oh yeah.
I already said.

I used a nasty workaround to disable the worldclicker function, but only making it work with the properties system.
(I already deleted it)
But it's patched now.

So a function or a hook to disable gun use would be good.

In multiplayer it can be abused by shooting in directions you don't even look using your cursor.
You can disorientate enemies this way.

**Comment by mcNuggets1** [comment]
https://pastebin.com/LwyjTRmQ
Disabling it this way doesn't work it seems.

**Comment by robotboy655** [comment]
```
hook.Add( "PreventScreenClicks", "PreventScreenClicks2", function()
	local pnl = vgui.GetHoveredPanel()
	if ( pnl:IsWorldClicker() ) then return true end
end )```
Works for you?

**Comment by mcNuggets1** [comment]
Yeah, this works.
I couldn't find it anywhere, sorry.
Thanks for the help.
