### ISSUE TITLE
re-add the player_missile entity from the hl2 beta

### ISSUE THREAD

**Issue by Aaron2550** [Facepunch/garrysmod-requests#1362]
hey, i think the player_missile entity would be really fun for phys maps and it would be fun to play around with friends. you can look at it here: [https://www.youtube.com/watch?v=NE_EkxHdD8E](https://www.youtube.com/watch?v=NE_EkxHdD8E)
Yes, its just like a rpg but there are some special use cases where you dont really wanna give the player a rpg.

**Comment by thegrb93** [comment]
Make it yourself with lua

**Comment by Aaron2550** [comment]
i would if i could, trust me

**Comment by robotboy655** [comment]
No, not interested in adding anything from the leak, definitely feels like mod territory.

This should be fairly easy to do in Lua with the drive system.
