### ISSUE TITLE
ENT:MoveToPos()

### ISSUE THREAD

**Issue by VaasKahnGrim** [Facepunch/garrysmod-requests#1363]
Digging through the wiki I was looking for something that would allow me to create some interesting new entities for my mapping projects. one thing I've found myself in need of is a function that would allow me to move an entity in a straight line to a specified pos without changing the angle it is facing.

For example just like the func_door entity does when you press USE on it or fire the open/close input and it sinks into the wall.

As a Side Note I'm still trying to find a function for making an entity not collide with world geometry but can collide with everything else including players or stuff like doors.

**Comment by thegrb93** [comment]
I recommend looking at the door source code and emulating it, https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/doors.cpp#L243

Garrysmod already has what you need to do this.

**Comment by thegrb93** [comment]
Just set movetype to MOVETYPE_PUSH and then SetLocalVelocity

**Comment by VaasKahnGrim** [comment]
that .cpp file feels like reading a fanfic on 4chan but I'll look into the SetLocalVelocity and MOVETYPE_PUSH

**Comment by Kefta** [comment]
You can also use https://wiki.garrysmod.com/page/PhysObj/ComputeShadowControl if your entity has a physobj.

**Comment by VaasKahnGrim** [comment]
Hmm, I think I might use the ComputeShadowController instead. it looks like I can do some other stuff with it aswell possibly. Thank you for showing me this.
