### ISSUE TITLE
Updating the Useragent for stuff involving http.Fetch() and http.Post()

### ISSUE THREAD

**Issue by VaasKahnGrim** [Facepunch/garrysmod-requests#1365]
Basically a means to fix a issue with Discord Webhooks and garrysmod. They apparently have the useragent for the game blocked via cloudflare. Changing the useragent to something differant but still identifiable as coming from garrysmod would be a big help.

Alternativly being able to define a useragent by string in the http.Fetch() and http.Post() functions would be useful aswell for anybody who would still need to be able to identify garrysmod Fetch/Posts from other attemps.

**Comment by robotboy655** [comment]
If we could change the UA string, and I am unsure if we can due the system using Steam's HTTP API which is fairly limited, the `HTTP()` function would just get abused again and the new UA would be blocked again, just like it happened the first time.

**Comment by meepen** [comment]
I think you should only allow setting the user agent server side and keep
it the default one that it is now clientside forever. Maybe add an option
to the global HTTP function, if it's even possible to change it in the
first place

**Comment by robotboy655** [comment]
Looking at the SteamHTTP docs, it would seem you cannot override the UA string, only add to it using `SetHTTPRequestUserAgentInfo`
https://partner.steamgames.com/doc/api/ISteamHTTP#SetHTTPRequestUserAgentInfo

**Comment by VaasKahnGrim** [comment]
Would it be possible to just get around it entirely with something like bromsock then somehow?

**Comment by robotboy655** [comment]
Considering what you want this for, the answer is no.
