### ISSUE TITLE
Easier Debugging with "developer 2" setting

### ISSUE THREAD

**Issue by VaasKahnGrim** [Facepunch/garrysmod-requests#1366]
Recently noticed this was going on and currently trying to find where this is originating from. but having it say which net msg is being spammed or even what file would be very useful for fixing things.

Right now its spamming net.Broadcast and net.Send very often and its begining to cause some issues for my server as idle CPU is actually noticable for once.

https://imgur.com/a/ZVqB6x0

**Comment by robotboy655** [comment]
Added the message name to those messages.
