### ISSUE TITLE
SecurePrompt (vgui) continued & SecureString (internals)

### ISSUE THREAD

**Issue by CaptainPRICE** [Facepunch/garrysmod-requests#1368]
(Warning: Advanced topic. thegrb93, don't bother if you still don't get it.)

As already stated in the original post, this requires a new special class (`SecureString`) and careful handling (on C-level).

_Originally posted by @willox in https://github.com/Facepunch/garrysmod-requests/issues/1367#issuecomment-513602871_:
> I think they don't work. You can open another issue if you actually come up with some sort of specification.

Alrighty, since you have asked for it. Let's dive into internals for better understanding.
I am assuming you're familiar with C# (due _S&box_). I'll be Windows-oriented mostly, but I am sure Linux has their own `SecureString` implementation similar to Windows.
So, let's begin, follow these link(s):
Here you can see how `SecureString` is implemented in .NET Framework (Windows-only implementation):
[SecureString.cs](https://referencesource.microsoft.com/#mscorlib/system/security/securestring.cs)
Here is Mono's version (Windows+Linux implementation | incomplete):
[SecureString.cs](https://github.com/mono/mono/blob/master/mcs/class/corlib/System.Security/SecureString.cs)
And here is .NET Core's version (it covers all operating systems supported by GMod; includes Windows+Linux+Mac implementation) - recommended:
[SecureString.cs](https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/Security/SecureString.cs)

Alrighty, getting started.
You can clearly see how it is implemented for Windows platform (see .NET Framework code). There are two main Win32 functions to deal with buffer encryption/decryption:
`Rtl*` [`advapi32.dll`] on Windows XP. `Crypt*` [`crypt32.dll`] on Vista and higher.
[RtlEncryptMemory](https://docs.microsoft.com/en-us/windows/win32/api/ntsecapi/nf-ntsecapi-rtlencryptmemory) / [CryptProtectMemory](https://docs.microsoft.com/en-gb/windows/win32/api/dpapi/nf-dpapi-cryptprotectmemory)
[RtlDecryptMemory](https://docs.microsoft.com/en-us/windows/win32/api/ntsecapi/nf-ntsecapi-rtldecryptmemory) / [CryptUnprotectMemory](https://docs.microsoft.com/en-gb/windows/win32/api/dpapi/nf-dpapi-cryptunprotectmemory)

# Design
Which I have briefly explained previously, goes (still WIP):
**SecurePrompt**
![SecurePrompt](https://user-images.githubusercontent.com/9789070/61650222-7c893100-acb3-11e9-89cd-951648eda55f.png)

## Coding our C++ `SecureString` class (and binding it to GLua)
// TBD

## Creating our "SecurePrompt" vgui control in Source engine
// TBD

# Example code/usage (GLua)
## (Client-side) HTTP example with Steam WebAPI
```lua
local question = "API key"  --- Question/Request to be displayed to the client (length should be limited internally).

-- ignore begin --
assert( isfunction( SecurePrompt ), "_G.SecurePrompt is missing" )
-- ignore end --

--- Note: SecurePrompt should be Singleton-based (only one vgui instance at a time).
---       Returns true if prompt has been created; otherwise, false to indicate existence of another SecurePrompt.
SecurePrompt(
    question,
    function( ud )  --- Completion callback to be run once the response is entered by client.

        -- ignore begin --
        assert( type( ud ) == "userdata", "input data is not userdata!" )
        -- ignore end --

        print( "input received:: " .. question, ud )  --- Note: GLua is unable to read the contents of userdata.

        --- TODO: Use ud with any function where security is due (i.e. HTTP)
        HTTP {
            method  = "POST";
            url     = "https://api.steampowered.com/ISteamUser/GetPlayerSummaries/v2";
            headers = {
                ["key"     ] = ud;  --- Would be read at C-level.
                ["steamids"] = "76561197960435530";
            };
            failed  =
                function( reason )
                end;
            success =
                function( code, body, headers )
                end;
        }

    end
)
```

**Comment by thegrb93** [comment]
We know how it works. We don't know how you intend it to work for gmod. What even is the point.

**Comment by VaasKahnGrim** [comment]
Couldn't people use modles such as gm_crypt aswell? The first thing that came to mind when reading this was that. Might be useful to look at. Not sure if relevent tho.

**Comment by meepen** [comment]
If all you want it to be for is http what's stopping someone from just
sending the not secure string to your own server

**Comment by meepen** [comment]
Also he asked for a spec and what you provided was nothing of the sort, if you have nothing why even make a new issue of you were going to just fill it in later

**Comment by thegrb93** [comment]
Encryption isn't even needed. He just wants a userdata that holds credentials that can be given to HTTP(), but he hasn't explained how this would be done in a way that isn't filled with security vulnerabilities.

**Comment by meepen** [comment]
Again nothing is stopping me from just giving it to my own webserver

**Comment by thegrb93** [comment]
Damn I was waiting to say that once it was the right time, but you spoiled it.

**Comment by CaptainPRICE** [comment]
Nice comments.

> Again nothing is stopping me from just giving it to my own webserver

(So, about serverside example.) You're *absolutely* right. There is nothing stopping you from misusing/phishing out server-side function.
I did want to point this out in the code comments, but oh well, it seems some of you still don't understand the main part.
Other than sending it to *your* webserver, an attacker could also use 3rd-party program (Wireshark) and then inspect the HTTP request (on the srcds).

But. You see, that's not the point of this. (Perhaps I should have simply avoided adding serverside function.)
Okay.. Let's put it this way, no more server-side functionality (`Player:SecurePrompt`). Let there be client-side only function `SecurePrompt`.
Now from security standpoint, do you see the main concern and goal of `SecurePrompt`?

**Comment by willox** [comment]
That isn't something I'm interested in protecting against

**Comment by CaptainPRICE** [comment]
> That isn't something I'm interested in protecting against

Fine. Off to binary module then.
