### ISSUE TITLE
game.GetIP()

### ISSUE THREAD

**Issue by HandsomeMatt** [Facepunch/garrysmod-requests#137]
Clientside:

    LUA_FUNCTION( GetIP )
    {
            INetChannelInfo* NetChan = g_EngineClient->GetNetChannelInfo();
            if ( NetChan != NULL ) {
                    const char* ipAddress = NetChan->GetAddress();
                    Lua()->Push( ipAddress != NULL ? ipAddress : "0.0.0.0" );
            } else {
                    Lua()->Push( "0.0.0.0" );
            }
            return 1;
    }

A shared function would probably be nice.

**Comment by willox** [comment]
http://wiki.garrysmod.com/page/game/GetIPAddress
