### ISSUE TITLE
Call GM:ScaleNPCDamage when a NextBot gets damaged

### ISSUE THREAD

**Issue by Dragoteryx** [Facepunch/garrysmod-requests#1371]
This is to my knowledge the only hook that lets you know when the entity gets hit on a specific HitGroup, and since nextbots already call `GM:OnNPCKilled` when they die and `SANDBOX:PlayerSpawn(ed)NPC` in sandbox, it would make sense that they also call `GM:ScaleNPCDamage` when taking damage.

You could also create a new hook called `GM:ScaleNextBotDamage` with the same arguments as `GM:ScaleNPCDamage` to avoid compatibility issues.

**Comment by robotboy655** [comment]
The `GM:OnNPCKilled` call is manually "faked" from Lua (https://github.com/Facepunch/garrysmod/blob/7c36de0558f42a4cd731bf16215193400e8c46a9/garrysmod/gamemodes/base/entities/entities/base_nextbot/sv_nextbot.lua#L146)

`SANDBOX:PlayerSpawn(ed)NPC` call is irrelevant to the NPC state, you can put literally any entity into the NPCs tab and when it will be spawned it will call the `SANDBOX:PlayerSpawn(ed)NPC` hooks.

So I am not sure if it should call `GM:ScaleNPCDamage`, a new hook, or if we should add a nextbot hook that would allow to emulate the hook. Ideas?

**Comment by Dragoteryx** [comment]
Maybe the hitgroup could be passed as a 2nd parameter for `NEXTBOT:OnInjured` and `NEXTBOT:OnKilled`.
```lua
function ENT:OnInjured(dmginfo, hitgroup)
  if hitgroup == HITGROUP_HEAD then dmginfo:ScaleDamage(3) end
end
function ENT:OnKilled(dmginfo, hitgroup)
  if hitgroup == HITGROUP_HEAD then
    -- play a headshot death anim
  else
    -- play a normal death anim
  end
end
```

**Comment by robotboy655** [comment]
Not possible, those hooks do not have such information, even internally. The hook would be ran before any damage is actually dealt.

**Comment by Dragoteryx** [comment]
Also I'm pretty sure at least a few SWEPs are using the `GM:ScaleNPCDamage` hook so if it called it for nextbots then those SWEPs would be compatible with nextbots.

**Comment by robotboy655** [comment]
I feel like adding a NEXTBOT hook is a better idea to allow emulating player related hooks as well, maybe defaulting the hook to call ScaleNPCDamage for the base nextbot.

**Comment by Dragoteryx** [comment]
Like `NEXTBOT:OnKilled` and the `GM:OnNPCKilled` hook then? Yes that makes sense.
So a `NEXTBOT:OnHitGroup` hook? Would the args be `dmginfo, hitgroup`, or just `hitgroup`?

**Comment by Dragoteryx** [comment]
Also it's kind of obvious but the `NEXTBOT:OnHitGroup` hook (or whatever it's called) should be called before `NEXTBOT:OnInjured`.

**Comment by robotboy655** [comment]
Added https://wiki.garrysmod.com/page/NEXTBOT/OnTraceAttack it calls to ScaleNPCDamage by default (https://github.com/Facepunch/garrysmod/commit/a803266e03f02ed67d2babe3fcd0c9f81daad407)

**Comment by Dragoteryx** [comment]
Thanks!
