### ISSUE TITLE
Changing engine.SetMounted() from menu state to shared

### ISSUE THREAD

**Issue by VaasKahnGrim** [Facepunch/garrysmod-requests#1372]
Would be very useful for compatibility reasons. We basically have a way of mounting addons but we have no way of unmounting an addon which makes things very annoying sometimes

**Comment by robotboy655** [comment]
There's a reason for this, unmounting can't be done. There's a reason there isn't a command to flush models or materials. This is the reason why the addon system rework was stopped being worked on according to @willox

**Comment by VaasKahnGrim** [comment]
Having the game by default run the command recursivly on all addons when disconnecting from a server an option? Would mean not having to worry about it not being in shared state anymore

**Comment by robotboy655** [comment]
The engine has no way to unmount content, its not designed to do so. Also `engine.SetMounted` has nothing to do with addons either way.
