### ISSUE TITLE
Add missing RT_SIZE enums

### ISSUE THREAD

**Issue by CornerPin** [Facepunch/garrysmod-requests#1373]
[imaterialsystem.h:533](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/public/materialsystem/imaterialsystem.h#L533)
`RT_SIZE_REPLAY_SCREENSHOT`
`RT_SIZE_LITERAL`
`RT_SIZE_LITERAL_PICMIP`

**Comment by robotboy655** [comment]
Added
