### ISSUE TITLE
Add the number of frames and the fps rate of a sequence to ENTITY:GetSequenceInfo

### ISSUE THREAD

**Issue by Dragoteryx** [Facepunch/garrysmod-requests#1375]
`ENTITY:GetSequenceInfo` returns a lot of useful information, but for some reason it doesn't return the number of frames a sequence has nor its fps rate.
```
activity    =    6
activityname    =    ACT_WALK
actweight    =    -1
bbmax    =    39.171135 62.932507 101.702057
bbmin    =    -79.435928 -65.362198 -7.337456
cycleposeindex    =    0
fadeintime    =    0.20000000298023
fadeouttime    =    0.20000000298023
flags    =    12289
label    =    walk
lastframe    =    0
localentrynode    =    0
localexitnode    =    0
nextseq    =    0
nodeflags    =    0
numblends    =    1
numevents    =    0
pose    =    0
```
This is what that function currently returns.

**Comment by robotboy655** [comment]
That's because sequences (mstudioseqdesc_t struct) don't have that information.

You can use `Entity.GetAnimInfo` which does provide that info.

**Comment by robotboy655** [comment]
Added "anims" field to GetSequenceInfo just for you.
