### ISSUE TITLE
Allow custom NPCs to have adjustable jump heights

### ISSUE THREAD

**Issue by epicplayer40** [Facepunch/garrysmod-requests#1379]
In Half-Life 2, some NPCs (Such as the fast zombie, hunter, antlion etc) have increased jump heights for navjumping larger distances. This is because of the NPC variables MAX_JUMP_RISE, MAX_JUMP_DISTANCE and MAX_JUMP_DROP being edited to be different from the standard NPC. These variables are found in CAI_BaseNPC::IsJumpLegal.

I am suggesting that these variables should be able to be overwritten for a custom NPC being made in LUA.

**Comment by robotboy655** [comment]
Assuming we are talking about SNPCs (base_ai), how does one make em jump?

**Comment by epicplayer40** [comment]
Well I'm referring to the jumping that occurs when NPCs use a hint node with the jump hint **(an example can be found on the top of the apartment building near spawn in gm_construct, where NPCs can jump down from the roof to the top room's balcony, it's easy to see if you have citizens following you or use a NPC mover tool from the workshop)**, and when they navjump to different elevations via ground nodes if they have the bits_CAP_MOVE_JUMP capability.

**Comment by robotboy655** [comment]
Added a binding for IsJumpLegal.
