### ISSUE TITLE
could we get a http.Listen() function added? (sorry for so many suggestions lately)

### ISSUE THREAD

**Issue by VaasKahnGrim** [Facepunch/garrysmod-requests#1382]
A function that would basically allow for the following:
`http.Listen(port,ip,func)`
 * port - the port to listen for connections on
 * ip - the IP that can connect to this port (Could also be a table of IPs to check incase you have multiple things that will be sending to this server)
 * func - a function that handles the data recieved in JSON table format

ServerA | IP is 192.168.0.4
`
http.Listen(80, "192.168.0.5", function(table)
    print(table.MSG)
    print(table.User)
    print(table.ID)
end)
`

Server B | IP is 192.168.0.5
`
http.Post("192.168.0.4:80",{msg = "Hello Server A!", user = "Some Playerss SteamID/64", ID = "some ID string of choice"})
`

This would be great for using http.post to send data directly to other servers. and if the server isn't using it data would be ignored if sent like normal. This could also help alot with middleman software such as websites that normally have a difficult time normally sending data between servers without having to use binary modules or really bad tick/think hooks to constantly check the software over and over.

Simply listening means those middle wares can just send when its time to send instead of constantly being checked or relying on modules that could end up breaking from a gmod update.

**Comment by meepen** [comment]
This could open huge vulnerabilities and add unnecessary bloat of libraries.

**Comment by thegrb93** [comment]
Use a module. This won't get added.

**Comment by thegrb93** [comment]
gm_sock will be your best bet probably.

**Comment by VaasKahnGrim** [comment]
if this would cause vulnerabilities then the module is no better and requires much more work to deal with but ok. any major differance between gm_socket and bromsock?

**Comment by thegrb93** [comment]
Look and see for yourself

**Comment by VaasKahnGrim** [comment]
I can't even find the repo

**Comment by robotboy655** [comment]
Basically duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1063
