### ISSUE TITLE
Add hooks for NPC:CurWaypointPos() and NPC:NextWaypointPos()

### ISSUE THREAD

**Issue by epicplayer40** [Facepunch/garrysmod-requests#1384]
Add these commands that return the vector of the current and next waypoint positions on a NPC's current path to it's goal. These vectors can be gathered from ai_route.cpp.
**IIRC these waypoints are the nodes that are connected to form a path to the NPC's goal if I'm not mistaken.**

**Comment by robotboy655** [comment]
Added
