### ISSUE TITLE
Compilation of File requests

### ISSUE THREAD

**Issue by GitSparTV** [Facepunch/garrysmod-requests#1388]
This request collects all existing opened issues about File object in the game.
#438, #1160, #1101 

What I choose to be in game:
- Ability to read/write (r+, w+, a+, rb+, wb+, ab+)
Source Engine has `r`, `w`, `a` ,`r+`, `w+`, `a+`, and `b` suffix. Missing the `+` suffix.
Purpose: to have more flexible writer code. For example skip some line to write after them (advanced append)
- IsEOF method
For code performance, to handle the reading process.
- :lines() for GMod
This can be done in Lua by `for line in f.ReadLine,f do` also in C lua_pushcfunction + lua_pushuserdata (or by C-iterator)
- Ability to choose `maxChars`
ReadLine has a limit of 8192

**Comment by robotboy655** [comment]
Don't create issues that are just a reupload of other issues.

**Comment by GitSparTV** [comment]
My issue also have my own item here. The last thing is not the reupload

**Comment by robotboy655** [comment]
Then make a separate issue if you think its a big problem, or add it onto an existing issue with similar theme.

**Comment by VaasKahnGrim** [comment]
@GitSparTV you can easily search through the issues using the text bar next to where it says 'Filters' on the issue page. for example adding 'websockets' will show you any issue opened relating to websockets. 

Chances are theres always a result for what your looking for since there are 619 currently open feature requests

**Comment by GitSparTV** [comment]
> @GitSparTV you can easily search through the issues using the text bar next to where it says 'Filters' on the issue page. for example adding 'websockets' will show you any issue opened relating to websockets.
> 
> Chances are theres always a result for what your looking for since there are 619 currently open feature requests

No tickets about `maxChars` limit. Also I mentioned:
> This request collects all existing opened issues about File object in the game.

**Comment by neico** [comment]
Size doesn't matter, what's important is that a single issue report is for a single issue (and with as much detail as possible)
It simply makes organizing things a lot easier

and by the way, the readme of this repo clearly states what's wrong: `Make sure the feature hasn't already been requested`
by batching things you clearly break that simple rule
