### ISSUE TITLE
Add ENTITY:AddCustomPhoneme()

### ISSUE THREAD

**Issue by Seamusmario** [Facepunch/garrysmod-requests#1390]
What the function does: Adds a phoneme file from the source engine and other mounted games to make lipsync work for other models.

**Comment by Jvs34** [comment]
I replied here https://github.com/Facepunch/garrysmod-issues/issues/3948#issuecomment-523582428

I'll also add something more, right now we can't play tf2 scenes as they're all packed inside tf2's scenes.image, and gmod can only use one at a time unless robotbot were to ship the 5000 vcds with garry's mod, but that's very unlikely to happen.

However it seems there are tools to extract tf2 vcds around the internet, and a tf2 gamemode on github has the vcds packed with the gamemode.
