### ISSUE TITLE
Replace the Physgun model with a refurbished tau cannon model 

### ISSUE THREAD

**Issue by TheAtomicChezz** [Facepunch/garrysmod-requests#1391]
Then it can finally match the weapon selector preview.

**Comment by VaasKahnGrim** [comment]
Better yet change the selector to blue and make it a plasma gun fitting for an Astartes lol

**Comment by robotboy655** [comment]
No. This is a job for addons if you want this. The selection icon is different so you can differentiate between Gravity gun and Physics gun without reading the text.
