### ISSUE TITLE
Simple ply:GetNoTarget() function request

### ISSUE THREAD

**Issue by VaasKahnGrim** [Facepunch/garrysmod-requests#1393]
Basically a function that would return true or false for a player in regards to this function being used on them(https://wiki.garrysmod.com/page/Player/SetNoTarget)

Would make things easier for determining if somebody needs to have ply:SetNoTarget() set to true or false without having to do some weird table for keeping track of who is set to what

**Comment by neico** [comment]
https://wiki.garrysmod.com/page/Entity/IsFlagSet + `FL_NOTARGET ` = ?

**Comment by VaasKahnGrim** [comment]
so something like say this?
`function IsNoTarget(pl)
    return pl:IsFlagSet(FL_NOTARGET)
end`
