### ISSUE TITLE
GMA Lua Module or functions for working with gmad in lua(shared)

### ISSUE THREAD

**Issue by VaasKahnGrim** [Facepunch/garrysmod-requests#1394]
Basically would it be possible to get lua functions for interacting with gma files clientside via the datafolder? I'd imagine this would be very useful for manually generating new GMAs on the fly for mod developers and also useful for some gamemode devs for managing content used for specific areas of a server such as dynamically adding generated models, generated materials and textures and so on into a physical file and have it organized aswell. then when its actually needed the specific gma can be mounted with game.MountGMA()

So a usage for gamemodes would be say, having players in the background generating the textures the saving into the gma in their data folder for a specific area of a map or for possibly future enemies in another area or something the have not encountered yet. this would mean they could have these things generated, saved and nolonger in use anymore until they are needed later. and when they are they are right there ready to mount on a moments notice when that specific player enters that area(for example placing a custom brush entity in the area that runs the mountGMA on the player that touched it if the gma isn't already mounted)

For example the following sort of functions maybe?

gma.Create(gma "path/filename.gma") - creates a gma in garrysmod/data/path/

gma.Delete(gma "path/filename.gma") - deletes a gma from the data folder

gma.AppendFile(gma "path/filename.gma", file "materials/pizza.vmt",string data) - Adds onto the end of a specific file inside a specific gma

gma.WriteToFile(gma "path/filename.gma",file "materials/pizza.vmt",string data) - Overwrites entire file in the gma with the data provided to it.

gma.RemoveFile(gma "path/filename.gma",file "materials/pizza.vmt") - removes a specific file from the gma, or if only a folder path is given rather than a file path it removes the entire folder and its contents from the gma

gma.AddFile(gma "path/filename.gma", file "materials/pizza.vmt") - adds a file into the gma

gma.AddDir(gma "path/filename.gma", file "materials/pizza.vmt") - adds a directory into the gma

gma.Info(gma "path/filename.gma") - lists all the filepaths currently contained in the gma file, for validation purposes and double checking things.

**Comment by ExtReMLapin** [comment]
get good and parse it yourself

**Comment by VaasKahnGrim** [comment]
Can't imagine any way to effectivly do it without using a clientside C++ module which ofcourse isn't really an option for everyone. besides simply pushing more functions that are in gmad would probably be alot easier for everyone.

as for lua, no clue where to begin with it

**Comment by ExtReMLapin** [comment]
Here is how I read all the filespaths  from a GMA

Here how it works with the filepaths 

You'll have to stick with the lua native file libs because it's much easier to work with it.


```Lua
local gma = file.Open(gma_path, "rb", "GAME")
local filelist = {}
```

I'll also need this function : 

```Lua
local function nextzero(file, _return)
	local byte = file:ReadByte()
	local str = ""

	while (byte ~= 0) do
		if (_return) then
			str = str .. string.char(byte)
		end

		byte = file:ReadByte()
	end

	if _return then return str end
end

```


I'll skip details and give you the answer then give you the documentation : 

`gma:Skip(22)` We don't need the first 22 bytes

Then there is 3 strings we don't need and since strings ends with a \0 ...


```Lua
	nextzero(gma)
	nextzero(gma)
	nextzero(gma)
```

And 4 extra bytes we still don't need 

`gma:Skip(4)`

Now you're at the file list.

Each entry starts with with it's number (a `long`) and from the end of the long to the next \0 (byte == 0)

It will be the file name, so you grab it this way : 

`local fileName = nextzero(gma, true)`

You don't need the 12 extra bytes so you keep going till the entre number is zero (the `long` i'm talking about right above

Here is how the code looks 


![](https://i.imgur.com/oLihmP9.png)


Now the documentation : 

https://github.com/garrynewman/gmad/blob/master/src/create_gmad.cpp#L60

(I'll comment with screenshot and arrows in few mins)

**Comment by VaasKahnGrim** [comment]
alrighty, I'll give it a shot and see how it goes with with reading some random gma and manually recreating it. thanks man :)

**Comment by ExtReMLapin** [comment]
@meepen I know you worked on it more than I did so if you got any protip, feel free to help

**Comment by meepen** [comment]
You can just copy the open source gmad library to create and extract your own (use util.Compress and Decompress for compression)

I don't know where my library is for my creation from Lua from files are atm

**Comment by VaasKahnGrim** [comment]
I mean I've messed around with that before but theres no real way to use that anywhere but serverside.

Was my main reason for suggesting something for lua clientside instead. tho I'm hoping when I get home I can make some progress with what lapin said so far

**Comment by meepen** [comment]
I used it clientside to mimic fastdl but in game

**Comment by ExtReMLapin** [comment]
Was bored, did something that might help ya : https://github.com/ExtReMLapin/glua_filestruct

**Comment by meepen** [comment]
Timestamp is Unix timestamp in 64 bits btw not double

**Comment by ExtReMLapin** [comment]
yes but there is no uint64/int64 read function so i just took a 64bit function to read it, better than nothing

**Comment by meepen** [comment]
You can ignore the upper bits they will basically always be zero until 2033
butt you should still store then as upper32_bits and lower32_bits

**Comment by robotboy655** [comment]
Not interested in this, and it can be achieved with Lua anyway.
