### ISSUE TITLE
Allow Half-Life: Source NPCs to use Death Animations

### ISSUE THREAD

**Issue by SupahMario** [Facepunch/garrysmod-requests#1395]
The only way to get these NPCs to use their death animations at the moment is to remove the ragdoll sequence within each model. It would be nice if these NPCs could use the death animations already included within the models alongside the normal ragdoll death behavior.

**Comment by robotboy655** [comment]
Why? I am not sure it is even programmed in for the HL:S NPCs.

**Comment by epicplayer40** [comment]
There is a boolean value called CanBecomeRagdoll in ai_basenpc.cpp. This is used for the Antlion Guard and Hunter's death animations which are followed by a ragdoll. I'd suggest adding a hook for this.

**Comment by robotboy655** [comment]
You can force this behavior already by running `AddFlags( FL_TRANSRAGDOLL )` on the desired NPC.

There are many problems with these death animations however, like NPCs will not despawn after dying (seemingly ever) and invisible collisions for certain NPCs preventing players from walking through.
