### ISSUE TITLE
Disable gravity on NextBots

### ISSUE THREAD

**Issue by Dragoteryx** [Facepunch/garrysmod-requests#1397]
I wanted to implement flying and wall walking on nextbots, but right now the only way to do that is to spam `SetPos` to make sure the nextbot doesn't fall to the ground. Being able to disable gravity on nextbots would be really useful.

Setting the velocity of the nextbot to `Vector(0, 0, 0)` doesn't work since the nextbots starts accelerating downwards in the next frame, so they end up falling slowly, but falling nonetheless.

**Comment by Roachdaripper** [comment]
Would be incredibly useful for the Licker nextbot I put on the workshop recently, since it can walk on walls and ceilings like the old replicators

**Comment by ZenkakuHiragana** [comment]
A hacky way to make flying Nextbots is calling self.loco:Jump() then self.loco:SetVelocity(desired_velocity).  I'm making [a flying Metropolice](https://youtu.be/006J7kOPz28) using this method.  It would be still nice if there were flying options for Nextbots though.

**Comment by Dragoteryx** [comment]
I know that technique but when using self.loco:SetVelocity(Vector(0, 0, 0)) whill slowly fall.

**Comment by robotboy655** [comment]
Added loco:SetGravity() default is 1000. In combination with `self.loco:SetVelocity()` to control the velocity this should give you exactly what you are looking for.

**Comment by Dragoteryx** [comment]
Is there a `loco:GetGravity()` function?

**Comment by robotboy655** [comment]
Naturally.

**Comment by Dragoteryx** [comment]
Nice! Thank you!
