### ISSUE TITLE
Breakable props advanced .qc setting

### ISSUE THREAD

**Issue by NicolaiSeven** [Facepunch/garrysmod-requests#1399]
Good day. 
I have 1 problem, 1 temporary fix(annoying) and 1 requesting feature. 
**1 problem** 
When a any breakable prop(breakable not via lua, via qc. file - $CollisionText and $KeyValues blocks) get any explosive damage prop will start to ignite and will burn until the prop is completely broken.

![89787945645123 (1)](https://user-images.githubusercontent.com/15887188/64059406-4bc7e000-cbff-11e9-8876-57651c8bd2a9.gif)

This occurs with standard $KeyValues block setting:
![image](https://user-images.githubusercontent.com/15887188/64059369-a3198080-cbfe-11e9-8610-a9020f91d7e7.png)

**1 temp fix**
So I tried make a small fix for breakable props, as saying in Valve Dev Wiki - breakable props have damage modifiers and **only** 3 values: dmg.bullet, dmg.club(like hl2 crowbar), dmg.explosive(any default hl2 explosive, rpg, grenade, etc).
So i make something like this(after field testing):
![image](https://user-images.githubusercontent.com/15887188/64059527-be39bf80-cc01-11e9-820c-175403028340.png)
Here is i set damage modifier "dmg.explosive 100" like as prop HP. This was help and partially fixed **1 problem**, but this setting is not realistic - breakable props **not start to ignite** but they **getting x2 splash damage** by explosive damage. It's really unrealistic and **very** annoying.

**1 requesting feature**
In next gmod update I would very much like changes and fixes with breakable props. That they do not start to ignite from explosive damage(as in Half-Life 2 - breakable props works right and has true behavior with explosive damage).
And also, if technically possible, add new types of damage modifiers **for props to using in .qc** as in the table(marked - unwanted modifiers):
![image](https://user-images.githubusercontent.com/15887188/64059697-eaa30b00-cc04-11e9-8f8e-241c1406317c.png)

**Comment by robotboy655** [comment]
1) False. It burns for a randomized amount of time,
Set the default explosive barrel's HP to 200 and apply 1 damage of `DMG_BLAST` and the prop will stop burning with around 128 HP left.
2) This behavior is **identical** to Half-Life 2. You can test it yourself by making a map and running it in both GMod and HL2, you can set the barrel HP via SetHealth input.
3) Definitely not adding `dmg.x` variants for all the different damage types. Props can't even accept a lot of those damage types naturally, like `drown` and `drownrecover`, not to mention this functionality is entirely controllable from Lua via the `EntityTakeDamage` hook.
