### ISSUE TITLE
Github page alternative for the gmod wiki

### ISSUE THREAD

**Issue by VaasKahnGrim** [Facepunch/garrysmod-requests#1400]
Would help for those rare moments when the wiki goes down or cloudflare is giving Error 524. I'd also imagine it would make it eiser for people to submit example usages of various functions and hooks for it aswell

**Comment by VaasKahnGrim** [comment]
a online PDF we could download would also be nice aswell for offline development

**Comment by robotboy655** [comment]
https://github.com/samuelmaddock/glua-docs

There are already community projects like that.

There definitely not gonna be a fucking PDF that needs updating every few weeks.
