### ISSUE TITLE
'GetModelMeshes' Not Useful Without a Way to Get a Model's Hard-Coded Bone Data

### ISSUE THREAD

**Issue by scnce** [Facepunch/garrysmod-requests#1404]
A function that returns the "true" positions of a specific model's skeleton relative to its origin is necessary to make sense of its vertex data given by `util.GetModelMeshes()`. Adding a function such as `util.GetModelBones()` or adding "default" bone data to the table returned by `util.GetModelInfo()` would be much appreciated.
All I'm looking for is a way to generate a table of data giving a bone ID and a matrix for each bone.

This might seem esoteric at first, but the solution is critical to making any use of  `util.GetModelMeshes()` for creating "Lua" versions of existing models, as is its intended purpose.
Show this to anyone with a good understanding of the rendering engine and model rigging, and they will know exactly why it's so important.

To explain some things: all models in the Source Engine have at least one single bone that all other bones and all vertices move relative to when the model is being rendered. All models also have at least _**one**_ "animation" that controls the bones. The animation tells where all bones should be and always controls the mesh. Even static props have a single-frame "idle" animation that controls the root bone at all times while the model is being rendered/simulated. The idle animation tells the engine where the root bone should be positioned relative to the model's origin and is active at all times, permanently making the model oriented _differently_ from its mesh alone, if the bones were not considered.
Here's where the problem is.

As an example, I was trying to create a fully-Lua version of the elite Combine soldier model using the data given by the new function, just to test things. This was supposed to simply be a "Lua-scripted" version of the model, while the soldier was standing in the familiar default at-rest animation where his gun lowered. However, to make the soldier stand in the correct pose, I need to know where the bones are located relative to the model origin _**outside of any animations**_, including the idle animation. I created a whole rendering and rigging system that takes weight mapping and everything else into consideration for the vertices. However,  there is no way to get the mesh correct and actually render it in-world without knowledge of where the bones are hard-coded to be in the model.

As a simpler example, a very large number of models used by Source Engine games have the model rotated 90 degrees by the idle animation, which is simply telling the root bone to stay at a 90-degree angle relative to its "true" hard-coded position, at all times. When you recreate the model in scripted form using the vertex data, there's no way to keep it at the same angles as the original model without knowing the bone data in the model.
As of right now, there is no way to determine the root bone's defined origin _outside of the idle animation_ (with the exception of some unreliable and insufficiently functional hacks).

The function `util.GetModelMeshes()` allows for the vertex data of the whole model to be accessed, but the vertices are all given relative to the model origin. To find where the mesh should be positioned in the world, you must know where the root bone is supposed to be relative to the model origin. All available methods for retrieving bone positions give the positions of the bone _**when the animations are applied to the model**_. **To render and position the model correctly, the "true" positions of the bones relative to the same origin as the model's vertices must be known.**

**Comment by scnce** [comment]
In other words...
![fshhd](https://user-images.githubusercontent.com/5619290/64367868-07fe1d80-cfe7-11e9-8ec9-2e480db5a3a9.png)

**Comment by 100PXSquared** [comment]
@robotboy655 is there any kind of ETA on this? `util.GetModelMeshes` provides bone weights, but with no good way to use them without really hacky and ineffective methods (currently having to create a copy of each entity, make sure it's in the player's view, and cache the transforms of the bone matrices of that localised to object space to use as the bind pose).  

Just needs an extra field in the returned table for the default bone positions, which wouldn't take much extra stack code beyond what you're already doing for the submeshes, and would make the function actually usable for more than just props (of which some are also rotated from their model origin, so it doesn't work for those either, an example being the GMod logo prop)

**Comment by robotboy655** [comment]
Added a second argument to util.GetModelMeshes - a table of tables where IDs are boneIds and contain a table of 2 keys: matrix and parent.

The matrix is the direct "poseToBone" matrix from the engine. There's still no way to get animation data from a model which is probably what you actually want to fix your rotation issues, etc, I don't know where that data even lives in the engine.

**Comment by 100PXSquared** [comment]
Making a test implementation now

**Comment by robotboy655** [comment]
Then I am considering this fulfilled. It will be made available on x86-64 within this week.
