### ISSUE TITLE
Net Message packet structure Documentation

### ISSUE THREAD

**Issue by VaasKahnGrim** [Facepunch/garrysmod-requests#1408]
Could we possibly get a bit of doccumentation regarding the structure of a packet being sent from a server to a client and viceversa?

For context, I'm looking at a packet for a net message in wireshark right now(I have confirmed that it is the net message as it contains the string I sent to my client from server) parts of it are clear and easy to read, however there are bits around the string that don't make any sense at all(basically missing characters and shapes) the packet currently being viewed as hexidecimal.

Being able to know what sections are what like how the valve wiki does for some things would help quite alot.

**Comment by meepen** [comment]
Source engine is open source... Go look at the source code and figure out what you need... Garry's mod is not open source

**Comment by VaasKahnGrim** [comment]
The only problem there is I don't know where to look in source engine and the only thing valve seems to have on their wiki is usermessages but those are deprecated.

**Comment by robotboy655** [comment]
Not gonna bother answering this on feature requests repo.

**Comment by VaasKahnGrim** [comment]
I would have put the suggestion on the gmod-wiki-requests repo but there isn't one. Not really any other place for me to go and likely get an answer or response but here :/

**Comment by meepen** [comment]
Why do you need it exactly? And what parts do you need help with

**Comment by thegrb93** [comment]
For sniffing stuff :v

**Comment by VaasKahnGrim** [comment]
well so far I've got this from wireshark. I placed the exact string into the net msg to be sent over however there are bits before and after the string which I have no idea what their purpose is. I want to be able to know what those bits purpose are and what they represent. Just like valve does for data contained inside map lump files.

https://pastebin.com/6Lhkn3Yu

**Comment by VaasKahnGrim** [comment]
as for why I need it I'm trying to make it where I can send net messages from a seperate application rather than just srcds. So lets say I had a seperate application running on a differant machine and it was being used for handling alot of things seperatly from srcds, I'd be able to simply build a net msg and send it to a client directly instead of having to bounce between differant machines before it ever gets to the intended location. This meaning that I wouldn't need to have an additional module on the srcds end, and I would also be able to have alot less work running on srcds.

It would be easier having a sort of listen function clientside for http library but unfortunatly the closest thing I can think of is net.Recieve() the only issue is, I have no idea what the packet structure is in order to make a packet atm.
