### ISSUE TITLE
Add AcceptInput support for Nextbots

### ISSUE THREAD

**Issue by Roachdaripper** [Facepunch/garrysmod-requests#1409]
I did ask for this before, but for a different reason, and ended up getting HandleAnimEvent and FireAnimationEvent support, which is great, but that's not this request.

I'm looking to get hammer to be able to fire inputs to nextbots, I can do this by force-spawning the entity as an OBSOLETE, and manually adding a "targetname" value after turning off SmartEdit, using this, the nextbot not only spawns, but can have inputs fired off to it.
However, since AcceptInput doesn't currently do anything on nextbots, they can't recieve the input and run code based on it.

Could this be added?

**Comment by robotboy655** [comment]
All Scripted Entities already have `ENT:AcceptInput` support.

**Comment by Roachdaripper** [comment]
> All Scripted Entities already have `ENT:AcceptInput` support.

In my tests, firing the "Wake" input and trying to accept it on the nextbot does nothing.

**Comment by robotboy655** [comment]
Post the code you have tried. Keep in mind AcceptInput only works serverside.

**Comment by Roachdaripper** [comment]
```
function ENT:AcceptInput(e)
	if e == "wake" then
		self:CallInCoroutine(function(self, delay)
			if delay > 0.1 then return end
			self:Timer(0.5,function()ents.FindByName("logic_relay_breakwalls")[1]:Fire("trigger")end)
			self:PlaySequenceAndMove("310"..math.random(2))
			self:SetAIDisabled(false)
		end)
	end
end
```

from the VMF in a func_button
```
	connections
	{
		"OnPressed" "test_tyrant,wake,,0,-1"
	}
```

**Comment by Roachdaripper** [comment]
Regarding the custom code in the input, it works in the context of the nextbot as it uses a custom base

**Comment by Roachdaripper** [comment]
@robotboy655 i can provide the nextbot in question and the bsp/vmf file if you want

**Comment by Roachdaripper** [comment]
Just did some further testing via adding prints and yeah the function doesn't seem to be called at all.

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/64616540-724aff80-d3e5-11e9-8743-aedf5052bcf8.png)
(using entity.Fire)

![image](https://user-images.githubusercontent.com/3299036/64616771-e685a300-d3e5-11e9-907c-f47917c18a1e.png)
(using a map with "obsolete")

It 100% works. Make sure you are not overwriting your AcceptInput hook, and that your targetnames are all correct.

![image](https://user-images.githubusercontent.com/3299036/64616911-1e8ce600-d3e6-11e9-8849-2c39011b8e96.png)
![image](https://user-images.githubusercontent.com/3299036/64616936-29e01180-d3e6-11e9-931d-5b3bbc748e84.png)
