### ISSUE TITLE
A clientside means of recieving a msg from a webserver and handling it in lua.

### ISSUE THREAD

**Issue by VaasKahnGrim** [Facepunch/garrysmod-requests#1410]
http.Post() and http.Fetch() aren't reliable for recieving a connection at a undetermined time.

Net Library only recieves from the server and attempts to figure out how to send a net message from elsewhere has failed to produce results even after talking to multiple people for advice.

A C++ module is also not an option as you guys won't allow us to FastDL them to clients due to security issues and hoping for a client to have it installed or be willing to install it, or trusting that they don't install something else with the same name as the module(let alone the average person knowing what they are doing in the first place when they do)

Could we get something that just listens for a connection made and then handles it when it arrives on a client?

**Comment by robotboy655** [comment]
You basically want sockets (and on client?), and the answer is no. Why do you need it on client anyway?

**Comment by robotboy655** [comment]
Also duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1063 basically.

**Comment by VaasKahnGrim** [comment]
> You basically want sockets (and on client?), and the answer is no. Why do you need it on client anyway?

well for one if it were on the client I could utilize multiple machines alot easier without having to do hacky shit to get it to work in the first place. Basically making it where I can have one machine handle networking for entity logic asides from maybe usergroup related check and stuff, another machine used for handling large amounts of info being sent to a client(such as say text screens that are likely to change very often) aswell generally anything could be ran on it then without having to run it on the same machine as srcds.

even if it were on the same machine it would be pretty damn useful to be able to have a second process able to handle some work while srcds does its own thing. http.fetch and post can only really handle so much and isn't really fit for sending a msg to a client at any given time like the net library is. thats why I was asking about the net message packet structure being added to the wiki before, because then you guys wouldn't have to do anything and we could effectivly have what we needed to do things like this

Also that issue has been open since 2017, I don't have faith that you guys at facepunch ever check back on any of those :/

**Comment by VaasKahnGrim** [comment]
At this point if its never going to get added in can we atleast get a legit answer as to why? Because even simple web browsers have websockets clientside and serverside and its been like that for years. If it was going to be a security issue adding it to the client for gmod then pretty much the http library aswell is already a security risk aswell :/

Like I just don't see why something as simple as this has been ignored for 2 years and is met with a flat out no with no further explanation as to why not.
