### ISSUE TITLE
Suggestions for Lua error notifications

### ISSUE THREAD

**Issue by KirbyJoe** [Facepunch/garrysmod-requests#1418]
In Garry's Mod, when the Lua error occurs, the "errors.lua" file gets a callback and shows a notification. I have the ideas for the error notifications to make them more convenient for both players and devs.

**Optional Notification Sound:** When a error notification is displayed, the sound will play to make the players easily notice it.
**Optional auto-feedback for Workshop addons:** On the few occasions, the Workshop addon continuously and rapidly creates the same error. When the game detects a continuously created errors, the automatically generated feedback for the addon will send automatically with the message "Sended an automatically generated feedback for the addon "(Addon Name)" due to continuously created errors" for the dev's convenience. The feature can be enabled per-addon (I think it's hard to implement it because sometimes when the same automated feedback has sended by many users, it will considered as spam).
**Addon confliction notifications:** Some errors are caused by the addon confliction. The confliction is currently only noticeable on the console. I think the addon confliction should more noticeable to the players by showing the special message for that. When the addon confliction occurs, the following message will display: " "(Addon Name A)" and "(Addon Name B)" is creating possible conflicts, check the console for details".

**Comment by VaasKahnGrim** [comment]
could probably be done using ```
hook.Add('OnLuaError','MenuErrorHandler',function(str,realm,addontitle,addonid)
    --CODE HERE
    surface.PlaySound('soundfolder/file.mp3')
    FunctionToSendErrorToWeb()
end)
```
I'd imagine you could also have this send errors about an addon to a 3rd party webserver aswell to better help developing it. Including which server the error came from to make it easier to contact them about it and help fix things.

the feedback spam issue could be solved with something like say counting how many times an error has been sent within a few seconds and if its spamming then lock the sending feedback feature(or maybe remove the offending hook.add that its coming from and replace it with one notifying the server of what happened and why a feature was temp disabled) Should go back to normal on a map change or lua refresh.

you could also probably do something for the addon conflict thing by using the IsMounted() function
https://wiki.garrysmod.com/page/Global/IsMounted

it might not detect everything that will have possible conflicts but it can atleast be used to notify about known conflicting addons to the server owner.

**Comment by Kefta** [comment]
``Optional Notification Sound`` - this would be very annoying for errors that occur every tick, and I honestly don't see much of a point. Visual notifications are ample imo.

``Optional auto-feedback for Workshop addons`` - https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/menu/errors.lua#L14-L31
There also used to be an official error logging page that would host all workshop errors incurred by users, but I believe it was taken down some time ago. Steam workshop doesn't really have a facility for auto-feedback to my knowledge, so I'm unsure of the feasibility of an official mode of error reporting.

``Addon confliction notifications`` - this would be somewhat hard to detect as the majority of conflicts stem from using the same unique identifier. For hooks, net messages, convars, and entity callbacks, a ``developer`` warning message about duplicitously registered identifiers could be added, but it would probably be impossible for Lua key conflicts (``util.SomeCustomFunction() existing in multiple addons with differing definitions``) without modifying GMod's LuaJIT build.

**Comment by KirbyJoe** [comment]
@Kefta The official error logging page is also mentioned at #355. At the issue, they are talking about the replacement of the page. I think reviving the error logging page is also a good idea...

**Comment by thegrb93** [comment]
That would be a form of DDOS

**Comment by KirbyJoe** [comment]
@thegrb93 In #355, @robotboy655 references #149 and he suggests adding a Lua hook for errors to avoid DDoS.

**Comment by SupinePandora43** [comment]
when error occurs every tick it spams errors in console.
1: remove console limit
or
2: hide spamming in console
3: special vgui window for looking at errors

**Comment by robotboy655** [comment]
I kinda like the idea of a separate GUI for logged errors, perhaps even not just Lua errors. Maybe it can even replace console messages altogether for Lua errors? Dunno.

I also had an idea to make a "Problems" menu near the mountable games and shit, a pop up that will tell you about common problems such as bad cvars for mouse issues, Unused .GMAs listing, etc
 with a one-click fix button.

Maybe something to experiment with in my Lua menu replacement.

**Comment by SupinePandora43** [comment]
@robotboy655 , it's challenging me ! i want try to do this!

**Comment by thegrb93** [comment]
4: fix your lua errors

**Comment by SupinePandora43** [comment]
@thegrb93 errors existed, existing, and will exists!
there's no way to fix all errors! 
###### remove lua = remove errors

**Comment by KirbyJoe** [comment]
@SupinePandora43 Removing lua will also result the addon not function normally. Removing lua is not a good solution.

**Comment by robotboy655** [comment]
The Problems panel was added in the March update.

**Comment by SupinePandora43** [comment]
> The Problems panel was added in the March update.

Can i clear lua errors in that panel?

**Comment by robotboy655** [comment]
Not yet, but not a bad idea.
