### ISSUE TITLE
option to change where player voice/text chat and net library are sent to

### ISSUE THREAD

**Issue by VaasKahnGrim** [Facepunch/garrysmod-requests#1419]
Basically allowing for changing what IP/url the client sends messages relating to Chat and Voice.

Would make things pretty easy for handling cross server tasks.

For voice and text chat, sending to a seperate destination using a replicated cvar could make things pretty easy for having those two things handled on a seperate service. It would also help with having an expensive GM:PlayerCanHearPlayersVoice() hook. Having a seperate $5 VPS simply for Voice and Text would make things alot less impacting. It would also let people have a chance to create their own means of handling who can hear who.

For net library net.Send('MSG_NAME','127.0.0.1') --Useful for sending things directly to a specific place rather than only to srcds(if no IP is included then default send to srcds)

Lowkey this would be much easier with a clientside way of using websockets with ease but at this point I'm sure I'd just get ignored again and not be given any explanation or linked to some old thread that never got put into the game from years ago

**Comment by meepen** [comment]
That's not even possible

**Comment by VaasKahnGrim** [comment]
I mean it can be possible, like legit just a socket connection to machine 2 for voice and chat and then handle it accordingly there instead of on machine 1.

and kinda the same for the chat stuff and net.Send()

**Comment by robotboy655** [comment]
This is simply not gonna happen. It is a very niche request, and IMO a silly one at that.

**Comment by VaasKahnGrim** [comment]
everythings a nice request to you tho

**Comment by Kefta** [comment]
This is incredibly niche though.

**Comment by VaasKahnGrim** [comment]
true, your not wrong there
