### ISSUE TITLE
Add a clientside implementation for Entity:Get/SetLightingOriginEntity

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#1421]
https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/se2007/game/client/c_baseanimating.h#L561

The client variable is synced with the server's - I have no idea why there is only a serverside method implementation.

**Comment by robotboy655** [comment]
I didn't make a clientside bind because it is a networked variable. Do we really need another case like https://github.com/Facepunch/garrysmod-issues/issues/3362 ?

**Comment by Kefta** [comment]
The getter should at least be added shared so we don't have to use GetInternalVariable.

**Comment by robotboy655** [comment]
Yeah that should be easy, the idea behind the function is to provide alternative to the input so you don't have to specify a name for the entity.
