### ISSUE TITLE
Add Entity:Get/SetLightingOriginRelativeEntity

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#1422]
Used to transform the base lighting origin position of the entity, it's restricted to info_lighting_relative entities in the input functions but the client code can be altered to allow the use of any entity in the same way as the primary origin.

```
		// In C_BaseAnimating::OnInternalDrawModel
		CBaseEntity *pRelativeOrigin = m_hLightingOriginRelative.Get();
		C_InfoLightingRelative *pInfoLighting = dynamic_cast<C_InfoLightingRelative*>( pRelativeOrigin );

		if ( pInfoLighting != NULL )
		{
			pInfoLighting->GetLightingOffset( pInfo->lightingOffset );
			pInfo->pLightingOffset = &pInfo->lightingOffset;
		}
		else if ( pRelativeOrigin != NULL )
		{
			VectorCopy( pRelativeOrigin->GetAbsOrigin(), pInfo->lightingOffset );
			pInfo->pLightingOffset = &pInfo->lightingOffset;
		}
```

Clientside implementations can also be made here.

**Comment by robotboy655** [comment]
Looking at https://developer.valvesoftware.com/wiki/Info_lighting_relative I feel like we should not add this at all.

It's essentially same as SetLightingOrigin but worse, isn't it?

**Comment by Kefta** [comment]
Yeah never mind, this is useless. I thought it acted in coordination with SetLightingOrigin as a modifier so that multiple entities could share a single origin while having individual relative control entities, but I misread the l_studio code.
