### ISSUE TITLE
Add VMatrix:Zero/IsZero

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#1425]
Already exists for vectors and angles.

**Comment by robotboy655** [comment]
Is that actually useful though?

**Comment by Kefta** [comment]
Yes, null matricies are pretty common. My specific use case is a Lua implementation of the least squares algorithm where the zero matrix appears when there is a perfect fit (R=0). It would be much more efficient to have IsZero to check if the matrix is a zero matrix instead of checking each element.

**Comment by thegrb93** [comment]
Considering there's bound to be floating point error, you would need to check within a certain epsilon. I think such a generalized method would need to be user implemented instead of an IsZero method.

**Comment by Kefta** [comment]
This is not a problem with Lua doubles with the range of inputs I'm using for my least squares.

**Comment by thegrb93** [comment]
VMatrix uses floats
