### ISSUE TITLE
Add Player:GetLastWeapon

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/garrysmod-requests#1432]
https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/src_main/game/server/player.cpp#L377

There is not a dedicated function for this yet. It would be nice to have one instead of using GetInternalVariable("m_hLastWeapon")

**Comment by robotboy655** [comment]
Added Player.GetPreviousWeapon()
