### ISSUE TITLE
Add EntityTookDamage hook

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#1434]
Should be called after EntityTakeDamage successfully passes. This is needed to detect if damage is actually applied to an entity, which EntityTakeDamage cannot do since a function down the line of hook calls could block the event.

Could also be named PostEntityTakeDamage.

**Comment by Verideth** [comment]
My idea on how to handle this currently without `PLAYER:EntityTookDamage`

You could hook `GM:EntityTakeDamage(ply, dmg_info)` then use `if (dmg_info:GetDamage() >= 1) then /* do stuff here */ end` to check if any damage is done.

**Comment by robotboy655** [comment]
Added it as `GM.PostEntityTakeDamage( ent, dmginfo, tookDamage )`

`tookDamage` is a boolean which tells you whether the damage was actually taken. (i.e. shooting a rollermine won't actually damage it, but the damage event is still passed onto the entity)
The hook won't be called if the damage was blocked/filtered out before `EntityTakeDamage` is even called, for example if it doesn't pass the internal `PassesDamageFilter()` or `EntityTakeDamage`
