### ISSUE TITLE
Add $phongdisablehalflambert

### ISSUE THREAD

**Issue by CaptainBigButt** [Facepunch/garrysmod-requests#1439]
The material parameter $phongdisablehalflambert was made available starting in the Alien Swarm branch.

Since recent changes from September come from the same branch it should hopefully be accessible.

Just copying all updated shaders over would be ideal but if that'll cause issues then at least the $phongdisablehalflambert parameter would be very useful.

**Comment by Kinyom** [comment]
Any updates on this?

**Comment by robotboy655** [comment]
Added on `dev` beta.
