### ISSUE TITLE
Steam Gameserver Accounts

### ISSUE THREAD

**Issue by 4bdul** [Facepunch/garrysmod-requests#144]
Utilize the new "sv_setsteamaccount" on Garry's Mod for server favorites migrations.

Please see thread link below for a quote of Valve Mailing List in regards to this new feature.
http://facepunch.com/showthread.php?t=1359894

**Comment by Rhys** [comment]
Bump.

**Comment by Rhys** [comment]
Bump. @robotboy655

**Comment by Jvs34** [comment]
This can only be enabled once @UnderscoreKilburn updates the steam sdk as it's using a really outdated one.

**Comment by P4sca1** [comment]
This would be great! :+1:

**Comment by JohnCenaFWKZT** [comment]
This would be amazing @UnderscoreKilburn @robotboy655 @garrynewman

**Comment by robotboy655** [comment]
Added in Dev

**Comment by Rhys** [comment]
I love you.
