### ISSUE TITLE
Add option to adjust ladder climb speed, possibly per-player

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/garrysmod-requests#1440]
The ladder climb speed is currently hardcoded at 200 units in https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/shared/shareddefs.h#L103

The best option would be functions like Player.SetLadderClimbSpeed / Player.GetLadderClimbSpeed to adjust the ladder climb speed individually for each player, defaulting at the current 200.

**Comment by robotboy655** [comment]
Since this alongside #1231 require networking changes, so I can't commit it right now, but I will add these 2 whenever we do a network change update.

**Comment by robotboy655** [comment]
Added in the next update which ships tomorrow.
