### ISSUE TITLE
Add a hook for controlling gmod_suit

### ISSUE THREAD

**Issue by TheMostUpset** [Facepunch/garrysmod-requests#1449]
Could we get a hook for controlling gmod_suit stuff? E.g. I want the suit voice but don't want sprint/oxygen stuff. A hook for enabling/disabling that would be useful.

**Comment by robotboy655** [comment]
Not a hook for sure, also I don't think I am interested in adding this.

**Comment by thegrb93** [comment]
Yah we don't need hooks controlling every aspect of every hl2 entity.
