### ISSUE TITLE
Super small Sandbox request

### ISSUE THREAD

**Issue by NiandraL** [Facepunch/garrysmod-requests#145]
A side-ways scroll bar would be useful for the Sandbox Q menu, as if you are going through many folders, it starts to get cut off and the names cannot be read.

For example, here is me going through TF2 folders. I can't see the folder or full model name:
![image](https://f.cloud.github.com/assets/6342762/2099450/3c56d9f6-8f3c-11e3-87e4-d3417932ce4a.png)

**Comment by robotboy655** [comment]
I guess this is mostly resolved by allowing the list to be wider.
