### ISSUE TITLE
Adding/Fixing back monster_flyer and monster_flyer_flock idle sounds

### ISSUE THREAD

**Issue by Akis-02** [Facepunch/garrysmod-requests#1455]
the npcs monster_flyer monster_flyer_flock don't play sounds, even tho the sounds are included in the sound scripts (which don't really do anything) as FlockingFlyer.Idle and FlockingFlyer.Alert

**Comment by robotboy655** [comment]
They are disabled on purpose in code by Valve, and I am not sure we want them back, but I guess I will re enable them for now.
