### ISSUE TITLE
Make util.JSONToTable work with prettyPrint .json

### ISSUE THREAD

**Issue by Nogitsu** [Facepunch/garrysmod-requests#1457]
I don't really know if it's a bug or anything else, but util.JSONToTable() on a JSON written with util.TableToJSON( any_table, true ) always returns nil, it should be freaking usefull to get it working correctly. ☺

**Comment by robotboy655** [comment]
Care to give us an example table that causes this problem? I cannot reproduce this:
```
] lua_run PrintTable( util.JSONToTable( util.TableToJSON( { "test", "test2", { test3 = true } }, true) ) )
> PrintTable( util.JSONToTable( util.TableToJSON( { "test", "test2", { test3 = true } }, true) ) )...
1	=	test
2	=	test2
3:
		test3	=	true
```

**Comment by robotboy655** [comment]
Also wrong repository, this one is for requests, not bug reports.
