### ISSUE TITLE
Improve math.IntToBin efficiency

### ISSUE THREAD

**Issue by GitSparTV** [Facepunch/garrysmod-requests#1463]
https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/includes/extensions/math.lua#L30-L33

Current implementation:
```lua
function math.IntToBin( int )
	local str = string.gsub( string.format( "%o", int ), "(.)", function ( d ) return intbin[ d ] end )
	return str
end
```

New suggestion:
```lua
function math.IntToBin(int)
	return (string.gsub(string.format("%o", int), ".", intbin))
end
```
Changes:
- GMod's IntToBin creates new closure each call, instead use table directly since string.gsub accepts tables for lookup. (`FNEW` bytecode is not JIT-able, hence the whole function is not JIT-ed, my solution is JIT-able with stitch)
- Removed parenthesizes in the pattern because it's useless and it eats performance.
- Instead of localizing, return results directly but wrap them in parenthesizes to return only first value (No changes in bytecode, but faster parsing)

Benchmark tests:
> GMod math.IntToBin: 0.65494 (Min: 0.50243, Average: 0.53948) second(s) (216.89852%)

> New math.IntToBin: 0.30196 (Min: 0.24653, Average: 0.26326) second(s) (100%)

Compatibility was tested for numbers from -(2^20) to 2^20, both for equality and back-conversion.

**Comment by robotboy655** [comment]
Why is this here? Why is this not a PR?

**Comment by GitSparTV** [comment]
If this required: ok. I just wanted to save space without forking whole repo

**Comment by thegrb93** [comment]
Cuz pr's get stuck in review hell

**Comment by Kefta** [comment]
I used a different implementation in https://github.com/Facepunch/garrysmod/pull/1477 to prevent the output string from being in multiples of 3. My implementation is definitely slower than yours, but the question is if that behaviour should be maintained or not.

**Comment by GitSparTV** [comment]
@Kefta When you convert binary made by this function tonumber(...,2) returns normal number

**Comment by Kefta** [comment]
Yes, both of our functions do that, but I'm saying that mine doesn't append extra 0s to the string like IntToBin currently does.

**Comment by ExtReMLapin** [comment]
Can confirm, FNEW isn't jit-compiled : 

lj_record.c:2448

```C
    /* fallthrough */
  case BC_ITERN:
  case BC_ISNEXT:
  case BC_UCLO:
  case BC_FNEW:
    setintV(&J->errinfo, (int32_t)op);
    lj_trace_err_info(J, LJ_TRERR_NYIBC);
    break;
```

NYIBC stands for **N**ot **Y**et **I**mplemented **B**yte**C**ode

**Comment by GitSparTV** [comment]
@Kefta PR has better implementation https://github.com/Facepunch/garrysmod/pull/1477
Closed
