### ISSUE TITLE
New functions/features

### ISSUE THREAD

**Issue by Waverun3** [Facepunch/garrysmod-requests#1464]
Diverse chasing mechanics, say if NPC Combine are in a city or a maze, they climb up and parkour a little. They vault over welded props such as benches and railing or objects built-in to the map. They even kick down doors.

Diverse NPC melee functions. Say if you want to see an NPC Rebel struggle against an NPC Combine in close-quarters combat, and either lose or win.

NPC smarts, such as using welded props as climbable objects, and other un-welded props as either shields from bullets or throwing weapons like a chair, complete with close-quarters combat.

NPC's take cover behind world-props/buildings big enough or welded props big enough only peeking out to shoot or scan the environment.

NPC rebels and citizens constantly looking-out-for-danger, a.k.a scanning the environment for enemies or dangerous hazards.

NPC's executing enemy NPC's via special animations on rare occasions if enemy NPC health is low enough.

NPC knockdown via vital forceful bullet wound(s) (not from 9mm pistol or SMG), physics prop, or strong physical non-lethal attack.

NPC's getting back up after being knocked down.

Player weapon "Fists" having several dynamic features including heavy punch (hold-down mouse-button and release) which does more damage and knocks down opponents, hook punch (e + LMB/RMB).

Proper grabbing of objects, props throwing, slamming/swinging as a weapon, and/or and NPC's for grabbing, punching and throwing.

Player-available executions to perform on NPC's and players for the crowbar, stunstick, and fists with 3 seperate executions for each.

Physgun carrying NPC's like ragdolls with slight resistance shown in "ragdolled" NPC's flailing their limbs and torso's about slightly. Physgun being able to throw NPC's, Slamming them into physical objects or terrain damages them and/or kills them.

Super Gravity gun now a featured weapon in HL2 weapons.

Crowbar having more attack animations, crowbar having heavy attack (hold down mouse-button and release) to knock down enemies and/or send them corspe-launching on instakill if positioned right, crowbar throwing.

**Comment by robotboy655** [comment]
All of these are game design ideas which are meant to be extended by addons, you know, the whole point of the game you could say.

**Comment by Kefta** [comment]
1-11. Can be done through addons. Garry's Mod is at its core a Half-Life 2 mod, and there are few unique features that don't exist in some other Valve game.
12. You can turn the NPC into a ragdoll in http://wiki.garrysmod.com/page/GM/OnPhysgunPickup and attach a PhysicsCollide callback with http://wiki.garrysmod.com/page/Entity/AddCallback to apply damage, though https://github.com/Facepunch/garrysmod-requests/issues/92 would be better for this.
13. https://github.com/Facepunch/garrysmod-requests/issues/91
14. Can be done through an addon/custom model. There's even a crowbar throwing addon already on workshop.

**Comment by Waverun3** [comment]
Apologies, just seems like something I would want officially because nobody
has ever done it before.
