### ISSUE TITLE
Allow SWEP.PrintName to be capitalized specifically in the HUD like Half-Life 2 stock weapons

### ISSUE THREAD

**Issue by mrbooboostank** [Facepunch/garrysmod-requests#1465]
Currently, SWEP.PrintName is used for both the HUD and the Spawnmenu; this makes it impossible to replicate the ALL-CAPS weapon formatting present in Half-Life 2.

Examples:

SWEP.PrintName = "Crowbar":
![swep printname problems 1](https://user-images.githubusercontent.com/57339742/69094897-e40f7d00-0a16-11ea-8087-613320ae1c55.jpg)

SWEP:PrintName = "CROWBAR":
![swep printname problems 2](https://user-images.githubusercontent.com/57339742/69092932-11f2c280-0a13-11ea-9204-b02548017f0c.jpg)

Half-Life 2's stock crowbar displays as "Crowbar" in the Spawnmenu, but it appears as "CROWBAR" in the HUD. Under the current SWEP.PrintName system, this is impossible to replicate. There are 2 ways this behavior could be implemented:

1: Add SWEP.HUDName in addition to SWEP.PrintName, and if SWEP.HUDName is nil, default to SWEP.PrintName (for compatibility).

2: Add a boolean value, SWEP.CapitalizeHUD, to determine whether SWEP.PrintName should appear as is or be ALL-CAPS in the HUD. This could be false by default for backwards-compatibility, or true by default to force better visual consistency.

**Comment by Kefta** [comment]
I like 1 better, 2 would be very oddly specific.

**Comment by mrbooboostank** [comment]
> 
> 
> I like 1 better, 2 would be very oddly specific.

I prefer 1 over 2, since it adds options other than capitalizing the Spawnmenu's name. I don't know how SWEP.PrintName works behind-the-scenes, so I mentioned 2 in case it would be easier to implement.

**Comment by Kefta** [comment]
It's done in the Lua spawnmenu code - the all-caps names are pulled from a .properties file. 1 is easier to implement.

**Comment by robotboy655** [comment]
Can't you just SWEP.Spawnable = false and then just readd it to spawnlist yourself just like the built-in weapons do?

**Comment by mrbooboostank** [comment]
> 
> 
> Can't you just SWEP.Spawnable = false and then just readd it to spawnlist yourself just like the built-in weapons do?

That sounds correct, but so far I can only de-list a stock weapon in game_hl2.lua and move/rename it using a new autorun file. It looks like list.set() is only recognizing stock weapon classes and not custom ones. The command "give weapon_example" still works when weapon_example.lua is present so list.set() might be running before custom weapons are mounted.

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/69167350-7d18c380-0afd-11ea-911c-22744978aef8.png)

```

list.Set( "Weapon", "testing", { ClassName = "weapon_base", PrintName = "B.A.S.E.", Category = "Otherrrrrrr", Author = "Volvo", Spawnable = true } )
```

So yeah it totally works. Make sure the second argument is not the same as the Classname.

**Comment by mrbooboostank** [comment]
Instead of list.Set(), the actual solution is to change self.PrintName in SWEP:Initialize(), so it was actually much easier than expected. list.Set() on a weapon introduces some weird problem where only the server host can spawn the weapon, so don't use it for this purpose.

**Comment by Kefta** [comment]
You have to change some key about admin spawning only if you use list.Set.
