### ISSUE TITLE
allowing table.insert() to use strings for the possition arg

### ISSUE THREAD

**Issue by VaasKahnGrim** [Facepunch/garrysmod-requests#1466]
https://wiki.garrysmod.com/page/table/insert

currently only allows numbers to be used for the possition arg, meaning if a table is inserted into another table it will be inserted as [1], [2] or [3]

however it would be pretty useful to be able to insert tables into other tables as ['Table 1'] or ['Table 2']

**Comment by willox** [comment]
Do you mean something equivalent `myTable['Table 1'] = var`? I don't understand

**Comment by VaasKahnGrim** [comment]
that or `myTable["Table 1"] = {"item 1","item 2","item 3"}`

right now it just inserts it as myTable[1]

**Comment by willox** [comment]
so... can you not use `table.insert( table['Table 1'], var )`? I don't really want any more stock Lua functions in GMod to be edited.

**Comment by VaasKahnGrim** [comment]
Would that work if myTable['Table 1'] doesn't exist yet?

**Comment by willox** [comment]
nope, but this seems like something you can work around
