### ISSUE TITLE
Expose SetPopup or make RemovePopup

### ISSUE THREAD

**Issue by GitSparTV** [Facepunch/garrysmod-requests#1469]
For now we can MakePopup, but we can't undo this method entirely or correctly.
Request to make :RemovePopup() or add :SetPopup(bool).

As addition :IsPopup() can be exposed too

https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/public/vgui/IPanel.h#L68

**Comment by Badger9** [comment]
Why is this here? Why is this not a PR?

**Comment by Kefta** [comment]
Because the methods need to be exposed from the engine, which we cannot PR.

**Comment by robotboy655** [comment]
IsPopup is added.
