### ISSUE TITLE
clientside loadingurl convar

### ISSUE THREAD

**Issue by Yogpod** [Facepunch/garrysmod-requests#1471]
A client convar that sets the loading url to whatever you set it to ex:
`cl_loadingurl "asset://garrysmod/html/loading.html `
or
`cl_loadingurl "google.com `
yeah prob not needed, & easy to do yourself but, could be a middle ground between disabling it completely and getting your ears destroyed by dubstep

**Comment by Kefta** [comment]
There's a convar to disable loading music now.

**Comment by robotboy655** [comment]
Adding such a feature would just be asking for it to be abused.

**Comment by Kefta** [comment]
Just blacklist the convar from being changed.

**Comment by Yogpod** [comment]
i worded this poorly, i meant like a convar created in menu state that can't be changed by clientside lua

**Comment by robotboy655** [comment]
Yeah, but It's still just a bandaid niche solution to the sound volume problem as far as I can tell.

**Comment by Kefta** [comment]
I think it would make those "GM12-styled loading screen" modifications easier without overriding core files.
