### ISSUE TITLE
AccountID conversion functions

### ISSUE THREAD

**Issue by WilliamVenner** [Facepunch/garrysmod-requests#1473]
There's currently no way to convert SteamIDs/SteamID64s to AccountIDs.

AccountIDs are generally accepted as a more storage-efficient and faster primary key in databases, for example.

It would be great if there was a reliable Gmod implementation of conversion for this.

It might be best to _not_ have functions that convert from AccountID to SteamID/SteamID64 as it wouldn't include the universe, which could cause problems for those who aren't aware of that.

Considering this, it would probably be wise to add a warning about that on the wiki page for these functions, if implemented :)

**Comment by meepen** [comment]
This is a stupid idea, and you can already do this stupid idea yourself if you wanted... Which you shouldn't

**Comment by Verideth** [comment]
> This is a stupid idea, and you can already do this stupid idea yourself if you wanted... Which you shouldn't

Man get out of here with that dumb negative garbage. Actually provide the answer that you don't seem to know.

@WilliamVenner This isn't necessarily something that needs to be added. It's possible to do yourself. `Player:AccountID` and `Player:SteamID() / Player:SteamID64()`

[SteamID's and how they work](
Player:AccountID()`https://developer.valvesoftware.com/wiki/SteamID#Universes_Available_for_Steam_Accounts)

Just compare the bits, that would be my best bet.

**Comment by WilliamVenner** [comment]
@Verideth
This would be useful in situations where the player is offline -- you can't call `Player:AccountID()` with no `Player` :)

**Comment by WilliamVenner** [comment]
@meepen
I can't tell if you just skimmed my issue or what, but that was a remarkably nonconstructive response.

**Comment by meepen** [comment]
You don't need to have a player object to convert data to another form. You can look here if you want to do it yourself: https://developer.valvesoftware.com/wiki/SteamID

However using account IDs is not faster in any database as a primary key, is barely any more efficient storage wise and removes vital information that could break your app in the future. 

I've repeated this many times but no one seems to listen. Using account IDs should never happen.

**Comment by WilliamVenner** [comment]
OK, so for the benefit of anyone stumbling across this, can you explain how it could break your app in the future?

**Comment by Verideth** [comment]
> OK, so for the benefit of anyone stumbling across this, can you explain how it could break your app in the future?

It won't. The dude has no idea what he's talking about. 

Representing a number in a bigger format isn't going to destroy and blow up anything. Maybe it CAN be less effective. 

But that all depends upon WHAT you're trying to accomplish.

**Comment by meepen** [comment]
Imagine you have 64 pieces of information from someone that uniquely identifies someone in a database. Now you have your own database that wants to reference and interact with the other one, but you store 32 pieces of information since, at least for now, they only have those being used.

In a few months or years they add another piece of information to their active use, and now you can't trust any of your data to be unique and you can't interact with the database without rewriting logic, schemas, and everything else.

**Comment by meepen** [comment]
Also a side note, this is sort of the issue with the Garry's mod uniqueid function.

**Comment by sweepyoface** [comment]
Are we not going to talk about having these functions for.. other purposes?

Say you want to convert to SteamID64 for linking to a profile.

**Comment by Kefta** [comment]
You can implement this in Lua.

**Comment by sweepyoface** [comment]
Just as you can do with the majority of functions we have. I don't think that's a real argument opposing this being included.
