### ISSUE TITLE
Add Vector:Distance2D()

### ISSUE THREAD

**Issue by ZenkakuHiragana** [Facepunch/garrysmod-requests#1475]
We have Vector:Length(), Vector:Length2D(), Vector:Distance() now but not Vector:Distance2D().
I'm too lazy to write (destination - source):Length2D() so if I could write source:Distance2D(destination), it would be great.

**Comment by Kefta** [comment]
More than laziness, it would be more efficient to implement into C anyway. ``Distance2DSqr`` should also be added.

**Comment by robotboy655** [comment]
Added both.
