### ISSUE TITLE
Portal 2 maps are completely broken and require compat fixes

### ISSUE THREAD

**Issue by pivotman319-new** [Facepunch/garrysmod-requests#1476]
The majority of Portal 2 maps are non-functional; I'm assuming part of it is due to the lack of proper VScript functions in the GMod/Source engine binaries as generic_actors like `@glados` are requested to trigger non-existent `CBaseEntity` functions.

Projected textures/lights also flicker on certain materials like unportalable black metal tile surfaces (which are are also broken since they display an RGB cubemap according to the player's position/world offset). There are also soundscripts which are not mounted in-game.

Certain scripted maps like sp_a4_finale4 (Wheatley boss fight) have broken sequences. Button sequence is unplayable and requires a recompilation of certain P2 models to fully work. (see video)

https://www.youtube.com/watch?v=cmt29IzDZPw

**Comment by pivotman319-new** [comment]
wait this isn't the bug tacker

**Comment by VaasKahnGrim** [comment]
a bigger issue with portal 2 maps is certain entities from portal need to be remade in gmod
