### ISSUE TITLE
Can't pick up HL2 grenades when thrown

### ISSUE THREAD

**Issue by Fesiug** [Facepunch/garrysmod-requests#1480]
In Half-Life 2, you are able to pick up thrown grenades with your Use key, for throwing back at Combine, for example. This is not available in Garry's Mod, however.

**Comment by Verideth** [comment]
Can't you just.. implement it? That's one of the points of the game, is easy to do moddability.

This repository is for engine feature requests or new coding requests. This can be done in simple Lua using features already there.

**Comment by Kefta** [comment]
Garry's Mod has been leaning towards replicating HL2 features accurately, I think this is a fair request.

**Comment by Verideth** [comment]
> Garry's Mod has been leaning towards replicating HL2 features accurately, I think this is a fair request.

Yea, I was a little skeptical about writing that response because I have noticed this. In that case, the request definitely wouldn't cause any harm, and move towards that goal..

**Comment by leverinet36** [comment]
> Can't you just.. implement it? That's one of the points of the game, is easy to do moddability.
> 
> This repository is predominately for engine features or new coding implementation requests. This can be done in simple Lua using features Garry's Mod already has there.

How would you start with implementing it?

**Comment by Kefta** [comment]
A PlayerUse hook and Player:PickupObject

**Comment by robotboy655** [comment]
This was fixed.
