### ISSUE TITLE
Concommand to clear the chatbox history

### ISSUE THREAD

**Issue by GitSparTV** [Facepunch/garrysmod-requests#1487]
Currently if your chatbox has ultra big history you can't do anything but to restart the game.
Ultra big chat box history takes a few seconds to load it all.
Console has `clear` concommand to clear.

Request: `chatclear` concommand to clear chat history, probably should be blocked as `clear`

**Comment by thegrb93** [comment]
A limit would probably be better.

**Comment by robotboy655** [comment]
Set the limit to 64000 symbols should be good enough to avoid lag and have plenty of history.

You can change this limit at any point by editing "maxchars" in resource/ui/basechat.res if you think you want a different limit or want to suggest a better default one.

**Comment by GitSparTV** [comment]
I see more sense in clearing function, maybe you need some information from big history, truncation will erase it.
But in another hand console is truncated too
