### ISSUE TITLE
Add commmandline library

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#1490]
A static library that wraps around the [global CommandLine](https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/src_main/tier0/commandline.cpp#L90). Used for directly reading options off the commandline which most don't have Lua accessors for, allowing Lua scripts to adjust to commandline behaviour.

Headers from https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/src_main/tier0/commandline.cpp#L34 :
``string commandline.Get()``
``number commandline.ParmCount()``
``string commandline.GetParm(number/*[0, ParmCount() - 1]*/ index)``
``[string] commandline.ParmValue(string parm, string default = nil)``
``number commandline.ParmInt(string parm, number default = 0)``
``number commandline.ParmFloat(string parm, number default = 0)``

Append/RemoveParm could potentially be abused so they shouldn't be added.

**Comment by ExtReMLapin** [comment]
I see it as something that would lead to security issues

**Comment by Kefta** [comment]
Like what?

**Comment by ExtReMLapin** [comment]
Like getting your steam API key "leaked"

**Comment by robotboy655** [comment]
Steam API keys are not in use by dedicated server for years now.

RCON password would be a problem though.

**Comment by ExtReMLapin** [comment]
RCON is already an issue

**Comment by Kefta** [comment]
Maybe don't bind ``commandline.Get`` and blacklist certain keys from ``commandline.Parm*``? Even if Steam API keys aren't utilised anymore, they shouldn't be retrievable.

**Comment by thegrb93** [comment]
What command line behavior specifically are you trying to adjust to? might be better just to add that instead.

**Comment by Kefta** [comment]
https://github.com/Facepunch/garrysmod-requests/issues/1489 inspired this, but there are more options like ``-nochromium``, ``-allowlocalhttp``, and ``-disableluarefresh`` which have Lua side effects undetectable from Lua. Adding an accessor for every option seems like a huge waste as opposed to just having a limited commandline library.

**Comment by VaasKahnGrim** [comment]
@robotboy655 you do know servers need to use a steamapi key in order to use workshop dl right? theres also server auth tokens aswell to worry about. would probably be better to have a way to check for specific things like -tickrate -nochromium -allowlocalhttp ect

**Comment by robotboy655** [comment]
@VaasKahnGrim You do not. I myself removed that necessity YEARS ago when I switched it to ISteamUGC.

**Comment by neico** [comment]
Tokens using `sv_setsteamaccount` from https://steamcommunity.com/dev/managegameservers are a valid point though

**Comment by ExtReMLapin** [comment]
[In a module I wanted to hide](https://github.com/ExtReMLapin/gmodstore-addon-extractor) an API key by setting it in the launch parameters of srcds or in lua.

The point if setting it in the launch parameters was to not expose it to lua and prevent anyone who has access to the server (legitly or not) to use the API key in a malicous way.
