### ISSUE TITLE
Add the ability to specify a recipient filter to ENT.StartLoopingSound

### ISSUE THREAD

**Issue by xaviergmail** [Facepunch/garrysmod-requests#1491]
I'm currently playing a looping sound on two entities, both outside PAS and teleporting a player from one entity to the other (elevator). It would be nice to be able to specify a recipient filter to StartLoopingSound to avoid the looping sound cutting out when the player gets teleported.

**Comment by xaviergmail** [comment]
After testing around, achieving this effect is currently possible using CreateSound instead

**Comment by robotboy655** [comment]
CreateSound and StartLoopingSound use the exact same system inside, should we even bother adding the extra argument(s)?

**Comment by Kefta** [comment]
I believe they should be added as CSoundPatch doesn't have a looping property, requiring a Lua replication of StartLoopingSound.

**Comment by robotboy655** [comment]
??? They are EXACTLY the same. StartLoopingSound will NOT loop non looping sounds for you.

**Comment by Kefta** [comment]
Never mind then, I thought it did.
