### ISSUE TITLE
env_sprite_clientside for GMod Hammer

### ISSUE THREAD

**Issue by Fishke1** [Facepunch/garrysmod-requests#1493]
env_sprites use up entdata unnecessarily as most of the time you use them as visual enhancers for static light sources, and aren't going to move/switch states at all

https://developer.valvesoftware.com/wiki/Env_sprite_clientside

**Comment by robotboy655** [comment]
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1282
