### ISSUE TITLE
Allow these NPC classes to have model overrides similiar to npc_combine_s

### ISSUE THREAD

**Issue by Servius** [Facepunch/garrysmod-requests#1494]
Allow these npc classes to have model overrides similar to [npc_combine_s](https://developer.valvesoftware.com/wiki/Npc_combine_s)

- https://developer.valvesoftware.com/wiki/Npc_zombie
- https://developer.valvesoftware.com/wiki/Npc_fastzombie

The overall behavior of the above two are not dependent on their half life 2 backgrounds as headcrab controlled zombie peeps. The option to override the model and retain the base functionality of the fast and slow zombie. Additionally the headcrab additionall companionship functionality should be togglable. 

`local NPC = {
	Name = "Zombie CT",
	Class = "npc_zombie",
	Category = "Zombies",
	Model = "models/dead_ct/dead_ct_zombienpc.mdl",
	Health = "650",
    KeyValues = { SquadName = "zombie",}
}

list.Set( "NPC", "npc_zombiect", NPC )
`

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod/commit/facf79b83d83a05dbc0899c1f551d24273723a3d

You have my permission now, you are allowed.

**Comment by Servius** [comment]
@robotboy655 Which PO Box do I send you fan mail at? Thanks my dude!
