### ISSUE TITLE
Add new argument of Emitsound to stop calling EntityEmitSound hook.

### ISSUE THREAD

**Issue by Headshotz** [Facepunch/garrysmod-requests#1496]
Add boolean for it because of performance. If you call Emitsound and its will calling EntityEmitSound hook that already edited the pitch, soundlvl and volume from EmitSound for ex, weapons. So this is waste the performance.

Its need set true to stop calling EntityEmitSound hook.

**Comment by Kefta** [comment]
If you want no perf loss on your server, empty the hook table for EntityEmitSound.

**Comment by Headshotz** [comment]
No, that's still same ever if it's empty.

**Comment by thegrb93** [comment]
Thats hardly anything

**Comment by Headshotz** [comment]
Do you believe that? I check through IDA and its possible.

**Comment by thegrb93** [comment]
Besides, it'd be annoying if you wanted to block emitsounds from another addon, but they decided to 'save performance' by making their sound unblockable.

**Comment by Headshotz** [comment]
Impossible.

**Comment by thegrb93** [comment]
That's not what I said. I said it would be annoying to try blocking an addon's sound only to find out that they made it unblockable.

**Comment by Headshotz** [comment]
I don't think that should block in mostly addons.

**Comment by thegrb93** [comment]
The whole point of emitsound is control over whether a sound plays. This defeats that purpose.

**Comment by Headshotz** [comment]
Anyways, I'll wait to hear from Gmod devs.

**Comment by robotboy655** [comment]
This is not a solution for anything.
