### ISSUE TITLE
Multiplayer Gamemode Browser Sorting

### ISSUE THREAD

**Issue by Dentist-afk** [Facepunch/garrysmod-requests#1497]
I think this is going to be a pretty controversial request, but I also think after looking at the server browser for so long, I think its a needed change.

I think the server gamemode browser should be updated, so that players can sort between 
A-Z, least people playing, most people playing, and as well as that add in a way to sought between official gamemodes and also derived gamemodes. When I say official gamemodes, I mean gamemodes that aren't based off another gamemode, so that players can finally filter out all the bullshit derived darkrp gamemodes. 

I also think the default sorting option for the gamemode browser should be A-Z, so that new players stop going for the gamemode that has the most amount of players, which is obviously DarkRP, which is causing great gamemodes like Murder and Prop Hunt too no longer get players, because no new people are joining, and all the old people now either have to play on really high pings because they have to join a server in a different region, play a gamemode like DarkRP or StarWarsRP, or just leave the entire game all together.

I have no problem with DarkRP and StarWarsRP, but one thing I've realized, that I've only just now began to realize, is the increasing drop in people playing other types of gamemodes, things like TTT that used to be at the top of the server browser list, with thousands of people playing all day long, is now sitting at roughly 500-600, which isn't bad, but compared to its old numbers, is an extreme decline.
I mean just look at the DarkRP numbers, it gets almost 10,000 players on a day, and the closest thing to it is StarWarsRP which is usually sitting at 1500-2000, and StarWarsRP is a derived gamemode from DarkRP.

I understand you can't control who plays on what, but the reason I feel that DarkRP has had such a huge boost in players, for it to completely destroy every other gamemode in the server browser list, is because new players see it at the top and instantly click on it, and choose the first server they click on, and they never bother to venture down to the other gamemodes below, and lets be real here, DarkRP servers probably aren't the best server for new players to be wanting to join, as they are extremely toxic, and aren't very welcoming, apart from rare occasions.

The main reason I think this feature should be implemented, is just because I feel as though Garry's Mod feels dead. 
No, I'm not saying Garry's Mod is dead, its not. It's got a very large and active  community still, the only problem is its beginning to feel empty and kind of like a wasteland, unless you go and play on a DarkRP server, or a StarWarsRP server, I have some of my best memories of Garry's Mod from other servers, like Sandbox, Murder, Prop Hunt, granted I do have many good memories from playing on DarkRP and StarWarsRP as well.

It's just I feel less and less excited as the years go by to go and see what new servers to go and play, because the majority of the time I'm going to be forced to play on the same old DarkRP and StarWarsRP server, because its the only type of server, that people play now a days, because its at the top of the server list, and new players are basically being advertised to go and play on those as they are at the top.

I'm sorry if this seemed more like a rant, its just that I really just wanted to justify my point of why I think this feature is needed, because its no longer exciting to explore new servers, and I know from a lot of old friends that I've talked with that say, they left Garry's Mod just because they don't want to be playing DarkRP and StarWarsRP all the time.

**Comment by Servius** [comment]
The problem with new gamemodes getting a fair chance is the problem with the gamemodes themselves. They usually dont receive the "exciting" start most skilled developers were hoping for, they generally try to monetize the shit out of their custom gamemode, and at the end of it all we end up with a new dead category. Favoring player count by default does, at the very least, filter new players to the less likely to die gamemodes which has probably contributed to the longetivity of the game itself.

Wish we would see facepunch team growth based around the creation and operation of new official gamemodes supported by Facepunch on GMod. They dont have to be huge or designed to have a ton of replayability like TTT. It would just be _neat_ to see an officially supported, light weight, fun gamemode be added to everyone's client universally. Could do bi-monthly or quarterly releases/updates and have it be a rotational focus. The "Gamemode" of the month/quarter would have a quick link-to in the "Updates" box they added to the top right. 

Would have a greater chance of introducing peeps to new-to-everyone gamemodes than a browser modification and could result in whole new genres of content creation completely based around peoples "fixes" to what the facepunch team initially releases.

**Comment by robotboy655** [comment]
Server browser got new filtering and sorting options since this issue was opened.
