### ISSUE TITLE
Player.SetCanZoom still lets zoom bind disable primary/secondary attack

### ISSUE THREAD

**Issue by Kinyom** [Facepunch/garrysmod-requests#1499]
Simple enough; if you use Player:SetCanZoom( false ), holding down G (or whatever the player has bound for zooming) will still disable your primary and secondary attack.

Steps for reproduction:
1.) Boot up any game
2.) Run "lua_run Entity(1):SetCanZoom( false )" in console
3.) Hold down both your zooming and primary/secondary attack binds
4.) You won't fire either

**Comment by robotboy655** [comment]
Should be fixed on Dev.

**Comment by Kinyom** [comment]
Just tried it; seems that the fix creates a buuuuunch of prediction errors. Whenever you're zoomed in via Player.SetFOV (not via the built-in suit zoom) and try to fire a weapon, it'll also fire clientside but not serverside, weirdly.

**Comment by robotboy655** [comment]
It should be resolved soon on Dev branch, but if you join non dev servers, obviously you are gonna get prediction errors.
