### ISSUE TITLE
Add support for per-map particle manifest

### ISSUE THREAD

**Issue by BoXiousNet** [Facepunch/garrysmod-requests#150]
https://developer.valvesoftware.com/wiki/Particles_manifest.txt
particles/mapname_manifest.txt (per-map) 

This would be useful for maps which do not come with their own particle_manifest.
https://github.com/Facepunch/garrysmod-issues/issues/787

**Comment by robotboy655** [comment]
The support for this existed forever apparently.

**Comment by robotboy655** [comment]
```maps/<mapname>_particles.txt``` is the format
