### ISSUE TITLE
Player.IsSprinting acts very weird when players run out of aux power

### ISSUE THREAD

**Issue by Kinyom** [Facepunch/garrysmod-requests#1502]
I'm not entiiiiiiirely sure of the specifics, but what I do know is that when gm_suit is enabled and a player runs out of aux power/regains juuuust enough to start sprinting again, Player.IsSprinting seems to return different values clientside and serverside. In a SWEP I'm creating, I'm tracking "sprint states" (done via NetworkVars - no worries, I'm handling my prediction properly, and when not out of aux power, it works perfectly), and once a player starts to sprint I play a sound and send an animation. In the cases I mentioned, that sound doesn't seem to play on occasion, and the animation I send is out of sync/generally fucky.

Given that everything works perfectly fine when I'm not out of aux power, I'm assuming this might have to do with IsSprinting screwing up when the player has no power, but still has the "shift" key or related bind down (I believe I kept holding it down when testing this).

Providing my entire SWEP code would probably be pretty tedious to both share and implement, so I'd suggest just testing this by starting a listen server, finding any predicted hook, putting a simple "print(Entity(1):IsSprinting())" statement in, then enabling gm_suit and holding shift down, running around, and never letting go.

**Comment by ExtReMLapin** [comment]
On another side, there are others cases when anything related to sprinting can be fucked up.

Example : 

* You don't have any aux power left
* You're pressing shift to sprint but it doesn't change your speed at all
* Some shit pushed you (like an antlion guard) and increased your linear speed to above the sprinting speed

Is it detected as sprinting ???

**Comment by robotboy655** [comment]
Are both of you on the latest server version? I cannot see anything "very weird"or "fucked up". You will need to be more specific.

```
hook.Add( "SetupMove", "Drowning:HandleWaterInLungs", function( ply, mv, cmd )
	local c = ply:IsSprinting()
	ply.OldC = ply.OldC or false
	if ( c != ply.OldC ) then
		print( c )
		ply.OldC = c
	end
end )
```

I used this code to see when it changes on both client and server on a dedicated server. I tried multiple move hooks and SWEP's think hook.
