### ISSUE TITLE
Add Player.AnimSetGestureSlotPlaybackRate

### ISSUE THREAD

**Issue by Kinyom** [Facepunch/garrysmod-requests#1504]
Currently, there's no way to set the playback rate of a player's individual gesture slot (i.e. GESTURE_SLOT_ATTACK_AND_RELOAD, GESTURE_SLOT_VCD, etc.). This would be really useful for speeding up or slowing down gesture animations when the default ones are too slow for whatever we're using them for; is there a way this could be implemented?

**Comment by robotboy655** [comment]
You can use https://wiki.facepunch.com/gmod/Entity:SetLayerPlaybackRate which will be made available clientside next update.

`Player.SetLayerPlaybackRate( GESTURE_SLOT_ATTACK_AND_RELOAD, 0.1 )`
