### ISSUE TITLE
Showbudget; Why is it locked behind SV_Cheats? 

### ISSUE THREAD

**Issue by Servius** [Facepunch/garrysmod-requests#1505]
https://developer.valvesoftware.com/wiki/Showbudget

It seems to be a valuable tool for players and server owners alike to discover what's killing performance. Is there actually a malicious use case for this or could it realistically be whitelisted as a non sv_cheats prereq command.

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/74166073-a9d90480-4c2e-11ea-9e41-b45847a32e91.png)

It's not?
