### ISSUE TITLE
allow the file class functions to reach the new workshop cache directory

### ISSUE THREAD

**Issue by NottyNoz** [Facepunch/garrysmod-requests#1507]
Since steamworks.DownloadUGC has replaced steamworks.Download and has a new workshop cache directory outside of the garrysmod folder aka "Steam\steamapps\workshop\content\4000", the file class functions should be able to reach it since game.MountGMA is able to mount .gmas from there.

**Comment by robotboy655** [comment]
I'd rather not. Why do you need this?

**Comment by VaasKahnGrim** [comment]
Being able to verify if a addon is already downloaded and then mounting it would be great. Why are addons even outside of the addons folder anyways?

**Comment by neico** [comment]
Because that's how ISteamUGC works, workshop items are part of steam, not the game, as such steam handles them, the game merely hooks into it.

What you want is a lua binding to `ISteamUGC::GetItemState` not direct filesystem access.

**Comment by VaasKahnGrim** [comment]
which one of those two would give me info about the file name, file size, ect?

**Comment by neico** [comment]
Why do you want to know that?

**Comment by VaasKahnGrim** [comment]
personally I use MountGMA a good few times but since the newer addons got shoved into a completly new folder I've been having some rather annoying issues thanks to it. I can't check file size to determin if I should redownload the gma or not.

**Comment by neico** [comment]
[steamworks.FileInfo](https://wiki.facepunch.com/gmod/steamworks.FileInfo) has everything you need, just take a look at the table, there's the mentioned `installed` field and also `updated` and `size`

There's no need to know the actual file name, all you need is the workshop id (regard them as workshop items, aka virtual, not files)

**Comment by VaasKahnGrim** [comment]
I don't use workshop for serverside addons, too much delay between reboots and map changes. for clientside its kinda useful to be able to get the file name to use MountGMA with. unless we could some how use the workshop addon id instead of a file path. or a seperate function such as game.MountGMAByID()

**Comment by robotboy655** [comment]
You don't need to check if it is downloaded or not, just call `steamworks.DownloadUGC`, it will not redownload shit if it is already downloaded. It never did that.

**Comment by NottyNoz** [comment]
What if we want to check the size of the vtfs in the gma?

**Comment by robotboy655** [comment]
All the files are mounted in a virtual filesystem. You can poll the size/open of all those files just like you used to, as well as enumerate them per addon.

**Comment by swampservers** [comment]
For some context, he's trying to fix Outfitter https://steamcommunity.com/sharedfiles/filedetails/?id=882463775 for us

**Comment by NottyNoz** [comment]
Outfitter reads the gma before unpacking and mounting it which is safer than just blindly mounting and accepting whatever the client uploads to the workshop.

**Comment by NottyNoz** [comment]
AddonMaterial can't reach the new workshop cache directory either which kind of defeats the purpose of it.

**Comment by robotboy655** [comment]
Lets try this then:

The callback of steamworks.DownloadUGC  will not have a second argument - a read only File object pointing to the ,gma. The file is closed after the hook is ran, so you gotta do everything you need to inside the callback.
