### ISSUE TITLE
Improve reporting on "zero area child patch" for the Gmod Hammer Editor. 

### ISSUE THREAD

**Issue by Servius** [Facepunch/garrysmod-requests#1508]
Currently reporting on "zero area child patch" is dumb. Its a dumb issue where an invalid solid has been created by accident. For whatever reason the problem checker will not flag the brush that's causing the problem despite it popping up during the compile. 

> A solid in your level has a face with no area

Implies vrad.exe encounters a specific object and thus should be capable of flagging that object.

**Comment by robotboy655** [comment]
Do you have a preferably small map with this problem I can test? I am not sure I can make it appear in Alt+P, but I can probably add more info to the error message to help narrow it down.

**Comment by robotboy655** [comment]
I guess not, so all you are getting is a possible position printout for that error.

**Comment by Servius** [comment]
@robotboy655 So sorry! Feel down a couple flights of stairs the other week and Ive been a little out of it due to the meds I am taking to cope with the pain. So sorry, ridiculously late response. 

Ill send over a mining station map that I am getting the error on.

**Comment by Servius** [comment]
https://drive.google.com/file/d/1pK5t0Dc7ARStt1vImv-HeCeXu1GdisX2/view?usp=sharing
https://drive.google.com/file/d/1wzyTdbFICz_1w8yEiSV9eWuI8wlRQbMs/view?usp=sharing

Mats, Models, and VMF. Hopefully that isnt too big. I hunted for **hours** and was able to get rid of 6 of the zero area child patch causers but that was mostly through trial and error. Id delete some geometry and check for any changes. If there wasnt any, id undo and repeat.

**Comment by thegrb93** [comment]
Wheres the .vmf? You should provide the .vmf with the problem and everything else deleted.

**Comment by Servius** [comment]
Oh yikes wrong map! One moment.

**Comment by Servius** [comment]
https://drive.google.com/file/d/1PAIWB14wZfUoPWpQWDWHLlTHvkgKal3x/view?usp=sharing
Materials to see the map above. Can just compile without models.

**Comment by robotboy655** [comment]
```
Zero area child patch at around -54.145229 -3422.984375 1787.575806
Zero area child patch at around -160.874741 -3286.208008 1787.578491
Zero area child patch at around -297.789886 -3392.867432 1787.577637
Zero area child patch at around -191.130234 -3529.791992 1787.578491
Zero area child patch at around -160.868210 -3606.207275 1787.577148
Zero area child patch at around -297.790619 -3712.867188 1787.577759
Zero area child patch at around -190.912979 -3849.881104 1787.575806
Zero area child patch at around 249.790726 -3743.129883 1566.756470
Zero area child patch at around 142.825180 -3606.083252 1566.755371
Zero area child patch at around 6.209322 -3712.866943 1566.756470
Zero area child patch at around 113.169456 -3849.913818 1566.755981
Zero area child patch at around 584.423889 -4686.747070 1566.757324
Zero area child patch at around 679.151184 -4541.248535 1566.755981
Zero area child patch at around 533.391907 -4446.566895 1566.755859
Zero area child patch at around 438.948212 -4592.697266 1566.755859
Zero area child patch at around 485.623688 -4399.321777 1993.671997
Zero area child patch at around 580.172241 -4253.880859 1993.676392
Zero area child patch at around 434.499115 -4159.130371 1993.676270
Zero area child patch at around 340.006958 -4304.595703 1993.675781
Zero area child patch at around 788.000183 -4295.125000 1699.249512
Zero area child patch at around 882.748840 -4149.566406 1699.248047
Zero area child patch at around 737.110291 -4054.952881 1699.248413
Zero area child patch at around 642.566589 -4200.526855 1699.247681
Zero area child patch at around 233.301331 -3337.270996 -1792.000000
Zero area child patch at around 374.729126 -3433.301270 -1792.000000
```
So yeah this works, and it should be helpful if you follow the coordinates:
![image](https://user-images.githubusercontent.com/3299036/75472455-34926100-599c-11ea-86ac-420df3f04455.png)

I doubt this is something that can be detected before vbsp splits the brushes.

Also I don't know what `A solid in your level has a face with no area` is or where you got it from, its not in any of our compile tools.

**Comment by Servius** [comment]
Its the valve wiki info on zero area child patch.
