### ISSUE TITLE
Hammer: Give Clips more material types

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-requests#1511]
Give Clips more material types, so footsteps can sound differently, like in CSGO, which supports  Concrete, Dirt, Glass, Grass, Gravel, Metal, Metal Grate, Plastic, Rubber, Sand, Tile and Wood.

**Comment by Servius** [comment]
Would be nice to not have to have these so we dont have to have dependencies on CSS/CSGO for simple junk like this.

**Comment by robotboy655** [comment]
Added.
