### ISSUE TITLE
Set Physics Attacker lua binding

### ISSUE THREAD

**Issue by Volantarius** [Facepunch/garrysmod-requests#1512]
A lua native bind to run SetPhysicsAttacker on props would be awesome! We can do this already with SetSaveValue. This is what the gravity gun does to props whenever it punts them, making the game keep track who punted the prop.

Here is the function itself in the source:
[https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/props.cpp#L1397](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/props.cpp#L1397)

I've tried setting this to props that the physics gun picks up / drops, and it totally works!

**Comment by Jvs34** [comment]
But we do? https://wiki.facepunch.com/gmod/Entity:SetPhysicsAttacker

**Comment by Volantarius** [comment]
Oops sorry sorry sorry!
