### ISSUE TITLE
TextEntry:SetMaximumCharCount(max)

### ISSUE THREAD

**Issue by Srlion** [Facepunch/garrysmod-requests#1515]
Could we have access to [TextEntry:SetMaximumCharCount](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/vgui2/vgui_controls/TextEntry.cpp#L2178) & [TextEntry:GetMaximumCharCount](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/vgui2/vgui_controls/TextEntry.cpp#L2186) bindings? I have tried to implement this on my own but it's really really buggy.

**Comment by robotboy655** [comment]
It should be trivial to add via `PANEL:AllowInput` but I have added it anyway. Also works on RichText.
