### ISSUE TITLE
Hook to detect a team change

### ISSUE THREAD

**Issue by WilliamVenner** [Facepunch/garrysmod-requests#1517]
(no, one doesn't concretely exist atm)

https://discordapp.com/channels/565105920414318602/669096349354033162/681981797210652708

**Comment by thegrb93** [comment]
Are there any non-lua things that set team? If not then I think you could just use a hook.Run whenever you set someone's team.

**Comment by Kefta** [comment]
``Player:SetTeam``, which actually exists on all entities but is only binded for players in Lua.

**Comment by WilliamVenner** [comment]
Of course you could run your own hook, but not all gamemodes do this. Sandbox does not.

**Comment by Kefta** [comment]
I think ``OnPlayerChangedTeam`` should just be changed to be called from ``SetTeam`` instead of ``PlayerJoinTeam``.

**Comment by robotboy655** [comment]
Unfortunately even such a simple change can cause problems for existing gamemodes.

Even sandbox is affected. I cannot predict how it will affect bigger gamemodes.
So either we can't use `OnPlayerChangedTeam` for this which sucks, or we potentially break every gamemode, or we don't have it.

**Comment by CornerPin** [comment]
Can it be added as a game event?

**Comment by robotboy655** [comment]
it can but is that a good solution?

**Comment by WilliamVenner** [comment]
Could just make a `PostPlayerChangedTeam` hook.

**Comment by Kefta** [comment]
Or just PlayerChangedTeam and OnPlayerChangedTeam can be deprecated.

**Comment by robotboy655** [comment]
Added as PlayerChangedTeam I guess
