### ISSUE TITLE
func_brush missing input ; Toggle and its validity as an option. 

### ISSUE THREAD

**Issue by Servius** [Facepunch/garrysmod-requests#1524]
The Func_Brush entity in hammer needs to have "Toggle" be added as a valid input. It **actually works** if you force the input as Toggle while the func_brush has the keyvalue "Togglable" for solidity. 
![image](https://user-images.githubusercontent.com/16316223/75862726-38671e80-5db4-11ea-8a11-22d91f003e66.png)

Would basically just make it so any entities that reference this mesh dont appear as entities with broken ties when doing alt+p

**Comment by robotboy655** [comment]
Added to the fgd.

**Comment by Servius** [comment]
@robotboy655 Does that mean Toggle is now valid? Do I need to look for an update or something?
