### ISSUE TITLE
Add ability to locally uninstall addons without unsubscribing

### ISSUE THREAD

**Issue by Yetoo1** [Facepunch/garrysmod-requests#1529]
I have GMod installed on two computers, but the laptop of the two has significantly less space than the other. I want to free space by locally uninstalling addons, but I want to keep those locally uninstalled addons subscribed and installed on the computer with more space. A button or other means to uninstall without unsubscribing would be very useful in the case.

**Comment by robotboy655** [comment]
There's a `-noworkshop` launch option (can be set through Steam or on the shortcut) that disables workshop addons locally.

**Comment by Yetoo1** [comment]
> There's a `-noworkshop` launch option (can be set through Steam or on the shortcut) that disables workshop addons locally.

But, that disables all addons instead of a user selection and doesn't uninstall them.

**Comment by robotboy655** [comment]
It doesn't download them if you use it before downloading anything, and this is an extremely niche need so I am not interested in adding something like that.

**Comment by robotboy655** [comment]
Actually come to think of it, it won't even be possible for us to do because all of the addons are automatically handled by Steam either way, so your request is more appropriate to be directed to them.
