### ISSUE TITLE
Rename all instances of uninstall to unsubscribe in the addon menu

### ISSUE THREAD

**Issue by Yetoo1** [Facepunch/garrysmod-requests#1530]
The current addon menu uses the word uninstall to remove an addon. However, this term is misleading because it was my understanding (and Oxford dictionary's understanding) that uninstall in this context meant removing a file from the computer. This is clearly not the case as it does not remove the GMA and appears not to as it's intended behavior (#246 #56). I was under the impression for a long time that uninstalling would remove the addon, but it instead just disassociates. By changing `uninstall` to `unsubscribe`, the meaning would be more accurate and less confusing.

**Comment by robotboy655** [comment]
It does delete the files. The only case where it doesn't is when you unsub not in-game and the addon was not updated/created since January 25th.
