### ISSUE TITLE
A List Of The Current Loading Statuses

### ISSUE THREAD

**Issue by Rainnerz** [Facepunch/garrysmod-requests#1531]
There should be a list of the current loading statuses to make it easier creating loading screens.

I am trying to use this function to change an elements width after every status change. _Excuse the clunkiness_
https://i.imgur.com/CBOgBfU.png

But as you can see. It is using partially outdated statuses and because there is no list (that I know of) I can't accurately make the changes.

**Comment by robotboy655** [comment]
If you really need a list of the statuses, just log them in the loading screen.
They will also be different for people with different languages.

https://github.com/Facepunch/garrysmod/blob/759de9269a192e125fe9478caa34e69732bdfedc/garrysmod/lua/menu/loading.lua#L126
You can just edit this file on your client and `print()` the different messages if you wish.
