### ISSUE TITLE
Seeking modders to make some feudal japanese addons for me

### ISSUE THREAD

**Issue by Braintennant** [Facepunch/garrysmod-requests#1533]
sorry if this is the wrong/inappropriate place to post this request, but i am nearing the point of desparation.... As the title says, I am looking for someone to make samurai addons for me. 

Specifically: 

Feudal japanese npcs, like merchants and citizens. And of course Samurai. All with AI

A medium/Large map with houses, inns, maybe a castle, and shops.

And misc. things like, Japanese style food, seiza sitting, kenjutsu stances and more

I realize this might be a very ambitious project, which is why i would be willing to pay for your "services". Also if you are reading this, and know of any allready existing addons such as these, i would be very happy if you would let me know. If so thanks in advance. 

Regards MLH

**Comment by meepen** [comment]
This is for actual developers to request features to be added to Gmod, might want to look at gmodstore for your request.

**Comment by Braintennant** [comment]
Thank you:)
