### ISSUE TITLE
Add game info for issues

### ISSUE THREAD

**Issue by GitSparTV** [Facepunch/garrysmod-requests#1535]
This is a meta request for garrysmod-issues.
The idea is to simplify issue searching, classification and reproduction.
```lua
concommand.Add("gmod_info", function()
    Msg( SERVER and "SERVER" or "CLIENT", ", os: ", jit.os, ", arch: ", jit.arch, ", ver: ", VERSION, ", branch: ", BRANCH, ", mcore: ", GetConVar("gmod_mcore_test"):GetInt() )
end)
``` 
I believe people won't use it without enforcing mentioning in the issue template.

Preview:

CLIENT, os: Windows, arch: x86, ver: 170320, branch: none, mcore: 1

**Comment by Servius** [comment]
So it poops out info to help when reporting issues. Nifty

**Comment by thegrb93** [comment]
How would players know to enter the command in their client or in the server? There should also be checks for if the game is Singleplayer, locally hosted, or dedicated. Even then, it might be misleading.

**Comment by GitSparTV** [comment]
@thegrb93 My idea is to add a line in `issue template` to use this command on the side where you the the issue. ("How would players know to enter the command in their client or in the server?").
As a dev you can also ask your players/users/testers to tell the result of this gameinfo
Also I made example in Lua, I think it should be made on C++.
Dedi/Local/Sigleplayer is a good info.

**Comment by GitSparTV** [comment]
This also helps to ensure the server/client is up to date to debug issues fast and precise.
Asking player with some issue to run `lua_run print(VERSION)` is slow, asking if the server is updated is unreliable

**Comment by GitSparTV** [comment]
Oh well we already have `version`
Maybe it can be extended to include what I suggested

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/86831065-1b629500-c09f-11ea-8d59-64c6f3c4bfea.png)

**Comment by neico** [comment]
This `x32` hurts, it's either `x86` or a variant of `32-bit`

**Comment by robotboy655** [comment]
I knew someone will have a problem with it.
