### ISSUE TITLE
Some ideas for the npc footsteps 

### ISSUE THREAD

**Issue by Akis-02** [Facepunch/garrysmod-requests#1537]
I saw in your las dev log, that you will bring back the combine and stalker footstep events.
is it possible for a toggleable option like: hl2_npcmakefootstepsnd 0/1, also Eli's footsteps could be added.By combine you mean combine soldiers or generally all combine, like metrocops etc?

**Comment by robotboy655** [comment]
Why would we ever make an option to toggle footsteps? Not to mention this is already achievable by modding the game.

I will look into metrocop/eli footsteps.
