### ISSUE TITLE
DamageInfo Armor Scaling

### ISSUE THREAD

**Issue by Volantarius** [Facepunch/garrysmod-requests#1540]
Armor has a ratio that the armor takes damage off to save health points. In player.cpp (server) theres a armor_ratio and armor_bonus that controls this. There are counter-strike weapons that change this ratio already and it would be awesome to replicate those weapons affect on armor.

**Comment by Volantarius** [comment]
Or maybe a hook where the armor ratio is calculated.

**Comment by robotboy655** [comment]
Essentially duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1192
