### ISSUE TITLE
Add ENTITY:IsClientside

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#1542]
Or ``ENTITY:IsCSEnt``. Clientside-only entity function to determine if the ent is a CSEnt or not.

**Comment by neico** [comment]
```lua
function ENTITY:IsClientSide()
    if CLIENT then
        return self:EntIndex() == -1
    else
        return false
    end
end
```
But yeah, should be added
You can even reverse the logic to get server only entities, and then do the following to round it up:
```lua
function ENTITY:IsShared() -- alternatives: HasEdict(), IsNetworked()
    if CLIENT then
        return !self:IsClientSide()
    elseif SERVER then
        return !self:IsServerSide()
    end
end
```

**Comment by Kefta** [comment]
I think IsCSEnt is the better name then as this is specifically to test if the entity is specifically a [CSEnt](https://wiki.facepunch.com/gmod/CSEnt) and thus can be removed clientside.

**Comment by robotboy655** [comment]
I am not sure how useful this will be over `EntIndex() == 1`, there are many other clientside only entities, like death radgolls and stuff, which do not have the CSEnt metatable.

**Comment by Kefta** [comment]
Why is there a CSEnt metatable at all then? I thought that was supposed to be the reliable way of determining if you can remove an ent clientside.

**Comment by robotboy655** [comment]
For GC I imagine?

**Comment by Kefta** [comment]
Well I suppose there's no need for this then.

**Comment by willox** [comment]
CSEnts will never be GC'd (at least until the entity has been removed anyway) because they hold a reference to themselves
