### ISSUE TITLE
Video support added? For cutscene purposes

### ISSUE THREAD

**Issue by VaasKahnGrim** [Facepunch/garrysmod-requests#1543]
Basically it would be quite nice to be able to ship MP4 files to clients and being able to have those used in a fullscreen client for transition cut scenes in gamemodes.

That and given how mp3 is already supported for audio I see no reason why MP4 can't be added aswell

**Comment by robotboy655** [comment]
You will be able to do this and whatever else using CEF.

**Comment by VaasKahnGrim** [comment]
@robotboy655 Will CEF be added in by default for the x86_64 update and will the .mp4 file extension added to the gmad whitelist?

**Comment by thegrb93** [comment]
No I don't think it supports mp4. Use webm instead.

**Comment by VaasKahnGrim** [comment]
mp4 would be a better option, generally its much better video quality. also last I checked webm files can't be sent to the client either. Would be better to just have mp4 video file support and having the file extention added to the whitelist

**Comment by willox** [comment]
web will be a better option because it will work

**Comment by thegrb93** [comment]
I have seen repos on github that patch Gmod CEF to work with mp4, but I don't think can be shipped with gmod due to licensing or whatever. Idk the details of all that.

**Comment by VaasKahnGrim** [comment]
.webm still isn't whitelisted for being packaged into a gma so thats kinda as useless as .mp4 files are right now, and those CEF patches made by the community are pretty much useless since we can't have them automatically installed to clients joining.
