### ISSUE TITLE
Enable BELLYBLAST for npc_combinegunship

### ISSUE THREAD

**Issue by GitSparTV** [Facepunch/garrysmod-requests#1545]
`npc_combinegunship` has secondary type of attack called ground attack or berry blast, it was disabled in HL2 but it still works and can be fired by inputs. However even when `m_bCanGroundAttack` is true it doesn't use this attack. In my tests it's working properly.

**Comment by robotboy655** [comment]
Done.

**Comment by thegrb93** [comment]
This sounds hot
