### ISSUE TITLE
Add FCVAR_ARCHIVE and remove FCVAR_NOT_CONNECTED from fps_max

### ISSUE THREAD

**Issue by GitSparTV** [Facepunch/garrysmod-requests#1547]
Currently fps_max convar is not savable and you can't change it while connected.
CS:GO allows to change it when in game and the value is saved.

**Comment by robotboy655** [comment]
I can remove FCVAR_NOT_CONNECTED, it seems to work just fine, but I don't know about saving.

There are parts of the game that will set that convar, for example the Demo to Video stuff, as well as servers/addons if we don't block this convar.

**Comment by GitSparTV** [comment]
Ok, just UNCONNECTED is fine
