### ISSUE TITLE
hammer - enable / disable spawn points

### ISSUE THREAD

**Issue by Combine900** [Facepunch/garrysmod-requests#1554]
can we may have the feature from csgo that allows hammer editor users to enable or disable spawn points?

https://developer.valvesoftware.com/wiki/Info_player_counterterrorist <- Inputs

why? well it would be great to create maps that can be used with multiple gamemodes that uses different spawn points like "info_player_deathmatch" for TTT etc

**Comment by robotboy655** [comment]
Potentially duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1525

I still don't see how this is useful. Those gamemode would just use proper spawnpoint class, and if not, how would you detect which gamemode is running to disable the spawnpoints, and do you even know if you can even do it in time before players actually spawn after a `game.CleanUpMap()`?

**Comment by joeyjumper94** [comment]
you should be able to check if a spawnpoint is disabled by looking up one of the keyvalues on the entity or by indexing its savetable.

**Comment by Combine900** [comment]
> 
> 
> Potentially duplicate of #1525
> 
> I still don't see how this is useful. Those gamemode would just use proper spawnpoint class, and if not, how would you detect which gamemode is running to disable the spawnpoints, and do you even know if you can even do it in time before players actually spawn after a `game.CleanUpMap()`?

thanks for the answer..
