### ISSUE TITLE
Clientside function to retrieve the LocalPlayer() fps

### ISSUE THREAD

**Issue by VaasKahnGrim** [Facepunch/garrysmod-requests#1556]
Basically would be useful for UIs/HUDs in order to display the players current FPS without needing to enable things like net_graph. this would also be great because net_graph displays more than just FPS when in use. it also to my knowledge doesn't have the option to scale up its size either, or atleast nobody seems to bother setting its scale IF there is a way.

Being able to  get the players FPS and display it in a hud or UI would look alot better than net_graph aswell depending on how a hud was made

**Comment by VaasKahnGrim** [comment]
something else I had thought of that this could be useful for is in certain lua effects and entities we could disable more expensive clientside stuff such as text above entities, expensive render functions could instead run more light and less fancy rendering functions instead. similar things could possibly be done with menus and panels aswell to reduce FPS impact

**Comment by Kefta** [comment]
You can calculate the framerate from Lua by using SysTime and a Think hook.

**Comment by meepen** [comment]
...Or 1/FrameTime()

**Comment by ThatLing** [comment]
> 
> 
> You can calculate the framerate from Lua by using SysTime and a Think hook.

Wouldn't it be better to use a PostRender hook?

**Comment by VaasKahnGrim** [comment]
`tostring(math.Round(1/FrameTime()))` to be exact worked for getting the players FPS as a whole number. tho imo it might be better to have what ever net_graph uses to get FPS exposed to lua for us to do the same

**Comment by Kefta** [comment]
@ThatLing It's inconsequeital, they're both called once a frame. I suggested Think instead of a render hook since some people return in render hooks.

@VaasKahnGrim It's not necessary - both the SysTime and the 1/FrameTime() solution are more accurate than what net_graph uses.

**Comment by robotboy655** [comment]
You can see the exact math net_graph does and do it yourself.

https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/client/vgui_netgraphpanel.cpp#L729
