### ISSUE TITLE
Please expose CNavArea::ComputeFuncNavCost ()

### ISSUE THREAD

**Issue by mrpotatofactory** [Facepunch/garrysmod-requests#1558]
Recently, I have attempted to create an mvm-based gamemode which heavily uses `NAV_MESH_FUNC_COST` in order to calculate what path a NextBot agent should use to add another dynamic to the gameplay.

![Nagivation Topology](https://i.imgur.com/HqC7Y0G.jpg)

This can be replicated in-game using the commands with `sv_cheats 1`:
`nav_show_func_nav_prefer 1`
`nav_show_func_nav_avoid 1`

In the current implementation of NextBot, there is a way to detect whether an area is marked to be subject to cost change using `CNavArea::HasAttributes (NAV_MESH_FUNC_COST)`. However, there is currently no official efficient way to compute whether the area in question has a cost multiplier active without the use of trapezoidal mapping.

_Note: This request is a repost from https://github.com/Facepunch/garrysmod-issues/issues/3789, as I wanted to make sure this request was potentially heard and did not fall on deaf ears._

**Comment by mrpotatofactory** [comment]
I already tried to close the previous issue, I don't have permission to do so.

**Comment by Kefta** [comment]
Everyone has permission to close their issues, it's next to the comment button.

**Comment by mrpotatofactory** [comment]
![Screenshot from 2020-04-05 18-12-08](https://user-images.githubusercontent.com/5634516/78512305-06592b80-7769-11ea-825e-38d633c97f9d.png)

I see the close button on this issue board for some reason though.

**Comment by robotboy655** [comment]
Even if I bind this function, it will always report 1. The 2 entities on that map only work in TF2, specifically only on their bots.
