### ISSUE TITLE
Remove gameui_preventescapetoshow from console command blacklist

### ISSUE THREAD

**Issue by rbreslow** [Facepunch/garrysmod-requests#1564]
This is what the engine uses to prevent the menu from opening when chat is visible: https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/src_main/game/client/hud_basechat.cpp#L1174

There's already been workaround for this that achieves the same functionality, so I don't really see the purpose of the blacklist.

```lua
hook.Add("PreDrawHUD", "EscapeClose", function()
    if gui.IsGameUIVisible() then
        gui.HideGameUI()
    end

    if input.IsKeyDown(KEY_ESCAPE) then
        chat.Close()
    end
end)
```

The UX with the workaround is pretty bad since you'll see the menu flash across the screen for a few frames.

**Comment by bizzclaw** [comment]
you used to be able to use the [PreRender](https://wiki.facepunch.com/gmod/GM:PreRender) to return true for that one frame the escape menu was visible, and it would show the previous frame for a single frame.

```LUA
hook.Add("PreRender", "rsrg_escmenu", function()
  if (input.IsKeyDown(KEY_ESCAPE) or input.IsButtonDown(KEY_XBUTTON_START)) and gui.IsGameUIVisible() then
    gui.HideGameUI()
    if not IsValid(EscMenu) then
      OpenEscMenu() -- custom escape menu open function
    else
      CloseEscapeMenu()
    end
    return true -- prevents the frame with the original UI in it to render
  end
end)
```

Regardless of the lost frame, this was completely seamless and worked perfectly until an update tried to "Fix" the issue where you see images bleeding into each other when you look outside of the map.

This is even mentioned in an example

> Fills the draw buffer with black pixels, removing tearing when looking at a world leak. Achieves the same effect as using gl_clear.  **This is no longer needed as GMod does this by default.**

Unfortunately, there is no way to revert this "Fix" even though it only occurred when someone was intentionally breaking the game with noclip or running a broken map anyways.

Honestly, a whole issue/request could be made about reverting this issue alone, but either way it would be nice to get smooth custom escape menus back.

**Comment by Kefta** [comment]
That draw buffer change had nothing to do with this issue, it was to prevent clientside screenshot addons from seeing the user's Steam overlay.

**Comment by bizzclaw** [comment]
@Kefta Ahh, that makes sense then. Honestly, it was kind of a dirty hack anyways, but there was no other way to achieve the effect and now it can't really be achieved at all. I think a proper way to get custom escape menus would be used well, hacky or not.

**Comment by robotboy655** [comment]
Closing in favor of https://github.com/Facepunch/garrysmod-requests/issues/1624
