### ISSUE TITLE
file.Write on file written completion

### ISSUE THREAD

**Issue by MyDimeIsUp** [Facepunch/garrysmod-requests#1566]
Allow us to run a function once the file has been completely written to.

```lua
file.Write(sGMAFile .. ".dat", sHTTPFetchGMABody, function(bSuccess)
  if !bSuccess then error("GMA File creation failed") return end

  verifyChecksumWithServer(sGMAFile)
end)
```

**Comment by Kefta** [comment]
https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/includes/extensions/file.lua#L21

file.Write internally opens the file, writes its contents, then closes it. You can just do the same and call whatever additional functions you need before the file is closed.

**Comment by MyDimeIsUp** [comment]
> https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/includes/extensions/file.lua#L21
> 
> file.Write internally opens the file, writes its contents, then closes it. You can just do the same and call whatever additional functions you need before the file is closed.

How would you go about doing that without slightly rewriting the file.Write function? And even so, I think this suggestion is just a more straight forward and elegant option that would be nice to have on a daily basis.

**Comment by Kefta** [comment]
You don't. You write your code as
```Lua
local pFile = file.Open(sGMAFile .. ".dat", "DATA")

if (pFile ~= nil) then
	pFile:Write(sHTTPFetchGMABody)
	verifyChecksumWithServer(sGMAFile) -- Or even send in the file object since that seems to be the whole point of doing this
	pFile:Close()
end
```
file:Write nor file.Write return anything so I'm not sure what bSuccess is referring to. I don't see a need to add this to file.Write since it's so niche.

**Comment by neico** [comment]
`file.Open( sGMAFile ..".dat", "wb", "DATA" )` tries to open the file in write binary mode, if it succeeds it returns a file object, if it fails it returns `nil`
if it can be opened in this case then it can also be written to, hence `Write` has no need to return anything.

**Comment by thegrb93** [comment]
I think he's trying to make sure the data on disk wrote correctly?

All you need is
```lua
file.Write(sGMAFile .. ".dat", sHTTPFetchGMABody)
verifyChecksumWithServer(file.Read(sGMAFile .. ".dat", "DATA"))
```

**Comment by thegrb93** [comment]
Checking if something wrote to harddisk correctly is kind of silly though and the OS does that for you; usually you only check if it was networked correctly.

**Comment by MyDimeIsUp** [comment]
What I'm trying to do is once a .gma/.dat was downloaded, check if the file that was downloaded was correct. Howevcer if I do just something like this
```lua
file.Write(sGMAFile .. ".dat", sHTTPFetchGMABody)
verifyChecksumWithServer(file.Read(sGMAFile .. ".dat", "DATA"))
```

There is a good possibility that it'll say that the file doesn't exist. IDK what lua says since I'm too lazy to get the error, but suffice to say it'll say the file doesn't exist a good majority of the time.

**Comment by thegrb93** [comment]
Just do verifyChecksumWithServer(sHTTPFetchGMABody), jeez
