### ISSUE TITLE
Make PData use SteamID instead of UniqueID

### ISSUE THREAD

**Issue by NickPackham** [Facepunch/garrysmod-requests#1568]
I'm not exactly sure if there's anything holding this back, i feel like PData is useful for a lot of situations but the main issue is that it uses UniqueID instead of SteamID which has the ability to collide from what I've heard.

**Comment by Kefta** [comment]
https://github.com/Facepunch/garrysmod/pull/1580
https://github.com/Facepunch/garrysmod/pull/1639
