### ISSUE TITLE
Could we get NextThink() fixed for Nextbots and SWEPs

### ISSUE THREAD

**Issue by VaasKahnGrim** [Facepunch/garrysmod-requests#1569]
Could we get the function fixed so that it actually works for nextbots and sweps? apparently it doesn't and it would be nice to have a clean way of doing this without having to manually recreate the functionality.

https://wiki.facepunch.com/gmod/Entity:NextThink

**Comment by Kefta** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/3269

**Comment by VaasKahnGrim** [comment]
marked as "won't fix" 🤔 thanks rubat, real cool

**Comment by thegrb93** [comment]
Read his explanation?

**Comment by robotboy655** [comment]
Unless you want all existing SWEPs to potentially break, it's not getting changed. Same goes for NextBots, it seems they just reset the nextthink time every think for I imagine good reasons to keep em working,

**Comment by VaasKahnGrim** [comment]
So basically "won't fix" because of older/abandoned/broken already addons that your afraid will get even more so broken.

basically any swep or nextbot that tries to implement this themselves would be perfectly fine. If they made their own NextThink() function for nextbots then they would be uneffected, same goes for if they don't even use think. and if they use CurTime() + a duration to create a delay then they also wouldn't be effected either.

Litterally not likely that fixing this bug would break a damn thing.

and at this point I'm actually going to respond with "yes, I do want all existing SWEPs to potentially break" even if only on the off chance it actually gets something done about NextThink.

**Comment by thegrb93** [comment]
I mean, it could be added to base sweps, but only some sweps would use it and it would still just be a lua implementation. Just do it yourself; it's 3 lines.

**Comment by VaasKahnGrim** [comment]
we shouldn't have to do bug fixes our self tho, thats the thing.

**Comment by Kefta** [comment]
It's really the fault of Garry for not adding a SENT metatable so it had to be added to all entities.

**Comment by VaasKahnGrim** [comment]
Thanks Garry, real cool

**Comment by thegrb93** [comment]
It makes sense from a performance perspective though
