### ISSUE TITLE
Function to give a player a dropped weapon

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-requests#1572]
Picking up dropped weapons is done by running over them.
This behaviour often comes with a lot of issues.

Weapons aren't getting picked up or it takes a few seconds before it picks up the weapon, etc. etc. etc.
I suggest a function to give a player a weapon entity, which was dropped to the floor.

I really don't want to make my own dropped weapon variant just for this cause.

(Give creates a new weapon, with different values)

**Comment by CornerPin** [comment]
#1235
