### ISSUE TITLE
Compatibility with MacOS Catalina 64-bit

### ISSUE THREAD

**Issue by Adameck360** [Facepunch/garrysmod-requests#1573]
Hi. I would like to know if GMod will be released/repaired on MacOS Catalina 64-bit OS. I have MacBook and when I had old OS version of Mac I can play GMod but now when was released Catalina I cannot run it.

**Comment by robotboy655** [comment]
Have you tried the x86-64 beta branch for Garry's Mod?

**Comment by Adameck360** [comment]
No, but now I just downloaded this x86-64 binary and now it works. @robotboy655 thanks for your help. I don't know about this binary on steam. Thanks
