### ISSUE TITLE
Replace or renew new backgrounds for the main menu.

### ISSUE THREAD

**Issue by GitSparTV** [Facepunch/garrysmod-requests#1574]
GMod has incredible art makers, with new GMod abilities more new tools and content came to the game. I'm not sure how old are the wallpapers in the main menu, but I know for sure they don't update for several years.

So my idea is to make a competition (a prize is obviously including the wallpapers to the game).
We have a centralized place: GMod Discord, which we can use for submissions. Steam news can be also used to inform people.
As a way to choose the winners (I guess 10 places) we can use members votes or/and dev's choice.

Thanks.

**Comment by AutismoPiggo** [comment]
Fully supported

The Garry's Mod backgrounds have been the first thing many many players have seen and they're a perfect, simple demonstration of the creativity of one of Gmod's most active niche communities 

Would also be an easy simple thing for Facepunch to do, even during this time of focusing on more modern, successful projects like Rust

**Comment by WilliamVenner** [comment]
+1 this will give a much stronger feeling of an active community.

**Comment by robotboy655** [comment]
I personally don't want to run a competition myself, but I don't mind if the Discord mods do it. Last one was done by a community member on the forums - Vioxtar I think, maybe he will be interested in getting involved again.

We currently have 25 backgrounds, so top 20-25 would definitely be fine if there's enough entries.

As for rules, just apply common sense:
1) You have to have made the artwork yourself
2) Avoid using/don't use 3rd party intellectual property, mountable content might be fine
3) Probably 1 winning item per person, but I don't see a point in restricting it to 1 entry per person
4) Pls no military/fnaf/splatoon/pony stuff
5) More as a guideline, but pls don't overuse Photoshop, the picture should still be recognizable that it was made in the game
6) All winning entries will be downscaled to 1920x1080

Can definitely shout it out on Steam announcements or w/e.

**Comment by AutismoPiggo** [comment]
Sounds good to me

**Comment by GitSparTV** [comment]
Thank you for letting us do this, we've started the competition.
