### ISSUE TITLE
Voice sounds terrible

### ISSUE THREAD

**Issue by mark27205** [Facepunch/garrysmod-requests#1579]
Since the new update the voice should be better and now it's clearer but it sounds terrible at the same time. You cannot understand anything because they're to quiet. And of course you can change the volume but what about people that already set their mic up so it's loud`? It'll blast your ears.

**Comment by thegrb93** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/4468

**Comment by mark27205** [comment]
Sorry for the duplicate then

**Comment by robotboy655** [comment]
Some time will need to pass before everyone adjust their mics, and an option for per player voice chat volume in the future, like in CS:GO is not out of question.
