### ISSUE TITLE
Revert voice back to 11KHz

### ISSUE THREAD

**Issue by nitromech** [Facepunch/garrysmod-requests#1580]
Revert the voice back to 11KHz. Reasoning is explained perfectly by the gentleman that made this petition: https://www.change.org/p/garrysmod-players-change-gmod-voice-back-to-11khz

**Comment by robotboy655** [comment]
Uhhh, no, It was highly requested to be changed. (https://github.com/Facepunch/garrysmod-requests/issues/1580)

Servers can use `sv_use_steam_voice 0` to old legacy Speex voice codec.
