### ISSUE TITLE
Make barnacles eat headcrabs off zombies

### ISSUE THREAD

**Issue by barn-advisor** [Facepunch/garrysmod-requests#1582]
this happens in episode 1 (not sure about hl2 or ep2)
currently barnacles just turn zombies into ragdolls, not even eating them

**Comment by robotboy655** [comment]
You need to enable episodic behavior on the server/singleplayer for this to work:
`hl2_episodic 1`

This is done automatically for Episode 1 and 2 maps.
It is also automatically set to 0 on non episodic maps, so keep that in mind. You will need to manually set to 1 every time you load a non episodic map.

**Comment by VaasKahnGrim** [comment]
could we get the default value for hl2_episodic set to 1 instead of 0? because that behavior honestly sounds like stuff that most people would want enabled anyways. it also makes sense gameplay wise that those sort of things would happen anyways. Can't think of anybody who would want that turned off.

**Comment by robotboy655** [comment]
hl2_episodic affects far more than barnacles, and having it enabled at all times will break other parts of the Half-Life 2 campaign.

**Comment by VaasKahnGrim** [comment]
yea but would it effect servers negetively in any way? because I doubt many people use any of the campaign maps in any multiplayer scenario except for fringe gamemodes that rarely see the light of day

**Comment by Kefta** [comment]
HL2 campaign gamemodes have some moderate popularity (see Lambda) - I think the default should be non-episodic HL2 behaviour. Server owners can enable this themselves.

**Comment by barn-advisor** [comment]
i never knew hl2_episodic did anything of note, thanks

**Comment by Xenthio** [comment]
I think this may be broken right now?
