### ISSUE TITLE
studiomdl $boneflexdriver support

### ISSUE THREAD

**Issue by xDShot** [Facepunch/garrysmod-requests#1584]
Source 2013 already has it. Compiled models from 2013 won't do the stuff. Would be nice to have it in gmod so we can do awesome vertex animating, eg. with HL:Alyx ported assets.

**Comment by MARK2580** [comment]
https://developer.valvesoftware.com/wiki/Vertex_animation
https://developer.valvesoftware.com/wiki/$boneflexdriver

**Comment by xDShot** [comment]
https://github.com/xDShot/gmod-boneflexdriver initial implementation

**Comment by JimbobweSmells** [comment]
An official implementation of this would be grand, there's so much that can be done in terms of visual effects with vertex animation. I can't imagine it being too difficult to implement given it runs off the 2013 branch.

**Comment by robotboy655** [comment]
A sample model sources would be needed for me to add this, as I need to test it with something.

**Comment by xDShot** [comment]
[alastor.zip](https://github.com/Facepunch/garrysmod-requests/files/6393660/alastor.zip)

An example playermodel. It has sequence which drives special bone which controls some eye flexes. Works in hl2. Let me know if something else needed.

**Comment by robotboy655** [comment]
Added.

**Comment by MARK2580** [comment]
> Added.

Seems to work. Checked in the game and hlmv. Well done Rubat, though I needed this function a year ago when we created a request.
