### ISSUE TITLE
Allow $envmaptint to take values above 1

### ISSUE THREAD

**Issue by Kinyom** [Facepunch/garrysmod-requests#1586]
Currently, $envmaptint can be used to darken/lessen the effects of specular cubemap reflections, but there's no way to brighten/enhance them because it can only take a max of [1 1 1] for its value. It'd be incredibly useful (especially for stuff like on-the-fly cubemap tinting based on lighting, etc.) if $envmaptint could accept values like [2 2 2], [1.5 1.5 1.5], etc.

**Comment by robotboy655** [comment]
I can't even imagine how many models this will unintentionally break. All the materials people edited and just left the value of `$envmaptint` at above `1 1 1` because it made no difference.

**Comment by Kinyom** [comment]
> I can't even imagine how many models this will unintentionally break. All the materials people edited and just left the value of `$envmaptint` at above `1 1 1` because it made no difference.

Perhaps a new parameter, $envmapscale -number to scale envmap by-? Or maybe just a boolean like $allowenvmapenhance or whatever that enables values above 1, and it’s set to false by default?

**Comment by robotboy655** [comment]
The problem with adding new parameters is that shader registers are not infinite, especially on SM2.0 hardware.

**Comment by Kefta** [comment]
For reference, I just searched all the VMTs in my downloads and addons and none have $envmapint above 1. None of the VPKs of mountable content have them either (I own all of the mountable games). I know it's anecdotal, but as I haven't cleared my downloads folder since 2012 and I have over 2,000 VMTs, I think the benefits outweigh the potential cons.

Maybe a convar could even be added to print whenever a VMT is loaded with an $envmaptint value > 1 for debugging purposes.

**Comment by Kinyom** [comment]
Given what code_gs pointed out I can’t think of any good reason not to have this.

**Comment by Kinyom** [comment]
Any final word on this?

**Comment by robotboy655** [comment]
I could not find any place in the code where it is limited. As far as I am concerned, it's always was unlocked. In fact, testing it - it works as you'd expect...

![image](https://github.com/Facepunch/garrysmod-requests/assets/3299036/cf41005f-247e-425c-a282-91ef3ad759a5)
![image](https://github.com/Facepunch/garrysmod-requests/assets/3299036/a3f6d96f-c191-4df3-ac33-de3c7dea86d1)
![image](https://github.com/Facepunch/garrysmod-requests/assets/3299036/4aa5d746-dd5a-4c4e-980a-d3c163188399)
