### ISSUE TITLE
More easily add multiplayer servers to favourites

### ISSUE THREAD

**Issue by viral32111** [Facepunch/garrysmod-requests#1587]
Kind of a follow on from #1585, but I also suggest we have some sort of way to add servers to the Favourites category without having to use the Legacy Browser or be playing on the server to see the button in the Esc menu.

Such as right clicking on the server row to bring up a context menu, then clicking a "Add this server to my favourites" button? (if the server IP is already in the favourites then it would say "Remove this server from my favourites")

**Comment by WilliamVenner** [comment]
My suggestion for this is to add an outlined/filled in star icon next to each server on the list, which adds/removes it from your favourites when clicked.

Roughly the position where I think it could be:

![image](https://user-images.githubusercontent.com/14863743/81209387-63ded300-8fc8-11ea-91c2-bdf88a8bf2ec.png)

**Comment by viral32111** [comment]
> Funnily enough, there is some code already in the game that suggests this would be a feature at some point: https://github.com/Facepunch/garrysmod/blob/master/garrysmod/html/template/servers.html#L80

I'm pretty sure that code is for the existing heart icon that appears to the left of each server row. However, it only shows when that server is **already** in the favourites and it's purpose is just to identify that the server is in the favourites list, and unfavourite the server when it is clicked. 
![Annotation 2020-05-06 184300](https://user-images.githubusercontent.com/19510403/81210227-1d39aa80-8fc1-11ea-832a-a85bfd2608eb.png)

It would be nice if we had a quicker way to **add** a server to the favourites aswell (that doesn't involve using the legacy browser or actually having to fully join the server), not just a quick way to remove them.

**Comment by robotboy655** [comment]
This was added.
