### ISSUE TITLE
Add ViewModelFOV

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#1588]
Binding to ``CViewSetup.fovViewmodel``. Useful for getting the view model FOV of engine weapons and SWEPs outside of SWEP functions.

**Comment by robotboy655** [comment]
Added`render.GetViewSetup()` that has the viewmodel FOV and bunch of other stuff:

```
] lua_run_cl PrintTable( render.GetViewSetup() )
angles	=	0.000 180.000 0.000
aspect	=	1.7777777910233
bloomtone	=	true
fov	=	106.26020812988
fov_unscaled	=	90.000007629395
fovviewmodel	=	68.381813049316
fovviewmodel_unscaled	=	54.000003814697
height	=	1440
origin	=	944.000000 289.687012 -79.080002
subrect	=	false
width	=	2560
x	=	0
y	=	0
zfar	=	28377.919921875
zfarviewmodel	=	28377.919921875
znear	=	3
znearviewmodel	=	1
```

the normal FOVs are the aspect ratio corrected 'real' FOVs, the `_unscaled` FOVs are going through an inverse function, they cannot be exact, but they are close enough.
