### ISSUE TITLE
Decal overflow causing players to return to game menu when loading into various maps

### ISSUE THREAD

**Issue by Statua** [Facepunch/garrysmod-requests#1589]
I'm getting more and more reports from players who cant play on multiple maps in singleplayer because of addons that pre-cache decals into their game: Check out this post for a possible solution to getting dropped back into the menu when trying to load the map: https://steamcommunity.com/app/4000/discussions/1/1696046342855471371/

**Comment by robotboy655** [comment]
Shouldn't boot you to main menu any more on Dev, will just make all overflowed decals not work.
