### ISSUE TITLE
Add "Material Design Icons" into the game

### ISSUE THREAD

**Issue by GitSparTV** [Facepunch/garrysmod-requests#1596]
In GMod we have Silkicons which is a great thing to have in-game for icons and visual hints. Not to mention some icons (such as money) are associated with DarkRP default HUD for me.
They still looks fine, but they were made in 2006. It's 2020 right now.

I suggest to ship new icons set into the game, `mdi` (Material Desing Icons).
They are already used in the facepunch wikis.
They have no limitations in commercial use (Apache + SIL Opeb Font License).
They have variations of some icons which gives variety of choice.

https://materialdesignicons.com/ -- The main site.
https://cdn.materialdesignicons.com/5.2.45/ -- Preview of the latest icons set.
https://github.com/Templarian/MaterialDesign -- Repo with all variants of use (as svg, ttf, etc)

**Comment by robotboy655** [comment]
Ship the ones you want in your addon(s)?

Silk icons are actually used by the base game.

**Comment by GitSparTV** [comment]
The purpose of adding is to offer existing asset to be used in all addons (zero-download). So you don't need to include the same font in all addons (different authors can do it differently: upload the font again, upload it with their addons or use existing addon). Dependences are not great if you need to use not your stuff. This reminds me of Awesome font that people uses in their projects, there are lots of workshop addons with this font.

Also, I'm not asking to replace Silkicons, my request is to add them.

**Comment by robotboy655** [comment]
So by that logic let's add every popular icon set and font into the base game?

**Comment by GitSparTV** [comment]
Fair, but for some reason we have Roboto font family, same Silkicons. They were chosen and added into the game.

**Comment by robotboy655** [comment]
Again, because both are actually used by the game.

**Comment by FoksVHox** [comment]
Maybe just do, so people can enable the icon/font sets and then the game will download them on the next startup?

**Comment by viral32111** [comment]
> Maybe just do, so people can enable the icon/font sets and then the game will download them on the next startup?

Couldn't this just be acomplished with an addon that has the same paths as the current silkicons do, so the custom icons from said addon override every place where a silkicon is used?
