### ISSUE TITLE
Bind couple of NPC functions to Lua

### ISSUE THREAD

**Issue by DrVrej** [Facepunch/garrysmod-requests#1600]
Hello, there are many core NPC functions that we have no access to and would be very useful if they were binded to Lua. I will post the name and the link to the function from the 2013 source sdk on GitHub.

- `OnChangeActivity`([Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/game/server/ai_basenpc.cpp#L6411)): Currently there are many animations that we have no control over in Lua, such as jumping, turning and climbing. This would be a good way to know when the engine decides to use one of those animations.
- `GetEnemyLKP`([Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/game/server/ai_basenpc.cpp#L10097)): Returns the enemy's last known position
- `GetEnemyLastTimeSeen`([Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/game/server/ai_basenpc.cpp#L10102)): Same as above, returns the time since it last saw the enemy
- The last 2 functions above could probably be solved by exposing some of the functions [found here](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_memory.h), it includes functions for last enemy location and last seen location. Also for the time since it first saw the enemy and the last time it was in its sight.
- There is another function(s) that would be very useful as currently we have no control over it, which is the turning of the NPC, it would be very useful to be able to set the target for the NPC to face and make them turn to that target without using tasks, I believe the function `SetIdealYawAndUpdate`([Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_motor.cpp#L681)) is the correct one in this case, because [Looking here](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_basenpc_schedule.cpp#L3217), the turning-tasks use this function. There are couple other turning functions that would be very useful if binded to Lua.

Also a side note, not sure if this requires a new post in the issues repository, `AddEntityRelationship` is unable to change the relationship between NPCs if they share the same model (not class!), it forces them to always be neutral (D_NU). This is probably an unintended bug that could hopefully be solved but removing the code that blocks it from changing if it's the same model.

I hope these requests are reasonable, thank you very much!

**Comment by robotboy655** [comment]
* `NPC.MarkEnemyAsEluded` and `NPC.ClearEnemyMemory` now have an optional argument - enemy
* Added `NPC.HasEnemyEluded`, `NPC.HasEnemyMemory`, `NPC.GetEnemyLastKnownPos`, `NPC.GetEnemyLastSeenPos`, `NPC.GetEnemyLastTimeSeen`, `NPC.GetEnemyFirstTimeSeen` - All of these have an optional argument - enemy, which defaults to `GetEnemy()`
Added `NPC.SetIdealYawAndUpdate( yaw, yawSpeed = -1 )`
  * yawSpeed, -1 = Recalc automatically, -2 = Keep yaw speed, other values = set yaw speed
* Added `ENT:OnChangeActivity` for `base_ai` entities

I don't see anything in the code that would suggest your claims about `AddEntityRelationship` are true.

**Comment by DrVrej** [comment]
> * `NPC.MarkEnemyAsEluded` and `NPC.ClearEnemyMemory` now have an optional argument - enemy
> * Added `NPC.HasEnemyEluded`, `NPC.HasEnemyMemory`, `NPC.GetEnemyLastKnownPos`, `NPC.GetEnemyLastSeenPos`, `NPC.GetEnemyLastTimeSeen`, `NPC.GetEnemyFirstTimeSeen` - All of these have an optional argument - enemy, which defaults to `GetEnemy()`
>   Added `NPC.SetIdealYawAndUpdate( yaw, yawSpeed = -1 )`
>   
>   * yawSpeed, -1 = Recalc automatically, -2 = Keep yaw speed, other values = set yaw speed
> * Added `ENT:OnChangeActivity` for `base_ai` entities
> 
> I don't see anything in the code that would suggest your claims about `AddEntityRelationship` are true.

Thank you for adding these features! I will investigate the small issue I had with `AddEntityRelationship` if I find a proper way to reproduce it, I will post it on the issues repository. Thank you again!
