### ISSUE TITLE
Replace NPC/SNPC code internally with Nextbot functionality over time

### ISSUE THREAD

**Issue by VaasKahnGrim** [Facepunch/garrysmod-requests#1603]
Basically NPCs and SNPCs are considered deprocated thanks to valve creating nextbots. Nextbots so far comprise the entire AI in L4D and L4D2 and as we have seen before the game can usually handled ALOT of them all at once quite well. https://developer.valvesoftware.com/wiki/NextBot

Currently almost all the servers for mill-sim style gamemode categories use reskinned hl2 npcs which use the deprocated and ancient NPC code. Having these over time replaced with nextbots would be a bit better for alot of servers who don't have competent developers able to do this on their own. Having the normal HL2 NPCs replacing features inside the engine with those of Nextbots would help a good bit.

As long as the same reskinned AI still work but internally use the functionality of nextbots then there shouldn't be any breaking of any important addons that are used for alot of these AI.

**Comment by viral32111** [comment]
Did you accidently open two other identical issues? 🤔 #1601 #1602

If all you wanted to do was change the issue's title or content, it's possible to edit your already posted issue by clicking the three dots at the top-right of the issue comment, then pressing the edit option.

Probably best to close your other issues if this was the case, and just keep the discussion about this topic in a single issue.

**Comment by VaasKahnGrim** [comment]
yea github kept giving me an error when submitting it and I thought it was something with the title causing it. didn't know they went though

**Comment by Kefta** [comment]
Absolutely not, legacy AI and nextbots are two unique systems and should stay that way for compatibility and accuracy to HL2.

**Comment by VaasKahnGrim** [comment]
tbh valve did away with legacy AI for a reason, I'm not saying get rid of them entirely(tho tbh I don't see any legit reason to keep them) what I'm saying is replace the garbage code for things such as navigation with nextbots and making them not as garbage when it comes to performance

**Comment by Kefta** [comment]
This is addon territory. There is no reason to replace functioning code just to ruin compatibility and legacy behaviour. Valve still uses legacy AI for CS:S bots, HL2 NPCs, and more in pre-L4D games, there's no reason to change that in GMod.

**Comment by NathanX-S** [comment]
this is up to the addon creators to solve, this should be closed

**Comment by VaasKahnGrim** [comment]
I'll agree to disagree, the legacy AI is utter garbage and there already are addons meant to replace it. the problem is that people refuse to use them and keep opting for using reskinned HL2 combine npcs.

**Comment by VaasKahnGrim** [comment]
not to mention that addons aren't able to touch AI shit thats written in the engine itself. so in the end replacing crappy code is the best option anyways.

**Comment by Fafy2801** [comment]
I beg to differ, replacing code WILL break things unnecessarily, it's the worst option. You say the legacy AI is bad but then say that there's a replacement for them, and if people refuse to use them why force them to. All in all this change will bring more harm than good.

**Comment by JustPlayerDE** [comment]
I agree that a change like this will break everything based on the "legacy" npc stuff

(and no, a newer system is not a valid reason if it breaks more than it fixes)

**Comment by neico** [comment]
This doesn't even touch the subject that there are cases where NextBot isn't very suitable for,
think flying/swimming NPC's that still require air nodes or some kind of path track that is not on the ground.
This isn't covered by the NavMesh at all.

**Comment by robotboy655** [comment]
This is just unfeasible and pointless.
