### ISSUE TITLE
Add MDLCache::Flush before the map changing.

### ISSUE THREAD

**Issue by Headshotz** [Facepunch/garrysmod-requests#1604]
I made a request because I tested on CS:GO and CS:S, that they actually fixed it. I believe this is should fixed the vertex error with just call Flush.

**Example the error:**
**Error Vertex File for 'props_c17/door01_left.mdl' checksum 145318345 should be 972034250**

The model cause the conflict from recent maps to another map. Its will fix by just calling mdlcache::flush before the map changing or GMOD_MODULE_CLOSE (actually same as ShutDown).

If its unsafe then please add the cvar, that should works on server and client as well.

**Comment by Kefta** [comment]
This might also fix https://github.com/Facepunch/garrysmod-issues/issues/2650.

**Comment by Headshotz** [comment]
I've created module for calling MDLCache::Flush() on GMOD_MODULE_CLOSE function. I can confirm its fixed the vertex errors after I tested over 80 maps without restart the game.

**Comment by mcNuggets1** [comment]
Still don't understand, why GMod does maintain model, material, lua cache and everything of that sort, after a successful disconnect or map change.

**Comment by Kefta** [comment]
Probably for efficiency.

**Comment by thegrb93** [comment]
Back when hl2 took 3 minutes to cold-start, it makes sense. Now it doesn't matter.

**Comment by robotboy655** [comment]
This is just a more crash prone version and worse version of r_flushlod. It crashes the physics engine if called on level start or shutdown.

Running r_flushlod on disconnect may be viable (I have tested it, it works), but:
1) I have seen crash reports regarding it https://github.com/Facepunch/garrysmod-issues/issues/4401
2) It will increase subsequent loading times in a session, i.e. reloading a map will be slower
3) You will get the model loading freezes every time you start a new map, etc

Probably should move this discussion to https://github.com/Facepunch/garrysmod-issues/issues/2650 as this is what you want fixed as far as I can tell.
