### ISSUE TITLE
RichText enhancement

### ISSUE THREAD

**Issue by art-gur** [Facepunch/garrysmod-requests#1606]
Richtext is userful thing thats allow you to add a lot of text in witch you can change color in any part of it and add clickable area getting one vgui panel unlike DLabel.

But some restrictions of RichText make it non customizable, for example.
You can't:
1. change highlight color, when text was selected
2. hide strange default engine menu or customizable it
3. catch mouse pressed or wheeled events
4. customize font in clickable text

It would be cool, if all this things will be added to game 🥰

**Comment by robotboy655** [comment]
4. https://wiki.facepunch.com/gmod/Panel:SetUnderlineFont

**Comment by robotboy655** [comment]
Fixed OnMouse* and OnCursor* hooks not working on panels derived from RichText, so 2. and 3. are now solved on Dev.

**Comment by Fruityman577** [comment]
Any progress on 1: "change highlight color, when text was selected"?

It's changeable in the ClientScheme.res, just not by any helper functions.
`RichText.SelectedBgColor "192 28 0 140"`
