### ISSUE TITLE
Usermessage to net autoconverting

### ISSUE THREAD

**Issue by FalseGM** [Facepunch/garrysmod-requests#1611]
It seems that it's time to change the outdated library and replace it with The net library. A soft transition will be to create an autoConvert function. Why is this necessary? You yourself have been trying to give it up for 5 years, and Addons continue to do :/

**Comment by Kefta** [comment]
Willox said he would change usermessages to use net messages internally years ago. I don't know what happened to that.

**Comment by VaasKahnGrim** [comment]
@willox as a placeholder you could atleast make this a default part of the game until the umsg crap is finally dumped internally https://github.com/SuperiorServers/dash/blob/master/lua/dash/libraries/usermessage.lua

**Comment by Kefta** [comment]
I wrote that library. It's outdated and doesn't really work properly, I don't know why it's still in Dash. It'd be way better to do internally since there is no good umsg:Reset alternative for the net library.

**Comment by VaasKahnGrim** [comment]
Old or not it actually has been working well with DarkRP so far which considering 90% of servers are DarkRP its one of the best options atm for it until its done internally

**Comment by VaasKahnGrim** [comment]
well not so much the best option as its more the only one well known about

**Comment by Kefta** [comment]
That doesn't mean it should be implemented by default into the game.

**Comment by VaasKahnGrim** [comment]
guess we could always wait another 5 years for it to be done internally in the game instead

**Comment by robotboy655** [comment]
What is the point of this? What's the point besides telling developers it's OK to use the usermessage library now, to have 2 identical systems?

**Comment by thegrb93** [comment]
Not to mention it would likely break things since net doesn't properly network entities.

**Comment by Kefta** [comment]
The point is to convert stuff that is already using usermessages for legacy reasons/API compatibility (DarkRP). Changing over to net in the Lua code could break addons expecting usermessages. Usermessages are deprecated so people wouldn't use it over net.

@thegrb93 Legacy behaviour can be hacked in, they don't have to be exact aliases.

**Comment by FalseGM** [comment]
Autoconversion is a softer version of the transition.

**Comment by robotboy655** [comment]
> The point is to convert stuff that is already using usermessages for legacy reasons/API compatibility (DarkRP). Changing over to net in the Lua code could break addons expecting usermessages. Usermessages are deprecated so people wouldn't use it over net.

Again, why is this necessary? What's the benefit?

**Comment by thegrb93** [comment]
@Kefta I was referring to the fact the networking entities in net library suffers from networking race conditions that umsg doesn't in certain cases.

**Comment by DBotThePony** [comment]
There are addons which rely on `net.Start ... ; umsg.Start ... ; umsg.End ; net.Send`, so this **will** break existing addons.
