### ISSUE TITLE
Ability to disable crazy physics entirely.

### ISSUE THREAD

**Issue by Evans-Developer** [Facepunch/garrysmod-requests#1613]
Currently, we have some convars which enable us to suppress a few features of the crazy physics protection.

I've recently started a larger project and it requires moving entities past a limit where crazy physics kicks in and stops the entity from going any further. Now I know these features are in place to reduce crashing etc however we should be able to disable these completely at our own discretion.

**Comment by Kefta** [comment]
Or at least add a convar to set the cutoff speed directly.

**Comment by Evans-Developer** [comment]
> Or at least add a convar to set the cutoff speed directly with any val < 0 disabling the protection.

Yeah I mean that'd solve it for speed. For me its about an entity being too far from World origin so it'd be nice if I could disable that.

**Comment by robotboy655** [comment]
```
sv_crazyphysics_defuse 0
sv_crazyphysics_remove 0
```

There you go.

**Comment by Evans-Developer** [comment]
Are you able to explain what exactly thw defuse convar does? I was recommended it prior to opening this and it didn't seem to dm anything in my case

**Comment by robotboy655** [comment]
As their help text suggests (`sv_crazyphysics_defuse` in console), it defuses the crazy physics object, i.e. set velocity to 0, set pos/ang to 0,0,0, etc.

**Comment by Evans-Developer** [comment]
@robotboy655 When I was using these they still gave "Ignoring unreasonable position" and stopping my object moving further away from the origin after moving too far. Unless this is not related to crazy physics?

**Comment by robotboy655** [comment]
That would be correct then. The entities are restricted to the -16k to +16k on each axis in terms of position, etc

**Comment by Evans-Developer** [comment]
Is this the same when using SetPos on the clientside? I've managed to get the position to x:100,620 y:92,896 z:-15,652 before.

**Comment by robotboy655** [comment]
yes

**Comment by Evans-Developer** [comment]
How am I managing to get above the 16k in either direction then?

**Comment by robotboy655** [comment]
So here's the situation:
* Lua SetPos, etc  functions are limited to 8*16k in every direction from origin.
* engine's SetLocalOrigin and physics (Specifically MOVETYPE_VPHYSICS entities, when the entity is set to its physobj position) are limited to 16k in every direction

**Comment by Evans-Developer** [comment]
This information is really useful, thanks!
