### ISSUE TITLE
Binding NextBot functions to lua

### ISSUE THREAD

**Issue by Roachdaripper** [Facepunch/garrysmod-requests#1614]
I was looking at the NextBot source code and noticed some functions that could definitely see some use in gmod, as the current alternative is extremely hacky, expensive, and requires hooking into a lot of things.

[NextBotManager.CPP]
NEXTBOT:Reset()
From what I can tell this appears to restart the coroutine and make the nextbot act like it was just spawned.

NEXTBOT:OnSound(CBaseEntity source, Vector pos, Keyvalues keys)
Allows nextbots to hear things, without having to hook into EntityEmitSound

[NextBotVisionInterface.CPP]
NEXTBOT:IsAbleToSee(CBaseEntity subject, Vector visibleSpot)
A nextbot equivalent of ent:Visible would be nice :)

[NextBot.CPP]
NEXTBOT:IsUsableEntity(CBaseEntity entity, requiredCaps)
NEXTBOT:UseEntity(CBaseEntity entity, USE_TYPE useType)
Having the ability for bots to +use things like buttons or doors is an amazing feature and one that I sincerely hope above all else is added

Thanks for reading :)

**Comment by robotboy655** [comment]
Engine's `OnSound` is never actually called from my testing, so that is unfortunate.
`Reset()` you can easily achieve yourself.

**Comment by Roachdaripper** [comment]
> Engine's `OnSound` is never actually called from my testing, so that is unfortunate.

Darn...

> `Reset()` you can easily achieve yourself.
Fair enough, but what are the others being taken into consideration?

**Comment by bizzclaw** [comment]
These suggestions are interesting, but pretty much all these you can already do with the tools we have for nextbots.

For instance, you can reset a nextbot's coroutine with **ENT:BehaveStart()**, line of sight checks can be achieved with a few traces, ect.

**Comment by Roachdaripper** [comment]
Bumping.
@robotboy655 would you be able to add the use functions for nextbots? it would be so much more optimized than running loops or traces all the time checking for doors, buttons, etc.

**Comment by robotboy655** [comment]
I don't see how those would help you avoid "running loops or traces all the time checking for doors, buttons, etc.".

You can already simulate +use on entities by simply doing `Entity:Fire( "Use" )` or using `Entity.Input`, although I might add a function for it anyway (for all entities, not as `Nextbot.UseEntity`) to allow for custom `UseType`.

You can recreate `IsUsableEntity` yourself with `Entity.ObjectCaps` or just do whatever logic you need, so I am definitely not adding that.

**Comment by robotboy655** [comment]
You want them to automatically open doors? No, that's not happening. It's up to you to code how or if that interaction should occur. It wouldn't be more optimized in C++.

**Comment by robotboy655** [comment]
https://wiki.facepunch.com/gmod/Entity:Use(function)
This already exists.

* Added NextBot.IsAbleToSee( ent, useFOV = true )
* Added NextBox:GetFOV()
* Added NextBox:SetFOV( fov )
* Added CNavArea.IsPotentiallyVisible( cnavarea )
* Added CNavArea:IsCompletelyVisible( cnavarea )
* Added CNavArea:IsPartiallyVisible( eyepos, ignoreEnt = NULL )
