### ISSUE TITLE
Entity Filter HOOK for game.CleanUpMap or IgnoreOnCleanup Flag

### ISSUE THREAD

**Issue by KingDavidW** [Facepunch/garrysmod-requests#1617]
Currently CleanUpMap has a filter argument that prevents those entities specified from being removed

There is no way to access that argument unless you call the function yourself, meaning if some other addon or function calls CleanUpMap, you need to recreate your entities from scratch.

This is problematic especially if you have entities with states, as the only way to handle the cleanup is to search, store, and recreate after the cleanup.

I think a hook for adding entities to this filter would be great. It could even double down and be in the PreCleanupMap hook

Alternatively, giving us a way to flag an entity to be protected from cleanup would be good enough IE: _ENTITY:IgnoreOnCleanup( true )_

**Comment by robotboy655** [comment]
https://wiki.facepunch.com/gmod/Enums/EFL#EFL_KEEP_ON_RECREATE_ENTITIES

This can be used now.
