### ISSUE TITLE
Increase limits imposed by vbsp

### ISSUE THREAD

**Issue by stopmotio** [Facepunch/garrysmod-requests#1618]
GMod has always been the game of choice for those trying to test the source engine, so it just makes sense.I think 100,000 would be a good start for brush model limit and others.

**Comment by VaasKahnGrim** [comment]
better to just outright remove the limits than to increase them. but both are certainly better than the current limits with vbsp/vvis/vrad

**Comment by robotboy655** [comment]
It's not as simple as increasing or removing these limits. A lot of them are directly imposed by the .bsp file format, or by the architectural decisions of the people who made the engine.

If you have a specific limit you want looked into, do share the exact error message you are hitting with vbsp, or the exact name of the limit.

**Comment by stopmotio** [comment]
> It's not as simple as increasing or removing these limits. A lot of them are directly imposed by the .bsp file format, or by the architectural decisions of the people who made the engine.
> 
> If you have a specific limit you want looked into, do share the exact error message you are hitting with vbsp, or the exact name of the limit.

For me specifically the brush model limit. I do understand that source is very old at this point but since it's the 16 bit integer limit I thought it could be upped to at most the 32 bit limit. Also, thanks for replying!

**Comment by neico** [comment]
For the record:
Changing data storage types in the BSP requires a new BSP version as changing the size of the header fields also makes the header itself grow,
and with that changes all offsets to read a file.
There is a reason why valve created `.vmap` for source2 to lift certain, if not all limits.

Anyway, `brush model limit` probably means `MAX_MAP_MODELS`, with the error message `Too many brush models in map, max = %d`
the best it could be upped would be `32 767`, without having to change some code (making `int` an `unsigned int` and then moving to 32 bit or even 64 bit)
And GMod currently has it set to `1024`, so there's still a lot of room before it gets troublesome
This limit is one of the few that is only limited by the variables that are used to count the amount of models (at least if I understood the code correctly, the BSP format files can be a bit confusing at times)

Of course things like the stringtables need to account for such an increased size too.

The only other limits that appear rather small in comparison to the others would be (based of source2013 values)
`MAX_MAP_AREAPORTALS = 1024`
`MAX_MAP_CUBEMAPSAMPLES = 1024` (this one probably doesn't ever need to change)
`MAX_MAP_TEXTURES = 1024`
`MAX_MAP_OVERLAYS = 512`

Here's also the output of what limits gmod currently spews out on map compile (with comparison to source2013 and hidden limits): https://puu.sh/FT9C7/af615ee38f.txt

**Comment by robotboy655** [comment]
Ok, I have quadrupled the max to `4096`. @neico is right that too many models will fill the stringtables which will cause other problems on the server and 4x the limit should be plenty. (No effing clue why map models are included into that stringtable, one would assume all map models would be force precached, oh valve)
