### ISSUE TITLE
Increase or remove flex vert limit (currently 10,000)

### ISSUE THREAD

**Issue by AutismoPiggo** [Facepunch/garrysmod-requests#1619]
Please update gmod's flex vert limit of 10,000
SFM currently has no limit at all, or at least the limit is so high that its never been hit.
Removing it would be preferable but 60,000 would be a good limit if the developers would prefer a limit.

This would mean SFM models would be able to have none-broken faceposing and give modellers a much easier time of porting whilst keeping quality.

Here is an example model alongside some images of what currently happens when the flex limit is broken
https://mega.nz/file/wuw1CYzT#ku5VzGZx_7EApdTmUk2x1Vzcfm8RDT1nywxejyj4DFI

https://i.imgur.com/lBvwkux.jpg
https://i.imgur.com/Udp7gzZ.jpg
It's Jill Val from RE3, ported by ArachnitCZ. All of his SFM models have this issue in gmod, ergo his gmod ports are specifically modified to get under the limit but he and many other SFM modellers find this a long, annoying process and would greatly appreciate this change.

(If images are not viewable to anyone reading, any verts that go above the limit freeze in place. This could be eyebrows, hair or even the entire jaw. Depends on the model.)

**Comment by AutismoPiggo** [comment]
If anyone is understandably concerned for the effect this might have regarding terrible server owners making extremely high vert models: It's already possible, up to the millions of verts.

This would simply mean faceposing won't be broken on models already in source and SFM, ergo thankfully this change would have absolutely no effect on the multiplayer community of gmod.

**Comment by robotboy655** [comment]
Looks like it has no effect on overall memory usage in my testing, so gonna increase it to 65k, we shall see if people spot any problems with it.

Removing the limit is not an option, or it would've been done by Valve if the comments in the code are to be believed.
