### ISSUE TITLE
Add function to get a player's current reverb/echo DSP

### ISSUE THREAD

**Issue by Kinyom** [Facepunch/garrysmod-requests#1622]
I'm trying to detect whether a player is in an echoey/reverb-y space like a room or out in the open. It seems that the dsp_automatic CVar contains this information, but there doesn't seem to be a way to access it on a per-player basis. Could one be added, and if not, how should I go about checking this?

**Comment by robotboy655** [comment]
It will be different for every player on their client, so you'd need to GetConVarNumber on client of the player want to get current DSP of.

**Comment by Kinyom** [comment]
> It will be different for every player on their client, so you'd need to GetConVarNumber on client of the player want to get current DSP of.

I'm looking to get their DSP serverside - sorry, I should have clarified.

**Comment by robotboy655** [comment]
It's a clientside effect, you cannot get it serverside.
