### ISSUE TITLE
Escape menu hooks

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-requests#1624]
I have a chatbox and need to not trigger the escape menu, when someone opens the escape menu, when in the chatbox, to close it.
I manually do it via the "cancelselect" concommand, but it shows for a frame.

It would be neat if there were a hook for this.
As the escape menu can already be circumvented by a lot of things, this wouldn't hurt.

**Comment by Srlion** [comment]
Sorry for late comment, but this is something that I really want for my chatbox.

> This is something that would need to be solved before this request can be considered.

why do we have ```gui.HideGameUI()``` if that's something that needs to be solved, it's just annoying when you want to type something like **`** or try to close the chatbox and the escape menu shows for a split second.
Just remove ```gameui_preventescapetoshow``` from blocked concommands.

**Comment by garryspins** [comment]
```lua
hook.Add("Think", "RemoveMenu", function()
  gui.HideGameUI()
end )
```

```lua
hook.Add("CanOpenMenu", "RemoveMenu", function()
  return false
end )
```

Only difference would be that it doesn't flash for a frame, this could be useful for chatboxes, main menu rewrites, any UI that wants keyboard only support improving accessibility. Your hatred of this useful feature is infuriating and arbitrary, if there was a security risk or a problem with not allowing the menu to be closed from lua, then many functions need to be altered/removed. If there is some reason that this is impossible, then why havent we been given a reason.

**Comment by garryspins** [comment]
I dont see a problem.

**Comment by robotboy655** [comment]
Added `GM:OnPauseMenuShow`

This is meant to replace other methods of hiding the mainmenu (which will be disabled at some point). Return false to prevent main menu from showing for that key press.

The user can hold SHIFT to bypass this hook at any time, in case the server/addon has malicious intent of not allowing the player access the main menu.

**Comment by garryspins** [comment]
Wiki page created, thank you Rubat, much needed addition! https://wiki.facepunch.com/gmod/GM:OnPauseMenuShow
