### ISSUE TITLE
Enable Visual Styles 6.0 in Hammer Editor

### ISSUE THREAD

**Issue by Jaffies** [Facepunch/garrysmod-requests#1625]
Enabled Visual Styles 6.0 allows hammer to look more modern and fancy.
It is arleady implemented into Slammin's Hammer Editor and in the CS GO's one.

**Comment by GitSparTV** [comment]
Is the visual styles a thing for vrad or for Hammer UI?

**Comment by Jaffies** [comment]
> Is the visual styles a thing for vrad or for Hammer UI?

Nope, just look at the buttons. Hammer without Visual Styles 6.0 has ugly-looking XP-styled buttons.

**Comment by robotboy655** [comment]
Applied, lets see if this makes people on WinXP come out from under their rocks.
