### ISSUE TITLE
Add HexToColor

### ISSUE THREAD

**Issue by FoksVHox** [Facepunch/garrysmod-requests#1627]
It would be nice to see a function called `HexToColor(#aaaBbb)`, so we don't have to convert the Hex color to an RGB color

**Comment by viral32111** [comment]
```lua
function HexToColor( hex )
	local hex = hex:gsub( "#", "" )
	local red, green, blue = hex:sub( 1, 2 ), hex:sub( 3, 4 ), hex:sub( 5, 6 )
	return Color( "0x" .. red, "0x" .. green, "0x" .. blue )
end
```

Works, but will throw errors if you pass an invalid hex string ([original](https://gist.github.com/jasonbradley/4357406)).

**Comment by FoksVHox** [comment]
Oh didn't see that..
