### ISSUE TITLE
Suggestion: Don't remount addons in-game

### ISSUE THREAD

**Issue by ecumber** [Facepunch/garrysmod-requests#1629]
When in-game, it can sometimes take a really long time to remount addons. I think that the game should remount them while in the menu instead, since it won't take as long and the changes won't load in-game anyway.

**Comment by viral32111** [comment]
Wouldn't this break in-game addons that rely on downloading and mounting addons live? such as Outfitter, for example.

**Comment by robotboy655** [comment]
The changes actually do apply immediately, for example try subscribing to this addon while in a singleplayer map:
https://steamcommunity.com/sharedfiles/filedetails/?id=104606791

And then enter this command into your console to actually load the code from the addon:
`lua_openscript_cl autorun/rb655_battery.lua`

For addons with models it's easier, you can just spawn them immediately, only thing is the spawnmenu needs to be reloaded for the addon to appear in it.

For example:
https://steamcommunity.com/sharedfiles/filedetails/?id=2133127530

Sub to that, wait for to download, run `spawnmenu_reload` in your console and boom, you can use that model without any restarts.
