### ISSUE TITLE
custom map category

### ISSUE THREAD

**Issue by Combine900** [Facepunch/garrysmod-requests#1630]
Im not sure if i already made a request years ago sorry if me or someone else did so.

Can we have a simple feature that allows mappers too create their own map category?

as far as i know its just possible if you create a custom gamemode, or use known gamemodes like rp = roleplay, ttt = trouble in terrorist town

**Comment by Kefta** [comment]
How would this be registered? Reading each bsp file would slow down the loading screen by an absurd amount.

**Comment by Combine900** [comment]
> 
> 
> How would this be registered? Reading each bsp file would slow down the loading screen by an absurd amount.

thats why im asking. i think you know what you talking about.

wonder what rubat think about that

**Comment by Kefta** [comment]
Maybe by a text file read by the server ex. ``dm_mymap.txt``, but that's already used by a number of maps for custom info. Rubat might have a different idea.

**Comment by viral32111** [comment]
A potential solution would be a Lua function to the `MapNames` table [in this file](https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/menu/getmaps.lua), then mappers just have to include a small Lua script bundled with their map (or even use that run lua entity available to mappers) which registers their custom map category. Not the best solution, but it would work ¯\\_(ツ)\_/¯

Example:

```lua
util.RegisterMapCategory( "ex", "My Example Game" ) -- Where ex would be the map's prefix (e.g. ex_whatever)
```

This way, it's not just limited to mappers, but anyone who's making an addon could also register their own map category, such as a custom gamemode adding it's own map category. Then mappers making maps for this custom gamemode wouldn't all have to bundle/add extra information inside the map about the map's category.

**Comment by robotboy655** [comment]
I don't see why you'd need this, especially for 1 map, except for petty reasons like "MY MAPS MUST HAVE CUSTOM CATEGORY CUZ ITS SPECIAL"

**Comment by Kefta** [comment]
It has precedent - custom maps like https://steamcommunity.com/sharedfiles/filedetails/?id=222346103, https://steamcommunity.com/sharedfiles/filedetails/?id=221148728, and https://steamcommunity.com/sharedfiles/filedetails/?id=218185156 were created for CS:S as deathmatch maps but do not have a prefix. They were specifically named as such to appear "abstract" and "artistic" but are currently lumped with "Other".

**Comment by robotboy655** [comment]
But do you need each map to have its own category? The categories are mostly meant for gamemodes/games, if you need a specific map, you find it using search,

**Comment by Combine900** [comment]
> 
> 
> But do you need each map to have its own category? The categories are mostly meant for gamemodes/games, if you need a specific map, you find it using search,

well it would be a cool feature if you make more maps

**Comment by Kefta** [comment]
You can close it yourself; thought I agree with this issue's general idea I can't see how this can be implemented practically.
