### ISSUE TITLE
Allow for table of two volume values for sound.Add - or correct Wiki entry

### ISSUE THREAD

**Issue by Kinyom** [Facepunch/garrysmod-requests#1631]
Currently, the wiki states that [sound.Add's "volume" entry can be given a table of two min-max values](https://wiki.facepunch.com/gmod/Structures/SoundData). However, after testing this on the dev branch (and many previous branches; this has been a long-standing issue), it simply doesn't work. If you provide a table, the volume will just default to 1 each time you play it.
Could this functionality be added (I'd err on the side of this, as it'd be incredibly useful to have randomized volumes without needing to hook into EntityEmitSound), or the wiki entry corrected?

**Comment by robotboy655** [comment]
It definitely already works as described on the wiki.

```
sound.Add( {
	name = "EpicMetal_Hard",
	channel = CHAN_STATIC,
	volume = {0.01,1.0},
	level = 80,
	pitch = 100,
	sound = "phx/EpicMetal_Hard.wav"
} )
timer.Create( "test_sound", 0.1, 0, function() Entity(1):EmitSound("EpicMetal_Hard") end )
```

**Comment by GitSparTV** [comment]
Kinyom, check wiki page again, the warning was added
