### ISSUE TITLE
does not seem to be anything on the wiki for a PANEL:OnHoverStart() or PANEL:OnHoverEnd()

### ISSUE THREAD

**Issue by VaasKahnGrim** [Facepunch/garrysmod-requests#1636]
There doesn't seem to be anything that would basically function in this way for vgui elements. the only thing I can seem to find is a PANEL:IsHovered() which basically is only useful for if your creating new vgui elements with their own PANEL:Paint() function. but other than that its kinda useless.

Could we get those two functions added please

**Comment by viral32111** [comment]
These already exist and basically act as an "on hover start" and "on hover end":

[`PANEL:OnCursorEntered()`](https://wiki.facepunch.com/gmod/PANEL:OnCursorEntered)
> Called whenever the cursor entered the panels bounds.

[`PANEL:OnCursorExited()`](https://wiki.facepunch.com/gmod/PANEL:OnCursorExited)
> Called whenever the cursor left the panels bounds.

**Comment by VaasKahnGrim** [comment]
ah overlooked those, perhaps garry should put in a sort of alias for functions when searching then since he's decided to use his own wiki software now. thanks dude
