### ISSUE TITLE
Remove 5% Weight Bone Link Cull In Studiomdl

### ISSUE THREAD

**Issue by Raxsyz** [Facepunch/garrysmod-requests#1637]
As you may know, by default studiomdl tends to have a limit where if a model's vertex has link to a bone with a weight below 0.05 (5%), studiomdl will ignore that bone for that vertex.

Meaning, for a very high poly models, this brakes the models rigging. Essentially the models have spiky weights when moving bones around, looking kinda messy.

The fix is as simple as changing the value from "9A 99 99 99 - 99 99 A9 3F" to "01 00 00 00 - 00 00 00 00" in the offset "0x5BE020" (the offset might be different in Gmod version.)

This technique will remove 99% of culling in the models weights, and it will benefit all of the model porters (including myself) with better and smoother weights on high poly models. Especially at the times like these where games tend to have highly detailed models.

**Comment by robotboy655** [comment]
Changed from 0.05 to 0.0001 (matches csgo)
