### ISSUE TITLE
cl_phys_timescale is flagged as a client side cheat

### ISSUE THREAD

**Issue by MagentaIris** [Facepunch/garrysmod-requests#1641]
Not sure why this is the case, Figured i'd ask to see if this was possibly planned to be changed at all in the future to allow free control over it.

If not i'll have to make a custom library for it on the client, but i'd rather not waste my time on that if it's possibly getting changed in the near future, Thanks for any heads up on this.

**Comment by robotboy655** [comment]
No, there are no plans in changing this. I imagine it is a cheat because Valve didn't want it changed in multiplayer, etc.

**Comment by MagentaIris** [comment]
Rip in pip, Work around time.
