### ISSUE TITLE
add support for point_message in multiplayer

### ISSUE THREAD

**Issue by weaponcubemap** [Facepunch/garrysmod-requests#1650]
point_message is a text box sprite, that's being used by mappers. Add support or spawnflag for this entity, would be great

**Comment by robotboy655** [comment]
Well, I fixed it not working for the server's host in local multiplayer. but it cannot be easily fixed for all players without completely redoing that entity which I won't be doing at this time.

**Comment by weaponcubemap** [comment]
Yep, thank you
