### ISSUE TITLE
GM:PlayerCanHearPlayersVoice on client side

### ISSUE THREAD

**Issue by arkayden** [Facepunch/garrysmod-requests#1652]
https://wiki.facepunch.com/gmod/GM:PlayerCanHearPlayersVoice
**Please add this to client side because it requires a lot of performance on the server, it would be nice to use it on the client.**

**Comment by robotboy655** [comment]
This is not how it works. The point of the GM:PlayerCanHearPlayersVoice is to determine where to send the voice data. It cannot function on client.

**Comment by arkayden** [comment]
> Это не так, как это работает. Задача GM: PlayerCanHearPlayersVoice - определить, куда отправлять голосовые данные. Он не может работать на клиенте.

Не требуется сделать дубликат этой функции на клиенте, требуется запрещать слышать игрока без использования https://wiki.facepunch.com/gmod/Player:SetMuted на клиенте. Эта функция нужна для создания систем слышимости без использования производительности сервера.

**Comment by Kefta** [comment]
If you do want something like PlayerCanHearPlayersVoice clientside as an alternative to SetMuted, then it shouldn't be called PlayerCanHearPlayersVoice because it will start making code that registered the hook shared start to do unintended things. It would also confuse people into thinking the hook is predicted or something.

**Comment by arkayden** [comment]
> If you do want something like PlayerCanHearPlayersVoice clientside as an alternative to SetMuted, then it shouldn't be called PlayerCanHearPlayersVoice because it will start making code that registered the hook shared do unintended things. It would also confuse people into thinking the hook is predicted or something.

"Decides whether a player can hear another player using voice chat." - так написано на wiki. Как она работает "под капотом" мы знать не можем. Неважно как будет называться данная функция, главное - чтобы мы могли контролировать слышимость игроков на клиенте, для создания системы слышимости без использования производительности сервера.
