### ISSUE TITLE
subcategory for weapons

### ISSUE THREAD

**Issue by Combine900** [Facepunch/garrysmod-requests#1655]
can we have a feature that allows modders too create a subcategory for weapons?

as example prop spawnlists have these "subcategories" (RED standard), (BLU standard) etc.
![](https://i.imgur.com/63nKovG.png)

That would be a great cleanup and a cool feature that our weapon modders could use.
![](https://i.imgur.com/wGTaDJF.jpg)

**Comment by viral32111** [comment]
Having the treenode system on the left sidebar similar to the spawnlists category sidebar would be nice too. It would allow for addon packs to have a single category (e.g "My Amazing Weapon Pack"), then that node would expand to reveal types of weapons (e.g. Pistols, Shotguns, Assault Rifles) and then inside the main view it could be sorted up into even more subtypes, such as size of weapon. It would also be nice if this was available in the other tabs, such as Entities, NPCs, Vehicles, etc. (and yes I already know all of this can be done already with custom spawnmenu tabs, but I don't think it can be done with default tabs without overriding the default spawnmenu files.)

**Comment by Combine900** [comment]
@robotboy655 Is it possible to do it?

**Comment by robotboy655** [comment]
It's possible, but is it necessary?

**Comment by Kefta** [comment]
It will look nicer for big categories of weapons, ex. TFA, M9K, etc.

**Comment by FoksVHox** [comment]
> It's possible, but is it necessary?

Not really. But if you could create a "dropdown" in the spawnmenu I think that would be usefull. So you would have the name and then you'd have a arrow, click on the arrow and the it would expand? Hope it makes sense

**Comment by Combine900** [comment]
> 
> 
> It will look nicer for big categories of weapons, ex. TFA, M9K, etc.

Exactly 👍
