### ISSUE TITLE
Could we get a proper way of creating air/ground/water/stationary vehicles

### ISSUE THREAD

**Issue by VaasKahnGrim** [Facepunch/garrysmod-requests#1657]
Currently it seems most vehicles are stuck with using the vehicle txt scripts that come default in source engine. Its very limiting to really go about actually making proper vehicles with them.

Alot of people seem to opt for having a custom entity and then parenting several of these other entities onto it in order to create a functioning vehicle, but this is kinda shitty as instead of 1 entity you now have several entities for a single vehicle. While you can do something as simple as seen [HERE](https://github.com/Facepunch/garrysmod/blob/394ae745df8f8f353ea33c8780f012fc000f4f56/garrysmod/lua/autorun/base_vehicles.lua)

its also very limited as all you can really do is have a single player inside the vehicle. That and your still forced to use the txt vehicle scripts.

It would be very helpful if we had specific stuff in the game for creating new vehicles that didn't involve these txt entities at all. I heard that such a thing was brought up early in the gmod13, would be nice if that actually made it into the game given how many years its been.

**Comment by robotboy655** [comment]
This is extremely vague and is essentially modding territory. You have https://wiki.facepunch.com/gmod/Vehicle:SetVehicleParams so you don't necessarily have to use a custom vehicle script .txt, even though it's literally not a problem.

**Comment by VaasKahnGrim** [comment]
Ok, and what if the vehicle that somebody is trying to make isn't a car? Logically there would be none of these in it to begin with in that case. https://wiki.facepunch.com/gmod/Structures/VehicleParams. so the SetVehicleParams is kinda useless at that point because it seems to only be useful for car vehicles.

I'd also say its not all that vague at all. There is legit no proper method of creating new vehicles for the game. Pretty much everything on this entire page is just for interacting with already made vehicles or vehicles that relly on the txt vehicle scripts https://wiki.facepunch.com/gmod/Vehicle.

**Comment by Kefta** [comment]
You don't have to use the official Vehicle structure if you aren't making a car, you can just make a SENT that acts as a vehicle. What you're asking for exactly isn't very clear since this all seems possible to do in Lua.
