### ISSUE TITLE
DTextEntry's Right Click DMenu 

### ISSUE THREAD

**Issue by orionman** [Facepunch/garrysmod-requests#1662]
Currently there is no possible way of retrieving/editing/removing the DMenu that opens up when you right click a DTextEntry
Adding something like 
`DTextEntry:GetDMenu()` 
Or transferring the DMenu purely into lua would be useful for a lot of things

I know there is already a DMenu associated with DTextEntries which is used for AutoCompletion but thats not really a problem

Translating the DMenu into lua could be a problem due to it having language options and an option to Paste that could be used that as a way to get clipboard text

Images of what im talking about:

![image](https://user-images.githubusercontent.com/56239348/88488662-9eab3400-cf43-11ea-9329-4b2d6be8b4cd.png)
![image](https://user-images.githubusercontent.com/56239348/88488675-af5baa00-cf43-11ea-89b8-177076d2f8a9.png)

**Comment by GitSparTV** [comment]
Language is problematic to bind

**Comment by orionman** [comment]
I know it is but it seems silly not to be able to do anything with it, atleast paint it

**Comment by GitSparTV** [comment]
I wonder if GetChildren works when this menu is opened

**Comment by orionman** [comment]
hmm ill try it right now

**Comment by orionman** [comment]
It does but it seems to be nothing seen on the wiki 

1	=	Panel: [name:EditMenu][class:Menu][948,550,105,108]

**Comment by robotboy655** [comment]
The paste button is exactly why this cannot be changed.
