### ISSUE TITLE
Move render.GetSurfaceColor() feedback

### ISSUE THREAD

**Issue by TankNut** [Facepunch/garrysmod-requests#1666]
Using render.GetSurfaceColor() on certain surfaces (e.g. grates, windows) or on the air outputs white along with the following message being printed in your console:

`Couldn't find surface in GetColorForSurface()`

All I'm asking for is that this message is hidden behind `developer 1` or something like that, seeing as it's next to impossible to filter out every case of this happening _before_ the function is called and depending on what kind of code you're using it in it can get very spammy very quickly
![2020-07-29_16-24-20](https://user-images.githubusercontent.com/1381265/88812433-fce04d00-d1b7-11ea-94fb-3966a0ff5748.png)

**Comment by robotboy655** [comment]
Done.
