### ISSUE TITLE
Zombie buff.

### ISSUE THREAD

**Issue by Hunkersan** [Facepunch/garrysmod-requests#1669]
There was alot of zombie related mods, but none of them were able to make the zombies destroy any prop. So i hope you will be able to make the zombies : destroy any prop in few hits, climb walls, a bit faster and stronger. Thats all if you take my request i will be forever in your debt. Thank you and good luck!

**Comment by Kefta** [comment]
This is mod territory, zombies behave exactly as they do in HL2.
