### ISSUE TITLE
lua/bin/ folder for legacy addons on dedicated servers

### ISSUE THREAD

**Issue by viral32111** [Facepunch/garrysmod-requests#1672]
As the title says, allow only **legacy addons** on only **dedicated servers** to have C++ modules in their `addon-name/lua/bin/` folder. I know everyone's going to argue about how this is a security issue, but most of the time legacy addons on dedicated servers specifically are installed by people who know what they're doing.

It's not hard to put the module in the `garrysmod/lua/bin/` folder, but it would keep addons neater if the module could just go inside the addon folder. It's sometimes quite hard to keep track of which module was required by what addon when there's like 15 different modules in the `garrysmod/lua/bin/` folder. It's also really inefficient to make a symlink to that folder for all legacy addons that have a `lua/bin/` folder.
 
This has probably been asked before, but I couldn't find any existing requests from a quick search.

**Comment by GitSparTV** [comment]
I think it's disabled to make sure the owner understands the addon want you to install external modules which can do anything with the machine

**Comment by viral32111** [comment]
I know they can do anything to the host machine, which is why it's a security issue, but just having it enabled for legacy addons on servers only would eliminate a massive porition of the security issue.

At the very least, can we please have some sort of toggleable option (maybe a srcds startup argument? `-allowaddonmodules`?) that enables it, just for ease of life for those developers who make c++ modules and/or use them quite often.

**Comment by thegrb93** [comment]
This is a security issue. "Add an option" no

**Comment by thegrb93** [comment]
If you really want, ship a script with your addon that softlinks the binaries. Otherwise, no.

**Comment by viral32111** [comment]
> This is a security issue. "Add an option" no

Having an command-line option argument has the same level of security as dropping a file into a different folder, both don't prevent malicious modules, they just add an extra step to enable the modules.

**Comment by xaviergmail** [comment]
One of the primary appeals of having a single path where binaries are loaded from is avoiding conflicts.

For example if everyone on gmodstore started to ship their own binaries of MySQLOO, a plethora of issues could arise such as outdated versions, mismatched architectures, abi incompatibilities.

Furthermore this wouldn't solve the issue of modules which require certain shared libraries to either be present on the system or alongside the srcds binary.


The current implementation is more than satisfactory. The main attraction I can see to this would be to simplify deployments, but if you're automating deployments to begin with, I don't see why you wouldn't go the extra step to either maintain a "binaries" repository modify your script to move files in the required directory.

**Comment by viral32111** [comment]
Eh fair enough, completely forgot about conflicts when originally posting.
