### ISSUE TITLE
Add flags argument to Entity.EmitSound

### ISSUE THREAD

**Issue by Kinyom** [Facepunch/garrysmod-requests#1674]
Currently, Entity.EmitSound doesn't have an argument for SND_ flags, which the standard EmitSound does. Strangely, the wiki says that Entity.EmitSound *does* have this argument, but it doesn't (and I've tested by tacking on the desired flags as a last argument). Can this be added? It'd be very useful.

**Comment by robotboy655** [comment]
Added new argument to Entity.EmitSound - flags, and fixed type checking for the other optional arguments, including pitch and volume arguments not working if soundlevel argument is not given.

Do not expect this to make it into the next update on 19th. It will likely be delayed for the update after 19th.
