### ISSUE TITLE
Add a variable to use NextBotTraversableTraceFilter for pathing

### ISSUE THREAD

**Issue by tobiasx** [Facepunch/garrysmod-requests#1677]
Nextbots, for the most part, are pretty bad at traversing maps that have entities on it, especially custom created entities.

It would be nice to have NextBotTraversableTraceFilter to be an option for path creation, so we don't have to make them just walk through entities by setting their collision group.

Its already implemented in the game, its just a matter of giving an option to toggle them on, and maybe a bit of editing.

**Comment by robotboy655** [comment]
It is already being used.
