### ISSUE TITLE
CSound binding

### ISSUE THREAD

**Issue by DBotThePony** [Facepunch/garrysmod-requests#1680]
Primarily for creating sounds with flags, such as `SOUND_DANGER` and other manipulations.

Also this will allow mod makers to make their NPCs react to dangerous conditions defined by source engine, and allow other mods to define dangerous conditions by themselves.

**Comment by robotboy655** [comment]
Added sound.EmitHint( SOUND_ enum, position, volume, duration, owner = NULL )
Added SOUND_ enums for the function above

Gonna document in a while if there's no criticisms.
