### ISSUE TITLE
Nextbot shadows uncontrollable

### ISSUE THREAD

**Issue by Jova1106** [Facepunch/garrysmod-requests#1684]
https://github.com/Facepunch/garrysmod-requests/issues/918

As this post from 2017 states, things such as nextbot shadows are apparently uncontrollable. They are force drawn no matter what. They can't be set to not draw, and they can't be removed via destroyshadow (they will flicker endlessly with this method).

Why? I don't want to draw shadows for my nextbots.

**Comment by GitSparTV** [comment]
Duplicate of #918

**Comment by Jova1106** [comment]
> 
> 
> Duplicate of #918

If you're going to move something to another section, you should note in your comment that you moved it to avoid confusion. This is hardly a duplicate. I referenced the 3 year old post. 

This is an issue, not a request. I think it belonged in the place where I put it initially. I don't understand how this could be seen as anything else. I SHOULD be able to control nextbot shadows, but I am unable to. This is a blatant **issue** with the way nextbots are designed currently. I'm not requesting a feature that isn't here, I'm pointing out that there is an issue with the functionality of the current nextbot mechanics. I am not really requesting for anything, other than the issue to be fixed.

**Comment by Jvs34** [comment]
There's a little bit of confusion here I feel, the linked issue is about physics shadows (which is what source uses to make npcs and players push props and be affected by physics damage) while you're actually talking about shadows rendering (as noted by the fact that you're mention ENT:DestroyShadow())

Also this IS the requests repository, [the issues one is over here](https://github.com/Facepunch/garrysmod-issues/issues).

**Comment by Jova1106** [comment]
Ah, this was my confusion. I was linked a post that was here, but I've never been here so I assumed it was in the other repository. It should've never been here to begin with, that might be why it was never resolved. I could've sworn I posted it in the other place, so I came back and thought it had been moved. Apologies.
