### ISSUE TITLE
Add voice_maxgain to Garrys Mod settings or allow Lua editing

### ISSUE THREAD

**Issue by Benn20002** [Facepunch/garrysmod-requests#1691]
voice_maxgain should be a setting in Garrys Mods settings or allowed to be edited by Lua.
Many players don't know about the command and therefore keep complaining about too low voicechat volume which then results in staff having to explain each individual how to increase the voice volume.

If its in the Garrys Mod settings most players would find it by themselves or it at least would be very easy to explain them how to change it.
If its changeable by Lua we just could make ingame settings menus.

I know there is a reason why its not higher by default, but I dont see a point why its not changeable except with console commands.

**Comment by robotboy655** [comment]
I have looked into it, and the volume cannot be separated properly from `volume` convar. What we could do is either switch voice to use BASS.DLL in which case we could probably separate it, or give you a permanent "overdrive" setting, that works not just when someone talks, but all the time.

You can preview what overdrive does with these:
"voice_overdrive" 0-256 where 256 means other sounds are silent
"voice_overdrivefadetime" = "0.4"

**Comment by robotboy655** [comment]
Also try setting `voice_fadeouttime` to 0, I just noticed it makes voice chat quieter.

**Comment by robotboy655** [comment]
Added `volume_sfx` console variable - Adjusts the volume of sound effects & NPC voices, but does not affect player voice chat or music, both of which have their own console variables.

Currently it doesn't affect the ear ringing noise, I am not sure why/where that sound is generated.
