### ISSUE TITLE
Add support for gamedata-based resource mounting to hammer

### ISSUE THREAD

**Issue by stepa2** [Facepunch/garrysmod-requests#1694]
Add some way to choose whether to load resources using mount.cfg or gameinfo.txt (checkbox in Game Configurations probably)
This would allow to edit other source games' VMFs with updated version of Hammer

**Comment by robotboy655** [comment]
You already have mount.cfg which does exactly what you need?

**Comment by viral32111** [comment]
I think they meant for an options dialog to be added to toggle mounting of each game?
Although that can easily be done by just adding/removing entries in mount.cfg.

**Comment by stepa2** [comment]
I want to edit Source 2013 levels with garry's mod Hammer

**Comment by robotboy655** [comment]
And what is stopping you?
