### ISSUE TITLE
Expose $surfaceprop to Lua

### ISSUE THREAD

**Issue by Cordon** [Facepunch/garrysmod-requests#1697]
A way to change the $surfaceprop on an entity would be cool. Would allow me to rewrite this tool to not use a hacky footstep sound method:
https://steamcommunity.com/sharedfiles/filedetails/?id=1915099464

**Comment by robotboy655** [comment]
You already have this. https://wiki.facepunch.com/gmod/PhysObj:SetMaterial

What you want is this being fixed: https://github.com/Facepunch/garrysmod-issues/issues/1089
