### ISSUE TITLE
Entity:EmitSound DSP argument

### ISSUE THREAD

**Issue by DBotThePony** [Facepunch/garrysmod-requests#1702]
To remove hack related to hooking onto `EntityEmitSound` before doing `EmitSound` and setting `EmitSoundInfo.DSP` to new value.

Also would love to see `DSP` parameter in `SoundData`

Like this
![browser_pE5vEIZw4S](https://user-images.githubusercontent.com/6339511/93015400-5f17d480-f5e3-11ea-9e32-ef0a54bf0b21.png)

**Comment by robotboy655** [comment]
DSP is not a thing for sound scripts.

Added DSP argument to entity.EmitSound and EmitSound global

**Comment by DBotThePony** [comment]
Thanks
