### ISSUE TITLE
A srv hook to deny ConCommands

### ISSUE THREAD

**Issue by Earu** [Facepunch/garrysmod-requests#1710]
Everything in the title, a server hook to deny ConCommands being executed on the server.

See: https://github.com/Heyter/gbins/tree/master/slog/src

**Comment by robotboy655** [comment]
Related requests:
https://github.com/Facepunch/garrysmod-requests/issues/1038
https://github.com/Facepunch/garrysmod-requests/issues/1501
https://github.com/Facepunch/garrysmod-requests/issues/1135

**Comment by Earu** [comment]
Example of usage: https://github.com/Earu/EasyChat/blob/master/lua/easychat/engine_chat_hack.lua#L16
