### ISSUE TITLE
Add CTakeDamageInfo:SetBaseDamage(float)

### ISSUE THREAD

**Issue by LeQuackers** [Facepunch/garrysmod-requests#1711]
Having a setter for CTakeDamageInfo.m_flBaseDamage would be nice.

https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/shared/takedamageinfo.h#L123

**Comment by robotboy655** [comment]
Added

**Comment by Kefta** [comment]
There was no reason to add this, base damage isn't supposed to be directly manipulated.

**Comment by robotboy655** [comment]
We can always remove it, it isn't shipped in an update yet.

**Comment by thegrb93** [comment]
This allows modding hl2 weapons' damage before being scaled right?

**Comment by Kefta** [comment]
Skill level scaling takes place after the base damage is modified so that the regular damage value can be modified. ``CopyDamageToBaseDamage`` is how this takes place, but I suppose that setting the base damage directly is more flexible, weird Valve design decisions.
