### ISSUE TITLE
Would be quite useful to have a way of saving an IMaterial to a file in the data folder?

### ISSUE THREAD

**Issue by VaasKahnGrim** [Facepunch/garrysmod-requests#1720]
Basically we have the option to save files of type vtf, vmt, png and jpg, we also have the option to create an IMaterial object out of anything we want(png files, draw/surface library, online APIs and so on)

But from what I can tell there doesn't seem to be a function that would get an IMaterial object in a way to save it to a file so that it can then be used as a png/vtf file. I also didn't really see any previous requests like it either.

While I can create materials in lua just fine, I'd like to be able to save what I've made to a file for use elsewhere besides ingame

**Comment by robotboy655** [comment]
You can `file.Write` `.vmt` perfectly fine.

**Comment by VaasKahnGrim** [comment]
Yes, I'm aware of that, however theres no way to get the data for the material to put into the file itself.

**Comment by CornerPin** [comment]
There is a method that returns all the material parameters: [IMaterial:GetKeyValues](https://wiki.facepunch.com/gmod/IMaterial:GetKeyValues).

**Comment by GitSparTV** [comment]
Which returns all keys even untouched ones

**Comment by VaasKahnGrim** [comment]
Thats half of it solved I guess. theres still the issue of cached textures tho. How would we save that to a vtf file?

**Comment by robotboy655** [comment]
This is basically already solved,

Feel free to create an issue that addresses this
>Which returns all keys even untouched ones

for the function IMaterial:GetKeyValues, or for a way to save `ITexture` to disk.
