### ISSUE TITLE
Bodygroups/skins tool for bonemerged entities

### ISSUE THREAD

**Issue by Kuma96** [Facepunch/garrysmod-requests#1725]
Since the engine limits the maximum number of materials per model to 32, if I want to make a model with a higher material count, I compile 2 (or more) different models, one of them being the main model, and the rest of them (ClientsideModels) being bonemerged to it. The "child" models do not add new bones, as they use the same skeleton as the main entity, but they have their own bodygroups and/or skins.
I suggest that the bodygroyp tool checks wether there are other entities attached to the selected entity, so their bodygroups are shown by the tool.

**Comment by robotboy655** [comment]
There will not be any adjustments of default tools/features to take into account specific addons. Addons can modify the default behavior of the game to suit their needs, i.e. hide the default Bodygroup/skin properties and create a custom one ( or simply override the default one) with the desired functionality.
