### ISSUE TITLE
Suppress/Remove Unhandled animation event messages

### ISSUE THREAD

**Issue by TankNut** [Facepunch/garrysmod-requests#1727]
```
Unhandled animation event AE_NPC_BODYDROP_HEAVY for <entity> (x12)
Unhandled animation event AE_NPC_ITEM_PICKUP for <entity>
Unhandled animation event AE_NPC_BODYDROP_HEAVY for <entity>

Unhandled animation event 1003 for <entity>
Unhandled animation event AE_HUNTER_FOOTSTEP_BACK for <entity>
Unhandled animation event AE_HUNTER_FOOTSTEP_RIGHT for <entity>
Unhandled animation event AE_HUNTER_FOOTSTEP_LEFT for <entity>

Unhandled animation event AE_HUNTER_MELEE_ANNOUNCE for <entity>
Unhandled animation event AE_HUNTER_START_EXPRESSION for <entity>
Unhandled animation event AE_HUNTER_MELEE_ATTACK_LEFT for <entity> (x2)
Unhandled animation event AE_HUNTER_END_EXPRESSION for <entity>
```

These messages show up regularly when using `developer 1` and working with entities that use any kind of npc model/animations, you can filter them out sure but they don't really serve any purpose seeing as they

1. Don't indicate an actual problem (It doesn't cause any issues)
2. Can't be 'fixed'
3. And can get _really_ spammy with some examples printing 5 messages within the span of a single animation

If removing them outright isn't happening then could we maybe just suppress them by returning true in ENT:HandleAnimEvent()?

**Comment by robotboy655** [comment]
ENT:HandleAnimEvent can now return true to suppress the default action
