### ISSUE TITLE
Move vgui.CreateX error to ErrorNoHalt

### ISSUE THREAD

**Issue by GitSparTV** [Facepunch/garrysmod-requests#1729]
C function `vgui.CreateX` when a unknown element is called shows a white warning, my suggestion to move this error to ErrorNoHalt.
If someone is creating vgui too early it will clearly say this. The error can also specify a common reason why it fails.

I'm speaking about `Warning: vgui.Create failed to create the VGUI component (ClassName)`

**Comment by robotboy655** [comment]
Done.
