### ISSUE TITLE
repurposing the vscript keyvalues for map entities

### ISSUE THREAD

**Issue by VaasKahnGrim** [Facepunch/garrysmod-requests#1730]
While I know that we will never be getting support for vscripts and that vscripts themselves are basically worthless to garry's mod anyways because lua is FAR FAR more capable of things that vscripts isn't capable of, I feel that it would be useful to have the vscript parameters for various entities repurposed for mapping.

For example rather than trying to use a vscript, having the option for the entity to call a lua function or utilize a lua file instead would be quite useful. So lets say we were to create a prop_dynamic entity with a lua script on it. That lua script could have a ent referance to that specific prop_dynamic passed to it, we could then setup a ENT:Function() for that specific prop. such as say applying a specific animation to it under specific circumstance. or changing other keyvalues of it based on said circumstances.

While we can technically do this already without the vscript keyvalue, I think being able to use the keyvalue for it would make things alot easier, people could basically avoid having to give every single entity a name for easy referancing it in scripts. Aswell some entities also behave very difficult when they are nammed so this could be used as a way to get around that issue aswell

**Comment by robotboy655** [comment]
>That lua script could have a ent referance to that specific prop_dynamic passed to it

And how do you think that would work exactly?

> While we can technically do this already without the vscript keyvalue,

Yeah, so this request is entirely pointless?

> Aswell some entities also behave very difficult when they are nammed so this could be used as a way to get around that issue aswell

What are you even talking about?

**Comment by VaasKahnGrim** [comment]
1. I'd imagine similar to how lua entities work already with ENT. not magically being a nil value. that or pushing the value when the file is loaded. If not that, thats why I mentioned calling a lua function as an alternative to loading a file.

2. Not entirely pointless, it would make people's lives alot easier when tieing things to specific entities. Less work involved with having to get a referance to the entity itself considering that said entity would be calling the function. Basically no need to perform stuff like ents.FindByName/ents.FindByClass and then performing other checks. It would be much more clean and simple to have the entity able to do it on its own.

3. certain entites when given a name behave differantly or in somecases have more of an impact on performance. there are a good few examples on the valve wiki btw. one that notably has a vscript option aswell as the performance issue is infodecal(https://developer.valvesoftware.com/wiki/Infodecal). When nammed, this entity gets put into the entity lump, aswell becomes more expensive to exist. another entity with similar issues when nammed are light entities(https://developer.valvesoftware.com/wiki/Light) their behavior when nammed changes aswell as stated. I can imagine some people would not want those behavior changes when building a map so naming these entities could cause issues for make makers who utilize lua. aswell naming entities also bloats lmp_0's size, being able to avoid that would be a massive benefit aswell

**Comment by robotboy655** [comment]
1 and 2. ENT is just a table that then gets merged onto an entity instance, it's not an actual entity instance itself. There is no magic here, and there can't be magic for your magical "the lua file somehow now has a reference to the entity". Having a callback/global variable function is more dirty than calling `ents.FindByName`
3. You do realize that without those different behaviors the "entities" will not be able to change, right? i.e. if you do not name a light, you will not be able to turn it on and off, not with Lua, not with Hammer IO, not with C++, not with a quantum computer. Same goes for infodecal. This request will not be able to help with that, nothing will be able to help with that.

**Comment by VaasKahnGrim** [comment]
in that case then why even leave the vscript stuff in if its not going to even be usable. its just bloating the entity lump size. I just figured making it actually usable to us would be a good idea for mappers. also the light sure.

I will say I dissagree with you on the ents.FindByName() tho. It just seems insanely more messy than it needs to be to referance specific entites. because if you are building a map that utilizes lua your not going to be just referancing one or two entities via lua, chances are you'll have alot more all with their own unique name and intended actions to be done with them. having the hammer entity itself being able to load a file or run a lua function directly however seems the most clean way of doing it. Which I'd imagine is why valve came up with the whole idea of using a vscript as a perameter with the entities in the first place. Logically having the entities do it directly seems the best option when looking at effort involved to do things with the map.

**Comment by VaasKahnGrim** [comment]
I should also mention some other entities where it would be most usefull, mainly func_door, prop_dynamic, func_button and so on to name a few.

**Comment by robotboy655** [comment]
Logically speaking yeah it makes sense, but I don't think this would see much use, compared to what is already possible and is being done. Most mapping related discussion I see is about how they don't want to touch Lua. 
You can pretty much already do this with custom entities anyway. And there's also the `lua_run` entity. 

Also I am really not sure what do you mean by `in that case then why even leave the vscript stuff in`. Garry's Mod never had any parts of vscript, be that in the fgd or otherwise, unless you are using custom tools/.fgd, which is not part of Garry's Mod and therefore isn't my concern. We are based off of the Team Fortress 2 SE branch.

Also the `entity lump bloat" is really not a concern, its a fraction of a fraction of the filesize of a map. It's mostly textures, PAK-ed assets and the baked lighting that's contributes to vast majority of it, and that just comes down to the skill of the mapper/modeller to optimize for the engine, which you must do whether you like it or not. We are not Unreal 5 here, if that ever lives up to its promises.

**Comment by VaasKahnGrim** [comment]
Alot of mappers I've seen mainly don't use lua simply because they don't know how to deal with code in the first place. But would this not give them a much easier and simple means of getting started with it? I know of a few who have talked about using lua in their maps but they typically don't know where to start.

as for the entity lump, yea its not much but its still unused. No real reason to be there if its not used. But I felt it would be more useful to have them actually do something rather than nothing. But if its not going to be changed, oh well. I tried

**Comment by Kefta** [comment]
Your vscript solution still requires the mapper to have Lua knowledge, especially around what will be scantly documented system from it being so new. If they are wondering how to target specific entities by name, they can always ask in the GMod Discord.
