### ISSUE TITLE
Enable/Disable Props Spawning Partially In Walls

### ISSUE THREAD

**Issue by ThinkingParadox** [Facepunch/garrysmod-requests#1731]
Hello,
After the recent update, I noticed that Prop Hunt servers are having issues with prop's hitboxes pushing them out of walls although the props themselves are not in the wall itself. I realized that there was a portion added that blocks props from spawning partially in walls. 
Is there a possibility that there could be a CVAR or setting added to allow servers to disable the new fix from being applied on servers that decide they want to keep this?

**Comment by robotboy655** [comment]
It should be fixed if you update your server(s).
