### ISSUE TITLE
ModelImage more functions

### ISSUE THREAD

**Issue by DEXTER251** [Facepunch/garrysmod-requests#1732]
Need to add function at ModelImage to check if icon is error

**Comment by WilliamVenner** [comment]
Couldn't you just use https://wiki.facepunch.com/gmod/util.IsValidModel ?

**Comment by DEXTER251** [comment]
i cant, cause if model is valid - icon is already generated as error and how to check this

**Comment by robotboy655** [comment]
Error icons are not saved on disk.

**Comment by DEXTER251** [comment]
![image](https://user-images.githubusercontent.com/64154463/96177361-732e5900-0f36-11eb-8f93-30d8c2a9f2d4.png)
I dont think so

**Comment by robotboy655** [comment]
See the creation date on that file, or try to delete it and see if gets recreated.

**Comment by DEXTER251** [comment]
![image](https://user-images.githubusercontent.com/64154463/96337881-e2b95b00-1092-11eb-9c67-c76aa20dc7af.png)
still creating

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/96471423-ff42c800-1237-11eb-827e-bf0f4f4f95eb.png)

It really doesn't unless you are manually re-rendering the icon

**Comment by DEXTER251** [comment]
> It really doesn't unless you are manually re-rendering the icon with Lua or the Icon Editor.
Im creating custom panel which use ModelImage and need to check if icon is error (if he generated error model before and try to re-render this icon automatycally).

**Comment by robotboy655** [comment]
The game already handles all of that for you?

**Comment by robotboy655** [comment]
There's not really a way to distinguish if the icon on disk is an error image or not anyway.

I have made sure manual renders also do not save pictures of ERROR to disk.
The error model itself can still be re-rendered as normal of course.
