### ISSUE TITLE
bring back the colors in the `find` concommand result

### ISSUE THREAD

**Issue by 2048khz-gachi-rmx** [Facepunch/garrysmod-requests#1733]
### Details
On x86-64 as of 14.10.2020 the `find` concommand results clientside look like this:
![gmod_dm0Nf9bXIL](https://user-images.githubusercontent.com/44749188/96155923-affc4f00-0f3a-11eb-929c-4b4fdf141d77.png)

and they used to look like this:
![image](https://user-images.githubusercontent.com/44749188/96155968-bd193e00-0f3a-11eb-97dd-94aa147124a3.png)

pls return

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/96158470-3a818600-0f1c-11eb-8716-3e9a87c066ae.png)
