### ISSUE TITLE
Add "Vscript" hook

### ISSUE THREAD

**Issue by Jaffies** [Facepunch/garrysmod-requests#1735]
Since we arleady know - gmod doesn't have vscript support, instead of it, gmod uses a more powerfull tool, called Lua (Actually it's a programming language)
So my idea is to implement a Vscript hook, which would be look like that
```
hook.Add("Vscript", "VscriptRestoreHealth", function(object, code)
    if string.find(code, "SetHealth(100)") then
          object:SetHealth(100)
    end
end)
```
So what is object and code?
Object - is the object, where vscript was called.
Code - is the vscript code, formatted in string, like "for k, v in pairs(entity.GetAll()) do v:Remove end "
This will allow us to do custom vscript interpretators by ourself and will allow to use vscript logic in gmod (with custom coded lua interpretator)

**Comment by CornerPin** [comment]
Just use Lua.

**Comment by robotboy655** [comment]
You can already do all of this.

Here's an example custom entity that display path to it's vscript:
```
[KeyValue] logic_script #32: origin - -2928 4656 -7.62939e-006
[KeyValue] logic_script #32: vscripts - br/br_trainride.nut
[KeyValue] logic_script #32: thinkfunction - BRThink
[KeyValue] logic_script #32: targetname - @script_br_trainride
[KeyValue] logic_script #32: classname - logic_script
[KeyValue] logic_script #32: hammerid - 326
```

Input of running code
```
[Input] logic_script #32: RunScriptCode - PlayShakeRattleSound() (Entity [0][logic_timer], Entity [0][logic_timer])
[Input] logic_script #32: RunScriptCode - PlayShakeRattleSound() (Entity [0][logic_timer], Entity [0][logic_timer])
[Input] logic_script #32: RunScriptCode - PlayShakeRattleSound() (Entity [0][logic_timer], Entity [0][logic_timer])
```

It won't work for non existing entities, but the hooks AcceptInput and EntityKeyValue can also capture these:
```
NPC [106][generic_actor]	vscripts	choreo/glados_coop.nut
```
Even if the built-in entities do not store or use these keyvalues/inputs.
