### ISSUE TITLE
Add ".texturename", ".textureU", ".textureV" to TraceLine.

### ISSUE THREAD

**Issue by Jaffies** [Facepunch/garrysmod-requests#1736]
I'f we wanted to do the camera, based on traces, we won't be able to know the texture, and it's UV coordinates on traced model/brush.

**Comment by thegrb93** [comment]
Would need to be a new function rather than util.TraceLine. You could technically already do this using the model mesh data.

**Comment by gonzalologorg** [comment]
The problem is that the rendered element it's usually not the same than the collision mesh that receives the trace, although maybe source works different and they solved it somehow

**Comment by Kefta** [comment]
@gonzalologorg is correct, the visual mesh and physical mesh have no relation to each other.

**Comment by thegrb93** [comment]
That's why I mentioned it would need to be a new function.
