### ISSUE TITLE
Less limited ProjectedTexture

### ISSUE THREAD

**Issue by VladUndying** [Facepunch/garrysmod-requests#1737]
### Details
Normally, "class C_EnvProjectedTexture" is very flexible, but ProjectedTexture isn't. You can pretty much do anything you want with C_EnvProjectedTexture because it's an entity and on the other hand ProjectedTexture doesn't even have SetParent, Think function, any way of finding it if the object was lost.
Please, at least allow Entity functions for "ProjectedTexture", you can't edit KeyValues on the client (because they're less prioritized than the server, but the server automatically fills them) making it absolutely impossible to have flexible ProjectedTexture (You can't spawn it as Entity on the client).
**Also, DynamicLight sucks**

**Comment by robotboy655** [comment]
ProjectedTexture is not an entity, as such it having all the entity functionality will not be possible.
