### ISSUE TITLE
Make DTextEntry options (autocomplete system) working with mouse clicks.

### ISSUE THREAD

**Issue by FlorianLeChat** [Facepunch/garrysmod-requests#1738]
### Details

I recently learned that an autocomplete system was available with **DTextEntry**, when I tried to use it I realized that it was impossible to control this with the mouse (I thought there was a bug with Gmod). Without consulting the wiki, it's not possible to know how this menu should be controlled with the arrow keys.

The usage of this menu is really **not intuitive** and it's a real "shame" because it could be really useful for a lot of people who want to start creating custom menus using features already exist in the game.
And for those who want to workaround this issue by recreating this system (or find another way), **it can be difficult** for new modders.

For those who want to test, here is a code snippet you can use (below). **Please note that it's possible to select with the mouse the last option but not the first three...**

**Screenshot**:

![image](https://user-images.githubusercontent.com/26360935/96903979-ce140300-1496-11eb-911f-b78321b6c6ad.png)

**Test code**:

```lua
-- Copy/paste from : https://wiki.facepunch.com/gmod/DFrame
local DFrame = vgui.Create( "DFrame" ) -- The name of the panel we don't have to parent it
DFrame:SetPos(100, 100)                -- Set the position to 100x by 100y
DFrame:SetSize(300, 200)               -- Set the size to 300x by 200y
DFrame:SetTitle("Derma Frame")         -- Set the title in the top left to 'Derma Frame'
DFrame:MakePopup()                     -- Makes your mouse be able to move around

-- Copy/paste from : https://wiki.facepunch.com/gmod/DTextEntry
local DTextEntry = vgui.Create("DTextEntry", DFrame)
DTextEntry:SetValue("Bye")
DTextEntry:SetPos(120, 30)
DTextEntry:SetSize(100, 100)

DTextEntry.GetAutoComplete = function(text)

    -- Override...
    -- https://github.com/Facepunch/garrysmod/blob/da4cde037c9ee541ce2ebdc24cc1f1f56a79f0cf/garrysmod/lua/vgui/dtextentry.lua#L367-L369
    return {"test1", "test2", "test3", "test4"}

end
```

**Comment by robotboy655** [comment]
Should be fixed. For the future, you should report bugs in this repository:
https://github.com/Facepunch/garrysmod-issues

**Comment by FlorianLeChat** [comment]
Thank you very much Rubat! 👍 
Sorry for posting this here, I thought it was intentional and not a bug.
