### ISSUE TITLE
Add "ClientTakeDamage" hook.

### ISSUE THREAD

**Issue by Jaffies** [Facepunch/garrysmod-requests#1742]
It's impossible to know if LocalPlayer() has attacked (or taken damage).
Since we have "EntityTakeDamage" hook in server, then we need to have "ClientTakeDamage"
The following argument would be: Dmginfo.
So by hook.Add("ClientTakeDamage", "12313" function()
    print("The client was damaged!")
end)

**Comment by Jaffies** [comment]
GM:PlayerTraceAttack( Player ply, CTakeDamageInfo dmginfo, Vector dir, table trace ) - doesn't really work for clients and LocalPlayer().

**Comment by robotboy655** [comment]
Since damage is not shared, this is unfeasible. Send whatever you need on client from the server via net messages.

**Comment by Kefta** [comment]
Predicted damage events are on my todo list, but it won't be for a while and of course only apply to entities with SetPredictable enabled.
