### ISSUE TITLE
Add "ClosedCaption" hook.

### ISSUE THREAD

**Issue by Jaffies** [Facepunch/garrysmod-requests#1745]
This hook will ovveride the ClosedCaption thingy with 2 arguments, which are "string name", "color col" and one return, which is true or false. True basically allows to display cc, and false - to disable cc displaying.
So by `hook.Run("ClosedCaption", "Ok, so this is a Lua closed caption!", Color(0, 255, 100))` it'll call closed caption for one frame.
And of course, it must be ```
hook.Add("ClosedCaption", "MyHudCaptions" function(str, color, time)
    draw.SimpleText(str, "Arial", 250, 250, color) --Drawing our captions
    return false -- Disabling default captions
end)
``` which allows to display our own captions.

**Comment by FlorianLeChat** [comment]
This would be great. Also, it would also be useful to add a function to add new ones!

**Comment by robotboy655** [comment]
Added `OnCloseCaptionEmit` hook
Arguments are:
```
string soundScript
number duration
bool fromPlayer
string fullText - can be nil if token is not registered
```

**Comment by Kefta** [comment]
Any returns?

**Comment by Zaurzo** [comment]
> Any returns?

Just did a test, returning `true` blocks the caption from emitting.
