### ISSUE TITLE
Add Half-Life: Source Hand grenade, satchel, snarks, tripmine weapons to spawnable entities menu.

### ISSUE THREAD

**Issue by malortie** [Facepunch/garrysmod-requests#1747]
### Details

Given the following Half-Life: Source weapons:

- Hand grenade (weapon_handgrenade)
- Satchel (weapon_satchel)
- Snark (weapon_snark)
- Tripmine (weapon_tripmine)

Players can only get ammunition for those weapons by picking them up.

There is currently no way to spawn these weapons via the 'entities' menu, and equipping with them in 'weapons' menu does not give additional ammunition.

Without going too much into technical details, as this is a feature request, but these could be added using ADD_ITEM in [game_hl2.lua](https://github.com/Facepunch/garrysmod/blob/a091bd032b8ad09c335570e515277cf404043b42/garrysmod/lua/autorun/game_hl2.lua#L121).

**Comment by robotboy655** [comment]
Middle mouse click the weapon in spawnmenu, or right click > spawn with toolgun.
