### ISSUE TITLE
Texture Scaling

### ISSUE THREAD

**Issue by Advooser** [Facepunch/garrysmod-requests#1748]
the ability to scale textures would be incredibly nice for the material tool. there are some tools on the workshop that do it but they're evidently fairly niche as i've only heard about them after discussing this with other people, so i think for the sake of universally easier building it could make a good vanilla feature.

**Comment by robotboy655** [comment]
Texture scaling is dictated by the model's UV coordinates. There's no way of doing this properly/cleanly. Your mods are either creating a new material per entity or changing the existing material which would affect all entities using the same material.

And again, if it's already possible via a mod, there's not much point of adding it into base game. Modding is the entire point of the game.
