### ISSUE TITLE
Bind additional Awesomium functions

### ISSUE THREAD

**Issue by samuelmaddock** [Facepunch/garrysmod-requests#175]
There are a few Awesomium functions that aren't binded which I believe would be rather useful.

* [WebView](https://www.awesomium.com/docs/1_7_2/cpp_api/class_awesomium_1_1_web_view.html)
     * title
     * url
     * InjectMouse*
     * GoBack
     * GoForward
     * GoToHistoryOffset
     * Stop
     * Reload (specifically the `ignore_cache` parameter)

* [WebViewListener.Load.OnDocumentReady](https://www.awesomium.com/docs/1_7_2/cpp_api/class_awesomium_1_1_web_view_listener_1_1_load.html#aed2fe4f10d72079ecd1b0d3006cdb8c2)

It's also worth noting that there are a few HTML Panel events which never get called:
* Panel.OpeningURL
* Panel.FinishedURL
* Panel.PageTitleChanged
* Panel.ResourceLoaded
* Panel.StatusChanged

**Comment by xaviergmail** [comment]
I think it's time this gets looked into. Having Awesomium updated would be very beneficial for loading screens (I made one using HTML5 Canvas and it doesn't work, I was quite disappointed.) as well as new advancements in terms of UI. 

+support

**Comment by willox** [comment]
Added the Panel hooks I mentioned in #189 as well as the following methods:

```lua
Refresh( ignoreCache = false )
Stop()
GoBack()
GoForward()
GoToHistoryOffset()
```
