### ISSUE TITLE
Allow NW/NW2 functions to specify an integer key

### ISSUE THREAD

**Issue by LeQuackers** [Facepunch/garrysmod-requests#1756]
String keys are nice, but aren't always the best choice. Adding integer keys would provide more flexibility in how data types and structures, in particular arrays, are networked to clients.

Why don't you use DT variables?
There are only 32 indexes per type (minus strings), so if you wanted to associate each player to a single DTFloat the system would break if there where more than 32 players.

Why don't you send it as a DT/NWString char array?
Any change in the array would cause the whole thing to be networked.

Why don't you concatenate an integer to the end of your string key?
NW string keys fill the networkstring table, which is terrible because of how [congested the table already is](https://github.com/Facepunch/garrysmod-requests/issues/1741).
NW2 is better off because the networkvars table is only used for NW2 string keys as far as I can tell and has twice the capacity, but it's still not ideal.

Why don't you use net messages?
Net messages aren't predicted. Even if you align them with prediction they can still miss timing. Other issues include <strike>detecting when entities enter/leave a client's PVS/PAS server-side</strike> as well as detecting when the client needs a full update packet server-side.

**Comment by thegrb93** [comment]
You shouldn't be creating so many nwvars that you need all whole numbers as keys. The system HATES when its bloated with items. Use net library instead.

**Comment by Kefta** [comment]
You can always use net mags and store the data until it's proper to introduce it into the predicted tick/interp it.

**Comment by LeQuackers** [comment]
> You shouldn't be creating so many nwvars that you need all whole numbers as keys.

All whole numbers is quite an exaggeration. The required size would be less than or equal to the number of players on the server, so 64 max in most cases.

> The system HATES when its bloated with items.

100 NW2 vars appear just fine unless you change everything at once or cl_fullupdate. As for 100 NW1 vars I can't say because they don't appear in DTI.

> Use net library instead.

I appreciate the advice, I'll probably experiment with net messages for the time being. if #204 and #718 where closed I'd probably close this as well.

> You can always use net mags and store the data until it's proper to introduce it into the predicted tick/interp it.

Same thing as above; I'll mess with it in the mean time.

**Comment by LeQuackers** [comment]
There's an OnRequestFullUpdate game event now now so there's no need to keep this open.
