### ISSUE TITLE
Add Support for Binary 4 PCF 2

### ISSUE THREAD

**Issue by Caskoo** [Facepunch/garrysmod-requests#1757]
Im requesting this because the garrys mod only supports PCF Binary 2 PCF 1, L4D2 particles use Binary 4 PCF 2. 

Why am I requesting this? 

Binary 4 PCF 2 has features not available in the current supported version, and by supporting it you offer mappers to use particles from L4D2 without having to convert it and then to find out it won't work because a function isn't supported.

https://imgur.com/vCK0Stg

I hope this isn't too difficult to implement. It would be much appreciated.

[where Cull relative to Ray Trace Environment is found](https://github.com/perilouswithadollarsign/cstrike15_src/blob/f82112a2388b841d72cb62ca48ab1846dfcc11c8/particles/builtin_initializers.cpp)

**Comment by Kidnation** [comment]
If this gets supported, another request should be for func_precipitation's particle based options to be added, along with the addition of func_precipitation_blocker too.

**Comment by robotboy655** [comment]
Added support for loading DMX versions 3, 4 and 5.

I don't know what the difference is between `PCF 1` and `PCF 2`.

**Comment by robotboy655** [comment]
Update: I now know what the difference is between PCF 1 and PCF 2.

For anyone wondering, the only difference are some renamed particle operator names: (`PCF1` => `PCF2`)

The game already handles these renames when loading the PCF files, so realistically there's no difference.
