### ISSUE TITLE
Improve SourceScheme.res Appearance

### ISSUE THREAD

**Issue by WinterPhoenix** [Facepunch/garrysmod-requests#1758]
### Details
Let's be honest, black on white isn't the pinnacle of UI design. On the old Facepunch Forums, somebody from pixelTail Games posted a custom SourceScheme.res that, in my opinion, looks much better than the default.

For years I've been using it, and now I think is the time to save the rest of the GMod population from the tyranny of `"255 255 255 255"`.

### Before
![image](https://user-images.githubusercontent.com/2799393/100526518-89674000-3197-11eb-80de-dcfb879236aa.png)
![image](https://user-images.githubusercontent.com/2799393/100526531-a8fe6880-3197-11eb-953a-151c97f5654a.png)
![image](https://user-images.githubusercontent.com/2799393/100526541-b4519400-3197-11eb-9792-e8658397cada.png)
![image](https://user-images.githubusercontent.com/2799393/100526551-cdf2db80-3197-11eb-94c2-23046e22ea4d.png)

### After
![image](https://user-images.githubusercontent.com/2799393/100526562-e9f67d00-3197-11eb-8088-bcfa520122d0.png)
![image](https://user-images.githubusercontent.com/2799393/100526569-f549a880-3197-11eb-8847-63f986c57fbf.png)
![image](https://user-images.githubusercontent.com/2799393/100526571-fbd82000-3197-11eb-9586-568033af40d1.png)
![image](https://user-images.githubusercontent.com/2799393/100526573-07c3e200-3198-11eb-9687-a02dd937c30b.png)

### The Replacement File
[SourceScheme.zip](https://github.com/Facepunch/garrysmod-requests/files/5611262/SourceScheme.zip)

**Comment by WilliamVenner** [comment]
This is nice, the blue tint goes well with Gmod's blue.

**Comment by FlorianLeChat** [comment]
You saved my eyes. 👍

**Comment by robotboy655** [comment]
The point of the current colors is to resemble Derma colors. Furthermore I cannot simply throw in that file you attached since neither I nor you made it.

You don't like server browser colors? Propose better ones. https://github.com/Facepunch/garrysmod/blob/master/garrysmod/resource/SourceScheme.res

I am not interested in changing the entire scheme.

**Comment by WilliamVenner** [comment]
@WinterPhoenix Can you put this on GitHub? We could add to it.
