### ISSUE TITLE
Outfitter Playermodels Wiped after Joining and Reboot

### ISSUE THREAD

**Issue by immortalslime53** [Facepunch/garrysmod-requests#1759]
I noticed this last week and was trying to figure out why all of my outfits wiped after a rejoin of a server with outfitter.

Help!

- Immortal Slime

**Comment by robotboy655** [comment]
This is not a place to get help, especially with addons. You can get help either on our official Discord server (https://discord.gg/gmod), or contact the addon author.

**Comment by immortalslime53** [comment]
Understandable. hope you have a good day.
