### ISSUE TITLE
Add bind for CMatRenderContextBase::ComputePixelDiameterOfSphere

### ISSUE THREAD

**Issue by WinterPhoenix** [Facepunch/garrysmod-requests#1760]
### Details
I'm attempting to recreate `CStaticPropMgr::ComputeScreenFade` in Lua, to have the effect present on *all* entities, not just `prop_static`, but I'm hitting a roadblock.

Many of the pieces needed to recreate `CMatRenderContextBase::ComputePixelDiameterOfSphere` aren't exposed to Lua, but since it's easier to just request a single bind instead of all of the pieces needed to recreate it, this is as much as I'm asking for.

### SE2007 code that might be helpful for finding it
`CStaticPropMgr::ComputeScreenFade`
https://github.com/VSES/SourceEngine2007/blob/master/se2007/engine/staticpropmgr.cpp#L1991

`CMatRenderContextBase::ComputePixelDiameterOfSphere`
 https://github.com/VSES/SourceEngine2007/blob/master/src_main/materialsystem/cmatrendercontext.cpp#L715

**Comment by robotboy655** [comment]
Looks like this will only give useful results under specific circumstances, i.e. in entity rendering hooks. You could quite easily recreate the number you seek with model bounds, Vector.ToScreen and some math(basically a get a square that covers the model), not sure which will be faster though.

Still want it?

**Comment by WinterPhoenix** [comment]
Probably... I have a close approximation recreated in Lua, but I think my math is off and there's some edge cases with `GetUp` on the view:

```lua
function ENTITY:GetSizeOnScreen(viewUpVec)
	viewUpVec = viewUpVec or GetViewEntity():GetUp() -- TODO: GetViewEntity():GetUp() isn't always correct? Maybe hook into CalcView instead?

	local worldSpaceCenter = self:WorldSpaceCenter()
	local boundRadius = self:BoundingRadius()

	local boundMax = worldSpaceCenter + (viewUpVec * boundRadius)

	local worldSpaceCenterScreen = worldSpaceCenter:ToScreen()
	local boundMaxScreen = boundMax:ToScreen()

	-- Radius of Sphere * 4 = Diameter of Sphere * 2 = Rough "box" for estimated size on screen
	return math.abs(boundMaxScreen.y - worldSpaceCenterScreen.y) * 4
end

-- WARN: This is intense, but grants us enough of a performance benefit that it's worth it
local sgsDrawScreenSpaceConVar = GetConVar("sgs_draw_screenspace")
local function screenspaceRenderOverride(self)
	local minScreenSpaceSize = math.max(sgsDrawScreenSpaceConVar:GetInt(), 0)

	if minScreenSpaceSize == 0 or self:GetSizeOnScreen() >= minScreenSpaceSize then
		self:DrawModel()
	end
end

timer.Create("sgs_draw_screenspace.EngineDrawCulling", 5, 0, function()
	for _, ent in ipairs(ents.FindByClass("prop_*")) do
		ent.RenderOverride = screenspaceRenderOverride
	end
end)
```

Thoughts?

**Comment by WinterPhoenix** [comment]
Bumping this because I think it would be useful to have the real engine implementation here instead of some hacked together Lua version of it

**Comment by robotboy655** [comment]
```
hook.Add( "HUDPaint", "HUDPaint_DrawABox", function()

	local point = Vector(0,0, 0)
	
	cam.Start3D()
	local diameter = render.ComputePixelDiameterOfSphere( point, 10 ) 
	cam.End3D()

	local pos2D = point:ToScreen()	
	surface.DrawCircle( pos2D.x, pos2D.y, diameter / 2, Color( 255, 120, 0 ) )
end )
```

**Comment by WinterPhoenix** [comment]
thanks babe! ❤
