### ISSUE TITLE
fix weapon netvars for observers

### ISSUE THREAD

**Issue by homonovus** [Facepunch/garrysmod-requests#1764]
### Details
spectators can see engine defined netvars like DT_BaseCombatWeapon.m_iClip1 perfectly fine, but lua defined netvars only stay for a single tick before resetting

**Comment by robotboy655** [comment]
![GIF](https://user-images.githubusercontent.com/3299036/100913417-6eb80280-34da-11eb-96c5-8c16a1c59ffc.gif)

Cannot reproduce. Seems to work as intended?

```

function SWEP:DrawHUD()

	local i = 0
	for id, val in pairs( self:GetNetworkVars() ) do
		draw.SimpleText( id .. ": " .. val, "Default", 5, 50 + i * 20, color_white )
		i = i + 1
	end

end

```

**Comment by robotboy655** [comment]
Also wrong repo.
