### ISSUE TITLE
Make cam.IgnoreZ() return its previous value

### ISSUE THREAD

**Issue by WilliamVenner** [Facepunch/garrysmod-requests#1765]
### Details
It would be cool if `cam.IgnoreZ(m_bIgnoreZ)` returned its previous value or `cam.GetIgnoreZ()` was implemented.

This would allow you to finely control IgnoreZ-rendering in a tree-like fashion, like you can do with other render functions, e.g. 
`DisableClipping` and `render.EnableClipping`.

Here's my use case:

![image](https://user-images.githubusercontent.com/14863743/100917274-d405f680-34ce-11eb-80dd-8b3b2ef2f871.png)

In this example, I'm using `render.ModelMaterialOverride` to draw the keypad's model again using a material which produces the diagonal red lines effect you can see here.

I want this to be visible through walls, so I have to call `cam.IgnoreZ(true)`. The problem with this is that it also causes the 3D2D UI to draw whilst ignoring Z.

Here's what it should look like:

![image](https://user-images.githubusercontent.com/14863743/100918943-0d3f6600-34d1-11eb-929c-64a3156060b5.png)

Thanks :D

**Comment by robotboy655** [comment]
Unfortunately this really isn't possible with how it works internally. Essentially `cam.IgnoreZ` is a duplicate of `render.DepthRange` that sets values to `0, 0.01` and `0, 1` for `true` and `false` respectively, and we can't really convert them back to a bool from any arbitrary combinations of 2 floats that the engine may have those set to at any point.

I have documented this on the wiki as well.

There isn't a `render.GetDepthRange` in the engine, and I am not sure you should need it, you should be able to achieve whatever you need with simply setting `render.DepthRange`. Or simply doing `cam.IgnoreZ( false ) after you done your rendering, before drawing 3D2D. Or drawing your model after the 3D2D. I can't really say much more without having some minimal code to reproduce the issue you are having.

**Comment by WilliamVenner** [comment]
OK fair enough. I managed to work around this quite simply by making my own cam.IgnoreZ function where I store its previous value myself and just return that. It sounds like that wouldn't work in every case in a more generalized context.
