### ISSUE TITLE
Improve the func_tracktrain entity

### ISSUE THREAD

**Issue by VaasKahnGrim** [Facepunch/garrysmod-requests#1766]
Currently we have an "OnStart" output and "OnNextPoint" output for this entity, however "OnNextPoint" is improperly listed in the fdg as "OnNext" and despite its name it doesn't get used after reaching its destination, instead it is apparently fired each frame until reaching the next point in the track.

The improvements I was thinking were fixing the fdg output name for "OnNextPoint", and putting a note about the behavior in its description so as not to confuse mappers unfamiliar with the entity. Aswell adding an "OnStop" output for when the func_tracktrain has actually stopped moving.

Information regarding OnNextPoint found here: https://developer.valvesoftware.com/wiki/Func_tracktrain

**Comment by robotboy655** [comment]
Corrected the .fgd
