### ISSUE TITLE
Function to copy a PhysObj shape.

### ISSUE THREAD

**Issue by Ramalayha** [Facepunch/garrysmod-requests#1767]
I would like some way to copy the shape of a physobj after having run say :PhysicsInitConvex() and then being able to have another entity create its own physobj using that so you don't have to generate the shape again.

**Comment by robotboy655** [comment]
https://wiki.facepunch.com/gmod/PhysObj:GetMeshConvexes
https://wiki.facepunch.com/gmod/PhysObj:GetMesh

???

**Comment by Kefta** [comment]
There will also be PhysObj:Serialize() which will be able to efficiently recreate the physobj based on its exact props in a future update.

**Comment by Ramalayha** [comment]
Cool, that sounds just like what i want Kefta.
