### ISSUE TITLE
ITexture:GetStartingAnimationFrame()

### ISSUE THREAD

**Issue by WilliamVenner** [Facepunch/garrysmod-requests#1768]
### Details
Pretty sure you can just expose `CVTFTexture->m_iStartFrame`

**Comment by robotboy655** [comment]
function GetStartingAnimationFrame() return 0 end

??

**Comment by WilliamVenner** [comment]
No.

![image](https://user-images.githubusercontent.com/14863743/101428370-7c192680-38f8-11eb-9863-552f2282b3a5.png)

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/101428443-652f0000-3909-11eb-9854-fc07d5bce2cb.png)

**Comment by WilliamVenner** [comment]
They still implemented it and used it. It's functional in all games. It's not like they can remove it at this point.

**Comment by robotboy655** [comment]
It's not like we **have to** add it Lua for it be never used.

**Comment by WilliamVenner** [comment]
If this doesn't exist then it's not actually possible to render an animated texture as per the specification of VTF via Lua because this isn't implemented.

I don't understand what your problem is with adding a simple function. Do you really get paid to argue down extremely simple requests because _you_ don't think they'll get used, despite a community request? It's exhausting. I'm not asking for much. You already did half the work by finding `CVTFTexture->m_iStartFrame`

**Comment by robotboy655** [comment]
Looking more into it, it's never actually used in the engine, so there's literally no reason to bind it. It's not even exposed to `ITexture(Internal)`. Even if you set it to non 0 in the .vtf, it will never affect the texture in-game. So assume StartFrame = 0.

**Comment by WilliamVenner** [comment]
What the fuck, you're right. Strange how VTFEdit implements it if it's literally unused.
