### ISSUE TITLE
Make "mp_falldamage 1" the default setting

### ISSUE THREAD

**Issue by Tiagoquix** [Facepunch/garrysmod-requests#1769]
Realistic fall damage is a good thing, and I think it should be enabled by default.

**Comment by thegrb93** [comment]
Iirc mp_falldamage 1 just kills you if you take damage. Servers have the option of adding it via lua https://steamcommunity.com/sharedfiles/filedetails/?id=762217660.

**Comment by Kefta** [comment]
I think this is a bad idea. People love zooming around in sandbox and only taking 10 fall damage. Gamemodes can add this on their own basis.
