### ISSUE TITLE
Ban Anycast.

### ISSUE THREAD

**Issue by NathanX-S** [Facepunch/garrysmod-requests#1770]
### Details
Anycast has been one of the pillars of making Garry's Mod servers the complete wasteland they are today. For every "valid" use of Anycast there's about 500 servers misusing and abusing it. Ping spoofing does no good for anyone, ruins the server browser more than it already is and allows the big boys to stay on top a lot longer than they should've.

**Comment by SneakySquid** [comment]
why would we ban it? anycast is a great addition to any gmod server

**Comment by Kefta** [comment]
See https://discord.com/channels/565105920414318602/589120351238225940/788424882840666134

**Comment by SneakySquid** [comment]
> See https://discord.com/channels/565105920414318602/589120351238225940/788424882840666134 for your answer.

that's pog champ af thanks gs do we have any eta on surface.Get* yet?

**Comment by JustPlayerDE** [comment]
and how you think it should detect anycast? 
banning anycast is not a solution in the long run, may even hit the wrong people
