### ISSUE TITLE
Add proper +use drag hooks

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-requests#1772]
I would propose to add more hooks for the pickup utility, because right now it lacks proper hooks.

Currently available:
AllowPlayerPickup

Suggestion:
PlayerPickedUp(Entity)
PlayerDropped(Entity)

This would help to determine the player dropping entities, thus being able to detemine which player dropped Prop X using the +use pickup system

**Comment by robotboy655** [comment]
Added OnPlayerPhysicsPickup and OnPlayerPhysicsDrop hooks, which handle +use physics pickup
