### ISSUE TITLE
nav_generate_incremental should not run nav_analyze after.

### ISSUE THREAD

**Issue by jacklollz2** [Facepunch/garrysmod-requests#1773]
nav_analyze & nav_generate for a large map is extremely slow and timely. nav_generate_incremental allows me to generate a small patch of a nav area while I am manually editing, but it then tries to analyze the entire map, causing the game to freeze up and run poorly. This is not the final edit, I am not done manually editing the map, I will run nav_analyze after I have finished. The behavior of this command should be changed so it does not try to analyze the map every time it is run.

**Comment by robotboy655** [comment]
nav_quicksave 2 will now skip mesh visibility computation

**Comment by jacklollz2** [comment]
nav_quicksave 2 now no-longer skips mesh visibility computation, it seems this was reverted.

**Comment by robotboy655** [comment]
It was not touched.

**Comment by jacklollz2** [comment]
You're right, even though it was set to 2 it still computed, however, after restarting the game, setting it to 2 again made it not compute. I wonder, if I set it to 2, join a server, then join an SP map, even if it says 2 it may not have changed internally, or something.

**Comment by T-Rizzle12** [comment]
@robotboy655 
I know why nav_quicksave 2 breaks with nav_generate_incremental. I found out that nav_generate_incremental sets nav_quicksave to 1 internally. Disabling this when nav_quicksave is greater than 0 should fix this.

Source:
https://github.com/sr2echa/CSGO-Source-Code/blob/master/cstrike15_src/game/server/nav_generate.cpp#L3426

**Comment by robotboy655** [comment]
It already works like that.
