### ISSUE TITLE
Continued compatibility with Steam API v019

### ISSUE THREAD

**Issue by TiberiumFusion** [Facepunch/garrysmod-requests#1777]
### Details
The [last change](https://commits.facepunch.com/376679) to the x86-64 branch causes gmod to a produce a "Steam Error: No SteamUser" fatal error message on startup when launched through the previous generation Steam client. Vanilla gmod (2020.12.11) is not affected. I certainly could be wrong, but I suspect this is due to a new requirement of Steam API v020. Of course, this means the game will become unplayable in some situations if these changes persist into the master branch.

### Please consider continued v19 support!
**I know this is an unusual request**, but I am dubious of the need for v20+ as a non-negotiable _necessity_ for gmod to work. From the release of v19 up to yesterday's breaking changes, gmod has behaved perfectly when launched under v19. It would be very, very sad if the new requirement of v20 was purely for a trendy throwaway feature, like those fancy status messages in the Steam friends list or to cram unsolicited chat censorship down the player's throat.

I would like to believe there is very minimal effort required in testing for the presence of v20 and disabling the unnecessary fluff features if it's not available. Again, **gmod already runs flawlessly under v19**, before yesterday's breaking changes. At this early point, *it takes more effort to break that than it does to maintain it*, right? Perhaps it even took virtually zero additional effort or conscious thought to maintain v19 compatibility for the last 2 years - so just keep going with that, please!

### Please be civil.
We all know politics and ego rule the gmod community. Crucify me, berate me, tell me how wrong I am and how right you are about embracing the new age of dystopian software... or just don't. You don't *have* to comment if you don't support this request. You already have everyone on your side. Simply being quiet on this matter is already another nail in the coffin and a victory for you.

**Comment by robotboy655** [comment]
The only reason it was updated is to fix Steam fucking up Steam Workshop support for dedicated servers. Rolling the change back is not really an option due to this fact.
