### ISSUE TITLE
Bind NPC functions to Lua

### ISSUE THREAD

**Issue by DrVrej** [Facepunch/garrysmod-requests#1778]
Hi, I have listed couple of functions that would be very useful to bind to Lua. All links point to 2013 source sdk on GitHub.
- `GetIdealActivity() / SetIdealActivity(activity)` ( [Link 1](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/game/server/ai_basenpc.h#L931), [Link 2](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/game/server/ai_basenpc.cpp#L6219) ): Basically the ability to retrieve and change the NPC's ideal activity, which is very useful for transitions between animations, currently there is arrival activity but that only focuses on movement-type of tasks.
- `OnMovementFailed() / OnMovementComplete()` ( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/game/server/ai_basenpc.h#L1320) ): Gives the ability to know if the current movement has failed or completed. At the moment there isn't a reliable way of retrieving this, especially when it fails to do its movement task.
- `OnChangeActiveWeapon(oldWep, newWep)` ( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/game/server/ai_basenpc.h#L1552) ): Useful function to easily detect when the active weapon of the NPC changes.
- `OnObstructingDoor / OnUpcomingPropDoor(doorEnt?)`( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/game/server/ai_basenpc.h#L1343) ): Not sure if these can be binded correctly, but it would help reduce the number of costly checks currently needed to properly detect if a door is blocking the way of an NPC. Maybe they could also be merged into a single function but it seems each points to a different type of object.

Hopefully these are reasonable requests and I understand if some can't be added, good luck and thank you!

**Comment by robotboy655** [comment]
Added NPC:GetIdealActivity
Added NPC:SetIdealActivity
Added ENTITY:OnMovementFailed
Added ENTITY:OnMovementComplete
Added ENTITY:OnChangeActiveWeapon( old, new )

Also updated base_ai with some code that at least makes it work. This should not affect existing SNPCs, as they are overwriting the changed callbacks.

I also documented the return value for ENTITY:OnTakeDamage( dmginfo ), and changed the hook so that if you do not return anything or return a bool, it will take damage and die/ragdoll automatically. Let me know if this uses problems.

I will look into the usefulness of the last 2 later. From their names I am not sure they do what you want them to do.

**Comment by DrVrej** [comment]
> Added NPC:GetIdealActivity
> Added NPC:SetIdealActivity
> Added ENTITY:OnMovementFailed
> Added ENTITY:OnMovementComplete
> Added ENTITY:OnChangeActiveWeapon( old, new )
> 
> Also updated base_ai with some code that at least makes it work. This should not affect existing SNPCs, as they are overwriting the changed callbacks.
> 
> I also documented the return value for ENTITY:OnTakeDamage( dmginfo ), and changed the hook so that if you do not return anything or return a bool, it will take damage and die/ragdoll automatically. Let me know if this uses problems.
> 
> I will look into the usefulness of the last 2 later. From their names I am not sure they do what you want them to do.

Thank you, everything works fine on my end!
For the door functions: Basically when an NPC encounters certain entities such as "func_door" (Popular in HL1-style maps), they are unable to open it. I fixed this by calling `self:GetBlockingEntity()` and opening door through inputs. The issue is that by the time the engine sets the door as blocking, it also sets the node connection to invalid (red). This causes all NPCs to not use that connection again until the `ai_clear_bad_links` command is ran. The command clears all invalid links, which is not good as some of them are important. My hopes are these functions can capture these door entities so I can open them before the node connection is set to invalid, but I am not 100% sure if they capture entities like "func_door". If these are difficult to add, I understand, thanks again!

**Comment by robotboy655** [comment]
Can you get me a link to an example map? (and NPC if the new base_ai on Dev is not good enough)

**Comment by DrVrej** [comment]
> Can you get me a link to an example map? (and NPC if the new base_ai on Dev is not good enough)

Map: https://steamcommunity.com/sharedfiles/filedetails/?id=2284440298
NPC: Default HL2 Rebel
Most doors in this map are "func_door" and "func_door_rotating", some have automatic trigger to open when a NPC comes close, but more than half don't. I used a default HL2 rebel for simplicity, but it can be tested with any default NPC or scripted NPC.
I have also provided a quick video for 2 good locations to test in the map, 1 for "func_door" and the other for "func_door_rotating": https://www.youtube.com/watch?v=61seyA9apz8

**Comment by robotboy655** [comment]
Ok, I made the NPCs open brush doors they come in contact with. I don't see a reason to only limit this to custom NPCs.

They will only open the doors if:
* A player can open the door via +use or touching it
* The door is not locked
* The door does not have the "NPCs can't" flag, meaning they are not meant to be opened by NPCs

Let me know if this causes any problems.

**Comment by DrVrej** [comment]
> Ok, I made the NPCs open brush doors they come in contact with. I don't see a reason to only limit this to custom NPCs.
> 
> They will only open the doors if:
> 
> * A player can open the door via +use or touching it
> * The door is not locked
> * The door does not have the "NPCs can't" flag, meaning they are not meant to be opened by NPCs
> 
> Let me know if this causes any problems.

Thank you, I tested it with both of the entities, everything is working good!
