### ISSUE TITLE
Quaternions 

### ISSUE THREAD

**Issue by Ultimum-Aeternum** [Facepunch/garrysmod-requests#1794]
Can we get functions to work directly with quaternions and vector4?

**Comment by thegrb93** [comment]
vmatrix serves the purpose of rotations

**Comment by Ultimum-Aeternum** [comment]
Sure yes its very efficient to simulate physics by rotating props with matrix and converting to angle.
Sure its not even as fast as directly fucking with quaternions.
Btw nevermind, found workaround to my initial problem and outsourced it back to havok.

**Comment by Kefta** [comment]
Vector2D->5D have been added to the new API/module base. This will not be available in the near future, but will eventually.
