### ISSUE TITLE
Increase MAX_DECALS

### ISSUE THREAD

**Issue by JokerR3310** [Facepunch/garrysmod-requests#1796]
i'm currently working on a large map that have ~1300 info decals placed randomly all around the map, and the problem is when in game someone place a spray or shoot a wall, only one "dynamic" decal is appeared and previous one disappears immediately, not even all "static" decals is appeared on the map.

This followed by this message: "**R_FindDynamicDecalSlot: no slot available.**" 

If i render whole map at once on the screen i get this error:
"**R_DrawDecalsAll: overflowing m_aBatches. Reduce 1048576 decals in the scene.**"
But i think this has nothing to do with actual hard decal limit.

With "**r_printdecalinfo**" command it says:
**2048 decals: 2048 permanent, 0 dynamic**
and if somebody place one decal:
**2048 decals: 2047 permanent, 1 dynamic**

So, is decals limit can be increased, will it break the game in any horrible way ?

Interesting thing is info_overlay don't count as decals, so 2048 are coming from 1300 infodecals only, and maybe each brush 
one infodecal touch is considered as separate decal by engine.

![ind](https://user-images.githubusercontent.com/14869831/107132043-7f269800-68e4-11eb-8f8c-1e8461ea6649.jpg)

**Comment by robotboy655** [comment]
It is controlled by the `r_decals` ConVar as far as I can tell.

**Comment by JokerR3310** [comment]
`r_decals `ConVar has no effect over maximum decal limit, it can only set limit of "dynamic" decals from 0 to 2048 but not above


![52maxdecal6435435876235](https://user-images.githubusercontent.com/14869831/107438398-14ba6580-6b39-11eb-828b-217e8e62409b.jpg)

**Comment by robotboy655** [comment]
You must set it before loading a map.

**Comment by thegrb93** [comment]
Also, it's likely stored in cfg/client.cfg or somewhere there so you should change it there.Also, it's likely stored in cfg/client.cfg or somewhere there so you should change it there.

**Comment by JokerR3310** [comment]
I set it in **/garrysmod/cfg/autoexec.cfg** before loading a game and also i have same convar in **config_default.cfg**, so its always have correct number and still no luck, limit is solid 2048

![4567567867078078340-4](https://user-images.githubusercontent.com/14869831/107545595-269d1680-6bd4-11eb-95b4-eb83a9332e4c.jpg)

**Comment by JokerR3310** [comment]
![4567567867078078340-4](https://user-images.githubusercontent.com/14869831/107550040-379c5680-6bd9-11eb-807e-5eb5f379ba39.jpg)

I made a test map with 2040 infodecals, can somebody check if `r_decals` can actually make it past 2048 or not
https://drive.google.com/file/d/1mNhDt2az3KYETkAz84n3mMqEZ4Q-J7N7/view?usp=sharing

**Comment by robotboy655** [comment]
Oh, I misread the code, it will use the `r_decals`'s default value, not its current value.

I will make it use the `r_decals` value with the hardcoded maximum of 8192 for safety reasons, don't wanna have people make their gmod run out of memory with `r_decals 9999999999`

**Comment by JokerR3310** [comment]
This is great, 8k is more than enough, thanks you, Cant wait to see darkrp servers to be covered in blood and bullet hole decals. xD
