### ISSUE TITLE
Option to add custom presets for enabled addons. (Explained further in post)

### ISSUE THREAD

**Issue by Zohondekids** [Facepunch/garrysmod-requests#1797]
## Customly creatable enabled addons sets.
I was thinking earlier, it would be nice if you could have another option in the addons menu, to save a certain set of enabled addons, instead of just the basic enable/disable all and going through manually. I think it'd be nice for when I'm hosting a P2P and want certain addons, I could have a preset saved for playing with friends that only has some addons I want enabled, that can be loaded in one click. Then later when I want to play alone, I could load a singleplayer set of addons. The reasoning for this is cause when you have so many addons, it takes forever to scroll through the menus and choose which ones you want/need, and then you can up passing by or going over some ones you wanted but forgot. Whereas if I had access to custom presets (preferably you'd be able to make as many as you want and customly name them), I'd only have to go through addons once for each preset list I choose to create.

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/107161510-cd4fa000-69a5-11eb-94c8-864329e19244.png)

It is already in the game since 2020.

**Comment by Zohondekids** [comment]
> ![image](https://user-images.githubusercontent.com/3299036/107161510-cd4fa000-69a5-11eb-94c8-864329e19244.png)
> 
> It is already in the game since 2020.

Wow, I am blind, sorry about that!
