### ISSUE TITLE
Improvement of some windows hammer editor.

### ISSUE THREAD

**Issue by MARK2580** [Facepunch/garrysmod-requests#1798]
In the texture browser and in the texture editing window, there is a very short field where the path and name of the texture is displayed, it is very difficult to understand which texture is currently selected, especially if there are many textures with the same beginning in the name.
![Strip 1](https://user-images.githubusercontent.com/11617079/107246666-844d2980-6a41-11eb-9735-1638adb977fc.jpg)
![Strip 2](https://user-images.githubusercontent.com/11617079/107246678-87e0b080-6a41-11eb-82cd-93114732a332.jpg)
I would also like hammer to finally support the visual design of the operating system and not look like a program from windows 2000.
![Strip 3](https://user-images.githubusercontent.com/11617079/107247882-ccb91700-6a42-11eb-8de4-fc0bbc2a3ceb.jpg)
I personally did it by changing the manifest in hammer.exe

**Comment by robotboy655** [comment]
Addressed the bottom 2 issues.

**Comment by MARK2580** [comment]
> Addressed the bottom 2 issues.

I am using x64 assembly, I cannot check.

**Comment by robotboy655** [comment]
Stretched the Face Edit Sheet UI as far as it will go, name your textures shorter.

**Comment by MARK2580** [comment]
> Stretched the Face Edit Sheet UI as far as it will go, name your textures shorter.

the name of my texture now fits
But increasing the width of the right panel is not the best solution, I even disable the status bar for the sake of workspace.
p.s. - it's not my fault that they are named so in gtav, if I change the names, confusion will begin.
