### ISSUE TITLE
Add Sprinkle Tool (Hammer)

### ISSUE THREAD

**Issue by JokerR3310** [Facepunch/garrysmod-requests#1799]
Great and modern mapping instrument, sadly it's only available in cs:go, but since recent activities the source files got publicly available, so they can be analyzed to recreate something similar but better on our platform.

https://developer.valvesoftware.com/wiki/Sprinkle

Some examples of how it might look:
![hammer_spr](https://user-images.githubusercontent.com/14869831/107829500-86d9b700-6d92-11eb-9d34-7a88c368b6ba.jpg)
![hammer_spr_set3](https://user-images.githubusercontent.com/14869831/107836514-15a3ff00-6da6-11eb-85fd-363f6647995a.jpg)

Here's link with example files for "educational purposes" from game i mentioned above:
https://drive.google.com/file/d/1GWV0-7sHZWBZxQVEoRGeeS-lKa7GXzO1/view?usp=sharing

**Comment by robotboy655** [comment]
Not sure how useful this tool is in its CS:GO form, but I have added it.

I am thinking of using the otherwise unused "Grid Offset" for X/Y pos randomization (so setting X to 5 will add a random value from -5 to +5 to the position on the X axis, etc, and maybe adding a Z pos offset, randomization. Thoughts?

**Comment by robotboy655** [comment]
Added.

**Comment by JokerR3310** [comment]
Just notice, if you releasing L/R mouse button outside of the 3D preview window while paining with Sprinkle Tool it continue to paint until you reclick in the 3D view, same thing happens while resizing a sphere. 
Similar to https://commits.facepunch.com/379580

Should i create a new issue, or this is fine to leave it right there ?

**Comment by JokerR3310** [comment]
OMG you actually did it, first time in history of hammer this menu got an update, i didn't expect that to be honest.
![5545](https://user-images.githubusercontent.com/14869831/110686885-94932880-81e8-11eb-8175-a3e9d0fa5f2d.jpg)

:
This is the time to start Sprinkle Tool icon competition!

**Comment by robotboy655** [comment]
The LMB/RMB issue should be fixed.
