### ISSUE TITLE
NextBot Create Spots

### ISSUE THREAD

**Issue by FoulPlay** [Facepunch/garrysmod-requests#18]
Could we have in the nav that we can create custom spots e.g. 
nav_create_spot SpawnZombies which we can use NextBot to create zombie in that spot and we can move a zombie to e.g. house spot
local pos = self:FindSpot( "near", { type = 'house', radius = 5000 } )

Thank you.

**Comment by LuaHash** [comment]
test

**Comment by LuaHash** [comment]
any updates on this?

**Comment by Roachdaripper** [comment]
Something like this really needs to happen.

**Comment by robotboy655** [comment]
https://wiki.garrysmod.com/page/CNavArea/AddHidingSpot

Not exactly what you wanted, but you can now manually add hiding spots. Custom types are just not really possible without changing the .nav file format.
