### ISSUE TITLE
Addon download retry on Addons Menu

### ISSUE THREAD

**Issue by KirbyJoe** [Facepunch/garrysmod-requests#1803]
### Details
When a subscribed addon is failed to download, the "retry" button appears to make users able to retry downloading addons without restarting Garry's Mod.

**Comment by robotboy655** [comment]
Dedicated retry button unfortunately will not achieve much, the download process is handled entirely by Steam, so should an error on their side happen, it will happen every time until the game is restarted, or worse - verified through Steam if you deleted addon files yourself.
