### ISSUE TITLE
Change blood effect materials with Lua

### ISSUE THREAD

**Issue by TiberiumFusion** [Facepunch/garrysmod-requests#1804]
### Details
There is no way to truly customize the blood impact effects in gmod. The [current options](https://wiki.facepunch.com/gmod/Enums/BLOOD_COLOR) are extremely limited and only include the pre-existing blood types that are built into the engine.

A way to change the [various](http://ozxy.xyz/sourceDocs/2007/fx__blood_8cpp_source.html#l00341) [hardcoded](http://ozxy.xyz/sourceDocs/2007/fx__blood_8cpp_source.html#l00379) [blood](http://ozxy.xyz/sourceDocs/2007/fx__blood_8cpp_source.html#l00418) [materials](http://ozxy.xyz/sourceDocs/2007/fx__blood_8cpp_source.html#l00475) on a per-entity basis would enable the creation of more interesting and believable models. I'd like my oil barrels to bleed oil and my bags of money to bleed money when shot.

Replacing the default blood textures and material files with an addon is an ugly hack and I am dubious of the performance and worth of replicating engine effects 1:1 with Lua effects.

**Comment by thegrb93** [comment]
Can already be done with lua by adding additional effects with EntityFireBullets hook.

**Comment by TiberiumFusion** [comment]
@thegrb93
I was hoping for a cleaner solution. Something where I don't have to hook `EntityFireBullets` or `DoImpactEffect` to create Lua particles. I'd rather just have a different blood material instead of recreating all of the engine blood effects with slower Lua effects.

**Comment by thegrb93** [comment]
You can edit the blood materials already as well.

**Comment by TiberiumFusion** [comment]
@thegrb93 I did not find any information on the wiki that indicated this was possible or how to go perform it. Do you have a specific wiki page that you can cite? Or is this more forbidden knowledge from the facepunch forums...?

**Comment by thegrb93** [comment]
Fetch the material with 'Material(bloodmaterialname)' then https://wiki.facepunch.com/gmod/IMaterial:SetTexture or any of the other IMaterial functions.
