### ISSUE TITLE
Add bindings for missing collision/intersection functions

### ISSUE THREAD

**Issue by Cheatoid** [Facepunch/garrysmod-requests#1805]
### Details
Currently there are just two of such functions available in glua (`util.IntersectRayWithOBB` and `util.IntersectRayWithPlane`).
Requesting to add others (as seen in the [SDK](https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/public/collisionutils.h)):
- [ ] IntersectRayWithRay
- [ ] IntersectRayWithSphere
- [ ] IsSphereIntersectingCone
- [ ] IsSphereIntersectingSphere
- [ ] IsBoxIntersectingSphere
- [ ] IsRayIntersectingSphere
- [ ] IsPointInCone

**Comment by robotboy655** [comment]
Was fulfilled here: https://github.com/Facepunch/garrysmod-requests/issues/2134
