### ISSUE TITLE
More Hammer visual improvements

### ISSUE THREAD

**Issue by JokerR3310** [Facepunch/garrysmod-requests#1807]
1. 3D View Selection
- When Hammer is started for the first time default 3D View Selection window mode is set to "3D Wireframe" this need to be changed to "3D Textured" to make it less confusing for new players.
![4_3ds](https://user-images.githubusercontent.com/14869831/108565332-2bb54080-730d-11eb-8e86-1c887a21ceae.jpg)

2. VGUI model browser
- Make list of models scrolls down or up automatically if arrow key is being held.
- Add Textures tab that show all materials selected model is using.
![4_mat](https://user-images.githubusercontent.com/14869831/108565356-37086c00-730d-11eb-873d-d6b5634ef77a.jpg)

3. Textures browser
- Add a method to copy texture name to clipboard from Textures Browser.
- Move existing textures counter from blue bar to black bar on top
![4_mat — копия](https://user-images.githubusercontent.com/14869831/108565369-3bcd2000-730d-11eb-9ccd-67ff84e584f0.jpg)

4. Entity report window
- Text entry for exact search is extremely small and it's difficult to work with, need to be extended to the right side of the window.
- Remove useless "Close" button to achieve space for longer search bar.
![4_ent_report](https://user-images.githubusercontent.com/14869831/108565396-4687b500-730d-11eb-85ca-d7655996a33b.jpg)

**Comment by robotboy655** [comment]
Model textures are pointless, they cannot be used as map textures. (Because they use a different shader)

**Comment by JokerR3310** [comment]
> Model textures are pointless, they cannot be used as map textures. (Because they use a different shader)

That's right, this one is only for informative purposes, exactly like in HLMV.

**Comment by MARK2580** [comment]
I support. Helpful fixes.

**Comment by robotboy655** [comment]
1. and 4. are fully handled on Dev beta.
3. is partially handled on Dev, haven't looked into copying yet

**Comment by robotboy655** [comment]
3 is now fully handled as well.

**Comment by MARK2580** [comment]
> 3 is now fully handled as well.

Great job, especially useful editable field in the texture browser, I always had problems remembering the names of the skybox textures, now I can just copy and paste it into the map properties. 😊

**Comment by robotboy655** [comment]
I have added the "hold key to scroll" thing to the model browser (and any other place that panel appears).

I will not be adding the Materials tab to it though. I do not see a use for it within Hammer.

**Comment by JokerR3310** [comment]
That's amazing. 
I have already tried these changes, everything looks very good. Nevermind about the materials tab.
