### ISSUE TITLE
Add info_lighting_relative and lightingoriginhack to fgd

### ISSUE THREAD

**Issue by MARK2580** [Facepunch/garrysmod-requests#1812]
I suggest adding `info_lighting_relative` entity to `fgd`, rarely used but useful. It is not very convenient to work with it in SmartEdit mode.
And also `lightingoriginhack` for `prop_dynamic`.
**More info:**
https://developer.valvesoftware.com/wiki/Info_lighting_relative

**Comment by robotboy655** [comment]
What does this provide that the normal `lightingorigin` does not? What's the difference?

**Comment by MARK2580** [comment]
> What does this provide that the normal `lightingorigin` does not? What's the difference?
This is an additional option for info_lighting_relative to work. Here's an example. Original map from hl2.
[d2_prison_06.zip](https://github.com/Facepunch/garrysmod-requests/files/6070135/d2_prison_06.zip)

**Comment by robotboy655** [comment]
That doesn't answer my question.

The wiki page you linked says the following:
>Deprecated by `LightingOrigin` keyvalue and `SetLightingOrigin` input for point entities (these however are not in Valve's FGD by default), use those instead, as they can accept any entity as a lighting origin.

So I ask again:
What does this provide that the normal `lightingorigin` does not? What's the difference?

**Comment by MARK2580** [comment]
> That doesn't answer my question.
> 
> The wiki page you linked says the following:
> 
> > Deprecated by `LightingOrigin` keyvalue and `SetLightingOrigin` input for point entities (these however are not in Valve's FGD by default), use those instead, as they can accept any entity as a lighting origin.
> 
> So I ask again:
> What does this provide that the normal `lightingorigin` does not? What's the difference?

![123456](https://user-images.githubusercontent.com/11617079/109691349-65e9d200-7b98-11eb-8739-ae77a1f5999c.jpg)
gtamike_TSGK intentionally left a tutorial, a link to the original vmf to demonstrate the work of this "CRUTCH from valve" but for some reason you still resist. Do not trust the wiki 100%, there are a lot of things that are never mentioned at all, but they are.
![nIcMBzfKCY](https://user-images.githubusercontent.com/11617079/109692168-42735700-7b99-11eb-81f4-a9cf1227d25f.jpg)
https://developer.valvesoftware.com/wiki/Prop_dynamic

**Comment by robotboy655** [comment]
> but for some reason you still resist
Oh fuck off. You linked me an article that just states that you should not use this, with a tiny link at the very end of the page for a video tutorial. None of the page describes what the difference is which is what I asked for. Instead of being a smart ass you could've just linked the image you posted above in the first place.

Anyway, it is added.

**Comment by MARK2580** [comment]
@robotboy655 
You yourself confused me and I almost agreed that light origin and hack are one and the same. Good thing I checked on this map.
