### ISSUE TITLE
render.ReadPixel alpha output

### ISSUE THREAD

**Issue by DBotThePony** [Facepunch/garrysmod-requests#1813]
As for now, a workaround would be to use two additional rendertargets, one being completely white but translucent (`render.Clear(255, 255, 255, 0, true, true)`) for extracting alpha channel, second being completely opaque and black (`render.Clear(0, 0, 0, 255, true, true)`), and rendering first render target over second will provide you with alpha in form of white color gradation

![gmod_3tT4sj9XRo](https://user-images.githubusercontent.com/6339511/109409542-3a16f280-79c6-11eb-8391-5eba89d38be1.png)

Original rendertarget/material need to be drawn over sample (first additional rendertarget) using next blend mode:
```lua
render.OverrideBlend(true, BLEND_DST_COLOR, BLEND_DST_COLOR, BLENDFUNC_ADD, BLEND_SRC_ALPHA, BLEND_DST_ALPHA, BLENDFUNC_ADD)
```

Also i would like to push any textures to `render.CapturePixels()` and `render.Capture()`, to avoid copying it to temporary rendertarget and wasting even more video memory, for example, not to copy HTML Material to a rendertarget to be able to capture pixels of it or make PNG out of it.

Usecase: Encoding rendertargets onto transparent VTF textures straight without hacks.

**Comment by thegrb93** [comment]
Yucky work-around. Hopefully fix can be soon; I know a people who also needs it.

**Comment by robotboy655** [comment]
What are you even trying to accomplish there? You are loading images (`.png`/`.jpg`) from the web right? Why not just use `Material()`?

Also I do believe this would be a much more sensible solution to your problem than strange hacks to existing functions.
https://github.com/Facepunch/garrysmod-requests/issues/605

**Comment by thegrb93** [comment]
It's needed for other things too like reading pixel data from game textures. Someone I know needs it for their raytracer.

**Comment by DBotThePony** [comment]
@robotboy655 yes, i load them from web server, but i encode them to DXT1/DXT5 (where applicable) at runtime (pure GLua) to save *a lot* of video memory.

**Comment by robotboy655** [comment]
Now returns the alpha channel.

**Comment by DBotThePony** [comment]
Many thanks
