### ISSUE TITLE
Add scripts/*.txt to GMA whitelist

### ISSUE THREAD

**Issue by ceifa** [Facepunch/garrysmod-requests#1814]
### Details
It's useful to edit weapons of vanilla gmod and sentences.txt

**Comment by ceifa** [comment]
The feature is already implemented, should just be merged: https://github.com/Facepunch/gmad/pull/24

**Comment by robotboy655** [comment]
sentences.txt is a bad idea because they have to match **exactly** between client and server.

**Comment by ceifa** [comment]
I really can't get `PrecacheSentenceFile` working, related: https://forum.facepunch.com/t/how-to-use-precachesentencefile/241338

**Comment by robotboy655** [comment]
Looks like there is an issue with it yeah.

https://github.com/Facepunch/garrysmod-issues/issues/3987

**Comment by Xalalau** [comment]
I also need this function.
https://forum.facepunch.com/t/how-to-use-precachesentencefile/241338

**Comment by ceifa** [comment]
Tested and it's working well after this commit:
![image](https://user-images.githubusercontent.com/26205666/109898396-f1d02c80-7c72-11eb-8617-4217d5909cdd.png)
Thanks a lot for the quickly fix, I will be closing this issue.
A suggestion now would be log an error if the file precached not exists, fail silently it's a very bad ideia.
