### ISSUE TITLE
Bind GetSoundInterests for SNPCs

### ISSUE THREAD

**Issue by BREEDNKMs** [Facepunch/garrysmod-requests#1827]
Most NPCs from Half - Life 2 sense bullets passing by, notice grenades, run away from incoming vehicles or hear footsteps with GetSoundInterests. None of present SNPCs can sense any of sound hints, probably because SNPC base derives from CGenericActor (cycler_actor) which defaults all perceivable sounds to none, such as following: 

`int CGenericActor::GetSoundInterests ( void )
{
	return	NULL;
}
` 

Whereas any Half - Life 2 NPC has a perceivable sounds list defined like: 

`int CNPC_MetroPolice::GetSoundInterests( void )
{
	return SOUND_WORLD | SOUND_COMBAT | SOUND_PLAYER | SOUND_PLAYER_VEHICLE | SOUND_DANGER | 
		SOUND_PHYSICS_DANGER | SOUND_BULLET_IMPACT | SOUND_MOVE_AWAY;
}
` 

Binding GetSoundInterests will both eliminate the need of writing Lua hooks to detect objects, and give a purpose for "sound.EmitHint".

**Comment by robotboy655** [comment]
I am not sure `GetSoundInterests` will do anything on its own. It's down to the NPC code to act on the sounds it hears nearby. Perhaps a way to get that would be far more useful? I.e. a binding for `GetLoudestSoundOfType`

**Comment by BREEDNKMs** [comment]
`GetSoundInterests` looks like a whitelist function. Most of the sound data is being parsed in npc internal code and then sets specific conditions like `COND_HEAR_DANGER,` and npcs react to conditions they have in mind. `GetLoudestSoundOfType` would work too when bound, but I was looking for a way to bring back default functionality that's mostly used in HL2 npcs, to my snpcs I work with. `GetLoudestSoundOfType` would enable us to get best sound, as an alternative to `GetBestSound,` but would require all condition sets to be rewritten in LUA, even to react to a grenade or turn around when they hear a bullet passing by.

**Comment by robotboy655** [comment]
Added `NPC:GetBestSoundHint( types = all of them ) = table or nil` (Requires `ENT:GetSoundInterests` to allow the given type(s))
Added `sound.GetLoudestSoundHint( type, pos ) = table or nil`
Added `ENT:GetSoundInterests` for `ai` type SENTs (Limited update rate to 1 per second)

This should fulfill this request.
