### ISSUE TITLE
Allow matproxy.Init's return value to be passed to/returned in IMaterialProxy::Init implementation

### ISSUE THREAD

**Issue by LeQuackers** [Facepunch/garrysmod-requests#1829]
```IMaterialProxy::Init```'s return value controls whether or not a particular material proxy is allowed to run. Being able to control this would help with lua proxies that are only run once or that don't update often.

**Comment by robotboy655** [comment]
Is that actually useful though? Returning false will not ever call the `bind` function of the matproxy, its not just "once" or "always", it's "never" or "always".

**Comment by robotboy655** [comment]
Yeah as far as I can tell this is not what you think it is.

**Comment by LeQuackers** [comment]
That's unfortunate. I was looking into adding some custom material proxies through lua. The main issue was detecting what materials had what proxies at runtime without calling the bind function every frame. In the case of the ConVar proxy the plan was to record what materials had the ConVar proxy then bail to prevent the bind function from being called every frame and only update the particular materials when needed.

Is it possible to get a hook or gameevent for when a material is precached or its proxies are being initialized?
