### ISSUE TITLE
slight improvement to player.GetAll() GetBots() and GetHumans()

### ISSUE THREAD

**Issue by VaasKahnGrim** [Facepunch/garrysmod-requests#1835]
Basically just having it store current player count in the 0 index. since ipairs and pairs will ignore the 0 index its unlikely to cause any issues with the majority of already built addons and gamemodes.

This would be really great as we wouldn't have to use the # opperator to get the amount of players returned by player.GetAll() anymore. This being based on info found here from section 10 regarding for loops https://gitspartv.github.io/LuaJIT-Benchmarks/ According to the test results there tbl[0] was a fair bit faster than #tbl.

If player.GetAll() naturally had the player count stored as the 0 index it would allow devs to further improve performance on some expensive loops with little to no risk of damaging anything else already using player.GetAll()/player.GetHumans()

This would also be a fair bit useful for some other functions in the future possibly, such as ents.Find* functions, but I'm not sure that would be possible or not depending on how source engine handles entity count. But for player.Get functions I'm fairly sure implementing this would be much easier, if not trivial to add

**Comment by thegrb93** [comment]
pairs doesn't ignore the 0 index. Isn't there player.GetCount and ents.GetCount already or something?

**Comment by VaasKahnGrim** [comment]
yes I'm aware of player.GetCount() but thats  involving a seperate function call thats moving data from C/C++ to lua state. Sending the count along with the list of players automatically would be better than doing two seperate function calls that both move data from C/C++ to lua

**Comment by neico** [comment]
See the Note on the mentioned `GetCount` functions in the wiki:
> Similar to #ents.GetAll() but with better performance since the entity table doesn't have to be generated.
If ents.GetAll is already being called for iteration, then using the # operator on the table will be faster than calling this function since it is JITted.

Only `player.GetBots` and `player.GetHumans` isn't covered by those, but one could add an optional filter arg to `player.GetCount` to filter either humans or bots out,
or simply make it return all 3 counts as table if the arg is true.

**Comment by GitSparTV** [comment]
I heard another idea of making it return 2 values: table or entities and # of the table
```lua
local ply, ply_len = player.GetAll()
```

**Comment by VaasKahnGrim** [comment]
> I heard another idea of making it return 2 values: table or entities and # of the table
> 
> ```lua
> local ply, ply_len = player.GetAll()
> ```

This would also be acceptable and pretty much accomplish the same thing. and even less likely to cause issues considering pairs would loop over 0.

**Comment by Kefta** [comment]
> I heard another idea of making it return 2 values: table or entities and # of the table
> 
> ```lua
> local ply, ply_len = player.GetAll()
> ```

I suggested this years ago and it unfortunately breaks compatibility. PrintTable(player.GetAll()) would change behaviour with two returns for example.

**Comment by GitSparTV** [comment]
As expected. We are doomed here then. `#` operator will be faster in LuaJIT 2.1 (already in HEAD).

**Comment by VaasKahnGrim** [comment]
> > I heard another idea of making it return 2 values: table or entities and # of the table
> > ```lua
> > local ply, ply_len = player.GetAll()
> > ```
> 
> I suggested this years ago and it unfortunately breaks compatibility. PrintTable(player.GetAll()) would change behaviour with two returns for example.

Why wouldn't PrintTable() just ignore the 2nd return for the count? shouldn't it only try to use the 1st var given to it?

**Comment by GitSparTV** [comment]
PrintTable has 3 args actually.
Second one is ident amount
https://wiki.facepunch.com/gmod/Global.PrintTable

**Comment by VaasKahnGrim** [comment]
ah, I've only ever put one in. Didn't know it had 2 other params. Tho people could just localize the first return from player.GetALL() and then print that out I guess?

**Comment by GitSparTV** [comment]
or `PrintTable((player.GetAll()))`
But it's still potential risk of incompatibility. Better approach would be having player.AllLen, but at this point `#` is fine

**Comment by VaasKahnGrim** [comment]
lame, but guess no way around it unless a mirical happens
