### ISSUE TITLE
DNumSlider Light mode

### ISSUE THREAD

**Issue by pparadoxx** [Facepunch/garrysmod-requests#1837]
### Details
Currently the DNumSlider slider part (the one that's got the notches) is completely black, I'd be useful to have a function to turn it white. And no, overriding Paint doesn't work (it includes the chunk of text next to it).

**Comment by robotboy655** [comment]
DNumSlider now colors the notches and the DTextEntry text to match the slider label
Added DSlider.Set/GetNotchColor
Added SKIN.colNumSliderNotch
Improved slider notch rendering - ensure all notches have at least 1 pixel between each other, and fixed the last notch not rendering for sliders with a range that isn't a whole number

This should fix any color inconsistencies you were looking to fix. Existing derma skins may need some updating to support notch coloring.

**Comment by pparadoxx** [comment]
Thanks, love you too xd
