### ISSUE TITLE
Nextbot Brush Clip Collision Problem/NextBot Tweak Request.

### ISSUE THREAD

**Issue by rebel1324** [Facepunch/garrysmod-requests#184]
You know, old GMOD SNPC Creation method is pretty broken. So, garry gave us NextBot as alternative solution, 

NextBot is good, Easy to code, Uses navmesh so you don't have to find ai-noded maps. But since garry made it as a replacement of NPC, I think It should has some property of NPC. Maybe, A way to implant property of NPC to specific Entity.

If you made some NextBot NPC for your gamemode, you'll face several problem. 

1. Your NextBot NPC does not targets your NPC. 
2. Your NextBot NPC can't go through NPC Clipping Tool Brush.
3. Your NextBot NPC does not considered as NPC in the engine( the problem that you can partially deal with. )

This is serious concern. This problems make developer hesitate or not want to make NextBot NPCs in thier gamemode. 

Why would developers use NextBot if it's broken?

I seriously think this must be fixed. This problems actually ruins NextBot's purpose.

**Comment by robotboy655** [comment]
1) If you want, you can open a new issue for this. ( In garrysmod-issues )
2) Fixed
3) Its not really supposed to.
4) One problem/request per issue.
