### ISSUE TITLE
Pretty please make NPC:Disposition() & Entity:GetRelationship() able to be called clientside

### ISSUE THREAD

**Issue by Vuthakral** [Facepunch/garrysmod-requests#1846]
### Details
Title.

The functions are currently serverside-only which can make it very extremely not network-performance friendly if these functions are needed for client-side renderables such as HUDs.

**Comment by thegrb93** [comment]
I think stuff like this is up to addons to network. The engine only networks the bare essentials because networking everything would be too much.

**Comment by thegrb93** [comment]
Also the NPC relationships are a somewhat complex structure I think.

**Comment by robotboy655** [comment]
This data does not exist on the client.

**Comment by robotboy655** [comment]
I don't think it's a good idea force this not insignificant data to be sent to all clients on every server for the 1 or 2 addons to use it. Network it yourself if you need it.

**Comment by Vuthakral** [comment]
darn
