### ISSUE TITLE
Allow BoneFollowers to collide with world with boolean setting.

### ISSUE THREAD

**Issue by wolfestridershooter** [Facepunch/garrysmod-requests#1848]
### Details:
This would allow for entities like planes and movable doors to update their collision using bone positions.

**Comment by robotboy655** [comment]
If you mean https://wiki.facepunch.com/gmod/Entity:CreateBoneFollowers, the bone followers are not actual physics objects. Planes is not what they are for. That's what normal physics is for. Animated doors is what the bone followers are for.
