### ISSUE TITLE
Add clientside PlayerCanHearPlayersVoice 

### ISSUE THREAD

**Issue by aStonedPenguin** [Facepunch/garrysmod-requests#1852]
### Details
The recent changes to `PlayerCanHearPlayersVoice ` are a great step but the ability to do the more intensive tasks clientside would be very helpful.

**Comment by meepen** [comment]
I feel like this could be very misused by developers causing harm to
players experience, but this could alternatively be used instead of setting
the bitmask on events serverside

**Comment by robotboy655** [comment]
You can already mute players clientside. 

But moving the hook clientside completely would also cause higher network usage because voice chat data would still be sent to the client, even if it cannot be heard by the client.

**Comment by aStonedPenguin** [comment]
I don't mean move it clientside, I mead add it clientside so more complex things may be done there.

For example I would like to do my basic distance check server side and then do traces clientside to determine whether you're standing behind a prop, wall or some other factor that would be a lot more efficient to handle clientside.
