### ISSUE TITLE
New Servers are Dying because of this BUG. 👎💯 

### ISSUE THREAD

**Issue by anyome** [Facepunch/garrysmod-requests#1855]
Hey !

I noticed that the Gmod Browser don't show all the Server when you click on "Find Multiplayer Games" for the first Time
It only shows Server that are not Empty or Full servers.

So people need to do: "Refresh Listing" in order to see the Others Servers.

We are a New Community, and we want to bring Players to our Servers, but they don't see Them in the Server Browser List and need to do "Refresh Listing" everytime in order to be able to see our Servers cause they are New Servers.

When they press : Find Multiplayer Servers it only shows 2000 Servers.
After clicking on Refresh Listing it start Showing +7000 servers.

This is a Bug that needs to be Fixed.

Bug => Empty Servers are not Shown on the Server Browser List.
How are we Supposed to make our Servers Successful if they don't even get Shown on the Browser List if they are Empty?.
Please fix this ASAP. it's only this that makes our Community not able to rocket launch.

Thank you
@robotboy655
@willox

**Comment by viral32111** [comment]
This is a bug report, not a request. It belongs in the other repository.
