### ISSUE TITLE
Make collection button/Share preset

### ISSUE THREAD

**Issue by SimplesOne** [Facepunch/garrysmod-requests#1856]
We need an option on the preset part of addons to make a collection on steam, or to make a preset tab on workshop so we can share our mods to our friends because they either want it or they need them to play with us

**Comment by MARK2580** [comment]
For this there are collections in the workshop. You are asking for a completely new function that will have to be written from scratch. There are more important bugs that have not been fixed for 4 years.

**Comment by robotboy655** [comment]
You can now copy presets directly in-game and share them with your friends. You can also now import Steam Workshop collections as presets.
