### ISSUE TITLE
Not a feature but I really need help with this: [ADMIN] Arc and [STAFF] Steve stop my server?

### ISSUE THREAD

**Issue by StupidRepo** [Facepunch/garrysmod-requests#1859]
So basically these people ([Admin] Arc and [Staff] Steve) said I broke the rules and are terming my account and they shutdown my server! Please help, I am scared and don't know if this is true!

Chatlogs:

```
[ADMIN] Arc: Is this your first time hosting a server?
2Epic4You: Yes, I never knew it was gonna be on the first time 
2Epic4You: I mean
2Epic4You: On the server list
[ADMIN] Arc: This server is in direct violation with F4EEO1 section V3
[STAFF] Steve: It has come to our attention that you are breaking our hosting rules, so we are terminating your account 
2Epic4You: How?
[ADMIN] Arc: Your server will be disconnected.
[STAFF] Steve: Please make an inquiry at our website
```

**Comment by StupidRepo** [comment]
I didn't do anything wrong! How did I break the rules? I was just making (testing) a mod and people just joined the server randomly so how was I breaking the rules!

**Comment by StupidRepo** [comment]
Ok, they didn't terminate my account, whatever that means. The server can still show up and be launched *phew*

**Comment by StupidRepo** [comment]
But what does this mean?

**Comment by StupidRepo** [comment]
Update: F4EE01 *section* V3 isn't a real thing. They didn't even link the website. What website am I supposed to send an inquiry to? I think they just used some thing to shut it down. I bet they are not even real right?

**Comment by FoksVHox** [comment]
This isn't for support, close the issue.

**Comment by StupidRepo** [comment]
Please though, I'm worried and I don't know what it means!

**Comment by thegrb93** [comment]
Just a prank bro

**Comment by StupidRepo** [comment]
Wha- what?
How did you shutdown the server?

**Comment by StupidRepo** [comment]
So I can now restart it without being pranked again? *XD*

**Comment by robotboy655** [comment]
Those 2 guys are just some random people. I don't know how the y crashed your server, but everything they said is meaningless.

**Comment by StupidRepo** [comment]
Ok, thanks!
