### ISSUE TITLE
Colorable ropes

### ISSUE THREAD

**Issue by KekkyShmekky** [Facepunch/garrysmod-requests#1860]
Pretty self-explanatory; the ability to color ropes via the Rope Tool as well as Lua as a color argument.

**Comment by robotboy655** [comment]
I have it working, but it cannot be committed yet as it breaks network compatibility.

It will be as simple as calling `SetColor()` on the `keyframe_rope` entity as far as Lua goes, it may even work in Hammer via the "rendercolor" keyvalue, and adopting this to tools should not be too difficult.

**Comment by robotboy655** [comment]
Added.
