### ISSUE TITLE
Add reverse flag into $sequence

### ISSUE THREAD

**Issue by gonzalologorg** [Facepunch/garrysmod-requests#1862]
### Details
There has been multiple additions into studio_mdl from csgo and it would be nice if reverse it's one of those, you can make exit animations and mirror some to give an illusion of different animations

**Comment by robotboy655** [comment]
StudioMDL: Added support for "noanim_keepduration", "forceboneposrot", "scalebonelen", "bonedriver", "reverse", "appendanim", "framestart" and "nostallframes" commands from CS:GO

I have not tested these in game as I do not know what they are for, but everything they do seems to be only in studiomdl itself so they all should work.

In case someone is curious about other undocumented commands, the full list in GMod is as follows:
**ParseSequence** ($sequence)
* event
* activity
* snap
* blendwidth
* blend
* calcblend
* blendref
* blendcomp
* blendcenter
* node
* transition
* rtransition
* exitphase
* delta
* worldspace
* post
* predelta
* autoplay
* fadein
* fadeout
* realtime
* posecycle
* hidden
* addlayer
* iklock
* keyvalues
* blendlayer
* All of ParseAnimationToken

**ParseAnimationToken** ($animation)
* if
* fps
* origin
* rotate
* angles
* scale
* loop
* startloop
* fudgeloop
* snap
* frame
* framestart
* blockname
* post
* noautoik
* autoik
* cmdlist
* motionrollback
* noanimblock
* noanimblockstall
* nostallframes
* All of ParseCmdlistToken

**ParseCmdlistToken**
* fixuploop
* weightlist
* subtract
* presubtract
* alignto
* align
* alignboneto
* alignbone
* match
* matchblend
* worldspaceblend
* worldspaceblendloop
* rotateto
* ikrule
* ikfixup
* walkframe
* walkalignto
* walkalign
* derivative
* noanimation
* noanim_keepduration
* lineardelta
* splinedelta
* compress
* numframes
* counterrotate
* counterrotateto
* localhierarchy
* forceboneposrot {str boneName} [`pos` {vector}] [`rot` {angle} [`local`]] [`range` {int start} {int end} ] [`copyframe` {int}]
* scalebonelen {str Bonename} [`scale` [float=1]]
* bonedriver {str boneName} [`axis`=`x` or `y` or `z`] [`value` {float}] [`range` {float start} {float peak} {float tail} {float end} ]
* reverse
* appendanim {str anim}

[] = optional, {} mandatory, ` ` must be exactly typed like that (subcommand?)
