### ISSUE TITLE
Better resolution for cube maps

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-requests#1864]
### Details
Cube maps right now look a little bit of disgusting.
Making it configurable or atleast higher res would make them prettier and maybe more often used.

A sample of low quality cube maps would be on gm_construct.
These just look low quality and bad in general.

**Comment by robotboy655** [comment]
The engine seems to already have the option to select the size when building cubemaps, but it is used only when the current cubemaps in the map have size of 0.

I have made the command override the size if it's higher than the current map cubemap size (at map compile time, it is 32, which is also the default value of the relevant cvar)

The cvar is:
`mat_envmaptgasize`
