### ISSUE TITLE
SetLagCompensated need work on Player

### ISSUE THREAD

**Issue by wackod** [Facepunch/garrysmod-requests#1871]
LagCompensated on Player sometime can cause issues , such as when player in a trigger_push  
so if SetLagCompensated can work on player   we can fix it by set it false when a player start push by trigger_push  and set it true when end push

**Comment by wackod** [comment]
now  SetLagCompensated is not work on player   IsLagCompensated always true on players

**Comment by wackod** [comment]
i try to use SetLagCompensated(false) on player when he touch trigger_push   but it dose not work    IsLagCompensated always return true

**Comment by robotboy655** [comment]
Please do not open multiple posts about the same issue.

https://github.com/Facepunch/garrysmod-requests/issues/1871
