### ISSUE TITLE
Increase in-game detail prop limit

### ISSUE THREAD

**Issue by JokerR3310** [Facepunch/garrysmod-requests#1873]
In-game Detail prop limit are too small for large maps and not enough to cover entire map tightly with grass.
![2553456436634890-](https://user-images.githubusercontent.com/14869831/120908569-2b4e7480-c674-11eb-8d1c-7018017e30bb.png)

**Comment by MARK2580** [comment]
Yes, the grass disappears from the map too quickly, but this type of vegetation is terribly not optimized. Just look at fps with and without grass. Even with a minimum fps density, it drops dramatically, if the default range is increased, this will greatly aggravate the situation. Better to just use prop_detail and place the grass models where needed.

**Comment by JokerR3310** [comment]
The problem is there is hard limit maybe around 64K or 128K of individual grass sprites game can render, beyond this limit any other grass is not rendered in game. In this screenshot i use absurd "density" "2250" to make it more obvious what it look like in game. In reality i have to use "density" around "160" or less to force game to render grass all around the map, but it look like there is 1-2 meters between individual grass sprites with is so sad.
![64356543293-89087](https://user-images.githubusercontent.com/14869831/120922579-aba3c280-c6d2-11eb-87c1-6ea9502aa56e.jpg)

**Comment by MARK2580** [comment]
what to do, very old engine, hopefully source 2 will be better... yes @robotboy655  😁

**Comment by robotboy655** [comment]
There was a bug that "limited" the detail prop count to 65k (in reality it would render incorrect detail props), it will be fixed in the upcoming update, and is already available on the `dev` beta.
