### ISSUE TITLE
Export / Import subscribed addons from file

### ISSUE THREAD

**Issue by redsigma** [Facepunch/garrysmod-requests#1875]
### Details
I think having 2 buttons:
- one that can export all the subscribed addons to a text file, or better export all the workshop community links of each addon in that file. 
- another one that can import the file (for example if a file called saved_addons.txt exist in the garrysmod/data folder, then the import button will subscribe to those addons)
 
I think this is an useful feature especially for devs that want to debug other people addons in order to find the cause of the problem.

**Comment by robotboy655** [comment]
You can use the addon preset system for this (saved to `settings/addonpresets.txt`)

**Comment by robotboy655** [comment]
Recent update added the ability to export presets to clipboard, which you can just paste into a file and save it if you wish to.
