### ISSUE TITLE
Bind CAI_Navigator::AdvancePath() for SNPCs 

### ISSUE THREAD

**Issue by BREEDNKMs** [Facepunch/garrysmod-requests#1877]
I am attempting to create a flying SNPC which finds its way using air navigation, just like crows, manhacks or scanners. 

I prevent default movement code from being called because they request to have a movement action included in the model and it halts the movement task entirely without a move anim. I was trying to rewrite the fly movement code, which works, but cannot decide to move on to next waypoint itself. With an AdvancePath(), I can simply let an NPC take the next waypoint ahead, rather than stick to a single waypoint. 

Example use:

```
function ENT:WaypointReached() 
	if self:GetNextWaypointPos() != vector_origin then  -- we have another waypoint 
		self:AdvancePath() 
	else self:ClearGoal() 
	end 
end 

function ENT:HasWaypointReached()
	return self:WorldSpaceCenter():Distance(self:GetCurWaypointPos()) < self:BoundingRadius())  -- inside the bounding radius, but we can also allow custom distance checks here 
end 

function ENT:RunEngineTask(taskid,data) 
	if taskid == 128 or taskid == 129 then  -- moving
	self:SetMovementActivity(ACT_IDLE)  -- those things block the default move code 
		self:SetArrivalActivity(ACT_IDLE) -- those things block the default move code 
	if self:HasWaypointReached() then self:WaypointReached() end -- what bothers me 
	if !self:IsGoalActive() then self:SetTaskStatus(TASKSTATUS_COMPLETE) end 
	end 
end 
```

**Comment by BREEDNKMs** [comment]
Any updates on AdvancePath()? I'm still trying to make SNPCs with custom flying movement, but I can't make it select next path when it has more than 1 path. It is easy to move to only one waypoint, but not those paths with more than one waypoint. They are always stuck on the same waypoint. 

https://user-images.githubusercontent.com/2939893/158177707-f29bcaba-028e-4002-986f-917666c59b3a.mp4

This may even help us to make ground NPCS with custom movement as well, not just air. I really need this because I often get illegal movement errors with normal movement code.

**Comment by BREEDNKMs** [comment]
i bump this, especially after https://github.com/Facepunch/garrysmod-requests/issues/2231, or else the scripted npcs with alternative movement methods won't progress after first path.

**Comment by robotboy655** [comment]
Added as `NPC:AdvancePath`. Pls test and let me know if it does anything useful for you.

**Comment by BREEDNKMs** [comment]
i tested with the code above on this snpc and now it can travel along paths properly after AdvancePath, clears the current path and connects the snpc to next path.
