### ISSUE TITLE
Unnecessary table structure for function. Change request.

### ISSUE THREAD

**Issue by f1ndme** [Facepunch/garrysmod-requests#1879]
**Entity:PhysicsFromMesh(table)** is a function that requires a specific MeshVertex table structure. While only utilizing 1 of the 8 parameters in it.

The issue is, that single parameter needs to be wrapped in its own table with a specific key value defining it.

Example of a required argument for this function: 
{ {pos=Vector(0,0,0)}, {pos=Vector(0,1,0)}, {pos=Vector(1,0,0)} }

Example of how I believe it could be better: 
{ Vector(0,0,0), Vector(0,1,0), Vector(1,0,0) }

Frankly I don’t know if this improves anything. However having a table for every vertex seems excessive in its current state.

 If there is a concern for changing the argument this function takes, & potentially breaking existing things. Maybe it could be possible to have a second _optional_ argument added instead. Which takes a simple table as suggested above.

Any feedback would be nice. Also below are two links. One to the function in question, & one to the required table structure. Thanks.

[Entity:PhysicsFromMesh(table)](https://wiki.facepunch.com/gmod/Entity:PhysicsFromMesh) 

[MeshVertex (table structure)](https://wiki.facepunch.com/gmod/Structures/MeshVertex)

**Comment by GitSparTV** [comment]
I can think of a very complex solution to use less tables preserving same internal code.
Metatable. Make an array of vectors as you wanted. And the table you input to the function has a metatable with __index metamethod, when indexed it uses dummy table which changes its content depending on the key you index, dummy table also has __index which points to the vector in the array when `pos` is requested

:pepega:

**Comment by robotboy655** [comment]
It is this way so you can reuse data from other functions without any modifications to the table. I have made it accept a table of vectors as well as the old format on the 'dev' beta.

**Comment by f1ndme** [comment]
Thanks guys!
