### ISSUE TITLE
Portal (2) Weapons and Entities

### ISSUE THREAD

**Issue by Pop4484** [Facepunch/garrysmod-requests#1880]
I have played Portal 2 for a really long time and i would like to see it in gmod

**Comment by FlorianLeChat** [comment]
I believe that because [VScript is used](https://github.com/Facepunch/garrysmod-issues/issues/4091) and because Portal's Source engine version is newer than Garry's Mod, it's impossible to use them.

**Comment by MARK2580** [comment]
For the entire existence of gmod, it does not even support the portal gun from the first part, let alone the second, where technologies have long gone ahead, compared to source 2013. It's time to bury GMmod, a replacement will come soon - s&box.

**Comment by FlorianLeChat** [comment]
It's pretty normal that the engine doesn't support this, because it's based on a branch of a game that didn't even have this feature. By the way, it's the same thing with S&Box, it doesn't natively support what Portal 1 & 2 did in the past because S&Box is based on the Alyx branch. So it's clearly not a question of Source 1 or 2.

**Comment by MARK2580** [comment]
> It's pretty normal that the engine doesn't support this, because it's based on a branch of a game that didn't even have this feature. By the way, it's the same thing with S&Box, it doesn't natively support what Portal 1 & 2 did in the past because S&Box is based on the Alyx branch. So it's clearly not a question of Source 1 or 2.

s&box has just begun its development, all entities there are now being rewritten from scratch, I think a lot of things will be out of the box right away, the main thing is that the water is delivered x)

**Comment by Pop4484** [comment]
Could addding trigger_catapult, prop_weighted_cube and stuff like that be possible?

**Comment by GitSparTV** [comment]
First requires the model to be shipped with the game for sure

**Comment by robotboy655** [comment]
`trigger_catapult` is just a trigger entity, it doesn't require anything (it's also in TF2)

**Comment by GitSparTV** [comment]
Oops meant `second` instead of `first`

**Comment by Pop4484** [comment]
so does that mean adding trigger_catapult would be possible?

**Comment by robotboy655** [comment]
Yeah I can see it being useful to mappers.

**Comment by robotboy655** [comment]
`trigger_catapult` was added a good while ago.
