### ISSUE TITLE
SetLightWorld() for ProjectedTexture

### ISSUE THREAD

**Issue by ZH-Hristov** [Facepunch/garrysmod-requests#1882]
Allow us to set the "lightworld" keyvalue through Lua. I'm trying to do it with SetKeyValue but it doesn't seem to work on either realm. Maybe I'm just doing it wrong, but it would be nice to have as a Lua function nonetheless.

**Comment by ZH-Hristov** [comment]
Bump, but the problem was that ProjectedTextures just seem to not inherit methods from Entity at all. Why is this the case?

**Comment by robotboy655** [comment]
ProjectedTextures are not entities, hence why they don't inherit any methods.

**Comment by robotboy655** [comment]
Added.
