### ISSUE TITLE
Why the Npcs are in T poses? I don’t have any extra content!

### ISSUE THREAD

**Issue by MrKingAwesomeYT** [Facepunch/garrysmod-requests#1886]
When I play Gmod, I spawn a Npc and it just standing there in a T pose, how can I fix this problem? Please help me out.

**Comment by FlorianLeChat** [comment]
https://github.com/Facepunch/garrysmod-requests#read-this-before-doing-anything

**Comment by robotboy655** [comment]
This is not a place to get help. You can get help either on our official Discord server (https://discord.gg/gmod), or on the official Support website: https://support.facepunchstudios.com/
