### ISSUE TITLE
Prop Hunt Help? Stuck and can’t see my self as prop.

### ISSUE THREAD

**Issue by MrKingAwesomeYT** [Facepunch/garrysmod-requests#1887]
When I play Prop Hunt, I’m zoom in as the rag doll for the prop character and when I turn into a Prop I can’t see my self as a prop, I mean just a little and first person as a prop, how I fix this.

**Comment by FlorianLeChat** [comment]
Same as #1886 and this isn't a Garry's mod issue but the Prop Hunt gamemode.

**Comment by robotboy655** [comment]
This is not a place to get help. You can get help either on our official Discord server (https://discord.gg/gmod), or on the official Support website: https://support.facepunchstudios.com/
