### ISSUE TITLE
util.Base64Encode - option to omit the newline after every 76th character

### ISSUE THREAD

**Issue by WilliamVenner** [Facepunch/garrysmod-requests#1889]
util.Base64Encode is compliant with RFC 2045, meaning it inserts a newline every 76th character.

I am not really sure why they did that. All I know is that is it very inconvenient in some situations, is a waste of space (util.Base64Decode doesn't require this newline anyway) and is a waste of performance as removing the newlines in Lua comes with a cost.

It would be great if there was an argument to disable this behaviour.

**Comment by thegrb93** [comment]
Especially since chromium doesn't support the newlines

**Comment by robotboy655** [comment]
Done.

**Comment by WilliamVenner** [comment]
Cheers Rubat
