### ISSUE TITLE
Allow a way to disable SDK shader fallback

### ISSUE THREAD

**Issue by Xenthio** [Facepunch/garrysmod-requests#1892]
The SDK shader fallback breaks the ability to use custom shaders in garrysmod
perhaps a cvar or launch option could be added to disable the fallback?

**Comment by Xenthio** [comment]
or make it only fallback if no SDK shaders are found

**Comment by robotboy655** [comment]
Assuming you mean falling back of `SDK_VertexLitGeneric` to `VertexLitGeneric` and such, it was done in March 2024 update so that it checks if the shader exists first.
