### ISSUE TITLE
Enable util.GetModelMeshes server-side

### ISSUE THREAD

**Issue by Ramalayha** [Facepunch/garrysmod-requests#1893]
Could be used for example to generate physics meshes for models that don't have them.

When I originally made the function for my module it worked fine both client and server-side so it should just be a case of enabling it unless some changes where made in your implementation that makes it not possible.

**Comment by robotboy655** [comment]
GMod's implementation relies on stuff that only exists on clients. (`CStudioRenderContext::GetTriangles` specifically)

**Comment by Ramalayha** [comment]
I used that in my module as well and it works fine server-side

**Comment by Ramalayha** [comment]
I use that in my module too and it works fine server-side [as can be seen here](https://www.youtube.com/watch?v=8p64GZWKajg)

([Full module code](https://pastebin.com/BXVsyiRq))

**Comment by Ramalayha** [comment]
But [as you said here](https://github.com/Facepunch/garrysmod-requests/issues/84#issuecomment-503714800) you had to rewrite most of it so I don't know if something was changed that makes it client only.

**Comment by robotboy655** [comment]
Huh, I guess it does exist on the server after all. Made `util.GetModelMeshes` shared.

**Comment by Ramalayha** [comment]
Yeah I was surprised it worked too. Thank you :)
