### ISSUE TITLE
A way to multiply matrices without creating garbage.

### ISSUE THREAD

**Issue by Ramalayha** [Facepunch/garrysmod-requests#1894]
Trying to do anything with matrices inside render hooks for example creates a ton of garbage so having something like Vector:Mul but for matrices would be nice, or in the case for a matrix multiplied by a vector having a way to pass in a vector object to write the output to.

**Comment by robotboy655** [comment]
Added VMatrix.Add, VMatrix.Sub and VMatrix.Mul (matrix*matrix only)

Not sure how to do VMatrix*Vector since it returns a vector.

VMatrix:MulVec( in, out ) ?

**Comment by Ramalayha** [comment]
I think either the first on or make Vector:Mul accept a matrix as argument

**Comment by Ramalayha** [comment]
Oh and passing a matrix to write to as a 2nd argument to Entity:GetBoneMatrix as well.

**Comment by robotboy655** [comment]
`Vector:Mul()` now supports `VMatrix`
