### ISSUE TITLE
Use hexadecimal numbers for Entity:SetBodyGroups 

### ISSUE THREAD

**Issue by Nitestokeh** [Facepunch/garrysmod-requests#1895]
Greetings.
It is inconvenient to use bodygroups strings with bodygroup-heavy models because of 9 values limit. Normally, as the wiki points out, for anything with more than 10 bodygroups you could just use Entity:SetBodyGroup, however it's not the case with spawnmenu.AddPropCategory or player_manager.AddValidHands, which both require the usage of a string. Would be nice to either have hexadecimal numbers for string bodygroups for a larger quantity of available bodygroups or add an option to use numbers (ID, value) for these functions.

**Comment by robotboy655** [comment]
Entity:SetBodyGroups now accepts a-z as 10-35
