### ISSUE TITLE
Hide LUA Errors

### ISSUE THREAD

**Issue by Ashen-109** [Facepunch/garrysmod-requests#1901]
Arguably one of the most annoying features of Gmod to date, the LUA error pop-up is one of the most intrusive and immersion-breaking things out there. The ability to disable them, or a feature to automatically hide errors that are created by the same addon after a certain number of errors are created. For example, the error pop-up is hidden if an addon creates something like 10 errors in 2 minutes or something of the like.

**Comment by FlorianLeChat** [comment]
This is similar to #149 but yeah it would be nice if players could disable this feature in the settings without going through the Lua.

**Comment by robotboy655** [comment]
Fix the errors, do not hide them.

**Comment by Faervn** [comment]
"my personal beliefs about how user's should experience the game will stop me from thinking logically. and adding this feature." wow they let monkeys run Gmod huh?

**Comment by rmod8** [comment]
Whislt i do agree with the belief of fixing the error, the end user might just want to do stuff in gmod without having to see the error message. It should be a message for developers, not end users.

**Comment by garryspins** [comment]
> user has no idea why addon isnt working

**Comment by rmod8** [comment]
A player can disable the hud, change fov, disable the green ring on effect models, disable physgun beams, but disabling a notification box in the top left is too far? I feel an option in the context menu would suffice, and if an addon is not functioning (like nothing happening when pressing e on an entity for example), then the user should turn on the LUA errors notification box to see what addon is causing issues. Don't remove the LUA error notification, just give the end user some agency in what is rendered or not. Don't take this message as anti LUA error notifications, i just think more agency in what is shown is good.

**Comment by FlorianLeChat** [comment]
It's fair enough, these messages are intended for developers to fix these errors (and also in some cases for players to report them), but after all, why not give players the option of hiding them? If a convar is added to hide Lua errors, it **should be unchangeable** by the server and Lua scripts, but only by the end-user through the console.
