### ISSUE TITLE
Function to check if an audio file has a start & end cue (loops) or not

### ISSUE THREAD

**Issue by Vuthakral** [Facepunch/garrysmod-requests#1904]
### Details
I have this old script I was working on a while back which was full 3d audio in Garry's Mod which I'd love to finish and publish, but the only main issue I ran into is that there is no way to detect if a sound being played is a looping file or not. This results in looping sounds that are played from a sound bounce that will never stop.

A function which can return if a specific audio file have start/end cue points (what is used to loop them) would be very beneficial for anyone working with sound-related hooks that need their code to ignore/avoid looping sounds, or exclusively target them.

**Comment by robotboy655** [comment]
You should be able to simply parse and cache this data yourself, the `.wav` format is dead simple:
https://sites.google.com/site/musicgapi/technical-documents/wav-file-format#cue
