### ISSUE TITLE
vrad.exe should print offending model name when "unexpected strips found"

### ISSUE THREAD

**Issue by osiris-plus** [Facepunch/garrysmod-requests#1910]
vrad.exe should print offending model name when "unexpected strips found"

https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/utils/vrad/vradstaticprops.cpp#L1999

This change should save time massively when you want to find which model prevents vrad from working properly

**Comment by osiris-plus** [comment]
The current workaround: Make Process Monitor from Sysinternals watch vrad.exe.
The last vvd loaded when message is printed - vvd of the offending model.

**Comment by robotboy655** [comment]
Added models name (from the .mdl, not real filepath) and entity's position to the error message, but I can't really test it without a bad model.

**Comment by osiris-plus** [comment]
```
unexpected strips found in props_interiors\TrashCan01.mdl @ -1024.000000 2656.000000 544.000000
```

it works
