### ISSUE TITLE
Increasing MAXSTUDIOANIMS and MAXSTUDIOSEQUENCES in studiomdl.exe

### ISSUE THREAD

**Issue by KingDavidW** [Facepunch/garrysmod-requests#1912]
### Details
Unsure if these limits are arbitrary but I was hoping it'd be possible to increase the following block sizes:

`#define MAXSTUDIOANIMS			2000	// total animations
#define MAXSTUDIOSEQUENCES		1524	// total sequences`

When decompiling certain animation models with Crowbar you are given the smd files along with CORRECTIVE animations, which add a number of sequences to the model when you recompile it. What would have been under the limit ends up going above erroring with:

`overflowed g_numsources`

requiring that you split the model up.

This is mostly a convenience update, you CAN split up the model but when I reported an issue with the ANIMBLOCKSIZE overflow a while back it turned out that it was just affecting the compiler itself, so I'd hope it's the same with these

**Comment by robotboy655** [comment]
They are tools only limits, and I have increased them slightly to 3k and 2k respectively, de/recompiling models is not something I'd really want to encourage.

**Comment by ZH-Hristov** [comment]
I think they should be raised at least to the L4D2 or the CSGO branch limits, if they're not already. Porting models/animations from those newer branches is a pain due to these overflows.

**Comment by robotboy655** [comment]
They are at/above limits of CSGO now.
