### ISSUE TITLE
Increase MAX_THREADS for vvis and vrad

### ISSUE THREAD

**Issue by osiris-plus** [Facepunch/garrysmod-requests#1913]
I'm trying to run vvis and vrad on a massive VM with 96 cores (through MPI). Unfortunately, I can't utilize all 96 threads due to MAX_THREADS limiting them to 16.

Running multiple instances of workers doesn't help due to some weird error:
```
MPIPortalFlow:       RunMPIPortalFlow: CreateMulticastListenSocket failed. (The operation completed successfully.).
```

This article shows where to change this.
https://developer.valvesoftware.com/wiki/Increased_Thread_Limit_for_Compile_Tools

I hope it's possible to set MAX_THREADS and MAX_TOOL_THREADS to 96, or even 128.

**Comment by robotboy655** [comment]
I have increased it to 64 which is more than enough for all consumer grade hardware currently available, and to see if it makes a difference at all, because the linked article does not inspire confidence with listed <5% improvement.

**Comment by osiris-plus** [comment]
It says this in the article.
> Also the results show only VVIS.

I'll try it with 64 cores.
Also, AMD Threadripper processors come with 128 cores on top model.
