### ISSUE TITLE
Invalid model version (v49) and VRAD's inability to bake shadows for them.

### ISSUE THREAD

**Issue by PixelAffection** [Facepunch/garrysmod-requests#1916]
**### Details**
If the model that you use on your map has a newer MDL version than the one GMod supports (i.e. CSGO and L4D2 models aka v49) it prints the Invalid Model Version error while compiling. What this causes is that shadows will not be calculated and baked by VRAD for those models. Only way around it with GMod is to decompile the models and re-compile them for GMod. This is a decent workaround, but what this causes is that the models will have ugly and incorrect blobby shadows. I've avoided the issue by using Slammin' Source Tools for compiling instead, but it has vastly lower limits for MAX_MAP_BRUSHSIDES along with other limitations that current GMod compiling tools don't have so it's not viable for very detailed maps. So what I'm requesting here is that if it's any way possible, could you make GMod support those newer v49 .mdl files? 
Slammin' Source Tools does it somehow so maybe there is a way to make it recognize those models properly?

**Comment by robotboy655** [comment]
I think this was fixed a long while ago. Let me know if that is not the case.
