### ISSUE TITLE
Add Half life Source Weapons

### ISSUE THREAD

**Issue by T-rex123Dino** [Facepunch/garrysmod-requests#192]
If you added the NPC's, i am pretty sure you can add the weapons too :)
Thank you and i hope you will add those :)

**Comment by CaskoChan** [comment]
@robotboy655 Im pretty sure you recently added HL weapons.

**Comment by robotboy655** [comment]
What do you guys propose we do about duplicate weapon classes? (crowbar, 357, rpg, shotgun, crossbow, possibly _glock and _mp5 for css weapon packs)

Can definitely add a _hl1 suffix but the problem are the maps, which will still spawn the HL2 variations of those weapons.

**Comment by Kefta** [comment]
Can you use BSP versioning to make HL1 weapons load into the default class strings if the map is pre-HL2, and HL2 weapons, otherwise?

**Comment by MaestroFenix** [comment]
I recommend using a prefix / suffix like we did for Obsidian Conflict, and then checking the mapname at the code to force loading the HL1 weapons onto the players. You need to remove the old weapon entries on these maps however.

**Comment by thegrb93** [comment]
_hl1 suffix is fine, just use lua to replace the map's weapons.

**Comment by MaestroFenix** [comment]
HL1 npcs have no "weapons" per se, but directly made onto them. However when the Hgrunts or Barney are killed they drop the weapons ( Glock, MP5, MP5 grenades, Shotgun, grenade ) so extra modifications have to be done so these weapons spawn correctly.

**Comment by Kefta** [comment]
These have all been added.
