### ISSUE TITLE
Request: Access to NPC's CollisionProp()

### ISSUE THREAD

**Issue by MagentaIris** [Facepunch/garrysmod-requests#1929]
Since bounding boxes are trashy most of the time with NPC hit boxes when shooting at them from the side with trace checks, Being able to get access to their CollisionProp() object will let you change the ABSMin and ABSMax box to keep the Bounding box the same but change what encompasses the hit boxes.

Example in antlionguard.cpp
```
// We need to bloat the absbox to encompass all the hitboxes
	Vector absMin = -Vector(100,100,0);
	Vector absMax = Vector(100,100,128);

	CollisionProp()->SetSurroundingBoundsType( USE_SPECIFIED_BOUNDS, &absMin, &absMax );
```

You can use cl_ent_absbox with sv_cheats on up close to an npc to see its CollisionProp abs bounds.

**Comment by MagentaIris** [comment]
No updates on this?

**Comment by robotboy655** [comment]
Added `Entity:SetSurroundingBounds( mins, maxs )` and `Entity:SetSurroundingBoundsType( BOUNDS_  )`

They are mutually exclusive, `BOUNDS_ ` values can be `BOUNDS_HITBOXES` which will make the game try to set the bounds to fit all hitboxes, and `BOUNDS_COLLISION` to use the Entity's collision bounds, which is also the default value for most entities.

The mins and maxs are of an AABB, not OBB!

Also added `mins, maxs = Entity:GetSurroundingBounds()` which will get you the Calculated AABB of the surrounding bounds.
