### ISSUE TITLE
nextbot convars

### ISSUE THREAD

**Issue by Jova1106** [Facepunch/garrysmod-requests#1930]
nb_allow_avoiding
nb_allow_climbing
nb_allow_gap_jumping

I need to change these convars automatically on the server, but it's not possible to do without sv_cheats, or the one 10 year old module that is no longer functioning. Would it be possible to change them to be non-cheat convars, so they can be changed without having to do it manually?

**Comment by Jova1106** [comment]
That, or allow (most/many/some) non-Lua convars to be changed with the ConVar Set commands. Working with Nextbots is a hassle.

**Comment by robotboy655** [comment]
Added CLuaLocomotion.Get/SetClimbAllowed
Added CLuaLocomotion.Get/SetJumpGapsAllowed
Added CLuaLocomotion.Get/SetAvoidAllowed

Since those convars are all enabled by default, these per-nextbot bindings should be enough.
