### ISSUE TITLE
Increase MAX_MAP_TEXINFO

### ISSUE THREAD

**Issue by gooball60** [Facepunch/garrysmod-requests#1932]
Would be nice not to run into this anymore. Current limit is 12288.

**Comment by jorjic** [comment]
You can try increasing this limit and recompiling vbsp. I mentioned more about this [on your other post](https://github.com/Facepunch/garrysmod-issues/issues/5066). You should be able to use the recompiled version to bypass the limit.

**Comment by gooball60** [comment]
> You can try increasing this limit and recompiling vbsp.

I actually ended up doing just that; recompiled my own version of Source with increased limits. The map compiled, but unfortunately engine crashes immediately with a "Map has too many surfaces" error. I suppose I'm out of luck here.

**Comment by jorjic** [comment]
MAP_MAX_TEXINFO is a constant that gets compiled into the engine.dll at compile-time. You could try using a debugger to find where the constant is defined and change it with a memory editor.

**Comment by gooball60** [comment]
The issue is that even if I got the map running on my custom version of Source, it still wouldn't work on the GMod engine unless the limits are increased for GMod as well.

**Comment by jorjic** [comment]
Looks like this request is dead for good then.

**Comment by robotboy655** [comment]
Solved in https://github.com/Facepunch/garrysmod-requests/issues/2304
