### ISSUE TITLE
Reserve main menu in case of chromium failure

### ISSUE THREAD

**Issue by GitSparTV** [Facepunch/garrysmod-requests#1933]
We have https://github.com/robotboy655/gmod-lua-menu as alternative for people who has chromium issues.
However I think the game should inform somehow that chromium failed to load or -nochromium was passed, provide message why main menu is not available, give help link and provide minimal functions. I think it should be as separate file that is required by engine in case chromium failed. Don't load it by default

**Comment by robotboy655** [comment]
There is now a fallback menu in case the HTML one fails to load for any reason.
