### ISSUE TITLE
Serverside disabling worldclicker aiming

### ISSUE THREAD

**Issue by klen-list** [Facepunch/garrysmod-requests#1934]
Serverside ability to disable worldclicker aiming using some hook or at least clamping aimvector to player view.
PreventScreenClicks is not suitable for this purpose as it is clientside and can be easily bypassed with a luarun cheats.
![unknown22](https://user-images.githubusercontent.com/49125075/144906318-c0a31d36-55bd-44cf-b207-902b72972215.png)
As already mentioned in #1361 it can be abused or used as aimbot by lua/c++ cheats.

**Comment by GrandpaTroll** [comment]
Would like a function or hook to allow context world clicking.

**Comment by robotboy655** [comment]
Added Player:DisableWorldClicking & IsWorldClickingDisabled for next update.

It's not currently networked to clients (for UI purposes), but will be in some future update.
