### ISSUE TITLE
A way to set the jump ACT for nextbots

### ISSUE THREAD

**Issue by ZH-Hristov** [Facepunch/garrysmod-requests#1937]
Currently, [Nextbot.loco:Jump()](https://wiki.facepunch.com/gmod/CLuaLocomotion:Jump) relies on the nextbot's model having an ACT_JUMP activity, without which it can't jump unless forced with SetVelocity right after (which immediately makes the NB t-pose).

Something like Nextbot:SetJumpAct(ACT_ID) would be nice.

**Comment by robotboy655** [comment]
Added as the argument to the Jump() function, which defaults to ACT_JUMP
