### ISSUE TITLE
Enabling Combine Advisor's AI And Adding it to the Spawn Menu?

### ISSUE THREAD

**Issue by Pop4484** [Facepunch/garrysmod-requests#1938]
I think it would be pretty cool if the advisor was in with it's AI enabled.

**Comment by robotboy655** [comment]
They do not have any AI as far as I am aware. Any appearances in the Half-Life series are scripted. (Just animations playing)

**Comment by conneath** [comment]
> They do not have any AI as far as I am aware. Any appearances in the Half-Life series are scripted. (Just animations playing)

they do, its disabled by default though (probably for a good reason)
https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/game/shared/episodic/npc_advisor_shared.h#L18
