### ISSUE TITLE
Server Hostname Colour Scheme for Game Browser

### ISSUE THREAD

**Issue by SuperiorJacob** [Facepunch/garrysmod-requests#1940]
### Details
Having formattable and colorizable Garry's Mod server hostnames with possible formatting rules like the ability to **Bold**, _Italic_ or underlining.

Aka add format symbols to the hostname, then when the game browser picks it up, it formats the server.

Example:
![image](https://user-images.githubusercontent.com/33310669/147844876-adbd2e4a-8232-471a-8b94-7e10bcdbad9d.png)

**Comment by Kefta** [comment]
Please keep this out of GMod.
