### ISSUE TITLE
CRecipientFilter boolean functions

### ISSUE THREAD

**Issue by TiberiumFusion** [Facepunch/garrysmod-requests#1941]
It would be nice to have union, difference, and intersection functions available to CRecipientFilter.
- `CRecipientFilter:AddPlayers(CRecipientFilter)` or `CRecipientFilter:UnionWith(CRecipientFilter)`
- `CRecipientFilter:RemovePlayers(CRecipientFilter)` or `CRecipientFilter:DifferenceWith(CRecipientFilter)`
- `CRecipientFilter:KeepPlayers(CRecipientFilter)` or `CRecipientFilter:IntersectionWith(CRecipientFilter)`

It would probably be faster for the engine to provide this instead of relying on Lua-based loops, yes? At scale, I imagine this would have a noticeable performance impact (e.g. setting up multiple recipient filters per tick per weapon per bullet shot).

**Comment by robotboy655** [comment]
Added:
```
CRecipientFilter.AddPlayers( table or filter )
CRecipientFilter.RemovePlayers( table or filter )
CRecipientFilter.RemoveMismatchedPlayers( table or filter )
```

`CRecipientFilter:KeepPlayers` feels like a weird name.
