### ISSUE TITLE
Better error messages when loading a binary module fails

### ISSUE THREAD

**Issue by NoSharp** [Facepunch/garrysmod-requests#1942]
### Details
Better error messages when a binary module fails to load, at the moment, it's simply "Couldn't load module library".
Now, of course there some circumstances where it'd be impossible to determine the reason for a module not loading,
however in the vast majority of cases it can be just a dependency is missing.

For example:
"Unsatisfied dependency DependencyHere"

**Comment by robotboy655** [comment]
I have added OS specific error messages to those Lua errors, that's all the info we have.
