### ISSUE TITLE
Call 'PlayerFootstep' hook when player speed is under 100.

### ISSUE THREAD

**Issue by PixelAffection** [Facepunch/garrysmod-requests#1944]
### Details

Is it possible to get rid of the minimum speed limit so `PlayerFootstep` hook runs even when the player speed is under 100?

My gamemode has walk speed set to 80 and it's rather annoying that footsteps won't play when walking.

I'm aware of the `PlayerHandleAnimEvent` hook to circumvent this, but if player is holding a weapon that has the 'normal' holdtype (like hands) it won't call the events (namely event 45 and event 46) for some reason.

**Comment by Kefta** [comment]
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1064. I'm sure you noticed this, just documenting it.
