### ISSUE TITLE
entity:SetVelocity()

### ISSUE THREAD

**Issue by ReaPeRz38** [Facepunch/garrysmod-requests#1946]
Hello I noticed that when we setVelocity an entity we can not reset it.
Indeed, my print(ent:GetVelocity()) output -1227 in x while I SetVelocity to 0 just before

function dropoffFlight(ent, dropPos)
    if not IsValid(ent) then return end -- Prevent if 'ent' is not valid

    local dropVehicle = ents.Create("lunasflightschool_atte")
    if not IsValid(dropVehicle) then return end -- Prevent if 'dropVehicle' is not valid

    local inFlight   = true
    local dropped    = false
    local timerName  = "inFlightTimer" .. math.random(0, 1000)
    local moveVector = Vector(-10, 0, 0)
    local stopVector = Vector(0, 0, 0)

    originalAngle = dropVehicle:GetAngles()

    print(dropPos)

    timer.Create(timerName, FrameTime(), 0, function()

        if not IsValid(ent) then
            timer.Remove(timerName)
            return
        end

        if inFlight then

            --print( ent:GetPos():DistToSqr(dropPos) )

            if ent:GetPos():DistToSqr(dropPos) < 10000000 then
                inFlight = false
                dropped    = true
                print("test")
                ent:SetMoveType(MOVETYPE_NONE)
                ent:SetVelocity(stopVector)
                --ent:SetMoveType(MOVETYPE_FLY)
                print(ent:GetVelocity())

                timer.Remove(timerName)

                timer.Simple(5, function()
                    if IsValid(ent) then removeEntity(ent) end
                end)
            end
            if not dropped then
                --print("test1")
                ent:SetVelocity(moveVector)
            end
        end
    end)
end

**Comment by FlorianLeChat** [comment]
Wrong repository, you should put this here instead: https://github.com/Facepunch/garrysmod-issues
