### ISSUE TITLE
Bind Remaining NPC Memory Functions to Lua

### ISSUE THREAD

**Issue by DrVrej** [Facepunch/garrysmod-requests#1950]
- [ ] `NumEnemies()`( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_memory.h#L68) ): Simple and effective function, returns the number of enemies in its memory.
- [ ] `SetTimeValidEnemy(enemy, time)`( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_memory.cpp#L601) ): Basically sets the enemy to not be targeted for the given amount of time, assuming another target exists. This is used in some of the complex NPCs in HL2 and would be useful to have it exposed to Lua.
- [ ] `TimeLastReacquired(enemy)`( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_memory.cpp#L475) ): Does exactly as the name suggests, time since it last reacquired the enemy. This function was unfortunately left out when the other `"GetEnemyLast-"` functions were added. This would complete that set of functions, recommend calling it `GetEnemyLastReaquiredTime` 👍
- [ ] `LastTimeTookDamageFrom(enemy)`( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_memory.cpp#L553) ): Returns the last time it got damaged from the given NPC/Player (If it has it in its memory). _ai_basenpc_ already updates this every time the NPC is hit by an NPC/Player, so might as well make this information retrievable in Lua.
- [ ] `OnTookDamageFrom(enemy)`( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_memory.cpp#L397) ): This is how _ai_basenpc_ updates the time, would be good to expose it to Lua so a developer can update the time at any moment they want.

Feel free to name the functions to something else to match rest of the binded functions in Lua, I am using the same names as Source engine to not confuse anyone.. Thank you.

**Comment by robotboy655** [comment]
Added NPC:GetKnownEnemyCount - includes `danger position` "enemy"
Added NPC:GetKnownEnemies - returns a table of entities, does NOT include the above special case
Added NPC:IgnoreEnemyUntil( enemy, time )
Added NPC:GetTimeEnemyLastReacquired( enemy = current )
Added NPC:GetLastTimeTookDamageFromEnemy( enemy = current )
Added NPC:MarkTookDamageFromEnemy( enemy = current )
