### ISSUE TITLE
Expanded Bone Followers Support

### ISSUE THREAD

**Issue by Cpt-Hazama** [Facepunch/garrysmod-requests#1955]
In this previous issue (https://github.com/Facepunch/garrysmod-requests/issues/1229), basic support was added for bone followers in GMod. However, they are limited to anim type entities only, and they lack any arguments that the original functions have. I would like for the bone follower system to be added to more than just anim type entities, specifically ai type entities.

As seen in the strider source code ( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/game/server/hl2/npc_strider.cpp#L638) ), we are able to specify which bones to add followers to.

It would also be beneficial to add AddBoneFollower ( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/game/server/physics_bone_follower.cpp#L64) ) as well as GetBoneFollower ( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/game/server/physics_bone_follower.cpp#L184) ), since we are currently unable to get the bone followers.

**Comment by Dragoteryx** [comment]
> specifically ai type entities
If this is added, having this available on nextbots too would be nice.

**Comment by VpSnipes** [comment]
This would be a seriously nice feature; especially concerning larger NPCs, like Dragons for instance. As it sits, there's no real feasible way to do large NPCs, they just don't work. Unless you specifically code it as an Entity; even then, there's problems with how the Bone Followers were added in the first place so it isn't as reliable as how the engine runs it.

**Comment by Cpt-Hazama** [comment]
Bump

**Comment by robotboy655** [comment]
* Added `Entity:GetBoneFollowers`
* Added new argument to `Entity:CreateBoneFollowers` - table of bones to apply bone followers to
* Bone follower support for `ai` and `nextbot` SENTs
