### ISSUE TITLE
Add autocheck and warning for conflicting addons

### ISSUE THREAD

**Issue by KirbyJoe** [Facepunch/garrysmod-requests#1956]
### Details
Check conflicting addons and warn on problems tab to reduce the time taken for finding these.
The warning message for conflicting addons in problems tab should include buttons to choose which addon to disable.

**Comment by thegrb93** [comment]
There's no list or database of what addons conflict so it won't be possible unless that is done first.

**Comment by GitSparTV** [comment]
Sometimes gmod reports in the console for conflicts. I think it can be made on the same level

**Comment by robotboy655** [comment]
There isn't really a way to test for things like that. The console message just warns of files with same file names in multiple addons. Maybe that could be moved to the Problems tab.

**Comment by GitSparTV** [comment]
Good point

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/158899231-e12ada91-916a-438a-a33e-38d16cc14c54.png)

Here.
