### ISSUE TITLE
Allow loading mounted CS:GO maps seperately from CS:S maps

### ISSUE THREAD

**Issue by somedoodest** [Facepunch/garrysmod-requests#1957]
Currently, attempting to load a CS:GO version of a map that also has a CS:S counterpart (i.e. Dust 2 or Nuke) will result in the CS:S version loading instead, even though they are in a seperate category of maps. This is a problem, as most CS:GO maps are vastly different to their CS:S counterpart and most of the versions of those CS:GO maps on the workshop are heavily outdated, and won't be updated anytime soon. I think a good way to solve this would be to have the game detect if you are trying to load a map located in either the "Counter-Strike" or "Counter-Strike: GO" tab, and loading which mounted game to load the map from based on that.

**Comment by UAVXP** [comment]
Devs should also think about map/changelevel/changelevel2 convars too to support this request

**Comment by robotboy655** [comment]
CS:GO is dead, so this is no longer an appropriate request.

**Comment by Kefta** [comment]
There are still plenty of custom CS:GO maps that will be distributed well past its death. At least leave the request open.
