### ISSUE TITLE
"fadetime" parameter for soundscapes

### ISSUE THREAD

**Issue by Dexterowski** [Facepunch/garrysmod-requests#1961]
### Details
Please add working "fadetime" parameter for soundscapes like specified one in [VDC](https://developer.valvesoftware.com/wiki/Soundscape#fadetime_.3Cfloat.3E)

**Comment by robotboy655** [comment]
Added the following from CS:GO:
`playlooping.position` "random"
`playlooping.radius`
`fadetime`
