### ISSUE TITLE
Change to effect "circle" indicators

### ISSUE THREAD

**Issue by StrawWagen** [Facepunch/garrysmod-requests#1964]
### Details
Remove the gravity gun from the "show effect circles" weapon list.
This feels more like an oversight than something that should go in the workshop.
Thanks!

**Comment by robotboy655** [comment]
Can you please elaborate? I am not quite sure what you mean and how the Workshop factors into this.

**Comment by StrawWagen** [comment]
I got a bit ahead of myself, sorry lol.
![20220430140537_1](https://user-images.githubusercontent.com/64710817/166122695-b45a641d-16e1-4abd-ae7a-482118788674.jpg)
The circle sprites on effects that tell people where to pick them up for building.

They make sense with the Phys/tool gun, but the gravgun is more of a "weapon" than a building tool.
Suggestion I was trying to make was removing the gravgun from the list of weapons that trigger the sprite's rendering.
Thanks haha.

**Comment by robotboy655** [comment]
I don't think so. I see what you are saying, but I have no plans to change this. If you need to, you can hide the circles with the following option:

![image](https://user-images.githubusercontent.com/3299036/166205290-365371fa-5205-4130-b314-304e01d35f72.png)

**Comment by Kefta** [comment]
What's your reasoning? If you can't pick up the object with the grav gun, what use does the circle serve?

**Comment by robotboy655** [comment]
You can pick it up with the gravity gun.

**Comment by StrawWagen** [comment]
You can pick them up with the gravgun? neat!
Still, I don't know if that's a very explored option, lol.
