### ISSUE TITLE
Entity:SetTextureFrameIndex

### ISSUE THREAD

**Issue by mgetJane** [Facepunch/garrysmod-requests#1966]
it's already possible to toggle textures on an entity by setting a targetname and creating an env_texturetoggle entity that targets that name and then firing its inputs, but the [SetTextureFrameIndex](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/env_texturetoggle.cpp#L59) function should just be available through lua so you don't have to do all that hassle

**Comment by mgetJane** [comment]
seems like `ent:SetSaveValue("m_iTextureFrameIndex", value)` works, i guess that makes this unnecessary

**Comment by mgetJane** [comment]
> seems like `ent:SetSaveValue("m_iTextureFrameIndex", value)` works, i guess that makes this unnecessary

something to note though is that it doesn't update for clients immediately this way (takes a few seconds) unless you do something like `ent:SetModel(ent:GetModel())` to immediately update the entity (doesn't seem like there's a more elegant way to do that)

**Comment by Kefta** [comment]
You could request m_iTextureFrameInfo to be added as a clientside keyfield so that you could set it shared.
