### ISSUE TITLE
TTT request

### ISSUE THREAD

**Issue by Tiagoquix** [Facepunch/garrysmod-requests#1972]
### Details
This is not exactly a request for TTT, but possibly a good suggestion.

My idea is to make the TTT translation files be imported and adapted to the Garry's Mod translations present in Crowdin, so that possibly new languages are added to the gamemode.

I will mention the author of the gamemode to get their opinion.

**Comment by robotboy655** [comment]
I am not sure about it being included in the official Crowding project for GMod, it being a community gamemode.

TTT requests/bug reports do not belong here.
