### ISSUE TITLE
Add Lua Function Entity:GetSequenceCycleGroundSpeed()

### ISSUE THREAD

**Issue by Goldermor** [Facepunch/garrysmod-requests#1974]
### Details
Same as Entity:GetSequenceGroundSpeed(), but you can set from which point of the cycle you need to get the speed.
This is very useful in working with motion that based on animations.

I hope it won't be difficult for you, cuz HLMV can already do this

**Comment by robotboy655** [comment]
Added as optional arguments.

Related? https://github.com/Facepunch/garrysmod-requests/issues/1314
