### ISSUE TITLE
[Select All In This Page] Button in the Addons Menu

### ISSUE THREAD

**Issue by arroyoquiel** [Facepunch/garrysmod-requests#1983]
As a player, trying to check which addon is lagging my game is a hard task.

When I need to do this task, what I do is this manual function/algorithm (I don't know the word): Turn on 1/2 of my addons, check if the addon that lags my game is in that half, if not, do it with the other half, then keep dividing until I discover which addon is causing trouble.

Basically I do this (🟩 enabled addon (🟪 if unchanged) ,⬛ disabled addon (🟫 if unchanged), 🟦disabled addon by "Disable All" button, 🟥 enabled bad addon, 🟨 disabled bad addon)

Figure (a)
1)🟩🟩🟩🟩🟩🟩🟦🟦🟦🟦🟨🟦 No bad addon in this half
2)🟦🟦🟦🟦🟦🟦🟩🟩🟩🟩🟥🟩 Found bad addon in this half
3)🟦🟦🟦🟦🟦🟦🟪🟪🟪⬛🟨⬛ No bad addon in this half
4)🟦🟦🟦🟦🟦🟦⬛⬛⬛🟩🟥🟩 Found bad addon in this half
5)🟦🟦🟦🟦🟦🟦🟫🟫🟫🟪🟥⬛ Found bad addon in this half
6)🟦🟦🟦🟦🟦🟦🟫🟫🟫⬛🟥🟫 Found the bad addon -> Uninstall

Now pretend that each square equals 24 addons (a page).

Clicking the checkboxes one by one is just a so slow and tedious process, they are very small and most people don't have an Osu-level of aim to do this task fast.
If I could select all the 24 addons of a page with just 1 click it would help tremendously anyone that has this problem.
This could save approximately 18-24 seconds per page of clicking. 

On average I take 19 seconds to click all the addons of a page, my game takes 40 seconds to load, it takes 2 seconds of changing each page and 3 seconds to leave the addon menu to clicking the "Start Game" button.
If I do the task in Figure (a) manually it would take:
`((green squares*clicking time)+(black squares*clicking time)+(rows*loading time)+(seconds of changing each page*green and black squares)+(seconds to leave the addon menu*rows))`
`((13*19)+(7*19)+(6*40)+(2*20)+(3*6)) = 678 seconds (11.3 minutes)`

If we change the clicking time to 1 second because you can click all addons of a page with a single click it should take
`((13*1)+(7*1)+(6*40)+(2*20)+(3*6)) = 318 seconds (5.3 minutes)`

It would make the process 47% faster (for me).

I think that an intuitive way to implement this could be:
1) Double clicking the dot of the page
![image](https://user-images.githubusercontent.com/81461845/175456476-5daa291d-1702-4c95-86e4-5d1234c00f0c.png)

2) Pressing the "Select All" button with Alt, Shift or Ctrl + Left Click or just do a Right Click on it.
![image](https://user-images.githubusercontent.com/81461845/175456647-d99e759d-1905-46cf-9191-46f1d1c57a11.png)

Pls don't laugh I really need this in Garry's Mod because I usually play with ~240 addons.

**Comment by robotboy655** [comment]
Added on dev beta under "Select All" button.
