### ISSUE TITLE
Add surface.GetTextureName( number id ) function 

### ISSUE THREAD

**Issue by URAKOLOUY5** [Facepunch/garrysmod-requests#1986]
### Details
Opposite version for `GetTextureID( string name/path )`, gets name from texture's ID

### Issue
`weapon.WepSelectIcon` returns texture's ID not path or name, I want to do black and white texture and increase brightness, to draw it in hud, but came into problem where `weapon.WepSelectIcon` is not ITexture, and cant set it into "pp/colour".

**Comment by robotboy655** [comment]
Added surface.GetTextureNameFromID( id )

**Comment by URAKOLOUY5** [comment]
This change not present in `dev` brunch
> attempt to call field 'GetTextureNameFromID' (a nil value)
