### ISSUE TITLE
DNumSlider/DSlider pop up removal function

### ISSUE THREAD

**Issue by pparadoxx** [Facepunch/garrysmod-requests#1987]
### Details
So, I was making a menu for an addon and I needed to remove this:
![image](https://user-images.githubusercontent.com/63322972/177049267-9b2b0154-79ee-4f87-8817-f09e472d3ca0.png)

I was looking for any way to do this and I couldn't find one. I went ahead and printed some of the sub sub children and found the scratch but it just throws errors if I remove it. If I don't remove it and do some trickery it'll just be annoying with the button that activates the scratch (it covers a checkbox for me).

What I'm asking is just a simple enable/disable on the scratch which would also disable the button that is around the slider (the button that activates the scratch).

**Comment by robotboy655** [comment]
```
DNumSlider.Scratch:SetEnabled( false )
```
or
```
DNumSlider.Scratch:SetVisible( false )
```
?

Only gotta worry about calling those functions on DNumSlider itself resetting the number scratch
