### ISSUE TITLE
An ability to unsubscribe subscribed Dupes in-game

### ISSUE THREAD

**Issue by ShinexWipex** [Facepunch/garrysmod-requests#1992]
As the title says - it would be more convenient, because it would be less of a hassle than going to the Workshop and manually unsubscribing to each of the Dupe separately. Also a function of "Unsubscribe to all" within the Workshop would be useful in some areas too (with safety precautions to avoid accidental clicks), either for dupes separately or addons or both.

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/178166280-cb83e2e2-8c0f-4c18-8d5d-1ad0ab082d7a.png)

The button is already there.

It will not be added to spawnmenu because then someone can just unsubscribe you from all your addons.,

**Comment by ShinexWipex** [comment]
> ![image](https://user-images.githubusercontent.com/3299036/178166280-cb83e2e2-8c0f-4c18-8d5d-1ad0ab082d7a.png)
> 
> The button is already there.
> 
> It will not be added to spawnmenu because then someone can just unsubscribe you from all your addons.,

Got it. Thank you.
