### ISSUE TITLE
Add a "duplicator.GetEntityModifier" or something similar

### ISSUE THREAD

**Issue by Andrew-Eathan** [Facepunch/garrysmod-requests#1993]
### Details
like duplicator.StoreEntityModifier, but you can get the data you stored (or nil), i don't think there's anything more special to it than this
honestly somewhat surprised this doesn't exist by now, it would be useful to know if an entity has a certain modifier

**Comment by robotboy655** [comment]
You are not really meant to directly access that stuff, but you can via `Entity.EntityMods[ Type ]`.

You are supposed to apply your modifiers via callback you give to https://wiki.facepunch.com/gmod/duplicator.RegisterEntityModifier

**Comment by Andrew-Eathan** [comment]
Thanks, i just needed to check if the modifier exists, the actual data and apply function is mostly scondary to me
