### ISSUE TITLE
CS:GO shaders integration

### ISSUE THREAD

**Issue by Goldermor** [Facepunch/garrysmod-requests#2000]
Is there any chance that you will be able to integrate CS:GO shaders to gmod, with all their fixes, new lighting, CSM, and other features. Even maybe update particle system to CS:GO state.
This is what the game lacks to become much better, and at the same time maintain its greatness for a long time. I know that there is already s&box in dev, I don't think gmod will retire, but the game really needs it. it 's already 2022, who can still use dx8 that much? even the cheapest computers in the present are already using dx9 for that.

This is what I think about for days, weeks, but I do not know if it is worth having hope. I know that I'm not the only one, and many people would like to see new shaders at least from csgo.

just tell us - is it possible?

**Comment by SpiffyJUNIOR** [comment]
bruh we have been asking for this for years it ain't happening

**Comment by Goldermor** [comment]
> bruh we have been asking for this for years it ain't happening 💀

hope dies last

**Comment by Andrew-Eathan** [comment]
> > bruh we have been asking for this for years it ain't happening 💀
> 
> hope dies last

and die it shall, in the hands of gmod devs
:trollface:

**Comment by robotboy655** [comment]
This request is too vague. Closing in favor of more specific requests.

**Comment by Andrew-Eathan** [comment]
yep predicted it
