### ISSUE TITLE
Replace NPCs' sentence files

### ISSUE THREAD

**Issue by Nitestokeh** [Facepunch/garrysmod-requests#2003]
### Details
There's [PrecacheSentenceFile](https://wiki.facepunch.com/gmod/Global.PrecacheSentenceFile) function available but it has no practical use since you can't assign custom sentences anywhere. Adding a function to override NPC's sentence file completely would help a lot
Maybe something for scripts/talker too to override citizen lines and the likes

**Comment by robotboy655** [comment]
https://wiki.facepunch.com/gmod/GM:EntityEmitSound is now called for sentences (on dev/x86-64 betas), so you should be able to achieve what you want now.
