### ISSUE TITLE
OnLeaveGround hook for players

### ISSUE THREAD

**Issue by ZH-Hristov** [Facepunch/garrysmod-requests#2019]
A hook that runs when a player's feet leave the ground, similar to [NEXTBOT:OnLeaveGround](https://wiki.facepunch.com/gmod/GM:OnPlayerHitGround) could be useful in my opinion.

There's this animation oversight where players will not play the jump/fall anim unless the player specifically jumped, even if they fall off a ledge without jumping. This results in the player "running" on air. This hook could probably be used as a hacky way to fix that if it can't be fixed on the engine side.

Could also be used to detect jumping overall. Maybe if possible pass whether the player left the ground due to a jump when the hook runs?

**Comment by Kefta** [comment]
Just check between the Move and FinishMove hooks if the ground entity has changed to NULL - a hook for this is unnecessary.

**Comment by ZH-Hristov** [comment]
> > This results in the player "running" on air. This hook could probably be used as a hacky way to fix that if it can't be fixed on the engine side.
> 
> This is fully intentional for HL2:DM and GMod - the Lua anim impl takes great care to maintain this behaviour.

Why maintain that behaviour though? It just looks bad and unintentional.

And I still think a simple single hook for this would be better than having to add 2 hooks to check if the player did leave the ground. It'd also be consistent with the NextBot hook.

**Comment by Kefta** [comment]
> Why maintain that behaviour though? It just looks bad and unintentional.

Because it's intentional and looks good in the same way a very slow swimming animation is played when you fly thru the air.

If you want a single hook, you can manually hook.Call one from FinishMove then never think about it again. If anything we need less hook calls from the engine, not more utility ones that serve single purposes.

**Comment by robotboy655** [comment]
I agree with @Kefta
