### ISSUE TITLE
Portal 2 sound files

### ISSUE THREAD

**Issue by ZehMatt** [Facepunch/garrysmod-requests#202]
It would be nice to get them to play, they are named as .wav files while they are actually mp3 files so the Engine decides to open them as wav files and fails and even flags them as missing/bad.

**Comment by imp0se** [comment]
I used a Portal 2 sound in one of my Garry's Mod maps, and it works fine.

**Comment by robotboy655** [comment]
"Fixed", and now we know why they did it:
![The more you know](https://github.com/Facepunch/garrysmod-requests/assets/3299036/25b0f44a-a14b-43b8-8796-23ed830a7cbf)
