### ISSUE TITLE
Make util.ImpactTrace(...) callable from Lua

### ISSUE THREAD

**Issue by MrGeRoI** [Facepunch/garrysmod-requests#2020]
It is useful to create a impact effect in order to then process it through `ENTITY:DoImpactEffect(...)` or through the native `UTIL_ImpactTrace` function of the engine, rather than calling `ENTITY:FireBullets(...)` (it is not guaranteed that they will get where we want)
This can be used to make Lua melee weapons for example

**Comment by robotboy655** [comment]
You can recrate the impact effect via `util.Effect` and `Impact` effect.

https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/game/shared/baseentity_shared.cpp#L665-L695
