### ISSUE TITLE
Function to push a string to the closed-caption box

### ISSUE THREAD

**Issue by Vuthakral** [Facepunch/garrysmod-requests#2024]
### Details
Currently to the best of my ability for trying to find something, there appears to be no way to add or push a string for closed captions to Garry's Mod, and after looking into the functionality in the game itself it seems that existing CC's in the game are tied to a resource textfile. Due to this limitation, I ask would it be possible to have a function which can push a string value into the CC box? Maybe a function something like `SendCloseCaption(<string>, <color>, <bool> italic, <bool> bold, <bool> not dialogue)`.

Explanation of each for the sake of being clear:
- `string` : The string the user wants to be pushed into the CC box
- `color` : The colour of the text to appear
- `italic` : Whether or not it should be italicized
- `bold` : Whether or not it should be boldfaced
- `not dialogue` : Whether this request should be classified as dialogue or not. Dialogue has its own distinction in the close caption settings. The setting "Close Captions" makes non-dialogue CC appear as well, i.e. "[Cant use]"

**Comment by robotboy655** [comment]
Added `gui.AddCaption( text, duration, fromPlayer )`
