### ISSUE TITLE
Make "givecurrentammo" command give secondary ammo too

### ISSUE THREAD

**Issue by Nitestokeh** [Facepunch/garrysmod-requests#2026]
Self-explanatory, should make for easier SWEP debugging

**Comment by Kefta** [comment]
https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/src_main/game/server/player.cpp#L186-L191 
![lmao](https://user-images.githubusercontent.com/4593679/197585856-9f54f291-1d2d-4ccf-90e8-2022d5dea2d7.png)

**Comment by Nitestokeh** [comment]
> https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/src_main/game/server/player.cpp#L186-L191 ![lmao](https://user-images.githubusercontent.com/4593679/197585856-9f54f291-1d2d-4ccf-90e8-2022d5dea2d7.png)

Yes, but we can have it give ammo at 0 too :(

**Comment by GrandpaTroll** [comment]
Or just make a server concommand to do that for you.

**Comment by robotboy655** [comment]
Don't see a reason not to change this, so there.
