### ISSUE TITLE
Add detailed explanation of "Steam Downloads" section in "Addon failed to download" message from Problems tab

### ISSUE THREAD

**Issue by KirbyJoe** [Facepunch/garrysmod-requests#2030]
### Details
I guess we need a better explanation of where the "Steam Downloads" section is on the "Addon failed to download" message.

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/199503469-91eca4af-293d-4a7e-ad87-5ad3e29cd094.png)
![image](https://user-images.githubusercontent.com/3299036/199503507-7634508c-3e21-4971-8b19-0656a14ff423.png)

Do we?

**Comment by KirbyJoe** [comment]
Yes. I think some users don't check the section often...

**Comment by GrandpaTroll** [comment]
Why should I have to get out of gmod just to see the problem?
Of course he's probably asking in the addon section, instead of saying Failed to download, append a simple reason why.
But of course steam has alot of error reason and theres no point in trying to add all of the reasons into it.

**Comment by robotboy655** [comment]
> Yes. I think some users don't check the section often...

Which is why it tells players to check it in case there are some errors that we cannot solve/control from the game.

I do not feel like any further details are necessary, you interact with that menu when downloading games, it's not a stretch to expect players to know where to find it.
