### ISSUE TITLE
entity:LightLevel function

### ISSUE THREAD

**Issue by VaasKahnGrim** [Facepunch/garrysmod-requests#2035]
##Details:
A function similar to entity:WaterLevel() but used to get the current light level of the entity between 0 and 255. 0 being no lighting at all, 255 being fully lit.

##Usecases:
Determining when a player or entity has entered a dark area on the map and transitioning between darker and lighter areas of a map. Can be useful for stuff such as night vision, controling the use of Dynamic Lights, handling player sanity in a gamemode(allowing devs to make game mechanics similar to the way sanity works in Amnesia when the player is in the dark or light), and possibly more use cases I've not thought of yet.

**Comment by robotboy655** [comment]
https://wiki.facepunch.com/gmod/render.ComputeLighting

**Comment by VaasKahnGrim** [comment]
These only work inside rendering hooks if I'm not mistaken. I don't think it would work outside of that in something such as a think hook or net.Receive

**Comment by VaasKahnGrim** [comment]
upon testing in a think hook it works(did not expect it to work but it did. just not entirely the same with the numbers)
