### ISSUE TITLE
Change scr_centertime default value to 5

### ISSUE THREAD

**Issue by Tiagoquix** [Facepunch/garrysmod-requests#2040]
The current default value is 2. This cvar controls the time that center text is displayed when used by community server admins. I think it's pretty useful on the TTT server that I play on, since a center text message is used to indicate if the round has reached 3:30 (time), allowing the use of some Detective orders and weapons.

For reference, TF2's default value is 5.

**Comment by robotboy655** [comment]
Surely you can code this trivial thing yourself and make it look much better than the default HL2DM text on screen?

**Comment by XAYRGA** [comment]
> I agree with you, but I think this adjustment is a nice change for addons that use this cvar's value in one way or another.
> 
> P.S.: I'm not a developer, just to clarify.

This CVAR is not blacklisted. Literally just put 

`RunConsoleCommand("scr_centertime","7")`

In the lua/autorun/client/whatever.lua of your server :v

**Comment by r47orr** [comment]
> > I agree with you, but I think this adjustment is a nice change for addons that use this cvar's value in one way or another.
> > P.S.: I'm not a developer, just to clarify.
> 
> This CVAR is not blacklisted. Literally just put
> 
> `RunConsoleCommand("scr_centertime","7")`
> 
> In the lua/autorun/client/whatever.lua of your server :v

It seems not to work properly using the code below for some reason. Might be a bug?

```
hook.Add("PlayerInitialSpawn", "TTTEnforcePlayerScreenMessageTime", function(ply) 
    ply:ConCommand("scr_centertime", "5")
end)
```


You can even print something to certify it was executed, but doesn't seem to work, since checking the cvar on the game shows it as the default value

**Comment by robotboy655** [comment]
Done
