### ISSUE TITLE
Implement a way to automatically delete other players' spray files on shutdown

### ISSUE THREAD

**Issue by Tiagoquix** [Facepunch/garrysmod-requests#2041]
Such as L4D2 and [TF2](https://www.teamfortress.com/post.php?id=89183)¹, I think Garry's Mod should also have an option to automatically delete other players' spray files on shutdown (being enabled by default).

Basically, delete "materials\temp" and "download\user_custom" on shutdown.

The two main advantages are:

- Delete unnecessary files stored on disk and free up space.
- Remove possible illegal images from users' hard drives. This was used by TF2 bots on community servers to spread racist images and CP².

¹ `Added ConVar "tf_delete_temp_files" to control custom player sprays and other temp files being deleted on shutdown`

² https://steamcommunity.com/app/440/discussions/0/3047235309978419614/

**Comment by Combine900** [comment]
Sounds great 👍

**Comment by robotboy655** [comment]
This is kinda lame considering the data folder exists, but I have made those 2 folders auto wipe on game startup/exit.
