### ISSUE TITLE
Add physenv.GetSimulationTime()

### ISSUE THREAD

**Issue by Python1320** [Facepunch/garrysmod-requests#2042]
### Details
Add `physenv.GetSimulationTime()` that returns the last result of [simRealTime 
](https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/game/server/physics.cpp#L1763)

There is no way to read how long physics takes compared to the rest of the frame except by setting phys_speeds to 1 and parsing the emitted message or by hooking [`physenv.Simulate`](https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/game/server/physics.cpp#L1712) 

```c++
...

// extern float g_simRealTime; // Also publish to C modules?

float g_simRealTime; // https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/physics.cpp#L73

...

void PhysFrame( float deltaTime )
{
...
	
	//if ( bProfile ) // GMOD: always calculate simRealTime for physenv.GetSimulationTime()
	//{
		simRealTime = engine->Time();
	//}

...

	simRealTime = engine->Time() - simRealTime; // add here
	g_simRealTime = simRealTime;

	if ( bProfile )
	{
		// simRealTime = engine->Time() - simRealTime; // remove from here

...

LL_Function( physenv, GetSimulationTime )
{
    Push_Number( g_simRealTime );
    return 1;
}
```

**Comment by robotboy655** [comment]
Added `physenv.GetLastSimulationTime` for the next update.
