### ISSUE TITLE
OnHookAdded Hook

### ISSUE THREAD

**Issue by ZH-Hristov** [Facepunch/garrysmod-requests#2046]
I'm writing a library for ordered/prioritised CalcView hooks, and I was wondering if we could get a hook that runs when a hook is added with hook.Add, so that I could detour (optional with CVar) the hooks to the ordered system.

It would also be nice if returning false in this hook stopped the to-be-added hook to not be added to the default table.

**Comment by robotboy655** [comment]
No. You can override/detour hook.Add if you need to.
