### ISSUE TITLE
Portal 2 Shaders?

### ISSUE THREAD

**Issue by Dogo20** [Facepunch/garrysmod-requests#2055]
So i know that Portal 2 maps will be broken due to V-Script but could it be _somewhat_ possible to at least have the lighting work? Bc every time i go into a map with mostly white surfaces (Like Triple Lazer) I get flash-banged.

**Comment by robotboy655** [comment]
It's not the lightmaps, its the shaders.

Partially related to https://github.com/Facepunch/garrysmod-requests/issues/2000

**Comment by Dogo20** [comment]
Oh. well is it still possible? I would love to see it in the next update / beta branch build
