### ISSUE TITLE
Permission 'friends'?

### ISSUE THREAD

**Issue by zohart75** [Facepunch/garrysmod-requests#2060]
### Details
We need 'friends' permission, like RequestPermission("voicechat") or permissions.AskToConnect(...). It's not should be that hard.
After asking this permission we could get a list of user's friends in Steam. That should be very helpful for developers)

**Comment by pparadoxx** [comment]
> ### Details
> We need 'friends' permission, like RequestPermission("voicechat") or permissions.AskToConnect(...). It's not should be that hard. After asking this permission we could get a list of user's friends in Steam. That should be very helpful for developers)

I assume you mean be able to connect without going through the server? Thats a major security risk.

And if you want to go through server theres already libraries out there for that (infact I have some).

**Comment by garryspins** [comment]
This would be a good addition although this can be done without the users permission, via [This](https://developer.valvesoftware.com/wiki/Steam_Web_API#GetFriendList_.28v0001.29), I do think it would be good to have an interface in-game for this though

**Comment by robotboy655** [comment]
Why do you need the friend list anyway?

**Comment by zohart75** [comment]
For example in DarkRP, to give your Steam-friends access to keypads; in sandbox - give your friends an access to your props. I hope that this is a good reason to make it)

**Comment by robotboy655** [comment]
https://wiki.facepunch.com/gmod/Player:GetFriendStatus This fulfils that.

**Comment by zohart75** [comment]
OK, didn't knew that, but this permission should give the lua information about users friends list, to manipulate with it. Give some things even if the player is offline or something, for example - sleeping bags from Rust that you can give to your friends while he's loading.

**Comment by pparadoxx** [comment]
> OK, didn't knew that, but this permission should give the lua information about users friends list, to manipulate with it. Give some things even if the player is offline or something, for example - sleeping bags from Rust that you can give to your friends while he's loading.


Define "manipulate with it"; you can already do this via indexing steamids. Though I do get what you mean, something like the invite friends list from other steam games where it pops up with a list (in this case you'd make the list) of all of your friends and  you can click on them.

**Comment by zohart75** [comment]
Cool idea, but that's kinda not what I mentioned. I was telling about a function that will return players friends as a lua table even if they are offline or even weren't on the server

**Comment by zohart75** [comment]
Cool idea, but that's kinda not what I mentioned. I was talking about a function that will return players friends as a lua table even if they are offline or even weren't on the server

**Comment by garryspins** [comment]
You wouldn't be able to use it on the client anyways, the interface would be on the server, just use the api i sent

**Comment by pparadoxx** [comment]
> Cool idea, but that's kinda not what I mentioned. I was talking about a function that will return players friends as a lua table even if they are offline or even weren't on the server

That is what I was referring to. The way you'd get that is the same API callback that the friend invite system uses.

See [ISteamFriends](https://partner.steamgames.com/doc/api/ISteamFriends)

**Comment by zohart75** [comment]
> You wouldn't be able to use it on the client anyways, the interface would be on the server, just use the api i sent

Why wouldn't I be able to use it client-side? I ask to add this permission so it will work on client. I need it client-sided

**Comment by zohart75** [comment]
> > Cool idea, but that's kinda not what I mentioned. I was talking about a function that will return players friends as a lua table even if they are offline or even weren't on the server
> 
> That is what I was referring to. The way you'd get that is the same API callback that the friend invite system uses.
> 
> See [ISteamFriends](https://partner.steamgames.com/doc/api/ISteamFriends)

Oh, OK then.

**Comment by Aws0mee** [comment]
> Cool idea, but that's kinda not what I mentioned. I was talking about a function that will return players friends as a lua table even if they are offline or even weren't on the server

Using [ISteamFriends](https://partner.steamgames.com/doc/api/ISteamFriends) was already mentioned, also you could simply store a player's friends in a database or text file and read from it if they go offline

**Comment by robotboy655** [comment]
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/645
