### ISSUE TITLE
ProtectedCall with arguments 

### ISSUE THREAD

**Issue by pparadoxx** [Facepunch/garrysmod-requests#2061]
### Details
Something like FuncCall(func, ...)  that would allow you to call a function (and still have it throw errors unlike pcall and xpcall) with arguments.

**Comment by garryspins** [comment]
you mean like this?
```lua
function FuncCall(fn, ...)
    fn(...)
end
```

**Comment by garryspins** [comment]
No idea why you would need this when you can literally just.... call the function

**Comment by garryspins** [comment]
I see, misunderstood what was being asked, yea that would be a nice addition! ProtectedCall is a fairly rarely used function in the first place, extra arguments could probably be added just fine to ProtectedCall, no need for a new function imo

**Comment by pparadoxx** [comment]
> He's asking for the same syntax as pcall because otherwise, you'd have to create a function at runtime every time ProtectedCall is ran so that the arguments can be binded to the function.

Yeah that was what I asking about; sorry for the bad description I guess.

**Comment by brandonsturgeon** [comment]
> I see, misunderstood what was being asked, yea that would be a nice addition! ProtectedCall is a fairly rarely used function in the first place, extra arguments could probably be added just fine to ProtectedCall, no need for a new function imo

In my opinion, ProtectedCall is often a better choice than pcall/xpcall - often times you want to run your function in an important hook without some stray logic error breaking literally everything else in the hook chain.

Plus, default error handling is such a good feature.

For me the pcalls only make sense if there's an error that is outside of your control that you need to detect and respond to.

ProtectedCall with varargs would be 👌 💯

**Comment by robotboy655** [comment]
Should work now.
