### ISSUE TITLE
Add trigger_serverragdoll to FGD

### ISSUE THREAD

**Issue by Roachdaripper** [Facepunch/garrysmod-requests#2063]
### Details
https://developer.valvesoftware.com/wiki/Trigger_serverragdoll

this entity is present in the branch of source engine that L4D/TF2 uses (though its apparently bugged in L4D?) anyway this would be a really cool feature that would be great for gmod mappers

**Comment by robotboy655** [comment]
It was always in the `.fgd` files, since at least 2014.

![image](https://github.com/user-attachments/assets/f35eb8c2-7560-4169-acc8-5709218443ab)
