### ISSUE TITLE
Lua Hook that provides Environment/Point Entities when they are created

### ISSUE THREAD

**Issue by gamerguy7620** [Facepunch/garrysmod-requests#2069]
### Details

Can you make [Environment Entities](https://developer.valvesoftware.com/wiki/List_of_entities#Environment_Entities)/[Point Entities](https://developer.valvesoftware.com/wiki/Point_entity), in my case specifically [env_splash](https://developer.valvesoftware.com/wiki/Env_splash), call the [GM:OnEntityCreated](https://wiki.facepunch.com/gmod/GM:OnEntityCreated) or alike, when they are created, so it can be accessed/prevented/modified with LUA? Since I can not find a hook that does.

-----
Hi
I am a server owner who is trying to find a way to stop [water splashes](https://developer.valvesoftware.com/wiki/Env_splash) (primarily the effect) from playing or being created.
I have used [this](https://developer.valvesoftware.com/wiki/Point_entity) and [this](https://developer.valvesoftware.com/wiki/Env_splash) as a guide. And looked around for hooks like [GM:OnEntityCreated](https://wiki.facepunch.com/gmod/GM:OnEntityCreated), [GM:NetworkEntityCreated](https://wiki.facepunch.com/gmod/GM:NetworkEntityCreated) and [GM:AcceptInput](https://wiki.facepunch.com/gmod/GM:AcceptInput) but none seems to give the entity i am looking for.
I have no idea if this already is a feature that I just cannot find?

**Comment by robotboy655** [comment]
They do. The water splashes you are referring to (from shots and physics entities entering/exiting water) are not entities.
