### ISSUE TITLE
util.IsOBBIntersectingOBB onto Wiki

### ISSUE THREAD

**Issue by pparadoxx** [Facepunch/garrysmod-requests#2073]
### Details
An already made (and useful) function that doesn't have a spot in the wiki as of right now and should probably have one.

![image](https://user-images.githubusercontent.com/63322972/230729582-7a67a0c9-1bd1-4eba-80eb-873ec24d56a7.png)

**Comment by robotboy655** [comment]
You can make wiki pages yourself!


Anyway, I made it for you: 
https://wiki.facepunch.com/gmod/util.IsOBBIntersectingOBB

**Comment by Kefta** [comment]
Why is this only available clientside?
