### ISSUE TITLE
infinite ammo cvar

### ISSUE THREAD

**Issue by Combine900** [Facepunch/garrysmod-requests#2075]
Hey, i dont think that garrysmod ever get updated too the engine branch of l4d2 or csgo, so i might ask for a feature request.

Is there a chance that we can add the infinite ammo cvar too garrysmod? That would make the addons for that obsolete.

I searched for the code stuff inside the "leaked" csgo version. I know that it isnt just about copy paste, but would be cool too see it in gmod. :)
ConVar & Code functions
cstrike15_src/game/shared/baseplayer_shared.cpp
https://github.com/perilouswithadollarsign/cstrike15_src/blob/master/game/shared/baseplayer_shared.cpp
Line 144, 362, 363

cstrike15_src/game/shared/basecombatweapon_shared.cpp
https://github.com/perilouswithadollarsign/cstrike15_src/blob/master/game/shared/basecombatweapon_shared.cpp
Line 3490, 3491

cstrike15_src/game/shared/basecombatcharacter_shared.cpp
https://github.com/perilouswithadollarsign/cstrike15_src/blob/master/game/shared/basecombatcharacter_shared.cpp
Line 138, 139, 142, 143, 189, 190

cstrike15_src/game/shared/ammodef.cpp
https://github.com/perilouswithadollarsign/cstrike15_src/blob/master/game/shared/ammodef.cpp
Line 134

**Comment by robotboy655** [comment]
There isn't a way to make this work with all addon guns, and as you pointed out, already possible with mods.
