### ISSUE TITLE
Include Directory

### ISSUE THREAD

**Issue by ryanoutcome** [Facepunch/garrysmod-requests#2079]
### Details
Add another argument to include that allows you to include a directory. Something like:

`include( string fileName, boolean directoryInclude )`

When you use the second argument it will include the directory listed in the first argument. This would prevent errors/issues with older addons that may be looping through tables and including things (file.Find for example).

Examples:

`include( "addonExample/modules", true )`
`include( "addonExample/test.lua", false )`
`include( "addonExample/", true )`

**Comment by robotboy655** [comment]
I am really confused as to what "errors/issues" this is meant to solve, and why the current methods of doing this are apparently not good enough anymore.

**Comment by ryanoutcome** [comment]
> I am really confused as to what "errors/issues" this is meant to solve, and why the current methods of doing this are apparently not good enough anymore.

What do you mean? You'd make it an argument so that past addons that loop through directories by default aren't going to get errors when they loop through the directory and include more directories. 

As for why have include directory as a feature, well, instead of using file.Find multiple times throughout modular code you could simply use a couple includes and you'd have your modular code already done for you without the need for several file.Finds, for loops, and includes.

**Comment by garryspins** [comment]
I don't like this approach, there's nothing wrong with how things are done now and having a builtin for it takes away a lot of the extensibility that comes from writing your own.

**Comment by Kefta** [comment]
Load time is not performance sensitive, I don't see a problem with using file.Find.
