### ISSUE TITLE
SetAmmoMax()

### ISSUE THREAD

**Issue by vcf55** [Facepunch/garrysmod-requests#2080]
A method for manually overriding the maximum amount of ammo which can be carried by players, it would have arguments for the ammo type's ID and the new maximum carry amount.

Player:SetAmmoMax( number id, number carry max ) or game.SetAmmoMax( number id, number carry max ) depending on which would be better, this would also override gmod_maxammo (Unless its set to 0).

**Comment by Kefta** [comment]
This can be achieved with a PlayerAmmoChanged hook; I don't see the benefit of adding another networked player class variable for a semi-niche, Lua-implementable feature.

**Comment by Kefta** [comment]
PlayerCanPickupItem can be used to block ammo ent pickups, and I'm sure item_dynamic_resupply can either be externally influenced or just rewritten in Lua to take the hook into account - I know this latter solution is ideal but I do not see one entity used in the HL2 campaign as justification to add a new networked player variable that affects every server.

**Comment by vcf55** [comment]
Understandable, I'll look more into it, I'm not an expert on this, thanks for taking the time to answer chief.
