### ISSUE TITLE
Allow the usage of ConCommand on player bots

### ISSUE THREAD

**Issue by T-Rizzle12** [Facepunch/garrysmod-requests#2083]
### Details
I have been messing around with player nextbots and read on the wiki that ConCommand doesn’t work on them. It would be nice to fake client commands on bots since it would allow mod creators to set client cvars on bots. I know it’s possible to do this since Valve does it with their bots.

**Comment by robotboy655** [comment]
I don't know what you are trying to achieve, or where you get your information about "I know it’s possible to do this since Valve does it with their bots.", but no. The clientside console commands/variables are ran/stored on your Garry's Mod client. Bots do not have a game client running each, so they cannot have clientside convars/concommands.

If you want to store data per bot, you can just do that.

**Comment by T-Rizzle12** [comment]
> I don't know what you are trying to achieve, or where you get your information about "I know it’s possible to do this since Valve does it with their bots.", but no. The clientside console commands/variables are ran/stored on your Garry's Mod client. Bots do not have a game client running each, so they cannot have clientside convars/concommands.
> 
> If you want to store data per bot, you can just do that.

In cs_bot_buy.cpp when bots decide to buy a weapon they use ClientCommand to make the purchase, on line 653 and 689. I’m currently looking for the code used itself.

**Comment by robotboy655** [comment]
All that piece of code is used to capture the console commands aimed at a bot, but as far as I can tell, they are never used anywhere (The `m_args` variable).

What the CS bots do is equivalent to this in GMod:
```lua

local meta = FindMetaTable( "Player" )
local SendConCommand = meta.ConCommand
function meta:ConCommand( command, bSkipQueue )

		if ( !self:IsBot() ) then
			SendConCommand( self, command )
		else
			if (command == "buy weapon_mp5" ) then
			end
		end
end
```

**Comment by robotboy655** [comment]
To be clear, you are allowed to use `Player.ConCommand` on bots. It's not blocked or anything like that. It will just do nothing because it makes no sense.

**Comment by T-Rizzle12** [comment]
I did a bit more digging and found this being called when CBot< PlayerType >::ClientCommand was called.
It takes two parameters, a player edict and the command itself.
engine->ClientCommand( pClient, "cd pause\n");

Now if this still isn't possible or still makes no sense to you. Is it possible to add SetFakeClientConVarValue instead. Since both L4D2 and TF2 have it accessible in VScript?
