### ISSUE TITLE
Restore Creation of Ladders during NavMesh Generation

### ISSUE THREAD

**Issue by T-Rizzle12** [Facepunch/garrysmod-requests#2085]
### Details
I noticed when generating navmesh for CS:S, CS:GO, and L4D2 that they automatically create CNavLadder areas during generation. It would also generate navmesh on the top and the bottom parts of the ladders it created said CNavLadders. It would not only save a lot of time noCliping around the map manually creating ladder areas, but it would reduce the chance of certain parts of the map not having any navmesh.

**Comment by robotboy655** [comment]
Our navmesh generator is identical to that of CS:S/CSGO, one key difference is that GMod does not have `func_simpleladder` entity which is what those games use to generate the ladders.

**Comment by T-Rizzle12** [comment]
Sorry about the late response, Is it possible to change the NavMesh to check for `func_ladder` instead?

**Comment by robotboy655** [comment]
Unfortunately now, as func_ladder doesn't actually exist in-game when the nav generation happens.

**Comment by T-Rizzle12** [comment]
@robotboy655 
I have done some more looking into CS:GO Source Code and I was wondering if you could make the navmesh generator detect CONTENTS_LADDER and automatically build ladders during the sampling phase of the generation. It would also be nice if it could also create CNavLadder areas on func_useableladder as suggested in #1109.

**Comment by T-Rizzle12** [comment]
Another possible fix I have been thinking about is can you change `func_ladder` to exist in-game?
