### ISSUE TITLE
surface.GetTextPos

### ISSUE THREAD

**Issue by Be1zebub** [Facepunch/garrysmod-requests#2087]
[surface.DrawText](https://wiki.facepunch.com/gmod/surface.DrawText) moves text position  
![image](https://github.com/Facepunch/garrysmod-requests/assets/34854689/f2912440-83cd-4e15-8d86-fd35228cb894)  
but there is no way to get current text position value  
surface.GetTextPos would be useful in other, more complex cases

**Comment by robotboy655** [comment]
Added on `dev` and for future update.
