### ISSUE TITLE
Add surface.StopSound()

### ISSUE THREAD

**Issue by LCon-tech** [Facepunch/garrysmod-requests#2088]
### Details
Add an ability to stop a sound played from surface.PlaySound() - I request the function surface.StopSound().

**Comment by garryspins** [comment]
Use `https://wiki.facepunch.com/gmod/sound.PlayFile` or another function that gives you an IGModAudioChannel instead, redundant addition imo

**Comment by LCon-tech** [comment]
> Use [sound.PlayFile](https://wiki.facepunch.com/gmod/sound.PlayFile) or another function that gives you an `IGModAudioChannel` instead, redundant addition imo

Interesting, thanks for this information.
