### ISSUE TITLE
Vector:__div support vec / vec

### ISSUE THREAD

**Issue by Be1zebub** [Facepunch/garrysmod-requests#2091]
Vector:__div supports div with number only, while other math between vectors works fine
![image](https://github.com/Facepunch/garrysmod-requests/assets/34854689/85276a19-16c9-4677-9a4a-65ad0adf7c91)
rn i need todo detour to work with vector math
```lua
local Vec = FindMetaTable("Vector")

function Vec:__div(v)
	if isnumber(v) then
		return Vector(self.x / v, self.y / v, self.x / v)
	elseif isvector(v) then
		return Vector(self.x / v.x, self.y / v.y, self.x / v.y)
	end
end
```

**Comment by Be1zebub** [comment]
it would also be cool to have built-in __mod & __pow

**Comment by Be1zebub** [comment]
same issue with [VMatrix](https://wiki.facepunch.com/gmod/VMatrix)
no __mod & __pow support, no __div matrix / matrix support
also no VMatrix __unm support

**Comment by robotboy655** [comment]
Vector/Vector is not a thing from a mathematical standpoint. Same goes for the other 2 really.

Do you even actually need this/use this, or is this "just have it" type of thing? Can you provide examples where it'd make sense?

**Comment by Be1zebub** [comment]
isnt?
here is how i translate 3d world position to 2d gui map position
```lua
function imap.Translate3D(map, zoom, cursor)
	local delta = map.bounds.maxs - map.bounds.mins
	local frac = (cursor - map.bounds.mins) / delta

	return (map.pos + frac * map.size) * zoom
end
```

**Comment by Kefta** [comment]
What you're really doing here is using the Vector class to hold three scalars (frac). I know div simplifies the code here, but I would either just calculate each frac or multiply by the inverse vector. I don't think this justifies adding the operation.

**Comment by Be1zebub** [comment]
agree, it is possible todo this with methods - but I prefer not to inflate the code
![image](https://github.com/Facepunch/garrysmod-requests/assets/34854689/e71edc79-b215-41f8-8c90-5066934a3a40)
