### ISSUE TITLE
Backport "Position #" from newer games

### ISSUE THREAD

**Issue by URAKOLOUY5** [Facepunch/garrysmod-requests#2099]
### Details
This are initializers that exist in newer branches (since L4D2 or Alien Swarm).
Maybe even other position initializers.

One of them is:
#### Position Along Ring

Alien Swarm ([Enhanced Source](https://github.com/Enhanced-Source-Project/Enhanced-Source) repository, same in [P2:CE](https://store.steampowered.com/app/440000/Portal_2_Community_Edition/) (licensee csgo based project))
![](https://cdn.discordapp.com/attachments/619231812987650059/1118946963136712714/image.png)

Garry's Mod (10.05.23, default branch)
![](https://github.com/Facepunch/garrysmod-requests/assets/41019056/b9bedc46-f067-4bd7-a8da-fda8cad21cb0)
I'm not sure about other stuff for particles from newer branches.

**Comment by robotboy655** [comment]
Ok, I have added:
* Position Along Ring
* Position Along Epitrochoid
* Position Modify Place On Ground
  * This one has one caveat - `set normal` parameter may not be functional.
* Position From Chaotic Attractor
* Scalar Random
* Vector Random
* Vector Component Random
* Set Hitbox to Closest Hitbox
* Set Hitbox Position on Model
* Velocity Set from Control Point

I have also added hitbox/hitbox set parameters to these initializers:
* Position on Model Random
  * Also `hitbox scale` is now `model hitbox scale` and is a float (as opposed to whole numbers only) - please test if this causes any issues, especially with existing particles

And on these "operators":
* Movement Lock to Bone
* Cull relative to model

These changes are available in `dev` beta. I would appreciate it very much if you'd test their functionality for me and report any issues 

These are all from CS:GO. If you have any other ones that you want, now is the time to tell me (in a separate issue) and I will see what I can do.

Here's a list of initializers we don't have but CS:GO does: (internal names)
```
C_INIT_ColorLitPerParticle	
C_INIT_RemapParticleCountToScalar	
C_INIT_OffsetVectorToVector	
C_INIT_RemapSpeedToScalar	
C_INIT_ModelCull
C_INIT_RtEnvCull
C_INIT_NormalAlignToCP
C_INIT_NormalOffset
C_INIT_SequenceFromCP
C_INIT_InitFromCPSnapshot
C_INIT_InitFromParentKilled
C_INIT_InheritFromParentParticles	
C_INIT_RemapInitialDirectionToCPToVector
C_INIT_RemapInitialCPDirectionToRotation
```
