### ISSUE TITLE
Introduce new particle render modes from CSGO (SFM)

### ISSUE THREAD

**Issue by gonzalologorg** [Facepunch/garrysmod-requests#2100]
Rubat recently implemented some new features for particle system
It would be nice if we can get model renderer, it's the most cool of the renderers since we can use meshes to bring a much better inmersive effect into FX 

https://github.com/Facepunch/garrysmod-requests/assets/7375225/52d2bcc0-8a62-48b8-9c8a-855def9b5f4b

We also have blob renderer

https://github.com/Facepunch/garrysmod-requests/assets/7375225/6f355a0d-a851-46bc-a40e-2a2d3c454e2c

Not sure if the second one it's useful, but atleast the one from models it's pretty much interesting, model renderer just works like a sprite renderer, like operators modify the meshes as a simple quad

**Comment by Heliobask** [comment]
It would also be very helpful to have new generic render operator visibility options like Visibility input (dot/distance) min/max.

**Comment by robotboy655** [comment]
Added the model renderer, but not the blobular thing as I don't think it will be useful.
