### ISSUE TITLE
New Particle Visibility Options

### ISSUE THREAD

**Issue by Heliobask** [Facepunch/garrysmod-requests#2102]
In addition to the recent updates, new generic render visibility I/O options like Visibility input (distance/dot) min/max would be fantastic!
![123](https://github.com/Facepunch/garrysmod-requests/assets/1835329/601744b8-fd3d-43e9-9c33-0ef2699ec616)

The "screen space effect" mode option can also be very helpful for screen overlay particles.
![456](https://github.com/Facepunch/garrysmod-requests/assets/1835329/de47a9f5-35eb-4a02-82f3-dc9b06a09256)

**Comment by robotboy655** [comment]
Added all 5.
