### ISSUE TITLE
fix util.DecalEx for static props

### ISSUE THREAD

**Issue by homonovus** [Facepunch/garrysmod-requests#2103]
### Details
currently, util.DecalEx works on brushes, displacements, and dynamic/physics entities
they do not work on static props

i believe this code in the SDK will help to achieve this

https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/client/fx_impact.cpp#L150

**Comment by robotboy655** [comment]
There isn't a proper way to do this with `util.DecalEx` because there's no way to know which static prop was hit from the arguments, but I have applied a hacky workaround involving an additional trace that does the job well enough I think.
