### ISSUE TITLE
Backport behaviour of "Movement Basic" with "Oscillate Vector" from newer games

### ISSUE THREAD

**Issue by URAKOLOUY5** [Facepunch/garrysmod-requests#2104]
### Details
Looks like, in `dev` branch now, "Movement Basic" with "Oscillate Vector" still causes horror particles

#### With Movement Basic and Oscillate Vector
![](https://github.com/Facepunch/garrysmod-requests/assets/41019056/944f0dc4-80f7-4e2e-b3a4-8220d0f14e20)

#### Without Movement Basic
![](https://github.com/Facepunch/garrysmod-requests/assets/41019056/e7f2cdc5-5130-42a7-8a85-5841d0c54b75)

#### With Movement Basic (no Oscillate Vector)
![](https://github.com/Facepunch/garrysmod-requests/assets/41019056/253bab69-29ba-4f32-9bad-1e7b287b7a5f)

*this are particles from portal2 again* (converted to old pcf format, are fine in p2ce/alien swarm)

**Comment by URAKOLOUY5** [comment]
By the I found new stuff that missing

## Initializers

```
Remap Particle Count to Scalar
```

## Operators
```
Ramp Scalar Linear Simple

**Comment by URAKOLOUY5** [comment]
Also I found out that this particles relies on missing stuff

**from previous issue**
`Remap Particle Count to Scalar` (initializer)
`Remap Direction to CP to Vector` (operator)

**Comment by robotboy655** [comment]
As far as I can see, the implementation of `Movement Basic` and `Oscillate Vector` are consistent with CS:GO's implementation.

I have added the other 2 operators
* Remap Particle Count to Scalar (initializer)
* Remap Direction to CP to Vector (operator)
