### ISSUE TITLE
Bind COND_ enums to Lua

### ISSUE THREAD

**Issue by DrVrej** [Facepunch/garrysmod-requests#2106]
### Details
NPC condition enums aren't defined in Garry's Mod, forcing every NPC mod or base to define it themselves unnecessarily. Simply defining the condition enums listed here would solve this issue.

Conditions can be found here: https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/ai_condition.h#L25
They are also mentioned in the Garry's Mod wiki, but are only references: https://wiki.facepunch.com/gmod/Enums/COND

**Comment by Roachdaripper** [comment]
bump

**Comment by robotboy655** [comment]
Added as `COND.` enums (Not `COND_`)
