### ISSUE TITLE
Backport small stuff for entities from newer games

### ISSUE THREAD

**Issue by URAKOLOUY5** [Facepunch/garrysmod-requests#2107]
### Details
In newer games (>swarm and >portal2) there're bunch of stuff (that I found useful and need):

---
#### KeyValues
* `colortransitiontime`
#### Spawnflags
* `Enabled` - fix auto start (current workaround is using logic_auto -> TurnOff)
* `Always update`
---
### Inputs
* `MoveToPathNode`
* `TeleportToPathNode`
* `LockOrientation`
* `UnlockOrientation`
* `SetMaxSpeed`

---
#### KeyValues
* `disableshadowdepth`
* `shadowdepthnocache`
* `disableflashlight`

#### Inputs

* `EnableDraw`
* `DisableDraw`
* `EnableReceivingFlashlight`
* `DisableReceivingFlashlight`
* `SetLocalOrigin`
* `SetLocalAngles`
* `SetModel`

For shadow caching I'm not sure if it requires updating flashlight shaders somehow and even possible that easy.
+binding to lua.

**Comment by robotboy655** [comment]
Related/duplicate: https://github.com/Facepunch/garrysmod-requests/issues/1577

**Comment by robotboy655** [comment]
Added the inputs for `func_tracktrain` (not `path_track`)

I don't get the point of adding `Always update` for `env_projectedtexture`, it already always updates?
I am afraid making changes to  `Enabled` spawnflag would break existing content.

`disableshadowdepth`, `shadowdepthnocache` is not a thing in our engine version.
