### ISSUE TITLE
Add generatelightmaps support for prop_static

### ISSUE THREAD

**Issue by WinterPhoenix** [Facepunch/garrysmod-requests#2109]
### Details
In the [June 2023 Update](https://store.steampowered.com/news/app/4000/view/3672170635428139756):
> The game can now load and render Static Prop Lightmaps on maps that have them, such as select maps from Team Fortress 2

Since GMod is now capable of using Static Prop Lightmaps, I'd like to see support added to GMod's Hammer toolset for it, so mappers can leverage the new feature in their maps.

It's been supported since the Source Engine 2013 Multiplayer SDK, so it's a little puzzling why support for it doesn't exist in GMod.

### 2013 SDK Sources
Relevant code (that I can find off of a quick search of the SDK) is here:
https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/utils/vbsp/staticprop.cpp#L521-L522
https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/utils/vbsp/staticprop.cpp#L628-L638

**Comment by robotboy655** [comment]
This was already added yesterday.

**Comment by WinterPhoenix** [comment]
Fuck yeah, thanks!

**Comment by WinterPhoenix** [comment]
The property name is probably too long lol
![image](https://github.com/Facepunch/garrysmod-requests/assets/2799393/bc7a8cbd-95b3-433e-9e6e-cf36abe6e8cb)
