### ISSUE TITLE
CUserCmd:IsWorldClicking() serverside binding

### ISSUE THREAD

**Issue by Yogpod** [Facepunch/garrysmod-requests#2111]
It's in the usercmd header, can we get a binding for it so we can have this function serverside?
Possibly the direction as well since it's there

**Comment by robotboy655** [comment]
https://wiki.facepunch.com/gmod/Player:IsWorldClicking ?

**Comment by Yogpod** [comment]
Is the note on Player:IsWorldClicking's page wrong?

**Comment by Yogpod** [comment]
nevermind it has vanished
