### ISSUE TITLE
Baked ambient occlusion

### ISSUE THREAD

**Issue by shortnamesalex** [Facepunch/garrysmod-requests#2117]
Can we get baked ambient occlusion similar to the one used in CSGO's branch? It would improve the overall atmosphere of maps by a lot

I was previously using Slammin' Source Tool's vrad compiler for baked ao but the new June update has rendered the compiler useless.

**Comment by URAKOLOUY5** [comment]
Isn't there's MP version of slammin tools?

**Comment by shortnamesalex** [comment]
> Isn't there's MP version of slammin tools?

Yes but that uses the same vrad.exe as the SP one.

**Comment by shortnamesalex** [comment]
I had gone 4 months without realizing the MP version actually works. Closing this. Sorry.
