### ISSUE TITLE
Dynamic and baked light support for $phong reflections on LightmappedGeneric and WorldVertexTransition

### ISSUE THREAD

**Issue by qwerty-gm** [Facepunch/garrysmod-requests#2124]
### Details
There are such reflections on VertexLitGeneric materials

**Comment by robotboy655** [comment]
I am not going to be adding this. The shader is already at its limits and barely compiles due to its complexity. I am sorry, but it is not happening.

**Comment by qwerty-gm** [comment]
Maybe you can get this shader from here: https://github.com/mapbase-source/source-sdk-2013
![image](https://github.com/Facepunch/garrysmod-requests/assets/136369264/b5575ca3-4d14-48f8-9f36-8a5d2b1a0efc)
