### ISSUE TITLE
Add missing functions from Source Engine

### ISSUE THREAD

**Issue by zohart75** [Facepunch/garrysmod-requests#2134]
### Details
Why Garry's Mod doesn't have these functions that are implemented in Source Engine?

- [IsSphereIntersectingSphere](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/public/collisionutils.cpp#L245)
- [IsBoxIntersectingSphere](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/public/collisionutils.cpp#L259C1-L259C1)
- [IsBoxIntersectingSphereExtents](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/public/collisionutils.cpp#L303C31-L303C31)
- [IsCircleIntersectingRectangle](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/public/collisionutils.cpp#L339)
- [IsRayIntersectingSphere](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/public/collisionutils.cpp#L375)
- [IntersectInfiniteRayWithSphere](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/public/collisionutils.cpp#L443)
- [IntersectRayWithSphere](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/public/collisionutils.cpp#L495)
- [IsSphereIntersectingCone](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/public/collisionutils.cpp#L516)
- [IsPointInBox](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/public/collisionutils.cpp#L539)
- [IsPointInCone](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/public/collisionutils.cpp#L561)
- [IsBoxIntersectingBox](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/public/collisionutils.cpp#L578)
- [IsBoxIntersectingBoxExtents](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/public/collisionutils.cpp#L597)

Yes, we can just reimplement them, but C++ is much faster than GLua.

P.s. pls make them shared.

**Comment by robotboy655** [comment]
Added half of those, these are not added as they are just duplicates.
* IsBoxIntersectingBox - IsOBBIntersectingOBB with angle 0
* IsBoxIntersectingBoxExtents - IsOBBIntersectingOBB with angle 0
* IntersectRayWithSphere - uses IntersectInfiniteRayWithSphere internally
* IsCircleIntersectingRectangle - 2D stuff, we have no 2d vectors anyway.
* IsBoxIntersectingSphereExtents - IsBoxIntersectingSphere
* IsRayIntersectingSphere - basically same as IntersectRayWithSphere

Here are examples (I will put them on wiki later)

Sphere intersection:
```
-- Store entity we look at
local ent = NULL

-- Do this every frame
hook.Add( "Think", "Think_IntersectRayWithOBBExample", function()

	-- Store player object
	local ply = LocalPlayer()
	
	-- If player looked at some valid entity, swtich our entity to that
	local trEnt = ply:GetEyeTrace().Entity
	if ( IsValid( trEnt ) ) then ent = trEnt end

	-- No entity? do nothing
	if ( !IsValid( ent ) ) then return end

	local start = ply:GetShootPos()
	local delta = ply:GetAimVector() * 500
	local endpos = start + delta

	-- Perform a ray intersection against a sphere from the player's eyes
	local frac1, frac2 = util.IntersectRayWithSphere( start, delta, ent:GetPos() + ent:OBBCenter(), ent:OBBMaxs():Length() )
	--print( "res: ", frac1, frac2 ) -- For debugging

	if ( frac1 ) then
		local intersect1 = LerpVector( frac1, start, endpos )
		local intersect2 = LerpVector( frac2, start, endpos )
		debugoverlay.Axis( intersect1, angle_zero, 10, 0.01 )
		debugoverlay.Axis( intersect2, angle_zero, 10, 0.01 )
	end

	-- Draw the OBB visualization, requires developer 1 in console.
	debugoverlay.Sphere( ent:GetPos() + ent:OBBCenter(), ent:OBBMaxs():Length(), 0.01, frac1 != nil and Color( 0, 255, 0 ) or Color( 255, 0, 0 ) )

end )
```

Point in Cone
```
function ENT:Draw()

	local pos = self:GetPos()
	local point = Vector( 0, 0, 0 )
	local sphereRad = 20

	local height = 100
	local angle = 45 --[[degrees]] / 180 * math.pi -- converted to radians
	
	local size = math.tan( angle  )*height
	local segs = 32
	local is = util.IsPointInCone( point, pos, self:GetUp(), math.cos( angle ), height )
	local is2 = util.IsSphereIntersectingCone( point, sphereRad, pos, self:GetUp(), math.sin( angle ), math.cos( angle ) ) -- infinite height

	local precalc = 1/segs * math.pi * 2
	local center = pos
	for i = 1, segs do
		local pos1 = pos + math.sin( i * precalc ) * size * self:GetForward() + math.cos( i * precalc ) * size * self:GetRight() + self:GetUp() * height
		local pos2 = pos + math.sin( (i-1) * precalc ) * size * self:GetForward() + math.cos( (i-1) * precalc ) * size * self:GetRight() + self:GetUp() * height
		
		render.DrawLine( pos2, pos1, is and Color( 0, 255, 0 ) or Color( 255, 0, 0 ) )
		render.DrawLine( pos2, center, is and Color( 0, 255, 0 ) or Color( 255, 0, 0 ) )
	end
	
	render.DrawLine( pos, point, is and Color( 0, 255, 0 ) or Color( 255, 0, 0 ) )
	debugoverlay.Sphere( point, sphereRad,0.01, is2 and Color( 0, 255, 0 ) or Color( 255, 0, 0 ) )
end
```

**Comment by zohart75** [comment]
IsBoxIntersectingBox is faster than IsOBBIntersectingOBB.
