### ISSUE TITLE
Custom Closed Captions support from a file

### ISSUE THREAD

**Issue by Goldermor** [Facepunch/garrysmod-requests#2136]
it would be really useful to get custom сlosed сaptions support.
i think they can be used in the same way as .properties files, so we can just put .dat files to resource\localization\%language% and gmod will load them.

**Comment by robotboy655** [comment]
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/2024

Also related https://github.com/Facepunch/garrysmod-requests/issues/1745

**Comment by robotboy655** [comment]
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1994
