### ISSUE TITLE
add light amplification amount to color random

### ISSUE THREAD

**Issue by homonovus** [Facepunch/garrysmod-requests#2142]
### Details
add the `light amplification amount` field to the `color random` initializer.

https://github.com/perilouswithadollarsign/cstrike15_src/blob/f82112a2388b841d72cb62ca48ab1846dfcc11c8/particles/builtin_initializers.cpp#L2952-L2953

**Comment by robotboy655** [comment]
Added "Color Lit Per Particle" particle initializer, updated "Color Random" to include the stuff from CS:GO.
