### ISSUE TITLE
Add ability to create folders and files in materials/temp/

### ISSUE THREAD

**Issue by Dead0Duck** [Facepunch/garrysmod-requests#2145]
### Details
That would be great, if we had ability to create temp files, which removes on game launch/shutdown.
Now we can remove files in data folder on [GM:ShutDown()](https://wiki.facepunch.com/gmod/GM:ShutDown), but it triggers on map change too
![image](https://github.com/Facepunch/garrysmod-requests/assets/46423255/29f803d1-c1fe-41db-a891-14fa1f53c771)

**Comment by robotboy655** [comment]
I don't think so. I don't want addons writing files outside of `data/`. It adds unnecessary complexity.

You can delete unnecessary files yourself from the data folder (for example on Lua init, if the files are older than 2 days or something), even tie it to the convar.
