### ISSUE TITLE
Make bots return a proper SteamID instead of BOT

### ISSUE THREAD

**Issue by T-Rizzle12** [Facepunch/garrysmod-requests#2146]
### Details
After todays patch I noticed that now bot players now return on both client and server when you call SteamID64, "90071996842377216" as an example, would it be possible to make player bots return a proper SteamID, "STEAM_0:0:0" using the SteamID64 assigned to the bot?

Edit: I was messing around and figured out an easy way to implement this. I entered this into the console, `lua_run print( util.SteamIDFrom64( Entity( botindexhere ):SteamID64() ) )`

**Comment by robotboy655** [comment]
I am not sure it is a good idea.

The solution you presented is definitely a bad idea, as it introduces possible collisions with real SteamIDs (however unlikely that may be), and causes data loss, as you can no longer convert the `STEAM_0:0:0` format back to a steamID64 of a bot without assumptions. Not to mention addons that rely on `SteamID` returning `BOT` when storing data to handle bots.

The answer is simple - just use `SteamID64`.

**Comment by T-Rizzle12** [comment]
> I am not sure it is a good idea.
> 
> The solution you presented is definitely a bad idea, as it introduces possible collisions with real SteamIDs (however unlikely that may be), and causes data loss, as you can no longer convert the `STEAM_0:0:0` format back to a steamID64 of a bot without assumptions. Not to mention addons that rely on `SteamID` returning `BOT` when storing data to handle bots.
> 
> The answer is simple - just use `SteamID64`.

Understandable, I completely forgot about addon that check for BOT.
