### ISSUE TITLE
SteamID64 stream reader & writer convenience methods

### ISSUE THREAD

**Issue by WilliamVenner** [Facepunch/garrysmod-requests#2148]
### Details

The most common use case of writing larger-than-32-bit integers to the net stream or a file is probably for SteamID64s.

Currently, it's wasteful to write a SteamID64 to one of these streams as it must be written as a string. That means your average SteamID64 is going to take up 136 bits (17 bytes).

Whilst 17 bytes is nothing to panic about, [it would be trivial](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/tier1/bitbuf.cpp#L744) to implement the following methods:

- [ ] `net.ReadSteamID64() -> string`
- [ ] `net.WriteSteamID64(steamid64: string)`
- [ ] `File:ReadSteamID64() -> string`
- [ ] `File:WriteSteamID64(steamid64: string)`

These methods would cover 99% of use cases for writing larger-than-32-bit integers to the respective streams in Garry's Mod and would help keep the size of SteamID64-heavy net messages and files down.

Additionally, it would make some net message code easier to write. String SteamID64s are actually technically not always 17 bytes, so keeping track of the remaining length of the buffer would be made easier, for example. (It should be acknowledged however that `net.BytesLeft()` does exist)

_\* For anyone reading that needs to more efficiently send SteamID64s you can use a big hack I wrote [here](https://github.com/Facepunch/garrysmod/compare/master...WilliamVenner:garrysmod:feat/bigint) in the mean time_

**Comment by robotboy655** [comment]
Added net.Write/ReadUInt64 and File:Write/ReadUInt64

They accept and return string values, and can be used with Player:SteamID64()
