### ISSUE TITLE
vscript support

### ISSUE THREAD

**Issue by wackod** [Facepunch/garrysmod-requests#2150]
Gmod can run all of the  TF2 \ CSGO \ L4D2   maps  ,but  a lot of maps made by community need vscript to play (they use vscript to make minigames \ boss  \ triggers)

**Comment by garryspins** [comment]
kekw

**Comment by GrayWolf64** [comment]
A lot of VScript features, like functions, may be game-specific, which in turn needs a more advanced mounting system.

**Comment by URAKOLOUY5** [comment]
There's Lua, you can literally recreate vscript system (or even parser for them) by using Lua or native modules.
https://en.wikipedia.org/wiki/Parsing_expression_grammar
https://en.wikipedia.org/wiki/Parsing

**Comment by FlorianLeChat** [comment]
This is nearly a duplication of https://github.com/Facepunch/garrysmod-issues/issues/4091 where Rubat stated about VScript support would never be added.

**Comment by robotboy655** [comment]
No.
