### ISSUE TITLE
Port some of the easier Portal entities to Garry's Mod

### ISSUE THREAD

**Issue by wolfestridershooter** [Facepunch/garrysmod-requests#2151]
### Details
As I'm sure you know there are some Portal Gun mods on the workshop and I'm aware the portals themselves will likely never be add to the game officially although it would be really nice if all the other entities could be ported over into Garry's Mod since that would make Portal fully playable with just a single addon.

### Point entities:
- [ ] env_portal_credits
- [x] point_energy_ball_launcher

### Brush entities:
- [ ] func_noportal_volume
- [ ] func_portal_bumper
- [ ] func_portal_detector
- [ ] func_portal_orientation
- [x] trigger_portal_cleanser

### Prop entities:
- [x] prop_energy_ball
- [x] prop_glados_core

### NPCs:
- [x] npc_portal_turret_floor
- [x] npc_rocket_turret
- [x] npc_security_camera

**Comment by garryspins** [comment]
can you not replicate most of these through lua? excluding the brush entities ofc

**Comment by wolfestridershooter** [comment]
You could but why when you could have the actual entities? I don't think the game entities themselves should have to be recreated in lua

**Comment by URAKOLOUY5** [comment]
Those entities relie on portals's, for what purpose do you want `trigger_portal_cleanser`? Player from HL2 (and HL2MP) don't have portal feature and there's no portals at all... 

Actually, EVERY entity relie on portals!
NPCS can be recreated with GLua

**Comment by robotboy655** [comment]
I have ported some of them just for the fun of it, their clientside components are missing right now (those require network compatibility with existing servers to be broken).

I will **not** be adding the rest for the aforementioned reasons.

**Comment by wolfestridershooter** [comment]
Thank you!

**Comment by wolfestridershooter** [comment]
> Those entities rely on portals, for what purpose do you want `trigger_portal_cleanser`? Player from HL2 (and HL2MP) don't have portal feature and there's no portals at all...
> 
> Actually, EVERY entity here relies on portals or can be recreated with GLua!
> 
>     * `env_portal_credits` - c'mon, just vgui panel?
> 
>     * `func_portal_detector` - just trigger that detects if there's prop_portal in it
> 
>     * `func_portal_bumper` - entity that used in COMPLEX logic of portal placement calculation and useless if you don't have them (you don't)
> 
>     * `func_portal_orientation` - same as above
> 
>     * `point_energy_ball_launcher` - entity that spawns prop_energy_ball, sets it's velocity and etc...
> 
>     * `prop_glados_core` - prop entity that plays anims and :PlayScene() or :PlaySound()
> 
>     * `prop_energy_ball` - just sprite that bounces around world, dies after some time (same as prop_combine_ball, but don't follow player on bounce)
> 
>     * NPCS can be recreated with GLua as I said
>       
>       * **Camera** just follows nearest player do little offset for pose parameters every N second, plays moving sound
>       * **Rocket turret** and turret floor same as **camera**, but fires bullets/rockets and plays scenes/sounds.

I know this is a super late reply but the reasons why I wanted these entities ported to Garry's Mod was because if you've ever seen the attempts at recreating these entities in GLua they are pretty lacking. I'm not 100% sure weather it's because we are missing some functionality in GLua to enable us to recreate these entities 100% faithfully or if it's because everyone who has attempted does know how to code very well, probably a little bit of both. Point is weather or not it is possible to recreate these entities is largely irrelevant because at the end of the day it's just one more barrier for people trying to get Portal working within Garry's Mod. Instead of having just to recreate the portal gun and the portals themselves now we need to worry about getting all the other Portal entities ported over into Garry's Mod via GLua. Plus iirc we have all of Half-Life: Source's entities ported into Garry's Mod, by principle why not the easier ones from Portal? Not to say that I'm not grateful for what was already ported ofc

**Comment by robotboy655** [comment]
![Image](https://github.com/user-attachments/assets/4ba0f39d-419d-491b-99fb-909830623cd9)

The client parts (lasers) will be added in the next update.

**Comment by wolfestridershooter** [comment]
What about the energy ball fade?

**Comment by robotboy655** [comment]
Haven't tested that, but the clientside part of `prop_energy_ball` is also restored. The changes are live on `dev` beta, you can test it there yourself.

**Comment by wolfestridershooter** [comment]
Just tested it on `dev` and your only missing the burn decals for `prop_energy_ball` now
