### ISSUE TITLE
util.ScreenShake 5th argument

### ISSUE THREAD

**Issue by Roachdaripper** [Facepunch/garrysmod-requests#2154]
UTIL_ScreenShake in the C++ code has a 5th argument to affect airborne players
`void UTIL_ScreenShake( const Vector &center, float amplitude, float frequency, float duration, float radius, ShakeCommand_t eCommand, bool bAirShake )`

Could this be included in the lua binding?
It's fully functional, despite what the comments say
![image](https://github.com/Facepunch/garrysmod-requests/assets/11798863/33805911-6434-4d7a-ab16-3664e6f44aac)

and the affect-airborne-players spawnflag of env_shake works perfectly fine too.

**Comment by robotboy655** [comment]
Done.
