### ISSUE TITLE
Add Lua Bindings to CNavArea Damaging Attribute

### ISSUE THREAD

**Issue by T-Rizzle12** [Facepunch/garrysmod-requests#2155]
### Details
I was working on pathfinding for my player bots when I noticed this Convar nav_select_damaging_areas. After looking into CS:GO source code, the damaging attribute is used in bot pathfinding to avoid tigger_hurt and molotovs. Would it be possible to add bindings to the following functions:
- [ ] CNavArea::IsDamaging( void )
- [ ] CNavArea::MarkAsDamaging( float duration )

If possible could you also make the damaging attribute automatically apply to CNavAreas that contain tigger_hurt?

Sources:
https://github.com/sr2echa/CSGO-Source-Code/blob/master/cstrike15_src/game/server/nav_area.h#L860
https://github.com/sr2echa/CSGO-Source-Code/blob/master/cstrike15_src/game/server/cstrike15/bot/cs_bot.h#L2078

**Comment by robotboy655** [comment]
Done.
