### ISSUE TITLE
Add player_jump event to gameevent.Listen

### ISSUE THREAD

**Issue by wackod** [Facepunch/garrysmod-requests#2158]
it is useful to make addons about bhop

**Comment by Yarukon** [comment]
https://github.com/alliedmodders/hl2sdk/blob/78dab58646d5983c77af44c45a877b89196eb82c/game/shared/gamemovement.cpp#L2526

```c++
IGameEvent * event = gameeventmanager->CreateEvent( "player_jump" );
if ( event )
{
	event->SetInt( "userid", player->GetUserID() );
	gameeventmanager->FireEvent( event );
}
```

**Comment by robotboy655** [comment]
Added `OnPlayerLand`/`OnPlayerJump` hooks. (not game events) Arguments are `Player, number`, where the number is the velocity/impulse of the landing/jump respectively.

Opinion wanted: Should these 2 hooks be combined into 1? i.e. `OnPlayerJumpLand` with an argument if it was a jump or a landing.

**Comment by Yarukon** [comment]
> Added `OnPlayerLand`/`OnPlayerJump` hooks. (not game events) Arguments are `Player, number`, where the number is the velocity/impulse of the landing/jump respectively.
> 
> Opinion wanted: Should these 2 hooks be combined into 1? i.e. `OnPlayerJumpLand` with an argument if it was a jump or a landing.

2 hooks is good

**Comment by robotboy655** [comment]
Yeah, I forgot `OnPlayerHitGround` existed, I have already removed `OnPlayerLand`.
