### ISSUE TITLE
Clientside Files

### ISSUE THREAD

**Issue by ryanoutcome** [Facepunch/garrysmod-requests#2161]
### Details
Add a function to check if a file located in a directory from 'garrysmod/' (GAME in file.Find terms) is a valid clientside file and is already pooled.

Example usage would be:

IsValidClientside( 'addons/exampleAddon/lua/autorun/clientside/cl_example.lua' ) would return true if the file is valid and pooled.

**Comment by robotboy655** [comment]
file.Exists, file.Find

**Comment by robotboy655** [comment]
You can use `lcl` path, which would search only `AddCSLuaFile`'d files on client.

https://wiki.facepunch.com/gmod/File_Search_Paths

**Comment by ryanoutcome** [comment]
> You can use `lcl` path, which would search only `AddCSLuaFile`'d files on client.
> 
> https://wiki.facepunch.com/gmod/File_Search_Paths

Seems not to work on my server. I assumed you already knew of that though. Running localhost.

**Comment by robotboy655** [comment]
It works:
![image](https://github.com/Facepunch/garrysmod-requests/assets/3299036/f7004e26-1cf0-4c83-a855-3b3b99b82565)
