### ISSUE TITLE
Introduce $notint $allowdiffusemodulation to block $color2

### ISSUE THREAD

**Issue by gonzalologorg** [Facepunch/garrysmod-requests#2162]
### Details
As seen at [$notint](https://developer.valvesoftware.com/wiki/$notint) and [$allowdiffusemodulation](https://developer.valvesoftware.com/wiki/$allowdiffusemodulation) this flag on materials it's useful so you can disable color tinting in some materials without disabling it on other sub materials on your model

This can be dealt with by creating a proxy and tinting it from there, but honestly a flag like this would save the need to create a new proxy to handle this issue

This is how the model would look with this flag (Right now i've spawned and removed the bodygroups, but this would require 2 models)
![gPaLdOMs](https://github.com/Facepunch/garrysmod-requests/assets/7375225/6bf58dee-df07-4fe9-8f40-354feef856f5)

https://github.com/perilouswithadollarsign/cstrike15_src/blob/f82112a2388b841d72cb62ca48ab1846dfcc11c8/materialsystem/stdshaders/phong_dx9_helper.cpp#L772

**Comment by robotboy655** [comment]
`$notint` and `$allowdiffusemodulation` are both implemented in CS:GO, and are implemented differently.

`$allowdiffusemodulation` disables the per-model-instance tint (i.e. color tool), but what `$notint` does I am not sure. Reading its code, I think it is meant to disable effects of `$blendtintbybasealpha` specifically?

Given internal differences in shaders between CS:GO and GMod, as well as the parameter descriptions on the wiki, I have made `$notint 1` do the same thing as `$allowdiffusemodulation 0`.
