### ISSUE TITLE
Add CNavMesh::CreateLadder bindings?

### ISSUE THREAD

**Issue by StrawWagen** [Facepunch/garrysmod-requests#2164]
Add lua bindings for creating cnavladders

I know that you have to do some finagling to make nextbots work with ladders.
But for addons that have done the legwork to add ladder "support", you have to rely on navmeshes with manually placed ladders.

I was hoping that CNavMesh::CreateLadder, (or a different more appropriate function) could be exposed to lua, allowing for the creation of navladders, i haven't checked the code but making ladders without a func_ladder to "place" it on, would be fantastic! (eg in case a map used only func_usableladders)

Here's the function!
https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/game/server/nav_generate.cpp#L166C6-L166C28

**Comment by robotboy655** [comment]
Done. I have bound the other version of the function that provides more control.
`navmesh.CreateNavLadder( Vec top, Vec bottom, float width, Vec2D dir, float maxHeightAboveTopArea = 0 )`

You should be able to derive the mins/maxs version using this one if you really want it.
