### ISSUE TITLE
Expose GetMaterialIndex and GetMaterialNameFromIndex

### ISSUE THREAD

**Issue by brandonsturgeon** [Facepunch/garrysmod-requests#2167]
### Details
It would be very handy if we could use the engine functions:
- `int GetMaterialIndex( const char *pMaterialName );`
  - [Client](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/client/cdll_client_int.h#L150)
  - [Server](https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/game/server/gameinterface.cpp#L2241-L2260)
- `const char *GetMaterialNameFromIndex( int nIndex );`
  - [Client](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/client/cdll_client_int.h#L150)
  - [Server](https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/game/server/gameinterface.cpp#L2265-L2268)

If it's exposed on both realms, I imagine a Global function for each would be fine 👍

Thanks @RaphaelIT7 for noticing that these would be useful 🎉

**Comment by RaphaelIT7** [comment]
This would be useful because, for example: [render.MaterialOverrideByIndex](https://wiki.facepunch.com/gmod/render.MaterialOverrideByIndex) requires an material index to override the material.

**Comment by Kefta** [comment]
I think it'd be better if every instance that required a material index was hidden from the Lua side just like model indices are. What functions other than the one you linked need an index?

**Comment by brandonsturgeon** [comment]
If you could pass a material name instead of an index into that function, I would also be happy :)

Either is fine with me. It just seemed easier to expose the function that already exists than to add a brand new one (or change the existing one 😬)

**Comment by robotboy655** [comment]
But [render.MaterialOverrideByIndex](https://wiki.facepunch.com/gmod/render.MaterialOverrideByIndex) has nothing to do with material indexes though? The index it takes is the index of the model's texture (0 to 32), just like `SetSubMaterial` does.
