### ISSUE TITLE
Add xml, csv files to whitelist of the in-game mounting system

### ISSUE THREAD

**Issue by BrooS222** [Facepunch/garrysmod-requests#2169]
### Details
I would like to be able to upload xml and csv files to the workshop.
Even if Lua and Gmod dont have a built-in parser, devs can write one themselves and use these files for their own purposes (defining the user interface, game items and other assets without using Lua).
Why not do this?

**Comment by Dizcordum** [comment]
https://github.com/Facepunch/garrysmod-requests/issues/1262#issuecomment-740790115
Good point

**Comment by robotboy655** [comment]
Related issues:
https://github.com/Facepunch/gmad/issues/42
https://github.com/Facepunch/garrysmod-requests/issues/1386
https://github.com/Facepunch/garrysmod-requests/issues/1322
https://github.com/Facepunch/garrysmod-requests/issues/1070

**Comment by robotboy655** [comment]
Done.

Added data_static/ alternative to data/ folder with all the acceptable extensions
