### ISSUE TITLE
Changes Stack:Pop( number ) 

### ISSUE THREAD

**Issue by AlexSwift** [Facepunch/garrysmod-requests#217]
Could you change Stack:Pop( number ) to return what ever was at the top of the stack instead of just moving the stack pointer?

**Comment by Tripperful** [comment]
Would be pretty helpful

**Comment by AlexSwift** [comment]
I made this suggestion 5 years ago. In this time I went to University, got myself the dept that came with university, faced many life challenges, graduated, had 3 girlfriends, started work on an operating system, took up drums and am now fairly decent, started driving,  had depression, recovered from it. 

And now I finally have a better stack implementation, Thank you.
