### ISSUE TITLE
Add TextEntry:GetHorizontalScrollStartIndex()

### ISSUE THREAD

**Issue by arknis** [Facepunch/garrysmod-requests#2170]
Expose the `_currentStartIndex` variable in the `TextEntry.h` class, which indicates the index of the starting glyph of the visible window in the text entry when horizontal scrolling is enabled.

Use case:

This so I can correctly implement screen tracking of the cursor/letters (ie, pixel offset) to augment the text content. This is used for an autocomplete menu and in-line ghost text that aligns to incomplete syntax in the entry. Currently, this works fine as long as the text in the entry doesn't exceed the width. After typing in text past the window end and returning the cursor to edit text, the alignment calculation fails because it has no information regarding the window offset.

Example of what isn't possible when the horizontal window has shifted:

![image](https://github.com/Facepunch/garrysmod-requests/assets/7801006/92ade43e-a10b-4266-8bd7-591573240072)

Replicating the source engine horizontal window tracking as a workaround is painful and this addition would save a lot of headache.

**Comment by garryspins** [comment]
This would be _extremely_ useful, big 👍
