### ISSUE TITLE
support PCF 2 (CSGO)

### ISSUE THREAD

**Issue by wackod** [Facepunch/garrysmod-requests#2172]
CSGO's particle file can not use in gmod
now need to change the pcf file format to PCF1 
![image](https://github.com/Facepunch/garrysmod-requests/assets/36387604/89c22b95-08bd-47f8-92af-dc7ce793da15)

**Comment by wackod** [comment]
some CSGO maps have a custom pcf file, but gmod does not support pcf2 format

**Comment by robotboy655** [comment]
CS:GO is getting deleted soon, so I see no reason to provide any extra support for it.

There's also already a request for this: https://github.com/Facepunch/garrysmod-requests/issues/1757
