### ISSUE TITLE
Bind NPC:GetGoalPos, NPC:GetGoalTarget, NPC:CurWaypointIsGoal, NPC:GetGoalType, NPC:SetGoalType, GOALTYPE_* enums to Lua

### ISSUE THREAD

**Issue by DrVrej** [Facepunch/garrysmod-requests#2177]
### Details
Couple of important self explanatory navigation functions and a set of enums for 2 of them:
- `vector NPC:GetGoalPos()`( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/ai_navigator.h#L353) ): Returns current goal's position, different from the existing `NPC:GetCurWaypointPos()` & `NPC:GetNextWaypointPos()`!
- `entity NPC:GetGoalTarget()`( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/ai_navigator.h#L354) ): Opposite of the existing `NPC:NavSetGoalTarget()`, it returns the current goal's target, this is different from the existing `NPC:GetTarget()`!
- `bool NPC:CurWaypointIsGoal()`( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/ai_navigator.h#L360) ): Returns true if current waypoint is the goal.
- `enum NPC:GetGoalType()`( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/ai_navigator.h#L352) ): Returns the current goal type.
- `void NPC:SetGoalType(enum)`( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/ai_route.h#L106) ): Sets the goal type, useful for those who are making their custom tasks. 
- `GOALTYPE_* enums` ( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/ai_navgoaltype.h#L21) ): Enums used by `NPC:GetGoalType`, `NPC:SetGoalType`.

**Comment by robotboy655** [comment]
I added all functions except for `GoalType` stuff. I feel like it's too low level to expose, `NavSetGoalTarget` sets the goal type appropriately. I think it would be more logical to have more functions that generate a path and set the goal type appropriately.

**Comment by DrVrej** [comment]
> I added all functions except for `GoalType` stuff. I feel like it's too low level to expose, `NavSetGoalTarget` sets the goal type appropriately. I think it would be more logical to have more functions that generate a path and set the goal type appropriately.

Thank you for adding the other ones! As for `GoalType`, I primarily need `GetGoalType`, it would greatly help custom tasks and certain parts of the AI. The enum binding can be skipped too, the return number will be sufficient. Thank you!

**Comment by robotboy655** [comment]
Alright, added `NPC:GetCurGoalType`
