### ISSUE TITLE
Add Lua Bindings to CNavArea Block Attribute

### ISSUE THREAD

**Issue by T-Rizzle12** [Facepunch/garrysmod-requests#2179]
### Details
I have noticed that there is no lua binding to marking a CNavArea as block. Adding said binding will make it so addon creators don't have to override the CNavArea::IsBlocked or disconnect CNavAreas during gameplay, "which also destroys visibility data and encounter spots."
- [ ] CNavArea::MarkAsBlocked( CBaseEntity )
- [ ] CNavArea::MarkAsUnBlocked()
Source:
https://github.com/sr2echa/CSGO-Source-Code/blob/master/cstrike15_src/game/server/nav_area.cpp#L4601

**Comment by robotboy655** [comment]
Added missing enum for `NAV_MESH_BLOCKED_PROPDOOR`
Added `navmesh.GetBlockedAreas()`
Added `CNavArea:MarkAsBlocked( teamID )`
Added `CNavArea:MarkAsUnblocked( teamID )`
Added `CNavArea:RemoveAttributes( flags )`
Added `CNavArea:AddAttributes( flags )`
Disable default automatic navmesh unblocking
