### ISSUE TITLE
Entity:MapCreationID - Shared

### ISSUE THREAD

**Issue by ShadowRanger** [Facepunch/garrysmod-requests#218]
Currently, Entity:MapCreationID is serverside. Due to it's usefulness, I believe it would be a better idea to have it shared instead so it can be used more easily than now. Additionally, due to the fact ents.GetMapCreatedEntity relies on this, making that shared as well would only make sense. Anyways, just thought it would be a good idea to request this change. Thanks.

**Comment by robotboy655** [comment]
Done. It is now shared.
