### ISSUE TITLE
Hammer Entity Report Model Paths/Names

### ISSUE THREAD

**Issue by Mingooberus** [Facepunch/garrysmod-requests#2180]
### Details
Certain FGDs for other source engine games when added to hammer enable features like viewing the model pathways of the entity they're set on in the Hammer "Entity Report" window.

I'm proposing this is added to the FGD for Garry's Mod. 

A screenshot of what I'm referring to will be linked here: https://imgur.com/a/qyb4J3n

Concluding this I will attach the .fgd for Military Conflict Vietnam which includes this feature (although I'm not sure on which line the code occurs). 
[vietnam.txt](https://github.com/Facepunch/garrysmod-requests/files/12810895/vietnam.txt)

**Comment by robotboy655** [comment]
![image](https://github.com/Facepunch/garrysmod-requests/assets/3299036/f74f7592-762c-4c7c-8553-0fc7da150035)

I have added a bunch for ya to the default FGD. You can edit the FGDs yourself and add `*` to the key value type like so:
![image](https://github.com/Facepunch/garrysmod-requests/assets/3299036/be67053c-7de5-4663-838e-954656486648)

And it will make the key value appear in the report window
