### ISSUE TITLE
Bind NPC:DispositionPriority(Entity) to Lua

### ISSUE THREAD

**Issue by DrVrej** [Facepunch/garrysmod-requests#2181]
### Details
Bind [CBaseCombatCharacter::IRelationPriority( CBaseEntity *pTarget )](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/basecombatcharacter.cpp#L2757) to Lua, probably best to name it `DispositionPriority` instead of `IRelationPriority` to be on par with the other Disposition function that is already binded: [NPC:Disposition(Entity)](https://wiki.facepunch.com/gmod/NPC:Disposition).

**Comment by robotboy655** [comment]
Added as the second return value of `NPC:Desposition`
