### ISSUE TITLE
Bind NPC:StepHeight() to Lua

### ISSUE THREAD

**Issue by DrVrej** [Facepunch/garrysmod-requests#2184]
### Details
Used in couple of places to help the engine decide if the NPC is able to step up/down in a movement path. It is also used in IK calculations, it's a specific check for NPCs only where IK height calls `NPC:StepHeight()`. Works similar to [`GetStepHeight / SetStepHeight`](https://wiki.facepunch.com/gmod/CLuaLocomotion:SetStepHeight) that is already binded for Nextbots.

Link: https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/ai_basenpc.h#L1299

**This can be done in 2 ways:**
1. Simply do it the same way the engine does, where `NPC:StepHeight()` is a base NPC function that can be overridden by NPCs. So in Lua, `NPC:StepHeight()` would be called whenever it's requested by the engine and returning a number would override the engine's default value, 18. - _I recommend this one as it is simpler and same as the engine._
2. OR do it similar to nextbots where it could be defined as `NPC:GetStepHeight()` and `NPC:SetStepHeight()`.

**Comment by WoodzieWolf** [comment]
### **Bump**
