### ISSUE TITLE
Add VVD, PHY, VTX to file.Write Whitelist

### ISSUE THREAD

**Issue by KingDavidW** [Facepunch/garrysmod-requests#2188]
### Details
Model files work perfectly fine in the data folder, and there's currently workarounds to get it going properly. However, the model loading mechanism outside of $IncludeModel or ANI block addressing within the model require exact extensions for it to load into the game. So while you can set your model and do everything you'd like, if the VVD/VTX/PHY aren't alongside whatever you loaded in, you'll have no visual mesh or collision data.

It would be nice to have the capabilities to add these files into the data folder. An alternative to doing this that I can think of is mounting a gma with that content, but that seems like a needless workaround.

I guess technically you could also remove the strict extension requirement but it just seems easier to allow the extension in file.Write

**Comment by Kefta** [comment]
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1552.

**Comment by KingDavidW** [comment]
Ahh almost a year past since last word.  As nice as a blacklist instead of a whitelist might be, I can see the security issues sure. That being said, the entire extension list there seems like a must have. 

Honestly all source engine content formats should just be whitelisted full stop. I recognize that maybe the precompiled formats don't need to be there as they're just containers (our discussion in discord helped), but since source has so much bound to extensions once compiled it'd be nice to let us expand the toolset.

If we can already write and mount GMAs, then we have access to all the content formats that was whitelisted for use / recognized by the game in there. 

I will of course settle for my initial request as it is directly stopping me from having a dynamic model/mesh editor within the game 😃 .

**Comment by robotboy655** [comment]
Done.

mdl, phy, vvd, vtx and ani
