### ISSUE TITLE
Add more arguments to GM:OnScreenSizeChanged

### ISSUE THREAD

**Issue by PrikolMen** [Facepunch/garrysmod-requests#2192]
### Details
I think it's worth adding 2 additional arguments with new width and height to GM:OnScreenSizeChanged, because in most cases the developer needs them, and making 2 additional calls to `ScrW` and `ScrH` every time is at least not convenient and silly considering that we do them in a hook that intercepts screen resizing.

#### Old
GM:OnScreenSizeChanged( `number` oldWidth, `number` oldHeight ) 

#### New
GM:OnScreenSizeChanged( `number` oldWidth, `number` oldHeight, `number` newWidth, `number` newHeight )

**Comment by robotboy655** [comment]
Done.
