### ISSUE TITLE
add more navmesh.Find functions

### ISSUE THREAD

**Issue by homonovus** [Facepunch/garrysmod-requests#2193]
### Details
currently, all we have is [navmesh.Find](https://wiki.facepunch.com/gmod/navmesh.Find) _(InSphere)_
could we get a binding around for navmesh.FindInBox as well?

[CNavMesh::ForAllAreasOverlappingExtent](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/game/server/nav_mesh.h#L556) with a [NavAreaCollector](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/game/server/nav_mesh.h#L41)?

**Comment by robotboy655** [comment]
Added navmesh.FindInBox( mins, maxs )
