### ISSUE TITLE
Increase entity limit in the compilers (vbsp, vvis, vrad)

### ISSUE THREAD

**Issue by Unusuario2** [Facepunch/garrysmod-requests#2196]
### Details
Increase entity limit in the compilers (vbsp, vvis, vrad) from 20144 (i think it is the actual limit) to 65536 
Increasing the limit would serve to allow more internal entities in case it is needed (like my case)

**Comment by robotboy655** [comment]
I have increased it to 32k, that's already 4 times the actual entity limit in the game.

**Comment by Unusuario2** [comment]
is it possible to increased more?

**Comment by robotboy655** [comment]
Why do you need more? How is 32000 not enough?

**Comment by Unusuario2** [comment]
because my map has a buch of internal entities, most of them are some kind of prop_detail (more than 25000), func_detail, prop_static, ect.... 
It would be better 65536 or 131072, i think 131072 is to much maybe
in case you don't believe me:
![image](https://github.com/Facepunch/garrysmod-requests/assets/110506367/9aab9228-c740-4360-a279-203d6f9365af)
![image](https://github.com/Facepunch/garrysmod-requests/assets/110506367/60bc96aa-7b91-4080-8598-51bb6b549503)

**Comment by robotboy655** [comment]
I can try, but you most definitely should be trying better to optimize your map for the engine.
