### ISSUE TITLE
Please add MaxHealth option to NPC spawn entries and dupe-persist it.

### ISSUE THREAD

**Issue by Grocel** [Facepunch/garrysmod-requests#2200]
Please add `MaxHealth` option to NPC spawnmenu entries (`list.Set("NPC", ...)`) and persist it in dupes. This would be similar to the `Health` option, but for `NPC:SetMaxHealth()` instead.

### Why? (Developer's-Why™)
As it has been discussed on discord it has the following points:
- There is engine level and GMod level logic in NPCs that depends on MaxHealth. Such as the NPCs healing other NPCs (like the medic citizen/rebel) based on their max health. Another example is GMod's default Medikit SWEP "only" healing to MaxHealth.
- Allows for easier and more consistent coding across the board for NPCs with default behavior but custom models, skins and properties. (The entire point of the NPC settings).
- It should be just like 5 minutes to add on GMod level. The addon level solution powered by the "Make it yourself™" technology that could be responded with on requests like these is not always the best. In this particular case it has several disadvantages:
  - It takes at least twice as match time to implement for each addon that needs to use it. It is tedious to implement too.
  - It has potential of creating addon conflicts if not done properly.
  - "Why was the `Health` option added and dupe-persisted again?"

### Discord context
This request is a follow up to this discord chat that buried without no further follow up on that topic. Because it is actually better and usually also required to submit and discuss requests via GitHub, let's move that topic here.

For context:
<img width="1056" alt="Discord_2023-10-31_19-51-34" src="https://github.com/Facepunch/garrysmod-requests/assets/2457653/f46cfdc0-1dd2-4c18-83c7-2b86f4679e6f">

**Comment by robotboy655** [comment]
Yes, thank for you reminding me, I knew I forgot something from that channel, I have made `MaxHealth` save, and be set on NPC spawn as well.
