### ISSUE TITLE
Allow SetPreventTransmit to receive a table of Players or a CRecipientFilter

### ISSUE THREAD

**Issue by brandonsturgeon** [Facepunch/garrysmod-requests#2201]
### Details
Let's say I have a list of entities that I only want to transmit to certain players.

Right now, that means I'll have to loop a lot of times - first over the entities, then over all of the players for each entity.

Instead, if `:SetPrevenTransmit` could take a table of Players or `CRecipientFilter`, I could more easily control an entitiy's transmission with less performance impact.

For example, if I wanted to make a chat command that only shows a list of ents to Admins:
```lua
function OnlyShowToAdmins( entities )
    local plys = player.GetAll()

    for _, ent in ipairs( entities ) do
        for _, ply in ipairs( plys ) do
            if not ply:IsAdmin() then
                ent:SetPreventTransmit( ply, true )
            end
        end
    end
end
```

That isn't _horrible_ or anything, but it would be really nice if I could do this:
```lua
function OnlyShowToAdmins( entities )
    -- Or, ideally, maintain a list of not-admins as players join/leave
    local notAdmins = {}
    for _, ply in ipairs( player.GetAll() ) do
        if not ply:IsAdmin() then
            table.insert( notAdmins, ply )
        end
    end

    for _, ent in ipairs( entities ) do
        ent:SetPreventTransmit( notAdmins, true )
    end
end
```

**Comment by robotboy655** [comment]
Done.
