### ISSUE TITLE
Add a list.GetStored function

### ISSUE THREAD

**Issue by barkleygaiden** [Facepunch/garrysmod-requests#2203]
### Details
Similar to [scripted_ents.GetStored](https://wiki.facepunch.com/gmod/scripted_ents.GetStored) / [weapons.GetStored](https://wiki.facepunch.com/gmod/weapons.GetStored). Pretty easy to add, and would be nice to have.
```lua
--
--	Gets the REAL list, not a copy
--
function GetStored( list )

	g_Lists[ list ] = g_Lists[ list ] or {}
	return g_Lists[ list ]
	
end
```

**Comment by Kefta** [comment]
list.GetForEdit already does this.
