### ISSUE TITLE
Add -blocksize arugment for vbsp just like slammin' has

### ISSUE THREAD

**Issue by Jaffies** [Facepunch/garrysmod-requests#2208]
Sourcebox arleady did this: https://github.com/nillerusr/source-engine/commit/25e30be665bcb20cf4c000e00d7de72e4fd8c657
All that needs to be done is to make the same.
Pros:
      Ability to create big maps with way lesser vertex count!
Cons:
       Nothing

**Comment by stephen-cusi** [comment]
Good proposal, but gmos developers may not adopt it even though they have 64 bit **gmos**

**Comment by robotboy655** [comment]
Done. (Ported from CS:GO)
