### ISSUE TITLE
Add the "args" Parameter to ConCommand Autocomplete

### ISSUE THREAD

**Issue by ghost** [Facepunch/garrysmod-requests#222]
Currently with concommand.Add() the command function has the player, command, arg list, and arg string as parameters. Would it be possible to add the same arg list parameter to the autocomplete function? That way you wouldn't have to create a lua method to parse the autocomplete arg string for variables surrounded in quotes.

This

``` lua

function MyConCommand(ply, cmd, list, full)
    ...
end

function MyAutoComplete(cmd, full)
    ...
end

concommand.Add("MyCommand", MyConCommand, MyAutoComplete)
```

Becomes

``` lua

function MyConCommand(ply, cmd, list, full)
    ...
end

function MyAutoComplete(cmd, list, full)
    ...
end

concommand.Add("MyCommand", MyConCommand, MyAutoComplete)
```

**Comment by Nyaaaa** [comment]
Anyone know how to use auto complete?

**Comment by robotboy655** [comment]
Added, but at the arguments end up swapped because backwards compatibility.
