### ISSUE TITLE
Add function to hide ugly and uncustomizable keyboard layout informer

### ISSUE THREAD

**Issue by MaslovKK** [Facepunch/garrysmod-requests#2222]
![image](https://github.com/Facepunch/garrysmod-requests/assets/45038542/3963e33c-2445-4e9c-a5db-de202778dd68)

And it's visible only on windows build, on Linux build it doesnt visible.

**Comment by FlorianLeChat** [comment]
https://wiki.facepunch.com/gmod/Panel:SetDrawLanguageID
