### ISSUE TITLE
Bind NPC:OverrideMove() and NPC:OverrideMoveFacing()

### ISSUE THREAD

**Issue by DrVrej** [Facepunch/garrysmod-requests#2231]
### Details
2 straight forward functions, both will work the same way. When `true` is returned, it will not run the engine code, this is what certain HL2 NPCs do. Below is definition for each one:
- **NPC:OverrideMove(flInterval)**: Called every time `Move` is called, when returned `true` it will make the NPC not move, allowing the developer to define their own.
- **NPC:OverrideMoveFacing(move, flInterval)**: Called every time `Move` attempts to override the ideal yaw, this is VERY important at the moment as the engine constantly overrides the NPC's ideal yaw when it's moving, using this function we can simple return `true` when we want complete control over the NPC's ideal yaw when it's moving!

Both functions are defined [HERE](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/ai_basenpc.h#L1306), note that the functions are used in AI navigator and motor classes

Thank you!

**Comment by robotboy655** [comment]
Added.
