### ISSUE TITLE
Increase maximum uniquely named lights

### ISSUE THREAD

**Issue by JohnOakman** [Facepunch/garrysmod-requests#2233]
### Details
I've been working on a map for 3 months now and I'm doing the finishing touches, modifying certain parts of the map to fit the gameplay I want to offer to players. 
However I've run into a problem, and that is the maximum number of uniquely named lights, or like vbsp.exe tells it: 
`Too many switched lights (error at light 1), max = 32`

To reproduce this error, simply create a map and name 33 lights differently.

Could this number be increased to at least 64 or more?
For the time being, I'll have to scale down my ambitions to this limit.

Thank you!

**Comment by Goldermor** [comment]
if you have lights that turn off at the same time, give them the same names

**Comment by robotboy655** [comment]
Increased by 64. Let's see if this breaks anything.
