### ISSUE TITLE
`net` function to abort current message

### ISSUE THREAD

**Issue by Denneisk** [Facepunch/garrysmod-requests#2235]
Like `net.Send`, except calling it would simply discard the message instead of sending it. This would allow safely breaking out of the net context for whatever reason.

**Comment by homonovus** [comment]
5 min addition in gmod code
alternatively, you could check your conditions to not send before you start writing the message

**Comment by garryspins** [comment]
This would be incredibly useful, this is a request I've drafted many times but never proposed, please add.

**Comment by Denneisk** [comment]
> alternatively, you could check your conditions to not send before you start writing the message

Helpful if you have an interface to do the networking where it isn't as easy to split the logic with the writing:
```lua
function helper_func(str)
    assert(isstring(str))
    net.WriteInt(1, 9)
    net.WriteString(str)
end

local ok = pcall(function ()
    net.Start("msg")
    helper_func(nil)
    net.Broadcast()
end)

if not ok then net.Abort() end
```
