### ISSUE TITLE
Bind NPC:PlayerHasIlluminatedNPC to Lua

### ISSUE THREAD

**Issue by DrVrej** [Facepunch/garrysmod-requests#2236]
### Details
`PlayerHasIlluminatedNPC(ply, losDotProd)`( [Link](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ai_basenpc.h#L1209) ): Called when the player's flashlight is illuminating onto the NPC. This is used in certain NPCs in HL2. It would be a much better way to determine if the player is shining a flashlight onto an NPC then the current existing Lua alternatives (Which can be performance heavy and unreliable)

**Comment by robotboy655** [comment]
This relies on episodic behavior that is not present in GMod, and it doesn't really do anything special compared to what you might be doing. It's just a distance and Dot product check.
