### ISSUE TITLE
Add use type to PlayerUse hook

### ISSUE THREAD

**Issue by MaslovKK** [Facepunch/garrysmod-requests#2240]
Why there's no useType in PlayerUse

**Comment by garryspins** [comment]
most likely because its entirely irrelevant and static, track it yourself if you need it

**Comment by robotboy655** [comment]
It's not really a thing when the hook is being called. The found entity will be used with `USE_ON` or `USE_OFF` depending on the entity's capabilities. https://wiki.facepunch.com/gmod/Entity:SetUseType
