### ISSUE TITLE
More BLENDFUNC`s

### ISSUE THREAD

**Issue by Isemenuk27** [Facepunch/garrysmod-requests#2242]
Add more blend functions ( mul, xor, etc... ). Multiplication gonna be useful for usage with large uncompressed overlay textures without alpha.

**Comment by garryspins** [comment]
I wish

**Comment by robotboy655** [comment]
That's not a thing in DX9 as far as I can tell. The BLENDFUNC are directly translated to these enums: https://learn.microsoft.com/en-us/windows/win32/direct3d9/d3dblend
