### ISSUE TITLE
Add NPC:GetIdealSequence()

### ISSUE THREAD

**Issue by DrVrej** [Facepunch/garrysmod-requests#2243]
### Details
`m_nIdealSequence` is heavily used in NPCs as it's the only proper way to retrieve the actual sequence and animation it's currently playing. Only way to access it is to call `self:GetInternalVariable("m_nIdealSequence")`, which causes a huge performance drop. After multiple performance tests comparing `self:GetInternalVariable("m_nIdealSequence")` and a similar function, `self:GetSequence()`, calling a direct function was about 50% faster in all cases. Unfortunately there is no such function for `m_nIdealSequence`, `self:GetSequence()` returns `m_nSequence` which shouldn't and can't be used in dealing with animation control for NPCs.

**Comment by robotboy655** [comment]
Added.
