### ISSUE TITLE
Separate Workshop Categories

### ISSUE THREAD

**Issue by NovaDiablox** [Facepunch/garrysmod-requests#2246]
### Details

I think there should be separate sub categories for these workshop categories.

- Player Models
- Prop Models
- SNPCs
- NAVMeshes
- NextBots
- SFM Models
- Ragdolls
- SWEPs*
- Weapons*
- Cars
- Aircrafts
- Planes
- Helicopters
- Cycles
- Submarine
- Boats or Ships

*There are some SWEPS that don't "shoot" anything and its use is something creative and different than a weapon.

**Comment by garryspins** [comment]
gl

**Comment by NovaDiablox** [comment]
> gl

Soon its going to be a year since this request. I don't see any luck at all =)
