### ISSUE TITLE
MySQL Integration

### ISSUE THREAD

**Issue by 8BallBomBom** [Facepunch/garrysmod-requests#225]
I know this is a long shot.
It has been requested before but would it be possible to get a built in MySQL solution?
The only reason I'm asking is due to the fact almost every serious server uses a MySQL database.

If possible could we have something like MySQLOO but less buggy please.

I'm sure there's many who support this.

**Comment by Kefta** [comment]
TMySQL was updated to be way more functional and stable, and doesn't create a bunch of internal junk like MySQLOO. Think this can be closed

**Comment by kklouzal** [comment]
I tried a couple years ago to get this implemented.

I just assume the devs would want to implement it themselves at this point so they can make it as efficient as possible with some documentation.

https://github.com/Facepunch/garrysmod-requests/issues/37
