### ISSUE TITLE
broaden gamemodes/*/entities whitelist

### ISSUE THREAD

**Issue by EntranceJew** [Facepunch/garrysmod-requests#2250]
### Details
I'm not certain for the reasoning behind it, or what sort of legacy may exist, but I would really appreciate it if the whitelist for gamemodes wasn't so restrictive about the entities folder:
https://github.com/Facepunch/gmad/blob/master/include/AddonWhiteList.h#L47-L49

It would be nice if [TTT2 could move these gamemode-specific files](https://github.com/TTT-2/TTT2/tree/master/lua/terrortown/entities) into the `gamemodes/terrortown/entities/` folder so that all the semantic entities/data files existed within reach of each-other, and all the library gamemode code could stay in `lua/` as-is.

Right now, you can't even make arbitrary folders inside `gamemodes/*/entities/` with those names and load files from them manually. I don't know what the reasoning for this may be, as seemingly a user could put any arbitrary lua in an ENT/SWEP/effect similarly. I would like to be able to do so.

For reference, here's a comparison of the strings listed if they were in order with each-other:
![image](https://github.com/Facepunch/garrysmod-requests/assets/5711436/d9f9089e-79c8-4a9e-85d8-622b5bcb54bd)
_`*.lmp` is missing from the gamemodes side, otherwise, nothing else of note_

**Comment by robotboy655** [comment]
The `gamemodes/<gamemode>/entities/` folder is specifically for entities/effects/weapons for that gamemode. Any other custom data you can store in `gamemodes/<gamemode>/gamemode/*.lua`.
