### ISSUE TITLE
Add util.IntersectRayWithRay

### ISSUE THREAD

**Issue by wrefgtzweve** [Facepunch/garrysmod-requests#2262]
### Details
Related to https://github.com/Facepunch/garrysmod-requests/issues/2134 and https://github.com/Facepunch/garrysmod-requests/issues/1805

I was trying to replicate source engines tracer logic and noticed that IntersectRayWithRay wasn't in gmod yet
![image](https://github.com/Facepunch/garrysmod-requests/assets/69946827/b8dce27b-fc29-4041-9ff5-17821d409fab)

Most other raywith functions have been added but RayWithRay seems to be missing
![image](https://github.com/Facepunch/garrysmod-requests/assets/69946827/a3955c5e-8b8c-4096-b6c8-7d6b98761783)
https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/public/collisionutils.h#L74

**Comment by robotboy655** [comment]
Added as `util.IsRayIntersectingRay` to keep consistency between names and return values.

`print(util.IsRayIntersectingRay( Vector(0,0,0), Vector(0,0,100), Vector(100,0,0), Vector(0,0,100) ))`

returns bool, ray1dist, ray2dist
