### ISSUE TITLE
Add Custom Animation Event Support

### ISSUE THREAD

**Issue by Cpt-Hazama** [Facepunch/garrysmod-requests#2265]
`HandleAnimEvent` would be more useful if we had access to the event names. Currently we only have access to the event IDs, however this is not useful for most cases, especially for NPCs because they tend to use custom event names. Custom event names, such as the ones used by HL2 NPCs are set to a different ID on map load. To solve this issue, we would need a way to retrieve the name of the event.

One possible solution would be to bind this function to Lua: `EventList_NameForIndex` ( https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/shared/eventlist.cpp#L179 ), which is used to print the error message that comes along with HandleAnimEvent indicating the associated event name.

Thank you 🙏

**Comment by Goldermor** [comment]
Can you provide an example of an event that relates to your request? I don't really understand what you're trying to say

**Comment by Cpt-Hazama** [comment]
```
	{ event AE_ZOMBIE_STEP_LEFT 5 "" }
	{ event AE_ZOMBIE_STEP_RIGHT 15 "" }
	{ event AE_ZOMBIE_SCUFF_LEFT 20 "" }
	{ event AE_ZOMBIE_STEP_LEFT 28 "" }
	{ event AE_ZOMBIE_STEP_RIGHT 38 "" }
	{ event AE_ZOMBIE_SCUFF_LEFT 40 "" }
```
This is from the HL2 zombie QC, we will never have proper access to such things in lua because the event ID that's returned is a generated number that is never the same per map load.

**Comment by Goldermor** [comment]
these events are registered internally as strings, and most likely the game just gives them random IDs

**Comment by Cpt-Hazama** [comment]
Yeah...that's what I've been saying lol. If we had access to the function that returns the string then that handleanimevent function could be used properly

**Comment by robotboy655** [comment]
Added `string = util.GetAnimEventNameByID( num )` as a binding to `EventList_NameForIndex`.
