### ISSUE TITLE
Add a 3rd generator function argument for PathFollower:Chase

### ISSUE THREAD

**Issue by justin-chellah** [Facepunch/garrysmod-requests#2267]
### Details
Hey, it would be nice to be able to control path generation using a custom generator function. Using `PathFollower:Compute` isn't an option because Chase recomputes the path periodically using a different cost function (in this case the default CLuaPathCost).

See here for reference: https://github.com/SourceSDK2013Ports/NextBot/blob/master/Path/NextBotChasePath.h#L95-L104

I think the code for that would look something like this in `PathFollower__Chase`:
```cpp
if ( LUA->IsType( 4, Lua::Type::Function ) )
{
    int ref = LUA->ReferenceCreate();

    CLuaPathCost cost( bot, ref );
    chasePath->Update( bot, ent, cost );

    LUA->ReferenceFree( ref );
}
```

**Comment by robotboy655** [comment]
Done.
