### ISSUE TITLE
Make SetModel function trigger clientside when it's called serverside

### ISSUE THREAD

**Issue by cat-marislav** [Facepunch/garrysmod-requests#2271]
I have a case where I need to do something before and after an entity's model changes. I rewrote the SetModel function both serverside and clientside, but it is only triggered in the realm it is called in. (For instance, if I call SetModel on the server, then my rewritten function will be called serverside, but not clientside).

**Comment by robotboy655** [comment]
I am not changing a function to suit your needs.

Something like this: https://github.com/Facepunch/garrysmod-requests/issues/747 would be a far more appropriate request.

**Comment by cat-marislav** [comment]
I'm not asking for you to change the function, I just want this function to be called in the clientside realm when you call it serverside. Doing #747 is a better way to do it I suppose, although that issue is almost 8 years old
