### ISSUE TITLE
Add support for effectName "Impact"'s flags

### ISSUE THREAD

**Issue by AirRice** [Facepunch/garrysmod-requests#2272]
### Details
When using util.Effect with the effectName "Impact", the engine-defined flags for the effect do not seem to do anything when supplied as flags in the CEffectData through :SetFlags(). Specifically, 0x1 should be [IMPACT_NODECAL](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/client/fx_impact.h#L26) and prevent the hitmaterial-based decal from being drawn, but the decal is still drawn even when the flag is supplied.

Allowing the flag would let, for example, weapons use custom impact decals while still performing the other impact FX (specks and dust on impact, the sound, etc)

**Comment by robotboy655** [comment]
Those flags are used internally only, `"Impact"` effect does not use any flags.

I have added another effect called `Impact_GMOD` that will do this. A separate effect to avoid issues with existing addons, especially considering `EffectData()` does not reset its internal data.
