### ISSUE TITLE
Allow uploads of .vbsp & .vmf within GMAD

### ISSUE THREAD

**Issue by Mingooberus** [Facepunch/garrysmod-requests#2284]
### Details
Allow the embedding of .vbsp (detail prop config) & .vmf files within addons for easier distribution of source content.

This would avoid the Valve and Steam hated linking of external download sites for these materials at the addon author's discretion.

Directories of both would be the following

garrysmod/customname.vbsp
garrysmod/mapsrc/customname.vmf

**Comment by robotboy655** [comment]
I am not sure I agree with this. Why should the average player be forced download the extra source files that are completely pointless for them? This also means that to access said files, the player would have to mess with extracting the files from the `.gma` files.

In my mind linking to a github repo (or any other website with similar functionality) is the superior option.

**Comment by Mingooberus** [comment]
Understood, appreciate the consideration regardless.
