### ISSUE TITLE
Allow util.ScreenShake to take a CRecipientFilter

### ISSUE THREAD

**Issue by brandonsturgeon** [Facepunch/garrysmod-requests#2289]
### Details
Just a small QoL feature: it would be nice if [util.ScreenShake](https://gmodwiki.com/util.ScreenShake) took a `CRecipientFilter` as the last parameter, similar to [util.Effect](https://gmodwiki.com/util.Effect)
_(I think this is a good example? Maybe there's something special about `util.Effect`?)_

Currently the only way to do this is to create a new net message and make your own `CRecipientFilter`.

**Comment by robotboy655** [comment]
Added as 7th argument, serverside only obviously.
