### ISSUE TITLE
Network teamonly in player_say

### ISSUE THREAD

**Issue by RaphaelIT7** [Facepunch/garrysmod-requests#2294]
### Details
`teamonly` should also be networked to the client.
It would only require that it's added to the `resource/serverevents.res` file. 
It wouldn't break anything for clients or servers that doesn't have it.
```lua
	"player_say"
	{
		"userid"	"short"		// user ID on server
		"text"		"string"	// the say text
		"teamonly"	"bool"		// is it teamonly <-- This line needs to be added
	}
```

**Comment by robotboy655** [comment]
I think I will bundle this with net compat breaking update

**Comment by robotboy655** [comment]
Done.
