### ISSUE TITLE
Allow .pat files through GMAD's whitelist

### ISSUE THREAD

**Issue by Mingooberus** [Facepunch/garrysmod-requests#2295]
## Details
 .pat files are map-associated files specifically relating to .lmp files for the .bsp file format. 
 They're pretty undocumented (one unfinished page on the Valve Developer Community wiki) but I assume they are essential for some maps to function (as I said I have almost no clue on how they work but they do).
 When opened in a text editor they seem to have a similar architecture as vmfs using "replace_entity" to further edit lmps/bsps.
 
 ## Usage?
 FakeFactory's Cinematic mod uses LMP edited maps as I believe the original .vmfs were not "out there" so recompilation of campaign maps was not fully possible (or legal lol). However when used in Garry's Mod with some minor tweaks to textures and their reliance on unsupported shaders the maps are playable (When loose in Garrys Mod\garrysmod\maps the maps are playable) however due to .pat files not being directly in the content when uploaded to the workshop the maps are unplayable.
 
 ### I completely understand this request is incredibly niche however it would be cool to use the maps (minus their flawed character models) in Garry's Mod. Furthermore I am **NOT** requesting for Cinematic Mod to be uploaded to the workshop. 
 
 Attached to this is a .pat file changed to a .txt file so that github allows it. 
[d1_canals_01.txt](https://github.com/Facepunch/garrysmod-requests/files/14367699/d1_canals_01.txt)

**Comment by robotboy655** [comment]
For anyone coming here from google or something, the `.pat` files seem to be used to patch the entity lump of a `.bsp`, via the `mkentitypatch` tool, which doesn't appear to even be shipped with HL2 itself. They are never loaded by the game itself.
