### ISSUE TITLE
Secondary UV maps for BuildFromTriangles

### ISSUE THREAD

**Issue by DeffOS** [Facepunch/garrysmod-requests#2296]
### Details
Extend IMesh:BuildFromTriangles to seek second uv maps for lightmap render when IMesh created with lightmapped material.
Using mesh library for this is ass because its at minimum 3 calls to C function for every vertex in que, also one error and prepare to crash on mesh.End

**Comment by DeffOS** [comment]
Yea, additional fields (u1/v1 or lu/lv) values on stage 1
Example of how i used it with mesh`
		mesh.Position(self:GetPosition())
		mesh.Normal(_nCap)
		mesh.TexCoord(0,self:GetUVs())
		mesh.TexCoord(1,self:GetLightUV())
		mesh.Color(255,255,255,invert and 255-self:GetAlpha() or self:GetAlpha())
		mesh.AdvanceVertex()
`
Also what exactly new changes on wiki mesh.TexCoord (Each UV set begins with a 0, 2, 4 and 6.) mean? For lightmaps i always used stage 1.

**Comment by robotboy655** [comment]
> Also what exactly new changes on wiki mesh.TexCoord (Each UV set begins with a 0, 2, 4 and 6.) mean? For lightmaps i always used stage 1.

Yeah, I am a bit confused on how the stage parameter is meant to work, looking at the code internally, using odd values (1,3,5, etc) should overwrite the second UV value of "previous stage".

**Comment by DeffOS** [comment]
[2ffacfab-9222-4247-ba48-67e05c18ece1.dmp](https://github.com/Facepunch/garrysmod-requests/files/14410414/2ffacfab-9222-4247-ba48-67e05c18ece1.dmp)
Crash dump itself

**Comment by robotboy655** [comment]
Looks like the crash is exclusive to the x86-64 beta.

**Comment by robotboy655** [comment]
I have added support for `u1` and `v1` to `dev` and `x86-64` betas.

**Comment by robotboy655** [comment]
The crash will also be fixed soon.
