### ISSUE TITLE
NavMeshes on client?

### ISSUE THREAD

**Issue by zohart75** [Facepunch/garrysmod-requests#2297]
### Details
Is it even possible to add navmesh.* to client?
If so, why can't we have those?
That would be great.

P.s. for example, we could make path finding solution without bothering the server.

**Comment by robotboy655** [comment]
It's not happening. Nothing inherently prevents it besides the fact that:
1) Nothing in the game currently uses/needs that on the client
2) it would be a substantial amount of work on my part for little gain
