### ISSUE TITLE
Add capability to set DSP preset for IGModAudioChannel

### ISSUE THREAD

**Issue by barkleygaiden** [Facepunch/garrysmod-requests#2301]
### Details
EmitSound, CSoundPatch, etc already have this feature but none support playing audio from a URL.

Instead of applying preset on channel initialization, might be better to do a Get/Set function for it?

**Comment by robotboy655** [comment]
`sound.PlayFile` and `sound.PlayURL` streams do not go through the game engine's sound system and therefore cannot do engine DSPs.
