### ISSUE TITLE
Increase texinfo and texdata limits

### ISSUE THREAD

**Issue by Aarik1** [Facepunch/garrysmod-requests#2304]
### Details
When the brush limit was increased to 16k other limits such as texinfo and texdata were not increased alongside it. This is a problem, as maps grow they use up more resources and other limits start getting hit. Currently our brush count is around 8k and the texinfo is at 11379/12288. It would also be nice if other limits alongside it were upped as well but currently these are the only limits that are preventing us from going any further.

Moved from the bug reporter repo.

**Comment by robotboy655** [comment]
I have increased them as such: 
MAX_MAP_TEXDATA 2048 -> 8192
MAX_MAP_TEXINFO 12288 ->16384

Please do test this change on `dev` beta.

This was also fulfilled:
https://github.com/Facepunch/garrysmod-requests/issues/2305
