### ISSUE TITLE
Add .svg, .html, .css to data_static/* folder whitelist

### ISSUE THREAD

**Issue by Jaffies** [Facepunch/garrysmod-requests#2311]
why not?

**Comment by Jaffies** [comment]
Basically it would add the possibility to make web interfaces without pain, especcialy with svg elements because there is no fucking way to use svg without internet connection and third-party file containers. GMAD can allow it, just add a few lines and it's done

**Comment by homonovus** [comment]
you can save the files as filename.svg.dat, read the file from data_static & use the data from that in any way you need
you don't have to save the filename exactly as .svg

**Comment by Jaffies** [comment]
<img src="asset://garrysmod/data_static/data.svg.dat"> won't work.

**Comment by robotboy655** [comment]
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1156
