### ISSUE TITLE
Hammer Editor - Radius bubble for point_message

### ISSUE THREAD

**Issue by Battlefieldkille** [Facepunch/garrysmod-requests#2312]
### Details
Currently there is no good way to visually determine how far the message radius will cover an area in the map.
Entity like ambient_generic has a radius bubble if you turn on Toggle Helpers. Could we get something similar?
[pointmessage.zip](https://github.com/Facepunch/garrysmod-requests/files/14502527/pointmessage.zip)

**Comment by robotboy655** [comment]
Will be added.
