### ISSUE TITLE
Hammer Editor - func_tanks cant recognize "Use" as a valid input

### ISSUE THREAD

**Issue by Battlefieldkille** [Facepunch/garrysmod-requests#2313]
### Details
I am not sure whether or not I should classify this as an issue or a feature request...
Besides walking up to them and activating them while being nearby, entities like func_button can activate them too. An output for that goes something like this: [ OnPressed _func_tank_name_ Use ] - This actually activates it and lets you control the func_tank from ANY part of the map - extremely useful.
Its just that its very annoying when its constantly being reported as an error in Check For Problems window in Hammer Editor.

This is the list of all entities that are similar/can be activated via "Use" input.
func_tank
func_tank_combine_cannon
func_tanklaser
func_tankmortar
func_tankpulselaser
func_tankrocket
func_tankairboatgun

[functanks.zip](https://github.com/Facepunch/garrysmod-requests/files/14524700/functanks.zip)
Map for ease of review ^

**Comment by robotboy655** [comment]
I have added the Use input to the fgd.
