### ISSUE TITLE
Allow :SetDSP() to be used with IGModAudioChannel

### ISSUE THREAD

**Issue by MagentaIris** [Facepunch/garrysmod-requests#2317]
Title says it all, I do not think that IGModAudioChannel allows you to use SetDSP on its snd entity.

Would be nice to use because sound.PlayFile() has much more in-depth capabilities VS CreateSound()

**Comment by robotboy655** [comment]
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/2301
