### ISSUE TITLE
Bind Entity:Dissolve 

### ISSUE THREAD

**Issue by BREEDNKMs** [Facepunch/garrysmod-requests#2326]
Right now, entities are generally dissolved by spawning the env_entity_dissolver and firing "dissolve" input on the target entity, with LUA. 

Entities can additionally be dissolved using the CBaseAnimating::Dissolve function without creating additional entity but it is not yet bound to the LUA API. Creating a dissolver manually and firing the input involves creating one more dissolver, because "dissolve" input creates another dissolver internally. Binding the necessary function would decrease the max spawned entity requirement to 1.

**Comment by robotboy655** [comment]
Added `Entity:Dissolve( type = 0, magn = 0, orign = EntOrigin ) `
