### ISSUE TITLE
Add the sdk launcher from csgo (or any game that have it)

### ISSUE THREAD

**Issue by Unusuario2** [Facepunch/garrysmod-requests#2327]
### Details
Add the sdk launcher in order to have tools more organise, here is an example:
![image](https://github.com/Facepunch/garrysmod-requests/assets/110506367/82facbbc-8b06-4213-9875-52ac081dd7e0)
![image](https://github.com/Facepunch/garrysmod-requests/assets/110506367/c4c291a6-86f0-4546-aeec-33f3232fdf58)

**Comment by robotboy655** [comment]
Copy the hammer.exe/hlmv.exe shortcut to your desktop, job done?

**Comment by Unusuario2** [comment]
It also works, I just would like to have it so I don't put it on the desk

**Comment by robotboy655** [comment]
You'd have to put something on the desktop, be it the SDK launcher or the direct hammer and other .exes
