### ISSUE TITLE
Upgrade to [existing] Source features

### ISSUE THREAD

**Issue by CaptainBigButt** [Facepunch/garrysmod-requests#233]
I'll be honest, I may be really ignorant on this subject. I'm not sure what access the Facepunch team has to Source branches, but it'd be wonderful to see some updates to the shader department on Garry's Mod. Lots of these shaders have already been updated to newer Source games such as Portal 2, Global Offensive, and even Dota. In other words, newer revisions of Source have things such as Dota's cloth physics or Portal/CS:GO's new lighting features and such which could have some really creative uses in Garry's Mod. On a side note, it looks as though that "leaked Left 4 Dead 3" stuff was rendered using Portal 2 foliage and CS:GO shaders which should explain the rest assuming this is possible.

**Comment by cannon** [comment]
bump, would like to use csgo graphics features

**Comment by Kefta** [comment]
Did Kilburn have greater access to engine branches or something?

**Comment by CaptainBigButt** [comment]
Greater, no. It's been years since I asked him but if I recall he said Valve was becoming less and less willing to work with others when it came to steamworks. I don't think they were as willing to share engine access which could've been due to Source 2, Valve simply becoming distant, or whatever else. Unless something turns up out of the blue, I don't think it's going to happen.

**Comment by robotboy655** [comment]
There are already requests for specific shaders to be added from newer Source branches and this request is just vague on you actually want.
