### ISSUE TITLE
"Update lighting" to a newer source version.

### ISSUE THREAD

**Issue by Fedox-die-Ente** [Facepunch/garrysmod-requests#2330]
### Details
In other Source games/bases like in this case Source SDK Base the light ratio is much better than in Garry's Mod.

Here is a small example:

Here we see the Hammer++ Lighting (On Source SDK Base)
![image](https://github.com/Facepunch/garrysmod-requests/assets/67076970/16eb9493-4493-4f0b-bfa7-5bc1ac3e05fb)

And here is the same lighting but in Garry's Mod:
![image](https://github.com/Facepunch/garrysmod-requests/assets/67076970/5224a2dc-c19c-4b4f-9aef-ef4a858c64db)

I don't know if updating something like this is fast, or even works without changing a lot, but if it did, it would be something the mapper community would be happy about.

**Comment by robotboy655** [comment]
What you show in the top preview appears to be a Hammer raytraced preview, which is simply not comparable to in-game graphics.

This very much feels like "make graphics better" request without any details to work with.

**Comment by Fedox-die-Ente** [comment]
> What you show in the top preview appears to be a Hammer raytraced preview, which is simply not comparable to in-game graphics.
> 
> This very much feels like "make graphics better" request without any details to work with.

Well, yes. I don't know how to describe it better. I mean that all the light just becomes a bit "softer". Or like in the second preview, the chairs on the right are completely dark, even if there is light nearby.

**Comment by robotboy655** [comment]
I am not adding raytracing to the game.
