### ISSUE TITLE
Add .yml, .toml, .json to resource.AddSingleFile

### ISSUE THREAD

**Issue by smokingplaya** [Facepunch/garrysmod-requests#2333]
### Details
We love lua (partially), and we also love adding possible customization to our addons/scripts as it's good practice. But keeping all configs as lua is not very cool. So I propose to add YAML, JSON, TOML, XML type data saving languages to the allowed languages in **resource.AddSingleFile**.

**Comment by robotboy655** [comment]
I don't see how `resource.AddSingleFile` and your target for customization relate in any way.

`resource.AddSingleFile` marks files to be downloaded from server to client, to the download/ folder, which is static.

What you want to do sounds to me like a job for the `data/` folder and `file.Write/Read` instead, or better yet, just a menu on the client to configure whatever it is you want to the players to be able to configure.

**Comment by garryspins** [comment]
you can quite easily write a system for this yourself, or is it a skill issue🥱
