### ISSUE TITLE
Expose HandleChange_Lua et al. on x86-64 Linux

### ISSUE THREAD

**Issue by Python1320** [Facepunch/garrysmod-requests#2336]
### Details
Please re-expose `HandleChange_Lua` symbol so those who want to live dangerously [can refresh lua files manually](https://github.com/Cynosphere/gbins/blob/47205e62e046658486ac06af716fa62918aa6e5d/manualupdate/src/main.cpp#L49).
We can't use automatic lua refresh due to too many files.

**Comment by robotboy655** [comment]
The function wasn't removed, or even touched, and there's also `lua_refresh_file` console command which does what you want I think?

**Comment by Python1320** [comment]
Thank you, I wasn't aware of the console command.

Almost all symbols are hidden by default now on x86-64 as far as I am aware. 
The original reason from Willox that I heard was that CS:GO branch would be too close to CS:GO in symbols so it could be used by cheaters. 
Now that CS:GO no longer exists it could make sense to revisit the symbol hiding, since they are especially useful for crash stack trace debugging on Linux. Just found a longstanding bug (10 years) on "enginespew", because I could see that the error happened in luajit module and was related to string pushing, etc.
