### ISSUE TITLE
Updated particle editor layout

### ISSUE THREAD

**Issue by homonovus** [Facepunch/garrysmod-requests#2337]
## Details
The particle editor from CS:GO/Alien Swarm has a lot more quality of life improvements compared to the one currently in GMod
Like live previews on the list of particles in your pcf file, or a list view of your currently selected particle's properties

Could the layout & QoL features of those other games be brought into GMod?

![CS:GO's particle editor](https://github.com/Facepunch/garrysmod-requests/assets/13565394/1a4df6db-e104-4cf7-af72-66a8125b9a30)
![GMod's particle editor](https://github.com/Facepunch/garrysmod-requests/assets/13565394/b5d2783c-040e-4142-a825-44762e529867)

**Comment by VpSnipes** [comment]
Single best thing Gmod could have related to particle editing. Though I think the biggest thing to add is consistency when reading the files. As most particle enthesis's have come to know; when opening a particle file each and every parameter location is random. Things like spawning a particle in a radius, will have swapped positions of MANY if not ALL of the parameters you can alter for it. If that was kept more consistent, it'd be better than 90% of the existing particle editors in source as it stands now. @robotboy655 If you're ever able to get around to something like that, it would help a lot of people like you wouldn't believe. Consistency is HUGE especially in development (which I'm sure you're already well acquainted with)

**Comment by homonovus** [comment]
oh yeah, I did notice that occasionally
the particles' initializers & operators would lose their position in the list upon loading the file, taking a random spot in the list instead

**Comment by robotboy655** [comment]
![image](https://github.com/user-attachments/assets/061c2c86-4fe7-4a7c-a0af-13b5e1b07537)

Ported the browser

**Comment by robotboy655** [comment]
![image](https://github.com/user-attachments/assets/e0daf80a-82ad-46bc-8543-4bde77efdc6b)

Ported the properties panel tool, and preview panel got new options as well.
