### ISSUE TITLE
Queue System

### ISSUE THREAD

**Issue by FrankPye** [Facepunch/garrysmod-requests#2338]
### Details
Include your request here

Queue system similar to fivem where people can wait in a queue for full servers instead of spamming trying to join, Think this has been needed for a long long time tbh.

**Comment by MorrowFOC** [comment]
🙏

**Comment by robotboy655** [comment]
![image](https://github.com/Facepunch/garrysmod-requests/assets/3299036/0219817b-05b5-4f22-bd8e-4a35b79ab5c9)
