### ISSUE TITLE
Allow .cache file extension for Material() function

### ISSUE THREAD

**Issue by mgetJane** [Facepunch/garrysmod-requests#2339]
this will make creating materials using thumbnails from `cache/workshop/` more straightforward

currently you have to rename them to png or jpg first (source engine doesnt actually care if the file extension doesnt match since it will just use the file header)

**Comment by robotboy655** [comment]
https://wiki.facepunch.com/gmod/Global.AddonMaterial

**Comment by mgetJane** [comment]
> https://wiki.facepunch.com/gmod/Global.AddonMaterial

oh

in my defence i looked at several workshop addons and they all went to rename the cache file first instead of using this function so i guess i trolled myself into thinking that's the only way to do it
