### ISSUE TITLE
A move to Unix style line-endings

### ISSUE THREAD

**Issue by BreakinBenny** [Facepunch/garrysmod-requests#2340]
### Details
This is probably a very small change, but I think moving on from carriage returns alongside the newlines would be a good one. Those don't have much purpose, and if you run the replacement feature in NPP to delete all instances of `\r` (which is CR) while leaving `\n` (for LF) be, you'll keep some kilobytes especially if this is done on many files that used the DOS-style thing.

@YoYo178 and @Azzyr suggested this way to me during the project to upgrade _Fortress Forever_ to SDK 2013.

**Comment by garryspins** [comment]
Negligible.

**Comment by robotboy655** [comment]
This __really__ doesn't matter, especially for the average player.
