### ISSUE TITLE
allow AddonMaterial() to take material parameters like Material() does

### ISSUE THREAD

**Issue by mgetJane** [Facepunch/garrysmod-requests#2342]
i want to have it generate a texture without mipmaps

**Comment by mgetJane** [comment]
actually, it seems like the only reason AddonMaterial() even exists is to load image files with the `.cache` file extension because Material() doesn't let you do that for whatever reason

Material() also doesn't allow the `.jpeg` and `.gif` extensions even though JPEG and GIF files will be loaded fine if you rename them to have the `.png` or `.jpg` extension

wouldn't it be better to just add `.jpeg`, `.gif`, and `.cache` to the allowed file extensions for Material()?
(i guess maybe mark AddonMaterial() as deprecated in that case since it'd end up being an inferior version of Material())

**Comment by robotboy655** [comment]
I opted to make Material() accept .cache files.
