### ISSUE TITLE
allow GetConVar("sv_password") on the server

### ISSUE THREAD

**Issue by mgetJane** [Facepunch/garrysmod-requests#2345]
you can already get its value in a  less convenient way through the [GM:CheckPassword](https://wiki.facepunch.com/gmod/GM:CheckPassword) hook

i guess maybe also add a convar that disables GetConVar("sv_password") and the GM:CheckPassword hook if it's really a security concern

**Comment by mgetJane** [comment]
my use case is basically just for checking if the server has a password or not

maybe a function called something like `game.IsPasswordProtected()` would be nice if getting sv_password's contents without GM:CheckPassword is infeasible for whatever reason

**Comment by garryspins** [comment]
Yea this doesn't make a whole lot of sense

**Comment by robotboy655** [comment]
No.

**Comment by robotboy655** [comment]
Also duplicate of https://github.com/Facepunch/garrysmod-requests/issues/2067
