### ISSUE TITLE
 Add vbspinfo.exe

### ISSUE THREAD

**Issue by Unusuario2** [Facepunch/garrysmod-requests#2346]
### Details
This tool is very usefull in order to use CompilePal, it reads the hdr levels so CompilePalX can compile the cubemaps properly.
https://developer.valvesoftware.com/wiki/Vbspinfo
https://github.com/ruarai/CompilePal
(and yes vbspinfo.exe of SDK2013SP/MP does not work on large maps, becouse they excede the bsp limits of SDK2013 )

**Comment by robotboy655** [comment]
Ok.

**Comment by Unusuario2** [comment]
thanks!!
