### ISSUE TITLE
Replace Toy Train model to fix collisions

### ISSUE THREAD

**Issue by A1steaksa** [Facepunch/garrysmod-requests#2348]
The PHX toy train model has had broken collisions for a long time.  I decompiled the model, rotated the collision mesh, and recompiled the model to fix this.

## Before:
Credit: Redox
![image](https://github.com/Facepunch/garrysmod-requests/assets/8369707/30b8dda3-7fbf-4248-8b4e-8d718a3deadf)

https://github.com/Facepunch/garrysmod-requests/assets/8369707/d72d4fd4-806c-42ef-a2ef-e49ee9cf940b

## After: 
![image](https://github.com/Facepunch/garrysmod-requests/assets/8369707/de71194f-1e13-425f-ae1d-3b47e0fd1888)

https://github.com/Facepunch/garrysmod-requests/assets/8369707/d3e66c32-cae5-48f1-a7e7-8c897801c13e

## The fixed model and uncompiled source:
[fixed-toy-train.zip](https://github.com/Facepunch/garrysmod-requests/files/14824982/fixed-toy-train.zip)

**Comment by goodusername123** [comment]
Probably just only the rotated `.phy` you compiled should be used/needed rather then replacing the whole model with a recompiled one, unless that causes some issue I'm unaware of.

**Comment by robotboy655** [comment]
Done.
