### ISSUE TITLE
Overhaul Detail.vbsp

### ISSUE THREAD

**Issue by Battlefieldkille** [Facepunch/garrysmod-requests#2351]
I wanted to classify this report as an Issue, but due to many changes needing to be done in order to fix everything, it should be a Request instead.

I had a map that has most of the available textures with grass sprites that I myself made for ease of access when I wanted to use a texture with a specific grass sprite.
There was a single texture that had an Error on itself in Hammer Editor, but the Error would never be seen in-game.
![error](https://github.com/Facepunch/garrysmod-issues/assets/69215350/33fe5984-ecfa-41d1-8e79-1390647b8116)
At the time I ignored it but months later down the line, once I started to mess with decompiling the game and editing VMT files, I decided to take a closer look on why that particular texture had an Error.
The VMT of that texture was using a specific Detail Type, which itself was referencing a non existent model.
Most of HL2 textures that are using these Detail Types have them blocked in their VMTs.

[detailtypes_original.zip](https://github.com/Facepunch/garrysmod-issues/files/14818224/detailtypes_original.zip) < The original **Detail.vbsp**, a map for ease of review & custom textures made specifically to showcase all possible detail sprites/models. ( Put these custom textures in the Materials folder. )
Once you load the map you will see:
**( Left Side )** - All possible Detail Types + Each model being used in them.
**( Right Side )** - All textures using possible Detail Types.
**( Behind )** - All models used by Detail Types.

---------------------------------------------------------------------------------------------------------------------------------------------------
# Detail Types list
This is the list of all Detail Types, followed by whats wrong with them, what models they are using and by what texture they are being used by ( Textures that block Detail Types will be marked like this: X_texture_X ):
| Detail Type | Whats wrong | Model/s used | Used by |
| :-: | :-: | :-: | :-: |
| `swamp_land_001` | Missing textures | `grass_swamp_001a.mdl` `grass_swamp_001b.mdl` `grass_tuft_003a.mdl` `grass_tuft_004b.mdl` | No texture uses this Detail Type! |
| `swamp_land_002` | Missing models | `grass_swamp_001a.mdl` `grass_swamp_001b.mdl` `grass_tuft_001a.mdl` `grass_tuft_001b.mdl` | No texture uses this Detail Type! |
| `swamp_water_001` | Missing textures | `grass_tuft_001a.mdl` `grass_tuft_001b.mdl` `grass_tuft_003a.mdl` `grass_tuft_004b.mdl` | No texture uses this Detail Type! |
| `grassland1` | Missing textures | `grass_tuft_004a.mdl` `grass_tuft_004b.mdl` `grass_tuft_004c.mdl` `grass_tuft_004d.mdl` `grass_tuft_001a.mdl` `grass_tuft_001b.mdl` | `X_blenddirtgrass001a_X` |
| `grassland2` | Missing models | `w_traffcone.mdl` | No texture uses this Detail Type! |
| `rocks1` | Missing models/textures | `rocksground01a.mdl` `rocksground01b.mdl` `rocksground01c.mdl` `rocksground01d.mdl` `rocksground01e.mdl` `rocksground02a.mdl` `rocksground02b.mdl` `rocksground02c.mdl` | `X_blendrockdirt005b_lowfrict_X` `X_blendrockdirt006a_X` `X_blendrockdirt006b_lowfrict_X` `X_blendrockdirt007d_X` `X_blendrockdirt008c_X` `X_blendrockdirt008d_X` `X_blendrocksand008c_X` `X_blendrocksgrass005a_X` `X_blendrocksgrass006a_X` |
| `grassland3` | Missing models/textures | `shrub_01a.mdl` `shrub_03a.mdl` `shrub_03c.mdl` `grass_tuft_001.mdl` | No texture uses this Detail Type! |
| `test` | Missing textures | `grass_tuft_001a.mdl` `grass_tuft_001b.mdl` `grass_tuft_003a.mdl` `grass_tuft_004b.mdl` `grass_tuft_004a.mdl` `grass_tuft_004c.mdl` | No texture uses this Detail Type! |
| `grass01` | Nothing | None | `blenddirtgrass001b` |
| `grass02` | Nothing | None | No texture uses this Detail Type! |
| `coastline_grass01` | Nothing | None | `blenddirtgrass005a` `blenddirtgrass006a` `blendsandgrass008a` `blendsandsand008a` `X_blendsandsand008b_antlion_X` |
| `coastline_grass02` | Nothing | None | No texture uses this Detail Type! |
| `coastline_redgrass01` | Nothing | None | `blenddirtgrass008a` `blendmuddirt001a` `blendrockgrass004a` |
| `coastline_redgrass02` | Nothing | None | `blendgrassgravel001a` `blendgrassgravel002a` |
| `coastline_redgrass03` | Nothing | None | `blendgrassgravel001b` |
| `citygrass01` | Nothing | None | `blenddirtdirt001a` `dirtfloor001a` |
| `redgrass` | Nothing | None | `red_grass` |
| `redgrass_light` | Nothing | None | `red_grass_thin` |
| `short_redgrass` | Nothing | None | `short_red_grass` |
| `PerfTest1` | Missing textures | `grass_tuft_004a.mdl` `grass_tuft_004b.mdl` | `blendrockdirt001a` |
| `canal_reeds` | Nothing | `cattails.mdl` | `blendsandrock004c` `canal_reeds` |
| `rocks_redgrass` | Missing models | `detail_rocks01a.mdl` | `X_blendrocksand008d_X` `rocks_red_grass` |
| `street_junk` | Missing models | `detail_junk01.mdl` `detail_junk02.mdl` `detail_junk03.mdl` | No texture uses this Detail Type! |

[all_textures_with_detailtypes.zip](https://github.com/Facepunch/garrysmod-requests/files/14858782/all_textures_with_detailtypes.zip) - A zip file containing all VMTs that reference these Detail Types, I wanted to include even those Detail Types that are blocked for the sake of documentation.

---------------------------------------------------------------------------------------------------------------------------------------------------
# All models inside the Detail Types
Now I will list the actual models that the **Detail.vbsp** contains, whats wrong with them, their game of origin and how they are supposed to look like:
| Model name | Whats wrong | Game of origin | How its supposed to look like |
| :-: | :-: | :-: | :-: |
| `grass_swamp_001a.mdl` | This model doesnt exist! | HL2 Beta | ![grass_swamp_001a](https://github.com/Facepunch/garrysmod-issues/assets/69215350/7da2e03d-eb3e-463a-911b-024a194531c2) |
| `grass_swamp_001b.mdl` | This model doesnt exist! | HL2 Beta | ![grass_swamp_001b](https://github.com/Facepunch/garrysmod-issues/assets/69215350/55d5bbb0-42f9-4878-9c69-0f7c4004fb39) |
| `grass_tuft_001.mdl` | This model has no texturing! | HL2 Beta | ![Grass_tuft_001](https://github.com/Facepunch/garrysmod-issues/assets/69215350/a430d5ad-1735-45f1-9c9b-b02905e9a776) |
| `grass_tuft_001a.mdl` | This model has no texturing! | HL2 Beta | ![Grass_tuft_001a](https://github.com/Facepunch/garrysmod-issues/assets/69215350/04e9e866-3cc0-4805-ac03-88c07a78a3e3) |
| `grass_tuft_001b.mdl` | This model has no texturing! | HL2 Beta | ![Grass_tuft_001b](https://github.com/Facepunch/garrysmod-issues/assets/69215350/ca82e155-ccdf-4b3e-bee4-28e89c81cfe4) |
| `grass_tuft_003a.mdl` | This model has no texturing! | HL2 Beta | ![Grass_tuft_003a](https://github.com/Facepunch/garrysmod-issues/assets/69215350/e74d3312-5b93-486e-bb37-fda0516e1ce5) |
| `grass_tuft_004a.mdl` | This model has no texturing! | HL2 Beta | ![Grass_tuft_004a](https://github.com/Facepunch/garrysmod-issues/assets/69215350/a3701c1f-ee66-481c-a3fc-97aff0e74028) |
| `grass_tuft_004b.mdl` | This model has no texturing! | HL2 Beta | ![Grass_tuft_004b](https://github.com/Facepunch/garrysmod-issues/assets/69215350/ef5e8a7d-7963-4fee-98cb-f8f52bd35ced) |
| `grass_tuft_004c.mdl` | This model has no texturing! | HL2 Beta | ![Grass_tuft_004c](https://github.com/Facepunch/garrysmod-issues/assets/69215350/68abeebb-2bb7-4a55-911a-0b8a51682788) |
| `grass_tuft_004d.mdl` | This model has no texturing! | HL2 Beta | ![Grass_tuft_004d](https://github.com/Facepunch/garrysmod-issues/assets/69215350/100c4820-dfa3-4fb7-9577-3cbe70558984) |
| `w_traffcone.mdl` | This model doesnt exist! | HL2 Beta | ![W_TraffCone](https://github.com/Facepunch/garrysmod-issues/assets/69215350/355f044b-316f-4014-9571-dcd722269589) |
| `rocksground01a.mdl` | This model has no texturing! | HL2 Beta | ![rocksground01a](https://github.com/Facepunch/garrysmod-issues/assets/69215350/0a84dce9-bc3a-4847-8114-f53ed09b24a7) |
| `rocksground01b.mdl` | This model has no texturing + Cant be seen in-game due to an Error in console: **Detail prop model models/perftest/rocksground01b.mdl is using vertex-lit materials!** | HL2 Beta | ![rocksground01b](https://github.com/Facepunch/garrysmod-issues/assets/69215350/c2ceff36-b774-479b-9da3-2f05581f50dc) |
| `rocksground01c.mdl` | This model has no texturing! | HL2 Beta | ![rocksground01c](https://github.com/Facepunch/garrysmod-issues/assets/69215350/e85619cd-ac39-4d24-b77c-3af94530649f) |
| `rocksground01d.mdl` | This model has no texturing! | HL2 Beta | ![rocksground01d](https://github.com/Facepunch/garrysmod-issues/assets/69215350/0453d0e5-5869-49ac-a317-a42c14b1bd75) |
| `rocksground01e.mdl` | This model has no texturing! | HL2 Beta | ![rocksground01e](https://github.com/Facepunch/garrysmod-issues/assets/69215350/4e231df0-f67c-4505-b3c1-1bacb8f51417) |
| `rocksground02a.mdl` | This model has no texturing! | HL2 Beta | ![rocksground02a](https://github.com/Facepunch/garrysmod-issues/assets/69215350/d8e35a22-e372-4285-bf27-3a1145bf6234) |
| `rocksground02b.mdl` | This model has no texturing! | HL2 Beta | ![rocksground02b](https://github.com/Facepunch/garrysmod-issues/assets/69215350/20daab50-25fe-4ae3-9dac-90962c2a79ab) |
| `rocksground02c.mdl` | This model has no texturing! | HL2 Beta | ![rocksground02c](https://github.com/Facepunch/garrysmod-issues/assets/69215350/81b3e9f4-fd3f-475a-853a-50f9594e74ba) |
| `shrub_01a.mdl` | Cant be seen in-game due to an Error in console: **Detail prop model models/props_foliage/shrub_01a.mdl is using vertex-lit materials!** | HL2 Beta | ![shrub_01a](https://github.com/Facepunch/garrysmod-issues/assets/69215350/9e6a5224-5e88-4c13-be1a-ce5c50d149a5) |
| `shrub_03a.mdl` | This model doesnt exist! | HL2 Beta | ![Shrub_03a](https://github.com/Facepunch/garrysmod-issues/assets/69215350/ad945118-d7e8-4cf0-92f7-48f8ae6e8340) |
| `shrub_03c.mdl` | This model doesnt exist! | HL2 Beta | ![Shrub_03c](https://github.com/Facepunch/garrysmod-issues/assets/69215350/1d44a8a2-ca20-4c79-82d7-5868149be2c5) |
| `cattails.mdl` | Works fine. | HL2 | ![cattails](https://github.com/Facepunch/garrysmod-issues/assets/69215350/f040829a-9688-435b-b78b-95ce5dacf1c3) | 
| `detail_rocks01a.mdl` | This model doesnt exist! | Unknown | Unknown |
| `detail_junk01.mdl` | This model doesnt exist! | Unknown | Unknown |
| `detail_junk02.mdl` | This model doesnt exist! | Unknown | Unknown |
| `detail_junk03.mdl` | This model doesnt exist! | Unknown | Unknown |

---------------------------------------------------------------------------------------------------------------------------------------------------
# Fixing everything
I will explain bit by bit on how to fix everything manually or you could download the few links I will provide and just replace those files.
Lets start off with the **Detail.vbsp** itself, some Detail Types are straight up unfixable while some of them require a tiny bit of work to function as intended.
Notepad is enough to modify this file, its located in: **GarrysMod/garrysmod/detail.vbsp**
Keep in mind im not asking for the actual models to be removed, just for them to be commented out of this file.

---------------------------------------------------------------------------------------------------------------------------------------------------
### 1. Swamp Grasses, Tufts, Traffic Cone, Shrubs & Detail Junks
This is the list of the Detail Types that have models/textures that simply cannot be fixed since the files were abandoned in HL2 Beta, part of me wishes we could use those files but we obviously cant due to licensing issues.
`swamp_land_001` - Broken beyond repair, should be removed.
`swamp_land_002` - Broken beyond repair, should be removed.
`swamp_water_001` - Broken beyond repair, should be removed.
`grassland1` - Broken beyond repair, should be removed.
`grassland2` - Broken beyond repair, should be removed.
`test` - Broken beyond repair, should be removed.
`street_junk` - Broken beyond repair, should be removed.
![1](https://github.com/Facepunch/garrysmod-issues/assets/69215350/accbd27e-c029-4945-b848-1fe2d6ea178a)![2](https://github.com/Facepunch/garrysmod-issues/assets/69215350/37b5de65-4149-4b4f-ae20-9cc9a91a3dd9)![3](https://github.com/Facepunch/garrysmod-issues/assets/69215350/5cc84528-c9bc-4bc7-8ac7-615e046c43d6)![4](https://github.com/Facepunch/garrysmod-issues/assets/69215350/f7cad8c2-a149-4b86-9a16-463b8dddcbd6)![5](https://github.com/Facepunch/garrysmod-issues/assets/69215350/4589d1a8-5d0d-44a0-b7b4-5410ce247c21)![6](https://github.com/Facepunch/garrysmod-issues/assets/69215350/0cb424ae-7db2-4997-99d2-b622a3a8371e)![7](https://github.com/Facepunch/garrysmod-issues/assets/69215350/28d7317a-1400-49c3-9418-f6c618e315a2)![8](https://github.com/Facepunch/garrysmod-issues/assets/69215350/20cdafd8-5d0a-49a2-ac99-b6ee50fff7eb)![9](https://github.com/Facepunch/garrysmod-issues/assets/69215350/529d929f-69b1-4131-b192-443ebc835b34)![10](https://github.com/Facepunch/garrysmod-issues/assets/69215350/6cf10f76-6b20-4a7d-b9d2-1345f6e445f6)![11](https://github.com/Facepunch/garrysmod-issues/assets/69215350/2d05b608-0362-4303-8414-2ae1f7c8a0d9)![12](https://github.com/Facepunch/garrysmod-issues/assets/69215350/b16817a7-c806-404b-b278-c4e0977e9adc)![13](https://github.com/Facepunch/garrysmod-issues/assets/69215350/4c05ec5e-dafc-4c8e-b941-f877bec67350)![15](https://github.com/Facepunch/garrysmod-issues/assets/69215350/44575585-65dd-482f-a634-ce3622073f4e)![16](https://github.com/Facepunch/garrysmod-issues/assets/69215350/348230ce-a486-4bbe-98b5-e62c37acf044)![17](https://github.com/Facepunch/garrysmod-issues/assets/69215350/e304810c-6add-460d-b2b8-5b8ded52ecc0)
If the models are outright removed from these Detail Types, we will only have a completely empty Detail Type so I think we should just opt to completely remove these Detail Types.
Very few base HL2 textures are using these Detail Types but those that do use them are having them blocked in their VMTs so no map will be affected by this change, the VMTs looking like this:
![Example1](https://github.com/Facepunch/garrysmod-issues/assets/69215350/29e5d2b3-4111-4d3e-b50d-73a71f9d1b7b)![Example2](https://github.com/Facepunch/garrysmod-issues/assets/69215350/eb86fece-6e84-4b96-9ba6-1cc30036d9e2)

---------------------------------------------------------------------------------------------------------------------------------------------------
### 2. Tufts & Detail Rocks
`PerfTest1` - I didnt want to completely remove this Detail Type as it has functional grass sprites, I instead removed these 2 models referenced within the Detail Type:
![Example3](https://github.com/Facepunch/garrysmod-issues/assets/69215350/15282a42-57ae-4eca-9031-01b9610304bd)![Example4](https://github.com/Facepunch/garrysmod-issues/assets/69215350/b70a9f92-b1a2-4f5e-9468-272ea5e7f778)
Fixing this would mean that any map with the texture `blendrockdirt001a` will now all of a sudden lose the Tuft models if the map is recompiled, but I dont know any sane mapper that would purposely use these broken models in their maps.
`rocks_redgrass` - This is what started all of this, the first image on this post. This Detail Type is referencing a model that doesnt exist in the game at all, but it can only be seen in Hammer Editor.
Despite that, I decided to remove that model in order to prevent confusion when mappers use the texture `rocks_red_grass`.
![Example5](https://github.com/Facepunch/garrysmod-issues/assets/69215350/40b1d224-eb19-435e-9cb1-ee1d18e749b7)![Example6](https://github.com/Facepunch/garrysmod-issues/assets/69215350/eadd7ded-0035-42cb-998a-0b9dc726d044)
![14](https://github.com/Facepunch/garrysmod-issues/assets/69215350/26725133-0daf-48c4-beb3-b9d0391e09de)

---------------------------------------------------------------------------------------------------------------------------------------------------
### 3. Unused Construct Grass
`grassland3` - Originally, I removed this Detail Type due to it having missing models/textures much like the other Detail Types mentioned in the 1st section.
But at one point while researching all of this, a guide on GameBanana listed all various detail sprites from some Valve games.
One of those detail sprites was the unused gm_construct grass which was present in the older versions of the map.
`construct_grass.vmt` & `gm_construct_grass.vmt` directly reference the non existent `construct_grass` Detail Type:
![Example12](https://github.com/Facepunch/garrysmod-issues/assets/69215350/2ce73629-3260-459b-afd9-c3772dd0b6aa)![Example13](https://github.com/Facepunch/garrysmod-issues/assets/69215350/00187e01-6010-4b67-adb2-a9a0b29ec1fd)
I realized that this would be a great opportunity to re-add this grass so it could be usable again, no HL2 texture uses this Detail Type.
The original density of this Detail Type was 1500.0 but I set it to 3000.0.
![Example7](https://github.com/Facepunch/garrysmod-issues/assets/69215350/219e2a5c-978a-45aa-a900-378f357bf310)![Example8](https://github.com/Facepunch/garrysmod-issues/assets/69215350/89caed58-0eb8-4572-a1d2-08530aeebe58)
It is also worth mentioning that before reworking this Detail Type, it tried to generate `shrub_01a.mdl` which cant load in-game due to **Detail prop model models/perftest/rocksground01b.mdl is using vertex-lit materials!** - This means that in order for the model to be generated on the texture, its VMT would need to have **UnlitGeneric** instead of **VertexLitGeneric** - but dont do this.
I have good reason to believe that the `shrub_01a.mdl` we currently have isnt the original one and was instead a replacement, the old one was simply left forgotten by Valve.
This is the original:
![Shrub_01a](https://github.com/Facepunch/garrysmod-issues/assets/69215350/7c67d0e9-0bf7-461b-8b6b-de8519afbc61)

---------------------------------------------------------------------------------------------------------------------------------------------------
### 4. Rocks
This Detail Type needs its own section as it cant be fixed through **Detail.vbsp** itself, we instead have to edit a few VMTs.
I used Crowbar to unpack the VPK and to also decompile the models to figure out what VMT they are trying to use.
I am unsure if there is a way to edit these files without unpacking and repacking the entire VPK file.
Notepad is enough to modify these files, they are located in: **GarrysMod\sourceengine\hl2_misc_dir.vpk\root\materials\perftest\rock_wasteland01a.vmt**
**GarrysMod\sourceengine\hl2_misc_dir.vpk\root\materials\perftest\rockcliff02b.vmt**
**GarrysMod\sourceengine\hl2_misc_dir.vpk\root\materials\perftest\rockground03a.vmt**
`rocks1` - I was greatly disappointed when I realized we were always meant to have randomly generated rocks on some textures, this was the main inspiration to continue to try and fix all this.
![18](https://github.com/Facepunch/garrysmod-issues/assets/69215350/e90cfc7b-6128-4569-a7ec-80e8d540893a)![19](https://github.com/Facepunch/garrysmod-issues/assets/69215350/385f1e5a-e2e3-446f-834c-e982cc89e109)![20](https://github.com/Facepunch/garrysmod-issues/assets/69215350/8dda11bd-7dca-420c-836f-c174add6d159)![21](https://github.com/Facepunch/garrysmod-issues/assets/69215350/42476666-2199-4b7c-acc5-197eeab26047)![22](https://github.com/Facepunch/garrysmod-issues/assets/69215350/bb3a71ac-866a-4def-a844-81d369bf3259)![23](https://github.com/Facepunch/garrysmod-issues/assets/69215350/5e2778a3-3b46-49a9-94e6-8249cc87d135)![24](https://github.com/Facepunch/garrysmod-issues/assets/69215350/982309c6-cdcf-4d35-b9e7-f06300bbd8db)![25](https://github.com/Facepunch/garrysmod-issues/assets/69215350/bfd5d3c2-76ea-475a-8d8c-cdc1ed896574)
I had to remove `rocksground01a.mdl` & `rocksground02a.mdl` from the **Detail.vbsp** because they were always dark when they generated on the displacements, I tried moving their illuminated origin around to no avail, I guess im too dumb.
![rawr](https://github.com/Facepunch/garrysmod-issues/assets/69215350/6569896d-c0b5-4424-967f-058afe4a7a60)
But removing `rocksground01a.mdl` was kind of necessary since it contained big rocks, given that these are details, they generate with no collision and its kind of ugly to interact with them because of that.
However I still want this prop fixed despite removing it, the VMT for that prop needs to be modified:
`rock_wasteland01a.vmt` - **$basetexture** needs to point to **perftest/rock_wasteland01a**.
![exampru1](https://github.com/Facepunch/garrysmod-issues/assets/69215350/2ae72fa1-8c0d-4198-989f-0a0b07dc508b)
Also removing `rocksground02a.mdl` because of it being dark all the time is a bit unfortunate but the prop is identical to its counterparts so its really insignificant.
`rocksground01b.mdl` can never be seen in game due to **Detail prop model models/perftest/rocksground01b.mdl is using vertex-lit materials!**, meaning it needs to use **UnlitGeneric** shader for it to properly work.
That obviously means the model itself will never have any lighting unfortunately, much like `cattails.mdl`.
This was also mentioned in #1295.
Valve Developer Community states that it can be fixed:
> To allow **VertexLitGeneric** models, open game\client\detailobjectsystem.cpp and remove the conditional block from CDetailObjectSystem::UnserializeModelDict().

I have absolutely no clue where this file even is or whether or not it would break anything in the game if tampered with.
For now lets just try to fix these rocks in a way that we know works.
`rockcliff02b.vmt` - It uses **VertexLitGeneric** shader, it has to be **UnlitGeneric** + **$basetexture** needs to point to **perftest/rockcliff02b**.
![Example10](https://github.com/Facepunch/garrysmod-issues/assets/69215350/ad016766-7bd4-438b-9894-197d02a453be)
`rockground03a.vmt` - **$basetexture** needs to point to **perftest/rockground03a**.
![Example11](https://github.com/Facepunch/garrysmod-issues/assets/69215350/4d55ccb9-6c20-49f3-91c4-7fa5effa1e88)
[rocks.zip](https://github.com/Facepunch/garrysmod-issues/files/14857465/rocks.zip) - A zip file with fixed VMTs, I double checked to make sure that modifying these 3 VMTs wouldnt break any other existing rock model.

---------------------------------------------------------------------------------------------------------------------------------------------------
[detailtypes_overhauled.zip](https://github.com/Facepunch/garrysmod-issues/files/14857462/detailtypes_overhauled.zip) - The fixes I provided were all applied to this zip file aswell, it has a modified **Detail.vbsp** and it also has a map for ease of review to how it all looks like. I DID NOT modify any other Detail Type that didnt need fixing, only stuff from the "Fixing everything" section was changed.

---------------------------------------------------------------------------------------------------------------------------------------------------
![Untitled](https://github.com/Facepunch/garrysmod-issues/assets/69215350/4b789be7-7291-4d86-936d-6b31afb9294a)
Its been almost 2 decades and nobody ever tried fixing this, so why am I requesting it?
This is for the mappers.
Giving them more accessibility and working tools to play with, I also feel like its just a great missed opportunity to not have this working as intended.

( Side note 1: Yes im aware EP1/2 Detail Types exist and that no HL2 texture is using them, but I decided to not mention them in this post since some need their own episodic models which GMOD obviously doesnt have. )
( Side note 2: Seems like `grass_01.vmt` used to have `tf_forest_grass` Detail Type but its blocked now, interesting. )
![sarma](https://github.com/Facepunch/garrysmod-issues/assets/69215350/6d0fa58e-fde9-4d3c-8641-f26c7e4e6e0e)

**Comment by robotboy655** [comment]
I appreciate the detailed report and the map files.

Here's the summary of the changes:
* Fixed the missing materials on the rock/grass models
* `detail_junk01.mdl` and others replaced with junk-like models that is already shipped with the game
* Replaced usages of `grass_tuft_001a` with `grass_tuft_001`, because the 001a variant has badly applied texture (it's a model issue)
* Renamed `test` to `grassland2`, removed the original `grassland2`, it makes no sense for it to be just traffic cones
* Replaced usage of `models/props_foliage/detail_rocks01a.mdl` with `models/perftest/rocksground02b.mdl`
* Restored grass_swamp models & textures
* Removed usage of `shrub_03a` and `shrub_03c`

The textures/models came from the (private) Source Engine licensee repository.

I am not sure this was worth the effort, but at least there are no longer any missing textures/models with the default detail.vbsp.

**Comment by Battlefieldkille** [comment]
> I appreciate the detailed report and the map files.
> 
> Here's the summary of the changes:
> 
> * Fixed the missing materials on the rock/grass models
> * `detail_junk01.mdl` and others replaced with junk-like models that is already shipped with the game
> * Replaced usages of `grass_tuft_001a` with `grass_tuft_001`, because the 001a variant has badly applied texture (it's a model issue)
> * Renamed `test` to `grassland2`, removed the original `grassland2`, it makes no sense for it to be just traffic cones
> * Replaced usage of `models/props_foliage/detail_rocks01a.mdl` with `models/perftest/rocksground02b.mdl`
> * Restored grass_swamp models & textures
> * Removed usage of `shrub_03a` and `shrub_03c`
> 
> The textures/models came from the (private) Source Engine licensee repository.
> 
> I am not sure this was worth the effort, but at least there are no longer any missing textures/models with the default detail.vbsp.

That is sick, I got no words. :heart:

**Comment by Battlefieldkille** [comment]
One thing I noticed:
![1](https://github.com/Facepunch/garrysmod-requests/assets/69215350/62114391-39c2-43f4-8cf9-ea8f4c013a82)
`rocksground01c.mdl`
`rocksground01d.mdl`
`rocksground01e.mdl`
`rocksground02a.mdl`
`rocksground02b.mdl`
`rocksground02c.mdl`
These rocks all use the same texture but they are still UnlitGeneric instead of VertexLitGeneric.

Would it be a good idea to apply VertexLitGeneric to these new Grass Swamps, Grass Tufts, & old Cattails? I understand if not.
![2](https://github.com/Facepunch/garrysmod-requests/assets/69215350/46b9ed03-dc33-4683-8b58-12ed53cfe090)
This is how the old Cattails model would look like with VertexLitGeneric, I observed no errors with it.

**Comment by robotboy655** [comment]
`UnlitGeneric` is what those materials already had set, and detail props normally want that shader as well, so I don't think changing base game content like that is a good idea.

There's also the issue of detail props not accepting flashlight light at all, vertexlit or not.

**Comment by Battlefieldkille** [comment]
> `UnlitGeneric` is what those materials already had set, and detail props normally want that shader as well, so I don't think changing base game content like that is a good idea.
> 
> There's also the issue of detail props not accepting flashlight light at all, vertexlit or not.

Fair.
