### ISSUE TITLE
`lua_log_cl` convar for `clientside_errors.txt`

### ISSUE THREAD

**Issue by wrefgtzweve** [Facepunch/garrysmod-requests#2373]
### Details
Currently the convar `lua_log_sv` exists which when enabled logs all server errors to `garrsymod/lua_errors_server.txt`, however there is no `lua_log_cl` equivalent. By default every client error gets written to this file which most servers don't use/ignore serving no purpose but bloat.
It'd be helpful if there was a convar to toggle this feature off / have it off by default like sv errors.

**Comment by robotboy655** [comment]
![image](https://github.com/Facepunch/garrysmod-requests/assets/3299036/f9599541-d42c-4abf-aae2-cbf0cc6d274c)

Huh?

**Comment by shockpast** [comment]
> ![image](https://private-user-images.githubusercontent.com/3299036/326518367-f9599541-d42c-4abf-aae2-cbf0cc6d274c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MDk0NDIsIm5iZiI6MTcxNDQwOTE0MiwicGF0aCI6Ii8zMjk5MDM2LzMyNjUxODM2Ny1mOTU5OTU0MS1kNDJjLTRhYmYtYWFlMi1jYmYwY2M2ZDI3NGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjlUMTY0NTQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGJjMTEwYWNkNjI1NTIwYjRjYzYxNGVlMGI4YzIyZjIzY2FkNjA1MTRhNzc0ODZkZjFiNGFhMDM4MGJjMjE4OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Ur9sV7dXengpi6Utrjz1JjQYbrIL_nYRdy_HEKtA3SI)
> 
> Huh?

Server logs all clientside errors into `clientside_errors.txt` and there is no `lua_log_cl` command to disable it, only `lua_log_sv` that disables only serverside stuff
