### ISSUE TITLE
Check to get legitimate owner of GMod

### ISSUE THREAD

**Issue by Cyberuben** [Facepunch/garrysmod-requests#238]
I'd like to see an addition to Garry's Mod's function. A steamworks function to get the Steam ID of the user who owns the game, in case the game is shares.

Family sharing has become an issue and way too many people use it to test their hacks without any fear of being banned. A new account can be created within 3 minutes so the player is unbanned on every server again. Adding functionality to get the owner of the shared game can help many game servers to auth if the original owner is banned already, making it impossible to avoid bans using Family Share. Since VPNs and dynamic IPs have become such easy to use tools, an IP ban is simply not enough anymore. It will not solve the family sharing issue.

A function like this still allows the games to be shared, but if one person gets banned, all others could get banned too. 

As mentioned by a Valve employee, this has been possible for a while:
http://steamcommunity.com/groups/familysharing/discussions/0/792924412076257902/#c648811126385548052
Update 1.26: http://steamcommunity.com/groups/steamworks#announcements/detail/1606951947121753685

**Comment by zerfgog** [comment]
Not sure if this is would be considered a closing solution, but the Steam Web API has a method of doing this which you can use in CheckPassword or whatever.

**Comment by Kefta** [comment]
http://facepunch.com/showthread.php?t=1341204&p=43469693&viewfull=1#post43469693

**Comment by xaviergmail** [comment]
View "duplicate" for information on implementation detail - #1664

**Comment by robotboy655** [comment]
Added `Player.OwnerSteamID64()`, serverside only, returns the SteamID of family sharing owner of the game license (or just the player's SteamID if not using FS), will be 0 before player is fully authed.
