### ISSUE TITLE
add AO comands in the common options of vrad.

### ISSUE THREAD

**Issue by Unusuario2** [Facepunch/garrysmod-requests#2383]
### Details
In the common options of vrad, the ambient occlusion commands are missing (there is no documentacion in the gmod compilers so it is imposible to use them) (the github comment about ambient occlusion https://github.com/Facepunch/garrysmod-requests/issues/2264)
![image](https://github.com/Facepunch/garrysmod-requests/assets/110506367/e1849086-d9bc-4d1e-ae9e-b90edd9e16cf)

Please add all the missing commands related to the ambient occlusion in the common options of vrad.

**Comment by robotboy655** [comment]
They are there, you are using outdated compilers. The AO options are only available in `dev` or `x86-64` beta, they are not released as part of an update yet.

**Comment by Unusuario2** [comment]
are you sure? i have the dev branch of gmod 
![image](https://github.com/Facepunch/garrysmod-requests/assets/110506367/9722c9af-e434-490b-8bba-07ff3cccc72a)

**Comment by robotboy655** [comment]
You are trying to use `bin/win64` files on `dev` beta which doesn't ship those files, therefore it is out of date.

I don't even know how you have those files without the `x86-64` beta, you must've placed them there yourself.

But yes, I am very certain:
![image](https://github.com/Facepunch/garrysmod-requests/assets/3299036/0755542d-e85e-4bb7-858c-e4cb2911441e)

**Comment by Unusuario2** [comment]
To be honest i have no idea how steam downloaded those files, but thanks!
