### ISSUE TITLE
Add Missing Parameter to NPC:StopMoving()

### ISSUE THREAD

**Issue by DrVrej** [Facepunch/garrysmod-requests#2385]
Currently the NPC method `StopMoving` is missing an essential parameter `bImmediate`, by default it's set to true, which is what the binded Lua version is set to. However, in the Lua version we don't have the ability to set it to false. When set to false, the NPC will gradually slow down using its locomotion rather than doing a sudden stop. This should be a quick implement, thank you.

Link: https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/ai_navigator.cpp#L911

**Comment by robotboy655** [comment]
Done.
