### ISSUE TITLE
Bind NPC:GetArrivalSpeed and NPC:GetArrivalDistance to Lua

### ISSUE THREAD

**Issue by DrVrej** [Facepunch/garrysmod-requests#2386]
We already have `SetArrivalSpeed` and `SetArrivalDistance` but their getter methods aren't binded

NPC:GetArrivalSpeed ->https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/ai_navigator.cpp#L1072
NPC:GetArrivalDistance -> https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/ai_navigator.cpp#L1106

**Comment by robotboy655** [comment]
Done.
