### ISSUE TITLE
Lua binding for CNewParticleEffect::GetRenderBounds

### ISSUE THREAD

**Issue by NO-LOAFING** [Facepunch/garrysmod-requests#2389]
### Details
https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/client/particles_new.cpp#L364
The use case I had in mind was to automatically make a CNewParticleEffect fit nicely inside a model panel, like spawnicons do for models.

**Comment by robotboy655** [comment]
Done.
