### ISSUE TITLE
Allow players to open console on the main Gmod menu

### ISSUE THREAD

**Issue by brandonsturgeon** [Facepunch/garrysmod-requests#2391]
### Details
For me (on main branch), if I'm at the main menu and don't have console open, I have to open the Options or Legacy Browser UI elements for my console keybind to work.

I would like to be able to open it with my keybind from the main menu without opening a new UI element 👍

e: Looks like it's working on x86-64? Is this a bug?

**Comment by robotboy655** [comment]
Either hold the console key, or use SHIFT+ESC.

**Comment by A1steaksa** [comment]
I can confidently say this functionality (Both holding the console key and the `shift`+`esc` hotkey) is entirely new to me.

I've been opening the Options menu every time for years.  I had assumed it was a bug where the VGUI system didn't initialize until one of menu buttons forced it to, after which point the console would open as expected

**Comment by brandonsturgeon** [comment]
Same! Both of these are completely new to me as well. Very neat.

I see Rubat mentions Shift+Esc in Discord pretty regularly but maybe I never noticed.

I wonder if there's a good place on the wiki for this knowledge 🧠
