### ISSUE TITLE
`steamworks.FileInfo` on the Serverside

### ISSUE THREAD

**Issue by wrefgtzweve** [Facepunch/garrysmod-requests#2395]
### Details
Currently there's no easy way to get addon information on serverside, it'd be rather useful to be able to get when certain addons updated to detect auto restarts or know when the current map has updated so you can switch off it / restart.

I know there's https://github.com/WilliamVenner/gmsv_workshop which adds this functionality but that's a dll, having it in base gmod would be pretty useful and should be relatively easy to implement.

**Comment by robotboy655** [comment]
Done.
