### ISSUE TITLE
Add PhysicsSolidMaskForEntity for entities

### ISSUE THREAD

**Issue by TheMostUpset** [Facepunch/garrysmod-requests#2397]
Lua entities can't touch hitboxes without hacky ways like checking trace every tick, but engine entities like HL2 or HL1 rocket actually can, and I guess this is where it being set: https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/game/server/hl2/weapon_rpg.cpp#L191
Please add same thing for lua entities, so SOLID_BBOX ones would be able to detect hitboxes on touch.

**Comment by RandomCatDude** [comment]
I'm developing an addon that's required faithfully replicating alot of HL2 behaviour and I just ran into this while replicating the crossbow bolts. would extremely appreciate having access to this.

**Comment by RandomCatDude** [comment]
is there anything stopping this from being implemented?? im finding that there really isn't a reasonable workaround to my problem, which would be entirely solved by just having access to this as a hook.

**Comment by robotboy655** [comment]
Added as `ENT.PhysicsSolidMask`. If left unset, falls back to the default value. On `dev`/`x86-64` betas right now.

**Comment by robotboy655** [comment]
I had to roll this back as it was causing unexpected issues, I will have another swing next week.

**Comment by robotboy655** [comment]
Should be good now.
