### ISSUE TITLE
Bind Awesomium.SetAcceptLanguage

### ISSUE THREAD

**Issue by samuelmaddock** [Facepunch/garrysmod-requests#24]
It would be nice if the AcceptLanguage property could be set on Awesomium web panels. However, it would be fine if it was automatically set by Garry's Mod, grabbing the user's language preference.

I'd like to be able to see the user language demographic playing my gamemode. I have Google Analytics setup on a commonly viewed webpage, which tells me the demographic. Since the Awesomium browser's language is not set, I get this:

![Languages](http://samuelmaddock.com/up/2013-06-12_18-53-52.png)

I understand this only applies to a very small audience of developers, but I hope you still consider implementing it. Here's the page on the Awesomium docs: http://docs.awesomium.net/html/P_Awesomium_Core_WebPreferences_AcceptLanguage.htm

**Comment by CaskoChan** [comment]
@robotboy655 Since Awesomium is going to be replaced, may as well close this.

**Comment by thegrb93** [comment]
Not until it's replaced
