### ISSUE TITLE
Make lua_errors_url send the gamemode name & also fix the convar updating when client leaves. 

### ISSUE THREAD

**Issue by TeddiO** [Facepunch/garrysmod-requests#240]
I've started making use lua_errors_url and found it quite handy. However it appears to be persisting somehow through states (what I presume is sandbox) because I've had other entries randomly appear on my page ( http://bbroleplay.co.uk/lauerrors/index.php ). 

All the errors on there with a addon (workshop) link I do not use or supply on any of my servers, yet they appear to be finding their way on to my page via what I presume is the convar not being updated (people could be pointing their convar to the page, but it seems unlikely). I can't filter the IP because when the client errors, it sends it directly from themselves as opposed to proxying via the server. 

Being able to directly filter which gamemodes can access (when passed via POST and I guess proper updating of the convar when the client leaves) would be pretty awesome outside of having to parse the error string each time to see if we can grab the gamemode.

**Comment by TeddiO** [comment]
Since found an alternative method via a binary module.

**Comment by willox** [comment]
Replicated ConVars don't network to the player if they're set to the default value. Is the issue here that when players join another server they keep your "lua_errors_url" value?

**Comment by TeddiO** [comment]
Yep, that's the issue. I haven't tested in the dev branch yet to see if the previous fix you did actually corrects this. That said I'm currently using luaerror instead to grab errors from both the server and the client.
