### ISSUE TITLE
Allow custom main menus for gamemodes

### ISSUE THREAD

**Issue by NostalgicLorikeet** [Facepunch/garrysmod-requests#2403]
### Details

Could be implemented using custom HTML, for example. Some problems could be with security issues or making sure the custom menu doesn't break functionality. Another option could be customizing CSS for the menu.

**Comment by garryspins** [comment]
You can make your own main menus without needing to just alter HTML, you can rewrite them nearly entirely from the ground up in lua on the client. Having the ability to control when the main menu is opened/closed would be fantastic, we already can stop it from opening entirely, calling a hook to allow it to open couldnt hurt a single thing.

**Comment by robotboy655** [comment]
No.
