### ISSUE TITLE
Add ability to set soundflags in sound.Add

### ISSUE THREAD

**Issue by Nitestokeh** [Facepunch/garrysmod-requests#2404]
### Details

[Global.EmitSound ](https://wiki.facepunch.com/gmod/Global.EmitSound) has a parameter for [soundflags](https://wiki.facepunch.com/gmod/Enums/SND), yet [sound.Add](https://wiki.facepunch.com/gmod/sound.Add) doesn't. It would be convenient to have for [event sounds](https://developer.valvesoftware.com/wiki/Animation_Events) (5004 for playing a sound in animation), which otherwise cannot be controlled by Lua

**Comment by robotboy655** [comment]
It's not a thing for Sound Script definitions. I don't know which flags you even want to set, most of them would be useless in the context of a sound definition.
