### ISSUE TITLE
Increase the number of active text channels for game_text

### ISSUE THREAD

**Issue by Battlefieldkille** [Facepunch/garrysmod-requests#2405]
I'll start off by saying that not that many people use game_text let alone to the extent that I do, so I understand if this gets denied.
Me and my friend use this entity primarily for "story/adventure" maps, npcs "speaking" or events being announced are some examples.
Currently, Hammer Editor provides 4 text channels to use which means 4 texts can be displayed on the screen at once, but by turning off SmartEdit you can add 2 extra unused channels, that means 6 game_texts can be on the screen at once.

So, lets say you already have 6 text channels active at the same time, if you want to have a 7th channel, its activation will replace the 1st channel, the 8th channel would replace the 2nd and so on...
I had 6 text channels used as "map announcements" for a special event happening or for an important info for the players, this became a problem once I wanted to add a 7th channel and I needed those texts to be displayed on the screen all at once.

[gametext.zip](https://github.com/user-attachments/files/15774061/gametext.zip)
^ A map where you can use buttons to activate up to 18 game_texts with each one having a special channel number.

**Comment by robotboy655** [comment]
![image](https://github.com/Facepunch/garrysmod-requests/assets/3299036/c35f0583-3c7f-4343-b30d-b2a6f3b5ef77)

255 should be enough for you. This will be available on `x86-64` beta today, in the next update whenever that releases.

Please test it and report any issues.

**Comment by Battlefieldkille** [comment]
Thank you for adding this.
Tested all 256 channels and nothing seems to be broken.
![showcase](https://github.com/Facepunch/garrysmod-requests/assets/69215350/57cdcc88-6433-4e15-8a77-6b8f8b720c1b)
[gametextnew.zip](https://github.com/user-attachments/files/15794874/gametextnew.zip)
^ Test map with all 256 channels, if anyone needs it.

**Comment by Battlefieldkille** [comment]
Hey Rubat, question, recent update limited the text Hold Time to 300sec (5min). I use those specific texts as hints as to where the player needs to go/what the player needs to do in the map. Some players recently got confused on how to progress due to the text disappearing early and it is a somewhat big map, would there be a chance of increasing that limit to 1800sec (30min)?
Upon completing whatever task the player is given, the text itself gets cleared by another text that holds the same channel.
I understand if this gets denied, thanks.

**Comment by robotboy655** [comment]
Bumped the limit to 3600.
