### ISSUE TITLE
Add a few file types to the file whitelist

### ISSUE THREAD

**Issue by marchc1** [Facepunch/garrysmod-requests#2411]
### Details
The following file types would be rather useful for me and I'm sure others:

### **.mid**
Writing MIDI music files.
### **.obj**
Writing basic 3D models. A real world example is https://github.com/shadowscion/Prop2Mesh, this addon has the ability to export props as a .obj, but has to save the filename as a .txt.

### **.gltf, .glb**
Writing more advanced 3D models/scenes

### **.bin**
The GLTF specification for .gltf uses .bin files for the geometry/animation/buffer data. It's only recommended, according to [2.6 "File Extensions and Media Types"](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#file-extensions-and-media-types), and I'm not sure if there may be a more valid reason to keep .bin blocked. If that's the case, .dat would work fine for my use cases and the format doesnt require you to use a specific file extension.

**Comment by robotboy655** [comment]
My "philosophy" in adding extensions to the whitelist is basically extremely common formats (json, etc) + whatever the game itself can actually use. (sounds, models)

These all look very niche, and the game cannot use them out of the box. I do not see a good reason to add them.
