### ISSUE TITLE
Add DELETE and PUT methods to the HTTP library

### ISSUE THREAD

**Issue by MuteTM** [Facepunch/garrysmod-requests#242]
Not every webserver accepts method overrides, so adding support for the delete and put methods would save guesswork with headers, along with expanding what the HTTP library can do (especially when interacting with certain APIs).

**Comment by Bo98** [comment]
Aren't these supported now after the last update?

**Comment by neico** [comment]
Supported but not implemented by the http library, see: http://wiki.garrysmod.com/page/Category:http

**Comment by Bo98** [comment]
http library has always been a stripped down version of the HTTP function.

**Comment by neico** [comment]
Well but other then that the library isn't really useful, so it's up to discussion if the library shouldn't be deprecated in favor of the HTTP function all together (if we had a deprecation system that is...)
