### ISSUE TITLE
Add SetMassCenterOverride

### ISSUE THREAD

**Issue by zohart75** [Facepunch/garrysmod-requests#2427]
### Details
Add new useful function to PhysObj - SetMassCenterOverride. (used by Source vehicles)

**Comment by robotboy655** [comment]
I am afraid this is not a thing you can just do on a physics object. Vehicles are able to do this only on spawn, not an any point during runtime. It should be possible to do on physobj creation though.

**Comment by zohart75** [comment]
> I am afraid this is not a thing you can just do on a physics object. Vehicles are able to do this only on spawn, not an any point during runtime. It should be possible to do on physobj creation though.

Then why not? It would be still useful. SetMassConterOverride could be used to fix model problems instead of recompiling them.

**Comment by robotboy655** [comment]
Added an optional parameter to the following functions
* PhysicsInit
* PhysicsInitMultiConvex
* PhysicsInitConvex
* PhysicsFromMesh
* PhysicsInitBox
