### ISSUE TITLE
Provide m_OwnerSteamID from ValidateAuthTicketResponse_t to GM:NetworkIDValidated

### ISSUE THREAD

**Issue by klen-list** [Facepunch/garrysmod-requests#2434]
At the moment you can only get the SteamID that owns the game via `Player:OwnerSteamID64`.
Now this is the only way since Valve stopped supporting `IsPlayingSharedGame` in WebAPI and hides this method from documentation (now it always returns empty string).
In the current implementation `m_OwnerSteamID` is apparently stored in the `CBaseClient` class when `CSteam3Server::OnValidateAuthTicketResponse` is called, and then it is obtained via `GMOD_GetPlayerOwnerSteamID`.
But for all this it is necessary that player is almost completely loaded on the server, that is, appeared as an entity.
It would be more convenient to get OwnerSteamID at the beginning of loading, because the order of calls allows to do this: `CSteam3Server::OnValidateAuthTicketRespons` -> `CServerGameClients::NetworkIDValidated` -> `CLuaGamemode::CallWithArgs(58)` aka `GM:NetworkIDValidated`

**Comment by robotboy655** [comment]
Done.
