### ISSUE TITLE
VBSP Reports how far past the map limit you are

### ISSUE THREAD

**Issue by Mingooberus** [Facepunch/garrysmod-requests#2437]
### Details
Typically when compiling large maps/detailed maps users are left in the dark upon a "Too many unique X, max = 65536"-like message on how much they need to reduce it, I understand completely that the max map limits have been reached and cannot go further however I wanted to know if it was possible to add a response from the compiler that states how many brushes, faces etc you are at regardless of it's ability to compile.

**Comment by robotboy655** [comment]
This is not always possible to do, but provide actual messages you have a complaint about and it can be looked into.

**Comment by Mingooberus** [comment]
Too many unique verts, max = 65536 (map has too much brush geometry) | if possible

**Comment by robotboy655** [comment]
That would be one of those that can't really give you the value above limit, because the error happens while the vertices are being generated, so there's no number to give since it stops making vertices when it reaches the limit.
