### ISSUE TITLE
Add render.SetAntialias(true, scale) to use with render/surface operations.

### ISSUE THREAD

**Issue by Jaffies** [Facepunch/garrysmod-requests#2439]
Some elements should be aliased, some not. The example is simple:
you want aliased surface.DrawPoly or any particular mesh, but not whole 3d scene. What you do? Nothing.

**Comment by robotboy655** [comment]
Basically duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1132

**Comment by Jaffies** [comment]
That's not that. What i mean is to set mat_antialias to different values for use in specific draw operations. Not on whole scene
