### ISSUE TITLE
Implement $lightmap VMT Parameter for VertexLitGeneric

### ISSUE THREAD

**Issue by MykhailKozak** [Facepunch/garrysmod-requests#2441]
### Details
Add [$lightmap](https://developer.valvesoftware.com/wiki/$lightmap) parameter to allow custom lightmap texture definitions. By my observation this isn't included in game contrary to what the VDC says. This can allow modders to use their own lighting pipelines for props instead of VRADs for improved accuracy and baking with normal maps, and to use lightmaps on dynamic props, useful for things like interiors of vehicles or even buildings, as well as another alternative to glowing textures that isn't additively impaired by other static light sources.

Setup example for $lightmap
[static_lightmap_test.zip](https://github.com/user-attachments/files/16386163/static_lightmap_test.zip)

Showcased below is a crude workaround with Cycles baked lightmaps using $detail multiplicatively, result is darker than should be since vertex lighting is applied on top as well, and as noted in the second image dynamic lights will not correctly light dark spots as the actual albedo is darkened. But improvements to lighting can be noted as high frequency detail is more apparent and better calculated, and light bleed is a non-issue.
![20240725202215_1](https://github.com/user-attachments/assets/32636721-1073-49a7-b2b1-5adea41d1d26)
![20240725202218_1](https://github.com/user-attachments/assets/b4bc8ab2-e6e2-4db8-9f03-f14ee17a1f84)

_Originally posted by @MykhailKozak in https://github.com/Facepunch/garrysmod-requests/issues/517#issuecomment-2251892663_

**Comment by robotboy655** [comment]
It is already part of the game, and can be seen in use on TF2's `rd_asteroid` map

It is (re)set at runtime, you cannot manually set it.

**Comment by robotboy655** [comment]
![image](https://github.com/user-attachments/assets/584cb030-6342-4f77-834b-36e7d3447320)

Made it not overwrite textures set in the material.
