### ISSUE TITLE
Allow loading screens to set loading box colour

### ISSUE THREAD

**Issue by DarthTealc** [Facepunch/garrysmod-requests#2451]
### What
Allow loading screens to set the loading box colour

### How - for developers
Developers would set a [theme-color meta tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color) on their loading screen eg `<meta name="theme-color" content="#FF00FF" />`
Developers may choose to use a different colour or image for the loading screen background, it does not have to align with the theme-color. 
Developers may additionally use HTML elements behind the expected loading box location to make it look even more integrated, such as a border or drop shadow.

### How - for the game
Gmod would look at the page and extract the theme-color. If a valid #RRGGBB colour, Gmod would set the loading box to that colour, and would set the buttons/borders/text to 2 contrasting colours. These contrasting colours are handled by the game to ensure they are readable and that loading pages can't use them to make the box invisible.
If no theme-color or an invalid theme-color is specified, Gmod sticks with the default loading box colours.

### Example
(theme-color is indicated for demonstration)
![image](https://github.com/user-attachments/assets/1e892790-e263-479b-bedf-588aab52107e)

### Alternative Method
Instead of using a single theme-color metatag with Gmod automatically calculating the 2nd and 3rd colours, developers could instead use gmod-color-a, gmod-color-b, gmod-color-c meta tags. This would allow developers to have more control over the colours.
_Example of where the gmod-colors apply_
```html
<meta name="gmod-color-a" content="#FF0000" />
<meta name="gmod-color-b" content="#0000FF" />
<meta name="gmod-color-c" content="#00FF00" />
```
![image](https://github.com/user-attachments/assets/cbfb9a33-6fd9-44b1-810a-f1b136adb155)
Gmod would check to make sure they pass a basic contrast calculation to ensure the status/progress and cancel buttons aren't hidden. If the check fails, Gmod would use the default loading box colours instead.

### Accessibility 
The basic contrast check would not be accessible for high-contrast users. If a user has high-contrast set in their OS, Gmod would ignore the custom colours and apply hardcoded ones.

**Comment by EvanPole** [comment]
@robotboy655

**Comment by YohSambre** [comment]
@robotboy655 PLEEAAAAAASEEEEEE
