### ISSUE TITLE
Proper Menus, HUD & UI Scaling (or at Least Proper Borderless Support) for UHD Resolutions

### ISSUE THREAD

**Issue by GSUser43** [Facepunch/garrysmod-requests#2453]
### Details

Everyone with a UHD resolution monitor and played Gmod before already knows that playing Gmod at these resolutions is a nightmare.

Gmod and Source games in general have terrible borderless windowed mode support for now, the window doesn't stretch over to the rest of your monitor's screen when you select borderless mode, instead, it just sits at the center of your screen with no way to move the window. This is an even worse support than the normal windowed mode.

I don't mind using 1080p or even 720p resolutions if Gmod had proper borderless windowed mode support to play it, pose something for a screenshot then switch to a UHD resolution merely to take that screenshot then switch back to 720p/1080p for another screenshot. But as I said, borderless support is terrible for now.

I don't know if it's just me, but Gmod feels like "borderless" when selecting the "full screen" option, but only if it's set to your monitor's native resolution (in my case, the monitor's native resolution is 4K so the menus, HUD & UI become very small), but if you select like full screen with 1080p resolution, the screen will blackout for a few seconds as in when entering exclusive full screen mode just like what the majority of games do. Borderless mode would be extremely handy for a game like Gmod where you constantly Alt+Tab and switch between playing the game, watching videos such as tutorials or subscribing to addons for it.

Any chance for a proper and official menus, HUD & UI scaling update by Facepunch? FYI, even some mods derived from Half-Life 1 such as Natural Selection 1 now have proper menus UI that scale at any resolution thanks to Half-Life 1's 25th Anniversary Update that added proper scaling for the menus, so I'm hoping for at least a major update for Half-Life 2 in the future that adds proper menus, HUD & UI scaling so that other Source games that are still being updated (Gmod being the most important out of them all) could possibly adapt from it. The extremely small menus, HUD & UI are the very reasons why the overwhelming majority of Gmod videos on YouTube are not anything higher than 1080p resolution.

Here are some suggestions:

1. Give us either of the following options; "big" size like what it is at 720p, "normal" size (the default setting for everyone when they launch Gmod) like what it is at 1080p, and "small" size like what it is at 1440p (don't even consider the size at 4K, it's just unbearable for a game like Gmod where you constantly navigate through the menus to spawn things, change the tool gun and stuff). OR, a custom slider that adjusts the menus, HUD & UI sizes. Either a custom slider or the 3 options (big, normal and small) that scale correctly regardless of the current selected screen resolution.

2. Separate size options for each of the menus, HUD and UI.

And here are some screenshots for comparison (took me quite a while switching between resolutions and taking screenshots at almost the same point and renaming the files in their respective orders):

"big" sizes (720p):

![1  Maps 1280x720](https://github.com/user-attachments/assets/956a6338-719f-45e9-a035-a7afb61af85c)
![2  Loading Screen 1280x720](https://github.com/user-attachments/assets/3cee70ea-3721-4ad4-b78b-22d3e8c50ae6)
![3  Menus 1280x720](https://github.com/user-attachments/assets/f715bfaf-0cb2-42c9-a911-f4351e132eee)
![4  HUD 1280x720](https://github.com/user-attachments/assets/0b2c79a1-0f57-446c-9153-a97f5045241a)
![5  Context Menu 1280x720](https://github.com/user-attachments/assets/a431450b-588e-4dbf-a87d-d85ba98bc6e9)
![6  Playermodel Selector 1280x720](https://github.com/user-attachments/assets/9b0a8886-9261-4b82-8482-748911a81686)
![7  Spawn Menu 1280x720](https://github.com/user-attachments/assets/66eb4437-06c9-4db6-84dd-30409c4aaa5d)
![8  Addons 1280x720](https://github.com/user-attachments/assets/afa1c188-0eb2-4509-a2aa-f31ad26e557c)
![9  Addons Last Page 1280x720](https://github.com/user-attachments/assets/0b01559d-d3ee-417d-8cea-0390db80dc25)

"normal" sizes (1080p):

![1  Maps 1920x1080](https://github.com/user-attachments/assets/ccb67501-b8ad-4288-a837-7047c043c262)
![2  Loading Screen 1920x1080](https://github.com/user-attachments/assets/5f1dc176-42f5-454f-bfde-cf6a9ff3bef9)
![3  Menus 1920x1080](https://github.com/user-attachments/assets/83ed13ed-8855-4d06-9574-de2a132c0a0c)
![4  HUD 1920x1080](https://github.com/user-attachments/assets/db93260b-7cb8-4c6a-a560-b1a68373cc51)
![5  Context Menu 1920x1080](https://github.com/user-attachments/assets/65f385b9-5ec5-4932-8f02-a8ed8da38e12)
![6  Playermodel Selector 1920x1080](https://github.com/user-attachments/assets/b7f4fa7a-8180-486c-9476-0df1604a0cc2)
![7  Spawn Menu 1920x1080](https://github.com/user-attachments/assets/d2179272-d471-44db-9989-deae1958caae)
![8  Addons 1920x1080](https://github.com/user-attachments/assets/51805eca-ae6f-449f-883c-532d332e02dc)
![9  Addons Last Page  1920x1080](https://github.com/user-attachments/assets/0da49585-3027-449d-b4b1-0a00f2e65477)

"small" sizes (1440p):

![1  Maps 2560x1440](https://github.com/user-attachments/assets/358dda4f-f8e8-4669-a3eb-8e94d01ab816)
![2  Loading Screen 2560x1440](https://github.com/user-attachments/assets/78199560-0ccc-4b64-9e14-0af7a3e13fcc)
![3  Menus 2560x1440](https://github.com/user-attachments/assets/9a47b79c-d271-4e46-9633-0a34dfe92e67)
![4  HUD 2560x1440](https://github.com/user-attachments/assets/fad11e94-3d7a-43e0-a035-ecc814726f44)
![5  Context Menu 2560x1440](https://github.com/user-attachments/assets/017e239d-fe5a-4ca3-811a-5928356475dd)
![6  Playermodel Selector 2560x1440](https://github.com/user-attachments/assets/7423229e-5539-4191-80e9-69aa44e1652c)
![7  Spawn Menu 2560x1440](https://github.com/user-attachments/assets/f0b4a3b6-ec27-4682-95e7-f3e3b53a8fdd)
![8  Addons 2560x1440](https://github.com/user-attachments/assets/02603056-3f8d-4461-80a7-168ec811c86c)
![9  Addons Last Page 2560x1440](https://github.com/user-attachments/assets/f982051a-6b35-4c08-9a91-60dea523ae89)

The extremely small sizes at 4K and why such option shouldn't exist:

![1  Maps 3840x2160](https://github.com/user-attachments/assets/84016c1c-0258-4b08-a489-a30a66d8f5ff)
![2  Loading Screen 3840x2160](https://github.com/user-attachments/assets/bce0c41c-09e2-4d3a-a3cc-646781d1d8f7)
![3  Menus 3840x2160](https://github.com/user-attachments/assets/75a2a846-7e7e-4f77-93ee-e964ad823c06)
![4  HUD 3840X2160](https://github.com/user-attachments/assets/c4ff64b0-6e66-438d-a70a-f3b69989cdaf)
![5  Context Menu 3840x2160](https://github.com/user-attachments/assets/f3caf0f6-1dce-45cb-ad24-716b52651ea3)
![6  Playermodel Selector 3840x2160](https://github.com/user-attachments/assets/1d7c0d7d-2e82-43ad-b9dc-bc70fe622d5b)
![7  Spawn Menu 3840x2160](https://github.com/user-attachments/assets/f99c6bdf-34d0-482b-af2c-edd4ebf3d69a)
![8  Addons 3840x2160](https://github.com/user-attachments/assets/dd97bd09-a002-4d22-b986-645c7cbd3678)
![9  Addons Last Page 3840x2160](https://github.com/user-attachments/assets/ab8bf200-ee6d-4550-9434-313fa710e2c5)

FYI, I'm using the "BF Hud" addon not only because I like it, and also not only because it unfortunately doesn't scale well (it even unfortunately has worse scaling than the default HL2 HUD, the latter only has the text in it not scaling, while the other has the entire HUD not scaling), but also because I wanted to demonstrate how the HUD shrinks at UHD resolutions.

In case you're interested in it, you can find it in the Steam Workshop here (keep in mind that you have to enter the **gzg_vignette 0** command each time you load a map to disable the vignette):

https://steamcommunity.com/sharedfiles/filedetails/?id=125867420

(I can also tell you the playermodels that I have in case you're interested in them).

Also, just in case you haven't noticed and maybe it's worth pointing out; the last screenshot in each of the respective size/resolution section that is the last page of my subscribed addons, only 720p has the last page of the addon being up to 65, every other size/resolution has the last page being up to 27 due to the former's big interface size (the arrows and dots to change the page get smaller the higher the resolution gets though).
```[tasklist]
### Tasks
```

**Comment by robotboy655** [comment]
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5123
Related: https://github.com/Facepunch/garrysmod-requests/issues/1048

**Comment by Darvan76** [comment]
The goal is not just to make fonts bigger, but to make the entire UI use a 1080p logical coordinate system while the game still renders at native 4K.

Example:
- Game resolution: 3840x2160
- UI logical resolution: 1920x1080
- UI scale: 2.0

This would make the spawnmenu, context menu, HUD, Derma panels, fonts, buttons, margins and layout keep the same perceived size as 1080p, while preserving native 4K rendering for the 3D scene.

A proper solution would need to scale:
- Fonts
- Panel sizes
- Positions
- Margins and padding
- HUD drawing helpers
- Default Derma controls
- Spawnmenu/context menu
- Main menu and console if possible

Community addons can partially scale Derma/UI elements, but they cannot reliably fix the main menu, console or every hardcoded VGUI/HUD element. An official gmod_ui_scale ConVar would be much cleaner.

Suggested ConVar:
gmod_ui_scale 0 / 1 / 1.25 / 1.5 / 2

Where:
0 = automatic based on 1920x1080 baseline
1 = original behavior

**Comment by benrrava** [comment]
i agree, its just so bad to go on a server, and see the ui is too big because im playing on low res and my computer cant handle a big resolution
