### ISSUE TITLE
Dump_scripted_entity_sizes

### ISSUE THREAD

**Issue by RepositoryLover** [Facepunch/garrysmod-requests#2456]
### Details

Like dump_entity_sizes, but lists the scripted entities (default and addon) and how big they are in bytes.

**Comment by robotboy655** [comment]
Their sizes are right here:
![image](https://github.com/user-attachments/assets/ac3175cf-e6b5-4956-9766-83e08d6e9f66)

I don't know of a way to accurately measure entity's memory consumption in Lua, given its dynamic nature the value will never be correct or constant.
