### ISSUE TITLE
Add Workshop Localization

### ISSUE THREAD

**Issue by NovaDiablox** [Facepunch/garrysmod-requests#2458]
### Details
Add workshop page localization to crowdin.

**Comment by robotboy655** [comment]
I am not quite sure what you mean. The entire main menu is translated, including the Addons menu. The workshop website is not part of Garry's Mod, it cannot be translated.

**Comment by NovaDiablox** [comment]
> I am not quite sure what you mean. The entire main menu is translated, including the Addons menu. The workshop website is not part of Garry's Mod, it cannot be translated.

Thanks for quick reply. Yes I meant the steam workshop page. In some times I have seen it translated to various languages. I thought It was possible in Garry's Mod.

**Comment by robotboy655** [comment]
It is translated to different languages by Steam:
![image](https://github.com/user-attachments/assets/d7b4d2ec-2b19-415b-b993-670da2b6e58c)

You need to change your language in Steam to see the translated website.

**Comment by robotboy655** [comment]
Addons themselves would need to be individually translated by their authors.

**Comment by NovaDiablox** [comment]
For example "ADDON TYPE" and their respective categories are not translated but other elements such as Gmod workshop description is translated to my language. As we can see the "Addons" next to the Russian string is not translated. CONTENT TYPE, Gamemode as well.

**Comment by NovaDiablox** [comment]
> Addons themselves would need to be individually translated by their authors.

Yes sir.

**Comment by robotboy655** [comment]
There appears to be a way to localize the tags, but not the "Addons" part from the picture.

And by the looks of it, the tags localization doesn't even work, I tried applying it to Russian and it doesn't appear to be working.

Sadly the way the localization is done on Steam means that it cannot be easily added to our localization website.

**Comment by robotboy655** [comment]
Nevermind, it took a while, but they do work.

If you want to contribute localization for one of Steam's supported languages for workshop tags, you can send me a `.json` file formatted like so:
```
{
    "language": "english",
    "appid": 4000,
    "category_0": "Content Type",
    "category_1": "Addon Type",
    "category_2": "Addon Tags",
    "category_3": "Dupe Tags",
    "category_4": "Save Tags",
    "tag_12087": "Addon",
    "tag_12088": "Dupe",
    "tag_12089": "Save",
    "tag_12090": "Demo",
    "tag_12091": "Map",
    "tag_12143": "Gamemode",
    "tag_12144": "Weapon",
    "tag_12145": "Vehicle",
    "tag_12146": "NPC",
    "tag_12147": "Tool",
    "tag_12148": "Effects",
    "tag_12149": "Model",
    "tag_12150": "Fun",
    "tag_12151": "Roleplay",
    "tag_12152": "Scenic",
    "tag_12153": "Movie",
    "tag_12154": "Realism",
    "tag_12155": "Cartoon",
    "tag_12156": "Water",
    "tag_12157": "Comic",
    "tag_12158": "Build",
    "tag_12570": "Posed",
    "tag_12571": "Scenes",
    "tag_12572": "Machines",
    "tag_12573": "Vehicles",
    "tag_12574": "Buildings",
    "tag_12575": "Others",
    "tag_12576": "Courses",
    "tag_15526": "ServerContent",
    "tag_116672": "Entity"
}
```
Where you'd replace the strings on the right with localized ones for whatever language.

**Comment by NovaDiablox** [comment]
> Nevermind, it took a while for Steam to refresh, but they do work.
> 
> If you want to contribute localization for one of Steam's supported languages for workshop tags, you can send me a `.json` file formatted like so:
> ```
> {
>     "language": "english",
>     "appid": 4000,
>     "category_0": "Content Type",
>     "category_1": "Addon Type",
>     "category_2": "Addon Tags",
>     "category_3": "Dupe Tags",
>     "category_4": "Save Tags",
>     "tag_12087": "Addon",
>     "tag_12088": "Dupe",
>     "tag_12089": "Save",
>     "tag_12090": "Demo",
>     "tag_12091": "Map",
>     "tag_12143": "Gamemode",
>     "tag_12144": "Weapon",
>     "tag_12145": "Vehicle",
>     "tag_12146": "NPC",
>     "tag_12147": "Tool",
>     "tag_12148": "Effects",
>     "tag_12149": "Model",
>     "tag_12150": "Fun",
>     "tag_12151": "Roleplay",
>     "tag_12152": "Scenic",
>     "tag_12153": "Movie",
>     "tag_12154": "Realism",
>     "tag_12155": "Cartoon",
>     "tag_12156": "Water",
>     "tag_12157": "Comic",
>     "tag_12158": "Build",
>     "tag_12570": "Posed",
>     "tag_12571": "Scenes",
>     "tag_12572": "Machines",
>     "tag_12573": "Vehicles",
>     "tag_12574": "Buildings",
>     "tag_12575": "Others",
>     "tag_12576": "Courses",
>     "tag_15526": "ServerContent",
>     "tag_116672": "Entity"
> }
> ```
> Where you'd replace the strings on the right with localized ones for whatever language.
> 

https://github.com/NovaDiablox/gmodworkshoppagelocalization/blob/main/tr.json
