### ISSUE TITLE
Add NPC:SetIdealSequence

### ISSUE THREAD

**Issue by URAKOLOUY5** [Facepunch/garrysmod-requests#2462]
### Details
There's a SetIdealActivity, but there is no SetIdealSequence.
It's possible with ACT_SPECIFIC_SEQUENCE and m_nIdealSequence in SDK.

Correct me if I don't know something, because there is GetIdealSequence.

**Comment by robotboy655** [comment]
Added, even though I am not sure how useful this is, or whether this is a "just because there's no setter" type request and you don't actually need it.

**Comment by URAKOLOUY5** [comment]
Because many models have their own ACT_ that are not added to the game and I don't see a way to do that without sequences

**Comment by robotboy655** [comment]
You are looking for https://wiki.facepunch.com/gmod/util.GetActivityIDByName if you want to use model-speific activities.

**Comment by URAKOLOUY5** [comment]
Haven't seen it, good to know
