### ISSUE TITLE
HDR static prop lightmaps (RGBA16161616f PPL/`-dumppropmaps` PFM files)

### ISSUE THREAD

**Issue by piqey** [Facepunch/garrysmod-requests#2464]
### Details
Source SDK 2013 Multiplayer (and Garry's Mod) support static prop lightmaps in the form of RGB888 (24-bit SDR) PPL files. According to the VDC Wiki's page on `VertexLitGeneric`'s [`$lightmap`](https://developer.valvesoftware.com/wiki/$lightmap) VMT parameter:

![image](https://github.com/user-attachments/assets/4b4dd2c5-df79-4c0b-9218-053c8ca8bf16)

VRAD ought to be modified to compile static prop lightmaps to RGBA16161616f to support HDR lighting for maps that use it as most already do.

If Garry's Mod supports conditional statements in VMT files like I believe it does, VRAD could generate both LDR _and_ HDR lightmaps for static props, swapping between them depending on which lighting mode is loaded at runtime. An example VMT could look something like this (untested):

```
"VertexLitGeneric"
{
    $basetexture            "mybasetexture"

    "!HDR?$lightmap"   "lightmap/path"
    "HDR?$lightmap"    "lightmap/path_hdr"
}
```

Will reference issues #2109, #517 and #2441 for posterity.

**Comment by piqey** [comment]
Come to think of it, I actually have no idea if PPL files use custom-generated and BSP-packed VMT files to mount like `env_cubemap`s do on brush faces, so the syntax above may be completely useless for any situation other than manually including lightmaps via those dumped via `vrad.exe` executed with `-dumppropmaps`.

**Comment by robotboy655** [comment]
I have made `-dumppropmaps` also dump `.pfm` files in addition to `.tga`, which should allow you to experiment here further.

I have tried to also just force the PPLs to 16161616F format, but it didn't workout well:
![Image](https://github.com/user-attachments/assets/cbe29956-2455-4c7b-8ee3-dfd609ae875a)

There must be something else going on and needing changes for this to maybe work. I also have no comparisons where the current functionality is producing unwanted or bad results as VDC describes them, so I am not sure what I can really achieve here.

**Comment by piqey** [comment]
> I have made `-dumppropmaps` also dump `.pfm` files in addition to `.tga`, which should allow you to experiment here further.
> 
> I have tried to also just force the PPLs to 16161616F format, but it didn't workout well: ![Image](https://github.com/user-attachments/assets/cbe29956-2455-4c7b-8ee3-dfd609ae875a)
> 
> There must be something else going on and needing changes for this to maybe work. I also have no comparisons where the current functionality is producing unwanted or bad results as VDC describes them, so I am not sure what I can really achieve here.

I have no clue how PPL format works and I will eagerly admit I no longer really care because you gave me exactly what I wanted. You just released the tools we need to make static prop lightmaps not look like crap anymore and I'm not sure you even realized that when you pushed these changes to the dev branch.

It appears the TGA files deposited in the `sp_lightmaps/` folder are broken now (they seem to be somehow PFM or 32-bit color but in TGA format or something, they look the way `RGBA16161616f` VTF files look when you try to open them in VTFEdit, that's all I have to offer a solution). However, the new PFM files are exquisite. While it's somewhat disappointing your efforts to pack them as PPL files were unsuccessful, my efforts to compile them into VTF files with VTEX were not as fruitless.

While I did need to make my own model/material/`$lightmap` combo, here's some LDR vs. HDR comparisons (`mat_hdr_level 0` vs. `mat_hdr_level 2`), swapping between one of the PFM files generated by your new `vrad.exe` and an `RGB888` lightmap I made by tonemapping the PFM file to 8-bit in Photoshop:

![Image](https://github.com/user-attachments/assets/c741f0f4-57d9-400f-a0cf-181f8b70e145)
![Image](https://github.com/user-attachments/assets/47839264-8b67-47f7-b67b-f5eaa3f7de9e)
![Image](https://github.com/user-attachments/assets/72c9b8cf-f683-47a9-a0a2-9b9e6b7ddf40)
![Image](https://github.com/user-attachments/assets/c72e385f-c3b4-49e9-92ec-4ed36994b497)
![Image](https://github.com/user-attachments/assets/893abefe-6d54-41ce-a3da-d84dce850e0c)

Here's the stills themselves without the lossy GIF dithering:

![Image](https://github.com/user-attachments/assets/8e2c6205-2535-4703-ba85-298a8c3cd48c)
![Image](https://github.com/user-attachments/assets/97b329a0-85b9-42a1-bf2c-cbeb974bfc4d)
![Image](https://github.com/user-attachments/assets/a17bb33e-fa38-4abf-84c9-949ea63c63af)
![Image](https://github.com/user-attachments/assets/42ab27e9-f61b-4924-ac45-14c578d8db3f)
![Image](https://github.com/user-attachments/assets/3e6df3ad-58c6-43a1-a066-4a5a8463ed4b)

![Image](https://github.com/user-attachments/assets/72b00bf8-8f5d-4d26-9ace-9920ea61fef0)
![Image](https://github.com/user-attachments/assets/bc878e37-564e-460f-8b45-d52de6d2219c)
![Image](https://github.com/user-attachments/assets/039ea65a-277d-444f-b624-387436168018)
![Image](https://github.com/user-attachments/assets/72d7fd80-eb00-4810-a1eb-f7ba3cf3875a)
![Image](https://github.com/user-attachments/assets/b427e814-a68d-4cb5-b184-45ec82548089)

![Image](https://github.com/user-attachments/assets/22b1f408-597d-4f4f-ad8d-1936b0dd825d)

I'm still trying to figure out how to adjust the `pfmscale` for these. It's a bit clearer for 2D skyboxes where the `pfmscale` is just the brightness, but in this case it seems to both simultaneously increase the relative brightness and decrease the lightmap's response to tonemapping, which means adjusting it in one direction appears to improve the lighting in some spots and worsens it in others.

## A few things to note

1. A small issue with actually using static prop lightmaps this way at runtime. I noted in my initial suggestion that conditional VMT statements could maybe be used to swap in the HDR lightmap when HDR is enabled by clients, though after some testing this does not appear to be the case. I would, however, like to offer an alternate solution:
    - Add support for an `<original texture name>.hdr.vtf` texture placed alongside the LDR lightmap, similar to cubemaps.
        - Example implementation: ![Image](https://github.com/user-attachments/assets/07781054-4ed0-4d4b-bef4-ec160fc9bc01)
2. Look at how much better the shadow casting looks on the HDR lightmap. I hadn't expected soft shadows to be one of the improvements we'd get from something like this but I suppose I should have. Ridiculously sharp edges were one of the things I disliked the most about static prop lightmaps; I'm extremely happy with the results of this experiment.
3. Though I did say before that I'd eagerly give up the ability to have these automatically packed into maps as the traditional PPL files we're used to, there are some situations I'm certainly not looking forward to manually authoring materials for. Namely, ones like these (pictured below), where there are probably 30+ static props pictured that have fairly contrasting highlights casting on them, being the impetus for me making this request in the first place.
    - ![Image](https://github.com/user-attachments/assets/98dbca97-8daf-4025-b7fa-e7e962d7cff5)

Anyways, this is huge; you've already given me and anyone else who does mapping at this level a massive service today. Thank you very much.

**Comment by piqey** [comment]
The APC example I've given probably isn't the best for demonstrating this as the scene doesn't have much ambient lighting and there's only a few light sources and they're pushed right up against the APC, which also messes with the player's exposure/tonemapping. So I don't have a very good baseline to provide you.

But the important factor to acknowledge is the PFM files `vrad.exe` is putting out are absolutely tenable

**Comment by robotboy655** [comment]
> It appears the TGA files deposited in the sp_lightmaps/ folder are broken now (they seem to be somehow PFM or 32-bit color but in TGA format or something, they look the way RGBA16161616f VTF files look when you try to open them in VTFEdit, that's all I have to offer a solution). 

I have not touched the way it dumps .tga files at all. It should work identically between `dev` and `NONE` beta, except for the location where they are saved.

What it does internally (and always did) is that it converts the float values to a TGA image, for debugging purposes, by multiplying them by 255. This process was not changed.

**Comment by piqey** [comment]
> > It appears the TGA files deposited in the sp_lightmaps/ folder are broken now (they seem to be somehow PFM or 32-bit color but in TGA format or something, they look the way RGBA16161616f VTF files look when you try to open them in VTFEdit, that's all I have to offer a solution).
> 
> I have not touched the way it dumps .tga files at all. It should work identically between `dev` and `NONE` beta, except for the location where they are saved.
> 
> What it does internally (and always did) is that it converts the float values to a TGA image, for debugging purposes, by multiplying them by 255. This process was not changed.

Yeah, I see that now. Apologies.

Comparing them with the Source SDK 2013 `vrad.exe`'s `-dumppropmaps` they're the same; in a previous map I released I had forgotten I'd used [ficool2's `proptexelvtf` tool](https://developer.valvesoftware.com/wiki/$lightmap#:~:text=Ficool2%27s%20proptexelvtf.exe%20(direct%20download)) instead of `-dumppropmaps`, likely for this reason (I have a short memory).

Here's the TGA file (then to PNG to post here) vs. the PPL file converted to VTF with that tool and (then to PNG to post here):

![-dumppropmaps TGA file](https://github.com/user-attachments/assets/826d6448-f2f0-46aa-8d18-cb5ebcdaaf37)
![Extracted PPL file -> proptexelvtf](https://github.com/user-attachments/assets/9898a1b7-e08b-41e5-90a2-90496a84a816)

> What it does internally (and always did) is that it converts the float values to a TGA image, for debugging purposes, by multiplying them by 255. This process was not changed.

Perhaps I'm talking nonsense, but just looking at the differences between these two images suggests to me that the exported TGA files are "attempting" express the full color depth we're now getting in the PFM files (and have always been, as you describe here), whereas I was under the assumption that we were supposed to be getting the same output as in the PPL files. The banding is particularly visible near the light sources, and the brightness of the light source I placed above the APC is `2000`.

Would it be possible to get TGA files (in addition to the debug TGA files that may exceed the usable color range as seen above) with the proper color transformations applied as seen in the PPL files for ease of access/importing (as opposed to extracting the PPL files with BSPInfo or another tool, then relying on a third-party tool like `proptexelvtf` which is a dead link half the time)?

**Comment by piqey** [comment]
Also, this is only tangentially related but I'm only now realizing that I don't think there's a way to compile HDR textures to VTF _without_ generating mips for them. If you use VTEX and set `nolod 1` and `nomips 1` [it still generates mips anyways](https://developer.valvesoftware.com/wiki/VTEX_(Source)#:~:text=The%20MIPs%20are%20still%20generated%20and%20loaded) (the VTFEdit solution offered here is of no use, as VTFEdit doesn't support HDR texture importing, only _opening_ HDR VTFs).

**Comment by robotboy655** [comment]
Alright, I have adjusted `-dumppropmaps` to output TGA files as they would appear in the PPL files themselves. (I think)

**Comment by robotboy655** [comment]
I think I know why simply changing the image format did not work for PPL - There's no conversion from RGB888 to RGBA16161616F by default in the engine, and that would be pointless anyway. I will need to investigate more into what options there are in having HDR output for PPL some other time though, or at least to VTF.

**Comment by piqey** [comment]
Concerning the use of `$lightmap` between LDR and HDR modes, what do you think of the solution I proposed for swapping between LDR and HDR lightmap textures at runtime:

> A small issue with actually using static prop lightmaps this way at runtime. I noted in my initial suggestion that conditional VMT statements could maybe be used to swap in the HDR lightmap when HDR is enabled by clients, though after some testing this does not appear to be the case. I would, however, like to offer an alternate solution:
> * Add support for an `<original texture name>.hdr.vtf` texture placed alongside the LDR lightmap, similar to cubemaps.
>   * ![Image](https://github.com/user-attachments/assets/07781054-4ed0-4d4b-bef4-ec160fc9bc01)

I didn't include screenshots of the `RGBA16161616f` lightmap in LDR mode but it looks like this:

![RGBA16161616f lightmap in LDR mode (floor included)](https://github.com/user-attachments/assets/4553b243-3afe-43ab-85fb-1d9b0f862c32)
![RGBA16161616f lightmap in LDR mode (no floor)](https://github.com/user-attachments/assets/b4230d8f-5af1-42f0-86e1-9c2d58d1e630)

It's too bright for the scene, and in some places artifacts can be seen:

![RGBA16161616f lightmap in LDR mode, visual artifacts showcased](https://github.com/user-attachments/assets/cb616766-bf03-4686-b479-aa9bdf37498d)

So while it does load in LDR mode and isn't outright dysfunctional I do believe some form of cross-loading support is in order (and I think the existing convention employed by cubemaps I mentioned above would be the best way to go about it).

When I tried testing it out in hopes it wasn't strictly for cubemap textures, [TeamSpen's Hammer Addons](https://github.com/TeamSpen210/HammerAddons) actually detected and packed it in my map in addition to the LDR texture in the same way it would for cubemaps. That's not necessarily important to include here, just a nice detail.

**Comment by robotboy655** [comment]
In order to think about switching at runtime, the HDR stuff needs to exist first.

**Comment by piqey** [comment]
This seems to work for now:
```
"VertexLitGeneric"
{
	$basetexture		"my_textures/basetexture"
	$lightmap		"my_textures/lightmap"

	"VertexLitGeneric_HDR_DX9"
	{
		$lightmap	"my_textures/lightmap_hdr"
	}
}
```
Switches depending on `mat_hdr_mode`

**Comment by robotboy655** [comment]
Alright I have made some more changes on `dev` beta:
* Only output `.tga` for LDR compiles, `.pfm` for HDR compiles only (the dump lightmaps command)
* Compile `_hdr.ppl` files when map is compiled with HDR (in addition to normal `.ppl`)
* Load the `_hdr.ppl` file when the map is loaded with HDR enabled. Same behavior as the `.vhv` files
* Fallback to normal `.ppl` files if there's no `_hdr.ppl` for a specific static prop when loading the game
  * This retains existing lightmaps on existing maps when in HDR, such as TF2s `rd_asteroid`

Please test these changes and let me know if these work as expected for you.

**Comment by piqey** [comment]
It works great; thank you very much.

Concerning the `$lightmap` VMT parameter, would it be possible to receive similar cross-mounting support for LDR & HDR modes to avoid the use of fallback shaders (specifically `.hdr.vtf` to conform with the existing `$envmap` naming convention)? I believe auto-packing tools already pack textures with that naming scheme; mine do.

**Comment by robotboy655** [comment]
I am not sure what you mean by that. There are no `.vmt`s involved at all.

**Comment by piqey** [comment]
> I am not sure what you mean by that. There are no `.vmt`s involved at all.

In the event we manually specify our own lightmaps with the `$lightmap` parameter via VMT materials (as made possible following #2441), it would be helpful to have a syntax for cross-mounting between LDR and HDR textures.

**Comment by robotboy655** [comment]
I don't think I want bother adding that, sorry.

Using VMT's conditional `hdr?` and `ldr?` should work.

I think this request can now be considered fulfilled.

**Comment by piqey** [comment]
> I don't think I want bother adding that, sorry.
> 
> Using VMT's conditional `hdr?` and `ldr?` should work.
> 
> I think this request can now be considered fulfilled.

Oh, I suppose they're case-sensitive then? I tried `HDR?` and it didn't work, guess I should have tried lowercase.
Thank you for all the work you've done!
