### ISSUE TITLE
base engine weapons as custom weapons in maps.

### ISSUE THREAD

**Issue by RepositoryLover** [Facepunch/garrysmod-requests#2466]
### Details

Base weapons like weapon_hl2mp_base and basehlcombatweapon should be used for making custom weapons exclusive to maps. I know you can make SWEPs, but what if you want a custom weapons exclusive to a certain map that your making. SWEPs are usable in any map you got to, and I don't think they can be exclusive to certain maps. So if you want to make a custom weapon exclusive to your map, you can make one in a similar manner in making one in Portal maps. I got my idea from this: https://developer.valvesoftware.com/wiki/Weapon_portal_base

**Comment by robotboy655** [comment]
That's going to be a no for this one. It makes no sense for us to add a new custom weapon system when we already have scriptable weapons.

You can 100% code a weapon that would only function on a specific map, even though in my personal opinion, it's a bad idea. The whole ability to use random weapons on any map is kinda the cool part about having modded weapons.
