### ISSUE TITLE
Hook ‎CAI_BaseNPC::TranslateNavGoal for SNPCs 

### ISSUE THREAD

**Issue by BREEDNKMs** [Facepunch/garrysmod-requests#2469]
This is most likely the last 'translate' hook I will request 

TranslateNavGoal(pEnemy, chasePosition) allows the final move destination to be manipulated to somewhere else without reconstructing the entire path. It is mostly used for correcting the path towards the enemy, not during direct movement. Flying NPCs use this to move towards enemy's head rather than enemy's origin. Zombies use this to move towards the vehicle's front door, if the enemy is driving a vehicle. 

This may also be useful in cases the NPC wants to navigate to its enemy but there aren't any paths in map so you can generate a virtual path nearby within 512 units. 

Example use case: 

```
-- pEnemy: targeted entity in navigation process 
-- chasePosition: target coordinate our npc will move to 
function ENT:TranslateNavGoal(pEnemy, chasePosition) 
	if IsValid(pEnemy) then 
		-- get behind the enemy 
		local vecBack = pEnemy:GetPos() + (pEnemy:GetForward()*-16) -- assuming 16 is the max vertical extent of the bbox 
		return vecBack 
	end 
end 
```

**Comment by Roachdaripper** [comment]
this is good

**Comment by robotboy655** [comment]
Added ENT:TranslateNavGoal( enemy, currentGoal ) - return vector to override. It only gets called when an enemy is being chased it seems.

**Comment by BREEDNKMs** [comment]
also twice when constructing a path to [GOALTYPE_TARGETENT](https://wiki.facepunch.com/gmod/Enums/GOALTYPE#GOALTYPE_TARGETENT); first one is for first path_target, second one is for second path_target. it gets called twice again after [NPC:AdvancePath](https://wiki.facepunch.com/gmod/NPC:AdvancePath).
