### ISSUE TITLE
Prop type options

### ISSUE THREAD

**Issue by RepositoryLover** [Facepunch/garrysmod-requests#2470]
### Details

Right-click the prop you want to spawn and select "prop types". If it's a physics prop, then you have options to spawn it as: prop_physics, prop_physics_multiplayer, and prop_physics_override.

**Comment by robotboy655** [comment]
What is this meant to accomplish?

**Comment by RepositoryLover** [comment]
> What is this meant to accomplish?

There a differences between the prop_physics and prop_physics_multiplayer such as simplified collision system applied to prop_physics_multiplayer. I don't know what prop_physics_override would make so we can leave that one out I guess.

**Comment by RepositoryLover** [comment]
> What is this meant to accomplish?

It's so if people want to make a prop with simplified collision system. Like for a multiplayer map.

**Comment by robotboy655** [comment]
`prop_physics_multiplayer` is identical to `prop_physics` in Garry's Mod.

I also do not understand where you got the "simplified" physics part, or what you want it to do for you.

According to the Valve Developer Wiki:
https://developer.valvesoftware.com/wiki/Prop_physics_multiplayer

The only differences are solidity with the player, and the ability for the prop to be clientside only (I think).

`prop_physics_override` allows overriding of the physical material/properties and health.

All of these options are really meant for mappers, not regular Sandbox players.

**Comment by RepositoryLover** [comment]
> `prop_physics_multiplayer` is identical to `prop_physics` in Garry's Mod.
> 
> I also do not understand where you got the "simplified" physics part, or what you want it to do for you.
> 
> According to the Valve Developer Wiki: https://developer.valvesoftware.com/wiki/Prop_physics_multiplayer
> 
> The only differences are solidity with the player, and the ability for the prop to be clientside only (I think).
> 
> `prop_physics_override` allows overriding of the physical material/properties and health.
> 
> All of these options are really meant for mappers, not regular Sandbox players.

Ok
