### ISSUE TITLE
Allow doors to receive explosive damage

### ISSUE THREAD

**Issue by A1steaksa** [Facepunch/garrysmod-requests#2471]
Currently, doors in Garry's Mod are hard-coded to not receive explosive damage due to what I believe is an oversight in the logic of `CGameRules::RadiusDamage`.

The function finds all entities within the explosion's radius and iterates over them, performing a line trace (`tr`) between the center of the explosion and each entity's (`pEntity`) position.  It then performs the following code (Shown here in a somewhat condensed form)
```cpp
if ( tr.fraction != 1.0 ){ // If the trace hit something
	if ( IsExplosionTraceBlocked( &tr ) ){ // If the trace hit the world or a door (Which doors always are)
		if( ShouldUseRobustRadiusDamage( pEntity ) ){ // If the target of the trace was an NPC (Which doors never are)
			// NPC-related code removed for brevity.
		} else {
			continue; // Stop processing this entity (Doors always fall down this path)
		}
	}
}
```
The core of the issue is that this code does not differentiate between the case where the trace hit a door because the door is between the center of the explosion and the entity being traced against, and the case where the trace hit a door because the door is the entity being traced against.  This means that doors are effectively blocking themselves from taking damage.

My suggested fix is to add a check to make sure that the entity hit by the trace (`tr->m_pEnt`) is not the entity that the trace was attempting to hit (`pEntity`).

For example:
```cpp
if ( IsExplosionTraceBlocked( &tr ) && tr->m_pEnt != pEntity ){
```

As far as I know, this should not have adverse knock-on effects on the rest of the game.  
GoldSrc games had damage-activated doors, but that feature was removed from Source so I don't believe this would cause any unexpected behavior there and doors don't have health so they shouldn't be capable of dying unexpectedly.

**Comment by A1steaksa** [comment]
Thanks to WardenPotato for his help tracking this down!

**Comment by robotboy655** [comment]
Done.
