### ISSUE TITLE
Albedotint for rimlighting

### ISSUE THREAD

**Issue by Vuthakral** [Facepunch/garrysmod-requests#2472]
### Details
The standard behaviour of the shaders is that rimlights just inherit from `$phongtint`, but when you are using `$phongalbedotint` rimlighting is just stuck at solid white as rimlighting is not set up for albedo tinting. Is it at all possible we could get an optional bool parameter for rimlight tinting like `$rimlightalbedotint` that we could use to tie rimlighting to the albedo like we already can for phong?

As an example with an MP7 I am currently in the middle of working on materials for; I am using an albedotint to help tint the phong to the surface imperfections, but the rimlighting is limited to the colour of solid white as a result of this. Here is with vs without rimlighting applied:

![image](https://github.com/user-attachments/assets/eaa0b96e-852f-4375-b155-a9d021ad8eee)
![image](https://github.com/user-attachments/assets/1b6ad756-27bb-4973-b461-c2c3cc95b83d)

edit: I forgot to mention, a major reason this really sucks is that the rimlighting often ends up looking like this at most non-lighting-parallel viewing angles when you have a solid white rimlight:

![image](https://github.com/user-attachments/assets/37f6c3c1-3f08-48c9-81ba-b15ed420f903)

The closest thing we can get out of this right now is using a phong exponent texture which will give us a black & white mask for the overall "strength" of the rimlighting, but still won't let us give the rimlighting a tinted colour in any manner because of the aforementioned `$phongalbedotint`.

Rimlighting provides a very nice fake soft edge lighting effect, and it would be a great visual benefit for everyone if we could use them alongside phong albedo tinting without them being locked at solid white colouring.

**Comment by Goldermor** [comment]
Maybe you are doing something wrong because rimlight actually inherits from albedo color.
![image](https://github.com/user-attachments/assets/2af6d51c-e946-4d82-8b67-7be9d635f81d)

**Comment by Vuthakral** [comment]
> Maybe you are doing something wrong because rimlight actually inherits from albedo color.

Yeah you're right, I somehow didn't even notice until just now that for some reason my green channel was not being exported. Apologies for this submission without realizing.
