### ISSUE TITLE
Set `BRANCH` on Linux DS properly

### ISSUE THREAD

**Issue by RaphaelIT7** [Facepunch/garrysmod-requests#2474]
### Details
So, if I remember correctly,  
Rubat said that it uses the steamclient to get the current branch of the game.  
Since a dedicated server doesn't have this steam client, the BRANCH will always be unknown.  

So my suggestion is to save the branch in the `garrysmod.ver` and load/set it like done with `VERSION` and `VERSIONSTR`.
This would solve it and hopefully shouldn't be too hard to do.

**Comment by Grocel** [comment]
Yeah that issue and even the reason kinda annoys me. There are obviously different code bases for each branch, so why not hardcode the branch in them? This issue exists in Windows dedicated servers too.

**Comment by RaphaelIT7** [comment]
![image](https://github.com/user-attachments/assets/7fbec2a8-0c90-46a8-9600-2cb59a6c0b09)
:eyes:

**Comment by Grocel** [comment]
Apparently Rubat changed it the latest commit.

**Comment by robotboy655** [comment]
Made it fallback to `garrysmod.ver` when Steam isn't available, such as for SRCDS.
