### ISSUE TITLE
Add folders for extra animation, expanding base

### ISSUE THREAD

**Issue by Kpyxa** [Facepunch/garrysmod-requests#2477]
I've seen a lot of requests to add support for extra player animations using Lua, but judging by the date of these requests, it may require a lot of effort to implement.
So I suggest just adding a simple feature in my opinion, at the engine level, add the ability for base animation files to load animations from all models added to a specific folder. Gmod already works fine without activity enums, using only sequence IDs or their names.

I ask because community-created animation add-ons always conflict with each other, because they all modify base animation files, so why not just add official support for loading extra animations from a specific folder? This will reduce the headache for both content creators and ordinary players who constantly see some errors related to these add-ons on their side.

While there is no way to make a fully dynamic lua support for extra animations, make this one for now, because people need it, especially on multiplayer servers.
I myself, just to avoid creating problems for players, made a custom system for my server, which would not affect the basic animation files and broke my head with matrices and strange behavior of the ManipulateBonePosition function.
Well, imagine that King David is already editing files at the bit level so that his dynamic animation manager can work.

**Comment by robotboy655** [comment]
This is effectively https://github.com/Facepunch/garrysmod-requests/issues/230 but more error prone, since you'd have no control over what models are loaded.

**Comment by Kpyxa** [comment]
> This is effectively #230 but more error prone, since you'd have no control over what models are loaded.

Isn't it possible to make a blacklist of what is not needed? Or is there some way players can use it to upload malicious code?

**Comment by Kpyxa** [comment]
> I don't see how. This feature would need to work on any model, not just player models, having 1 specific folder (or 2 or 10) for this just doesn't work, since player models would load non player model animations, and vice versa.

In my request I meant specifically playermodels, if I want to have some other model with special animations, I can do it right now, because there is a base for it. Now all mods for extra animations directly change only player animations and not anything else. Why would I just need, say, animations of a vortigaunt on a person? Or if I want to make extra animations for a vortigaunt, I will recompile it.

**Comment by Kpyxa** [comment]
I mean, for any other situation you can easily get by with a private solution, changing a specific model or some trick, but for player animations you need a completely different approach, because all models are player customization, and if I want to make a universal set of animations for all models, I have 3 not the best ways:
1. Changing the basic animation files, with the possibility of their corruption if this is done by a person who does not understand this, many add-ons are guilty of this and they all conflict with each other.
2. Recompiling EVERY player model to add a line with extra animations to it, a huge amount of work with a high risk of corruption of certain models. 
3. Creating a dummy model and a bonemerge client-side player model, with subsequent manipulation of bones for proportions (what I'm doing now), the downsides of this method are some terrible matrices, imperfection, constant change of the player model to launch new animations, manipulation of bones at each launch for proportions and inappropriate hitboxes from the dummy model.
