### ISSUE TITLE
Add red variant of combine_intmonitor_001 and combine_intmonitor_003

### ISSUE THREAD

**Issue by bbqsaucegmod** [Facepunch/garrysmod-requests#2479]

**Comment by robotboy655** [comment]
What is `combine_intmonitor_001 `

**Comment by bbqsaucegmod** [comment]
> What is `combine_intmonitor_001 `

oops. models/props_combine/combine_intmonitor003.mdl and models/props_combine/combine_intmonitor001.mdl

**Comment by robotboy655** [comment]
Ok.
