### ISSUE TITLE
Whitelist vtx back.

### ISSUE THREAD

**Issue by Akis-02** [Facepunch/garrysmod-requests#2480]
I do realise it has been talked about a bunch of times in here already and the reason was "it wastes space" and I do acknowledge that but in my opinion removing that extension from the whitelist is a bit damaging, I tried to upload a model from Alien Swarm for instance
but it is literally impossible to upload it because of vtx being blacklisted, I thought originally that it wouldn't be an issue because sometimes some files are not necessary but in this case it was, it led to the model being invisible and I really don't want to go through the process to decompile and recompile the model. I believe that vtx should be brought back for compatibility reasons the gmod model compiler already doesn't create them so I don't see an issue with that.

  model without vtx
![Screenshot (1311)](https://github.com/user-attachments/assets/b18625c3-56aa-4f62-83ef-6a70bd28f8e8)

 model with alien swarm mounted in 
![Screenshot (1312)](https://github.com/user-attachments/assets/1b610e72-8c0d-4402-80a3-a87e3cee9473)
gma window about vtx
![image](https://github.com/user-attachments/assets/9747e4b3-c34e-459a-8bcb-df9585a16207)

**Comment by Akis-02** [comment]
Also the reason "it wastes space" is a bit redundant because I see people uploading maps with 4k textures packed in that are not even used by the map and are from a literal swep pack irrelevant to the map, so does that mean that packing bsps with content should also be blacklisted? I just think this logic is not very good in my opinion.

**Comment by robotboy655** [comment]
Related: https://github.com/Facepunch/garrysmod-issues/issues/5903

This actually seems like a unintended regression, what is disallowed are the `.sw.vtx` files, not all .vtx files.

I will need to adjust the blacklist to allow `.vtx` but still disallow `.sw.vtx`.

And I disagree regarding the reasoning for its exclusion being forced - these files (`.sw.vtx`) are **not used by the game at all**. It would be like allowing you to upload `.pdf` files or similar completely unrelated to the game file types.

**Comment by Akis-02** [comment]
when will this be put in action? by the next gmod update or this can be updated on the workshop itself?

**Comment by robotboy655** [comment]
https://github.com/Facepunch/gmad/commit/96156f81725f4223f2e6851ab935adc04af3e8e1

I have made the necessary changes to gmad.exe on `dev` beta.
