### ISSUE TITLE
Option to force projected textures to always update

### ISSUE THREAD

**Issue by DoctorHugoSource** [Facepunch/garrysmod-requests#2481]
Projected textures and lamps are currently hardcoded to stop updating (position, fov, possibly more) when out of the player's FOV
this makes them very visually jarring when used with things like portals and other render targets
is it possible to add an option to the projected texture object that forces it to update at all times?

one example for the application of this is the tardis addon, which makes extensive usage of lamps to create custom lighting inside interiors, and with current lamps it's impossible to make them update when viewed through the portal

**Comment by robotboy655** [comment]
Which projected textures, exactly? The entity or the Lua class?

**Comment by DoctorHugoSource** [comment]
the lua class i believe? not very familiar with the terminology
i just mean this: https://wiki.facepunch.com/gmod/Global.ProjectedTexture

**Comment by robotboy655** [comment]
Does calling https://wiki.facepunch.com/gmod/ProjectedTexture:Update not do what you want?

**Comment by DoctorHugoSource** [comment]
i've tried calling that every frame, aswell as anything else i could think of, but my lamps absolutely refuse to update while being outside of my field of view
this clip in the gmod discord is a perfect showcase of my issue, and in the latter half of the video you can see how the position of an active projected texture stops updating as soon as it's out of my fov
https://discord.com/channels/565105920414318602/1237798113918451712/1237911229021032518
(for context, the interior is set in the sky, so from certain angles the lamp coincidentally enters my fov and updates)

**Comment by garryspins** [comment]
Can you provide a repro

**Comment by DoctorHugoSource** [comment]
just put a lamp behind any kind of render target portal, be it the tardis or seamless portals, thats the repro
if the lamp ends up behind your fov it will immediately stop updating
for a visual example just look at the link above

**Comment by robotboy655** [comment]
Added `ProjectedTexture:Get/SetNoCull()` (disabled by default), which will disable the culling for when the projected texture is outside of player's frustum.

**Comment by MattJeanes** [comment]
Many thanks for adding this, just used it to deployed a fix to our TARDIS addon (https://github.com/MattJeanes/TARDIS/commit/67666385ec836c9a3a2cd6339a185ee18b4c81dd) which solves a longstanding issue we had with using lamps through portals
