### ISSUE TITLE
Hammer Editor - Func_water_analog cant recognize "Color" as a valid input

### ISSUE THREAD

**Issue by Battlefieldkille** [Facepunch/garrysmod-requests#2482]
You can change func_water_analog's color via outputs, it goes something like this; [ *Activation method* | *func_water_analog name* | Color | 255 0 0 ] - this will make the targeted water have a red color.
But this output method is displayed as an Error in Hammer Editor unfortunately and thus making it annoying to work with.
[funcwateranalog.zip](https://github.com/user-attachments/files/17176000/funcwateranalog.zip)
^ Map for ease of review.

**Comment by robotboy655** [comment]
Done.
