### ISSUE TITLE
Add Lua binding for LinearMove and AngularMove

### ISSUE THREAD

**Issue by A1steaksa** [Facepunch/garrysmod-requests#2484]
It would be very helpful to have Lua bindings for `AngularMove` and `LinearMove`

While this functionality can, technically, be triggered using internal variables, that method is obtuse, difficult to use, and requires viewing engine source code in C++ which presents an unnecessary barrier to an otherwise quite useful function.

Additionally, a hook (or entity hook) for the MoveDone and AngularMoveDone events would be very nice.

**Comment by A1steaksa** [comment]
I’m on mobile, so my ability to find the appropriate classes for this is limited.  I believe it originates in `CBaseToggle`.

**Comment by robotboy655** [comment]
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1952
