### ISSUE TITLE
Exposing map soundscapes to lua

### ISSUE THREAD

**Issue by DoctorHugoSource** [Facepunch/garrysmod-requests#2485]
Currently there is no way to manipulate map soundscapes through lua - the only option is to force the client to run the console commands 'playsoundscape none' and 'soundscape_flush' for stopping and starting the current soundscape respectively
This solution isn't really viable as it requires sv_cheats to be enabled, and soundscape_flush triggers a stutter about 0.3 seconds long
Two small clientside lua functions for starting and stopping the map's current soundscape would be ideal for scenarios where one wants to override in-built map ambience or create a silent environment

**Comment by robotboy655** [comment]
Duuplicate of https://github.com/Facepunch/garrysmod-requests/issues/913

So you'd realistically only want ability to stop individual soundscapes?

**Comment by archangel1104** [comment]
Nah, you're gonna add it. It's an old game and Hugo is making it for the TARDIS addon https://steamcommunity.com/workshop/filedetails/?id=307175678. Maps interfere with the interior sound and it causes pretty bad lag if you use the commands we have right now to attempt to remove the map noise.
