### ISSUE TITLE
Save Previous Connection IP Between Launches

### ISSUE THREAD

**Issue by A1steaksa** [Facepunch/garrysmod-requests#2487]
It would be nice to be able to use `retry` to re-join the server I was most recently connected to when launching the game.

This would be useful for players who might not remember which server they had been playing on on a previous day, as well as for developers to more easily re-join a development server.

As the command currently does nothing when run on a new instance of the game, no one's current usage of the command would be changed.

**Comment by robotboy655** [comment]
There's a whole tab in the server browser called History.

**Comment by A1steaksa** [comment]
> There's a whole tab in the server browser called History.

A whole tab that does not have the option to sort by or even view your most recent connection time, which makes it practically useless if you've joined more than a small handful of servers or happen to remember the name of the server you were on.

Given the way Garry's Mod servers are named, simply remembering the title is not as easy as it could be.

_"Was it Shadow Gaming? Synapse Gaming? Supreme Gaming? Syndicate Gaming?"_
You wind up wasting time re-joining a bunch of servers that you left for a reason to find the one you didn't leave.

**Comment by robotboy655** [comment]
![Image](https://github.com/user-attachments/assets/c53082ff-ca69-49c6-8814-e07fb81ef66a)


Does this change adequately address that specific concern?
(This would appear in every tab, not just history)

**Comment by A1steaksa** [comment]
This seems like it would solve that issue with the server browser, yeah.

I'd still like to be able to `retry` on a new instance of the game to make rejoining a development server faster, but that's a secondary concern to the more player-facing issue this change would solve.
