### ISSUE TITLE
TTT Localization Lines

### ISSUE THREAD

**Issue by NovaDiablox** [Facepunch/garrysmod-requests#2488]
### Details
https://github.com/Facepunch/garrysmod/blob/70fc8804ce2bf8aff246bdd06df344745d3e7df6/garrysmod/gamemodes/terrortown/gamemode/lang/english.lua#L159
https://github.com/Facepunch/garrysmod/blob/70fc8804ce2bf8aff246bdd06df344745d3e7df6/garrysmod/gamemodes/terrortown/gamemode/lang/english.lua#L164

The lines 159-164 should be full sentences instead of words or word groups. It causes weird and grammatically incorrect translations and there is no workaround.

**Comment by NovaDiablox** [comment]
Hmm to think about it, this is a both request and an issue at the same time. I hope its in the right place.

**Comment by robotboy655** [comment]
![image](https://github.com/user-attachments/assets/1f5ce465-6975-446b-8421-b2a0f785fadd)

Open a Pull Request with a fix if you want to.
