### ISSUE TITLE
Unblock "KillServer" or give me an alternative.

### ISSUE THREAD

**Issue by MagentaIris** [Facepunch/garrysmod-requests#2498]
KillServer was added to the blocked command list it seems **because i'm assuming it can be used maliciously** which, you can do with literally any part of lua.

I use KillServer in some of my menu UI in order to get the client to disconnect back to the main menu, because my gamemode uses a custom escape menu to do all kinds of neat little diegetic things.

If you're going to block KillServer, at least give me an alternative to this.

Or am I going to have to remove the option entirely and just make the player have to use the disconnect/quit commands from the Main Menu that I can't add custom options to because there is no library to do so.

**Comment by robotboy655** [comment]
If you want the player to disconnect, you use the aptly named `disconnect` concommand.

**Comment by robotboy655** [comment]
I tested it before making the comment, it was not blocked in my tests.

**Comment by MagentaIris** [comment]
Alrighty, Good to know theres atleast an alterantive.
