### ISSUE TITLE
npc_combine_camera output

### ISSUE THREAD

**Issue by DatGuy64** [Facepunch/garrysmod-requests#2505]
Add the output OnLostEnemy from the "BaseNPC outputs" to the npc_combine_camera

![Image](https://github.com/user-attachments/assets/6d55aed0-5c85-41c6-bfdd-064670c108ec)

camera:Fire('AddOutput', "OnLostEnemy trigger:RunPassedCode:hook.Run('OnLostEnemy'):0:-1") is not getting called

**Comment by robotboy655** [comment]
Done.
