### ISSUE TITLE
October 29 Update - raise sbox_maxconstraint count to 2,000 instead of 1,000

### ISSUE THREAD

**Issue by pauliewalnut** [Facepunch/garrysmod-requests#2507]
Hello,

Hope all is well - this doesn't necessarily concern a new feature to request, but it seemed like this category fits best. Having read the new sbox_maxconstraints functionality in store for the October 29 update, I saw it is set by default to **1,000**. 

As a builder of vanilla duplications including the popular [Field Artillery](https://steamcommunity.com/sharedfiles/filedetails/?id=2492304004), this default limit will likely cause problems for players who would like to use my dupes, especially given that most players are largely unfamiliar with console commands/game limits. Especially for vanilla duplications, a lot of advanced sandbox dupes use constraint counts of >1,000, from my experience up to **2,000**. Field Artillery for instance has a lot of local no-collide constraints to contain 48 cannonballs in an enclosed space, resulting in a ~1300 constraint count. Since many famous dupes have very high constraint counts, this issue will affect more people's dupes than just mine, including many famous dupes on the Garry's Mod workshop.

As such, I am wondering if your team were open to consideration to increase the default limit for sbox_maxconstraints to **2,000**. Many thanks in advance - have a good one!

**Comment by robotboy655** [comment]
I think Sandbox servers can easily adjust the limits to the needs of their players, but I will bump the default to the suggested value.
