### ISSUE TITLE
Make Point_devshot_camera write the images in .png instead of .jpg

### ISSUE THREAD

**Issue by Unusuario2** [Facepunch/garrysmod-requests#2511]
### Details

Self explanatory.
why? because the quality loss in darker areas is very significant with a lot of artifacts, so it would be nice if Point_devshot_camera could write photos in .png format instead of .jpg

**Comment by robotboy655** [comment]
It already uses `.tga` files as of October 2024 Update, no? The `screenshot` command it uses only writes `.tga` files.
