### ISSUE TITLE
Add NPC:GetCurrentScene

### ISSUE THREAD

**Issue by URAKOLOUY5** [Facepunch/garrysmod-requests#2513]
### Details
There's no way to find out SceneEntity on NPC (to check if it speaking, for example)

In C++ for GetCurrentScene (on BaseFlex):

```cpp
CSceneEventInfo curScene = m_SceneEvents.Head();

return (CBaseEntity*)(curScene.m_hSceneEntity.Get());
```

**Comment by robotboy655** [comment]
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/2274
