### ISSUE TITLE
Demo documentation

### ISSUE THREAD

**Issue by marcelgroeneveld** [Facepunch/garrysmod-requests#2529]
### Details
There exists little, yet useful, documenation for Source SDK2013  and other versionse, regarding demo (.DEM) files. Demo files are recordings of in-game events. In other source games, these demo's can be parsed using a variety of tools to create heatmaps, work with player data and even to replay events. A popular tool for CSGO for example is cs-demo-manager.

###use case
Even Garry's Mod demo's hold interesting and useful data which can be used for heatmaps, match playback and statistics. Furthermore, demo's are a great tool for server owners and administrators to resolve conflicts. Demo's can automatically record events on a player's computer without them having to manually start and stop a demo.

###Downside of demo's
Demos as previously mentioned hold data, like messages, user commands and other data and record these each tick. This means that when playing back a large demo the engine has to load all of these events. Demo's also have no method of playing in reverse or going back to a recently played Tick: The whole demo has to be replayed from tick 0 in order to review what happens in a Tick. Furthermore, demo's can corrupt on their own and refuse to play even though the data itself in the demo is intact.

### Depriciation of advancedFX
A great method of recording in-game events and using that data would be half-life advancedFX. However, this does not support 64bit binaries and has planned End Of Support next year. 

### Example:

Here is a code example of MessageTypes in source demo's pulled from
`enum MessageType : byte {
    SignOn = 1,
    Packet = 2,
    SyncTick = 3,
    ConsoleCmd = 4,
    UserCmd = 5,
    DataTables = 6,
    Stop = 7,
    CustomData = 8,
    StringTables = 9,
};`

Garry's Mod demos carry the Header: "GMODEMO" instead of "HL2DEMO" for most source mods. Furthermore, when modifying the header of a garry's mod demo to 'HL2DEMO' so demo parsers can read them; most, if not all, fail with a mix of errors. An example of this error would be:
`rror: Error while reading bits from stream: Unmatched discriminant '52' found while trying to read enum 'MessageType'
caused by: Unmatched discriminant '52' found while trying to read enum 'MessageType'`
further indicating that garry's mod demos are different from their source sdk counterparts. 

###the request
For documentation to be added in regards how Garry's Mod demos are built, or having the community develop documentation by releasing relevant source files like 'demofile.h'

**Comment by robotboy655** [comment]
There are no changes to the demo format itself, besides the header.

https://developer.valvesoftware.com/wiki/DEM_(file_format)

However the game has multitude of changes to various base Source Engine entities, as well as a number of custom entities which I expect whatever your are using is not set up to handle.

There are no plans to release any source code to the public.
