### ISSUE TITLE
Remove the sv_cheats restriction on the commands for configuring func_precipitation

### ISSUE THREAD

**Issue by kitrodian** [Facepunch/garrysmod-requests#2533]
### Details
The commands to change the visual settings for func_precipitation are currently sv_cheats protected. This is problematic because there are multiple maps on the workshop that rely on these commands to make func_precipitation look any good as the default settings are genuinely terrible and look like a bunch of vertical streaks slowly falling from the sky.

These convars include:
r_rainalpha
r_rainlength
r_rainspeed

[My most recent map suffers from this. In singleplayer it looks great, but in multiplayer these commands are restricted so the rain looks terrible.](https://steamcommunity.com/sharedfiles/filedetails/?id=3367068498)
![Image](https://github.com/user-attachments/assets/4fb0d577-b9d1-4417-93a0-b283b5aa12bf)

I really do not believe that any potential advantages a user can gain by changing these values are great enough to warrant these being sv_cheats protected, either.

**Comment by robotboy655** [comment]
I think using the new particle system based precipitation types would be a better solution to this, compared to using the legacy systems and hacking around for them to look a bit better.

https://github.com/Facepunch/garrysmod-requests/issues/809
