### ISSUE TITLE
Implement new soundscape features from Left 4 Dead engine branch or newer

### ISSUE THREAD

**Issue by siobhan-saoirse** [Facepunch/garrysmod-requests#2536]
### Details
Since Left 4 Dead, The soundscape system has changed and when the soundscapes from the maps are used in Garry's Mod, Sounds that depend on certain area play in the background globally instead of playing at the specified position.

**Comment by siobhan-saoirse** [comment]
```
	//dead bodies Flies
	"playlooping"
	{
		"volume"	".9"
		"pitch"		"120"
		"wave"		"ambient/creatures/Flies_Loop.wav"
		"origin"	"8155.776855, 3031.043945, -147.455017;"
		"soundlevel" 	"SNDLVL_65dB"
	}
```

**Comment by siobhan-saoirse** [comment]
The "Origin" command isn't implemented

**Comment by robotboy655** [comment]
Done.

Implemented `origin` for `playlooping`/`playrandom` and `ambientoriginoverride` for `playsoundscape`.

**Comment by siobhan-saoirse** [comment]
Thank you

**Comment by conneath** [comment]
~`playlooping` should receive support for `position random`, [since that's another L4D feature](https://developer.valvesoftware.com/wiki/Soundscape#playlooping:~:text=playlooping%20can%20also%20use%20position%20random.)~

**Comment by robotboy655** [comment]
It does support it.
