### ISSUE TITLE
Add PhysObj:GetIndex()

### ISSUE THREAD

**Issue by brandonsturgeon** [Facepunch/garrysmod-requests#2537]
### Details
We have `Entity:GetPhysicsObjectNum( number )` but no way to get what index a PhysObj exists at in its entity.

`PhysObj:OutputDebugInfo()` prints:
```
-----------------
Object: Mossman.mdl
Mass: 19.0 (inv 0.053)
Inertia: 1.26, 2.09, 2.00 (inv 0.795, 0.479, 0.501)
Velocity: 0.00, 0.00, -0.00
Ang Velocity: 0.00, 0.00, -0.00
Damping 0.01 linear, 1.50 angular
Linear Drag: 0.00, 0.01, 0.01 (factor 1.00)
Angular Drag: 0.00, 0.00, 0.00 (factor 1.00)
attached to 6 controllers
5) sys:friction
4) sys:friction
3) sys:friction
2) sys:constraint
1) vphysics:drag
0) sys:gravity
State: Asleep, Collision Enabled, Motion Enabled, Flags 1127 (game 0018, index 1)
Material: flesh : density(900.0), thickness(0.00), friction(0.80), elasticity(0.25)
CollisionModel: Compact Surface: 1 convex pieces no outer hull
```

So I'd expect `PhysObj:GetIndex()` to return `1` in this case (in the output: `(game 0018, index 1)`).
Alternatively, this could be added as a second return on `PhysObj:GetEntity()`

Particularly this could be useful in `ENTITY:PhysicsSimulate( phys, delta )` when you need the PhysObj's index for something like `ENTITY:TranslatePhysBoneToBone( number )`

PhysObjs can't be used as table indices so keeping your own copy and performing lookups isn't reasonable. There doesn't seem to be any way to perform this lookup without looping through something.

credit @bonyoze for inquiring in the discord

**Comment by robotboy655** [comment]
Added.
