### ISSUE TITLE
Support for Clientside Ragdoll contents in Trace masks.

### ISSUE THREAD

**Issue by MagentaIris** [Facepunch/garrysmod-requests#2540]
I may be bumbling around and unable to replicate the ability to detect C_Class Clientside Ragdolls, But it would be nice to be able to have Traces on the client detect client side ragdolls.

**Comment by robotboy655** [comment]
https://wiki.facepunch.com/gmod/Structures/Trace#hitclientonly

This should be what you are looking for.

**Comment by MagentaIris** [comment]
Perfect, I'll give that a try.
