### ISSUE TITLE
Function/Hook to pause physics

### ISSUE THREAD

**Issue by wrefgtzweve** [Facepunch/garrysmod-requests#2541]
It seems like there's already functionality for it in the engine. Seems relatively straight forward to add, could be either a hook or a function eg. `physenv.Enable()` `physenv.Disable()` `physenv.Status()` `physenv.Toggle()` or `hook.Add( "PhysenvShouldSimulate", `

Engine code:
`PhysFrame`
<https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/physics.cpp#L1676-L1677>
![Image](https://github.com/user-attachments/assets/e7a95634-1bf4-4ca3-9790-e1f177dd4776)
`g_PhysicsHook.ShouldSimulate`
https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/physics.cpp#L134-L137
![Image](https://github.com/user-attachments/assets/1e96c76a-9a31-4dd6-863a-d2d5bfef1a4d)

Being able to "pause" physics would be pretty useful for when there's server lag, you could even theoretically only run physics once every 2 ticks for example.

**Comment by wrefgtzweve** [comment]
Seems like someone made a DLL to do the same https://github.com/Astralcircle/gmsv_physframe confirming that it's entirely possible and seemingly pretty easy to add.

**Comment by robotboy655** [comment]
Added `physenv.SetPhysicsPaused` and `physenv.GetPhysicsPaused`
