### ISSUE TITLE
Enable dynamic changing of r_lightcache_zbuffercache (Light Cache perf improvement)

### ISSUE THREAD

**Issue by WinterPhoenix** [Facepunch/garrysmod-requests#2542]
### Details
A big thing that hurts client performance on high-population servers is Light Cache misses, especially when around a lot of players. There are a number of reasons for this, ranging from [only 200 entries being allowed in the cache](https://github.com/RaphaelIT7/obsolete-source-engine/blob/0b8cf62adc1551a77649a3ad0ab224a555d6dc48/engine/lightcache.cpp#L56) to cache misses for other reasons, like entities constantly moving to somewhere the client hasn't calculated the light cache for.

Which brings us to `r_lightcache_zbuffercache`. Turning it on leads to a BIG performance boost, without (as far as I can tell) any degradation in quality. As I understand it, it's essentially a second cache that's populated with shadow hits from raycasting (early exit optimization).

One problem though, since it's disabled by default, **the game crashes** if you enable it after loading the map. This is because it tries to access `CMapLoadHelper.GetMap()->shadowzbuffers`, which is only allocated while the map is loading (if `r_lightcache_zbuffercache` is turned on) and `NULL` otherwise.

Memory allocated here (empty):
https://github.com/RaphaelIT7/obsolete-source-engine/blob/0b8cf62adc1551a77649a3ad0ab224a555d6dc48/engine/modelloader.cpp#L1132-L1137

Ultimately used here:
https://github.com/RaphaelIT7/obsolete-source-engine/blob/0b8cf62adc1551a77649a3ad0ab224a555d6dc48/engine/lightcache.cpp#L995

Populated here:
https://github.com/RaphaelIT7/obsolete-source-engine/blob/0b8cf62adc1551a77649a3ad0ab224a555d6dc48/engine/lightcache.cpp#L1033-L1037

### Observed performance increase
https://winteris.moe/share/2024-11-22_16-14-14.mp4

### So, my request
Please either remove the check for `if ( r_lightcache_zbuffercache.GetInt() )` when `shadowzbuffers` is initially allocated, so it's always available, or implement some sort of dynamic allocation/freeing when the ConVar is toggled so that the game doesn't crash trying to turn it on after the fact.

Being able to toggle it from Lua without crashing would help IMMENSELY for high-population servers that often have many players in the same PVS.

**Comment by robotboy655** [comment]
Made it allocate the necessary memory if it hasn't done so already. It will print a message when it does so.

**Comment by WinterPhoenix** [comment]
Excellent!! Thank you Rubat!
