### ISSUE TITLE
Bind NPC:IsInViewCone & NPC:GetFieldOfView & NPC:SetFieldOfView to Lua

### ISSUE THREAD

**Issue by DrVrej** [Facepunch/garrysmod-requests#2546]
### Details
- NPC:IsInViewCone( entity | vector ) [Source Link](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/basecombatcharacter.h#L143): Determines if the given entity or vector is in the NPC's view cone.
- NPC:GetFieldOfView() [Source Link](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/basecombatcharacter.h#L476): Returns the field of view of the NPC.
- NPC:SetFieldOfView( float ) [Source Link](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/basecombatcharacter.h#L476): Sets the field of view of the NPC from the given float number.

**Comment by robotboy655** [comment]
Added `NPC:SetFOV`, `NPC:GetFOV` (in degrees), `NPC:IsInViewCone`

**Comment by DrVrej** [comment]
@robotboy655 Thank you for adding these! Could we also have at least the first 2 suggestions from here?  --> https://github.com/Facepunch/garrysmod-requests/issues/2502 It would go along the FOV functions as both of those control where the FOV is set and which direction, it would finally give us complete control for NPCs! Both of those methods would also effect the result of the new `IsInViewCone` function! Thank you!
