### ISSUE TITLE
Ignore `Entity.FollowBone` second argument if first argument would remove parent

### ISSUE THREAD

**Issue by Denneisk** [Facepunch/garrysmod-requests#2547]
`Entity.FollowBone` should not type check its second input if its first input is `nil` (or `NULL`). In other words, the call `someEnt:FollowBone(nil)` should not produce an error.

The function is used to remove some bone-following flags applied to the child, so I find it's reasonable to assume the second argument is worth ignoring when wanting to remove this state.

One strategy to solve this would be to default the second argument to 0, like `SetParent` does. `FollowBone` is more intentional with its naming and usage, so I think having a default value is a bit excessive, but maybe it's a simpler solution.

**Comment by robotboy655** [comment]
Done.
