### ISSUE TITLE
-softencosine parameter for VRAD

### ISSUE THREAD

**Issue by blackout201** [Facepunch/garrysmod-requests#2548]
### Details

[-softencosine](https://developer.valvesoftware.com/wiki/VRAD) "Softens coloured lighting so it blends more accurately" quote from Valve wiki. In other words, this helps make lighting more realistic. This parameter exists in the vrad.dll supplied by Slammin Source Map Tools. Could this be implemented into the official vrad.dll? Thanks.
![Image](https://github.com/user-attachments/assets/e9ae3982-444b-4e17-8f56-2cd2234641a1)
![Image](https://github.com/user-attachments/assets/b4b6187e-f3bb-4d55-b72d-aa60c59524f0)

**Comment by robotboy655** [comment]
The software you mention is not open source, so there's no way to know what the parameter does.

That being said, I see something with similar name in CS:GO's VRAD that is applied always, so I will add that behind `-softencosine` flag.

I can't see any difference from the picture besides the flag making everything darker.
