### ISSUE TITLE
Add a way to make more entities un-saveable

### ISSUE THREAD

**Issue by b0mbie** [Facepunch/garrysmod-requests#2549]
### Details
Currently, there is no way to mark scripted entities (or, in fact, any other entity) as un-saveable by the `gmsave` system.

When saving, [`gmsave.SaveMap`](https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/includes/gmsave.lua#L93) checks whether an entity should be saved or not, which is mostly delegated to [`gmsave.ShouldSaveEntity`](https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/includes/gmsave.lua#L93). Both of these functions don't ask the entities or the gamemode whether they should be saved or not.

Certain entities may simply not want to be saved, with one reason being fragile state that can't feasibly be cleanly preserved across saves. An example of this being an issue is the `fakeground` entity that the [addon _Walk on Moving Props_](https://steamcommunity.com/sharedfiles/filedetails/?id=2512464000) creates for giving players something to stand on. Saving a map with this addon running while someone is standing on a prop will make that temporary `fakeground` entity appear in the save, which manifests on load as an invisible prop that players can collide with. I imagine it would be a nightmare to make these entities work in saves, so the simple solution of just not letting themselves be saved should be very useful.

I propose to add either `boolean ENT.Saveable` or `boolean ENT:ShouldSave()`. Additionally, something akin to `boolean GM:ShouldSaveEntity( Entity entity )` could be added to let gamemodes & hooks completely override the verdict of `gmsave.ShouldSaveEntity`.

**Comment by robotboy655** [comment]
https://wiki.facepunch.com/gmod/duplicator.Disallow

**Comment by b0mbie** [comment]
Oh. My bad - didn't think to check the `duplicator` stuff.

Yeah that works.

**Comment by robotboy655** [comment]
Alternatively, you can probably set some conditional variables here: https://wiki.facepunch.com/gmod/ENTITY:PreEntityCopy and not spawn the entity in your custom https://wiki.facepunch.com/gmod/duplicator.RegisterEntityClass
