### ISSUE TITLE
Allow modders to change the attachment ID ENTITY:FireBullets uses

### ISSUE THREAD

**Issue by T-Rizzle12** [Facepunch/garrysmod-requests#2563]
### Details
Currently, weapon tracers created by FireBullets only use attachment 1 for bullets fired by it. This sucks for weapons such as dual pistols since the tracer will only come from the first pistol. Some modders have created ugly workarounds for this, but it would be nice to have an engine-level implementation since it is much faster than Lua ones. I have found the code that manages how tracer positions are defined for FireBullets and included a link to the Source 2013 SDK.
https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/shared/baseentity_shared.cpp#L2170-L2211

**Comment by robotboy655** [comment]
You can create your own tracer effects and use whatever attachment or whatever else have you.

Also https://wiki.facepunch.com/gmod/WEAPON:GetTracerOrigin this exists

**Comment by T-Rizzle12** [comment]
Ok, thank you for quick reply.
