### ISSUE TITLE
Lua binding to disable server hibernation (primarily related to bots)

### ISSUE THREAD

**Issue by TeddiO** [Facepunch/garrysmod-requests#268]
Currently JVS's implementation of the custom bots is fantastic, however they still seem to follow the general rule of, if the last player leaves, it will then punt all bots. I'm proposing that a binding for ::SetServerHibernation(bool) in lua be available so we can control whether or not we want the server to hibernate even when the last player leaves. 

:>

**Comment by neico** [comment]
If you're talking about some implementation it would be wise to also link to it for those who don't know it (me for example)

Is it done in lua? a module or a source plugin?

If it's done in lua then it might be worth thinking about using the Tick hook instead of the Think one (tick is being called even when the server goes into hibernation)

I also never really looked much into server hibernation, so if I'm missing something here like are bots kicked due to the server going into hibernation (which would make sense at least)

**Comment by TeddiO** [comment]
If you don't know what it is then you probably don't need to know, however to explain - 

Hibernation is something srcds does when all players have left a server (or when a server has first started) - designed to reduce memory and CPU footprint on a server. Essentially what was suggested was a custom implementation designed to control that behaviour. As this isn't exposed in the SDK and I don't have access to the engine, I can't suggest any implementation.

**Comment by neico** [comment]
I do know that much, it was more a general understanding question (I though that I was pretty clear on that :/) if such a feature is even needed (because so far I don't see any reason to fiddle with the hibernation)

**Comment by TeddiO** [comment]
I'm not trying to come across as facetious and I apologise if I did, however the request wouldn't be there if there wasn't a use case :)

One use case is if I want NPCs to continue certain behaviour even when players have disconnected (think maybe NPC pathing) - or if I still want certain server logic to run with no players available. I can appreciate why the behaviour as is - but with capacity today as it is, having the ability to change this would be nice.

**Comment by neico** [comment]
Ok then, are we talking about normal NPC's like npc_gman or custom ones using NextBot?

**Comment by TeddiO** [comment]
If you read my original post, you see I refer to NextBot, but in theory it could apply standard NPCs as well.

**Comment by neico** [comment]
Well for NextBot I'd setup a "Tick" hook to call NextBot:RunAI() (if that isn't called by the engine due to hibernation anymore) and see how far that goes.

This obviously won't work on default NPC's which is why wanted to make sure... (If they stop moving trough hibernation then they'll stay like that, but I also don't see much reason to let them do things while no one's there)

**Comment by TeddiO** [comment]
Both Think and Tick hooks get blocked upon hibernation. And while you don't see a use-case, that doesn't mean there isn't one.

**Comment by neico** [comment]
Well Bromsock which uses "Tick" to handle networking requests while no player is present proves me otherwise...

**Comment by TeddiO** [comment]
Is Tick fired even when the server first boots for the first time? Think does have similar behaviour where it can continue processing even when the last player leaves, but isn't guaranteed. 

Tick still doesn't prevent bots (Nextbot and otherwise) from being punted when the last player leaves either.

**Comment by neico** [comment]
That bot thing is about a Fake Client (probably player.CreateNextBot?) being kicked upon the last player leaving?

I just tested creating one via player.CreateNextBot and he didn't get kicked out, only after joining and then leaving, so I at least understand now what you mean by punting...

Which makes me wonder if the bot is able to do things while no one's there, theoretically all you need to do is rejoining them upon PlayerDisconnected which looks a bit strange though, so maybe a convar like in CS:S that handled bots being kicked or not upon the last player leaving would be one thing to handle this situation.

**Comment by sammyt291** [comment]
+Support for this,
We have scripts running that require bots to be on the server,
so it would be fantastic to be able to disable the punting of bots or the hibernation entirely.

**Comment by Bo98** [comment]
> I'm proposing that a binding for ::SetServerHibernation(bool)

This seems to have no effect nor does it gets called by anything for me.

**Comment by mcd1992** [comment]
:+1: This would help out in some development situations.

**Comment by willox** [comment]
A startup parameter?

**Comment by mcd1992** [comment]
neico linked a solution that CS:GO uses but a startup param would work as well. Just need a way to have bots stay in while a server is empty and timers/think to keep running.

**Comment by willox** [comment]
A ConVar!

**Comment by willox** [comment]
Added two ConVars: "sv_hibernate_think" and "sv_hibernate_drop_bots".
