### ISSUE TITLE
Console I/O hooks.

### ISSUE THREAD

**Issue by Nethie** [Facepunch/garrysmod-requests#269]
Retrieving the console output is almost impossible without doing it the tricky, mostly inefficient way (via -condebug and file reading)

I and other people would like to have these hooks implemented to the game.

These hooks can be used to create external consoles such as on screen display for quick debugging or to block the trivial informations such as "Nav File is wrong or something (4)" or the warnings that very often occur on crowded servers.

The hooks can be named anything, but my suggestion is:
ConsoleInput( text, color, typeEnum )
ConsoleOutput( text, color, typeEnum )

**Comment by Yuri6037** [comment]
+ Much Support. With these hooks i'd be able to generate (enough) some logging files, so when a client has a gamemode bu, he can just give me his logging file !!

**Comment by DrVrej** [comment]
+Support

**Comment by GGG-KILLER** [comment]
any updates on this?

**Comment by willox** [comment]
on behalf of @GGG-KILLER this request is officially canned

**Comment by GGG-KILLER** [comment]
what?
I didn't do anything....

**Comment by zerfgog** [comment]
:+1:

**Comment by Kefta** [comment]
RIP

**Comment by DrVrej** [comment]
broooo why u do this

**Comment by Nekiplay** [comment]
pls add

**Comment by VaasKahnGrim** [comment]
6 years later and still no option to get rid of the error msg in the top left corner of the screen on shitty darkrp copy paste servers. :(

**Comment by hanm13** [comment]
Any update?

**Comment by KingDavidW** [comment]
Bump because it'd still be great

**Comment by robotboy655** [comment]
The answer is no.
