### ISSUE TITLE
Content Streaming

### ISSUE THREAD

**Issue by CaptainBigButt** [Facepunch/garrysmod-requests#270]
I'm not sure if this is still possible but it'd be wonderful to stream content as the player, uh, plays. This was great back when Garry's Mod brought in the toybox features. Lots of good servers often have ridiculously large amount of content these days which means people sit in the loading screen for quite a while, especially if they have slow internet. If possible, it'd be great to give players the option to just download the workshop addons or content files (models, textures, and sounds) while they just skip ahead and join the server. 

Just to elaborate a little in case this is still possible to re-add, it'd be great to allow the gamemode to check when a file finishes downloading so it can reload the items. Previously models would often successfully reload after being streamed. Secondly, it might be necessary to allow server owners to choose what files can be streamed (lua.AddStreamedResource?) so necessary ui textures or map textures can be downloaded beforehand.

**Comment by zerfgog** [comment]
game.LoadGMA by @willox

**Comment by Kefta** [comment]
For normal files: http.Fetch and file.Write to the data/ folder. Materials, models, and sounds can all be used from there. https://github.com/Facepunch/garrysmod-issues/issues/3791 is the only issue
For GMAs: ``steamworks.Download`` and ``game.LoadGMA``
For VPKs: once https://github.com/Facepunch/garrysmod-requests/issues/1381 is fulfilled, ``http.Fetch`` and ``file.Write`` to the data/ folder with ``game.LoadVPK``
