### ISSUE TITLE
Make Entity:StopParticles() remove the particles and not just stop the particles

### ISSUE THREAD

**Issue by gonzalologorg** [Facepunch/garrysmod-requests#273]
I think that would be nice to make Entity:StopParticle() delete the particles, and not just stop the emitter, or at least make something like Entity:RemoveParticles() for particles that doesn't have a lifetime (Domination, magic, etc)

Example:
![2014-05-20_12-47-37](https://cloud.githubusercontent.com/assets/7375225/3148470/05764f22-ea61-11e3-89d3-0f890fd035d2.jpg)

The only way that i found of get rid of this just was moving the model outside of the map, but that's obviously it's not the best way of handle the situation

**Comment by robotboy655** [comment]
http://wiki.garrysmod.com/page/Entity/StopAndDestroyParticles
