### ISSUE TITLE
RichText OnTextClicked hook

### ISSUE THREAD

**Issue by Python1320** [Facepunch/garrysmod-requests#284]
Right now, whatever link you put into a RichText clickable text it opens in steam overlay. Could we have a hook into OnTextClicked to block the default behaviour to allow lua to do things instead of opening the damn overlay?

Simple implementation:
Add binding `RichText:SuppressNextLink()` which sets `m_bSuppressNextClick = true;`

Add after
`void RichText::OnTextClicked(const wchar_t *wszText)`

```
if ( m_bSuppressNextClick ) {
    m_bSuppressNextClick = false;
    return;
}
```

Now we can in RichText's ActionSignal "TextClicked" call RichText:SuppressNextLink() to block the default behaviour and handle the thing in Lua!

**Comment by robotboy655** [comment]
What exactly is wrong with the example @ https://wiki.facepunch.com/gmod/Panel:InsertClickableTextEnd ?
