### ISSUE TITLE
Add a concommand to hide DataTable Warnings

### ISSUE THREAD

**Issue by SkyfireFR** [Facepunch/garrysmod-requests#294]
Hello! 

I saw that using the RPG or the Airboat can create datatable warnings about some angles.
I don't know if these issues are fixed but I'm asking for a concommand because others "useless" warnings may happen in the future about anything.

By the way, it could be great to be able to hide some EmitSound errors like "volume/pitch out of bounds".

Thank's for reading!
Skyfire-FR

**Comment by SkyfireFR** [comment]
Why did you close it? Is it fixed or something?

**Comment by robotboy655** [comment]
No, it will not be added.

**Comment by robotboy655** [comment]
See my last comment @ https://github.com/Facepunch/garrysmod-issues/issues/1134
