### ISSUE TITLE
Add file.Rename file.RenameFolder

### ISSUE THREAD

**Issue by SimonSchick** [Facepunch/garrysmod-requests#30]
Technically this is already possible, but it would be nice to let the OS do this rather than having to to write the new file and delete the old one.

As for folders this is much more complicated to achieve in Lua, so please add this.

**Comment by TehBigA** [comment]
The file part of this seems like it might be simple if the file library works off `IFileSystem` since it has `IFileSystem::RenameFile( char const *pOldPath, char const *pNewPath, const char *pathID = 0 )`.

Was just hoping to use something like this for true atomic saving.

**Comment by mcd1992** [comment]
Garrysmod uses bootil for its filesystem library. You would need to either add a wrapper that does Remove/CreateFolder and RemoveFile/Write to garrysmod or create two rename functions in bootil and ask for a binding in garrysmod.
