### ISSUE TITLE
Implement func_instance

### ISSUE THREAD

**Issue by Donkie** [Facepunch/garrysmod-requests#310]
Instancing is a relatively new term since l4d2 I believe, which you use to put vmf's inside vmfs. Its like prefabs but 100 times more useful. Currently if you load a map which contains instancing, gmod will complain and say something error about func_instance, since gmod is on ep2 engine where instancing wasn't yet known about.

There's currently a workaround in hammer where you can simply merge (collapse) the instances into the map but it's troublesome and messy, having a real implementation of this would be great.

https://developer.valvesoftware.com/wiki/Instance

**Comment by ATrustedFriendInScience** [comment]
Currently adding This "InstancePath  "maps/instances/" " to the Gameinfo.txt and compiling the map the map from tf2 gets it work.

**Comment by robotboy655** [comment]
I am fairly certain this is already a thing, I have used this in GMod's Hammer.

The gameinfo.txt tweak was applied to the game as well.
