### ISSUE TITLE
Better AutoRefresh Hooks?

### ISSUE THREAD

**Issue by 8BallBomBom** [Facepunch/garrysmod-requests#311]
Would it be possible to add a new hook for AutoRefresh which would return some useful information and run for any type of reload? or maybe update the current OnReloaded hook, turn it into a global hook instead of a gamemode hook and return the extra information?

For example, i can't seem to get the OnReloaded hook working if i refresh any files which are in addons.

It would be great to have information being returned like the file name and file location of files being reloaded, maybe if you hooked into the shared version of the hook then it would also return what realm the files were reloaded on?

Along with that it would be great if the hook was called for every reload as long as the files being reloaded were in locations they are allowed to run in.

If not, would it be possible to add the OnReloaded hook to more things that may benefit from this system?

Like PANEL:OnReloaded()

**Comment by TehBigA** [comment]
It would be nice if we did get enhanced refresh hooks to be able to return true to force a reload on files that report unhandled. I noticed if files are included by a module that is required it wont auto-refresh them. Even if the file is required from an autorun.
