### ISSUE TITLE
Model invalidation

### ISSUE THREAD

**Issue by suchipi** [Facepunch/garrysmod-requests#315]
If a model doesn't exist and the engine tries to load it, it will remain an error even if the model exists later. If models could be invalidated, models that didn't exist the first time they were loaded could get "rechecked" later.

**Comment by willox** [comment]
http://wiki.garrysmod.com/page/game/MountGMA makes this possible. If you have any entities spawned, you will want to destroy/create their shadows.

**Comment by suchipi** [comment]
Neat, thanks!
