### ISSUE TITLE
Return "BOT" on client when running bot:SteamID()

### ISSUE THREAD

**Issue by Mista-Tea** [Facepunch/garrysmod-requests#317]
Currently, if you try to print the steamid of a bot via the client, a string containing "NULL" will be returned.

This is incorrect behavior as everything else that returns a player steamid, such as hooking into `gameevent.Listen( "player_disconnect" )`, returns "BOT" as the steamid on the client. Calling bot:SteamID() serverside will correctly return "BOT" as well.

This causes conflicting behavior when trying to use bots to test clientside things like derma panels because you may have a table entry under "NULL" for a bot but everything else uses "BOT".

I'm sure this would be a fairly easy fix. Not a high priority or anything but it is rather inconveniencing.

**Comment by mcd1992** [comment]
+1

This issue doesn't really hurt anything but the inconsistency creates the need for another string comparison; in some situations.

**Comment by nubpro** [comment]
Can we have this looked at?

I stumbled across this bug and it took me a while to figure out what was actually faulty.

**Comment by Noiwex** [comment]
:IsBot()

**Comment by T-Rizzle12** [comment]
@robotboy655
This should be closed since it was fixed in an update!
