### ISSUE TITLE
Set turnspeed of a NextBot loco

### ISSUE THREAD

**Issue by wyozi** [Facepunch/garrysmod-requests#318]
AFAIK there's no way to set the rate at which a nextbot turns when using MoveToPos or FaceTowards

**Comment by robotboy655** [comment]
I can add this, but it won't affect anything but the angles, so you will get things like NPC moving backwards, etc at low values.

**Comment by wyozi** [comment]
There are some places where the pathfinding for MoveToPos doesn't work properly, and it seemingly is because of the low turnspeed of the nextbot. That's the main reason for this suggestion.

**Comment by robotboy655** [comment]
Turn speed does not affect pathfinding.

**Comment by wyozi** [comment]
I'm not talking about pathfinding but traversing the pathfinded path. 

http://i.imgur.com/H60HWku.jpg
This is a bad example (because I can't remember the actual places where this happens), but in spots that are reminiscent of this spot the nextbot does not always manage to start walking uphill, but falls back to the ground below. It seemingly is caused by the slow turn rate.

**Comment by robotboy655** [comment]
Yeah, it's what I meant, I am currently testing that exact spot and higher or lower turn speed does not affect how the NPC traverses on the map at all. All it does is limits how fast the visual angle changes.

And I am not seeing any other methods that might fix the problem. I wonder if L4D2 / TF2 mvm has the same problem on that map in that spot.

**Comment by robotboy655** [comment]
I guess there's a workaround which involves editing the nav mesh.

**Comment by robotboy655** [comment]
It's added, but as I said, it doesn't do much, the problem in that place is the shit generated navmesh, not turn speed.
