### ISSUE TITLE
Add workshop support for individual saves, dupes, and demos

### ISSUE THREAD

**Issue by andrewmh2013** [Facepunch/garrysmod-requests#33]
Add a "Subscribed" category for ingame saves, dupes, and demos.

Currently there's no way to access specific dupes, saves, and demos from the workshop. Subscribing to one of these items doesn't do anything. Any content outside the "most popular" list is inaccessible.

Consider that the first thirty pages of "recently uploaded" dupes make up less than 0.000041 percent of all dupes on the workshop. Tens of thousands of other dupes are lying stagnant and simply wasting space on the workshop because they can't be spawned.

(This is a remake of):
https://github.com/Facepunch/garrysmod-issues/issues/51

**Comment by Radfordhound** [comment]
On this day in history... [I made a thing](https://github.com/Radfordhound/GMod-Dupe-Downloader/). :)

**Comment by Ruuttu** [comment]
Just chiming in here. 
Yeah, I believe this really needs to get done. 
KTHXBYE XOXO

**Comment by robotboy655** [comment]
Dev branch can now list your subscribed dupes,etc and they are no longer automatically unsubscribed.

This still won't download and make them be available in offline though ( yet? )
