### ISSUE TITLE
Flashlight creation control

### ISSUE THREAD

**Issue by Kogitsune** [Facepunch/garrysmod-requests#330]
Currently, without doing something dirty on the server and replacing the client's flashlight with an env_projected_texture, there's no way to adjust the fov, color, or texture. This leads to a laggy, sloppy flashlight that lags behind the player's movement. In flashlighteffect.ccp, lines 323 to 355 show how the engine handles the projected part of the player's flashlight.

Ideally, there would be two hooks:

GM:CreateFlashlight( Player, FlashlightState_t )
GM:UpdateFlashlightState( Player, FlashlightState_t )

Where FlashlightState_t is defined in imaterialsystem.h on line 404.

Which would offer the same functionality, but would catch UpdateFlashlightState instead of CreateFlashlight.

Finally, Player:ForceFlashlightUpdate( ), which would do as the name states - force the player's flashlight to update if it exists.

**Comment by Kogitsune** [comment]
Please!

**Comment by willox** [comment]
http://wiki.garrysmod.com/page/Category:ProjectedTexture will pretty much solve this
