### ISSUE TITLE
Add PathFollower:GetPoints() and PathFollower:GetPointPosition(number)

### ISSUE THREAD

**Issue by Nak2** [Facepunch/garrysmod-requests#336]
NextBot don't support running on bots, therefor I'm trying to make an entity to pass the path to the bot for it to follow.
However there are no functions to get the position for the points on the path (As in curves) and bots tent to get stuck unless I pass a large table (That usual tent to break entity:GetPos() for some strange reason).

**Comment by bizzclaw** [comment]
There's already a thread about this here
https://github.com/Facepunch/garrysmod-requests/issues/348

**Comment by robotboy655** [comment]
Pretty sure this is what the newly added segment functions do.
