### ISSUE TITLE
Missing HL1: Source NPCs

### ISSUE THREAD

**Issue by disseminate** [Facepunch/garrysmod-requests#338]
A couple missing NPCs that would be nice to play with:
- monster_apache
- monster_osprey
- monster_turret
- monster_miniturret
- monster_sentry

Obviously hardly a priority.

**Comment by Kefta** [comment]
monster_sentry, monster_turret, and monster_miniturret were added to the dev branch. Here're the entities still missing:
- monster_apache
- monster_osprey
- speaker
- weaponbox

**Comment by robotboy655** [comment]
What map and place exactly can speaker entity be heard/is used?

**Comment by Kefta** [comment]
``c2a5e`` has three.

**Comment by Kefta** [comment]
These have all been added.
