### ISSUE TITLE
Add some joystick bindings?

### ISSUE THREAD

**Issue by robotboy655** [Facepunch/garrysmod-requests#342]
A simple amount of axies or which axies the joystick has, and a function to return the "value" of an axis would be very useful.

**Comment by CapsAdmin** [comment]
I want to make some thirdperson camera with joystick support and at the moment I have to run "joystick 0" and "joy_advanced 0" when I enable the camera cause soruce engine overrides CreateMove when you have the joystick connected. Functions like `input.IsButtonDown(KEY_XBUTTON_STICK2)` work fine even if joystick is 0 though.

But then I have no way of knowing where the x y position of the thumbsticks. Something like `local x, y = input.GetStickPos(KEY_XSTICK1)` would be enough I think. (not knowing anything about the api though)

@jombo23 The joystick module for wiremod uses the windows api for some reason. This is not cross platform friendly and it's reinventing the wheel. It should be more simple to use source engine's joystick api.

Maybe it was maybe made before source engine had controller support?

**Comment by robotboy655** [comment]
Added input.GetAnalogValue( AnalogAxis )
Added ANALOG_* enums

ANALOG_MOUSE_X/Y/WHEEL for mouse
ANALOG_JOY_X/Y/Z/R/V/U for controllers
+/- 32768

ANALOG_JOY_R and U may be flipped on linux, needs testing
