### ISSUE TITLE
Get a panel Z Pos

### ISSUE THREAD

**Issue by KrakenZ** [Facepunch/garrysmod-requests#346]
There's actually no way of getting a Panel:GetZPos().
This would allow to handle panels drawing order.

I know there is MoveToAfter and MoveToBefore functions, but they are quite expensive and GetZPos would be more useful.

**Comment by mcd1992** [comment]
I actually had a use for this a couple of months ago, ended up just setting the pos to -999 which works but doesn't feel right. Would rather be able to do GetZPos - 1.
