### ISSUE TITLE
Can we get a function that returns the sum of all networked edicts?

### ISSUE THREAD

**Issue by TeddiO** [Facepunch/garrysmod-requests#353]
At the moment there is no easy way to get all networked edicts accurately, as ents.GetAll() returns all entities, regardless of whether or not they're networked. It'd be handy as to keep track and prevent specific server crashes.

I guess a function for each state (client / server) wouldn't go amiss either for non-networked ents. 

(Another edict raise would be totally awesome as well, but you might have to check a few tech limitations with that :v)

**Comment by mcd1992** [comment]
I don't have a use for this but it should be easily implementable. Looking in mp/src/game/server/entitylist.h shows that CGlobalEntityList::m_iNumEdicts keeps track of the number of networked entities.

**Comment by jcwik223** [comment]
This would be very useful to accurately track the entity count for ents.GetAll returning null from hitting the ent limit.

**Comment by robotboy655** [comment]
Added ents.GetEdictCount()
