### ISSUE TITLE
A method of tracking per-addon errors?

### ISSUE THREAD

**Issue by Lexicality** [Facepunch/garrysmod-requests#355]
Now that errors.garrysmod.com has completely bitten the dust can we have some way of somehow finding out about our errors?
Even if it's just entering an addon ID and a URL for errors to be forwarded to.

**Comment by Jvs34** [comment]
I've looked at getsentry.com, and apparently garry uses it for rust, the service also allows you to setup a custom [server](https://github.com/getsentry/sentry) so we can either have a default one hosted by facepunch ( that we still have to specifically make an account on to begin the tracking ) or a custom one if we want to.

Ideally the API link (used by the error reporter ) would be stored in the json of the addon.

**Comment by Jvs34** [comment]
I just noticed it does not come with a c++ client unfortunately, but the error is sent as json, so in theory shouldn't be too hard to make.

**Comment by robotboy655** [comment]
I feel like the best we can do right now is https://github.com/Facepunch/garrysmod-requests/issues/149, instead of making a way of ddosing a server with errors.

**Comment by robotboy655** [comment]
Not to mention Sentry is not free.

**Comment by kojiDev** [comment]
@robotboy655 it is free, with some limitation, great tool though

**Comment by robotboy655** [comment]
https://wiki.facepunch.com/gmod/GM:OnLuaError is now available to addons, so it should fulfill this request.
