### ISSUE TITLE
L4D model animations

### ISSUE THREAD

**Issue by disseminate** [Facepunch/garrysmod-requests#356]
L4D models can partially use animations if the entity has IK enabled.

![Here's a screenshot of the hunter's running animation.](https://cloud.githubusercontent.com/assets/3835600/4281064/6c6776ae-3d39-11e4-9024-d4cdb21ab477.jpg)

The legs animate but the rest of the model doesn't. If this could get looked at, I'd love to finally work with L4D models properly for NPCs and players.

In garrysmod-requests because it's more of a feature request than anything.

**Comment by robotboy655** [comment]
This was solved in https://github.com/Facepunch/garrysmod-issues/issues/5218
