### ISSUE TITLE
Ability to disable "Failed to load sound" notification in console

### ISSUE THREAD

**Issue by Mista-Tea** [Facepunch/garrysmod-requests#358]
I did a brief search to see if this had been requested before but I didn't see it anywhere.

May we please have the ability to remove the missing sound notification from spamming our consoles? E.g.:

``` lua_run_cl surface.PlaySound( "I am never going to have this sound file, ever.wav" ) ```

``` Failed to load sound "i am never going to have this sound file, ever.wav", file probably missing from disk/repository ```

Something like a convar ``` cl_missingsounds <1-show/0-hide> ```.

Why should this be added? 

Go onto any server where you happen to be missing a sound that plays dozens of times a second (like via E2, PAC3, ACF, etc) and you'll be unable to read anything coming through console. Are you trying to moderate a situation? Not possible -- console spam from sounds. Trying to grab someone's SteamID after they disconnected? Nope -- the message has already left the console buffer because of sound spam.

I realize the typical reply is "just download the addon", but filling the client with unnecessary clutter hardly solves the issue. Especially when it's someone playing a sound that only they have and no one else can download.

**Comment by robotboy655** [comment]
#269
