### ISSUE TITLE
Extra Navmesh Bindings

### ISSUE THREAD

**Issue by mcd1992** [Facepunch/garrysmod-requests#362]
There are a few navmesh bindings that need to be fixed and added. For starters some of the current navmesh bindings return invalid cnavareas. So there should be a CNavArea:IsValid implemented or the current navmesh functions need to return nil instead of invalid navareas.

Some CNavArea bindings that would be useful if implemented are:
**GetAttributes()**
> Returns the attributes of CNavMesh.

**GetAdjacentCount( NavDirType )**
> Returns the number of adjacent navareas to self navarea in Direction.

**GetAdjacentArea( NavDirType, Number )**
> Returns the Number-th navarea in the given direction relative to self navarea. (Starts at 0 and ends at GetAdjacentCount()-1)

**GetRandomAdjacentArea( NavDirType )**
> Returns a random navarea connected to the Direction side of self. (Nil if no adjacent areas in Direction.)

**CollectAdjacentAreas()**
> Returns a table of CNavAreas that are adjacent/connected to the self navarea. (Returns an empty table if no adjacent navareas.) [This should also add one way connections]

**IsConnected( CNavArea, NavDirType )**
> Returns true if self navarea is connected to the first argument navarea in Direction. False otherwise.

**GetPlayerCount( TeamID )**
> Return the number of players on self navmesh.

**ComputeGroundHeightChange( CNavArea )**
> Compute change in actual ground height from this area to given area

**ComputeDirection( Vector )**
> Returns the direction of the side that faces Vector

**IsOverlappingArea( CNavArea )**
> Returns true if self overlaps CNavArea's 2D bounds.

And some extra bindings to the CNavMesh would be welcome as well:
**navmesh.GetAllNavAreas()**
> Returns a table of every navarea on the map.

**navmesh.GetNearestNavArea( Vector pos, Bool anyZ = false, Float maxDist = 10000.0f, Bool checkLOS = false, Bool checkGround = true, Int team = TEAM_ANY )**
> Return the nearest navarea with the given arguments or nil.

These are just some of the bindings I've had to implement myself as they we're needed in my gamemode. I've also encountered a few situations on the forums where other people could benefit from the navmesh. So if possible I'd also like to get bindings for the other CNavArea methods and the CNavMesh methods for getting information and maybe even the methods that modify the navmesh.

**Comment by robotboy655** [comment]
I will add those bindings, but any bugs should be reported on garrysmod-issues with proper explanations.

**Comment by mcd1992** [comment]
I'll be sure to test it when its on the dev branch then, thanks!
