### ISSUE TITLE
Controlling the direction a Nextbot faces when it moves. 

### ISSUE THREAD

**Issue by bizzclaw** [Facepunch/garrysmod-requests#363]
Pretty self explanatory in the title, I've been working on some medieval npcs for some dynamic swordplay, but it's been difficult when I can't make them walk backwards or strafe. It would also allow NPCs to take cover better; It would be awesome if they could strafe in and out of cover, ect.

**Comment by robotboy655** [comment]
http://wiki.garrysmod.com/page/CLuaLocomotion/FaceTowards
