### ISSUE TITLE
Add SetUnderlineFont for RichText

### ISSUE THREAD

**Issue by Guillaume57** [Facepunch/garrysmod-requests#365]
Hello, when I try to add a clickable text in a RichText, the clickable text is set to a very small font (compared to the one I use for the rest of the text), I would like to be able to change this font, and I believe that the function needed to do this, is called "SetUnderlineFont" (see: http://hlssmod.net/he_code/public/vgui_controls/RichText.h )

**Comment by robotboy655** [comment]
This was done.
https://wiki.facepunch.com/gmod/Panel:SetUnderlineFont
