### ISSUE TITLE
Call PlayerSwitchWeapon if a player gets stripped

### ISSUE THREAD

**Issue by UselessGhost** [Facepunch/garrysmod-requests#366]
While the player isn't __technically__ switching their weapon, it'd be nice if this could be fired when a player gets stripped.

**Comment by robotboy655** [comment]
This won't happen, since the main purpose of the hook is to prevent/allow weapon switches, and as you noticed, the player isn't techincally switching their weapon.

This is also fairly easy to implement with Lua using OnEntityRemoved hook.
