### ISSUE TITLE
VMatrix:Unpack () and VMatrix:SetUnpacked ()

### ISSUE THREAD

**Issue by notcake** [Facepunch/garrysmod-requests#369]
or something similar, because this is much faster than calling VMatrix:GetField / SetField 16 times.

``` lua
m11, m12, m13, m14, m21, m22, m23, m24, m31, m32, m33, m34, m41, m42, m43, m44 = VMatrix:Unpack ()
VMatrix:SetUnpacked (m11, m12, m13, m14, m21, m22, m23, m24, m31, m32, m33, m34, m41, m42, m43, m44)
```

The same thing could be done for Vectors and Angles (could be useful for speeding up some addons, like PAC)

**Comment by Kefta** [comment]
Having methods for getting and setting rows/columns as tables, vectors, and unpacked values implemented in C would also be significantly more efficient from my tests.

**Comment by CornerPin** [comment]
[VMatrix:ToTable()](http://wiki.garrysmod.com/page/VMatrix/ToTable)
[Matrix(table data)](http://wiki.garrysmod.com/page/Global/Matrix)

**Comment by Kefta** [comment]
That does not retrieve nor set specific rows/columns.

**Comment by thegrb93** [comment]
It also does nested tables. Very slow

**Comment by robotboy655** [comment]
https://wiki.facepunch.com/gmod/VMatrix:Unpack
https://wiki.facepunch.com/gmod/VMatrix:SetUnpacked
https://github.com/Facepunch/garrysmod-requests/issues/515
