### ISSUE TITLE
Lua binding for INetChannel:IsTimedOut

### ISSUE THREAD

**Issue by zerfgog** [Facepunch/garrysmod-requests#371]
See http://facepunch.com/showthread.php?t=1374457&p=46379126&viewfull=1#post46379126
and http://facepunch.com/showthread.php?t=1434416&p=46376332&viewfull=1#post46376332

**Comment by xaviergmail** [comment]
Doesn't seem like a very hard thing to implement, I would like to see this too

**Comment by robotboy655** [comment]
We are not adding anything until the new update is out.

**Comment by MattJeanes** [comment]
Fair enough, but I would love to see this implemented some day.

**Comment by mcd1992** [comment]
+1

**Comment by zerfgog** [comment]
+1

**Comment by MattJeanes** [comment]
Has a clientside version been added now? Or is that a decline

**Comment by robotboy655** [comment]
INetChannel:IsTimedOut only exists on the server.

**Comment by MattJeanes** [comment]
Ah okay, that sucks but fair enough
