### ISSUE TITLE
kickid with newlines

### ISSUE THREAD

**Issue by VigiFyre** [Facepunch/garrysmod-requests#372]
A function that will kick players by their UserID with reason with newline support.
Needed to kick players, when they haven't loaded yet, so there is no entity yet.
I don't know if CheckPassword has newline support, but it doesn't matter, because i need to make asynchronous call to database to get player's bans.

**Comment by willox** [comment]
http://wiki.garrysmod.com/page/game/KickID

**Comment by Noiwex** [comment]
👏👏👏👏👏👏👏👏👏👏👏👏
