### ISSUE TITLE
A hook when I/O events are called in a map

### ISSUE THREAD

**Issue by SuperHighVoltage** [Facepunch/garrysmod-requests#374]
Something like ENTITY:AcceptInput but called when any entity gets an input called on it.
I would like to use use it to debug I/O in maps but other uses could be to deny certain events or modify them with return values or something

**Comment by robotboy655** [comment]
- Added GM:AcceptInput(ent, input, activator, caller, value), equivalent behavior of ENTITY:AcceptInput
