### ISSUE TITLE
Increase MAX_NODES limit

### ISSUE THREAD

**Issue by leiftiger** [Facepunch/garrysmod-requests#38]
I've come across an issue with a large map (gm_apocalypse) and wondered why certain parts of the map weren't noded. After trying to add additional nodes myself, I noticed that the map had actually reached the node count limit of 1500 AI nodes which would make the graph ignore any additional nodes exceeding that count.

And as I couldn't find any real reason for that arbitrary node limit, I'm suggesting that the define in ai_network.h could be increased to at least 3000 nodes, which should be more than enough for an optimized large map.

**Comment by DanilaFoxPro** [comment]
New Garry's Mod update will increase node limit to 4096.
