### ISSUE TITLE
Make include() return a value from the file it has executed.

### ISSUE THREAD

**Issue by Pecius** [Facepunch/garrysmod-requests#393]
Since the current include function hardly includes anything to the file where it's ran, 
it would be a nice addition if it allowed you to transfer the contents of an included file via return value. Instead of having to retrieve it from the global table.

**Comment by wiox** [comment]
Fix require so it does this as it should too please

**Comment by neico** [comment]
Well we could go ahead and add RunString and RunStringEx to that list as well while we're at it.

I don't really see why either functions mentioned here don't return anything at all, I mean even a boolean for successful execution would help already. (guess garry never thought much about it when he made them...)

**Comment by wiox** [comment]
require is supposed to return the value returned by the script it executes and is used over the module() function in most libraries written for Lua. Not having it is a cripple.

**Comment by thegrb93** [comment]
Yes please, I had to replace all of the "require" in an external library I wanted to use with my own module loader (using CompileFile) because gmod require doesn't return anything.

**Comment by mcd1992** [comment]
:+1:
