### ISSUE TITLE
Make the viewmodel_fov no longer a cheat cvar.

### ISSUE THREAD

**Issue by LordCasco** [Facepunch/garrysmod-requests#395]
Why a simple command to change your weapon fov is a cheat command at the first place?

**Comment by LordCasco** [comment]
Could you at least provide a reason for the "wont add" label please?

**Comment by robotboy655** [comment]
There's no point in it because it only works for default HL2 weapons and not SWEPs. besides, you will have to see the view model as the weapon author designed it to look like.

**Comment by Kefta** [comment]
Please complete this. Even if it doesn't affect SWEPs, SWEP owners can implement it in their weapons without adding a new convar. Also, there should be a convar to affect engine weapon FOV.

**Comment by robotboy655** [comment]
It is done.
