### ISSUE TITLE
Update Awesomium

### ISSUE THREAD

**Issue by wyozi** [Facepunch/garrysmod-requests#398]
It is slowly getting boring having to work around things like lack of ```display: flex``` or even the webkit prefixed version of it.

**Comment by Bo98** [comment]
There's an issue open at Facepunch/garrysmod-issues#1726 though I don't know whether it would be better to leave this open here at garrysmod-requests or to go with that one.

Ideally Awesomium would be updated before the next update is out but 1.7.5 seems to not be out for OS X yet.

**Comment by jgkamat** [comment]
Any news on when this could possibly be pushed to the dev branch?

**Comment by smithy285** [comment]
+1 Support

**Comment by mcd1992** [comment]
+1 Would love to get CSS3 keyframe bugfixes from the newer awesomium

**Comment by Bo98** [comment]
Probably should note here that 1.7.5 is out for OS X as of a few weeks ago.

**Comment by robotboy655** [comment]
We need to just punch @UnderscoreKilburn to do it.

**Comment by YourStalker** [comment]
^agrreed. Giving support to this as well.

**Comment by Noiwex** [comment]
Can't robotboy655 do it?

**Comment by YourStalker** [comment]
Probably but you have to remember that Rubat has many other things to do as well and it isn't a small task to switch to the newer version probably. It also seems like Kilburn is the one who gets involved a lot more with the non-lua stuff.

**Comment by Jitterclick** [comment]
Does Awesonuim support mac HTML 5 flash playback youtube videos in cinema mode? There is seem to be a bug where Cinema mode doesn't work on Mac. Don't say "Mac Sucks" we all don't have the time to spend all day and play on a PC Desktop (No offense not trying to start a war over OS's, yes windows is superior. I know don't need to be told again.})

**Comment by WinterPhoenix96** [comment]
Well, if you go into Cinema and open the Web Browser and then put in [http://www.quirksmode.org/html5/tests/video.html](this link), you can determine what's supported as far as HTML5 videos on Mac. Also, Flash Player is different from HTML5 and acts differently, and Mac doesn't like to work with it very well, especially in embedded solutions like using Awesomium in Cinema.

**Comment by meepdarknessmeep** [comment]
or just don't use mac

**Comment by thegrb93** [comment]
@meepdarknessmeep Switching to windows is a good temporary solution since it will take some time to fix these issues, but stop making it sound like the only solution.

**Comment by meepdarknessmeep** [comment]
using mac is bad

**Comment by WinterPhoenix96** [comment]
I'm sure that circlejerking that it's bad will improve the situation.

**Comment by meepdarknessmeep** [comment]
im sure that asking something that can be found publically online will also improve the situation
also it will help people not use the worse operating system of our time

**Comment by Noiwex** [comment]
Vinh'll fix this

**Comment by samuelmaddock** [comment]
Cinema YouTube videos are currently being forced to 360p or lower due to Awesomium being outdated and not supporting a few video codecs that YouTube uses. It would be much appreciated if Awesomium were to be updated.

**Comment by WinterPhoenix96** [comment]
An alternative should an updated version of Awesomium not fix the Cinema issue would be to completely replace it, as suggested in https://github.com/Facepunch/garrysmod-requests/issues/531, however it may take considerable more effort to do.

**Comment by neico** [comment]
Using steam's webhelper wouldn't be that much more effort, if anything it should make it easier as you don't have to bother with the 3rd party content, compiling and such.

At this point it simply makes more sense than trying to squeeze Awesomium in any more.

**Comment by samuelmaddock** [comment]
Quoting for relevance.
> I have updated Awesomium to 1.7.5.1 on Windows and Linux, OS X does not compile yet, I will need to figure out the linking error later this week.
> On linux, you might need to rename libawesomium.so.5.0 to libawesomium.so.2 and libawesomium.so.0, I have no idea what's up with the .2 and .0 in GMod and 5.0 in Awesomium.

https://facepunch.com/showthread.php?t=1485127&p=48780898&viewfull=1#post48780898

**Comment by HDG-MrDeeJay** [comment]
@Neico re steams web helper: Don't rely on that shit. Steam's browser is trash, slow, and from what I recall, their "Back" button reads error page redirects as whole new pages in your history, meaning going back through a submitted form is impossible.

**Comment by samuelmaddock** [comment]
@robotboy655 @UnderscoreKilburn The update is appreciated, however, it hasn't addressed any of the issues brought up in this thread—missing/outdated browser features. Is there still a possibility of looking into an Awesomium replacement as per #531?

**Comment by WinterPhoenix96** [comment]
Posted a reply to the Next Update Thread pertaining to this issue, that I've linked here: https://github.com/Facepunch/garrysmod-requests/issues/531#issuecomment-149788522
