### ISSUE TITLE
Allow cancel of ingame menu gui display.

### ISSUE THREAD

**Issue by Yuri6037** [Facepunch/garrysmod-requests#399]
Hello,

That's the first time I'm posting here because I'd like to cancel the display of ingame menu gui when I press Escape key.

Indead, it would be usefull to cancel ingame menu gui display when you just wan't to exit you custom chat for example.

**Comment by robotboy655** [comment]
That's how that custom content was coded, this does not belong here.

**Comment by Yuri6037** [comment]
Why ?

You can make Guis that requires to close them without showing the ingame menu gui, don't you ?

**Comment by robotboy655** [comment]
That needs to be done by addon author, not us.
