### ISSUE TITLE
Npc anims & weapons

### ISSUE THREAD

**Issue by Combine900** [Facepunch/garrysmod-requests#400]
Weapons:
Well npcs still cant use the HL2 rpg and HL2 357 mag and some also cant use the alyx gun (may this one is just designed for alyx), i know this isnt very important but it whould be nice to see them working for the npcs the crossbow also works since 2012

Animations:
i can remind at gmod 10 dont know what files changed but the npcs in garrysmod 10 like a "combine elite" could use a rpg also a pistol etc with working animations. (they just reload the pistol like an SMG) its garrysmod 13 now may 14 soon and they cant,  that make me feel sad is it possible to make them use the weapons with working animations again?

!Close this issue if it already exist anywhere!

**Comment by UnknowGuy200** [comment]
The rpg is working for npcs, Source switches them over to another kind of AI and will only fire in certain areas. The 357 isn't coded for most npcs and the alyxgun is only meant for Alyx.

**Comment by robotboy655** [comment]
There were many changes to NPC weapon support, the 357 definitely works with NPCs that have pistol animations.

As for NPC animation, there's nothing we can do about it, NPCs get whatever animations Valve gave them.
