### ISSUE TITLE
Better Constraints

### ISSUE THREAD

**Issue by JoeySkylynx** [Facepunch/garrysmod-requests#403]
Not exactly sure how possible this is, but with the current set of tools available in Garry's Mod, users are having a hard time trying to combat server latency issues. The greatest issue at this very moment is collisions between props and the lack of methods to deal with it. For the moment, builders have tried to take shots at this issue, and have developed methods of parenting props to entities like Bouncy Balls in order to retain physical qualities on props, but remove collisions and merge the contraption into one contraption. This has been used in ACF, Privateer, and several other combat gamemodes in order to deal with moving contraptions, but it's showing its age. 

I would like to make a formal request for the inclusion of something like Polyweld into vanilla Garry's Mod, that directly replaces the current constraints system(Weld, Ballsocket, Axis, ect) and allows users to weld props together, but instead of retaining say two props, it creates one prop with merged hitboxes and meshs. This would deal with a majority of the issues relating to collision lag. 

As I have said before, I am not exactly sure on how possible this is, but I hope it's possible enough to make something worthwhile. Thank you for reading!

**Comment by robotboy655** [comment]
We can't change anything about the physics of the game because we do not have source code for it.
