### ISSUE TITLE
Add server command to disable addons

### ISSUE THREAD

**Issue by hanm13** [Facepunch/garrysmod-requests#406]
I need custom server cfg command or srcd run command to disable addon for custom server
like -disable addon "bla bla" 
or sv_disableaddon "bla bla "
bla bla = the name of the directory from addons directory (garrysmod/addons) .
Thank you.

**Comment by robotboy655** [comment]
Just don't put in the addon?

**Comment by hanm13** [comment]
I have gamemode with Multi-Server System and I need to disable addon for one server and I cant...
I use the addon in server 1 and I dont want in server 2.

**Comment by neico** [comment]
What exactly do you mean by multi server system, I can think of some where this isn't a real issue...

**Comment by hanm13** [comment]
I have two servers are run from one directory, and for one server I want to disable addon.

Hanm13

‫ב-2 בפבר׳ 2015, בשעה 19:22, ‏‏Neico ‏<notifications@github.com> כתב/ה:‬

**Comment by neico** [comment]
Why not make 2 servers with 2 folders and symlink shared content, I've been doing it all along, windows and linux (they both support symlinks~)

**Comment by brandonsturgeon** [comment]
Is this close-able?
