### ISSUE TITLE
CBasePlayer::SetWaterJumpTime & CBasePlayer::GetWaterJumpTime bindings

### ISSUE THREAD

**Issue by wiox** [Facepunch/garrysmod-requests#408]
The property these functions utilise is used for movement. Chucking this in the game just opens that all up for more modification.

Gott's be shared.

**Comment by Noiwex** [comment]
Implemented?

**Comment by robotboy655** [comment]
No. @wiox no longer needs this. Let me know if you have any use for it.

**Comment by Noiwex** [comment]
I think it's for water bhop, would be cool. Let alone that all CBasePlayer
methods could be implemented in Lua.

**Comment by robotboy655** [comment]
It my tests it doesn't change anything, which is why I didn't add it for sake of having it.
