### ISSUE TITLE
Panel:PaintAt calls the Think function on given panel 3 times in the same frame, instead of once.

### ISSUE THREAD

**Issue by CGNick** [Facepunch/garrysmod-requests#409]
Here is an example code:

---------

local frame = vgui.Create("DFrame")
frame:SetSize( 300, 200 )
frame:MakePopup()
frame.Paint = function( s, w, h )
	s.button:SetPaintedManually(false)
	s.button:PaintAt( 0, -10, w, h )
	s.button:SetPaintedManually(true)
end

local d = CurTime()

frame.button = vgui.Create("DButton", frame)
frame.button:SetPaintedManually( true )
frame.button:SetSize( 100, 50 )
frame.button.Think = function( s )
	print( CurTime() - d )
	d = CurTime()
end

---------

If I use PaintManual instead of PaintAt, the delta print will be regular, however currently it spits out a number with 2 more prints after it being zeroes, meaning it's being called 2 extra times for some reason. This only happens for the Think function too, if you do the print check in Paint, it will print regularly.

**Comment by wiox** [comment]
PaintAt calls Think before and after drawing the panel, this is expected behvaiour.

```
PaintAt()
    pos = newpos
    Think(); Paint()
    pos = oldpos
    Think
```

This is so that if any position-sensitive code runs in Think that the rendering relies on, it won't fail.
