### ISSUE TITLE
Let CreateConVar take a numeric argument for the default value.

### ISSUE THREAD

**Issue by wiox** [Facepunch/garrysmod-requests#411]
```lua
CreateConVar( "my_convar", 1/60, ... -- What I would like
CreateConVar( "my_convar", tostring(1/60), -- What I have
CreateConVar( "my_convar", "0.01666666667", -- What is terrible
```

This should really be expected behaviour because Lua - by default - is not type-strict when it comes to strings and numbers.

**Comment by Jvs34** [comment]
Also the default value isn't even set as actual default value for the convar, it's only set as the initial value, which fucks up http://wiki.garrysmod.com/page/ConVar/GetDefault

**Comment by wiox** [comment]
Turns out this actually works.

![](https://paulstensondotcom3.files.wordpress.com/2014/07/oops.gif)

**Comment by Jvs34** [comment]
Goddamnit willox

**Comment by robotboy655** [comment]
@Jvs34, I have a fix for the default value stuff, but I think I won't commit it for now.
