### ISSUE TITLE
Lua binding for BeamRingPoint

### ISSUE THREAD

**Issue by UselessGhost** [Facepunch/garrysmod-requests#412]
Self explanatory. Sourcemod uses this extensively and it's curious that Gmod has no equivalent. It's also used in the combine ball explosion effect.

**Comment by homonovus** [comment]
we gonna get back to this any time soon?

**Comment by robotboy655** [comment]
Really not sure how best to bind this with so many arguments, currently it is like this:

```
util.BeamRingPoint( centerPos, lifeTime, startRadius, endRadius, 
					width, amplitude, colorObj, extraTable )
```
extraTable is optional and has the following keys: (=default)
* speed = 0 -- Doesn't seem to do shit
* spread = 0 -- same
* delay = 0
* flags = 8 (Fadeout = 8, FadeIn = 4,  NoFade = 0 )
* framerate = 0
* material = "sprites/lgtning"

**Comment by Kefta** [comment]
I think all the arguments should be in a table. Something like
```Lua
BeamRingData
{
   CenterPos,
   Time,
   StartRadius,
   EndRadius,
   Width,
   Amplitude,
   Color,
   Speed = 0,
   Spread = 0,
   Delay = 0,
   Flags = 8,
   Framerate = 0,
   Material = "sprites/lgtning"
}
```

Problem is that GLua currently does no type errors for table entries (util.Trace* table arg for example) so everything would technically have to have a "default" value. Not sure if this is something you want to start enforcing now or continue leaving as undefined behaviour.

**Comment by Kefta** [comment]
The table is essentially just a BeamInfo_t.

**Comment by robotboy655** [comment]
Yeah that's the only reason I didn't make them all in the table, and no it is not the same as BeamInfo_t, this is tempent stuff, although most of it is fed to BeamInfo_t somewhere.

**Comment by Kefta** [comment]
Maybe we should have an ``effect`` library for this if more are gonna be added (I requested BubbleTrail a while ago.

**Comment by robotboy655** [comment]
Seems logical for effects to be in the effects library.
```
Moved util.BeamRingPoint to effects library
Added effects.BubbleTrail(mins,maxs, count, height, speed=0, delay=0) and effects.Bubbles( same args )
```

**Comment by Kefta** [comment]
Forgot that library even existed. Thanks.
