### ISSUE TITLE
Error code for FastDL HTTP errors

### ISSUE THREAD

**Issue by DarthTealc** [Facepunch/garrysmod-requests#415]
When a download fails from FastDL it is displayed in console listing the URL that failed and "[HTTP Error]". That isn't very helpful because the error could be a range of things. 
Could the HTTP error code be added to the error message to help with debugging? For example "[HTTP Error: 404]".

**Comment by DarthTealc** [comment]
Just confirming this is still the case with today's update (2015.03.05)
Download errors start with "HTTP ERROR downloading".

**Comment by robotboy655** [comment]
There's no need to confirm issues that were not looked into.

**Comment by robotboy655** [comment]
I added some form of error reports in next Dev branch update, let me know if it works/shows anything useful.

It seems to be impossible to show the actual HTTP error though.

**Comment by robotboy655** [comment]
HTTP ERROR 8 downloading http://94.23.170.2:20080/fastdl/models/rubat.mdl.bz2
HTTP ERROR 8 downloading http://94.23.170.2:20080/fastdl/models/rubat.mdl

```
HTTP_ERROR_NONE = 0
HTTP_ERROR_ZERO_LENGTH_FILE = 1
HTTP_ERROR_CONNECTION_CLOSED = 2
HTTP_ERROR_INVALID_URL = 3,		///< InternetCrackUrl failed
HTTP_ERROR_INVALID_PROTOCOL = 4	///< URL didn't start with http:// or https://
HTTP_ERROR_CANT_BIND_SOCKET = 5
HTTP_ERROR_CANT_CONNECT = 6
HTTP_ERROR_NO_HEADERS = 7			///< Cannot read HTTP headers
HTTP_ERROR_FILE_NONEXISTENT = 8
```

This is the best Valve HTTP lib can do
