### ISSUE TITLE
CanTool should provide click type

### ISSUE THREAD

**Issue by NeatNit** [Facepunch/garrysmod-requests#418]
Currently CanTool only gives the following information:
The player
The trace
The tool trying to be used

However, many tools have different functions, such as: when the slider tool is right-clicked, it does an action practically equivalent to two left clicks, and more importantly - one of the entities involved in this action cannot be trivially acquired from the trace.

The bare minimum added argument I request to be added is the type: reload, left, or right click. IMHO this should be in an enum, but that doesn't matter.

The stage the tool is in might also be useful for some: http://wiki.garrysmod.com/page/TOOL/SetStage

In addition to that, any other information that can help and is tricky to get, such as stored objects, wouldn't hurt. http://wiki.garrysmod.com/page/TOOL/SetObject

Thanks.

**Comment by robotboy655** [comment]
You can easily figure out which one it is by using TOOL:GetStage and TOOL:GetOperation ( using ply:GetWeapon("gmod_tool"):GetToolObject() )

**Comment by NeatNit** [comment]
Okay, here is the results of three actions:
1. Left-click with remover tool
2. Right-click with remover tool
3. Reload with remover tool

![Image of results](http://i.gyazo.com/190873cba591142cfb36d7bb05f808a8.png)

Please tell me how to differentiate.

**Comment by robotboy655** [comment]
Fair enough, I will think about adding this. Not the GetStage or GetOperation though, you can do that already.

**Comment by NeatNit** [comment]
Thanks!

My thinking behind adding the stage to the hook is just for easier access. I mean, you can get the trace just as easily using Player:GetEyeTrace() but it still makes sense to add it to the hook - because it's relevant.

But since they're less commonly relevant and easy enough to acquire through other means, I suppose you're right about not including them.

**Comment by mcd1992** [comment]
As a temporary workaround, I haven't tested this though; try using [Player:KeyDown](http://wiki.garrysmod.com/page/Player/KeyDown) in the CanTool hook?

**Comment by robotboy655** [comment]
Added the toolObj and the button, but due to stuff like this:

https://github.com/Facepunch/garrysmod/blob/be251723824643351cb88a969818425d1ddf42b3/garrysmod/gamemodes/sandbox/entities/weapons/gmod_tool/stools/slider.lua#L106

Some addon tools may not call the hook with the new parameters, nothing I can do about it.

**Comment by thegrb93** [comment]
Very useful 6 years later
