### ISSUE TITLE
Add ability for contributors to update workshop addons

### ISSUE THREAD

**Issue by MattJeanes** [Facepunch/garrysmod-requests#419]
I'm not sure if this is something that is dealt with on this end or steam's end, but it would be really nice for contributors to be able to commit to the addon, much like on GitHub itself. If you were worried about contributors being malicious or something, maybe have it as a per-addon option off by default that can be enabled by the addon owner?

**Comment by wiox** [comment]
I don't think a per-addon option is possible unless Valve add it (actually the whole thing is probably all down to Valve).

Either way, with no option to disable this possible I'm against it. I don't want contributors to my addons changing them.

**Comment by MattJeanes** [comment]
Yes this is unfortunately the main issue with this, there needs to be an option because some won't want this behaviour.

**Comment by robotboy655** [comment]
As said above, it is not possible to do with how Workshop is currently set up.
