### ISSUE TITLE
[Dev] Change srcds title 

### ISSUE THREAD

**Issue by wyozi** [Facepunch/garrysmod-requests#420]
![](http://i.imgur.com/6XRzK3C.png)

One of those is the SRCDS server and one of them is the gmod client. I keep clicking the srcds when I want to open the client. Remembering is hard.

**Comment by mcd1992** [comment]
I agree, I've had to use resedit to change the icon so I can tell the difference. Putting SRCDS in the title and a different icon would be wonderful.

**Comment by Authorjames** [comment]
The SRCDS title will change as the server hostname changes. Changing the title to not the hostname could easily cause issues with some shitty server managers.

**Comment by mcd1992** [comment]
I actually never knew that it read from the hostname var, thanks for that. Still getting a different icon wouldn't hurt and would make alt+tab finding it easier.

**Comment by Authorjames** [comment]
Something like this, maybe? http://i.imgur.com/hjV46Eq.png

**Comment by mcd1992** [comment]
Ah it was you that posted that icon in the Next Update thread. Yea that's exactly what I'm using now with resedit. I figure changing the icon to something like that would benefit people running local srcds instances to develop on.

**Comment by Authorjames** [comment]
Yep. It was Braxen, by the way.

**Comment by robotboy655** [comment]
I am not sure if this will be possible, both srcds and hl2.exe use the same .ico file.
It was never my intention to change the srcds icon.

**Comment by robotboy655** [comment]
Nvm, got it. I hope you like orange.
