### ISSUE TITLE
Get Players

### ISSUE THREAD

**Issue by helix757** [Facepunch/garrysmod-requests#425]
A function to get the number of players to a connected server with a ip. This would make server hoppers easier.

**Comment by robotboy655** [comment]
As I understand you want a function what would return a number of players of the server on given IP?
I don't think this is worth adding due to extremely limited usage of this.

**Comment by helix757** [comment]
Well multiserver gamemodes like gmod tower can find use in it.

**Comment by Jvs34** [comment]
They don't need something like that, they already make use of external modules to make multiple servers communicate with each other.

**Comment by Netheous** [comment]
You can just use mysql for that.
I think they should look into stuff that has to be implemented and doesn't have a certain workaround before they move to other stuff.

**Comment by neico** [comment]
You could also just query the master server for those numbers, having that ability in general is probably more interesting then what you requested.

As this would require one to build a socket using a networking library like bromsock if you go pure lua and then import the master server protocol into it (or build it inside a module directly using a c++ library for said protocol).
Though I don't see anything that would make it easier for the gmod devs to add it as the protocol is hidden away behind the SteamAPI by now...

So I guess that's something that will only be available trough a 3rd party lib / module...

**Comment by robotboy655** [comment]
@neico, FYI, master server only returns a list of server IPs, all info is queried from the server.

**Comment by neico** [comment]
Yeah, but it's essentially the same route, only that if you have the IP already you can skip the master server and ask the server directly, it doesn't change the fact that you need to implement a protocol first...
