### ISSUE TITLE
GMPublish - Add a progress bar

### ISSUE THREAD

**Issue by Donkie** [Facepunch/garrysmod-requests#426]
Currently you just sit and stare blankly at it for 5 minutes hoping that it never failed on the way, having a progress bar would really help seeing if and how it works. Also a upload speed counter?

**Comment by robotboy655** [comment]
I looked into this, and it is impossible, at least with current Steamworks API GMod uses. Maybe when we update to newest version.

**Comment by Donkie** [comment]
Not even any upload speed or something?

**Comment by robotboy655** [comment]
No, it doesn't provide any info except for "did we fail yet?".

**Comment by Donkie** [comment]
lol

**Comment by robotboy655** [comment]
This is done on Dev branch, any addons uploaded on it however will not work with steamworks.Download (use steamworks.DownloadUGC in the next update)
