### ISSUE TITLE
Docking panels doesn't set their height

### ISSUE THREAD

**Issue by impulsh** [Facepunch/garrysmod-requests#427]
Docking a panel doesn't set its height, or at least it's not retrievable via :GetSize() or :GetTall(). An example would be fill docking a DIconLayout to a DPanel.

**Comment by wiox** [comment]
Invalidate it / the parent (or wait a frame) and try then (no promises).

**Comment by impulsh** [comment]
I've done :InvalidateLayout(true) and :InvalidateChildren(true) on the panel that holds all the docked panels, and there seems to be no effect.
