### ISSUE TITLE
Add PLAYER:GetHealth() as an alias to PLAYER:Health()

### ISSUE THREAD

**Issue by Mista-Tea** [Facepunch/garrysmod-requests#428]
I think this has been suggested on Facepunch months ago but it's still not implemented (just checked dev version). I couldn't find any requests in garrysmod-requests/issues.

Anyway, we have SetMaxHealth and GetMaxHealth, but for some reason we still don't have```Gethealth```.

For consistency's sake (and convenience), could we have PLAYER:GetHealth() while keeping PLAYER:Health() for backwards compatibility?

**Comment by DaaOtt** [comment]
+1

**Comment by bran92don** [comment]
+1

**Comment by misbe** [comment]
+1

**Comment by neico** [comment]
Less alias functions, more consistent naming structure and keeping at that.
That's how it should be...

**Comment by LUModder** [comment]
+1
