### ISSUE TITLE
Add PLAYER:GetArmor() as an alias to PLAYER:Armor()

### ISSUE THREAD

**Issue by Mista-Tea** [Facepunch/garrysmod-requests#429]
Couldn't find any previous github requests. Same deal with PLAYER:GetHealth().

Could we have PLAYER:GetArmor() for the consistency with other Get/Set functions as well as the convenience?

**Comment by DaaOtt** [comment]
+1

**Comment by Acecool** [comment]
There are a lot of these. In some instances it makes more sense to use Has instead of Is, just like using Get or not using it at all.

It's easy to set up an alias though...

```lua
// May need to be Player for armor...
local META_ENTITY = FindMetaTable( "Entity" );

META_ENTITY.GetHealth = META_ENTITY.Health;
META_ENTITY.GetArmor = META_ENTITY.Armor;
```

so it wouldn't hurt to have a few lines in the lua folder for the specific meta-table.

**Comment by wiox** [comment]
Meanwhile other duplicate functions are becoming deprecated. I'm not sure this is the best idea.

**Comment by Kefta** [comment]
Then deprecate Health and Armor; GetHealth and GetArmor are better matches

**Comment by wiox** [comment]
That's better than ending up with an alias. It still involves making a large portion of addons use deprecated features, though.
