### ISSUE TITLE
Add a hook for resolution changes

### ISSUE THREAD

**Issue by ottworks** [Facepunch/garrysmod-requests#432]
When you change resolution, all of the HUD and VGUI stuff breaks because people call ScrW() and ScrH() outside of hooks. Let's give people an option to fix that.

**Comment by robotboy655** [comment]
The only thing that breaks are the fonts. The rest is bad code.

**Comment by DaaOtt** [comment]
It's still a nice hook.

**Comment by Rusketh** [comment]
Agreed.

**Comment by neico** [comment]
Well it should work if you use http://wiki.garrysmod.com/page/PANEL/PerformLayout as a resolution change should invalidate all layouts (if it isn't then either what I know changed or it's a bug)

**Comment by zerfgog** [comment]
You're correct, neico. Willox posted this a few months ago:
```lua
hook.Add( "Initialize", "Resolution Change", function()
	vgui.CreateFromTable {

		Base = "Panel",

		PerformLayout = function()
			hook.Run( "ResolutionChanged", ScrW(), ScrH() )
		end
		
	} : ParentToHUD()
end )

hook.Add( "ResolutionChanged", "Resolution Change", function( w, h )
	print( "OH NO THE RESOLUTION CHANGED TO " .. w .. "x" .. h )
end )
```
To add to the discussion: I do believe that while it isn't necessary for things that properly use ScrW() and ScrH(), "It's still a nice hook."

**Comment by neico** [comment]
Well then you'd need to make it a hook that tracks the change to make it really stand out from the rest.
Since I don't want to copy paste your code example here's a small code with a slightly different approach:

```lua
local g_iScreenWidth = -1;
local g_iScreenHeight = -1;

function PANEL:Init()
	g_iScreenWidth = ScrW();
	g_iScreenHeight = ScrH();
end

function PANEL:PerformLayout()
	local iNewScreenWidth = ScrW();
	local iNewScreenHeight = ScrH();

	if g_iScreenWidth != iNewScreenWidth || g_iScreenHeight != iNewScreenHeight then
		// hook.Add( "ResolutionChanged", PANEL, function( iOldScreenWidth, iOldScreenHeight, iNewScreenWidth, iNewScreenHeight ) end )
		// function PANEL:ResolutionChanged( iOldScreenWidth, iOldScreenHeight, iNewScreenWidth, iNewScreenHeight ) end
		hook.Call( "ResolutionChanged", nil, g_iScreenWidth, g_iScreenHeight, iNewScreenWidth, iNewScreenHeight );

		g_iScreenWidth = iNewScreenWidth;
		g_iScreenHeight = iNewScreenHeight;
	end
end
```

**Comment by robotboy655** [comment]
Added.
