### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by deinemudda32** [Facepunch/garrysmod-requests#434]
The old browser isn't translated like in NMRIH.
Other games have a translated version of the old browser.

**Comment by robotboy655** [comment]
What browser? What are you talking about?

**Comment by deinemudda32** [comment]
The old browser.
Where you can join multiplayer games.

**Comment by robotboy655** [comment]
Oh. Its translation is tied to your Steam language I think. It will not be retranslated.

**Comment by deinemudda32** [comment]
It works with counter strike and every other source game without garry's mod.
my steam language is setted to mine and the game is not translated yet!
