### ISSUE TITLE
hl2dm weapon respawn and item respawn

### ISSUE THREAD

**Issue by kem008** [Facepunch/garrysmod-requests#437]
sv_hl2mp_weapon_respawn_time
sv_hl2mp_item_respawn_time

Would be greatful to add option for this

**Comment by robotboy655** [comment]
Is there really a need for this? This can be replicated with Lua in 0.5 seconds.

**Comment by Kefta** [comment]
I see no harm in adding them if they are in HL2DM

**Comment by robotboy655** [comment]
There's the minor issue of working on stuff that noone will use.
