### ISSUE TITLE
Increase default r_mapextents or remove cheat flag

### ISSUE THREAD

**Issue by Kawoosh** [Facepunch/garrysmod-requests#440]
By default r_mapextents has a value 16384, it cause half map not visible when you look out of corner, and not only.... It looks bad on sandbox or spacebuild with big maps. 32768 looks good, you can see all, even opposite corner. As it marked cheat users can't just fix this clientside, and I can't find any way to do this by script from server safely without enabling cheats. This not cause critical FPS drop, but looks really better.

**Comment by robotboy655** [comment]
I think map makers can override this in env_fog_controller, so there's no need for this.
You should also be able to do this via Lua.

https://developer.valvesoftware.com/wiki/Env_fog_controller#Keyvalues

**Comment by Kawoosh** [comment]
Thanks. Found a way to do this with env_fog_controller.
