### ISSUE TITLE
MC Supp

### ISSUE THREAD

**Issue by advancedrazor** [Facepunch/garrysmod-requests#441]
How about adding multicore support, since its gone all my servers are running on low resources and crash alot.
I dont even know why it got removed in gmod 12 or was it 11.
However could you simply add it as a option probably and default set it to 'false' and fix the crashs step per step. update by update.
So actually some folks can use it.
I would appreciate it alot.

Thanks for reading.

**Comment by robotboy655** [comment]
It is already requested.

**Comment by robotboy655** [comment]
( Also it wont magically solve your crashes, it will only make more of them, which is why it was disabled in the first place )

**Comment by advancedrazor** [comment]
Yea but as I said, it could be fixed step by step.
Not all at once, but just a option is not hurting anyone til its fixed (finally)
