### ISSUE TITLE
TTT Suggestions

### ISSUE THREAD

**Issue by MrUnknownGamer** [Facepunch/garrysmod-requests#444]
Hi,

I was thinking we could add some features to TTT. Its always being updated but this one will be a noticeable change to everyone who does not go on Github.

Jihad - We all know Jihads are a thing. I was thinking instead of it saying "...Died seconds before their team won" (The usual. Does not support jihad) to "...Took his fate to explode himself & everyone around him"

Recoil - We all know (This is how I start :~)) that the recoil just goes up. I was thinking  maybe we could make the recoil a little bit more like CSGO or CSS. Where the AK follows a D pattern and so on. So instead of recoil going up. It goes more realistic like CSS and CSGO. There should be a convar to disable this since people who have been playing since 2009-2010 have mastered the regular TTT recoil.

**Comment by robotboy655** [comment]
This is not a place to request features for TTT.

You can either make them yourself and Pull Request them or hire somebody to make them for your server or something.
