### ISSUE TITLE
Ability to separate bass.dll volume from GMod volume

### ISSUE THREAD

**Issue by Mista-Tea** [Facepunch/garrysmod-requests#446]
I had meant to post this suggestion months ago.

Would it be possible to add a menu option or cvar to separate the bass.dll's volume (see sound.Play/sound.PlayURL/etc) from GMod, similar to how Awesomium is independent of GMod?

**Comment by robotboy655** [comment]
#332

**Comment by Mista-Tea** [comment]
Haha, my bad. I thought I had never suggested it, my apologies. Wrong reference number by the way.
