### ISSUE TITLE
A way to get a list of banned users.

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-requests#447]
Basically the same as the concommand listid and listip. Returns a string or list of banned users.

**Comment by robotboy655** [comment]
You can already do this by reading files banned_ip.cfg and banned_user.cfg with Lua.

**Comment by thegrb93** [comment]
I know, but I figured it would be more efficient and accurate to get them from then filter being used by the engine.

**Comment by robotboy655** [comment]
If you want to get the engine bans, I just told you how to, they are saved to those files with "writeid" and "writeip" console commands. This includes Player:Ban()

Of course this won't give you players banned with custom admin mods, but no Lua binding from us can give you that.

**Comment by thegrb93** [comment]
Yeah I know. It would just be better if I could read the server filter.
