### ISSUE TITLE
Movedata SetVelocity prediction

### ISSUE THREAD

**Issue by Dgrouse96** [Facepunch/garrysmod-requests#450]
I've recently been heavily using the movement system, in particular GM:SetupMove().
I found that when I'm setting the player's velocity (shared), the client side's setvelocity is more like an empty function, giving the clients prediction errors.

By making the function actually affect the player there doesn't have to be that prediction error. I noticed the setorigin works client side, so why not setvelocity.

If you do get this right, the freedom of moving the player around smoothly can open so many possibilities, eg. Parkour, jet packs, more gamemode specific movements, high pings having less affect on gameplay. No more bumpy rides for me thanks.

**Comment by wiox** [comment]
I use SetVelocity on movedata all the time and it's fine. If you want help with prediction you should post your code (ideally to facepunch).

**Comment by Dgrouse96** [comment]
What I'm saying is that if I pulse my velocity clientslide it never responds. You are probably testing your code with little/no ping. Try cl_showerror 1 and it displays prediction errors if you cannot see the sudden change in position. There is absolutely nothing wrong with my code, I've tested this and even tried to fake the velocity change by setting the origin.

If you haven't understood this already the CLIENTSIDE SetVelocity function doesn't locally change the player's velocity. If you've ever played parkour on a high ping you notice that it takes a second for your wall kicks to respond. By allowing the clientside to predict velocity changes there doesn't need to be this delay.

**Comment by wiox** [comment]
Show some code or I'm going to tell you you're doing it wrong.

**Comment by Dgrouse96** [comment]
Wow, you're right, I just made an example to show you, then I tested it and it is predicted. Apologies and thanks.
