### ISSUE TITLE
Shared Vehicle:GetDriver/GetPassenger

### ISSUE THREAD

**Issue by Bo98** [Facepunch/garrysmod-requests#451]
Currently are serverside only.

**Comment by robotboy655** [comment]
Since vehicles are serverside only I am not sure if this is possible.

**Comment by Jvs34** [comment]
Also the clientside implementation of vehicles is not unified across crane/jeep/airboat/pod so it's kind of a pain in the ass.

**Comment by robotboy655** [comment]
Made Vehicle.GetDriver, Vehicle.GetPassenger, Vehicle.GetVehicleViewPosition shared
