### ISSUE TITLE
Advanced Controller Support

### ISSUE THREAD

**Issue by JoshuaDoes** [Facepunch/garrysmod-requests#460]
Hi,

Lately, I've been playing around with games with native gamepad support, personally using my Xbox One controller. I've been looking for game modifications or addons to add this, but I simply could not find anything of the sort. My request is an advanced controller support, for not only the gameplay but also the menus (like the server browser, the spawn menu, the pause and main menu, etc.), and the ability to choose between either different controller configs or create your own controller config.

Thanks in advance,
Joshua

**Comment by neico** [comment]
If we're going to do that I'd suggest to also include the steam controller into this, I'm pretty sure once it's out a lot will be requesting it...

**Comment by JoshuaDoes** [comment]
Steam will recognize the Steam Controller as your average Xbox 360 controller using the XPad drivers that come with Steam, but it won't have backwards compatibility support for the Xbox 360 or the Xbox One itself.

**Comment by neico** [comment]
Well but steam controller allows for more then just legacy controls (games that don't support the controller out of the box) and especially for gmod that can get interesting with custom configs...

**Comment by JoshuaDoes** [comment]
I would love to see that
Tbh I haven't read up on it too much

**Comment by robotboy655** [comment]
#342
