### ISSUE TITLE
Improve Workshop

### ISSUE THREAD

**Issue by emersont1** [Facepunch/garrysmod-requests#462]
A) Remove timeout for Workshop, as it prevents larger items from uploading
B) Give it a GUI as it can be 1) daunting for new users and 2) just impractical

**Comment by robotboy655** [comment]
One request per issue.

1) Explain
2) No. It is in fact very practical, there are community made GUI options. And in my mind it is good that it is daunting for new users, that means less shitty reuploads, edits or just 5 second addons.
