### ISSUE TITLE
Create a function to enable/disable the calling of Pre- and PostPlayerDraw.

### ISSUE THREAD

**Issue by JamesxX** [Facepunch/garrysmod-requests#463]

**Comment by neico** [comment]
And for what reason would you want that?
I don't see any to disable a hook call...

**Comment by JamesxX** [comment]
If I wanted to render 2 halves of the playermodel differently, for example, but I can see many other reasons.

**Comment by robotboy655** [comment]
I don't see how this can possibly help you do that.

**Comment by JamesxX** [comment]
Calling DrawModel on a player will call the Pre and PostPlayerDraw hooks. Drawing 2 halves of a playermodel would require calling DrawModel twice.

**Comment by robotboy655** [comment]
Use PreDrawTranslucentRenderables instead of PrePlayerDraw
