### ISSUE TITLE
Generally enhance the addons menu

### ISSUE THREAD

**Issue by Tenrys** [Facepunch/garrysmod-requests#465]
The addons menu currently is very annoying to use; change one addon's state, all addons get remounted. I'd prefer it as you make your modifications then have the choice to apply all of your changes at once.

It is also a pain in the ass to find addons; they are sorted in a very unusual way, it seems to be a mix between date subscribed and something else. We could really sure different sort algorithms and a search bar.

I tried implementing the first feature, but I failed miserably as my JavaScript skills were just not enough. (I couldn't set booleans, and I don't know how the environment works)

**Comment by robotboy655** [comment]
I guess this will be taken care what/if we get rid of the HTML menu. The way it is implemented right now ( the addon retrieval from Steam ) is really imperfect and remkaing it from scratch would not be worth it if we are getting rid of HTML menu.

**Comment by robotboy655** [comment]
Search bar is added, along side per tag subscription browsing, as well as bulk selection of items to disable/uninstall/enable. 

Newly subscribed addons are now always on the top of the list.

**Comment by Tenrys** [comment]
oh my

**Comment by Tenrys** [comment]
Great work
!(https://i.tenrys.pw/2017/May/KwMr.png)
!(https://i.tenrys.pw/2017/May/7n1p.png)
