### ISSUE TITLE
Make render.RenderView() work: add bindings to g_CurrentViewID

### ISSUE THREAD

**Issue by EstevanTH** [Facepunch/garrysmod-requests#467]
Hi Rubat and all others,

_Wiox_ suggested this to make **render.RenderView()** work properly with PixVis handles. I'm not 100% sure but that's probably a good trail to finally make it work.
I'm still almost sure that **render.RenderView()** misses something that makes it act differently from **point_camera** entities.

See the 2 last messages starting from here: [**render.RenderView()** corrupts PixVis handles](https://github.com/Facepunch/garrysmod-issues/issues/1764#issuecomment-76150270)

Setting and getting _g_CurrentViewID_ and using the enum

```
enum view_id_t
{
    VIEW_ILLEGAL = -2,
    VIEW_NONE = -1,
    VIEW_MAIN = 0,
    VIEW_3DSKY = 1,
    VIEW_MONITOR = 2,
    VIEW_REFLECTION = 3,
    VIEW_REFRACTION = 4,
    VIEW_INTRO_PLAYER = 5,
    VIEW_INTRO_CAMERA = 6,
    VIEW_SHADOW_DEPTH_TEXTURE = 7,
    VIEW_SSAO = 8,
    VIEW_ID_COUNT
};
```

(_viewrender.h_) should make it work. Modifying **render.RenderView()** as well is a very good & clean idea.

Thanks Rubat for taking my request into consideration. :heart:
Thanks William for helping me so much. :heart:

**Comment by UltimateByte** [comment]
So in the end, this would make mirrors possible ? :+1: then

**Comment by Kefta** [comment]
Could this be looked into? Could really use VIEW_MAIN for drawing water in render targets.

**Comment by SpiffyJUNIOR** [comment]
Apologies for the bump but any update on this?

**Comment by robotboy655** [comment]
I am failing to see any code that I could test with to know my changes are doing something, but I did manage to get map sprites to work correct-ish? on gm_construct from Willox's mirror example, by overriding VIEW_MAIN to VIEW_MONITOR from within `render.RenderView`. A separate binding would not be possible for this function, as it itself sets the current view multiple times.

I have applied the hack I came up with to `dev` beta, please let me know if that does anything useful for you.

**Comment by robotboy655** [comment]
I have changed it to "viewid" member on the input table. Default is 0 (`VIEW_MAIN`), `VIEW_MONITOR` is `2`. the previous change was causing issues with Soft Lamps, and so other addons as well, so I changed this to be optional, and by extension more configurable.

**Comment by robotboy655** [comment]
I am assuming this either solved, or nobody cares. The `viewid` option should be available on all beta branches.

**Comment by MattJeanes** [comment]
Noticed that this works but the VIEW_ enums don't seem to exist, is that intended? On x86-64 branch

Thanks for this by the way, I can remove my hacky workaround for util.PixelVisible now 😄
