### ISSUE TITLE
Backwards compatible DModelPanel that allows for multiple entities.

### ISSUE THREAD

**Issue by JamesxX** [Facepunch/garrysmod-requests#468]
It's something that everyone making a half decent inventory addon has to program in. I don't see why it has to be limited to just one model.

**Comment by bizzclaw** [comment]
It's really easy to make your own model panel actually. I made one myself for the character creation system in my gamemode as the character's hair styles are seperate models.

https://dl.dropboxusercontent.com/u/41867685/Sharex/pics042015/Garry%27s_Mod_2015-04-21_00-45-24.jpg

I just modified the already existing one, here's a link to it's code if you want it. 
https://github.com/garrynewman/garrysmod/blob/master/garrysmod/lua/vgui/dmodelpanel.lua

**Comment by robotboy655** [comment]
As mentioned above, it is too easy to do yourself.

**Comment by JamesxX** [comment]
I know its easy to make one myself, as I said, I've done it before, but seeing as everyone has to make one themself, it should really be in the game from the start.
