### ISSUE TITLE
PANEL:SetDrawLanguageID for TextEntry

### ISSUE THREAD

**Issue by KrakenZ** [Facepunch/garrysmod-requests#469]
This indicator is blocking some letters on small textentries:
![example](http://i.imgur.com/uhfSjBn.png) (in this example, the textentry dynamically resize itself, but the last letter is always blocked by the language ID)

We have Panel:SetDrawLanguageIDAtLeft, but that would still block the view.

**Comment by willox** [comment]
Added to dev branch.

**Comment by zerfgog** [comment]
willox is the real mvp
