### ISSUE TITLE
Applying Unicode Fonts to gmod.

### ISSUE THREAD

**Issue by rebel1324** [Facepunch/garrysmod-requests#47]
I'm trying to use this font 'seevaa9'. Link : https://dl.dropboxusercontent.com/u/41909844/1167249795_seevaa9.TTF

and I wrote this code 

surface.CreateFont( "ItemDisp" ,
{ font = "seevaa9",
	 size = 22,
	 weight = 300,
	 antialias = true,
	 outline  = false,
 } );

It is not working.

seevaa9 font -

Screenshot : http://cloud-2.steampowered.com/ugc/921266761932379271/BFE40006A25ECC1E6BDC2F7A4424C4093DF7B729/

Game Over font - Link : https://dl.dropboxusercontent.com/u/41909844/game_over.ttf

Screenshot : http://cloud-2.steampowered.com/ugc/921266761932378196/E71F17C196CE050B41004F23E68387FCF6089501/

 It is actually really small problem but I want to bring same experience with UI design to korean gmod users or am I doing it wrong?

**Comment by bmwalters** [comment]
You can use the `extended` option of [surface.CreateFont](https://wiki.garrysmod.com/page/surface/CreateFont):
```lua
local text = "저는 가끔 독서를 합니다."

surface.CreateFont( "SeevaTest", {
	font = "seevaa9",
	size = 22,
	weight = 300,
	antialias = true,
	outline = false,
	extended = true
} )

surface.CreateFont( "ConsolasTest", {
	font = "consolas",
	size = 22,
	weight = 300,
	antialias = true,
	outline = false,
	extended = true
} )

hook.Add( "HUDPaint", "seeva_test", function()
	surface.SetFont( "SeevaTest" )
	surface.SetTextColor( color_white )
	surface.SetTextPos( 200, 100 )
	surface.DrawText( text )

	surface.SetFont( "ConsolasTest" )
	surface.SetTextColor( color_white )
	surface.SetTextPos( 200, 200 )
	surface.DrawText( text )
end )
```

![](https://i.imgur.com/TOTDvaB.png)
