### ISSUE TITLE
Bring back sv_tags or game.AddTag()

### ISSUE THREAD

**Issue by TheFreezebug** [Facepunch/garrysmod-requests#470]
I think sv_tags should be re-implemented. Such a useful feature is being wasted on the current god-awful server browser. 

sv_tags used to be a useful utility for searching servers with specific content that you like, or getting rid of the servers that have content you don't like.

Even if we can't specifically do that (because it would break the god awful server browser, i think), is it possible a game.AddTag(STRING tag) function could be implemented? 

This way custom server browsers (and the default browsers) can search tags, to help users find servers with content relative to their liking

**Comment by thegrb93** [comment]
I was laggy as shit though.

**Comment by TheFreezebug** [comment]
@thegrb93 No laggier (in terms of network overhead) than the stupidly long hostnames we have with all the [custom][ custom ][   custom   ] [admin $4] in them.

**Comment by thegrb93** [comment]
Bump wtf

**Comment by UAVXP** [comment]
Bump.

**Comment by robotboy655** [comment]
Server browser tags are used internally, there's not enough space as is (iirc it has a 128 byte limit), let alone exposing this to Lua/servers.
