### ISSUE TITLE
Nextbot errors actually call error()

### ISSUE THREAD

**Issue by Exho1** [Facepunch/garrysmod-requests#471]
Currently they just print to console in the format of '[Nextbot] errormessage' which allows nextbots to silently fail, they should actually cause a Lua error so that developers can easily find errors

**Comment by robotboy655** [comment]
Easier said than done. This is caused by using coroutines for nextbot logic ( Which you do not have to do ), I could change it to call ```error()``` instead, but the error message will not be anymore helpful ( it will be actually less helpful )
```
[ERROR] gamemodes/base/entities/entities/base_nextbot/sv_nextbot.lua:27: addons/rb655_custom_addon/lua/entities/npc_test.lua:159: attempt to call field 'hax' (a nil value)
  1. error - [C]:-1
   2. unknown - gamemodes/base/entities/entities/base_nextbot/sv_nextbot.lua:27
```

**Comment by Exho1** [comment]
Oh okay so it is in Lua, thats cool. I understand keeping the stack trace, I just thought it would be beneficial to have the "something is causing lua errors" pop up when a nextbot errors. Its sorta like habit to look for that when testing your scripts

**Comment by willox** [comment]
Already improved these in the last update
