### ISSUE TITLE
Hiding TextEntry right-click context menu

### ISSUE THREAD

**Issue by KrakenZ** [Facepunch/garrysmod-requests#472]
![context menu vs lua contextmenu](http://i.imgur.com/K0LDpmd.png)
The engine-based context menu on TextEntry blocks mouse input for the lua context menu.

You cannot set the engine-based context menu's position, size or even remove it (if you try, it will crash the game on the next right click)

So I am asking for a TextEntry:SetContextMenuEnabled( bool ) function that safely disable this menu.

**Comment by robotboy655** [comment]
It's as simple as this:
```
TextEntry.OnMousePressed = function( self )
	local m = DermaMenu()
	m:AddOption("da")
	m:Open()
	return true
end
```
