### ISSUE TITLE
Server's workshop content size

### ISSUE THREAD

**Issue by DemetriussXVII** [Facepunch/garrysmod-requests#473]
While joining a server and downloading its content, make it show you the overall files' size and how many files left.

**Comment by Kefta** [comment]
Pretty sure there are PHP bindings for this, hence why they are on some loading screens

**Comment by GGG-KILLER** [comment]
there isn't anything showing the file size on Js, at least from what's shown on the [documentation](http://wiki.garrysmod.com/page/Loading_URL)

**Comment by robotboy655** [comment]
That's because it's simply impossible to do this due to Steam API not working properly and not returning the download progress with one function.

**Comment by GGG-KILLER** [comment]
If you think Steam API takes too much, I find this method faster: http://pastebin.com/tsAQ5bki

**Comment by robotboy655** [comment]
Added.

![image](https://user-images.githubusercontent.com/3299036/77768311-f9428b00-704a-11ea-89b5-028e3958178a.png)
