### ISSUE TITLE
Make UniqueID return a number directly related to SteamID

### ISSUE THREAD

**Issue by DaaOtt** [Facepunch/garrysmod-requests#474]
```
function meta:UniqueID()
  return tonumber(string.gsub(self:SteamID(), "%D", ""), nil)
end
```

so that STEAM_0:0:36527860 becomes 36527860.

I realize this would break _fucking everything_, but it'd be a nice solution to the hash collision problem (and a performance improvement).

**Comment by neico** [comment]
UniqueID is a completely different approach, and there enough ways to make the steamid return "garbage", for example how do you handle LAN SteamID's? or Unkown's

UniqueID on the other hand will most likely even work in those situations...

**Comment by wiox** [comment]
> and a performance improvement

There's no current performance issue. Your code is slower anyway rofl.
