### ISSUE TITLE
Prop_dynamic save support

### ISSUE THREAD

**Issue by Cordon** [Facepunch/garrysmod-requests#480]
Is it possible to make it so that prop_dynamics that are not from the vmf can be saved? This will fix not being able to save doors with the door tool. And also help with the wire mod supported prop_dynamic tool I reuploaded on the workshop.

**Comment by YourStalker** [comment]
This is something that you would code in lua yourself, scripts already exist for this.

**Comment by Cordon** [comment]
Could you point me to such a script? I'll close the issue down if I can find one.

**Comment by YourStalker** [comment]
https://scriptfodder.com/scripts/view/1047

**Comment by YourStalker** [comment]
Didn't even know this was a thing: http://forum.darkrp.com/threads/how-to-use-persistence-permanent-props.3371/

**Comment by Cordon** [comment]
Yeah that's not really the thing I'm looking for. I don't think you understood me, I'm talking about being able to save PROP_DYNAMIC class props with gmod's save system, I'm not looking for always permanent props.

**Comment by YourStalker** [comment]
What do you mean by saving a prop_dynamic, all that is is generally a prop with animations. You also wouldn't make a door using that, you would use prop_door_rotating

**Comment by Cordon** [comment]
Prop_dynamics don't work with gmod's saves. Also, the combine doors do infact use prop_Dynamic.

**Comment by robotboy655** [comment]
This is not a place to request addons. This is already possible and is done by me in my door tool ( Part of Half-Life 2 Tools addon )
