### ISSUE TITLE
Update srcds_run script (fixes -autoupdate)

### ISSUE THREAD

**Issue by Bo98** [Facepunch/garrysmod-requests#481]
Current GMod srcds_run: http://pastebin.com/s9Re1p0B
Current CS:GO srcds_run: http://pastebin.com/YFu16QKK

Differences:
- `-autoupdate` works (uses SteamCMD)
  - `-steambin`, `-steamverify`, `-steamuser` and `-steampass` removed (was for pre-SteamCMD)
    - `-steam_dir` and `-steamcmd_script` used instead.
- `-fork <n>` added (Run`<n>` server instances as subprocesses)
- `$FORCE` environment variable removed (use `-binary` launch option instead)
- `-nodefaultmap` added (don't know what GMod would do in this case)
- ./srcds_osx support removed
  - This used to exist in GMod (I have a copy) but I don't know the state of it now
  - Support can be kept (won't hurt anybody) by keeping the `detectcpu` function, readding `HL_DETECT=1` back near the start of the `init` function and readding the following before the "Source Engine binary" check:

``` sh
# Only detect the CPU if it hasnt been set with
# either environment or command line
if test "$HL_DETECT" -eq 1; then
        detectcpu
fi
```

---

You would need to change `DEFAULT_GAME` and `DEFAULT_MAP` variables in the new script. The current srcds_run used in GMod actually defaults to "tf" so this makes the `-game` launch option optional now.

**Comment by robotboy655** [comment]
I've merged most of this, except for the ```-fork``` stuff.

I used the TF2 version of srcds_run we have (23.11.2015) for most of it.

It'd be great if someone verified that I didn't do anything stupid and it still actually works, especially the -autoupdate stuff.

**Comment by robotboy655** [comment]
This is what I ended up with: https://pastebin.com/671BtSR7
