### ISSUE TITLE
Increase env_projectedtexture max projection distance from 10240 to 56756

### ISSUE THREAD

**Issue by baldursgate3** [Facepunch/garrysmod-requests#484]
Can you please increase it from 10240 to 56756? You may ask why you'd need such crazy high proxjection distance, but It will provide modders like me with the flexibility to create large lighting effects that become really useful.

**Comment by Bo98** [comment]
It's at 32768 in multiplayer on the dev branch.

**Comment by baldursgate3** [comment]
@Bo98 , I'm looking for exactly 40960.

**Comment by xaviergmail** [comment]
Why would you need 40960? That's above the map size limit, you won't get much out of anything higher.

**Comment by baldursgate3** [comment]
@xaviergmail but without that exact number, I won't be able to do this http://steamcommunity.com/sharedfiles/filedetails/?id=419769190 and http://steamcommunity.com/sharedfiles/filedetails/?id=419769545

**Comment by thegrb93** [comment]
@xaviergmail The distance from the far corners of gm_flatgrass is about 46238 so I can see why he'd need that much.

**Comment by xaviergmail** [comment]
@thegrm93 Ah I see, that makes sense. I'm all for this then.

**Comment by wiox** [comment]
If the maximum dimensions in hammer are 32768x32768x32768 I guess the maximum distance should be 56756 to allow for the distance to cross the largest possible amount of space a map could have.

**Comment by FirstRoboticsGuy999** [comment]
If we increase the hard-coded limit, won't that have a negative effect on maps?

**Comment by baldursgate3** [comment]
@FirstRoboticsGuy999, I don't think it's hard-coded. @Rubat did increase it a while ago in dev version.

**Comment by robotboy655** [comment]
That means exactly that it is a hardcoded limit, it can only be changed in the c++ sources.

The downside of this is pretty obvious, it will lag more if set to such extreme distances while calculating shadows and projections and shit.

**Comment by baldursgate3** [comment]
@robotboy655, yea but it'll lag when you spawn the projection. You  could put down clamp max range on the lamp tool while letting modders have limitless access by increasing the limit to 56756.

**Comment by baldursgate3** [comment]
Is there any reason why you don't want to increase it?

**Comment by baldursgate3** [comment]
@robotboy655, Is there any other reason why you don't want to increase it apart from excessive lag?

**Comment by Jvs34** [comment]
https://twitter.com/FacepunchBot/status/603115912854695936

**Comment by baldursgate3** [comment]
@Jvs34, crap didn't see that. Closed
