### ISSUE TITLE
Old server browser translation

### ISSUE THREAD

**Issue by deinemudda32** [Facepunch/garrysmod-requests#489]
In nearly every source game, like css, nmrih and hl2:dm is the server browser translated, but not in garry's mod.
Even the connection info like "Sending client-info" is not translated.
I configured steam properly and everyone of my friends have the same problem.

**Comment by Noiwex** [comment]
It's intended

**Comment by deinemudda32** [comment]
Yea, youre right. Bugs are NOT intented, nut not translated game points are intented.

**Comment by robotboy655** [comment]
This is not intended, but was never addressed.

**Comment by deinemudda32** [comment]
not everyone cares so much about this.
The most gmod players doesnt even know that this is a bug tracker or even exists.

**Comment by robotboy655** [comment]
Legacy browser should use your Steam's language now.

https://github.com/Facepunch/garrysmod-issues/issues/4110
