### ISSUE TITLE
User-friendly error messages in GMPublish

### ISSUE THREAD

**Issue by Bo98** [Facepunch/garrysmod-requests#49]
Not sure if this should be here since it's not strictly Garry's Mod but it is a tool included in GMod.

Currently GMPublish outputs an error number when it encounters an error. For a majority of people, this is useless as a lot of people do not know what each number means. I think a simple piece of text to accompany the error number will help more people understand why this error occurred.

**Comment by robotboy655** [comment]
This should be handled.
