### ISSUE TITLE
ShouldCleanUp hook

### ISSUE THREAD

**Issue by DaaOtt** [Facepunch/garrysmod-requests#491]
A hook that calls for every entity that's about to be removed by game.CleanUpMap(). So stuff like lua-added point entities (SpaceBuild atmosphere markers, filter_activator_name for Unbreakable tool, etc) won't break if coded properly (properly as in no [workarounds](https://github.com/garrynewman/garrysmod/blob/445719c10ddc6519b8bb36921e547f7521fee00d/garrysmod/gamemodes/terrortown/gamemode/ent_replace.lua#L164)).

**Comment by thegrb93** [comment]
I thought entities created during the InitPostEntity are safe from cleanups.

**Comment by DaaOtt** [comment]
If that's true, then it needs to be documented.

**Comment by xaviergmail** [comment]
All of my gamemode entities get fucked on game.CleanUpMap(). They're not created in InitPostEntity, though and it is not possible for me to create them only during that hook. I could see this as being beneficial, but also very slow if poorly implemented / hooked.

**Comment by thegrb93** [comment]
Never mind, I just tested it and entities created in InitPostEntity aren't safe. They should be imo.

**Comment by robotboy655** [comment]
1) http://wiki.garrysmod.com/page/game/CleanUpMap has a second arguments for exactly this.
2) If you are creating entities with Lua in InitPostEntity, also create them in http://wiki.garrysmod.com/page/GM/PostCleanupMap
