### ISSUE TITLE
physgun_maxrange

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-requests#492]
Server convar which will allow adjusting the range of the physgun beam. Would be useful to increase the range for sandbox and decrease the range for RP.

**Comment by Noiwex** [comment]
Why would you use physgun in rp.

**Comment by MrBrax** [comment]
@Noiwex don't pretty much every darkrp server support prop spawning & base building?

**Comment by UltimateByte** [comment]
:+1: This could be useful, i upvote this request.

@Noiwex Did you ever try to cook crystal meth with a gravgun ?

**Comment by Noiwex** [comment]
Why would I do such boring repetitive task.

**Comment by UltimateByte** [comment]
If you're using rp_setmoney to get money you can still use it because it's funny... If you think it's funny to cook meth. But we're off topic.

BTW, of course any object you want to rotate is a pain with gravgun.

**Comment by willox** [comment]
The range is 128 -> 8192, the default is 4096. You can pick up props that are 2x farther away but only move them towards/away from you up to the max range (that's just the current behaviour)
