### ISSUE TITLE
"Patch" shader type

### ISSUE THREAD

**Issue by Bo98** [Facepunch/garrysmod-requests#495]
Doesn't work in GMod currently

```
Error: Material "test" uses unknown shader "patch"
```

https://developer.valvesoftware.com/wiki/Patch

**Comment by FirstRoboticsGuy999** [comment]
The Patch shader is irrelevant, it isn't engine dependent like VertexLitGeneric and LightmappedGeneric.

**Comment by robotboy655** [comment]
You talk like it's has been purposefully disabled to fuck with you.
It never existed in GMod due to the fact that it was added in the Orange Box engine branch.

**Comment by robotboy655** [comment]
It appears that we do not have such shared in the code base, so don't expect it to ever work.

**Comment by robotboy655** [comment]
#671

**Comment by Bo98** [comment]
Are you saying that it's added now?

**Comment by willox** [comment]
It was never missing, the error messages for patches that fail to load are just slightly misleading.

**Comment by Bo98** [comment]
Yeah, I just read the Next Update post. No idea what mistake I was making in them before but maybe the better error messages will clear that up.

**Comment by Bo98** [comment]
Apparently patch just doesn't work with `CreateMaterial`. I think that was what I was trying to do before.
