### ISSUE TITLE
Add bindings to CBasePlayer::Get/SetLaggedMovementValue

### ISSUE THREAD

**Issue by xaviergmail** [Facepunch/garrysmod-requests#496]
This would allow us to easily scale player movement speed without having to rely on custom movement hooks.

**Comment by Jvs34** [comment]
Just as a FYI for robotboy or vinh or whatever, this system is used by HL2 during the weapon stripping sequence, and it's networked properly to the client.

**Comment by Kefta** [comment]
This would be great

**Comment by robotboy655** [comment]
Added in Dev.
