### ISSUE TITLE
Legacy Browser Favorite Storing

### ISSUE THREAD

**Issue by LordxDeath** [Facepunch/garrysmod-requests#497]
I wish there was a way to let people know if their server is Favorited like it is on tf2. That way servers can reward people for favorting their server. I asked multiple coders and all responded with currently not possible

**Comment by LUModder** [comment]
I don't think GMod can hook into the game like Sourcemod can to retrieve something like that.

**Comment by TheFreezebug** [comment]
@LUModder Sourcemod can only scratch the surface of the engine, and not much on clientside. This in fact would be more possible in garrysmod than in sourcemod.

**Comment by LordxDeath** [comment]
I heard that the legacy browser is used on html?. so i have no idea if it possible or not

**Comment by daunknownman2010** [comment]
The legacy server browser is not html. It runs off Source VGUI instead and looks less pretty than the normal Garry's Mod server browser.

**Comment by LordxDeath** [comment]
Based on my further investigation. tf2 works with sourcemod and has some
steamapi which helps it work and get the favorites list. Just what Flex
said.


So just a suggestion maybe we can have sourcemod support to gmod? expand
the options for players?

**Comment by robotboy655** [comment]
You can already see your favorite servers in both, the HTML server browser and the legacy server browser.

**Comment by LordxDeath** [comment]
I ment servers knowing you have them in their favorites so they can get
awarded

**Comment by thegrb93** [comment]
Rewarding players for favoring a server? Sounds super stupid.

**Comment by daunknownman2010** [comment]
@thegrb93 It is stupid in general. Though, there are some pretty weird server owners out there that might find this a "cool idea".
