### ISSUE TITLE
Allow SetNWInt to support 64 bit integers?

### ISSUE THREAD

**Issue by TheFreezebug** [Facepunch/garrysmod-requests#498]
The old SetNWInt supported 64 bit integers.

Thanks to this new net library, I can't use 64 bit integers ,  which is a bad thing. 

Not being able to have values over 2^31 is not fun :v

**Comment by wiox** [comment]
The numbers are stored in Lua as doubles. You're going to lose precision on your values if they are that large.

Use strings.

**Comment by TheFreezebug** [comment]
@wiox Forgot about that, note taken. Thanks Willox!
