### ISSUE TITLE
Workshop changes

### ISSUE THREAD

**Issue by comedinha** [Facepunch/garrysmod-requests#499]
When a script is removed from the workshop and you are subscribed in it you should be notified.

**Comment by robotboy655** [comment]
How you'd expect to be notified? What for?

**Comment by comedinha** [comment]
I put some addon on my server, a map for example. It is removed I am not warned he continues in my collection as nil and I get no track of which map which is removed.

**Comment by robotboy655** [comment]
And how you'd expect to be notified?

**Comment by comedinha** [comment]
The steam not give any option for "custom" notification?

**Comment by robotboy655** [comment]
No.

**Comment by comedinha** [comment]
:s
