### ISSUE TITLE
Add option to disable main menu slideshow

### ISSUE THREAD

**Issue by FirstRoboticsGuy999** [Facepunch/garrysmod-requests#501]
I would like to have an option to disable the slideshow of screenshots on the main menu. I personally don't care for the slideshow of screenshots, and they just waste texture memory in my opinion. 

Maybe we could allow users to also set their own color gradient if we wanted?

**Comment by meepdarknessmeep** [comment]
nothing is stopping you from doing it yourself
no need to add a setting for something only you have really wanted

**Comment by robotboy655** [comment]
Remove all the backgrounds in background/ and you are done.
