### ISSUE TITLE
No way to add a server to favorites except legacy browser

### ISSUE THREAD

**Issue by UltimateByte** [Facepunch/garrysmod-requests#503]
Title is self explaining, kids are always complaining to me "how do i put a server to favorites..." because they see the favorite menu.
I'd be grateful if you'd make servers right clickable in new server list, or add an option on the right to save them as favorite.

**Comment by robotboy655** [comment]
Now there is a way!

**Comment by UltimateByte** [comment]
Thank you. Cool to see you're still working on Gmod :)
(After almost 3 years haha! Just broke my previous record of 2 years for `+r_hunkalloclightmaps 0` ;) )
