### ISSUE TITLE
Make Sweps Dynamically editable

### ISSUE THREAD

**Issue by P4sca1** [Facepunch/garrysmod-requests#504]
So I want to make a Swep dynamically editable for every player. That would make it possible to set the SWEP.ViewModel for a specific player to something else then default without creating a new Swep.
I'm relatively new to lua and all the stuff so excuse me if this is really stupid. 
Regards, 
Pascal

**Comment by thegrb93** [comment]
Ask questions here first http://facepunch.com/forumdisplay.php?f=65

**Comment by P4sca1** [comment]
Thanks! I will do this the next time first. :)

**Comment by robotboy655** [comment]
1) You should never have the need to change view models on one SWEP on the fly
2) It is currently not advisable ( animations will break )
