### ISSUE TITLE
Add a way to stop specified attached engine particle effect

### ISSUE THREAD

**Issue by baldursgate3** [Facepunch/garrysmod-requests#505]
I would like to have a function that allows me to stop specified (attached) particle effect without having to stop all others. 
Maybe named something like Entity:StopParticlebyName("string particle name")

**Comment by robotboy655** [comment]
I feel like this is covered by #127

**Comment by baldursgate3** [comment]
@robotboy655,

Oh cool. Never knew ParticleEffectAttach() returned anything.

**Comment by robotboy655** [comment]
It's still a request. Learn to read.
