### ISSUE TITLE
ConVar to disable map graph sending over FastDL

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#508]
Most servers don't send .ain files and don't rely on them for nodegraphs anymore.

**Comment by besenyei** [comment]
This would be particularly useful for servers which don't even use npcs.
pvp based gamemodes, or ones that explicitly use nextbots.

**Comment by gabwiel** [comment]
It's really annoying...

**Comment by Kefta** [comment]
Or a command-line flag :)

**Comment by robotboy655** [comment]
Your should be able to already disable this by adding `nodegraph 0` to your `gameinfo.txt`

**Comment by Kefta** [comment]
@robotboy655 is correct. A better method of toggling this behaviour without modifying the ``gameinfo.txt`` would still be preferable though as this is probably something a lot of server owners would do were it more accessible/they knew about it.

**Comment by MyDimeIsUp** [comment]
Any update on this?

**Comment by robotboy655** [comment]
Add sv_no_ain_files, defaults to 0

here
