### ISSUE TITLE
Add Lua binding for UTIL_Tracer

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#513]
And add the extra TRACER enmus like TRACER_DONT_USE_ATTATCHMENT

**Comment by robotboy655** [comment]
```
function UTIL_Tracer( start, end, velocity, eff )
	local ed = EffectData()
	ed:SetScale( velocity or 3600 )
	ed:SetStart( start )
	ed:SetOrigin( end )
	util.Effect( eff or "Tracer", ed, true, true )
end
```

**Comment by robotboy655** [comment]
You can add the rest of the things by looking at the source:
https://github.com/ValveSoftware/source-sdk-2013/blob/55ed12f8d1eb6887d348be03aee5573d44177ffb/sp/src/game/shared/util_shared.cpp#L738-L773

**Comment by Kefta** [comment]
Thanks, 2007 leak didn't have any of the UTIL func sources

**Comment by Kefta** [comment]
Could you add the attachment TRACER enmus to the current TRACER globals we have?

**Comment by robotboy655** [comment]
No, TRACER_DONT_USE_ATTATCHMENT doesn't exist, and the existing TRACER enums are used for the ammo types.

**Comment by Kefta** [comment]
I spelled it wrong on my phone, but I meant TRACER_DONT_USE_ATTACHMENT, TRACER_FLAG_WHIZ, and TRACER_FLAG_USEATTACHMENT

**Comment by robotboy655** [comment]
They are useless in the Lua bindings other TRACER enums are used for, so no.

https://github.com/ValveSoftware/source-sdk-2013/blob/55ed12f8d1eb6887d348be03aee5573d44177ffb/mp/src/game/shared/ammodef.h#L45-L52
