### ISSUE TITLE
Add Panel:GetTooltip()

### ISSUE THREAD

**Issue by MattJeanes** [Facepunch/garrysmod-requests#514]
There's Panel:SetTooltip so I don't see why not. It is manually accessible with `panel.strTooltipText` but I still think there should be an official function so I don't have to use workarounds like that.

**Comment by Noiwex** [comment]
It's not a workaround, how accessor function would benefit you?

**Comment by Kefta** [comment]
Fixed in https://github.com/garrynewman/garrysmod/pull/998

**Comment by MattJeanes** [comment]
Cheers. @Noiwex Accessor function would not benefit me personally because I had a dig around to find it manually by using PrintTable(panel:GetTable()) but the point is I shouldn't have to do that, and others may not know how to find it. It makes logical sense that anything with a Set function should also have a Get one.

**Comment by Kefta** [comment]
Solved in https://github.com/Facepunch/garrysmod/commit/b2a6412bf0308be6257967f617e146d099144314.
