### ISSUE TITLE
Lightmaps on Static Props

### ISSUE THREAD

**Issue by Kemerd** [Facepunch/garrysmod-requests#517]
http://forums.tf2maps.net/showthread.php?t=23288

I know this is already implemented into the Source SDK 2013 Github, and implemented into not only TF2, but several SDK mods as well. Could you implement this into the FGD and Garrysmod itself?

**Comment by robotboy655** [comment]
We do not have any code for that, so don't expect it to ever be added.

**Comment by Noiwex** [comment]
This sucks.

**Comment by Kemerd** [comment]
Isn't the code for this in:
https://github.com/ValveSoftware/source-sdk-2013

Would it be so hard to just merge the code for it into the current Garrysmod mod?

**Comment by robotboy655** [comment]
Most of the code for Source SDK are just header files, that's not enough to have the functionality.

**Comment by Kemerd** [comment]
That's a shame. Thanks for responding, though!

**Comment by robotboy655** [comment]
This is now fully supported in `dev` beta.

**Comment by MykhailKozak** [comment]
> This is now fully supported in `dev` beta.

Does this _actually_ support the [$lightmap VMT parameter](https://developer.valvesoftware.com/wiki/$lightmap)? If so I am having trouble getting it working having tried different combos of VTF formats and prop_static parameters.
If not, it'd be a greatly appreciated implementation, I'd like to use baked maps from Cycles given the enhanced detail, less light leaking, and customizability. Plus this'd go great for lightmapping interiors of dynamic props such as vehicles.

**Comment by MykhailKozak** [comment]
Setup example for $lightmap
[static_lightmap_test.zip](https://github.com/user-attachments/files/16386163/static_lightmap_test.zip)

Below is an approximation using $detail multiplicatively, result is darker than should be and as noted dynamic lights will not correctly light dark spots as the actual albedo is darkened.
![20240725202215_1](https://github.com/user-attachments/assets/32636721-1073-49a7-b2b1-5adea41d1d26)
![20240725202218_1](https://github.com/user-attachments/assets/b4bc8ab2-e6e2-4db8-9f03-f14ee17a1f84)
