### ISSUE TITLE
Raise model precache limit

### ISSUE THREAD

**Issue by aStonedPenguin** [Facepunch/garrysmod-requests#518]
There's no reason it shouldn't be higher.

**Comment by Kefta** [comment]
Just add a convar

**Comment by Noiwex** [comment]
We can't just allow more precached models — this way players will load even
more models into memory (with all those HD materials). We need dynamic
model precaching.

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/56

**Comment by SSN-ATomIC** [comment]
Robonigger

**Comment by Kefta** [comment]
Shut up. You and Penguin aren't funny

**Comment by PHPApple** [comment]
this is a reasonable request and here is why agShasdhashasrhsDHsfSEGSDHSDFHSETADG ![http://facepunch.com/fp/emoot/zoid.gif)

**Comment by SSN-ATomIC** [comment]
Says the one in ts with us

**Comment by SSN-ATomIC** [comment]
Says the one laughing in ts with us

**Comment by PHPApple** [comment]
says the one saying the one laughing in ts with us in ts with us

**Comment by Kefta** [comment]
http://puu.sh/iJ27s.png

okay

**Comment by SQLATomIK** [comment]
http://i.imgur.com/NmGe2c5.png

okay

**Comment by Kefta** [comment]
http://puu.sh/iJ2dY.png

okay

**Comment by aStonedPenguin** [comment]
http://stonedpengu.in/i/hW3Dj.png

okay

**Comment by SQLATomIK** [comment]
http://i.imgur.com/nOqTmuO.png

okay

**Comment by PHPApple** [comment]
guys

**Comment by PHPApple** [comment]
move me back to the channel
