### ISSUE TITLE
Please tell how exactly you are using the BASS channel in game

### ISSUE THREAD

**Issue by SimonSchick** [Facepunch/garrysmod-requests#52]
I was trying to write a DLL to test some enhancements, however it seems the userdata does not contain the handle(atleast not directly), since I'm not good at reverse engineering I'd like you to post what exactly you store in the userdata(structs, classes, etc.).

**Comment by wyozi** [comment]
I had to go through painful procedure of figuring this out a while ago myself, but I got it in the end.

```cpp
DWORD GetBassHandle(GarrysMod::Lua::UserData* udata) {
	return *((DWORD *)udata->data + 1);
}
```

**Comment by Kefta** [comment]
@wyozi Could you make a BASS wiki page with this info?

**Comment by wyozi** [comment]
@Kefta sure
