### ISSUE TITLE
Add filter argument to EmitSound

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#520]
This way, we can manipulate our own PAS. For example, playing a sound in a radius to a certain team or to everyone except the local player

**Comment by mcd1992** [comment]
+1

Having more control over the networking of sounds is a must.

**Comment by mcd1992** [comment]
Still in need of this, having to re-create the sound when players change PAS is a nuisance.

**Comment by xaviergmail** [comment]
This is a small feature that goes a long way. Shouldn't be hard at all to add either. Someone please have a look!

**Comment by TehBigA** [comment]
I would love to have this support!

**Comment by robotboy655** [comment]
Done for both global and entity method - optional last argument.
