### ISSUE TITLE
On lua Error hook being usable clientside/serverside instead of just in the menu?

### ISSUE THREAD

**Issue by kulcris** [Facepunch/garrysmod-requests#521]
from the look of the function it appears that it is only usable from the menu. i would like to be able to hook into on lua error so that when a lua error happens

GM:OnError(string error, clientside/serverside)   (syntax probably way wrong for a hook but you get the picture)

**Comment by Bo98** [comment]
#149

**Comment by kulcris** [comment]
repeat of another request
