### ISSUE TITLE
Add CollisionGroup to trace structure

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#522]
For TraceLine and TraceHull. COLLISION enums are already in GMod.

**Comment by robotboy655** [comment]
Why? Just do tr.Entity:GetCollisionGroup() if you need it.

**Comment by Kefta** [comment]
I'm not talking about getting the collision group, I'm talking about setting it so we can specify what to collide with. Currently, it's set to COLLISION_GROUP_NONE which means all traces will hit everything.

**Comment by Kefta** [comment]
Would be nice to have an IgnoreEntity parameter also to prevent traces from hitting the entity being traced from

**Comment by robotboy655** [comment]
You can already use the filter field for that.

**Comment by Kefta** [comment]
Duh; also, the collision group parameter already exists for all Trace* functions, it just needs to be bound. I believe it currently defaults to COLLISION_GROUP_NONE

**Comment by robotboy655** [comment]
* Added "collisiongroup" to util.Trace* functions

**Comment by Kefta** [comment]
Thank you!
