### ISSUE TITLE
Mounting addons during game startup and menu caching

### ISSUE THREAD

**Issue by ElHyperion** [Facepunch/garrysmod-requests#523]
Every time I start Garry's Mod, the loading time during the blue splash screen is without any doubts almost lightning fast, since GM13. But a couple of seconds after the menu appears, the game hangs up for some time- that's when the workshop addons get mounted I suppose, as the "Addons have changed - remounting" message appears in the console.

Wouldn't it then be better to mount all the addons during the initial loading of the game, cutting out those few seconds of delay? Caching the Start New Game and Find Multiplayer Game screens into memory could prove useful aswell, as they introduce some loading time upon being pressed. All those loadings also badly affect custom background music, with multiple interuptions caused to it

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/1904

It won't "cut" the delay, it will just move it, but yes, it is planned to do.
