### ISSUE TITLE
Add RecipientFilter parameter to CreateSound.

### ISSUE THREAD

**Issue by mcd1992** [Facepunch/garrysmod-requests#525]
Looking through the sdk source I see that the engine's SoundCreate has a parameter for the IRecipientFilter. As with Gmod's CreateSound it seems to just use the PAS as the IRecipientFilter. Would it be possible to allow us to set the CSoundPatch's IRecipientFilter in Lua?

https://github.com/ValveSoftware/source-sdk-2013/blob/55ed12f8d1eb6887d348be03aee5573d44177ffb/sp/src/game/shared/soundenvelope.h#L55

**Comment by birdbrainswagtrain** [comment]
-1

**Comment by Kefta** [comment]
Care to explain? @birdbrainswagtrain

Also, this goes hand-in-hand with a greater PAS library being added: https://github.com/Facepunch/garrysmod-requests/issues/520

**Comment by mcd1992** [comment]
@robotboy655 Any update on this? Having to re-create the sound when a player that was outside of the PAS enters it is buggy and annoying.
