### ISSUE TITLE
Add basic math functionality as functions

### ISSUE THREAD

**Issue by Acecool** [Facepunch/garrysmod-requests#527]
I was working on a new meta-table object and was adding all of the math functionality to it and as I was designing it, I saw that a lot of code would be repetitive for those segments because we don't have basic math functions as default in Lua or GLua...

Note: Unpack converts "x.y.z" to return x, y, z

Basically:

```lua
function version:__add( _version )
	local _major_c, _minor_c, _build_c	= self:Unpack( );
	local _major_a, _minor_a, _build_a	= _version:Unpack( );
	return string.format( VERSION_FORMAT_STRING, _major_c + _major_a, _minor_c + _minor_a, _build_c + _build_a );
end

function version:__sub( _version )
	local _major_c, _minor_c, _build_c	= self:Unpack( );
	local _major_a, _minor_a, _build_a	= _version:Unpack( );
	return string.format( VERSION_FORMAT_STRING, _major_c - _major_a, _minor_c - _minor_a, _build_c - _build_a );
end

function version:__mul( _version )
	local _major_c, _minor_c, _build_c	= self:Unpack( );
	local _major_a, _minor_a, _build_a	= _version:Unpack( );
	return string.format( VERSION_FORMAT_STRING, _major_c * _major_a, _minor_c * _minor_a, _build_c * _build_a );
end

function version:__div( _version )
	local _major_c, _minor_c, _build_c	= self:Unpack( );
	local _major_a, _minor_a, _build_a	= _version:Unpack( );
	return string.format( VERSION_FORMAT_STRING, _major_c / _major_a, _minor_c / _minor_a, _build_c / _build_a );
end
```

is repetitive and can easily reduce to become

```lua
function version:__math( _version, _func )
	local _major_c, _minor_c, _build_c	= self:Unpack( );
	local _major_a, _minor_a, _build_a	= _version:Unpack( );
	return string.format( VERSION_FORMAT_STRING, _func( _major_c, _major_a ), _func( _minor_c, _minor_a ), _func( _build_c, _build_a ) );
end

function version:__add( _version )
	return self:__math( _version, math.add );
end

function version:__sub( _version )
	return self:__math( _version, math.sub );
end

function version:__mul( _version )
	return self:__math( _version, math.mul );
end

function version:__div( _version )
	return self:__math( _version, math.div );
end
```

Or even less depending on syntax chosen ( one line per math action ), or more with comments but less than needing to perform it all each time...

By adding:
```lua
function math.add( a, b ) return a + b; end
function math.sub( a, b ) return a - b; end
function math.mul( a, b ) return a * b; end
function math.div( a, b ) return a / b; end
-- math.mod exists...
-- math.pow exists...
```

I'll submit a proper pull-request with the code later but I wanted to gauge thoughts right now before doing it because adding these is incredibly easy and I don't know how many people would use this.. I just prefer to slim my code down as much as possible and hate ever repeating anything unnecessarily.. 

I'm surprised those 4 simple math functions aren't included by default...

. Currently we can not dynamically reference operators ( as far as I know ) but we can do so for functions...

**Comment by thegrb93** [comment]
I don't think anyone would use this. Most people would just use a lambda function. Your code is very strange btw.

**Comment by robotboy655** [comment]
Can you stop with these ridiculous ideas please that would be very good.
