### ISSUE TITLE
Add more CTakeDamageInfo modifiers

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#532]
Setting the reported position, DamageBonus, DamageCustom, and setting/checking friendly fire -- which would be made more efficient than doing a team check on every damage instance.

**Comment by thegrb93** [comment]
Hitgroup too if possible.

**Comment by robotboy655** [comment]
I dont think hitgroups are stored in damage info.

**Comment by Kefta** [comment]
It's not; just do a TraceHull before dispatching the trace attack

**Comment by robotboy655** [comment]
Mind explaining why you need DamageBonus, DamageCustom? They don't seem to be doing anything.
CTakeDamageInfo doesn't check for friendly fire by the way.

**Comment by robotboy655** [comment]
Ok, so it appears that DamageBonus is not used by the engine at all, and DamageCustom is used in some weird way to override killer class in HL2MP death notice which is not used in GMod.

**Comment by Jvs34** [comment]
Yes however they would allow us to carry more information on the damageinfo instead of having to use hacks, such as marking the damage as CRITICAL ( example ) in DamageCustom.

Tf2 does it this way.

**Comment by robotboy655** [comment]
Yeah, figured as much. New functions will arrive with next Dev update.

**Comment by Kefta** [comment]
@robotboy655 https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/game/shared/takedamageinfo.h#L80 ?

**Comment by Kefta** [comment]
@robotboy655 Also, it seems that DamageBonus was just added to the 2013 codebase; it's nowhere in 2007 or 2009, I confused it with a DamageCustom parameter
