### ISSUE TITLE
Add maxcarry and flag keys to Bullet structure for game.AddAmmoType

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#534]
Would be much easier to manage player ammo limits this way instead of checking the limit in a firing/ammo box entity hook.

**Comment by Jvs34** [comment]
How would you handle the max ammo on already defined ammo types, such as the hl2 ones?

**Comment by robotboy655** [comment]
@Jvs34 ??? it's set to 9999 by default.

**Comment by Jvs34** [comment]
no shit? I know that, but what if someone wants to modify the max ammo on those?

**Comment by robotboy655** [comment]
This request has nothing to do with modifying default ammo types though, which is what confused me. Afaik most of them are tied to convars.

**Comment by Jvs34** [comment]
Alright I apologize if I jumped the gun.

**Comment by robotboy655** [comment]
I am really not sure about flags though, there are only two flags that I don't think will have any difference/effect at all.

**Comment by Kefta** [comment]
This is done! Thank Robot
