### ISSUE TITLE
Call hook on convar change

### ISSUE THREAD

**Issue by mooshbeef** [Facepunch/garrysmod-requests#535]
Currently the engine calls functions in the cvar library. This library can easily be merged into the hook library, which makes more sense as it is the central point of communication from the engine.
After looking at the code, I can see why it has been made seperate; to optimize callbacks to specific convars rather than calling all callbacks for every convar change. But you could still add a hook.Call in cvar.OnConVarChanged. (please don't use ConvarChanged instead of OnConvarChanged as a hookname)

**Comment by robotboy655** [comment]
What's wrong with current system exactly?

**Comment by neico** [comment]
Well he has a point though, currently you're required to use the cvars lib to add a callback, but it looks a bit out of place considering that most of the other stuff runs on the hook lib.

Making it more streamlined and such, and looking on the code in modules/convars.lua it basically does exactly what the hook lib is doing, just isolated from the rest...

**Comment by robotboy655** [comment]
The problem is that we already have the cvar lib and we can't just remove it.

**Comment by robotboy655** [comment]
And I'd really rather not add 10 ways of doing the same  thing.

**Comment by neico** [comment]
Well gmod obviously lacks a deprecation system, but that's been discussed already no?

And removing it is out of the question at least shortly after such a change.
But those functions could be easily modified to use hook.Add and hook.Remove to bridge over to the hook lib (aliasing, which is very common on deprecation processes)

**Comment by wiox** [comment]
Replacing the current system is a terrible idea. You're going to have:

1) Addons that rely on it
2) Addons that stop other addons' hooks being called

**Comment by robotboy655** [comment]
Yeah, the hook system is pretty terrible like that.
