### ISSUE TITLE
Ability to set an entity's dormancy

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#540]
SetDormant binding

**Comment by Python1320** [comment]
What's different between SetDormant and serverside SetNoDraw

**Comment by Kefta** [comment]
Updates IsDormant -- which is a binded function, and updates visibility for children ( particles, effects ).

**Comment by Python1320** [comment]
SetNoDraw serverside stops networking, which is pretty much the dormancy system. I can't check if it's exactly the SetDormant you're wanting though. Have you tried?

**Comment by Kefta** [comment]
If SetDormant isn't going to be added, then IsDormant should be overwritten to check for NoDraw then.

**Comment by wiox** [comment]
Don't break IsDormant ty

**Comment by xaviergmail** [comment]
`Entity:SetEFlags(EFL_DORMANT)` ...?

**Comment by Kefta** [comment]
Doesn't update on client: http://wiki.garrysmod.com/page/Enums/EFL

**Comment by Python1320** [comment]
```Python1320@both_print: Entity(570):IsDormant()
false
[EasyLua Python1320] false
Python1320@server: Entity(570):SetNoDraw(true)
Python1320@both_print: Entity(570):IsDormant()
false
[EasyLua Python1320] true
```

**Comment by xaviergmail** [comment]
`Entity is dormant, no updates to client` That means the entity won't be updated to the clients. I make extensive use of this, it works just as expected.

**Comment by Kefta** [comment]
Oh, I misread that. I thought it meant that the dormant state isn't updated on the client. Thank you!
