### ISSUE TITLE
Ability to get an ammo type's index by string

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#541]
GetPrimaryAmmoType will return the index of the current equipped ammo type. Would be nice to get any type's index.

**Comment by mcd1992** [comment]
+1 actually had to find a workaround for this. game.BuildAmmoTypes doesn't match the indexes being returned by GetPrimary/SecondaryAmmoType. The only way as of now to convert the numerical ammo id to its string id is to iterate over all weapons and call their Get*AmmoType() then compare it. If it matches then get wep.Primary.Ammo.

**Comment by robotboy655** [comment]
Yeah, I tried to add this a few months ago, but it wasn't as straightforward so I didn't bother to look into it more.

**Comment by Kefta** [comment]
For now, I guess I'll just give a bot a weapon with each ammo type on startup, loop through each one, then store it to a global table.

**Comment by robotboy655** [comment]
Pretty sure you can make a static table for default ammo IDs.

**Comment by robotboy655** [comment]
Will be added in the next Dev branch update.

**Comment by robotboy655** [comment]
Will be added in the next dev branch update.

**Comment by Kefta** [comment]
Thank you <3
