### ISSUE TITLE
Add ability to change string.Comma's sign

### ISSUE THREAD

**Issue by P4sca1** [Facepunch/garrysmod-requests#542]
Some languages, like german write 1.000 instead of 1,000.
So another argument to change the , to a . would be great! :)

**Comment by Kefta** [comment]
Should the optional argument be a Boolean for .'s or a string?

**Comment by P4sca1** [comment]
the argument should be optional. I think a boolean would be fine. true for .  and false for , 
It could be a string too where you could put for example a "p" and every , will be replaced with p but I dont think that it will make any sense.

**Comment by Kefta** [comment]
Fixed in https://github.com/garrynewman/garrysmod/pull/1021

**Comment by P4sca1** [comment]
Thanks! :+1:

**Comment by P4sca1** [comment]
Is there already a way to revert string.Comma? So for example youj have 1,000 and want to make 1000

**Comment by thegrb93** [comment]
string.gsub

**Comment by zerfgog** [comment]
@thegrb93 why process it twice? this is a valid complaint as both , and . are widely used
