### ISSUE TITLE
Add ismatrix

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#543]
Or isvmatrix, just needs to be done C++ side

**Comment by Nyaaaa** [comment]
Nice this seems interesting!
                                                                         
What exactly is is vmatrix?

**Comment by thegrb93** [comment]
A 4x4 matrix which usually is used to contain a 3x3 rotation matrix and 3x1 translation vector.

**Comment by Nyaaaa** [comment]
Okay nice one didn't know that thank you very much!

**Comment by robotboy655** [comment]
Will be added
