### ISSUE TITLE
weapons.OnLoaded as hook

### ISSUE THREAD

**Issue by Alig96** [Facepunch/garrysmod-requests#545]
Can we have http://wiki.garrysmod.com/page/weapons/OnLoaded called as a hook?

Same with say: http://wiki.garrysmod.com/page/scripted_ents/OnLoaded & http://wiki.garrysmod.com/page/GM/OnReloaded

Should be a quick & small change.

**Comment by robotboy655** [comment]
Why

**Comment by Alig96** [comment]
So I can hook into them without overriding the function? Most important one being OnReloaded. I've used it in my gamemode to reload data, but I thought I should be calling it as a hook rather than a overriding.

**Comment by robotboy655** [comment]
http://wiki.garrysmod.com/page/GM/OnReloaded is already a hook, the rest are internal functions, you are not supposed to "hook" onto them.
