### ISSUE TITLE
Include CS:GO's vaudio_celt

### ISSUE THREAD

**Issue by opeik** [Facepunch/garrysmod-requests#547]
As you probably already know, CS:GO made CELT it's default audio codec. It would be great if you could include the codec into Garry's Mod so servers can toggle what they want to use via sv_voicecodec.

**Comment by Gliby** [comment]
Yes please!

**Comment by TylerB260** [comment]
please

**Comment by GlenAnderson** [comment]
Garry's Mod NEEDS this. Bring some life to the project guys! +1000

This has been put off WAY too long :(

**Comment by meatspace** [comment]
yes pls

**Comment by robotboy655** [comment]
Closing as duplicate of #479 / #647
