### ISSUE TITLE
Add some lightmap related things

### ISSUE THREAD

**Issue by Jcw87** [Facepunch/garrysmod-requests#548]
~~Currently, mesh.TexCoord only accepts '0' for the stage value. I need stages '1' and '2' to render meshes with lightmaps. I'm also planning on using these coordinates with a custom shader.~~

I need a binding to IMatRenderContext::BindLightmapPage, so that the correct lightmap texture can be used.
~~To get the full mileage out of the lightmap coordinates, a binding to IMatRenderContext::BindLightmapTexture would likely be useful to someone. For example, someone might want to make a map loader for old games that used lightmaps (like quake).~~

I'm currently doing these things with my own binary module, but I would like to be able to drop the requirement for it, and this will be the first step toward that.

**Comment by Jcw87** [comment]
I just realized that my custom shader may end up needing another set of TexCoords, if my lightmap TexCoord re-use idea doesn't work out. So, stage '3' for mesh.TexCoord, if at all possible?

**Comment by Jcw87** [comment]
So apparently the mesh library uses more texcoord stages just fine, and the wiki is wrong. The issue I was having with that was actually due to my method of determining the lightmap page ID. I also just noticed that render.SetLightmapTexture already exists. So that just leaves IMatRenderContext::BindLightmapPage.

**Comment by Jcw87** [comment]
Due to the difficulties involved with getting the correct lightmap page IDs used by the engine for each surface, I've decided that I'm going to make my own lightmaps.... with blackjack... and hookers.

**Comment by robotboy655** [comment]
I'd appreciate if you'd correct the stuff you mention on the wiki,

**Comment by Jcw87** [comment]
I just changed the wiki page for mesh.TexCoord. I've noticed similar disclaimers about mesh library functions doing nothing, but I suspect that they work just fine, so long as the currently bound material supports it. Unfortunately, I have no idea what things like mesh.TangentS and mesh.TangentT would even do, or what shaders support them.

I feel like I should document my troubles with getting lightmap page IDs here, in case you decide that you can do something about it. When the engine allocates the lightmap textures, it stores the offset into the lightmap texture on every brush face, as well as a 'material sort ID'. I can get this data pretty easily using IVModelInfo::GetModel(1) + some custom headers. The engine then calls IMaterialSystem::GetSortInfo() to get a lookup table that will convert these sort IDs to lightmap page IDs. The problem is that the data written by GetSortInfo() changes as soon as any additional materials are loaded, thus making the engine's copy of the data the only valid way to do the conversion. Getting a pointer to that data is much more difficult, and would require some ugly sigscanning hack.
