### ISSUE TITLE
Replace serverside SelectWeapon with shared version

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#552]
https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/game/shared/basecombatcharacter_shared.cpp#L38

No more need to network to get a player to select a weapon! Also, SetActiveWeapon would need to be made shared as well to reflect this

**Comment by wiox** [comment]
This method appears to still need to be called serverside to work.

**Comment by Kefta** [comment]
Why is that? Iirc this is the function called when swapping weapons via the HUD in HL2

**Comment by wiox** [comment]
Yeah but it's a predicted function, you need to call it from both states (or just one if it's done purely serverside).

**Comment by Kefta** [comment]
I thought deploy automatically netoworked its results and prediction to both realms -- this function aside.

**Comment by wiox** [comment]
Weapon switching is purely up to the server. The only correct way to change your weapon is to send the weapon to change to in your user-command.

**Comment by Kefta** [comment]
Fair enough, thanks for the info

**Comment by Jvs34** [comment]
We have ittttt http://wiki.garrysmod.com/page/CUserCmd/SelectWeapon
