### ISSUE TITLE
Move sound errors to higher developer verbosity

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-requests#553]
Very annoying to get spam for these errors and they are impossible to prevent for the client if the server plays sounds the client doesn't have.

Failed to load sound "", file probably missing from disk/repository

**Comment by robotboy655** [comment]
Do we really have to go over this argument again? Errors should not be hidden, they should be fixed.

**Comment by thegrb93** [comment]
>they are impossible to prevent for the client if the server plays sounds the client doesn't have.

**Comment by Kefta** [comment]
Then that's the server's fault. Otherwise, the client can google the sound

**Comment by thegrb93** [comment]
E2, wire sound emitters, ACF engines, all allow playing user defined sounds and sounds even the server doesn't have can be played and used to spam consoles with errors.

**Comment by Kefta** [comment]
That's the addon's fault. They could at least file.Find the sound

**Comment by thegrb93** [comment]
But then the server needs to have sounds from every game installed or players won't be able to play their sounds from portal/hl2ep2/etc. The error doesn't help anything, it's only obtrusive and noisy. Why is there such a large defense for it?

**Comment by Kefta** [comment]
Why allow people to play sounds from games the server and many other clients don't have mounted? Also, the sound error is very commonly used to detect BASS, FastDL, and typo errors; if it's changed, most server owners/developers wouldn't know how to enable it again. I'm all for the decluttering of console print, but this is one that should stay. It would be nice if there were a timer for erroring the same missing sound again; maybe every 30 seconds?

**Comment by robotboy655** [comment]
Because it makes the error people expect to see when developing to suddenly go away.

The developer console is for DEVELOPERS, not for random clients.

**Comment by thegrb93** [comment]
@robotboy655 Yes I know it is for developers and it is hard to develop when the console gets filled up with sound errors.

**Comment by robotboy655** [comment]
You can easily filter them out with console filters ( con_* convars )

**Comment by thegrb93** [comment]
The filter works.
