### ISSUE TITLE
Rope limit

### ISSUE THREAD

**Issue by deinemudda32** [Facepunch/garrysmod-requests#554]
sbox_maxropes

**Comment by robotboy655** [comment]
k

**Comment by deinemudda32** [comment]
Was that an bad idea or why did this got the label "invalid"?

**Comment by robotboy655** [comment]
What is "sbox_maxropes" supposed to mean?

**Comment by deinemudda32** [comment]
I thought it would explain itself.
Everything has an limit, but ropes.
Ropes need a limit more as everything else as you can crash servers with it easily.

**Comment by robotboy655** [comment]
It's not the amount that allows you to crash the serves, its their usage.

**Comment by deinemudda32** [comment]
I know, but I hate the users spaming with it, so I would like to set the rope limit.

**Comment by robotboy655** [comment]
Well how about you make a proper request of what you want to be added and an explanation as to why it should be added.

**Comment by deinemudda32** [comment]
Fine...
