### ISSUE TITLE
player.GetByUserID(UserID)

### ISSUE THREAD

**Issue by 00875** [Facepunch/garrysmod-requests#557]
returns player entity given by an argument: 
```
for _,v in pairs(player.GetAll()) do
	print(player.GetByUserID(v:UserID()):Nick())
end
```
Will display all player nicknames

player.GetByID(id) returns player entity based on it's entity index
![2015-08-15_09-20_garry s mod](https://cloud.githubusercontent.com/assets/6339511/9287074/ec8b0624-432e-11e5-8373-33954b03786f.jpg)
![2015-08-15_09-21_garry s mod](https://cloud.githubusercontent.com/assets/6339511/9287081/0159921e-432f-11e5-9eca-0090c2d17fbd.jpg)

**Comment by robotboy655** [comment]
http://wiki.garrysmod.com/page/player/GetByID

It returns players by Connection ID, not Entity index.

**Comment by robotboy655** [comment]
Pretty sure this is what you want:
http://wiki.garrysmod.com/page/Global/Player

**Comment by 00875** [comment]
Big Thanks.
