### ISSUE TITLE
PlayerCanHearPlayersVoice optimizations

### ISSUE THREAD

**Issue by syl0r** [Facepunch/garrysmod-requests#559]
Currently the PlayerCanHearPlayersVoice calls once for every pair of players every few ticks/milliseconds. This could be optimized by only calling the hook for every currently speaking player. Since typically on a regular server only a fraction of the players are speaking this could improve efficiency of the hook by a lot.
The only issue that I can see is that when the player starts talking the hook might not have been called for that player yet, so as soon as a player starts talking, the hook has to be called for that player as well.

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/1087
