### ISSUE TITLE
Ability to multiply up speed in movement hooks

### ISSUE THREAD

**Issue by Bo98** [Facepunch/garrysmod-requests#562]
CMoveData:SetMaxClientSpeed is great for cases when you want to slow down a player but it does not work if you want to speed up a player as it is limited by the player's GetWalkSpeed/GetRunSpeed etc. I'm not sure how easy this is to implement but the only workaround I see is to almost rewrite movement with custom velocity calculations (and fight the constant clamping every time SetupMove is called) or to set ply:SetWalkSpeed or ply:SetRunSpeed which just causes conflicts because of how it is used to set the default speed.

Example conflict scenario when using ply:SetWalkSpeed:

> Player has walk speed 160.
> Addon doubles this speed temporarily (320).
> Player dies/switches class/does something that changes the default walk speed to 200.
> Addon no longer has double speed effect (walk speed is now 200 rather than 400).

**Comment by Bo98** [comment]
Turns out you can do it in the Move hook (rather than SetupMove) but at the cost of prediction errors.

**Comment by wiox** [comment]
You're doing it wrong. Show the code!

**Comment by Bo98** [comment]
```lua
hook.Add("Move", "testestst", function(ply, mv, usrcmd)
    local spd=mv:GetMaxSpeed() * 2
    mv:SetMaxSpeed(spd)
    mv:SetMaxClientSpeed(spd)
end)
```

**Comment by wiox** [comment]
Nothing seems wrong. Make sure you run it shared.

**Comment by Bo98** [comment]
Looks like I accidentally put it in the wrong file. Oops.
