### ISSUE TITLE
Give Gmod (Source) support for Metal on OS X

### ISSUE THREAD

**Issue by Jake3231** [Facepunch/garrysmod-requests#563]
Gmod, or many Source powered games, can be a bit choppy as performance goes, and I think it would be awesome to see the adoption of the Metal API in Source, or even Gmod.  I understand that Garry can't just change his game specifically, but It would be nice to see some improved performance on OS X through Metal.

**Comment by Noiwex** [comment]
Metal is just a fork of opengl. Garrysmod uses directx on windows and
wrapper in other cases. There's no point in making it use metal before
remaking how game works with video.

**Comment by Jake3231** [comment]
To be correct, you're saying that gmod doesn't use any form of OpenGL?  If so, then I think it could still benefit from Metal no matter what overhaul that would require.

**Comment by neico** [comment]
Not going to happen.

Besides, source2 will use vulkan, so the discussion about a apple specific one is redundant.
So you'd have to wait for gmod to release on source2.

PS: the wrapper @Noiwex talked about is here( there might be a more simple version in use depending on the exact engine version ): https://github.com/ValveSoftware/ToGL
this one is used whenever there's no DX available...

**Comment by Jake3231** [comment]
Okay. With Gmod on Source2, it will use Vulcan. Apple is showing no evidence of supporting Vulcan and only Metal...  Does that mean that Source games will no longer work on Mac?  I also hope that Source 2 will just fix all of the performance issues if not...  I see why Metal would be hard to implement...

**Comment by Bo98** [comment]
OpenGL will still be supported in Source 2 as Vulkan is a very new technology and not widely available yet.

It's not the best of situations for Apple when they've spent what would probably be a while on Metal and Vulkan shows up and almost makes it obsolete. We'll see if they decide to implement Vulkan or not when it becomes more available. It will probably be a while before GMod is on Source 2 so there will be time.

**Comment by Jake3231** [comment]
That's good to know.  At least Gmod will still work on OS X either way. My only other question would be regarding Metal's improvement over OpenGL. Doesn't Metal replace, or lay over, OpenGl. So maybe OpenGL requests are processed using Metal's efficiency and performance?  Sorry that I'm not up to date on how all this works...

**Comment by Noiwex** [comment]
This doesn't go to anywhere useful, close the ticket.

**Comment by Jake3231** [comment]
Okay. If Gmod won't support Metal (and can't), I will close the ticket.  Thanks for the feedback on this.
