### ISSUE TITLE
sv_allowcslua default enabled, in Sandbox.

### ISSUE THREAD

**Issue by gamerpaddy** [Facepunch/garrysmod-requests#564]
Hello, since theres no advantage against others having sv_allowcslua enabled on sandbox, could it be enabled by default?
Its useful for people having stuff like: Build helpers, Tool Shortcuts, Holoeditors etc.

Server owners can still turn it off, but as default, it should be enabled.

A thread about sv_allowcslua in sandbox and what other people think about it:

http://facepunch.com/showthread.php?t=1483770&p=48592439#post48592439

**Comment by neico** [comment]
It's a security thing, you'd want to have your server the most secure from the get go, and not have to bother with switching of different aspects...

**Comment by thegrb93** [comment]
It doesn't matter whether or not it is on or off by default. Ask the server owner to change it if you need it.
