### ISSUE TITLE
Vector:ClosestPos( tableofpos )

### ISSUE THREAD

**Issue by Kemerd** [Facepunch/garrysmod-requests#566]
This is just a little "neat-o" function that might make someone's life easier. 

Vector:ClosestPos( tableofpos )

Example:
local AllPlayerPositions = {}

for _, v in pairs( player.GetAll() ) do
      table.insert( AllPlayerPositions, v:GetPos() );
end

print( LocalPlayer:ClosestPos( AllPlayerPositions ) )

"Prints the closest player's position."

Right now I'm using a function similar to this, but it'd be cool if it could be hard-coded into garrysmod.

function ClosestPos( pos, tableofpos )
	local list = { }
	for _, v in pairs( tableofpos ) do
		local dis = pos:DistToSqr( v*v )
		table.insert( list, dis );
	end
	math.min( list )
end

**Comment by Kefta** [comment]
Eh, I don't really see a use for this being embedded in the C++ environment

**Comment by neico** [comment]
Please use the markdown syntax highlighting, this is horrible to read... (you can just use the "lua" one, still works better then no highlight at all)

**Comment by robotboy655** [comment]
I don't see the point of this either, it's too easy to implement yourself if you need it.
