### ISSUE TITLE
trying to remove server entity on client

### ISSUE THREAD

**Issue by deinemudda32** [Facepunch/garrysmod-requests#568]
It would be helpful to display where this error happens.
Like a real lua error. It sucks you have to search 500 files just to find 1 little error.

**Comment by cactusadmin** [comment]
been having this issue alot aswell and would like to see it fixed to were I know what is causing it to happen

**Comment by Alf21** [comment]
Yea, me too. Seems like it happens too if you wanna try to remove an entity serverside

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/61309566-1ad04f00-a7fb-11e9-8fae-fb3941659d9a.png)

**Comment by swahealey** [comment]
How was this fixed?
