### ISSUE TITLE
Reduce echo and soundscape volume on gm_construct

### ISSUE THREAD

**Issue by ghost** [Facepunch/garrysmod-requests#569]
The echo on gm_construct is a little much in my opinion. When the sound of switching weapons echoes so much throughout the map, it throws me off a little.
Also, I find the wind/bird sounds a little too frequent and loud.

**Comment by robotboy655** [comment]
I am pretty sure the echo is auto generated on compile and is not changeable.

**Comment by imp0se** [comment]
Oh? Guess I didn't notice it as much before then.
Either way, could the soundscape volume still be turned down a bit?

**Comment by bellum128** [comment]
I agree, the soundscapes are somewhat trying on other maps as well, I kind of wish they wern't fixed for multiplayer. Would it be possible to add a client variable to disable them/change their volume?

**Comment by robotboy655** [comment]
The soundscape is already pretty quiet as is (10% to 25% of its full volume), especially compared to gunfire, `volume_sfx` should help you lower both without affecting voice chat.
