### ISSUE TITLE
Path generation for other entities than NextBots

### ISSUE THREAD

**Issue by fruitwasp** [Facepunch/garrysmod-requests#570]
Currently, there's only a way to compute paths with navmesh from a NextBot to a certain location (see wiki link). The ability to create paths for vehicles (and other entities) would come in handy.

Wiki link: http://wiki.garrysmod.com/page/PathFollower/Compute

**Comment by mcd1992** [comment]
+1

Had a need for this at one point. The issue with implementing this though is the source engine itself needs a entity to save parent navareas to. That is if I'm reading this correctly. Garry seems to of done this with the PathFollower class but to get a function like navmesh.ComputePath would mean a PathFollower would have to be created and allowed to follow the path generating the CNavArea list as it went. It just feels weird. I hope I'm wrong but from what I'm thinking its better to just wrap a NextBot/PathFollower yourself to calculate paths. 

https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/nav_pathfind.h#L94

**Comment by robotboy655** [comment]
Honestly, it should be possible for you to write your own path generation with the navmesh functions I added.

**Comment by fruitwasp** [comment]
You mean the ```CNavArea``` functions, right?

**Comment by robotboy655** [comment]
And http://wiki.garrysmod.com/page/Category:navmesh
