### ISSUE TITLE
Gravity Gun cheat convar flag removal

### ISSUE THREAD

**Issue by slayer3032** [Facepunch/garrysmod-requests#571]
Would it be possible to get the cheat flag removed from the gravgun convars since Gmod isn't HL2 singleplayer? 
>"physcannon_minforce" = "700"
> game cheat replicated
>"physcannon_maxforce" = "1500"
> game cheat replicated
>"physcannon_maxmass" = "1500" ( def. "250" )
> game cheat replicated
>"physcannon_tracelength" = "100" ( def. "250" )
> game cheat replicated
>"physcannon_chargetime" = "2"
> game cheat replicated
>"physcannon_pullforce" = "10000" ( def. "4000" )
> game cheat replicated
>"physcannon_cone" = "0.97"
> game cheat replicated
>"physcannon_ball_cone" = "0.997"
> game cheat replicated

We have these wonderful physgun convars which are quite useful but we can't modify the gravgun similarly.
>"physgun_maxAngular" = "5000"
> game
>"physgun_maxAngularDamping" = "10000"
> game
>"physgun_maxSpeed" = "5000"
> game
>"physgun_maxSpeedDamping" = "10000"
> game
>"physgun_DampingFactor" = "0.8"
> game
>"physgun_teleportDistance" = "0"
> game
>"physgun_timeToArrive" = "0.05"
> game
>"physgun_timeToArriveRagdoll" = "0.1"
> game

**Comment by Revenge282** [comment]
+1

**Comment by waut3r** [comment]
+1: stuff like this being cheat protected is not necessary.

**Comment by Mechtecs** [comment]
+1 this is fuc**** GARRYS MOD we are SUPPOSED to do that!

**Comment by robotboy655** [comment]
Should be in Dev soon

**Comment by Mechtecs** [comment]
Thanks :+1:
