### ISSUE TITLE
Support for `alias` in PlayerBindPress, or a general method of finding an alias' meaning

### ISSUE THREAD

**Issue by bmwalters** [Facepunch/garrysmod-requests#573]
Currently, PlayerBindPress is not effective for detecting binds because for alias, we cannot verify what that alias represents. Here's a good test:

``` lua
if not CLIENT then return end

function GM:PlayerBindPress(ply, bind, pressed)
    if bind == "invprev" then
        print("We would like to choose the previous weapon.")
    end
end
```

Now run `invprev` in console. You will have the message printed.
Next, run `alias inventoryprevious invprev` in console.
Now run `inventoryprevious` in console. The message will not be printed.

**Comment by Mista-Tea** [comment]
+1, encountered issues before because of having no (known) way of translating alias back to real ccmd.

**Comment by Z0mbine** [comment]
Yes please, would be amazing to have this

**Comment by xaviergmail** [comment]
This is a must

**Comment by robotboy655** [comment]
Ok, please stop spamming.

**Comment by SwadicalRag** [comment]
Sorry

**Comment by Authorjames** [comment]
Ok, will do.

**Comment by Velkon** [comment]
Plz add dis!

**Comment by danielga** [comment]
My deepest sorries.

**Comment by robotboy655** [comment]
:weary:

**Comment by robotboy655** [comment]
Added `input.TranslateAlias( str )` - translates "alias test lastinv" into "lastinv" when given "test". Returns nothing if no alias was found.

**Comment by thegrb93** [comment]
Will it translate commands?

aliascommand 1 2 3 -> command 1 2 3

Also is it a full translation or just a single layer? e.g. alias mycommand1 mycommand; alias mycommand2 mycommand1
mycommand2 1 2 3 -> mycommand 1 2 3

**Comment by robotboy655** [comment]
You can join Dev and see exactly how it works for yourself.
