### ISSUE TITLE
A method of hiding the CHudWeaponSelection panel without blocking weapon switching

### ISSUE THREAD

**Issue by zerfgog** [Facepunch/garrysmod-requests#574]
Currently, gamemode authors wishing to create a custom weapon selection panel have to use quite hacky methods for creating a custom weapon switch panel.
The most used method today is dipping into such hooks as PlayerBindPress to detect the switch concommands.
This is incredibly hacky and should not be necessary to accomplish this.

**Comment by robotboy655** [comment]
In what way this will be useful and in what way current methods are "hacky"?

If you hide the panel, you still have no way of determining which weapon is next, which is previous, which one is currently selected, etc.

The way it is currently done is the proper way.

**Comment by zerfgog** [comment]
The way that it is currently useful is for gamemodes which wish to create their own weapon selection panel, such as TTT.
The reason the current method is hacky is because the default works with the alias command, while PlayerBindPress does not detect alias and therefore cannot be relied on to accurately judge when a weapon should be switched.
The PlayerSwitchWeapon hook would instead be perfect for this, but it is sadly disabled by hiding the default panel.

**Comment by zerfgog** [comment]
Fair enough. Then, would the correct method be granting us a "HUDDrawWeaponSelection" as we are given with PickupHistory?

**Comment by robotboy655** [comment]
The difference between PickupHistory is that you cannot detect/implement it purely in GLua, where as with weapon selection you can.

Pickup history is still all in Lua, the only thing that is from C++ there is is a hook that is called when a new pickup was added which can't really be done/detected with GLua, the weapon selection alternative would be Player:GetWeapons().
