### ISSUE TITLE
[HAMMER UPDATE][VALVE] Add Propper to Gmod's Directoy, and here's why:

### ISSUE THREAD

**Issue by EthanTheGreat** [Facepunch/garrysmod-requests#575]
This amazing addon for the hammer editor lacks (updates). Attempting to get this to work, requires the DLL's inside of Source 2007 SDK (CREATE MOD) code.

Why would this be useful?
Seeing at though, our hammer is strictly usable for Gmod's Maps,

Mappers would be *great-ful* to have this addon in Hammer.
Creating Models from VMF's is the future. Hammer should have this already by default!!!!

Please consider using this, the code is posted below.
https://developer.valvesoftware.com/wiki/Propper

I'm asking, because this could essentially make maps more useful (In model forum.... Infinite maps would be easier to accomplish, in my opinion if we converted each map in sections (models) and accomplish everything on the client. Just a theory, I have not yet found concrete facts to support it, but I believe source is ready to move onto it's next stage. Waiting for Source 2 is a dream that everyone has, but I think Garry's Mod is already on the Source '2' xD

**Comment by Velkon** [comment]
no

**Comment by EthanTheGreat** [comment]
What do you mean no?

This is important for development...
Instead of just saying no, tell me why you think NOT?

**Comment by kklouzal** [comment]
I've used this before, its extremely fast and simple to create somewhat aesthetically pleasing .mdl files. I do remember when the whole hammer fiasco happened a year or so back propper became EXTREMELY hard to get working requiring you to use the buggy source sdk base 2007 workaround.

:+1:  add it, wont happen though. :(

**Comment by robotboy655** [comment]
No.

By your logic, we should be adding every "useful" tool because it's useful.
Especially considering all the shit needed to be added to make it work.

Besides, you can't just add someone else's work and essentially sell it on Steam.
