### ISSUE TITLE
disable downloading workshop addons from servers via concommand

### ISSUE THREAD

**Issue by deinemudda32** [Facepunch/garrysmod-requests#576]
I would like to see a console command which disables downloading workshop addons from servers similiar to cl_allowdownload 0

**Comment by zerfgog** [comment]
cl_downloadfilter mapsonly

**Comment by Kefta** [comment]
@zerfgog But then you can't download any FastDL stuff

**Comment by Velkon** [comment]
>Expecting good workshop support for gmod

**Comment by zerfgog** [comment]
In what case would you like FastDL things but not workshop things?

**Comment by Kefta** [comment]
@zerfgog When I want to get server resources but not keep getting shitty M9K addons
