### ISSUE TITLE
"Purge Workshop" option(Delete .GMA Files of unsubscribed addons to prevent unnecessary memory usage)

### ISSUE THREAD

**Issue by Taberone** [Facepunch/garrysmod-requests#577]
Can there be a "Purge Workshop" option that deletes the .GMA files of unsubscribed addons? One issue with Gmod is that all those .GMA files from addons subscribed slowly "stack up" over and eventually start taking dozens of gigabytes on my hard drive.

A "Purge Workshop" button would prevent that by deleting the .GMA files of every single currently unsubscribed addon. Going into my files and deleting every single .GMA file at once is a bit impractical, seeing as how Gmod now has to download all my workshop addons all over again.

**Comment by robotboy655** [comment]
![image](http://i.imgur.com/VBsyIxS.png)
![image](https://cloud.githubusercontent.com/assets/3299036/10428115/c6fb381a-70f7-11e5-9954-0280ac971091.png)

This is what it will look like. The first red block will be printed every time, the second if from the console command ```menu_cleanupgmas```.

**Comment by meepdarknessmeep** [comment]
Make it a button!

**Comment by Taberone** [comment]
Thank you

**Comment by Taberone** [comment]
Menu_cleanupgmas works beautifully and has been doing that for a long while, but the only problem with it now is that it doesn't seem to take other users into account. The console mentions a bunch of "unsubscribed" addons that actually seem to be subscribed addons from a sibling's account.

**Comment by robotboy655** [comment]
Well naturally it cannot detect someone else's subscriptions.

**Comment by Kefta** [comment]
Can you store each user's cached subscriptions in a text file in the garrysmod folder? Or maybe just the user's SteamID and you can check every startup?

**Comment by robotboy655** [comment]
That sounds really unnecessary and unreliable. This is a non issue. This is the literal case of "1 person has a very minor problem".
