### ISSUE TITLE
Hook for when the player is fully loaded and all functions are available.

### ISSUE THREAD

**Issue by DaaOtt** [Facepunch/garrysmod-requests#578]
It'd be nice to have a hook for when a player is fully spawned in and all functions are available so every addon doesn't have to have their own timer to check if a player is loaded after PlayerInitialSpawn.

**Comment by robotboy655** [comment]
Uh, it is PlayerInitialSpawn?

**Comment by DaaOtt** [comment]
[](http://i.imgur.com/NeBnrEX.png)

**Comment by robotboy655** [comment]
That's because that's the default player model? It means that Entity.SetModel was not yet called on the player at all.

**Comment by DaaOtt** [comment]
You and I both know it's not just GetModel.

**Comment by robotboy655** [comment]
Give examples? I honestly don't know any.

**Comment by thegrb93** [comment]
The only issue I'm having is with SetNW* but that might be unrelated. I think all of the PlayerInitialSpawn issues that used to exist have been fixed.

**Comment by Kefta** [comment]
SetupMove is the hook you want. It starts running as soon as all functions are avaliabke

**Comment by zerfgog** [comment]
uhhh kefta setupmove is called like every player tick

**Comment by Kefta** [comment]
@zerfgog When it's FIRST called.

**Comment by Kefta** [comment]
SetupMove will not run before all functions are avalible
