### ISSUE TITLE
Showing only disabled subscriptions in addon menu?

### ISSUE THREAD

**Issue by akos96** [Facepunch/garrysmod-requests#58]
It's really hard to sort out the addons that I want to enable or I don't. I have to watch all pages of addons to find the disabled ones. Especially for people with 100+ addons it's more like a torture. Please add a sub-group of disabled addons.

**Comment by robotboy655** [comment]
I feel like this is unnecessary since you can now search addons by name and show addons by specific tag, as well as select and enable/disable multiple addons.
