### ISSUE TITLE
GWEN

### ISSUE THREAD

**Issue by kklouzal** [Facepunch/garrysmod-requests#583]
https://github.com/garrynewman/GWEN

GWEN still has many outstanding bugs, many of which have been brought up on it's issue tracker yet never addressed. I fear most in the community do not know the complete source code driving the backend of DERMA is up on GitHub.

Why is GWEN hiding over there on gerrynewman instead of in the light on Facepunch where it will have tremendous amounts of exposure within our GitHub community?

I urge whoever has the power to make this happen to seriously consider the idea. The entire goal of even having these things here is in hopes of a pooled community effort to better the project, so give it the maximum exposure possible!

**Comment by zerfgog** [comment]
what

**Comment by iSnipeu** [comment]
The main garrysmod repo isn't on the Facepunch group either, if anything should be moved it'd be that. Regardless I don't think moving it is going to impact on how active it is.

**Comment by robotboy655** [comment]
GMod doesn't use GWEN as far as I can tell, only the .png skin.
