### ISSUE TITLE
Parallel FastDL downloads

### ISSUE THREAD

**Issue by immibis** [Facepunch/garrysmod-requests#586]
We've all had experiences where we've tried to join a server and had to wait for several thousand file downloads.

It appears the download time is dominated by round-trip time, at least when you have several thousand small files - not bandwidth.

So why not download several files at once, when they're under a certain size?

**Comment by willox** [comment]
When I tried this it provided surprisingly little benefit. If you want your server content to download faster just use the Workshop.

**Comment by immibis** [comment]
That is indeed surprising.

It's not a matter of me wanting my server content to download faster, though, it's a matter of me wanting to download content from servers faster as a client. Obviously I can't force servers to use the workshop.

It's noteworthy that using the workshop is inconvenient for a server owner, compared to FastDL, and FastDL is inconvenient compared to normal downloading. And server owners are lazy.

Was I at least correct in guessing that each file requires a round trip?
