### ISSUE TITLE
Add GetDefaultAnimSpeed patch to activity playing and SequenceDuration

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#587]
GetDefaultAnimSpeed is a base entity function that scales the rate at which a sequence is played, and thus its speed. This is used a lot in TF2, which can most clearly be modelled by the sentry gun animation speed when you hit it with a wrench. This would be nice to have attached to players and SWEPs for making activities condensed or elongated enough to fit a certain time.

**Comment by robotboy655** [comment]
http://wiki.garrysmod.com/page/Entity/SetPlaybackRate ?

**Comment by Kefta** [comment]
@robotboy655 Didn't know that alias existed. Thanks!
