### ISSUE TITLE
Weapon.GetViewModel accessor

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#588]
This method returns the view model string of the weapon; useful for C++ weapons that don't have the szViewModel element exposed. This is a default accessor in basecombatweapon

**Comment by robotboy655** [comment]
http://wiki.garrysmod.com/page/Player/GetViewModel :GetModel()?

**Comment by Kefta** [comment]
That only works if the weapon is active; having this might be able to fix this issue in Lua: https://github.com/Facepunch/garrysmod-issues/issues/2278

However, if garrysmod-issues:#2278 is fixed, then this isn't needed

**Comment by robotboy655** [comment]
Will be added.
