### ISSUE TITLE
Make releases on the main git repo when a gmod update comes out

### ISSUE THREAD

**Issue by meepdarknessmeep** [Facepunch/garrysmod-requests#589]
Right now we have no versioning or any way to look back at each version of gmod to see the changes.

**Comment by willox** [comment]
or tags

**Comment by meepdarknessmeep** [comment]
Or tags

**Comment by HDG-MrDeeJay** [comment]
what is that button in the top right corner of your game when you start it?

**Comment by Velkon** [comment]
You mean the main menu?

**Comment by meepdarknessmeep** [comment]
Something not related at all to this request?

**Comment by HDG-MrDeeJay** [comment]
You want to look at old versions of gmod and see the changes.

Garry or whoever releases update notes, and that button links to that.

Unless you are doing a shit job at describing your issue, I don't see anything else you need

**Comment by willox** [comment]
you can use git to automatically find when changes to certain lines of code were made, this would allow us to associate those with different versions of the game

**Comment by HDG-MrDeeJay** [comment]
^

**Comment by meepdarknessmeep** [comment]
deejay i don't think you understand

**Comment by HDG-MrDeeJay** [comment]
>we have no versioning
Incorrect, there are several means of versioning.
>or any way to look back at each version of gmod
Incorrect, git
>to see the changes.
git

What am I not understanding?

**Comment by willox** [comment]
How long does it take you to find the git commit that was shipped with the 15.03.09 update? Too long.

This would fix that.

**Comment by zerfgog** [comment]
deejay you assball he means tags in the repository as milestones when each update was released, allowing us to find between which two shipped updates a lua file was updated

**Comment by Kefta** [comment]
or tags

**Comment by willox** [comment]
it'll help find the errors you made fast next time :zap:

**Comment by Kefta** [comment]
Dev branch testing at its finest

**Comment by zerfgog** [comment]
@Kefta :zap: x*2* (list)
