### ISSUE TITLE
Add predicted_viewmodel.Set/GetIndex

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#590]
Missing modifier/accessor for viewmodels. Currently need it for overlaying multiple viewmodels on a player.

**Comment by Jvs34** [comment]
Why would you need to set the index? Also we already have the Get http://wiki.garrysmod.com/page/Entity/ViewModelIndex

**Comment by Kefta** [comment]
So GetViewModel(1) works. I also believe the engine uses indexed viewmodels for prediction

**Comment by Jvs34** [comment]
Could you please try to explain where you're getting at already? I've done work with multiple viewmodels in the past and I can help.

**Comment by Kefta** [comment]
I'm trying to set the index so that using GetViewModel(1) will return the second viewmodel.

**Comment by Jvs34** [comment]
Um what? That IS the second viewmodel, GetViewModel( 0 or nil ) returns the first viewmodel.
1 and 2 are respectively the second and third viewmodels.

**Comment by Jvs34** [comment]
The second and third viewmodels are usually never set up properly because they're not used, you have to use this function to initialize them.

http://wiki.garrysmod.com/page/Entity/SetWeaponModel

**Comment by Kefta** [comment]
So the second and third viewmodels are already valid entities that just need a model?

**Comment by Jvs34** [comment]
Yes, the only problem with SetWeaponModel is that you can't set the Weapon to NULL, which is usually what you should do after you stop using the extra viewmodel ( and also what happens internally anyway )

**Comment by Jvs34** [comment]
That however is a bug with the function, I'll report that.

**Comment by Kefta** [comment]
Thank you! :+1:
