### ISSUE TITLE
Crosshair Ammunition Meters

### ISSUE THREAD

**Issue by Timtronic125** [Facepunch/garrysmod-requests#591]
One of the main HUD elements in HL2 was the ammunition meters bordering the crosshair, a simple but important feature to the HUD.

**Comment by thegrb93** [comment]
It didn't exist in hl2 when garrysmod was made and the devs didn't want to add it afterwards so idk. Maybe you can get someone to make a lua script that does this.

**Comment by Jvs34** [comment]
It actually is still in the game, however garry disabled it on purpose, as there is still a convar for it but it does nothing.

Maybe @robotboy655 could enable the HUD element and change it so hud_quickinfo enables when you set the convar to 2 or 3 or some other shit, so it doesn't accidentally enable for the whole playerbase.

In the worst case someone can remake it with Lua.

**Comment by robotboy655** [comment]
Added this feature back, its disabled by default and won't save across sessions.
