### ISSUE TITLE
sbox_maxcameras

### ISSUE THREAD

**Issue by deinemudda32** [Facepunch/garrysmod-requests#592]
There is no limitation for cameras.
I would suggest to add one.

**Comment by robotboy655** [comment]
Why do you people have the need to restrict everything

**Comment by deinemudda32** [comment]
We have to, we dont want to.

**Comment by thegrb93** [comment]
Because unlimited of anything crashes the server

**Comment by immibis** [comment]
@robotboy655 If restricting things is bad, then why do all the other `sbox_max` convars exist?

**Comment by robotboy655** [comment]
This was added a long while ago.
