### ISSUE TITLE
Add a more descriptive error to font creation failure

### ISSUE THREAD

**Issue by Mista-Tea** [Facepunch/garrysmod-requests#593]
Could we get a more descriptive reason when clients fail to create a font?

This is what it is currently:
```
[<Name>|<Index>|<SteamID>] Lua Error:
There was an error creating the font!
```

If the name of the font (and possibly a stack trace if it's not too intensive on the client), it would be far more useful. I don't know whether it's currently using either Error() or ErrorNoHalt(), but if it's the former we could just use error() to get something like:
```
[<Name>|<Index>|<SteamID>] Lua Error:

[ERROR] Failed to create the "Example" font!
  1. error - [C]:-1
   2. unknown - addons/some/random/addon/file.lua:15
```
Or just add the font name to the current error:
```
[<Name>|<Index>|<SteamID>] Lua Error:
There was an error creating the "Example" font!
```

Right now it doesn't look like we have any way of knowing which font is erroring or where it is erroring, just that one is. So even just the name would at least let us search around and know if it's our code or someone else's causing the issue.

**Comment by robotboy655** [comment]
Added the font name to the error.
