### ISSUE TITLE
Add Entity.GetLocalVelocity

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#596]
We have the accessor, just not the modifier for some reason.

**Comment by Jvs34** [comment]
Fun fact, GetLocalVelocity is actually returned by Entity:GetAbsVelocity

The naming is wrong.

**Comment by Jvs34** [comment]
In fact the only difference from Entity:SetAbsVelocity and SetLocalVelocity I can see is that SetLocalVelocity actually clamps the speed you pass if it's too high, SetAbsVelocity seems to set it regardless.

**Comment by robotboy655** [comment]
@Jvs34 is pretty much corrent, Entity.SetLocalVelocity is the same as Entity.SetAbsVelocity, the only difference is that SetLocalVelocity clamps the velocity, while SetAbsVelocity doesn't. Consequently, Entity.GetAbsVelocity already returns the local velocity as it is, so there's literally no need to Entity.GetLocalVelocity.

**Comment by Kefta** [comment]
Thanks!
