### ISSUE TITLE
Timescale and SetLaggedMovementValue

### ISSUE THREAD

**Issue by Matspyder51** [Facepunch/garrysmod-requests#598]
Hey,
I have found on the Wiki the possibility to change the "Timescale" only for one player with the function "SetLaggedMovementValue" but it's only work on Player, and I ask you if you can do that for all entities, for exemplen, I wan't make move players and entity very slowly around a player, but not for all the server, and actually, I cannot do that

Thank before for your answers, and sorry for my bad English but I'm French.

**Comment by robotboy655** [comment]
No.
