### ISSUE TITLE
include function return value of file

### ISSUE THREAD

**Issue by mechanicalmind** [Facepunch/garrysmod-requests#602]
The include function should return the value returned by the file. This is common practice in regular Lua.

multiply.lua
````lua
return function (a, b) return a * b end
````

init.lua
````
multiply = include("multiply.lua")
print(multiply(2, 5))
````

**Comment by Kefta** [comment]
This is tied with the outdated module behaviour as well

**Comment by mechanicalmind** [comment]
I'm not sure what you mean by that.

**Comment by robotboy655** [comment]
Duplicate of #393
