### ISSUE TITLE
util.Decal Trace Filter

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#604]
Add trace filter to util.Decal to prevent it decaling on a specified entity

**Comment by aStonedPenguin** [comment]
util

**Comment by zerfgog** [comment]
util

**Comment by robotboy655** [comment]
4th argument is now an entity to ignore

**Comment by bigdogmat** [comment]
Is the 4th argument not already used?

**Comment by robotboy655** [comment]
I don't know why @willox put it on the wiki, but I just looked into it and util.Decal never had a 4th argument.

**Comment by Kefta** [comment]
That explains a lot. And thank you!

**Comment by robotboy655** [comment]
I can make it accept tables, but I do not see a reason for it

**Comment by Kefta** [comment]
Say if you don't want a decal from a knife hitting any of the owner's teammates -- it basically replicates the same behaviour as the actual swing trace.

**Comment by robotboy655** [comment]
Done
