### ISSUE TITLE
PlaybackRate does not affect players' gestures

### ISSUE THREAD

**Issue by waut3r** [Facepunch/garrysmod-requests#607]
I got rid of the PlaybackRate function in the base gamemode's animation.lua and messed with the PlaybackRate in my SWEP to see if I could modify how fast the reload gesture plays. I could successfully change the playback rate of the player's animations outside of restarted gestures, but not the gestures themselves. Could we get a function to modify the speed of gestures directly? As it stands there's no way to do them even when modifying the speed of the player in its entirety.

**Comment by Jvs34** [comment]
Misleading title, PlaybackRate does work on players, just not gestures because they're on a different system like the CBaseAnimatingOverlay functions that @robotboy655 added recently http://wiki.garrysmod.com/page/BaseAnimatingOverlay

**Comment by robotboy655** [comment]
Basically is fulfilled by https://github.com/Facepunch/garrysmod-requests/issues/1504
