### ISSUE TITLE
Ability clientside SetModel to player

### ISSUE THREAD

**Issue by oxplayru** [Facepunch/garrysmod-requests#613]
It would be useful ability to set custom clientside playermodel(fallback) if player disabled content download from server.

**Comment by fruitwasp** [comment]
+1

**Comment by kem008** [comment]
+1

**Comment by fruitwasp** [comment]
calling `Player.SetModel` in [UpdateAnimation](http://wiki.garrysmod.com/page/GM/UpdateAnimation) works on the client.
