### ISSUE TITLE
Detect gmod language in loading URL

### ISSUE THREAD

**Issue by AlexALX** [Facepunch/garrysmod-requests#614]
Is there way to add new parameter to loading URL what will have gmod language? So we can display page text depend on player language without doing workarounds (like after first connect store language in database and all next connections check if it exists in database).

**Comment by neico** [comment]
Could be monitored via #104

**Comment by robotboy655** [comment]
Passed to the GameDetails function.
`function GameDetails( servername, serverurl, mapname, maxplayers, steamid, gamemode, volume, lang )`
