### ISSUE TITLE
Custom 'Map is missing' disconnect message

### ISSUE THREAD

**Issue by fruitwasp** [Facepunch/garrysmod-requests#615]
The ability to overwrite the default 'Map is missing' message on disconnect would come in handy. A hook which returns the message perhaps?

**Comment by robotboy655** [comment]
1) I don't see much sense in this
2) It's pretty much impossible since at that point, you isn't actually connected to the server yet, meaning Lua and stuff, is not initialized.

**Comment by TheEMP** [comment]
Or perhaps a convar the server could set? It actually makes a ton of sense and would be a great way for server owners to inform players where they can find the map. Instead of just telling them its missing.

**Comment by zerfgog** [comment]
Why aren't you providing the map to the client in the first place?

**Comment by TheEMP** [comment]
It's possible for the client to be unable to download for what ever reason, that or they have downloads completely disabled.

**Comment by fruitwasp** [comment]
I do supply it to the client, but somehow some get kicked for missing map

**Comment by kalis0x** [comment]
@fruitwasp then you're not doing it right??????
