### ISSUE TITLE
Make a main menu button to delete all GMA's

### ISSUE THREAD

**Issue by Mka0207** [Facepunch/garrysmod-requests#616]
Alright so as you know when you join a server, especially a custom one, you download content hosted on that server. However after joining multiple Garry's mod servers you will start to accumulate more content stored in the game's directory. This can be a very bad thing as it causes .gma's downloaded to stack over time and produce huge caches of other wised unused content. As well as causing client side problems on other servers that don't particularly host those .gma's.

So what I am requesting is a simple button that gets added to the main menu or somewhere convenient that inexperienced players or developers can use to clean their Garry's mod with the click of a button. I would also like to recommend adding a fail safe which would keep track of all .gma's file size, date and total size of content in the garrysmod/downloads/server folder. Which would be used to delete old dated content and it can't go over an optional (1GB) range. I know "menu_cleanupgmas" was added but it only cleans unsubscribed .gma's in the garrysmod/addons folder. Having this feature would be very beneficial to developers as well.

I hope the Garry's mod development team takes this request.

Thanks for your time!

**Comment by rtm516** [comment]
This is a great idea because i have hundreds of .gma's that I'm not subbed to and they just fill my hard drive

**Comment by DrVrej** [comment]
+1

**Comment by kem008** [comment]
Good idea but the function is disable all then you can delete all addons :D

**Comment by originalwhitestar** [comment]
ehh, normally gmod checks already on boot for GMAs wich arent used anymore, and removes them.

Neutral for me.

**Comment by uRandomAlex** [comment]
@originalwhitestar GMOD don't checks for .GMA's in cache folder (there goes all Workshop downloads user is not subscribed to).

**Comment by robotboy655** [comment]
@uRandomAlex It does.

**Comment by robotboy655** [comment]
The recent changes to the workshop system should make this no longer necessary. Files from servers should get cleared after 2 weeks of not using them.
