### ISSUE TITLE
Beef up Text Entries

### ISSUE THREAD

**Issue by Pugsworth** [Facepunch/garrysmod-requests#619]
There are some much needed features for Text Entries that many would benefit greatly from.
1. Read only
   - The text in the text entry can only be changed via lua (SetText/Value)
   - no paste/insert/cut support (cut could just copy)
2. Disable the right click menu
   - not super important, but would be beneficial in some circumstances
3. Placeholder text
   - should speak for itself, simply text overlayed on until the box contains text

While Read Only can partially be done in lua, it requires hacks that might not work 100% all the time.

Placeholder text can be added in lua pretty easily, so that can just be implemented in the DTextEntry or custom elements that inherit from TextEntry, but would also be great with internal support.

**Comment by notcake** [comment]
These things make me sad:
- Panel:GetText () is truncated to 1023 B.
- Panel:GetValue () is truncated to 8091 B for TextEntries, 1023 B for other UI controls.
- TextEntry pasting is O(n^2) in the number of line breaks. Pasting 1000 "\n"s freezes the game.

**Comment by robotboy655** [comment]
Don't we already have read only DTextEntry though?

**Comment by Pugsworth** [comment]
I found no mention of this anywhere on the wiki or DTextEntry's source code.
If I did miss it, please let me know.

**Comment by robotboy655** [comment]
As for placeholders: https://github.com/garrynewman/garrysmod/pull/972

**Comment by robotboy655** [comment]
Pretty sure you can "Disable" it to achieve the same effect.

**Comment by Pugsworth** [comment]
> Pretty sure you can "Disable" it to achieve the same effect.

I did indeed try this, but it also blocks mouse input.

**Comment by robotboy655** [comment]
Read only was already possible, rightclick menu was always able to be disabled via https://wiki.facepunch.com/gmod/PANEL:OnMousePressed and placeholders were added.

GetText and GetValue are no longer limited in the amount of data they can return.
