### ISSUE TITLE
Make mesh.End return the created IMesh

### ISSUE THREAD

**Issue by mentlerd** [Facepunch/garrysmod-requests#62]
http://facepunch.com/showthread.php?t=1282568&p=41407322

**Comment by robotboy655** [comment]
If you do not give mesh.Begin a mesh, it will use a internal dynamic mesh, which is shared across many different parts of the engine. Having the ability to modify it past mesh.End will cause very unpredictable things to happen, and if you gave mesh.Begin a mesh, then you already have the mesh,

This will not be added.
