### ISSUE TITLE
More navmesh features

### ISSUE THREAD

**Issue by Kngrektor** [Facepunch/garrysmod-requests#624]
Speciafically https://developer.valvesoftware.com/wiki/Navigation_Meshes#Adding_place_names
Would be awesome to have a actual library for adding them

**Comment by robotboy655** [comment]
I have a strong reason to believe dynamic place names functions would not be possible and you'd be constrained to a list we make. At least that was the impression last time I looked into those functions.

**Comment by Kngrektor** [comment]
Is the place names not associated with CNavArea? If not a static list is just fine, was mostly thinking about cs maps

**Comment by Kefta** [comment]
A constricted list for CS:S, DOD, and other mount games would still be very nice. Not sure if the place names are stored in the map, but that could work too

**Comment by Kngrektor** [comment]
One would think its stored in / with nav meshes if its under the nav_ prefix

**Comment by robotboy655** [comment]
Yeah, as I suspected, the places list is defined in navplace.db and it would be improbable to make it dynamic, since the places in nav files are saved as indexes, positions of the actual strings in navplace.db

**Comment by Kngrektor** [comment]
Oh sorry i wrote i kinda hastely, I mean a function for grabbing the place name and then maybe a library for nav mesh editing.

**Comment by robotboy655** [comment]
You can't have a function to "grab the place name" because there are no place names in Garry's Mod.

I am assuming you mean place names from nav meshes from other games, and that is not going to happen (without you redoing all the places on a map for every imported navmesh) because that way we can only support places from only one game.

**Comment by raubana** [comment]
I could really use this feature right now. Even if it doesn't give an exact name; a number or an enumeration would work too.

**Comment by raubana** [comment]
With the exception of the ones for CS:S, it looks like the place names are saved directly in the .nav files. Is it really out of the question asking for a way to get access to a CNav's place?
