### ISSUE TITLE
More CNavArea Functions

### ISSUE THREAD

**Issue by maximlahaxim** [Facepunch/garrysmod-requests#625]
I recently started an AI project for player bots, so I decided I'd rewrite pathfinding for it. However, essential CNavArea functions that are used to calculate paths internally haven't been converted to Lua. I'd like to see all of the CNavArea functions in it's header (https://github.com/ValveSoftware/halflife/blob/master/game_shared/bot/nav_area.h) were converted to Lua. Being able to modify/get more aspects of CNavAreas would allow for much more control over them and would certainly prove useful.

**Comment by mcd1992** [comment]
A lot of those are already implemented. Saying "do all this" isn't proper for a ticket. List what methods you need implemented.

**Comment by robotboy655** [comment]
@mcd1992 Exactly.

**Comment by maximlahaxim** [comment]
@robotboy655 [Here's a list] : http://pastebin.com/Duzzmcqu

**Comment by robotboy655** [comment]
```Functions to get/set the CNavLadder's C++ values in a table (like Entity:GetSaveTable)```

That's not how it works.

**Comment by robotboy655** [comment]
Added these functions:
```
* Added CNavArea.SetParent( CNavArea, type )
* Added CNavArea.GetParent() - returns CNavArea
* Added CNavArea.GetParentHow() - returns NavTraverseType
* Added CNavArea.ClearSearchLists()
* Added CNavArea.SetTotalCost( float )
* Added CNavArea.AddToOpenList()
* Added CNavArea.GetTotalCost() - returns float
* Added CNavArea.IsOpenListEmpty()
* Added CNavArea.PopOpenList() - returns CNavArea
* Added CNavArea.IsBlocked()
* Added CNavArea.IsOpen()
* Added CNavArea.IsClosed()
* Added CNavArea.RemoveFromClosedList()
* Added CNavArea.UpdateOnOpenList()
* Added CNavArea.AddToClosedList()
* Added CNavLadder.ConnectTo( CNavArea )
```
