### ISSUE TITLE
GMod doesnt end is exe even after the latest update

### ISSUE THREAD

**Issue by deinemudda32** [Facepunch/garrysmod-requests#627]
Same problem as always.

After exiting gmod, the exe keeps running and it says that im playing gmod currently in the steam overlay.

**Comment by Velkon** [comment]
My gmod end IS exe!

**Comment by deinemudda32** [comment]
I've just encountered im in the requests tab. whops.

**Comment by kalis0x** [comment]
my gmod end in .bat help please :((
