### ISSUE TITLE
Request point_viewcontrol fix for multiplayer

### ISSUE THREAD

**Issue by kem008** [Facepunch/garrysmod-requests#628]
If I well remember this entity is in ctriggercamera.cpp but please tell me if I am wrong.
I dont know it can be recreated with lua, and still dont know where to start it. Tell me if it can be recreated in lua or not and give some idea where to start :)

https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/game/server/triggers.cpp

https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/triggers.cpp

I dont know gmod is using this from multiplayer or singleplayer version could be singleplayer o_O

**Comment by robotboy655** [comment]
Bug reports go this way: https://github.com/Facepunch/garrysmod-issues

Also tell us what the actual bug is if you want a fix.
