### ISSUE TITLE
CNavLadder m_*Area Functions

### ISSUE THREAD

**Issue by maximlahaxim** [Facepunch/garrysmod-requests#629]
Hey there, in my CNavArea function requests, I mentioned functions to get/set a CNavLadder's C++ values. I explained it wrong, unfortunately. The exact values I meant were the CNavLadder's m_topForwardArea, m_topRightArea, m_topLeftArea, m_topBehindArea, and m_bottomArea variables. Can we get functions to get/set those? Thanks!

**Comment by maximlahaxim** [comment]
Also, kind of going back to CNavArea, what about CNavArea::GetLadderList( navladder_dir )? That would also be useful. GetLaddersAtSide doesn't seem to do what GetLadderList does IIRC, correct me if I'm wrong.

**Comment by robotboy655** [comment]
There's no such function as "CNavArea::GetLadderList" in our version of the engine.

**Comment by robotboy655** [comment]
Your links are for Half-Life 1 SDK, not Half-Life 2 which GMod is based on.

**Comment by robotboy655** [comment]
And we already have GetLadders and GetLaddersAtSide functions which return connected to given CNavArea ladders. ( all ladders, or ladders at given side )

**Comment by robotboy655** [comment]
Added these functions:
```
* Added CNavLadder.SetBottomArea
* Added CNavLadder.SetTopBehindArea
* Added CNavLadder.SetTopForwardArea
* Added CNavLadder.SetTopLeftArea
* Added CNavLadder.SetTopRightArea
```

With their Get* methods too. All of them take/return single argument - CNavArea.
