### ISSUE TITLE
Add Framerate EffectData parameter and a way to find the material index

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#630]
Example of how it's stored: https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/te_explosion.cpp#L119

Useful for setting how fast you want the effect to cycle through

**Comment by Kefta** [comment]
Also, there's no real way of telling which index a material is stored in with http://wiki.garrysmod.com/page/CEffectData/SetMaterialIndex , so adding modelinfo->GetModelIndex would not hurt

**Comment by robotboy655** [comment]
Not going to happen, CEffectData does not have such parameter, and barely any effects support it.

And one request per issue.

**Comment by Kefta** [comment]
If barely any effects support it, then it does have it?

**Comment by robotboy655** [comment]
No, you are confusing CEffectData and a global c++ function & class that creates the effect.

**Comment by robotboy655** [comment]
Here are the fields CEffectData has:

https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/game/shared/effect_dispatch_data.h#L41-L72

**Comment by Kefta** [comment]
I'm asking to add the FrameRate parameter to our EffectData() since we have no way of creating TEs in Lua.

**Comment by robotboy655** [comment]
The TE_ effects are completely unrelated to EffectData(). I guess I could bind TriggerTempEntity clientside to allow creating TE effects.

**Comment by Kefta** [comment]
Thanks!!

**Comment by robotboy655** [comment]
I actually not sure if that's a good idea either, since it doesn't even provide support for the effects you wanted added.

**Comment by Kefta** [comment]
Really, the only effects I need are Bubbles/Trail, Explosion, and Smoke. The only problem with the explosion and smoke is that they go WAY too fast, which is why I requested the FrameRate modifier. As for Bubbles, it has a lot of its own TE variables, which I think can be bypassed all together by binding UTIL_Bubbles. 

I don't think BubbleTrail has an equivalent method, but TE::Create( params ) could be a way to access each effect individually. I think that would just become bloated to have one for each effect, though.
