### ISSUE TITLE
Add missing effects

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#631]
https://github.com/ValveSoftware/source-sdk-2013/tree/master/mp/src/game/server

The ones specifically missing include ArmorRichochet, the beams, Bubbles, BubbleTrail, Fizz, FootprintDecal (missing Decal), EnergySplash, LargeFunnel, and GlowSprite.

Some of these introduce new effect parameters; such as life, brightness, and amplitude. I can form a list of which effects require these if needed.

**Comment by Kefta** [comment]
@robotboy655 I found a solution to the problem raised in #630 -- the engine has methods such as UTIL_Bubbles/Smoke/Beam for invoking TEs. I suggest a function is added called util.TempEffect that accepts a string and table with key/values -- each effect can have its own key/value set since the parameters differ, and can be documented on the wiki, similar to util.Effect. 

Otherwise, you can make a library called effects or te and have a function for each effect -- similar to how it's current done in the engine.

**Comment by thegrb93** [comment]
Was this solved?

**Comment by Kefta** [comment]
No, but they can mostly be recreated in Lua.
