### ISSUE TITLE
Add argument to CNavArea:GetLadders

### ISSUE THREAD

**Issue by maximlahaxim** [Facepunch/garrysmod-requests#633]
Hey there. Sorry if I've been a nuisance with all the requests I've been making. However, there is one more thing I'm interested in seeing. AFAIK, CNavArea:GetLadders in Lua return ALL of the ladders connected to the specified CNavArea. However, I need to get ladders that are either up or down (not south, west, east, or north, so GetLaddersAtSide won't work). In the Source SDK 2013 code, CNavArea::GetLadders takes an argument that returns ladders that are in the specified direction (up, down). Can this be added to GMod? Correct me if I got anything wrong.

**Comment by robotboy655** [comment]
GetLaddersAtSide supports that.

**Comment by robotboy655** [comment]
Both GetLadders and GetLaddersAtSide use CNavArea::GetLadders internally.

**Comment by robotboy655** [comment]
I've fixed up the wiki to show correct info
