### ISSUE TITLE
engine.GetServerIP() and engine.GetServerPort()

### ISSUE THREAD

**Issue by looterz** [Facepunch/garrysmod-requests#634]
Would return the currently bound public IP address of the server and the current query port being listened on by the server from ISteamGameServer. 

This would be useful as ISteamHTTP is not reliable for retrieving this information from an external API on shared hosting providers and hostip, ip are not required to be set correctly to successfully host a dedicated server but is the only way to get this information from Lua currently.

**Comment by willox** [comment]
http://wiki.garrysmod.com/page/game/GetIPAddress
