### ISSUE TITLE
CNavArea:GetExtent

### ISSUE THREAD

**Issue by maximlahaxim** [Facepunch/garrysmod-requests#635]
Just realized the convenience this function could bring. Basically this would take and return the values that the CNavArea's m_extent variable contains. I need it for my pathfinding code, and it would also be useful for other cases. Can this one be added?

**Comment by robotboy655** [comment]
Added CNavArea:GetExtentInfo(), returns a table with given keys:
hi - vector
lo - vector
SizeX, SizeY, SizeZ - floats
