### ISSUE TITLE
poster2 (or whatever) - like poster, but outputs separate images

### ISSUE THREAD

**Issue by NeatNit** [Facepunch/garrysmod-requests#636]
The poster command creates a screenshot n times the resolution of your screen. It does so by taking many screenshots and stitching them together.

Can we get a version that doesn't stitch them together? As seen in the screenshot here: http://garry.tv/2012/02/25/poster-screenshots/

This was a WIP output, but the released command's output will always stitch them together. This is problematic when the target resolution is too big, and there isn't enough memory for the huge output image. By outputting a series of regular-sized screenshots, there is no special memory requirement so any size screenshot is achievable - while leaving the stitching work for the user.

**Comment by willox** [comment]
This is pretty fun: http://scrnsht.me/u/9jb/raw. That's 57000x30000 or 1.29GB worth of PNG files and took me about 10 minutes.

It'll be in the dev branch soon-ish. You can do it by just adding another argument (1) to the end of the poster command, for example:
```
poster 10 1
```

**Comment by NeatNit** [comment]
Thank you! I see that the feature is now live on dev, so thanks!

How do you get windows to play nice? https://i.gyazo.com/68b7fad317b12da0c83b5dbb883e29cd.png

**Comment by willox** [comment]
I was sorting by age descending
