### ISSUE TITLE
Add AllSolid index to TraceResult

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#638]
Boolean if the trace is trapped in a solid; already part of the engine's trace result, but is missing in Lua.

**Comment by thegrb93** [comment]
trace.StartSolid?

**Comment by Kefta** [comment]
That only says if the trace started in a solid environment, not if it stayed in it the entire trace length

**Comment by robotboy655** [comment]
Done.

**Comment by Kefta** [comment]
Thank you!
