### ISSUE TITLE
PathFollower:GetSegments/GetSegment?

### ISSUE THREAD

**Issue by maximlahaxim** [Facepunch/garrysmod-requests#639]
Hey there. A function to get all of segments of a PathFollower would be very useful, could this be added?

**Comment by mcd1992** [comment]
I'm not sure how the PathFollower was setup internally but if its using the Valve defined navmesh pathfinding then its slightly difficult to do as the pathfinding is updated every frame. The path/segments might also change if a navarea gets marked as blocked among other factors.

**Comment by robotboy655** [comment]
Naturally such a function would only return data for current tick.

**Comment by maximlahaxim** [comment]
@robotboy655

Would still be useful, at least in my case.

**Comment by robotboy655** [comment]
Added PathFollower:GetSegments(), returns a table of tables, where the format of the tables is the same as the one in PathFollower:FirstSegment().
