### ISSUE TITLE
Add mask and ignored entities to FireBullets structure

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#641]
From the trace structure: https://wiki.garrysmod.com/page/Structures/Trace (ignoreworld is not really needed for bullets).

Having these will allow bullets to pass through teammates and nocollided props. The FireBulletsInfo_t struct even has a parameter for a single ignored entity.

**Comment by meepdarknessmeep** [comment]
related #610

**Comment by Kefta** [comment]
I fixed this by making my own FireBullets function in Lua, but this https://github.com/Facepunch/garrysmod-requests/issues/755 is still needed.

**Comment by robotboy655** [comment]
Added "IgnoreEntity"

**Comment by Kefta** [comment]
@robotboy655 Does it support tables and functions like util.Trace*?

**Comment by robotboy655** [comment]
no

**Comment by Kefta** [comment]
Well that's kind of useless

**Comment by EAU7** [comment]
Sorry for bump, but will it be updated to support tables and functions? Is there an other way to make bullet go through entity (besides collision groups)?

**Comment by EAU7** [comment]
I could fire a trace on every bullet when it's get spawned to check if it will shoot that specific entity and set IgnoreEntity to that entity, but what if there will be few entities one after another? I'll ignore the first one, but shoot the second.

**Comment by Kefta** [comment]
Or at least re open the request so a duplicate doesn't have to be made.

**Comment by EAU7** [comment]
I was trying to make it work with just one entity and update its physics object with Entity.PhysicsInitMultiConvex (in my case entities don't move and are primitive cubes), but for some reason on the first update it replaces the first convex table with second one and keeps doing that with next updates, so entity disappears, but PhysicsInitMultiConvex call still returns true (seems like it's an obvious error in my code, but I looked everywhere and just couldn't see it)

**Comment by Kefta** [comment]
Jk, it was already recreated here https://github.com/Facepunch/garrysmod-requests/issues/969
