### ISSUE TITLE
Manual Lua Refresh

### ISSUE THREAD

**Issue by DuckyC** [Facepunch/garrysmod-requests#642]
Lua bindings for manually triggering a lua refresh like the autorefresh, for specific files or entities.

basically this: https://facepunch.com/showthread.php?t=1405662&p=45526879&viewfull=1#post45526879

**Comment by mcd1992** [comment]
Does python's module not work anymore? I see no reason why it wouldn't.

**Comment by DuckyC** [comment]
It only works for linux, and its hacky as fuck.

**Comment by Python1320** [comment]
there's windows build and it's the least hacky way there is, it uses the actual functions

**Comment by DuckyC** [comment]
`void *lHandle = dlopen( "garrysmod/bin/server_srv.so", RTLD_LAZY  );`
I don't see how this would work on windows?

**Comment by Leystryku** [comment]
The windows alternative to dlopen is LoadLibrary
The windows equivalent for your line would be void*lHandle = (void*)LoadLibrary( "garrysmod/bin/server_srv.so" );

**Comment by DuckyC** [comment]
except there is no server_srv.so on windows

**Comment by Bo98** [comment]
If you are using Source SDK you can use `Sys_LoadModule` which handles file extensions for you but you might still need to append the `_srv` for Linux DS specifically.

**Comment by Python1320** [comment]
https://github.com/willox/archive/tree/master/gmsv_refresh-master

**Comment by willox** [comment]
I wanted some sort of GMA hot-loading. This would make sense to be added at the same time.
