### ISSUE TITLE
Ammo accessors

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#646]
There's currently no way to get the AmmoData struct for a specific ammo type or it's specific values other than game.GetAmmoMax. It'd be nice to either have a table accessor or specific value accessors.

**Comment by robotboy655** [comment]
Added game.GetAmmoNPCDamage()
Added game.GetAmmoPlayerDamage()
Added game.GetAmmoForce()
Added game.GetAmmoDamageType()

All take the ammo index.

I don't see any reason for the other values. The functions will naturally follow any console variables.

**Comment by Kefta** [comment]
The other accessors are needed for custom FireBullets functions - flags, splash, and tracer type are all utilised, so this doesn't totally solve https://github.com/Facepunch/garrysmod/pull/1305

**Comment by robotboy655** [comment]
Added game.GetAmmoData( id )
