### ISSUE TITLE
Merge VBSP enhancements

### ISSUE THREAD

**Issue by wouterpleizier** [Facepunch/garrysmod-requests#648]
Some time ago I made two additions to the Source SDK 2013 version of VBSP (the BSP compiler, that is). The first addition is the [func_detail_blocker](https://developer.valvesoftware.com/wiki/Func_detail_blocker) entity, which was introduced in L4D1 but never made available to older Source games. The second addition is a command line option that allows most dynamic/physics props to be used as static props, resulting in better lighting and performance.

[I released the modified VBSP on the Facepunch forums.](https://facepunch.com/showthread.php?t=1488605) I don't know how many mappers use the GMod version of Hammer, but it might be worth merging these additions into the VBSP that is included with it. The changes are fairly minor and (presumably) easy to merge:
wouterpleizier/source-sdk-2013@804ff1c4f991b9194a1639231853b64260285acc
wouterpleizier/source-sdk-2013@65b93a4331cab65c45d2fb77fadb79b57140cacb

**Comment by robotboy655** [comment]
Added both I guess.
