### ISSUE TITLE
Convar to enable hl2dm sprint stamina / oxygen meter.

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-requests#651]
Can't find any way to enable the normal hl2 stamina/oxygen.

**Comment by madman32395** [comment]
Just install a new hud. its a sandbox game for a reason.

**Comment by robotboy655** [comment]
Is there any point in adding something that can be easily made with Lua?

**Comment by neico** [comment]
Well the Suit Module system itself is pretty decent, and includes a lot of various things that parts of the hl2 campaign depends on (ep2 flashlight drain for example)

So having it in a default setup is a great bonus, besides, some things like sprint are more or less hard coded with a dependency on the suit system.

Of course everything can be done via lua, that's what makes gmod so unique. But why reinvent the wheel when you already have the stuff sitting there, and even in native code...

If it's still not being considered it should be at least analysed if there's anything from the system that might be missing some lua bindings (ex. I don't think that you can make the flashlight flicker like it does with the suit system shortly before going out)

**Comment by Kefta** [comment]
Yes, because it's integrated with the suit sounds/features

**Comment by Kefta** [comment]
SetSuitUpdate is a missing binding.

**Comment by robotboy655** [comment]
I have restored most of the suit stuff, namely the oxygen and sprint stuff. They are of course disabled by default via `gmod_suit` convar, with a visible option to turn it on in the Start New Game screen.

Haven't done anything about the flashlight yet, so keeping this open for now.

**Comment by robotboy655** [comment]
Flashlight is added now, not the EP2 version though, that would require network changes and hud fixing. I kinda wanted to add the ep2 one with `hl2_episodic` convar but I am not sure we need this.
