### ISSUE TITLE
Make a startup game mounting crash log

### ISSUE THREAD

**Issue by EstevanTH** [Facepunch/garrysmod-requests#654]
Hello Willox and all,

After the update from February 22nd my game was crashing at startup, probably because of an error while mounting games. I have been aware of this kind of crashes through friends, who had corrupted VPKs or whatever.

What would be great is a crash dump for mounting issues. You know, a file that you write until the end of mounting that you remove when mounting is finished.

Thanks!

Love, Momo :heart:

**Comment by EstevanTH** [comment]
What I mean is that Garry's Mod can crash while mounting corrupted games during startup. I used a wrong word "dump", it's more of a *mounting crash log* because there's actually nothing to dump.
The point is to find out which game is the responsible of the crash.

**Comment by robotboy655** [comment]
This should've been handled earlier, I am not even sure this is needed anymore, or ever was, but `hl2.exe +developer 1 -condebug` will now print which game it is about to mount to the console (and therefore to the `console.log` file), similarly to folder addons, etc.
