### ISSUE TITLE
Increase FOV cap from 90 to 120 ( from cvars and networking and whatnot )

### ISSUE THREAD

**Issue by Jvs34** [Facepunch/garrysmod-requests#657]
It's 2016, I'm sure you don't need a proper explanation why this is needed.

**Comment by Kefta** [comment]
Just curious, why 110?

**Comment by Jvs34** [comment]
For the cap you mean? That can be up to debate I guess, it could be made 120 too but anything more than that gets really weird unless you're using one of those eye-finity monitors.

**Comment by Kefta** [comment]
I think 120 is a better cap aesthetically. Also, I didn't know eye-finity was a thing, looks pretty cool.

**Comment by Jvs34** [comment]
Cap got increases to 100 by willox, better than nothing
