### ISSUE TITLE
Add team metamethods to the RecipientFilters class.

### ISSUE THREAD

**Issue by mcd1992** [Facepunch/garrysmod-requests#658]
Request for the 3 team add/remove methods on RecipientFilters.

https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/recipientfilter.h#L53-L55

http://wiki.garrysmod.com/page/Category:CRecipientFilter
The three new bindings would take the m_iTeamNum index which is currently used in team.GetAllTeams() and team.Valid()

**Comment by robotboy655** [comment]
Added, not direct bindings (since they are incompatible), but equivalents.
