### ISSUE TITLE
Add missing DebugOverlay methods

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#659]
These are the methods that are currently missing from the library that write directly to the overly and can't be replicated with Lua:
- SweptBox
- Triangle
- EntityText/EntityTextAtPosition
- Grid
- ScreenText

Also, Text is missing the bViewCheck argument; It's not needed and its effects can be done in a wrapper function, but I would like to ask what it defaults to.

**Comment by robotboy655** [comment]
Added everything except for EntityText

**Comment by Kefta** [comment]
Thank you

**Comment by Kefta** [comment]
What does bViewCheck default to now since it is optional?

**Comment by willox** [comment]
false
