### ISSUE TITLE
Expose Base Velocity

### ISSUE THREAD

**Issue by Lexicality** [Facepunch/garrysmod-requests#660]
According to the [Valve Developer Wiki](https://developer.valvesoftware.com/wiki/Velocity ), players have three kinds of velocity

* Base Velocity - Applied by things such as `trigger_push`
* Local Velocity - Applied by the player themselves
* Absolute Velocity - The above two added together

However, I can't find how to access either the base velocity or the actual absolute velocity, since the two documented functions on the wiki ([GetVelocity](http://wiki.garrysmod.com/page/Entity/GetVelocity) and [GetAbsVelocity](http://wiki.garrysmod.com/page/Entity/GetAbsVelocity)) both return the same value regardless.

I'm working with a whole bunch of `trigger_push`es right now and would like to be able to get the base velocity they apply - or replicate it by setting it myself.

Could you please expose [`const Vector& GetBaseVelocity() const;`](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/baseentity.h#L1216) and [`void SetBaseVelocity( const Vector& v );`](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/baseentity.h#L1217) so I can do so

**Comment by willox** [comment]
Is that the thing that moving platforms in maps use?

**Comment by Lexicality** [comment]
AFAIK yes. Anything that pushes the player (explosions etc) uses it.

**Comment by Kefta** [comment]
Yeah, I've been using GetSaveValue for this in my weapon base.

**Comment by willox** [comment]
ent:SetVelocity() is CBaseEntity::SetBaseVelocity
ent:SetAbsVelocity() is CBaseEntity::SetLocalVelocity

Same goes for get

**Comment by Kefta** [comment]
So GetAbsVelocity isn't actually CBaseEntity::GetAbsVelocity and GetVelocity isn't CBaseEntity::GetVelocity? What is this then: https://wiki.garrysmod.com/page/Entity/SetLocalVelocity

:confused:

**Comment by Lexicality** [comment]
But `ply:GetVelocity()` returns `0,0,0` while being pushed by a `trigger_push`?

**Comment by Lexicality** [comment]
If you run https://github.com/Lexicality/slide on any of the included maps (You'll need to install [git lfs](https://git-lfs.github.com/) to get them) and watch the top right corner, all of the values are resolutely 0 when you're not pressing any keys.

**Comment by willox** [comment]
Entity:SetLocalVelocity() = CBaseEntity::SetLocalVelocity
Entity:GetLocalVelocity() = doesn't exist?

Entity:SetAbsVelocity() = useless
Entity:GetAbsVelocity() = CBaseEntity::GetLocalVelocity()

Entity:SetVelocity() = CBaseEntity::SetBaseVelocity
Entity:GetVelocity() =
	If movetype is vphysics & has a valid physobj, returns that physobj's velocity

	Otherwise:
	CLIENT = C_BaseEntity::EstimateAbsVelocity
	SERVER = CBaseEntity::GetAbsVelocity

**Comment by Kefta** [comment]
That couldn't be any more confusing for people reading engine code lol. Time to redo all of my CS:S grenades.

**Comment by Bo98** [comment]
> Entity:SetLocalVelocity() = CBaseEntity::SetLocalVelocity
> Entity:GetLocalVelocity() = doesn't exist?
> Entity:GetAbsVelocity() = CBaseEntity::GetLocalVelocity()

A++ API.

**Comment by Lexicality** [comment]
Um, ok.

Could you add `GetBaseVelocity` in that case? I'm still kind of confused as to why `CBaseEntity::GetAbsVelocity` is returning nothing when the player is definitely moving but that's a secondary point.

**Comment by willox** [comment]
This is a pretty annoying situation. There isn't much that can be done for the current methods, but I'll add GetBaseVelocity.

**Comment by Kefta** [comment]
Just add a new set of methods -- Set/GetActualWhateverVelocity to prevent confusion. You could deprecate the others, or just keep the Actual methods as alternatives

**Comment by zerfgog** [comment]
@Kefta `mysql_real_escape_string`
