### ISSUE TITLE
Add function like this

### ISSUE THREAD

**Issue by AMD-NICK** [Facepunch/garrysmod-requests#665]
Hi. I'm shit-coder and I cant construct this funtion correctly, but I would like to see that in some gmod update. I hope you promote this idea as soon as possible. Thanks in advance

![image](https://cloud.githubusercontent.com/assets/9200174/13469436/0d9ef810-e0b0-11e5-960c-a39456aabe3e.png)
![image](https://cloud.githubusercontent.com/assets/9200174/13469447/1833424a-e0b0-11e5-82e8-40e6882b64c1.png)

**Comment by AMD-NICK** [comment]
*offtop*

![image](https://cloud.githubusercontent.com/assets/9200174/13469820/9b5234a0-e0b1-11e5-8d3a-6c937787397a.png)
nearly :(

**Comment by robotboy655** [comment]
No thanks.

**Comment by neico** [comment]
This looks like something that's already possible if gmod would be able to use source engine's chat parsing natively.
I wrote a temporal workaround 2 years ago: http://puu.sh/nsl52/92da7efa33.txt
