### ISSUE TITLE
Change the logic of "ModelImage" thumbnail generation.

### ISSUE THREAD

**Issue by Pecius** [Facepunch/garrysmod-requests#669]
Currently _ModelImage_ generates a lot of unnecessary _error.mdl_ thumbnails for missing models.
So the idea is to stop it from generating a thumbnail in that case and use the already generated thumbnail of _error.mdl_. But if a thumbnail already exists and model does not (for example a model from unmounted TF2 content in the default spawn list) it will still load the thumbnail.

**Comment by willox** [comment]
That actually makes a lot of sense

**Comment by robotboy655** [comment]
This was handled years ago.
