### ISSUE TITLE
Ability to send HTTP requests with a custom body

### ISSUE THREAD

**Issue by timmyws** [Facepunch/garrysmod-requests#670]
The HTTP library currently prevents us from sending anything but URL-encoded KeyValue pairs in the body. It would be nice if this limitation could be removed.

There's a bunch of APIs that require you to send HTTP requests with a JSON body and I'd like to be able to interact with them directly.

**Comment by Bo98** [comment]
Does the "body" field not work? https://wiki.garrysmod.com/page/Structures/HTTPRequest

**Comment by timmyws** [comment]
Oh, I can't believe I missed that. The `body` field does work. Thank you very much.
