### ISSUE TITLE
Make Lua-code run in multi-thread, or a separate-thread

### ISSUE THREAD

**Issue by uRandomAlex** [Facepunch/garrysmod-requests#675]
How about making Lua things run in multithread? I mean, providing tools like special functions or something else for devs, so they can assign their tasks to different threads. If it isn't possible or very hard to implement, how about just run it in second thread? Only networking uses it, and it utilizes it very little. It can be a huge perfomance improvement for servers with many addons.

**Comment by neico** [comment]
First of, the engine and lua aren't really designed to be multithreaded in a way you'd probably want.
Even trying to run lua code from another thread causes gmod to crash (build a module and you'll see that).
In a multi-thread safe environment this wouldn't happen...
There are only very specific cases where multiple threads work (for example running worker threads that collect network data and store it to be called by the lua thread later on, alas think() tick() hooks)

Before even trying to think about multi-threading I'd rather see coroutines being fixed first (unless they are by now but the issues aren't closed yet of course): https://github.com/garrynewman/gmod-module-base/issues/3

Lua and it's states (menu, server, client) all run inside the main thread, which could be moved into their own thread to some degree (theory usually doesn't cover practical facts, so someone with access to the source code might need to cover in how practical this is).
There's also a bunch of worker threads that the engine launches that can be utilized, but for unique stuff, not for lua calls directly, which limits it's practical usage overall...
See https://developer.valvesoftware.com/wiki/Threads

In the lua community are many approaches for adding multi-threading support, the primary problem is that the engine itself has issues doing things in multiple threads (see the render threading issues / requests).

Another thing to note is that lua in gmod is actually LuaJIT which is a totally different approach and therefore most solutions don't apply.

You might want to go more into detail as to what exactly you (personally) want to achieve with the request (beside a general threading improvement)

**Comment by uRandomAlex** [comment]
If providing developer tools to hande multiple threads is very hard, then let's just move Lua things to the second thread, that today is busy by 10-20% (with 24 players) by networking. Just move Lua to the networking thread. I think you got it.

**Comment by Kefta** [comment]
That'll screw up engine calls, though

**Comment by thegrb93** [comment]
Just close this issue, there's so many duplicates from people who don't know how to search or how threading works.

**Comment by uRandomAlex** [comment]
That's very bad. We don't have good, or at least medium-level multithreading support in a game, that is very popular. I feel like I playing some shitty F2P...

**Comment by Kefta** [comment]
Lua is just a scripting language to the engine. It's not meant to be put on multiple threads that would separate it from what it's scripting upon -- all of this multithreading stuff would be major changes to a decade+ year old engine.

**Comment by uRandomAlex** [comment]
dumb

actually, we can make Lua multi-threaded (there's a Lua module with a coroutine-like API), but who will bother to do this?
