### ISSUE TITLE
Make PlayerSpawnedProp available on the client

### ISSUE THREAD

**Issue by fruitwasp** [Facepunch/garrysmod-requests#678]
Players can see props others spawn, so why shouldn't this information be available on the client. I would like to see ```PlayerSpawnedProp``` (http://wiki.garrysmod.com/page/SANDBOX/PlayerSpawnedProp) to be available on the client. Thank you.

**Comment by thegrb93** [comment]
Onentitycreated. Or you can network it yourself easily. Theres no point in networking it for every server if its not even used.
