### ISSUE TITLE
Add path-building/path-following functions for player.CreateNextBot-created bots

### ISSUE THREAD

**Issue by ghost** [Facepunch/garrysmod-requests#681]
Hey there. Please note that this request isn't asking "can you create a whole AI interface with everything done pretty much for me?", this is asking as to whether pathfinding/following functions can be implemented for player.CreateNextBot bots. The only current way to have path finding/following work on these bots so far is extremely hacky and isn't very reliable. I think this would be a necessary addition for those who want to add in AI players, can this please be put in?

**Comment by maximlahaxim** [comment]
Mike Booth's fake-client pathfinding functions are still around, should be easy to add those.

**Comment by robotboy655** [comment]
`PathFollower:Update` and `Compute` do support `player.CreateNextBot` entities, that should be it I think?
