### ISSUE TITLE
Implement AE_CL_STOP_PARTICLE_EFFECT

### ISSUE THREAD

**Issue by Donkie** [Facepunch/garrysmod-requests#683]
Found here: https://developer.valvesoftware.com/wiki/Particles_In_Animations

Just found some models that utilize this and their animations get wonky in garrysmod.

The Entity:StopParticles* functions seems to be doing the same as this.

**Comment by robotboy655** [comment]
Implemented AE_CL_STOP_PARTICLE_EFFECT & AE_CL_ADD_PARTICLE_EFFECT_CP

**Comment by robotboy655** [comment]
I couldn't test it because I don't know of any models that use them, but they do exactly the same thing as they do in Alien Swarm.

**Comment by Donkie** [comment]
That was quick, thanks!
