### ISSUE TITLE
Model information 

### ISSUE THREAD

**Issue by SuperHighVoltage** [Facepunch/garrysmod-requests#684]
I'm in need of a way to know if a model was compiled as a physics, static or dynamic prop.
Hammer's model viewer shows this info so I don't think it's far fetched:
![At text?](http://puu.sh/nNtHH/ae8ff174b7.jpg)

I'm not sure what other information you could grab from a model but maybe a util function where you can supply a model path and have it return a table of properties would be neat

**Comment by robotboy655** [comment]
I have added the `$staticprop` .qc value to `util.GetModelInfo` as `StaticProp`, the Dynamic/Physics are opposites of each other, and are determined if the model has any PropData keyvalues (if so, Physics) from the aforementioned function.

Static in Hammer is also set if there's a propdata value of `"allowstatic"` set to `"1"`. So these are mostly a parsing thing for your end.
