### ISSUE TITLE
Ability to easily convert image files (ex. jpg,png,gif) to vtf files.

### ISSUE THREAD

**Issue by LuaTenshi** [Facepunch/garrysmod-requests#686]
Ability to easily convert image files (ex. jpg,png,gif) to vtf files. For use with easily creating, custom decals, object textures, and probably more.

Related: https://github.com/Facepunch/garrysmod-requests/issues/605

**Comment by thegrb93** [comment]
Use vtfedit or vtex?

**Comment by LuaTenshi** [comment]
vtfedit/vtex can not get an image from a url and convert it into a working texture live. If some one wanted to make a way to load in different textures as they are needed. They would not be able to convert the images on the fly like that. (Without sending them to an external server)

**Comment by thegrb93** [comment]
Related then https://github.com/Facepunch/garrysmod-requests/issues/605

**Comment by LuaTenshi** [comment]
Guess it is... and that the searches I did sucked because I couldn't find anything like that.

**Comment by robotboy655** [comment]
Can't you use CreateMaterial for that? Not for converting naturally, but for "use with easily creating, custom decals, object textures, and probably more."

**Comment by robotboy655** [comment]
Because you know, .png already have to be converted into Source-readable format ( .vtf ) before they are usable in game.

**Comment by LuaTenshi** [comment]
I guess that works for PNG images but what about animated things like gifs?

**Comment by robotboy655** [comment]
You can't use .apng or .gifs in GMod, you may create a request for that, but I wouldn't get my hopes up, you should make an animated .vtf at that point.

**Comment by LuaTenshi** [comment]
I thought this was a request.

That's the problem let's say I want to have a client give a link to a gif
and then have it be made into a vtf. I could in theory create multiple
textures and cycle through them but I doubt it would be efficient.

**Comment by robotboy655** [comment]
1) It already converts to a .vtf internally in order to be loaded in-game, this request is thecnically already in the game, it just doesn't write it to a file because there's absolutely no reason for it to do that
2) You should not be relying on .png or whatever materials in making your mods
3) You can write custom downloaded .vtf files into data/ folder now anyway.

**Comment by thegrb93** [comment]
We want to be able to create the material without writing/reading from the disk. This is essential for allowing custom user created content to be uploaded to the server and then downloaded to the other clients for rendering.
