### ISSUE TITLE
Add language.GetCurLang()

### ISSUE THREAD

**Issue by art-gur** [Facepunch/garrysmod-requests#687]
This feature is very convenient because developers can quickly and easily add localization for their add-ons. This function is performed on the client and returns the language selected by the user in Garry's Mod main menu.

**Comment by neico** [comment]
just read the value of the convar "gmod_language" (same goes for normal source engine languages: "cl_language")

**Comment by robotboy655** [comment]
Your addons should use the .properties files for localization, which will be automatically loaded depending on what language the user has set. See the file structure in resources/ folder.

And as neico said, you can already get the current language.

**Comment by art-gur** [comment]
Thanks for answers.
