### ISSUE TITLE
physobj->GetVelocityAtPoint

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#692]
Binding

**Comment by Jvs34** [comment]
Because the getter doesn't exist.

**Comment by Jvs34** [comment]
https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/public/vphysics_interface.h#L775-L782

**Comment by Kefta** [comment]
I'm thinking of the wrong method

**Comment by thegrb93** [comment]
I'm guessing this gets the angular velocity at a point on the object?

**Comment by Kefta** [comment]
Yes, used for friction

**Comment by Kefta** [comment]
Jk, I found a better way
