### ISSUE TITLE
IMaterial:GetTable()

### ISSUE THREAD

**Issue by willox** [Facepunch/garrysmod-requests#696]

**Comment by Jvs34** [comment]
:GetKeyValues better name maybe?

**Comment by willox** [comment]
good idea

**Comment by LuaTenshi** [comment]
I like GetTable as its faster to type and fits the standard. Maybe have both?

**Comment by Kefta** [comment]
Did you just ask to create an alias?

**Comment by LuaTenshi** [comment]
Sort of. Gmod all ready has aliases for some other commands, so why not
this one? I mostly suggested it as a sort of compromise as GetTable seems
more intuitive. The other one I can't even recall right now.

**Comment by Kefta** [comment]
I think KeyValues is better -- creating aliases is kinda pointless which is why a lot are deprecated

**Comment by Bo98** [comment]
"API is already shit so let's make it more shit"

GetTable is the most vague name you could think of. All that tells me is that it's return type is a table.

**Comment by LuaTenshi** [comment]
How would we know when to GetTable or GetKeyValues?

**Comment by Bo98** [comment]
When do you use GetTable currently?

**Comment by LuaTenshi** [comment]
I use it all the time on stuff like entities. Especially when debugging.

**Comment by Bo98** [comment]
Entity has both GetTable and GetKeyValues and they're for different purposes. GetTable is the more free-for-all table that's used when you do `ent.somevar = "someval"` (equivalent to `ent:GetTable().somevar = "someval"`. GetKeyValues is the more predefined stuff that is mostly already covered by Entity functions. IMaterial falls under the latter for me.

**Comment by LuaTenshi** [comment]
Ah alright. Turns out my brain does stop working past 2 AM.
