### ISSUE TITLE
Make NextBot:BecomeRagdoll return the created ragdoll entity

### ISSUE THREAD

**Issue by fruitwasp** [Facepunch/garrysmod-requests#699]
Could you make the method [NextBot:BecomeRagdoll](http://wiki.garrysmod.com/page/NextBot/BecomeRagdoll) return the created ragdoll entity so methods can be run on the entity? Nothing more to say.

**Comment by robotboy655** [comment]
That would not be possible, the ragdolls created by that *serverside* functions are created on the *clientside*.

**Comment by fruitwasp** [comment]
Any way to remove them on the client?

**Comment by robotboy655** [comment]
Don't create them?

**Comment by fruitwasp** [comment]
Could a command like `r_cleardecals` be added?

**Comment by robotboy655** [comment]
You should be able to target those ragdolls with ents.GetAll().

**Comment by robotboy655** [comment]
Clientside obviously.
