### ISSUE TITLE
Make DEFINE_BASECLASS provide inherited methods from higher classes

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#700]
I didn't know whether to put this in issues or requests since I don't know the intended behaviour.

Currently, it only provides methods from the class input, and with self.BaseClass.Method( self ) causing a crash, there's no way to properly override methods from weapon/entity that aren't exclusively defined in the next higher class.

Ex.
weapon_1:
```
function SWEP:Initialize()
   doSomething()
end
```
weapon_2:
```
SWEP.Base = "weapon_1"
```
weapon_3:
```
DEFINE_BASECLASS( "weapon_2" )
SWEP.Base = "weapon_2"

function SWEP:Initialize()
   doSomethingElse()
   -- BaseClass.Initialize( self ) -- Doesn't work; method doesn't exist
   -- self.BaseClass:Initialize() -- Doesn't work; a table is provided to the method, not the actual userdata
   -- self.BaseClass.Initialize( self ) -- Crashes game
end
```

**Comment by neico** [comment]
> ] ent_create weapon_3
> doing something else...
> doing something...
> doing something else...
> doing something...
> ] ent_create weapon_3
> doing something else...
> doing something...
> doing something...
> doing something else...
> doing something...
> doing something...
> ] ent_create weapon_3
> doing something else...
> doing something...
> doing something...
> doing something...
> doing something else...
> doing something...
> doing something...
> doing something...
> 

works here... (uncommented them one after one in the hope to catch a error, nothing)

You might want to provide a full example and not such a stripped down version where things like the doSomething functions are missing...

**Comment by Kefta** [comment]
Got it; I'll put out the full source I'm using tomorrow. The way it's erroring is actually down this route: base (superclass, has Initialize) -> base2 (doesn't have initialise) -> base3 (doesn't have initialise) -> base4 (has initialise, calls BaseClass.Initialize(self)) -> weapon being used.

**Comment by neico** [comment]
The BaseClass always only contains functions present in the respective object.
You need to check for it's metatable to see where it's heading (see here: https://github.com/garrynewman/garrysmod/blob/master/garrysmod/lua/includes/modules/baseclass.lua#L52), this avoids defining redundant functions bloating the lua state.

`PrintTable( getmetatable( BaseClass ) )` should do the trick. I could probably come up with a little code that makes the traversal visible but meh... (think FindMetaTable but for FindFunction( Environment, FunctionName ) )

Sidenote: when using `DEFINE_BASECLASS( "weapon_2" )` you won't need to define SWEP.Base (I did it anyway in my test to reflect what you provided as close a possible), as you can see in the Get method included in the link above

**Comment by Kefta** [comment]
https://github.com/Kefta/Source-to-GLua

It seems since I pared the files down, it no longer corrupts BaseClass (I'll revisit it once I add the rest of them), but I am having an issue with SharedDeploy not being valid clientside with CallOnClient, which goes back to https://github.com/Facepunch/garrysmod-issues/issues/2369. I'm not sure if it's an issue with COC or BaseClass, so I'll keep posting here.

**Comment by Kefta** [comment]
@neico Helped me solve it -- came from faulty includes that created some weird DEFINE_BASECLASS behaviour; thank you!
