### ISSUE TITLE
Increase maximum length of kick reason

### ISSUE THREAD

**Issue by VigiFyre** [Facepunch/garrysmod-requests#701]
Current limit seems fine for ASCII-only, but if you need non-ASCII stuff in kick messages, it starts to get very constraining very soon.
![hl2_2016-04-04_23-15-15](https://cloud.githubusercontent.com/assets/4457582/14258416/dc9fb486-fabb-11e5-986a-3fed394a1d68.png)
![hl2_2016-04-04_23-17-59](https://cloud.githubusercontent.com/assets/4457582/14258423/e19a9730-fabb-11e5-8e63-c663a595acb0.png)

**Comment by robotboy655** [comment]
The kick reason was doubled in 2018, to ~512 bytes. It should be more than enough.

**Comment by VigiFyre** [comment]
```
> 2020
> being afraid to increase the limit of a network string that gets sent once per session to a number over 512 bytes
smh
```
