### ISSUE TITLE
Make Weapon.GetPrintName shared

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#711]
Just kind of a nitpicky thing, but all other weapon accessors (like GetSlot and GetWeight) are shared. This would be useful for nice console print for the server.

**Comment by Bo98** [comment]
Not all SWEPs set PrintName serverside.

**Comment by Kefta** [comment]
Same with Weight and Slot, but it seems to be networked with those when you call the accessor.

**Comment by robotboy655** [comment]
Done.

**Comment by Kefta** [comment]
Thank you
