### ISSUE TITLE
Add way to override Player->ProcessMuzzleFlashEvent

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#712]
There's currently no way to change world muzzle flashes nor shell outputs from the gun. The DLight would be easy to replicate, but as for the shell ejection effect, I believe #631 would need to be partially implemented to achieve the same effect.

**Comment by robotboy655** [comment]
I am fairly certin you can already override and replicate both the muzzle flash and the bullet ejection on both the world model and view model with http://wiki.garrysmod.com/page/WEAPON/FireAnimationEvent

**Comment by robotboy655** [comment]
As for replicating the effects, see the emitter tool.

**Comment by Kefta** [comment]
When I fire via the AK47 model, two events are triggered: 5001 and 20. I already do all of my viewmodel muzzle flash stuff with 5001, but I don't know what 20 nor can I find the engine definition. Is this the worldmodel firing event?

**Comment by robotboy655** [comment]
20 is the AE_CLIENT_EFFECT_ATTACH, which on AK47 world model is the bullet ejection. The AK47 worldmodel should also be firing 5003

**Comment by Kefta** [comment]
I'll test again tomorrow, but it was not earlier.

**Comment by Kefta** [comment]
@robotboy655 The events are called (5003 and 20) and I return true on them, but the default ones are still not blocked. Muzzle flash still appears in third-person and bullet ejections still show on both.

**Comment by robotboy655** [comment]
Without my code:
https://gfycat.com/MatureDesertedGalapagossealion

With my code
https://gfycat.com/LargeSmallArcticfox

My code being:
```
function SWEP:ShootEffects( pos, ang, event, options ) -- to hide dlight from :MuzzleFlash() call
end
function SWEP:FireAnimationEvent( pos, ang, event, options )
	print( "FireAnimationEvent", pos, ang, event, options, self.Owner:ShouldDrawLocalPlayer() )
	return true
end
```

**Comment by jcwik223** [comment]
i'm still having this issue, how did you solve?

**Comment by robotboy655** [comment]
The solution is right above your post.

**Comment by Kefta** [comment]
It turned out I had a custom worldmodel in my download folder that was using a number other than 5003 for the flash, if that helps
