### ISSUE TITLE
Allow to use values between 0 and 2 for IGModAudioChannel:SetVolume 

### ISSUE THREAD

**Issue by uRandomAlex** [Facepunch/garrysmod-requests#713]
Allow to use values between 0 and 2 for IGModAudioChannel:SetVolume. 1 is still the original sound's volume, that means values bigger then 1 will increase volume of original sound channel.

**Comment by thegrb93** [comment]
Would be especially useful for 3d sounds since they tend to be 50% volume no matter how close you are to them.

**Comment by Grocel** [comment]
You can't because Bass.dll clamps the volume between 0 and 1, as far as I know.

**Comment by willox** [comment]
> You can't because Bass.dll clamps the volume between 0 and 1, as far as I know.

It's possible to amplify the audio

**Comment by Grocel** [comment]
Oh that's nice. Hopefully it isn't a hassle with quality loss or with different file formats and streams and so on.

**Comment by uRandomAlex** [comment]
Any progress on that? There's even a working implementation: https://github.com/Grocel/GMod_Modules/commit/80187b10b44087096887c1b992ff6d66197fa5d3

**Comment by Grocel** [comment]
My implementation was an experiment to test if willox approach above could actual work. And Indeed it works quite well.

However the volume and the DSP based volume boost should be implemented as separate functions such as I did for the modules.

Unlike the normal volume functions, DSP affects the FFT output as they edit the actual sound input data. That supposed quality loss seems not to be a thing as it was not noticeable to me at 1000%+.

To compensate for the changed FFT output I divide the FFT outputs by the boost factor + 1 internally. At the end it at least looks the same.

You also may want to do ```BASS_SetConfig(BASS_CONFIG_FLOATDSP, TRUE);```. It sets a mode fills the pBuffer data with floats instead with shorts for the DSP callback function ```void CALLBACK fnVolumeBoostDSP(bass_dsp pDSP, bass_p pHandle, void *pBuffer, DWORD iLength, void *pUserData)```

**Comment by Grocel** [comment]
@willox: Bass can have a quite unlimited volume since version 2.4.13 without any DSP hacks. @robotboy655 has updated Bass and changed IGModAudioChannel:SetVolume() accordingly about a 1.5 years ago. I think this can be closed as it is implemented now.

**Comment by thegrb93** [comment]
Wiki says it's still 0-1 https://wiki.garrysmod.com/page/IGModAudioChannel/SetVolume

**Comment by robotboy655** [comment]
```IGModAudioChannel:SetVolume``` never clamped the value, I don't think I changed it.

**Comment by robotboy655** [comment]
Yeah it works.
