### ISSUE TITLE
Allow binding from Lua by special functions or console commands

### ISSUE THREAD

**Issue by uRandomAlex** [Facepunch/garrysmod-requests#714]
This can be done by removing 'bind' concommand from blocked (I know that there is a reason for it, however, I don't think that there is many servers that want to abuse this and lose players), or by making a special function, that will not touch button if it's already binded and will allow only commands, that's added from Lua. Also, 'Default Bind' argument for concommand.Add will be great addition to this.

**Comment by Kefta** [comment]
This is so abuseable it shouldn't even be a question

**Comment by uRandomAlex** [comment]
'...or by making a special function, that will not touch button if it's already binded and will allow only commands, that's added from Lua.'

**Comment by Kefta** [comment]
Your wording is very nebulous; can you provide an example? Otherwise, I don't see anything wrong with the PlayerKeyPress hook

**Comment by uRandomAlex** [comment]
@Kefta http://i.imgur.com/2zJnDO7.png
Actually, there is input.IsKeyDown function, BUT: player can't change key if he wants to, it don't work the same way as the bind because we have to put it in 'Think' hook (if we make code, that will do something when player has pressed a button, this code will run many times, it's bad), and because of the same this way is bad for the perfomance (it will run check every tick, 66 times/second by default).

**Comment by uRandomAlex** [comment]
Accidentally closed issue, sorry.

**Comment by Bo98** [comment]
The hook is KeyPress rather than PlayerKeyPress.

**Comment by uRandomAlex** [comment]
@Bo98 Thanks, didn't know about it. Anyway, user still can't rebind our command, and the 'Default Bind' argument for concommand.Add will be useful.

**Comment by thegrb93** [comment]
Servers shouldn't be allowed to tamper with player controls. If you need custom controls then use input.WasKeyPressed and RunConsoleCommand.

**Comment by uRandomAlex** [comment]
@thegrb93 Please, read the whole discussion.

**Comment by thegrb93** [comment]
I did and I don't think your arguments justify it. "or by making a special function, that will not touch button if it's already binded and will allow only commands" That's what I'm suggesting you to do, you only need 4 lines of code.

**Comment by Jvs34** [comment]
Use the PlayerButtonDown/Up hooks which is exactly how the sandbox entities (wheels, dynamites and whatnot) get activated.

**Comment by thegrb93** [comment]
@Jvs34 Ahhh thanks, I was searching for that everywhere using 'key' and 'input' but it's 'button'.

**Comment by robotboy655** [comment]
You can already create your own commands for binding, you can already override players binds ( By override I mean stop them from executing via PlayerBindPress ), you can already detect any key press and run code on that.
