### ISSUE TITLE
Allow to set and get pitch for IGModAudioChannel

### ISSUE THREAD

**Issue by uRandomAlex** [Facepunch/garrysmod-requests#716]
Functions IGModAudioChannel:SetPitch and IGModAudioChannel:GetPitch (or something like this) for controlling pitch of the sound channel, like in Entity:EmitSound (acceptable values are 0-255, with 100 being default pitch).

**Comment by robotboy655** [comment]
https://wiki.facepunch.com/gmod/IGModAudioChannel:SetPlaybackRate
