### ISSUE TITLE
PlayerFullyConnected Hook....

### ISSUE THREAD

**Issue by Acecool** [Facepunch/garrysmod-requests#718]
The only known method, that I knew of and found, was by using SetupMove hook with a variable attached to each player after the logic had been run to control fully-connected ( ie the player is in the game and can look around or move; or, if spawned in dead, can do whatever spectators are allowed to do, or if in menu while dead... ).

Unfortunately, at some point this changed, now this hook is called on connecting players when they're not in the game yet.. This may have been done to fix the water / frozen player / animation "glitch" while joining, although that could've been changed using animations file alone...

The only other ways I see how to achieve a similar result now relies on the client telling the server when they've connected, or if bypassed checking when input is actually pressed on either.... 

I'll be reporting this as a bug just in case SetupMove was unintentionally changed; but the feature request stands because this should be a default hook...

**Comment by Acecool** [comment]
Just got the reasoning behind the change from Willox...

It's to prevent players from intentionally preventing data from being sent and to prevent certain cheats from working....

An excellent reason to alter the behavior of SetupMove!! I'm asking him about adding in PlayerFullyConnected hook as a built-in feature; here's to hoping he'll say yes :-)

**Comment by robotboy655** [comment]
How PlayerInitialSpawn not fill this need?

**Comment by Acecool** [comment]
Because it is called prior to the client being fully in game...

The way SetupMove used to work, is it wouldn't be called until the player was actually in the game ( ie the same as HUDPaint being called on the client although this has issues where-as if the client has console open this isn't called, and if I recall correctly is is skipped if the game doesn't have focus.. both good reasons not to call HUDPaint.. )...

The reason I used it was to replace map textures without needing a timer, etc... basically some mac users have issues where the game will crash if the textures are replaced too early ( because the client authentication part of connecting, when InitialSpawn is called, takes varying lengths of time depending on the user PC ) and windows machines simply index the wrong texture ( but where macs crash, windows will be already loaded and will be fine in terms of loading the texture )..

I also use it to finish loading the client account data for the client to receive it ( character list, etc... ) plus a few other reasons...

Being able to determine the exact moment when a client is in the game, able to look around, etc... is valuable!

**Comment by Kefta** [comment]
I used to use SetupMove to play a sound to the player when they first joined, but I guess I'll just have to use HUDPaint now and hope they aren't in the menu

**Comment by Acecool** [comment]
HUDPaint works fine for localplayer stuff that isn't important, I just prefer not to have the client inform the server when they join..

Oh, if you're playing a sound for everyone else, you can use PlayerInitialSpawn or any other similar hooks if they don't need to be super accurate..

**Comment by ChampRay** [comment]
Yeah I can side with acecool on this,  the localplayer variable can sometimes not be ready ( depending on the computer the user is using I am guessing ) when PlayerInitialSpawn is ran.

**Comment by Acecool** [comment]
I eventually formulated the PlayerFullyConnected like this and moved it to the shared realm, instead of Server only ( plus networking to client ), and added another arg to help with certain features which don't need to be ran when other clients connect:

Server: function GM:PlayerFullyConnected( _p ) ... end
Client function GM:PlayerFullyConnected( _p, _islocal ) ... end

The islocal idea is similar to the sky draw for Pre/PostRenderables hooks.. It's useful because 

```lua
hook.Add( "PlayerFullyConnected", "SetupClientMapTextures", function( _p, _islocal )
   if ( !_islocal ) then return; end
   map:SetupClient( );
end );
```

Instead of adding the logic to check LocalPlayer( ) == _p, etc... simple flag which isn't necessary but helps!

**Comment by Kefta** [comment]
Maybe a PlayerNetworkReady hook? Just some way to know when the player is ready to start getting net messages since SetupMove is no longer reliable.

**Comment by thegrb93** [comment]
Or make playerinitialspawn call later. Anything

**Comment by Kefta** [comment]
PlayerInitialSpawn is called correctly, when the player initially spawns on the server. However, they may not be prepared clientside yet.

**Comment by thegrb93** [comment]
PlayerFinishLoading maybe then

**Comment by GitSparTV** [comment]
I use HUDPaint hook that sends empty net message once that render is started. Like HUDInit

**Comment by Kefta** [comment]
HUDPaint isn't called exactly when the player loads in from my experience.

**Comment by GitSparTV** [comment]
Never had on my tests.
But I can confirm that SetupMove is called right after player is ready do play.
Quite in the same time as the first HUDPaint call starts

**Comment by thegrb93** [comment]
SetupMove no longer works due to https://github.com/Facepunch/garrysmod-issues/issues/2560

HUDPaint is pretty inconvenient. Any other serverside solutions?

**Comment by GitSparTV** [comment]
@thegrb93 I saw people started using https://wiki.facepunch.com/gmod/CUserCmd:IsForced

**Comment by thegrb93** [comment]
That seems to work. Thanks

**Comment by thegrb93** [comment]
Nevermind... still has a chance to fail.

https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/sflib.lua#L621

**Comment by thegrb93** [comment]
Will try this
```lua
if SERVER then
	local initplayers = {}
	concommand.Add("_sf_plyinit",function(ply)
		if initplayers[ply] then
			for k, v in ipairs(initplayers[ply]) do
				v()
			end
			initplayers[ply] = nil
		end
	end)
	function SF.WaitForPlayerInit(ply, func)
		local t = initplayers[ply]
		if not t then t = {} initplayers[ply] = t end
		t[#t+1] = func
	end
else
	hook.Add("HUDPaint","SF_Init",function()
		RunConsoleCommand("_sf_plyinit")
		hook.Remove("HUDPaint","SF_Init")
	end)
end
```

**Comment by thegrb93** [comment]
HUDPaint seems a lot more reliable

**Comment by thegrb93** [comment]
Still not perfect though..

**Comment by thegrb93** [comment]
Another try
```lua
if SERVER then
	util.AddNetworkString("sf_playerinit")
	local initplayers = {}
	net.Receive("sf_playerinit",function(len, ply)
		local t = initplayers[ply]
		if t then
			for k, v in ipairs(t) do
				v()
			end
			initplayers[ply] = nil
			timer.Remove("SF_PlayerInit"..ply:EntIndex())
		end
	end)
	function SF.WaitForPlayerInit(ply, func)
		local t = initplayers[ply]
		if not t then
			initplayers[ply] = t
			local n = "SF_PlayerInit"..ply:EntIndex()
			timer.Create(n, 1, 0, function()
				if ply:IsValid() then
					net.Start("sf_playerinit")
					net.Send(ply)
				else
					initplayers[ply] = nil
					timer.Remove(n)
				end
			end)
		end
		t[#t+1] = func
	end
else
	net.Receive("sf_playerinit",function()
		net.Start("sf_playerinit")
		net.SendToServer()
	end)
end
```

**Comment by thegrb93** [comment]
Just found it does work, but the bug was somewhere else.

**Comment by angelfor3v3r** [comment]
It's been years and this isn't in the game? Any updates on this?

Very unfortunate that I have to make my own callback inside SetupMove just so I can freeze first-time joining players. Feels very over-engineered.

**Comment by LeQuackers** [comment]
[Bump](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/gameinterface.cpp#L2673)?

**Comment by Kefta** [comment]
Added ClientSignOnStateChanged (server) and SignOnStateChanged (client) which can be used to detect when the client is ready to receive network communications.

**Comment by Kefta** [comment]
> [Bump](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/gameinterface.cpp#L2673)?

That is essentially the equivalent of PlayerInitialSpawn. The client is not guaranteed to be ready for networking then.

**Comment by thegrb93** [comment]
Can someone document what the states are and what they mean in terms of being ready to receive net messages?

**Comment by LeQuackers** [comment]
if ```SIGNONSTATE_FULL``` is set server side it means the player is ready to receive net messages, but their entity hasn't been created yet. if ```SIGNONSTATE_FULL``` is set client side, it appears to be the opposite; basically they've received everything, their entity was created, and they are ready to play. The enums can be found [here](https://github.com/VSES/SourceEngine2007/blob/master/src_main/common/protocol.h#L159-L166) but I'm not sure if the context of the comments are server or client side.

**Comment by thegrb93** [comment]
So I guess we need to have the client send a message to the server still when they reach SIGNONSTATE_FULL.

**Comment by LeQuackers** [comment]
@thegrb93 In my stuff I use ```gameevent.Listen("OnRequestFullUpdate")``` server side. If you send net messages to the client during this they will receive them before ```GM:InitPostEntity``` is called. See https://github.com/Facepunch/garrysmod-issues/issues/4899#issuecomment-821164956

**Comment by Acecool** [comment]
Even if the client has to tell the server they are ready ( which isn't a huge inconvenience - but it would be nice for this step to be automated so instead of ping/ponging we can just send the initial data when they are fully in the game ) ...

But, the new hooks are a welcome change because it means one less self-deleting HUDPaint hook - and yes, HUDPaint is ignored when the user has console open, etc..

For the individual talking about freezing players - you can do that when the entity itself is created, or have them spawn in when ready. So if they are in console during connecting, when they close it they'd be put in.... It has been a while but know it was possible to open the console during the loading screen, but when you connect it closed??? I'd have to double check.... but it does make the code a bit shorter..

Instead of the whole HUDPaint thing, hook add state net send to server end. basically 4 lines when the player is ready. Being able to receive that automatically on the server would be nice though..

I'll go through and update my stuff and give it a test asap - I may leave my hook name and change the meaning slightly - fully connected for ready to receive, and fully loaded for just after the initial data-stream ( either in full if small enough, or packeted ) in my net system. 

But having this definitely cleans some things up - thank you for adding it to the game. 

We may want to create a new request to either have the back-end send that initial net message to the server from the client, or add the 4 lines of code to a default client file and 3 lines on a server file to call the hook with a state enum appropriate for they are ready to play - ie: ready to receive initial data, etc..

**Comment by thegrb93** [comment]
Is SIGNONSTATE_FULL only going to happen once or will it happen with each full snapshot update? Might still need to be self-deleting if it can happen more than one time.

**Comment by LeQuackers** [comment]
```SIGNONSTATE_FULL``` is set when the client joins the server or when the map changes, So it's once per map unless they rejoin. Full update packets are sent when the game state needs to be synced with the client (e.g. joining, lag, ```cl_fullupdate```), so it's sent multiple times.

Also, hold off from using ```gameevent.Listen("OnRequestFullUpdate")``` for early networking, it might not actually work. Something is wrong with my tests and I'm not sure what. Basically I decided to also test net messages sent from ```GM:PlayerInitialSpawn``` and they worked 100% of the time in terrible network conditions, which doesn't make sense.
