### ISSUE TITLE
Garry's Mod Reweite

### ISSUE THREAD

**Issue by Jake3231** [Facepunch/garrysmod-requests#719]
I love Garry's Mod, but I feel that there are many ways that it could be better.  Unless it is very easy to update, I think that Garry's Mod needs to be completely rewritten for both Windows and OS X.  I know this sounds crazy, but I really think that the games needs to be written to use Metal and DirectX better, and also improve stability and UI.  Complete backwards compatibility with the current Gmod and its addons would be nice.  These are among a few things that I would love to see, but I also understand the magnitude of this request.  I'd appreciate any thoughts or feedback on this too!

**Comment by robotboy655** [comment]
Whaat a great idea!

**Comment by Kefta** [comment]
Lmao
