### ISSUE TITLE
Allow weapons/entities to override ClassName

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#720]
I'm using a different file name from the class name in a weapon to tell if it's a base weapon, but retain map support for those that spawn based on the entity class. Currently, setting SWEP.ClassName has no effect.

**Comment by robotboy655** [comment]
Rename your folder? I see no reason for this, SWEP.ClassName is not meant for overriding, it's an auto set variable.

**Comment by Kefta** [comment]
If I rename the folder, I support for maps that create instances of the weapon. Ex: I've seen a few Surf maps that create weapon_cs_base, then rely on the CS:S code to cast it later. I need to tell when a weapon is a base class for debugging, which I currently do by checking if "base" is in the class name. However, this is prone to error as not all base weapons have base in the name and vice-versa.

**Comment by robotboy655** [comment]
What's wrong with having a dummy SENT called weapon_cs_base that would spawn the correct weapon or shit?

**Comment by Kefta** [comment]
I guess I can just use weapons.Register; just thought overriding class name would be less hacky since engine file names differ than the ones specified in LINK_ENTITY_TO_CLASS already.
