### ISSUE TITLE
PANEL:IsWithin hook 

### ISSUE THREAD

**Issue by meepen** [Facepunch/garrysmod-requests#723]
The request:

``` lua
-- PANEL is a circular panel

function PANEL:GetLeftRightAt(y)
    local dist = y / (self:GetWide() / 2)

    if (dist < 0) then
        dist = -dist
    end
    dist = 1 - dist

    dist = math.sin(math.acos(dist))

    local left = self:GetWide() * (0.5 - dist / 2)

    return self:GetWide() * (0.5 - dist / 2), self:GetWide() * (0.5 + dist / 2)
end

function PANEL:IsWithin(x, y)
    -- check top bottom here
    local leftx, rightx = self:GetLeftRightAt(gui.MouseY() - select(2, self:GetPos()))

    local x = gui.MouseX() - self:GetPos()
    return (leftx > x and 1 or 0) + (rightx > x and 1 or 0) == 1
end
```

as you can see this custom panel will be a circle and has circle boundaries. Since IsWithinTraverse in C++ won't allow us to change this at all (since it's a rectangular check by default) it would be great to allow lua to override what it thinks is within it's boundaries.

https://github.com/LestaD/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/src_main/vgui2/vgui_controls/Panel.cpp#L2840

**Comment by 0tt** [comment]
:+1: I had to do this manually just recently for a clickless camera control DModelPanel.

**Comment by robotboy655** [comment]
Added as PANEL:TestHover
