### ISSUE TITLE
Ability to receive VGUI PostMessage calls

### ISSUE THREAD

**Issue by Bo98** [Facepunch/garrysmod-requests#725]
We have a PostMessage function but no ability to receive them. This is hacked in the Slider control by overriding PostMessage but this does not cover any calls made from the engine. It only covers Lua calls which is useless as you might as well use regular functions.

This could either be a OnMessage hook or a way to register a receiver, whatever is easier. Though looking at the source, it seems to be `#define` hell so I don't know how easy it is to fit into Lua.

Alternatively, if this isn't feasible I can makae individual requests for each message that would be nice to be binded. I just thought this would be easier since it covers all possible use cases.

**Comment by robotboy655** [comment]
What exactly do you want this for?

**Comment by Bo98** [comment]
Found a different way to do what I specifically wanted. I'll just create requests for hook bindings for other messages as and when I find them. There was more already bound to hooks already than I thought.
