### ISSUE TITLE
TOOL:Deploy hook doesn't run after tool changing.

### ISSUE THREAD

**Issue by kojiDev** [Facepunch/garrysmod-requests#727]
Wiki says:
TOOL:Deploy()

Called when WEAPON:Deploy of the toolgun is called.
**This is also called when switching from another tool.**

it doesn't actually.
When tool is changing only prev. tool runs Holster, but not new Deploy.

https://github.com/garrynewman/garrysmod/blob/master/garrysmod/gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua#L185
```
	if ( self.last_mode != self.current_mode ) then

	if ( !self:GetToolObject( self.last_mode ) ) then return end
	
	-- We want to release the ghost entity just in case
	self:GetToolObject( self.last_mode ):Holster()
	
	end
```

**Comment by robotboy655** [comment]
It actually does.
![image](https://cloud.githubusercontent.com/assets/3299036/14983278/e3061942-1144-11e6-93f3-1983f44373c4.png)

The code used:

balloon.lua
```
function TOOL:Deploy()
	print("TOOL:Deploy balloonn")
end
```

axis.lua:
```
function TOOL:Deploy()
	print("TOOL:Deploy axis")
end
```

**Comment by kojiDev** [comment]
I forgot to add "doesn't at client when changing".

**Comment by robotboy655** [comment]
It's not really meant to. You can get it to work with self:GetWeapon():CallOnClient("Deploy") if you really need it on client.
