### ISSUE TITLE
file.Find name sorting arguments are backwards

### ISSUE THREAD

**Issue by TehBigA** [Facepunch/garrysmod-requests#730]
The default sorting for file.Find is by name in ascending order (A-Z then a-z, by ascii value) _but_ if the name sorting mode is specified (default arg is probably nameasc) they are backwards. 'namedesc' incorrectly gives you A-Z a-z and 'nameasc' also incorrectly gives z-a Z-A.

**Comment by robotboy655** [comment]
You missed the garrysmod-issues repo, but this will be fixed.

Default sorting is switched to nameasc, nameasc and namedesc functionalities have been corrected.
