### ISSUE TITLE
Gmad does not return any exit codes, necessary for continous integration

### ISSUE THREAD

**Issue by Hoffa1337** [Facepunch/garrysmod-requests#734]
GMad always return the same exit code after execution which is problematic for continous integrations.

A proper list of return codes for Success & Fail would make our life easier.

GMpublish gives proper exit codes so it's expected that Gmad would do the same.

**Comment by DuckyC** [comment]
I have a rough remake of gmad and gmpublish if you are interested. Its made in C#, but should be mono-compliant, if you're interested.

**Comment by robotboy655** [comment]
From what I can tell it always returned non zero on failure. Same goes for `gmpublish`.

gmad is open source here:
https://github.com/Facepunch/gmad
