### ISSUE TITLE
Ability to disconnect/remove ragdoll physics.

### ISSUE THREAD

**Issue by ZehMatt** [Facepunch/garrysmod-requests#736]
The title says it all, would be helpful in creating gibs without having the models. Currently any attempt to mess with the ragdoll physics causes a crash.

**Comment by thegrb93** [comment]
Already requested https://github.com/Facepunch/garrysmod-requests/issues/676

**Comment by ZehM4tt** [comment]
Robotboy says its impossible, well we have a module that removes the constraints so its possible and would do exactly what is needed to create gibs out of any ragdoll.

**Comment by robotboy655** [comment]
There's a difference between removing constraints on a physics object and removing actual bones and vertices from an entity.

I also don't see how you expect to "creating gibs without having the ???models???/create gibs out of any ragdoll." as you'd need to spawn the ragdoll in the first place to remove some of its physics objects/remove constraints or whatever.

**Comment by ZehM4tt** [comment]
I'm fully aware, removing the constraints would be enough in my case. However there is currently no way to access the constraint data or a way to modify them.

**Comment by ZehM4tt** [comment]
https://facepunch.com/showthread.php?t=1516664&p=51070979&viewfull=1#post51070979 Thats basically what I want.

**Comment by robotboy655** [comment]
https://wiki.facepunch.com/gmod/Entity:RemoveInternalConstraint
