### ISSUE TITLE
"sv_thinkticks" ConVar to control how often "Think" hook is called

### ISSUE THREAD

**Issue by uRandomAlex** [Facepunch/garrysmod-requests#737]
"sv_thinkticks" ConVar to control how often "Think" hook is called. If it set to 0 or 1, it will do nothing, else - "Think" hook will be called every [thinkticks_value] tick. This should not affect "Tick", "PlayerTick" and other similar hooks.

**Comment by robotboy655** [comment]
That sounds like a (sorry, but) retarded idea. If you need this for a mod, implement your own hook.

If you want this as some sort "optimization" to your server, then maybe you should consider that something on your server is coded very wrong.
