### ISSUE TITLE
Fix old NPC AI [Request]

### ISSUE THREAD

**Issue by crazycarpet** [Facepunch/garrysmod-requests#74]
I know Nextbot is way better and you don't planning of fixing this error: 

[ERROR] lua/includes/modules/ai_task.lua:91: bad argument #1 to 'StartEngineTask' (number expected, got nil)
  1. StartEngineTask - [C]:-1
   2. Start - lua/includes/modules/ai_task.lua:91
    3. StartTask - gamemodes/base/entities/entities/base_ai/schedules.lua:137
     4. SetTask - gamemodes/base/entities/entities/base_ai/schedules.lua:104
      5. NextTask - gamemodes/base/entities/entities/base_ai/schedules.lua:127
       6. DoSchedule - gamemodes/base/entities/entities/base_ai/schedules.lua:75
        7. unknown - gamemodes/base/entities/entities/base_ai/schedules.lua:22

But if it's not too much trouble I was hoping you could fix this in a future update. Please let me know if you plan to fix this.

**Comment by willox** [comment]
Should be fixed in the dev branch.

**Comment by SpencerSharkey** [comment]
:+1:
