### ISSUE TITLE
Ability to remove/disable/modify Jeep ammo box

### ISSUE THREAD

**Issue by Bo98** [Facepunch/garrysmod-requests#741]
It was fixed a while ago but not everyone wants the behaviour in certain scenarios/gamemodes.

**Comment by robotboy655** [comment]
I have already posted a Lua fix for this, one of the wiki pages I think.

**Comment by robotboy655** [comment]
http://wiki.garrysmod.com/page/GM/PlayerUse

Example 2.

**Comment by Bo98** [comment]
Didn't realise PlayerUse existed. Thanks!
