### ISSUE TITLE
Expose preAngularVelocity to CollisionData structure

### ISSUE THREAD

**Issue by Bo98** [Facepunch/garrysmod-requests#743]
I'm not sure whether `postVelocity` should be added too or not. Would `self:GetVelocity()` and `HitEntity:GetVelocity()` be the same as `postVelocity` at the time `PhysicsCollide` is called? If not, add that too.

**Comment by robotboy655** [comment]
I went ahead and just put in there all of the available info.

New members for PhysicsCollide hooks - OurSurfaceProps, TheirSurfaceProps, HitSpeed, OurNewVelocity, TheirNewVelocity, OurOldAngularVelocity, TheirOldAngularVelocity
