### ISSUE TITLE
util.TraceHull with angle

### ISSUE THREAD

**Issue by Netheous** [Facepunch/garrysmod-requests#748]
We could really use a tracehull that is more flexible, specifying just mins and maxes is way too restricted.

**Comment by robotboy655** [comment]
I don't think this is happening.

**Comment by Netheous** [comment]
Is it too hard for you or?

**Comment by robotboy655** [comment]
There is no way to do this currently, it'd need to be written from scratch editing some of the engine, in my mind this is not worth it spending the time on such a specific feature.

**Comment by Netheous** [comment]
Here's a solution:
`--clockwise
function utilities.doRectIntersect( recta, ang, rectb )
	for i, corner in pairs( recta ) do
		recta[ i ]:Rotate( ang )
	end

	for i, corner in pairs( rectb ) do
		rectb[ i ]:Rotate( ang )
	end

	for i, corner in pairs( rectb ) do
		if corner.x >= recta[ 1 ].x and corner.x <= recta[ 2 ].x then
			if corner.y >= recta[ 1 ].y and corner.y <= recta[ 4 ].y then
				return true
			end
		end
	end

	return false

	hook.Add( "HUDPaint", "visualizeeeee", function()
		surface.SetDrawColor( Color( 255, 0, 0 ) )

		for i, corner in pairs( recta ) do
			surface.DrawLine( corner.x * 10, corner.y * 10, ( recta[ i + 1 ] or recta[ 1 ] ).x * 10, ( recta[ i + 1 ] or recta[ 1 ] ).y * 10 )
			draw.SimpleText( i, "Default", corner.x * 10, corner.y * 10, Color( 255, 255, 255 ), TEXT_ALIGN_LEFT, TEXT_ALIGN_TOP )
		end

		surface.SetDrawColor( Color( 255, 255, 0 ) )
		for i, corner in pairs( rectb ) do
			surface.DrawLine( corner.x * 10, corner.y * 10, ( rectb[ i + 1 ] or rectb[ 1 ] ).x * 10, ( rectb[ i + 1 ] or rectb[ 1 ] ).y * 10 )
			draw.SimpleText( i, "Default", corner.x * 10, corner.y * 10, Color( 255, 255, 255 ), TEXT_ALIGN_LEFT, TEXT_ALIGN_TOP )
		end
	end )
end

local A = --post rotation, this resembles one of rectangles
{
	Vector( 53.581593, 15.937784, 0 ),
	Vector( 78.201782, 11.596581, 0 ),
	Vector( 82.542992, 36.216774, 0 ),
	Vector( 57.922798, 40.557976, 0 ),
}

local B =
{
	Vector( 75, 30, 0 ),
	Vector( 90, 30, 0 ),
	Vector( 90, 45, 0 ),
	Vector( 75, 45, 0 ),
}
utilities.doRectIntersect( A, Angle( 0, 10, 0 ), B )
`

Forgive me for not removing visualisation bits.

**Comment by Netheous** [comment]
Could require putting -ang rather than ang, but you get the idea.
