### ISSUE TITLE
player.GetCount()

### ISSUE THREAD

**Issue by aStonedPenguin** [Facepunch/garrysmod-requests#751]
Would be much faster then #player.GetAll()

**Comment by KingofBeast** [comment]
:+1:

**Comment by Kefta** [comment]
Pretty sure there's an enum for this in the engine; MAX_PLAYER_COUNT or something. Pushing an accessor would be ace. Also, this could be just as fast with the protected table stuff that was suggested in the other player/ents.GetAll suggestion.

**Comment by Acecool** [comment]
I rewrote the entire player table to add a monitored count ( ie +1 on connect and -1 on dc.. also added special functions to get the players that are fully connected vs unconnected vs all )...

So I'll support this.

**Comment by robotboy655** [comment]
Done. It is indeed somewhat faster.
