### ISSUE TITLE
util.DecalEx ignoring w and h parameters

### ISSUE THREAD

**Issue by Mista-Epic** [Facepunch/garrysmod-requests#752]
Changing the w and h parameters of a DecalEx method does not actually change the decal's width or height. No matter what size the material is, DecalEx paints it at a ridiculously huge size.

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/1624

**Comment by Mista-Epic** [comment]
That post doesn't help my problem.

**Comment by robotboy655** [comment]
This is not a place to get help. This is a bug tracker.

**Comment by Mista-Epic** [comment]
I mean that the post you linked didn't solve the problem, thus this is still a bug. I was wondering if that post you linked was supposed to work.

**Comment by bigdogmat** [comment]
The link posted was the issue already made about this issue. You posted this in the wrong place, as well as while an issue for it already exists.

**Comment by Mista-Epic** [comment]
Yeah, sorry. I didn't find that issue when I searched it. I thought I had posted it in issues, so, sorry. I haven't used github ever, so I didn't realize it was in the wrong section.
