### ISSUE TITLE
Optional remap of changelevel2 to changelevel in multiplayer

### ISSUE THREAD

**Issue by xenondice** [Facepunch/garrysmod-requests#753]
Half Life 2 maps call changelevel2 "mapname" in order to progress to a new map. This command doesn't work in multiplayer, but it's essensially the same as changelevel which does. This change would make it possible to play through the hl2 campain in sandbox with friends.

**Comment by thegrb93** [comment]
Can't you alias it in the server.cfg?

**Comment by xenondice** [comment]
Unfortunately not, the alias command doesn't support arguments afaik. Altough running "alias changelevel2 changelevel" does infact make the map call changelevel instead, only with no arguments.

**Comment by thegrb93** [comment]
How about
```
concommand.Add("changelevel2", function(ply,com,arg)
	if ply:IsValid() then return end
	RunConsoleCommand("changelevel", arg[1])
end)
```

**Comment by xenondice** [comment]
Already tried that, it will silently fail, concommand can't override engine commands.

**Comment by thegrb93** [comment]
Oh I misread and thought you said changelevel2 was missing. I guess if it isn't working this should be in garrysmod-issues instead.

**Comment by thegrb93** [comment]
It may be disabled due to crashing issues though, I remember some instability with playing multiplayer maps a long time ago. Don't know where that stands at the moment.

**Comment by xenondice** [comment]
It was disabled on purpose in the source engine. I think it worked in Gmod 12, but was disabled once the engine was updated. (bottom on https://developer.valvesoftware.com/wiki/Trigger_changelevel)

**Comment by xenondice** [comment]
Solved it for the hl2 maps with a dirty workaround. I put

```lua
concommand.Add("changelevelauto", function(ply,com,arg)
    local map = game.GetMap()
    local hl2maps = {"d1_trainstation_01","d1_trainstation_02","d1_trainstation_03","d1_trainstation_04","d1_trainstation_05","d1_trainstation_06","d1_canals_01","d1_canals_01a","d1_canals_02","d1_canals_03","d1_canals_05","d1_canals_06","d1_canals_07","d1_canals_08","d1_canals_09","d1_canals_10","d1_canals_11","d1_canals_12","d1_canals_13","d1_eli_01","d1_eli_02","d1_town_01","d1_town_01a","d1_town_02","d1_town_03","d1_town_04","d1_town_05","d2_coast_01","d2_coast_03","d2_coast_04","d2_coast_05","d2_coast_07","d2_coast_08","d2_coast_09","d2_coast_10","d2_coast_11","d2_coast_12","d2_prison_01","d2_prison_02","d2_prison_03","d2_prison_04","d2_prison_05","d2_prison_06","d2_prison_07","d2_prison_08","d3_c17_01","d3_c17_02","d3_c17_03","d3_c17_04","d3_c17_05","d3_c17_06a","d3_c17_06b","d3_c17_07","d3_c17_08","d3_c17_09","d3_c17_10a","d3_c17_10b","d3_c17_11","d3_c17_12","d3_c17_12b","d3_c17_13","d3_Citadel_01","d3_Citadel_02","d3_Citadel_03","d3_Citadel_04","d3_Citadel_05","d3_breen_01"};
    for i=1,table.getn(hl2maps)-1 do
        if (map == hl2maps[i]) then
            RunConsoleCommand("changelevel", hl2maps[i+1])
            return
        end
    end
end)
```
in lua/autorun/server/changelevelauto.lua and appended
```
alias changelevel2 changelevelauto
```
to cfg/server.cfg.

**Comment by bigdogmat** [comment]
@xenondice Just a note, table.getn is deprecated, just use `#hl2maps`, or better yet `for k, v in ipairs(hl2maps) do`
