### ISSUE TITLE
IsValid on IMesh objects

### ISSUE THREAD

**Issue by McDunkinY** [Facepunch/garrysmod-requests#757]
Can we get a way to check if an IMesh object is valid? Currently, if the mesh is being drawn, and IMesh:Destroy() is called, it will start erroring. Workarounds like checking if Mesh and Mesh.Draw ... do not work, as the Mesh itself isn't nil. I have other ways to prevent the error, was just wondering if it will ever become a thing to call IsValid( IMesh ) without it erroring.

If this is already a thing, please point me in the right direction.

**Comment by gspetrou** [comment]
Could you do type(mesh) == "IMesh". An invalid mesh would just be null right? This is all just a guess.

**Comment by Kefta** [comment]
It would still be an iMesh

**Comment by robotboy655** [comment]
Added IMesh.IsValid.
