### ISSUE TITLE
Vehicle->GetPassengerRole( Player ) or Player->GetPassengerRole()

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#759]
There's currently no way to retrieve which passenger number a player holds.

**Comment by Jvs34** [comment]
Does it matter? We don't have any c++ vehicles supporting more than 1 player at any time so I doubt these functions would be useful at all.

**Comment by Kefta** [comment]
Jalopy has a passenger: http://half-life.wikia.com/wiki/Muscle_Car

**Comment by Jvs34** [comment]
Players can't make use of that, alyx is hardcoded to get in the seat.

**Comment by Kefta** [comment]
Oh, I was under the impression it was usable by all CombatCharacter entities. Well that really sucks, but I guess this isn't needed, then.
