### ISSUE TITLE
Duplicator library should run duplicator functions of base entities.

### ISSUE THREAD

**Issue by AbigailBuccaneer** [Facepunch/garrysmod-requests#76]
Using thrusters as an example:

`gmod_thruster` is based on `base_gmodentity`, which is in turn based on `base_anim`.

Currently, the `MakeThruster` function checks to see if the player has hit the thruster limit, creates the entity, manually applies the model, angle, and position, the player, and then does thruster-specific things.

Given that the model, angle, position etc. is specific to the `base_anim`, and the limit check and setting player is specific to `base_gmodentity`, wouldn't it a lot of sense for there to be duplicator functions for those which are called?

I envision it being called something like the following:

``` Lua
function MakeThruster( player, data, key, key_bck, force, ... )
    if IsValid( player ) and not player:CheckLimit("thrusters") then return false end
    local thruster = duplicator.CreateParent( player, data )
    if not IsValid(thruster) then return false end

   -- do all the thruster-specific stuff below. no need to do SetModel, SetPlayer, etc.
end
duplicator.RegisterEntityClass( "gmod_thruster", MakeThruster, "Data", "key", "force", ... )
```

This would cut down on code not only for addons but for the base GMod entities.

If you like the proposal, I'll happily code it and send a pull request.

**Comment by robotboy655** [comment]
We already have kind of what you are asking for:
https://wiki.facepunch.com/gmod/duplicator.DoGeneric
