### ISSUE TITLE
Mark entity as invalid if Remove is called on it

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#762]
ent:Remove()
ent:IsValid() -- returns true

This makes sense as it's technically still "valid," but nothing should be called on it after Remove is called anyway.

**Comment by willox** [comment]
This was once the case and has since been changed back. The entity is valid up until the EntityRemoved hook is ran.

**Comment by Kefta** [comment]
Thanks for the info.

**Comment by thegrb93** [comment]
http://wiki.garrysmod.com/page/Entity/IsFlagSet FL_KILLME?
