### ISSUE TITLE
Orthographic ProjectedTexture

### ISSUE THREAD

**Issue by wouterpleizier** [Facepunch/garrysmod-requests#765]
Would it be possible to add an option to ProjectedTexture that lets it project orthographically?

I've been experimenting with cascaded shadow mapping (more or less; see [here](https://www.youtube.com/watch?v=4RtnCT6GAjM) and [here](http://images.akamai.steamusercontent.com/ugc/266091945781214799/D75B4FA2A05280D2B0234EE6D4E0B546D262D8C7/)), and it would benefit greatly from such a feature. It's not a cheap effect, but I feel that it would open up a lot of possibilities for mapping, such as day/night cycles and the ability to rely more on models (which can currently look kinda bad since they only use origin-based or per-vertex lighting).

Of course, official support for dynamic sunlight with CSM would be even better, but that might be too much to ask.

**Comment by willox** [comment]
What's the benefit of them being orthographic?

**Comment by wouterpleizier** [comment]
The perspective projection casts the light outward from a single point, causing the shadows to change shape when the position of that point changes. This can be mitigated somewhat by position the ProjectedTexture very far away from the player and using a small FOV, but this isn't perfect and it feels hacky (not to mention that it requires r_farz to be set to a very high number, as the skybox somehow stops rendering otherwise).

An orthographic projection causes the light rays to be parallel, which is much more similar to how sunlight behaves.

**Comment by willox** [comment]
Sounds reasonable. Getting the lighting itself to be orthographic was easy enough, although there seems to be something very wrong with rendering orthographic scenes which is causing the shadows to not draw on any surfaces. I'll push it to the dev branch once I fix it that too.

![hl2_2016-07-11_20-08-42](https://cloud.githubusercontent.com/assets/1499676/16743261/5e1f7814-47a3-11e6-81fb-0cead31ef934.png)
![hl2_2016-07-11_20-09-02](https://cloud.githubusercontent.com/assets/1499676/16743267/61752f18-47a3-11e6-91c3-67808f3230fa.png)

**Comment by willox** [comment]
I took a couple of videos: http://scrnsht.me/u/4Tb/raw http://scrnsht.me/u/5Tb/raw

The red/green/blue axis is the actual point of the projected texture, so you can see it's pretty damn orthogonal. The white lines you see in the back show the illuminated area. I was testing with a pretty small one.

Seeing as you work with projected textures often, have you noticed that at a certain distance props will not render any shadows? I'm wondering if you know a way around that because I'd ideally want to add some method to disable that.

(sorry i haven't committed the changes yet)

**Comment by thegrb93** [comment]
Probably involves adjusting the far plane of the projection matrix?

**Comment by wouterpleizier** [comment]
> (sorry i haven't committed the changes yet)

No worries :sunglasses: Looking good.

I've only noticed that certain props *never* cast shadows, even up close. For instance, the fence models under *props/wasteland*. Maybe the same issue occurs with the distant LODs of certain other props? Setting *r_lod* to 0 would be an easy way to check.

On a semi-related note, it seems that decals/overlays with the LightmappedGeneric shader don't receive shadows. It does work with the DecalModulate shader. Seems to happen in HL2 too. Not a huge bother, but I thought it was worth pointing out :kissing:

**Comment by willox** [comment]
I've been busy the last 10 days. This is actually finished but I've noticed some very very very large performance issues when the projections are running in certain places on certain maps. I want to look in to that before committing anything.

**Comment by willox** [comment]
```lua
local PJ = ProjectedTexture()

PJ:SetNearZ( 0 )
PJ:SetFarZ( 1024 )
PJ:SetOrthographic( true, 64, 64, 64, 64 )
PJ:SetTexture( "effects/flashlight/hard" )
PJ:Update()

hook.Add( "PlayerButtonDown", "", function( ply, button )

	if button == KEY_LALT then
		PJ:SetPos( ply:GetShootPos() )
		PJ:SetAngles( ply:GetAimVector():Angle() )
		PJ:Update()
	end

end )
```

http://wiki.garrysmod.com/page/ProjectedTexture/SetOrthographic
http://wiki.garrysmod.com/page/ProjectedTexture/GetOrthographic

It'll be on the dev branch today.

**Comment by wouterpleizier** [comment]
Works like a charm:

[<img src="http://images.akamai.steamusercontent.com/ugc/268346916421882042/B502C6328F7F42862CF92289310301812E547AF2/">](http://images.akamai.steamusercontent.com/ugc/268346916421881956/53A747733513E9C49D83510D1DD96A7EA3B0F1C2/)[<img src="http://images.akamai.steamusercontent.com/ugc/268346916421882154/AA15711B9A2C4BECF8CADD1536217CAEC60C7894/">](http://images.akamai.steamusercontent.com/ugc/268346916421882113/8EE43C8DA40BBCFC1B7D9EB6853880D1DE4B9794/)[<img src="http://images.akamai.steamusercontent.com/ugc/268346916421882295/8EF50FC8ACA036EDA3A02BB81846A480EE45D140/">](http://images.akamai.steamusercontent.com/ugc/268346916421882254/8C37240601C2884318B2DA1C32C60877ACE40FCC/)[<img src="http://images.akamai.steamusercontent.com/ugc/268346916421882417/3CCB7A5D9EF2FB7C1EAF61DA62C48C5A8EDEFABB/">](http://images.akamai.steamusercontent.com/ugc/268346916421882358/14797C30CA8AE1E12C88571E6E763894D964F013/)[<img src="http://images.akamai.steamusercontent.com/ugc/268346916421882533/0C26BD224F101CE10ED1910266993504C0CBCE79/">](http://images.akamai.steamusercontent.com/ugc/268346916421882481/8584FB6E0EC97FBCB958E7A567CD94D53028721A/)[<img src="http://images.akamai.steamusercontent.com/ugc/268346916421882641/5D0EC18F432FFEFE56E05C6CBD059E3AD88BADAA/">](http://images.akamai.steamusercontent.com/ugc/268346916421882601/C8462F74A63F9F10E097F9C486FF9A2F8EDCC9B0/)

Many thanks!

**Comment by LucasAiden** [comment]
how shadows?
