### ISSUE TITLE
filter_activator_team in Hammer for Custom Team Buttons

### ISSUE THREAD

**Issue by CryptAlchemy** [Facepunch/garrysmod-requests#768]
I'd like to request that the filter_activator_team entity be made to work with Garry's Mod as it doesn't seem to want to recognize any teams in DarkRP or ULX.

Here's the Valve Dev. page: https://developer.valvesoftware.com/wiki/Filter_activator_team

It's something that would really make it way easier for team-based buttons or anything, in fact.

**Comment by Kefta** [comment]
In-case your closing didn't mean you figured this out, there's a filter Lua entity type where you can make this yourself

**Comment by CryptAlchemy** [comment]
Oh, that would be sweet! Which entity is the one that I can edit to do this?

**Comment by CryptAlchemy** [comment]
I sort of found a way to do it but it's a bit sketchy because it forces whoever gets access to the door to be on team 1 in DarkRP.

**Comment by neico** [comment]
I think he meant this: https://github.com/garrynewman/garrysmod/blob/master/garrysmod/gamemodes/base/entities/entities/base_filter.lua

VDC is only for developer stuff related to the engine itself, for gmod use https://github.com/garrynewman/garrysmod and http://wiki.garrysmod.com

**Comment by robotboy655** [comment]
Yes, you can code your own filter_ entities now, and they will work properly with triggers.

**Comment by CryptAlchemy** [comment]
Okay sweet! Thanks for your help everyone!
