### ISSUE TITLE
Add BASSStream:Set3DEnabled(bool)

### ISSUE THREAD

**Issue by wyozi** [Facepunch/garrysmod-requests#769]
Seems like `ChannelSet3DAttributes` supports dynamic toggling of 3d functionality (as long as the 3d flag was passed in creation?)

**Comment by Jvs34** [comment]
@Grocel can you test that on your module?

**Comment by Grocel** [comment]
Sure, I can take a look at it. I need it as well for my radio addon. For now I just recreate the channel when I need to switch the 3D state.

**Comment by Grocel** [comment]
I did it. It works like a champ on channels with a 3D flag. But you can not use it on channels without this flag.

**Comment by robotboy655** [comment]
Added.
