### ISSUE TITLE
Add HTTPRequest.followRedirects

### ISSUE THREAD

**Issue by wyozi** [Facepunch/garrysmod-requests#770]
At the moment HTTP seems to follow redirects automatically. It would be nice to control this with either a HTTPRequest parameter for following redirects, or if that is not possible then at least a new parameter to success callback that is the final URL the redirect chain ended at.

**Comment by neico** [comment]
It's not possible with ISteamHTTP (which to my knowledge is what the http lib still uses internally) as such a option isn't exposed...

**Comment by wyozi** [comment]
I see, seems like ISteamHTTP doesn't contain methods to get the redirected-to URL either.
