### ISSUE TITLE
Enable developer console by default for new users

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#771]
I'm sure this has been requested before but I don't see why not. Trying to guide users in-game or on Facepunch on how to enable their console just to bind a key or enter some other option is a little bit of a hassle -- at the least an extra step.

**Comment by willox** [comment]
con_enable does nothing in gmod. Should probably change the options menu to reflect that. (Just tell them to press shift+escape, it can't be unbound.)
