### ISSUE TITLE
Add missing CMoveData modifiers/accessors

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#773]
https://github.com/LestaD/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/se2007/game/shared/igamemovement.h#L38

Specifically:
-m_outStepHeight
-m_outWishVel
-m_outJumpVel
-m_vecConstraintCenter
-m_flConstraintWidth
-m_flConstraintSpeedFactor
-m_bGameCodeMovedPlayer

**Comment by Jvs34** [comment]
-m_vecViewAngles already bound on http://wiki.garrysmod.com/page/CMoveData/SetMoveAngles
-m_vecAbsViewAngles already bound on http://wiki.garrysmod.com/page/CMoveData/SetAbsMoveAngles

**Comment by Kefta** [comment]
Quickly read "move" and thought they were akin to the directional move numbers. Thanks.

**Comment by Cynosphere** [comment]
Bump. Need m_outWishVel for movement scheme from a sourcemod I'm trying to port.

**Comment by robotboy655** [comment]
Added CMoveData.Set/Get for: ConstraintWidth, ConstraintSpeedScale, ConstraintCenter, FinalIdealVelocity, FinalJumpVelocity, FinalStepHeight

Don't see the point in adding a binding for `m_bGameCodeMovedPlayer` at this time.
