### ISSUE TITLE
Adjust RAM Usage through Main Menu

### ISSUE THREAD

**Issue by watssupya** [Facepunch/garrysmod-requests#777]
Possible to implement to Garry's Mod? Got tired of going over 3 GB of RAM.

**Comment by robotboy655** [comment]
No.

**Comment by Kefta** [comment]
You can do this in the command line with -heapsize

**Comment by bmwalters** [comment]
If you lower RAM to below what the game requires, you may experience crashes.

**Comment by watssupya** [comment]
nah, trying to prevent garry's mod from going over 3 gb
