### ISSUE TITLE
navmesh.GetWalkableSeeds()

### ISSUE THREAD

**Issue by maximlahaxim** [Facepunch/garrysmod-requests#778]
Can a function please be added that will return all walkable seeds that're on a map?

I need it for a navigation-related thing I'm creating.

**Comment by robotboy655** [comment]
Isn't this only for navmesh creation, i.e. you have to manually add walkable seeds before calling nav.Generate() or whatever and they will disappear afterwards.

Just making sure you are asking for what you think you are asking.

**Comment by maximlahaxim** [comment]
@robotboy655 Oh, they disappear after they're used to create a navmesh? Welp, that's not good. At the very least, is there a way to return all of them through a function while they exist?

**Comment by robotboy655** [comment]
What do you need that for? I feel like you are trying to do something you shouldn't be doing or going the wrong way around of doing that.
