### ISSUE TITLE
trace.HitColor - Color-Blind functionality

### ISSUE THREAD

**Issue by Acecool** [Facepunch/garrysmod-requests#78]
A while back I had a player that complained of being color-blind. They had trouble seeing the cross-hair and other things at times. I'd like to have functionality in a trace return that returns the color of the pixel that the trace hits. 

Or pixel color on the screen. That way I can dynamically change the cross-hair color and other things based on the background color

Maybe a new surface.SetDrawColor( ) that works by automatically returning the inverse of each pixel and transferring it through to an element. A line from top left to bottom right would be multicolored, but should be fully visible. But this would hopefully ensure that color-blind people can always see hud-elements as there is always a direct opposite color coming back at them.

This may not work on all color-blind people, it depends on the severity. But there is a white background and you render a black box with automated white text ( inverse of the parent each layer ) it could be beneficial. Likewise a blue background, orange might help, it might not. But some sort of automated option for color-blindness in game might be a great way to appeal to more players.

**Comment by robotboy655** [comment]
trace.HitColor is not happening.
