### ISSUE TITLE
LuaJIT 2.0.4

### ISSUE THREAD

**Issue by uRandomAlex** [Facepunch/garrysmod-requests#780]
Update LuaJIT to 2.0.4.
http://repo.or.cz/luajit-2.0.git/shortlog/refs/tags/v2.0.4 - all changes.

**Comment by neico** [comment]
I'd prefer this overview instead: http://luajit.org/changes.html and yeah, there are quite some fixes that might help "a bit" (I was honestly suprised that jit.version reported 2.0.3 considering how old 2.0.4 is...)

**Comment by robotboy655** [comment]
I guess https://github.com/Facepunch/garrysmod-requests/issues/1036
