### ISSUE TITLE
Stop Failed to Load spam.

### ISSUE THREAD

**Issue by LuaTenshi** [Facepunch/garrysmod-requests#783]
When something fails to load the game should stop trying to constantly load it again unless there has been an update to the files. I often find that things like this cause massive amounts of lag.

Maybe have some non-annoying non-intrusive error sound to replace sounds that can't be found just like the ERROR model replaces models that can't be found?

**Comment by Kefta** [comment]
I think an error sound would be too obnoxious, but :+1: for showing the missing message only once

**Comment by LonelyWolf-GitHub** [comment]
![6ody](https://cloud.githubusercontent.com/assets/16419827/16935421/47b8d6f8-4d2d-11e6-9dc1-4c77770115e2.png)

It causes huge FPS drops, there should be a console variable added to disable loading something that is not there, or maybe something like LuaTenshi said.

**Comment by LonelyWolf-GitHub** [comment]
@

**Comment by LuaTenshi** [comment]
Making a console variable wouldn't work because of https://github.com/Facepunch/garrysmod-requests/issues/358 and https://github.com/Facepunch/garrysmod-requests/issues/269

Instead it should be like I suggested above. "Sound failed to load? Notify the user, and lets not attempt to load it again unless there is a file update or the user rejoins."

**Comment by LonelyWolf-GitHub** [comment]
Yea, that would work much better and probably be smoother.

**Comment by LuaTenshi** [comment]
I mean the errors are not that annoying. The problem is that your fps drops to like 1. Even when not in the console. (Imagine joining a sandbox server and being fine with seeing errors but not wanting to download a million files.)

**Comment by Bletotum** [comment]
robotboy, you should read more carefully
the issue isn't that anyone wants error messages removed, but that the event causing the error (the missing file trying to load) is supposedly the cause of the lag and should not occur multiple times
