### ISSUE TITLE
More 'freedom'/overriding

### ISSUE THREAD

**Issue by originalwhitestar** [Facepunch/garrysmod-requests#790]
Make it able to initialize certain addons already whilst Gmod boots, like checking the /addons/ folder for addons.txt's wich contain a specific keyvalue to boot with gmod, so you can override specific things, like main menu. So users dont have to manually move specific files to the /lua/ folder.

tl;dr: Make it possible to easy-install things like this: https://github.com/robotboy655/gmod-lua-menu

**Comment by robotboy655** [comment]
No main menu access for addons.

I don't see how it is not easy-install when all you have to do is drag'n'drop the files into a certain folder, just like an addon.

**Comment by originalwhitestar** [comment]
I mean, maybe 'more' access for workshop, so people can upload custom menus to the workshop.

**Comment by Kefta** [comment]
Then addons can break it and people will complain.

**Comment by originalwhitestar** [comment]
I mean, the addon itself has to put the vernumber of Gmod in it, and when gmod updates, it automaticly disables that addon wich doesnt has the vernumber.

**Comment by robotboy655** [comment]
What will that do? Its like you are attempting to persuade us to make the game worse for the end user.
