### ISSUE TITLE
Add CLuaLocomotion:GetFaceTowardsAngle

### ISSUE THREAD

**Issue by maximlahaxim** [Facepunch/garrysmod-requests#794]
Hey. This request is simple, I'd like to have a function that lets you get the angle at which a Nextbot's locomotor is currently facing.

I need this for bot I'm creating.

**Comment by robotboy655** [comment]
Locomotors do not have angles. The function CLuaLocomotion:FaceTowards sets angles of the bot itself. Same as SetLocalAngles. The only reason it exists to do abide by CLuaLocomotion:GetMaxYawRate.
