### ISSUE TITLE
Command to disable thirdperson

### ISSUE THREAD

**Issue by markusmarkusz** [Facepunch/garrysmod-requests#797]
You can enable thirdperson view by using concommand "thirdperson".
But you can't disable it without settings sv_cheats to 0.

So why not add a command to disable it or make thirdperson like thirdperson_mayamode.

**Comment by robotboy655** [comment]
You can't enable it without sv_cheats set to 1.

**Comment by markusmarkusz** [comment]
@robotboy655 
That's true.
But if I have sv_cheats set to 1 and if I want to leave the thirdperson view then it would be nice if I can do this without settings sv_cheats to 0.
If I test something then I always have sv_cheats 1 because it's easier if I for example need thirdperson view or lua_run_cl.
And I'm too lazy to set sv_cheats to 0 only for leaving thirdperson.
thirdperson_mayamode is also leaveable without settings sv_cheats to 0. So why not thirdperson?

**Comment by robotboy655** [comment]
And I am too lazy to fulfill this request for a single person that makes no sense whatsoever.

**Comment by markusmarkusz** [comment]
I only have to disable sv_cheats because there is no other way to disable thirdperson view after enabling it.
I don't want to disable it but I have to because there is no other way.

If there would be a way to disable thirdperson by using the thirdperson command then I hadn't have to disable sv_cheats.

I know that sv_cheats is required to use thirdperson.
But I don't understand why I have to disable sv_cheats to disable thirdperson.

**Comment by robotboy655** [comment]
You can disable it with ```firstperson```.

**Comment by markusmarkusz** [comment]
Okay.
Thanks, @robotboy655
