### ISSUE TITLE
Allow omitting slot parameter to NetworkVar

### ISSUE THREAD

**Issue by wyozi** [Facepunch/garrysmod-requests#798]
This would assign the variable to the first free slot found.

Reasoning:
- Slot doesn't matter anywhere in Lua context AFAIK, why force developer to provide it?
- SetupDataTables inheritance chain is significantly easier to setup if you don't have to check the whole chain for colliding slots.

**Comment by Kefta** [comment]
At the very least, having a function to tell if a slot is taken would be much better than having to override DTVar. wyozi's solution is still the best, though.

**Comment by Jvs34** [comment]
If we override NetworkVars to make use of NW2Vars instead of dtvars, we can use the name of the networkvar as the index without having to worry about the 64 slots limit.

**Comment by Jvs34** [comment]
Although now that I think about it, that would break support for old saves that have networkvars with saved indexes fro 0 to whatever.

Disregard
