### ISSUE TITLE
Make the changing of a Nextbot's local angles when using PathFollower:Update optional

### ISSUE THREAD

**Issue by maximlahaxim** [Facepunch/garrysmod-requests#799]
So, when you call PathFollower:Update, the Nextbot it is called on has their local angles changed to face whichever direction they're moving.

Can an argument be added to PathFollower:Update which makes this angle-setting optional? I'd like to make my bot be able to appear that it's walking backwards/sideways.

**Comment by robotboy655** [comment]
http://wiki.garrysmod.com/page/CLuaLocomotion/FaceTowards ???

**Comment by robotboy655** [comment]
http://wiki.garrysmod.com/page/Entity/SetAngles ????????????????????????
