### ISSUE TITLE
Updated spawnlists

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-requests#804]
For advanced building I would suggest adding more props to the current spawnlists.

Offtopic:
Is there any way I can send in a customized spawnlist, because I could modify the spawnlist myself and send the updated list to the devs?

**Comment by Kefta** [comment]
You can PR the spawnlists yourself.

**Comment by mcNuggets1** [comment]
Will do. Thx.

**Comment by mcNuggets1** [comment]
I just love you, robotboy655.
Thank you for being a gmod dev.
