### ISSUE TITLE
Port func_precipitation functionality from Left 4 Dead 2 into Garry's Mod

### ISSUE THREAD

**Issue by MissingNoGuy55** [Facepunch/garrysmod-requests#809]
func_precipitation in L4D2 has much more uses for the entity, including collision detection to make placement of rain easier. This would definitely benefit mappers and the like if this was ported over to Garry's Mod, considering HL2's rain is convoluted and difficult to set up.

**Comment by robotboy655** [comment]
We cannot port anything from Left 4 Dead (2), Portal 2, CS:GO, etc. I might port the particle rain from Alien Swarm but I am not sure how much worthwhile it will be.

**Comment by MissingNoGuy55** [comment]
Even the particle rain from Alien Swarm would suffice. Please do that if you can, and thank you for replying!

**Comment by jbuug** [comment]
Do you mean like the particles

**Comment by CaskoChan** [comment]
This feature would be extremely appreciated by mappers as the default rain,snow,ash is garbage.

**Comment by robotboy655** [comment]
Added particle rain/snow/ash support.
