### ISSUE TITLE
TF2 Map Events

### ISSUE THREAD

**Issue by jbuug** [Facepunch/garrysmod-requests#810]
When players are on tf2 custom maps. for example koth_wubwubwub_remix_vip i notice the map dosent play out the crazy like it dose in tf2 but when i look in console it cant find the events. so maby we can try to port over game events from games like tf2 ect.

**Comment by robotboy655** [comment]
There will never be full support for all the mountable game entities. ( For licensing reasons afaik ) Deal with it.
