### ISSUE TITLE
Add "no addons" - Launch option for GMod

### ISSUE THREAD

**Issue by OmegaExtern** [Facepunch/garrysmod-requests#812]
Sometimes we want to start GMod without any addons (or non-builtin gamemodes), and in order to do that we would have to:

- Rename "addons" folder to something else.

But, GMod will automatically start downloading Workshop addons (on startup). However, if you are offline, obviously that would happen to work.

Or,
- Use "Disable All" button in Addons page from main menu.

But, unfortunately that's limited only to Workshop addons (you have subscribed to), so if you have cloned an addon using SVN (in such case, you would have a folder instead of a ".gma" file), which means GMod will load those non-Workshop addons. However, if you only have addons from Workshop, then that would logically work.

Or,
- Unsubscribe from all GMod Workshop addons.

This is essentially the same as the second option, btw I am sure there are auto-JavaScript which could help you manage it this way.

There are a few more options that I haven't posted, as I just wanted to point out three of them as an example.
Wouldn't it be so much easier to have a launch option (I am thinking of "-vanilla" or "-noaddons"), so that we can *tell* ![quotes](https://facepunch.com/fp/emotes_std/quotes.gif) GMod to not load/download any addons (including non-Workshop)?

**Comment by Bo98** [comment]
`-noaddons -noworkshop` should work already. The former only works on the dev branch atm.
