### ISSUE TITLE
Don't print "lua/includes/module.lua (File not found)" error on failed require

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#813]
require already throws an error when it fails to find a file -- printing this is redundant and makes it unpreventable if you use require w/ pcall.

**Comment by meepdarknessmeep** [comment]
Maybe it should be print
`Couldn't find library '%s'`

**Comment by robotboy655** [comment]
`require` calls `include` for Lua modules, and thus has same issues as it in relation to `pcall`.

Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/2498
