### ISSUE TITLE
Create fluid loading screen and C++ gamemode

### ISSUE THREAD

**Issue by StidOfficial** [Facepunch/garrysmod-requests#814]
Modify loading system for create interactive loading screen in thread. And remove source or optional source loading panel.

And have a possibility to create a dll gamemode for fast and optimize performance and custom engine.

**Comment by robotboy655** [comment]
Sure, done aaaaand done

**Comment by Kefta** [comment]
lmao

**Comment by StidOfficial** [comment]
Garry's Mod freeze in loading map, download and mount addon just no freeze in full loading.
Ex: In BF1 it's possible to interacting with the element in loading screen.

And how to remove source loading box for create a loading in a full screen ?
http://www.hostingpics.net/viewer.php?id=762831GMODLoading.png

And it's possible to create full gamemode in C++ library without lua and download dll gamemode ?

**Comment by bmwalters** [comment]
@StidOfficial Yes, it does freeze while mounting. This is a known issue and won't be fixed unless the loading screen rendering/logic is moved to a separate thread, which probably won't be done for difficulty vs benefit reasons.

You can't currently remove the source loading box, and you definitely won't be able to from the loading screen code.

It is technically possible to create a full gamemode in C++, but it has never been done before and would be fairly difficult.

**Comment by Kefta** [comment]
You cannot remove the loading box. It has been requested before for the loading screen to be put on a separate thread to prevent the loading box from being uninteractable during loading, but nothing has come of it. It's not realistically possible to create a C++ gamemode, but it's possible if you use Source's gamerules format, and both the server and client have the modules you made -- it would take a lot of knowledge of the internal layout of Garry's Mod gamemode system, though.

**Comment by StidOfficial** [comment]
Okey, any effort can be done for threading loading screen ?
I know, in a old version was it possible to download à dll. It's not possible to add a alert message before connect to the server for avoid viruses ?

**Comment by bmwalters** [comment]
I don't know the scale of effort required to improve the loading screen, but I estimate that it's quite a bit of work for not much of an important improvement; after all the game part of GMod is once you've loaded, not while you're on the screen.

And no, there would still be too much of a security vulnerability to allow servers to simply distribute and run DLLs.

**Comment by StidOfficial** [comment]
I do not think that threading loading function. Mostly to add in lua HideLoadingBox() function for no draw is very hard. Its would for player to interacte with a loading screen for wait the payer on longer downloading. It remains a good idea who could interest a lot of people.

**Comment by Kefta** [comment]
The loading box provides important information as well as a way to exit. Hiding it would not only be impractical but not to the benefit of the community

**Comment by StidOfficial** [comment]
CS:GO doesn't have a Source box. It same things.

**Comment by Kefta** [comment]
But TF2, CS:S, and HL2:DM do. What's your point?

**Comment by StidOfficial** [comment]
Its not bother anyone is removed. And is more beautiful to integrate loading information in html loading screen.

**Comment by Kefta** [comment]
Those are two polar assertions that you are making with no evidence to back them up

**Comment by StidOfficial** [comment]
That's better to have a loading screen in fullscreen that have Source box that ruins everything. Best to ask on Facepunch this question.

**Comment by Kefta** [comment]
So let's remove a loading progress counter with exit button just because it "ruins everything" in your opinion. It's a huge loss of convinence for the gain of nothing.

**Comment by StidOfficial** [comment]
That's why I asked of thread loading for interacting in loading screen for button, scrollbar, ect... There is ECHAP for exit. In CS:GO don't have exit button it is not so disturbing that his. It same on Dota. You really do not think it would be better while all integrated into the loading screen for better design ?

**Comment by Kefta** [comment]
I personally prefer having an exit button since it has always been a feature of Garry's Mod, and the escape shortcut is not explicitly stated. That's not to say having a multi-threaded loading screen would be bad, but I don't think removing the loading box is a step in that.

**Comment by uRandomAlex** [comment]
@StidOfficial You already can create gamemode using C++. Look at [Binary Modules](https://wiki.garrysmod.com/page/Creating_Binary_Modules) - you just need to require them in gamemode's base Lua file.

**Comment by StidOfficial** [comment]
I just ask to have a header with a class of architecture such as lua except bypassing LuaJit but simply directly in C++. For facilitate dev modules to create gamemode. It does not matter I'll use valve header for to do it myself.
