### ISSUE TITLE
Add engine.SentenceLength(), LookupSentence()

### ISSUE THREAD

**Issue by zambony** [Facepunch/garrysmod-requests#815]
Apparently the engine has a function to retrieve the total sound duration of a sentence, given its index.
It also has the function `SENTENCEG_Lookup` to retrieve the index of a sentence given its name as a string.

Could these possibly be added to Lua?

**Comment by robotboy655** [comment]
How is LookupSentence() useful? No Lua function takes sentence index as far as I can tell.

Added SentenceDuration( name )
