### ISSUE TITLE
Bindings for Pickup_*

### ISSUE THREAD

**Issue by ZehM4tt** [Facepunch/garrysmod-requests#817]
I'm currently porting the gravity gun to lua in order to provide the super gravity gun within my gamemode. 

I reached a point where I noticed that some bindings are missing to fire events on the entities that are held, thrown, punted, etc. which causes some outputs to never fire which is problematic for the campaign.

It would be nice to get the following bindings:

```
void PlayerPickupObject( CBasePlayer *pPlayer, CBaseEntity *pObject );
void Pickup_ForcePlayerToDropThisObject( CBaseEntity *pTarget );

void Pickup_OnPhysGunDrop( CBaseEntity *pDroppedObject, CBasePlayer *pPlayer, PhysGunDrop_t reason );
void Pickup_OnPhysGunPickup( CBaseEntity *pPickedUpObject, CBasePlayer *pPlayer, PhysGunPickup_t reason = PICKED_UP_BY_CANNON );
bool Pickup_OnAttemptPhysGunPickup( CBaseEntity *pPickedUpObject, CBasePlayer *pPlayer, PhysGunPickup_t reason = PICKED_UP_BY_CANNON );
bool Pickup_GetPreferredCarryAngles( CBaseEntity *pObject, CBasePlayer *pPlayer, matrix3x4_t &localToWorld, QAngle &outputAnglesWorldSpace );
bool Pickup_ForcePhysGunOpen( CBaseEntity *pObject, CBasePlayer *pPlayer );
bool Pickup_ShouldPuntUseLaunchForces( CBaseEntity *pObject, PhysGunForce_t reason );
AngularImpulse Pickup_PhysGunLaunchAngularImpulse( CBaseEntity *pObject, PhysGunForce_t reason );
Vector Pickup_DefaultPhysGunLaunchVelocity( const Vector &vecForward, float flMass );
Vector Pickup_PhysGunLaunchVelocity( CBaseEntity *pObject, const Vector &vecForward, PhysGunForce_t reason );

CBaseEntity *Pickup_OnFailedPhysGunPickup( CBaseEntity *pPickedUpObject, Vector vPhysgunPos );
```

I'm not quite sure what the best way would be, but most of them just cast them to IPlayerPickupVPhysics if supported, so adding ENTITY Metatable generics would work I suppose.

Thanks.

**Comment by willox** [comment]
Pickup_OnPhysGunDrop
Pickup_OnPhysGunPickup
Pickup_GetPreferredCarryAngles

**Comment by Kefta** [comment]
Also, there's already DropEntityIfHeld (http://wiki.garrysmod.com/page/Global/DropEntityIfHeld) for Pickup_ForcePlayerToDropThisObject, and AllowPlayerPickup (http://wiki.garrysmod.com/page/GM/AllowPlayerPickup) can hackily be used for PlayerPickupObject

**Comment by willox** [comment]
The idea is that you can trigger entities' gravity-gun specific behaviour. Like when you pick up roller mines.

**Comment by ZehM4tt** [comment]
Thank you a lot!
