### ISSUE TITLE
Add other common gui images for TOOL.Information

### ISSUE THREAD

**Issue by Mista-Tea** [Facepunch/garrysmod-requests#819]
If the title doesn't make sense, what I am requesting are more gui images that we can use with the new TOOL.Information style (like the current e.png, lmb.png, rmb.png, etc): 

```
TOOL.Information = {
    {
        name  = "shift_left",
        icon2 = "gui/e.png",
        icon  = "gui/lmb.png"
    }
}
```

I realize there are probably way more keyboard buttons available than what you'd like to create images for, which is why I am just asking for the more common missing ones. Specifically:

- Shift
- Alt
- Control (Ctrl)

With these additions, tool makers like myself could present users with more key combinations in a manner consistent  with the current LMB/RMB/E/R images.

**Comment by robotboy655** [comment]
Idealistically speaking you should not be using movement keys in your tool key combinations. Alt is not even bound by default.

**Comment by Mista-Tea** [comment]
The only other alternative that I know of would be adding more alphanumeric key images which would conflict with the spawnmenu (Q), undo (Z), voice chat (X), context menu (C), noclip (V), flashlight (F), and team chat (T) keys. Disregarding the rest of the keys since they are out of reach for the left hand.

Are there no other options? Or will we be limited to just these forever:
```
1) left
2) right
3) r
4) e + left
5) e + right
```
Not counting ```e + r + left``` and ```e + r + right``` since we can't show 3-key combinations.

**Comment by robotboy655** [comment]
I feel like if 5 key combinations are not enough for your tool, you should reconsider the UI of your tool.

**Comment by Mista-Tea** [comment]
Alright, thanks for your time.
