### ISSUE TITLE
Rebind SnapEyeAngles/SetLocalViewAngles

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#820]
https://maurits.tv/data/garrysmod/wiki/wiki.garrysmod.com/index75ee.html

No idea why this was removed.

**Comment by robotboy655** [comment]
http://wiki.garrysmod.com/page/Player/SetEyeAngles ?

**Comment by Kefta** [comment]
I was doing some testing around in HLTV and it seems that SetEyeAngles doesn't set the fixangle parameter which causes some weird bouncing, but it doesn't matter anyway
