### ISSUE TITLE
to find path from a texture 

### ISSUE THREAD

**Issue by BALIST0N** [Facepunch/garrysmod-requests#821]
a reverse function for " surface.GetTextureID "  ?

kind of : `surface.GetTexturePath(number TextureID)`

return string with the full path of a texture

this could help a lot for menus

**Comment by robotboy655** [comment]
Exactly how this would help?

**Comment by BALIST0N** [comment]
it would avoid having to create a search function who does not always work.. (with file.find etcc..)

**Comment by robotboy655** [comment]
What? How searching and surface.GetTextureID even remotely related to each other?

**Comment by BALIST0N** [comment]
i don't know, i try to find a way to get path of a texture    :°))))

**Comment by robotboy655** [comment]
I am not sure even you understand what you want.

Use Material()

**Comment by thegrb93** [comment]
http://wiki.garrysmod.com/page/ITexture/GetName
