### ISSUE TITLE
Allow the engine to control the rendergroup of "ai" SENTs

### ISSUE THREAD

**Issue by NO-LOAFING** [Facepunch/garrysmod-requests#824]
The dev branch introduced this feature, where setting **ENT.RenderGroup = false** would let the engine control the entity's rendergroup automatically:

> RenderGroup of SENTs and SWEPs is now defaulted to engine default unless manually overridden ( instead of defaulting to OPAQUE render group )

Would it be possible to get this for "ai" ents as well? It doesn't seem to apply to them.

**Comment by robotboy655** [comment]
Done.
