### ISSUE TITLE
WEAPON:SetLastShootTime( float Time )

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#825]
This allows WEAPON:LastShootTime() to support weapons that don't use FireBullets.

**Comment by Acecool** [comment]
You can already set the last primary / secondary fire time.... you don't need last shoot time?? or am I missing something...  My swep base works fine with those 2 without using LastShootTime and I use a custom bullet system that I created.

**Comment by Kefta** [comment]
@Acecool https://wiki.garrysmod.com/page/Weapon/LastShootTime

**Comment by Acecool** [comment]
Cheers; I've never used it but this can be redirected to use the swep time last primary time... Also, for those using the bullet callback to create penetration / ricochets will LastShootTime be updated each time the trace penetrates? I'm guessing it will...

**Comment by Kefta** [comment]
Penetration/callbacks happen on the same tick as the FireBullets call, so it wouldn't matter in this case.

**Comment by robotboy655** [comment]
Added Weapon.SetLastShootTime( time = CurTime() )
