### ISSUE TITLE
Allow GetInternalVariable to access FIELDs

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#826]
No reason to generate the SaveTable for accessing a single variable.

**Comment by ZehM4tt** [comment]
I would still prefer a different lua binding to access all the fields properly. Even function pointers should get a specific userdata type so one could serialize the entire table without any conflicts or missing data.

This would actually allow us to create real snapshots and load them the same way savegames work. It is crucial to know the field type especially with the local and world position fields same for the timestamp fields.

**Comment by Kefta** [comment]
Solved in https://github.com/Facepunch/garrysmod-requests/issues/1002
