### ISSUE TITLE
Add a function to regenerate mipmaps for a rendertarget

### ISSUE THREAD

**Issue by wyozi** [Facepunch/garrysmod-requests#829]
Namely something that would call `glGenerateMipmaps` on the texture object of a rendertarget.

**Comment by wyozi** [comment]
Reasoning in case I (or someone else) stumbles upon here later: 3D2Ds built using primitives suffer from aliasing. First rendering the primitives into a framebuffer, generating mipmaps and then rendering the texture using 3D2D would presumably fix this.

I guess rendering the primitives to texture and then rendering the texture using a nice filter mode would work as well, but mipmaps are cool.

**Comment by CapsAdmin** [comment]
Yes something like ITexture:GenerateMipMaps() would be very useful.

**Comment by robotboy655** [comment]
As discussed here I do not believe this would be of any benefit for render targets.

https://github.com/Facepunch/garrysmod-issues/issues/4718
