### ISSUE TITLE
Clientside/shared equivalent too Entity:SetLayerPlaybackRate()

### ISSUE THREAD

**Issue by bizzclaw** [Facepunch/garrysmod-requests#833]
I'm not sure if this is doable, but it seems odd that a function crucial for animation control is restricted to the server only. For many instances it would be preferable if there was a clientside version of this, most notably in prediction for weapon animations.

Since I'm using a custom animation rig with which I have custom attacking, reloading, swinging, ect animations, I'd like to be able to set the playback rate of these gestures, but not even the serverside-specific BaseAnimatingOverlay functions work on players. (which might be a bug report of it's own).

I understand I'm probably the only one who would use something like this, so it's understandable if this isn't worth being done. Either way, I figure it wouldn't hurt to ask.

Thank you.

**Comment by robotboy655** [comment]
Basically is fulfilled by https://github.com/Facepunch/garrysmod-requests/issues/1504

**Comment by bizzclaw** [comment]
Thank you, you have unlocked a massive world of opportunity for me.
