### ISSUE TITLE
Give NoCollides an Identity number

### ISSUE THREAD

**Issue by sammyt291** [Facepunch/garrysmod-requests#836]
Hello,

I have been making a Constraint Checker script for use on my servers so we can determine lag candidates etc,

And it has all been very successful until I added NoCollides, unlike other constraints NoCollides do not have the Identity key and thus cannot be uniquely referenced for counting and so on.

It would be great to have NoCollides have an Identity assigned to them within their UserData like every other constraint for scripting use.

Best regards,
Sam.

**Comment by robotboy655** [comment]
I don't follow.

**Comment by sammyt291** [comment]
Constraint entities all have the ID of 0 so I looked further into their userdata and found that all constraints have a key called Identity, which is unique to each constraint made on the server.

So that is useful when counting or otherwise referencing constraints.

NoCollides are the only constraint not to have this Identity key within its userdata

**Comment by robotboy655** [comment]
![image](https://cloud.githubusercontent.com/assets/3299036/19656545/2706ec9e-9a29-11e6-836b-0a6bb2159fe1.png)

It's from one of your addons.

**Comment by Bo98** [comment]
This is from Advanced Duplicator 2.

Internally, it is just [constraint:GetCreationID()](https://wiki.garrysmod.com/page/Entity/GetCreationID).
