### ISSUE TITLE
Make net library better by allowing to send messages using raw IDs, not only strings

### ISSUE THREAD

**Issue by uRandomAlex** [Facepunch/garrysmod-requests#837]
Make net library better by allowing to send messages using raw IDs, not only strings. Here is all I can help you with, this probably will help you to get a better idea on what I want:
```
net.ReceiversByID = {}

--
-- Set up a function to add network messages receive callback by ID (net.Receive but for ID messages)
--
function net.ReceiveByID( id, func )
	net.ReceiversByID[id] = func
end

--
-- A message has been received from the network..
--
function net.Incoming( len, func )
	local i = net.ReadHeader()
	local func = net.ReceiversByID[i]

	if ( !func ) then -- my additions. ID receivers have priority.
		local strName = util.NetworkIDToString( i )
		if ( !strName ) then return end
	
		func = net.Receivers[ strName:lower() ]
		if ( !func ) then return end
	end

	--
	-- len includes the 16 bit int which told us the message name
	-- why don't make it a uint? or I don't understand something because I can't code C?
	--
	len = len - 16
	
	func( len, client )
end

--
-- A message has been started (move net.Start implementation to Lua)
--
function net.Start( msg )
	local id = util.NetworkStringToID( msg )
	return net.StartID( id ) -- net.StartID is a new function to start net-message using ID
end
```

**Comment by robotboy655** [comment]
Uh, I really don't get what you are trying to say.

The string is the id, net messages already use util.NetworkStringToID internally, that's why you need to do util.AddNetworkString sometime before you send the message, the string id of the net message is not sent, only its ID is.

**Comment by uRandomAlex** [comment]
@robotboy655 Yeah, I know, I want to use net library with raw message ID, not converted to a string.

**Comment by robotboy655** [comment]
what on earth for

**Comment by uRandomAlex** [comment]
@robotboy655 Bypassing limit of stringtable, more efficient networking or some hidden shit like anticheats.

**Comment by robotboy655** [comment]
Since when 8000 is not enough

**Comment by uRandomAlex** [comment]
@robotboy655 IDK, that's only one of the reasons. But seeing as how garry made net.Incoming work with pure IDs, not converted to a string by C, I think he planned to move all net system to support pure IDs or something like that. Also there is an unused util.NetworkStringToID function, probably left for this.

**Comment by Bo98** [comment]
I'm worried about addons conflicting. How would addons know what IDs to use that will not conflict with another addon? They are very arbitrary. Strings are easier to make unique as you can prefix them with something that's likely unique to your addon, such as its name.

**Comment by uRandomAlex** [comment]
@Bo98 That's one of the reasons why I'm also trying to get "util.GetNetworkedStrings" there. Currently you can check it with util.NetworkIDToString - if it returns nil, then this ID is free to use.

**Comment by Bo98** [comment]
If you are wanting a function to use raw IDs instead of using networked strings, then how will those help?

**Comment by uRandomAlex** [comment]
@Bo98 

> Bypassing limit of stringtable, more efficient networking or some hidden shit like anticheats.

**Comment by willox** [comment]
How are we going to handle collisions? By networking more data alongside the original IDs to specify if it is meant to be received as an ID-registered message or a name-registered message?

This doesn't make the net library better or easier to use and it's not going to happen. Feel free to just make the changes on your own servers.

**Comment by Bo98** [comment]
@uRandomAlex That wasn't what I was aski but @willox more or less covered what I was trying to say.

**Comment by uRandomAlex** [comment]
@willox This is not intended to be used for simple net operations. A use for this is things th where network needs to be hidden (anticheats). On wiki there needs to be a note like "This function has it's own very special uses. If you just want to send a net-message, consider using net.Start instead." after function to start net-message by ID will be added. Developers can avoid collisions by sending net-messages with ID counting from the end, from what I know ID of net-message is 16-bit so developers will want to use 65536, 65535, 65534 instead of 1, 2, 3 (stringtable limit is 8000 from what Rubat said). Also I can't imagine how I can make that change on my servers, I will be happy if you will provide me that information.

**Comment by willox** [comment]
I guess it's not possible to make the changes yourself. That doesn't mean this is a sensible request, though.

At the end of the day, you're just using numbers instead of actually unique identifiers and I don't see any way to document that properly. The only benefit is that you can send more than 8k unique messages. Which is probably already enough.

**Comment by uRandomAlex** [comment]
Also helper function can be added, like util.GetFreeNetworkID, it will work by storing all IDs that has been used by a function that starts net-message by ID and returning the biggest available one.

**Comment by uRandomAlex** [comment]
@willox Why you don't want to expand "cat-and-mouse" game called "Anticheats-vs-Cheats war"?
