### ISSUE TITLE
Model:GetMesh() for visual meshes.

### ISSUE THREAD

**Issue by ndbeals** [Facepunch/garrysmod-requests#84]
This would be a really fun and useful function to have, I don't think it would be too hard to return the raw mesh that the engine is currently using, so it would account for LOD's. 

Some example uses are:
- dynamic clipping, cutting, shaping or modifying props for building purposes
- create actual puncture holes for bullets on models.
- getting poly count of models

There are probably more uses I just haven't thought of.

**Comment by Kefta** [comment]
@robotboy655 Could you reopen this or should I create a new issue? Also needing this functions for map meshes.

**Comment by ndbeals** [comment]
@Kefta I closed it because I doubt anything is happening with it after 4 years of it sitting open. I didn't even think there were others who wanted this too. I guess I'll re-open it.

**Comment by Kefta** [comment]
Would be nice if the devs worked backwards on issues so some of the older requests could get some long-needed love

**Comment by rickomax** [comment]
Pls add this feature s2

**Comment by Python1320** [comment]
Do we have reasons why the code in https://github.com/Facepunch/garrysmod-requests/issues/1216 ( https://pastebin.com/9wfu7xWn ) cannot be integrated?

**Comment by robotboy655** [comment]
Well it won't work for brush models and I had to recode most of it, but it's in the game now as `util.GetModelMeshes( ... )`

**Comment by rickomax** [comment]
Sample stuff I made with that:
https://www.youtube.com/watch?v=5lE7eQ7ALM4&feature=youtu.be

https://github.com/rickomax/slicegmod/blob/master/weapon_slicer.lua

**Comment by dhkatz** [comment]
Was this ever implemented to work with the world entity?

It seems to have extremely weird behavior

**Comment by robotboy655** [comment]
As my comment above states, it won't work for brush entities.

**Comment by Kefta** [comment]
I made a brush alternative in a module (it's really easy), but there are some other map structs that I'd like exposed that I'm trying to find a proper place for.
