### ISSUE TITLE
Add a hook for when a player's water level changes

### ISSUE THREAD

**Issue by gspetrou** [Facepunch/garrysmod-requests#841]
Like the title says, a hook that gets called when a player's water level changes would be a useful addition compared to using a Think hook or a timer to test this.

**Comment by Kefta** [comment]
You can test this change from Move to FinishMove. The engine doesn't test if there's a change by default iirc

**Comment by Acecool** [comment]
This isn't difficult to add in but I can see it having certain uses, but we do typically use the Move hook to reference it because, in water, we typically want to restrict movement, etc... All of that is possible in the move hook.

I do see it useful in terms of how I like coding things... ie as a "worker thread / service" which starts / stops based on requests.. My bullet system uses this, so does my notification system and many other systems I've written: Basically when the first job / request / notification / etc.. is added, the hook starts to process the data and when the last one is removed or finished the hook stops so there are no useless hooks running each tick / frame which aren't necessary...

Untested but should work...
```lua
//
// OnWaterLevelChanged Logic
//
hook.Add( "Move", "OnWaterLevelChanged:Logic", function( _p, _move )
     // Make sure the player is valid ( Move shouldn't be called on nonvalid players anymore, but just in case... return nil so it doesn't disrupt normal Move function or other Move hooks..
     if ( !IsValid( _p ) ) then return; end

     // Since we'll use the water level multiple times, make a var..
     local _level = _p:WaterLevel( );

    // Set up the cached water level we'll be comparing it to... Typically this will start at 0... No need to return for this.. you may wish to call OnWaterLevelInit type hook here just in case they start in water... but as the level changes it would likely be too quick to matter unless they spawn underwater...
    if ( !_p.__CachedWaterLevel ) then
        _p.__CachedWaterLevel = _level;
        hook.Call( "OnWaterLevelInit", GAMEMODE, _p, _move, _p.__CachedWaterLevel, _level );
    end

    // On change...
    if ( _p.__CachedWaterLevel != _level ) then
         // Send in the normal information along with the old level and the new level
         hook.Call( "OnWaterLevelChanged", GAMEMODE, _p, _move, _p.__CachedWaterLevel, _level );

        // Update the level
        _p.__CachedWaterLevel = _level;
   end
end


//
// OnWaterLevelChanged Hook / Override function ( Required or it will not be called - hook.Run may allow it, but it is good to have a template pre-set and I usually use the "gamemode" table for new hooks which allows them to load normally with addons without any fuss of hooking to Init the additions )..
//
function GM:OnWaterLevelChanged( _p, _move, _old_level, _level )
     // Override
end


//
// OnWaterLevelInit Hook / Override - went ahead and added this...
//
function GM:OnWaterLevelInit( _p, _move, _level )
     // Override
end
```

**Comment by ZehM4tt** [comment]
Not only is the code utterly disgusting it wouldn't work properly. For one its not ran clientside when the game is in singleplayer mode, the other thing is Move is too early as other hooks might modify movedata which is first applied in FinishMove.

It would be easier to use NW2Vars and setup a EntityNetworkedVarChanged hook on the specific network value on the client.

And the other thing is I don't think we should have a hook for everything that can be done manually.

**Comment by gspetrou** [comment]
How can this me solved "manually"? The only way I can see it is using a Think hook.

**Comment by Kefta** [comment]
Check between Move and FinishMove

**Comment by Acecool** [comment]
The code I posted does what you want, but you may want the Clientside Waterlevel fix:

```lua
//
// META_PLAYER:WaterLevel( ) networking fix.
//
META_PLAYER 							= FindMetaTable( "Player" );
function META_PLAYER:WaterLevel( )
	local _pos1 = self:GetPos( );
	local _halfSize = self:OBBCenter( );
	local _pos2 = _pos1 + _halfSize;
	local _pos3 = _pos2 + _halfSize;
	if ( bit.band( util.PointContents( _pos3 ), CONTENTS_WATER ) == CONTENTS_WATER ) then
		return 3;
	elseif ( bit.band( util.PointContents( _pos2 ), CONTENTS_WATER ) == CONTENTS_WATER ) then
		return 2;
	elseif ( bit.band( util.PointContents( _pos1 ), CONTENTS_WATER ) == CONTENTS_WATER ) then
		return 1;
	end

	return 0;
end
```

**Comment by willox** [comment]
WaterLevel's networking was fixed a while back. Try it out.

**Comment by Acecool** [comment]
Cheers, I'll take a look.

**Comment by robotboy655** [comment]
Added was `OnEntityWaterLevelChanged( ent, old, new )`
