### ISSUE TITLE
Add trace curve or follow-function / distance / time...

### ISSUE THREAD

**Issue by Acecool** [Facepunch/garrysmod-requests#844]
As far as I know, I haven't done a huge amount with gmod in a while, if you want a bullet to follow a path you write the function with takes in Muzzle velocity, time, projectile weight, muzzle-position and direction / normal at time of shooting ( pretty sure that is all that is needed for realistic ballistics because you can calculate rotation of earth with direction, drop based on weight, drag based on projectile shape [ which could be averaged for simplicity ], etc... ) to plot where the projectile will be and between ticks you trace a segmented line ( to ensure a more accurate curvature ) or a straight-line ( less accurate )...

But, instead of having to loop through creating a trace over time ( ie once per tick / frame or more than once for higher accuracy ), why not have a new trace mechanism that allows this ( an input function to determine parabola or shape of the trace meaning anything from ballistics could be handled to spirals, to whatever... )... 

It wouldn't need to do it over time but could be an instant curve-trace as the current system does ( but it could be cached and a callback could be used to see if a player intersects when the projectile would be passing through )...

I may be overthinking it, but even if the trace has to be called every frame to detect intersect; rather than calling the entire trace it would still provide a simple solution to tracing the segments of a projectile path to call a trace ONCE for the curve rather than 1 time for a straight line ( and if traveling too fast it would be inaccurate and may even cause a "hit" to be a miss ) or simplify it by not needing to call a trace many times for the more accurate curve...

**Comment by Jvs34** [comment]
You know, you don't have to abide to the bullet system anymore, with the EntityFireBullets hook you can just override any bullets and do it yourself. _Kilburn turned bullets into rockets when he tested the hook so yeah go nuts.

What you're asking while nice will never be done because there's no point when you can do it yourself.

**Comment by Acecool** [comment]
I haven't used the default bullet system in a long time... I'm asking for a new trace method to be implemented so instead of forcing it to be a straight line from a to b, it can be curved ( by using a function to describe the trajectory ).. This would simplify the logic even further and make the path more accurate than it currently is ( I sacrifice some accuracy right now to prevent having to loop through too many traces during 1 frame / tick for rounds that travel very fast like a rifle round at 3200 FPS )...

**Comment by thegrb93** [comment]
I think this can be written by anyone very easily and it won't have that much of a speed improvement over lua implementation.
