### ISSUE TITLE
Get the default vehicle wheel Spring Length

### ISSUE THREAD

**Issue by freemmaann** [Facepunch/garrysmod-requests#845]
An ability to get the vehicles current wheel spring length would be amazing.

http://wiki.garrysmod.com/page/Vehicle/SetSpringLength

Tried scouting the vehicle params and even trying to determine it manually from the vehicles handling files, no luck. Written a quick hacky solution to it, but its not precise at all.

**Comment by robotboy655** [comment]
Impossible since this is all from vphysics interface, and it doesn't have that function.
