### ISSUE TITLE
Options to adjust/customize a HUD Elements

### ISSUE THREAD

**Issue by KirbyJoe** [Facepunch/garrysmod-requests#846]
# HL2 damage indicator
The damage indicator was used in all HUD including a custom workshop-made HUD, and it's not customizable. but this new feature can customize this by your own style.

- HL2 style (Default): Only shows a Left/Right directions
- HL1 style: Four-direction based layout (Left, Right, Front, and Back), seen below: ![img_1473](https://cloud.githubusercontent.com/assets/20151551/20026984/897ca34e-a34a-11e6-8380-f9f341525085.PNG)
- TF2 style: Shows any directions and width/height/time are change depends on damages, seen below: ![img_1475](https://cloud.githubusercontent.com/assets/20151551/20027057/d41abaa6-a34c-11e6-9ac0-04a127aac32b.JPG)

# Poison damage indicator
The poison damage indicator was shown when you attacked by poison headcrab, seen below: ![img_1476](https://cloud.githubusercontent.com/assets/20151551/20027111/463029fe-a34e-11e6-8ac9-ebae28c2bc78.PNG)
But this was bit annoying because the HEV Suit FVOX was on hiatus (there's a [workshop addon](https://steamcommunity.com/sharedfiles/filedetails/?id=470004201) to make them back). I want to toggle them on/off by this option.

**Comment by robotboy655** [comment]
http://wiki.garrysmod.com/page/GM/HUDShouldDraw
To hide the default.

http://wiki.garrysmod.com/page/GM/HUDPaint
To draw whatever it is you want instead,

The end.
