### ISSUE TITLE
Add Player::NoteWeaponFired()

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#849]
This is used by HL2MP, Portal, DoD:S, and CS:S to make a choice on whether to enable lag compensation in WantsLagCompensationOnEntity. This also allows lag compensation to properly be used for weapons that shoot with a key other than IN_ATTACK.

**Comment by willox** [comment]
The only thing this does in gmod is some anti-cheat-y stuff. I don't see a point in exposing it.

**Comment by Kefta** [comment]
Can I ask if WantsLagCompensationOnEntity is implemented differently in GMod that works properly with custom firing functions?

**Comment by willox** [comment]
The only check in WantsLagCompensationOnEntity is the PVS stuff.
