### ISSUE TITLE
Allow player_weapon_color.lua to be replaced and shipped with SteamWorkshop addons

### ISSUE THREAD

**Issue by DPotatoman** [Facepunch/garrysmod-requests#852]
Hello, I am sorry if I formated request poorly, I'm just trying to get this confusing issue out and hopefully fixed.

The problem is with the said lua file being irreplaceable. I always wanted to get out a recolorable physgun and other weapons that can be colored with the context menu. However the sine parameter that makes weapon $selfillum pulsate won't make it possible. It just makes the $color pulsate.. I tried to ship my own edit with workshop addon but it won't work, original _player_weapon_color.lua_ from _GarrysMod\garrysmod\lua\matproxy_ would always override it.

Thanks for checking out this post,
~Alex

**Comment by robotboy655** [comment]
It's not explicitly disallowed.

If you have to override default .lua files, you are doing something very wrong.

You can call matproxy.Add to override any existing matproxy.

**Comment by DPotatoman** [comment]
> If you have to override default .lua files, you are doing something very wrong.3

It's the only way I know. I tried creating a dupe without sine and coloring didn't work in multiplayer, both for myself and other players.

>You can call matproxy.Add to override any existing matproxy.

How does it work?

**Comment by robotboy655** [comment]
Off to https://facepunch.com/forums/65 with you for Lua help.
