### ISSUE TITLE
Add support for ingame workshop subscribing without restarting

### ISSUE THREAD

**Issue by jbuug** [Facepunch/garrysmod-requests#858]
lets say for example, you want to download a mod but you dont want to have to restart or reload the map. maby we can figure out a way to load workshop content ingamew without restart

**Comment by Jake3231** [comment]
That would be awesome. I'm not sure exactly how you would do that. Maybe just show the Gmod loading screen, and load the new mod's resources into the current game session, just the same as you would do when starting up a map for the first time.

**Comment by thegrb93** [comment]
```
steamworks.FileInfo( 104548572, function( result )
	steamworks.Download( result.fileid, true, function( name )
		game.MountGMA( name )
	end )
end )
```

**Comment by Jake3231** [comment]
Would this allow the user to add an addon and see the changes applied in real time? Maybe a new weapon would appear in the spawn menu?

**Comment by jbuug** [comment]
im not sure i just added it as an idea i dont know how to code but i want to be helpful to this commutiy anyway possible

**Comment by jbuug** [comment]
i could test this though but where would i put the lua file

**Comment by robotboy655** [comment]
It already works like that for most content, except for Lua, for obvious reasons.
