### ISSUE TITLE
ENTITY:GetAngleVelocity() binding 

### ISSUE THREAD

**Issue by mandrewpowers** [Facepunch/garrysmod-requests#859]
Currently we have no way as far as I can tell *(searched the wiki and looked through the Entity metatable)* to get the angular velocity without access to the vphysics object. This makes it impossible to get the angular velocity on the client in normal situations. It seems like the engine returns both linear and angular velocity in CBaseEntity so I'm surprised it isn't already available.

```cpp
void CBaseEntity::GetVelocity(Vector *vVelocity, AngularImpulse *vAngVelocity)
{
	if (GetMoveType()==MOVETYPE_VPHYSICS && m_pPhysicsObject)
	{
		m_pPhysicsObject->GetVelocity(vVelocity,vAngVelocity);
	}
	else
	{
		if (vVelocity != NULL)
		{
			*vVelocity = GetAbsVelocity();
		}
		if (vAngVelocity != NULL)
		{
			QAngle tmp = GetLocalAngularVelocity();
			QAngleToAngularImpulse( tmp, *vAngVelocity );
		}
	}
}
```

**Comment by robotboy655** [comment]
http://wiki.garrysmod.com/page/Entity/GetLocalAngularVelocity ?

**Comment by Kefta** [comment]
Also, http://wiki.garrysmod.com/page/PhysObj/GetAngleVelocity for VPhysicsObjects

**Comment by TehBigA** [comment]
@Kefta I meant to say that this is needed for clientside.
@robotboy655 that is for parented props. It always returns `0 0 0`.

**Comment by Kefta** [comment]
That function works clientside

**Comment by TehBigA** [comment]
@Kefta there is no physics object for normal props on the clientside.

**Comment by TehBigA** [comment]
Any more thoughts on this?

**Comment by jbuug** [comment]
Seems a little complex but i think this could work

**Comment by Kefta** [comment]
@jbuug Can you not spam every request?

**Comment by Kefta** [comment]
What you're asking for is already binded. The client uses http://wiki.garrysmod.com/page/Entity/GetLocalAngularVelocity while the server uses http://wiki.garrysmod.com/page/PhysObj/GetAngleVelocity

**Comment by robotboy655** [comment]
You are correct @Kefta, the only difference is the absence of QAngleToAngularImpulse call in Entity.GetLocalAngularVelocity
