### ISSUE TITLE
game.GetAmmoData( number id )

### ISSUE THREAD

**Issue by kklouzal** [Facepunch/garrysmod-requests#861]
Request the ability to get the AmmoData Structure, for a particular Ammo ID, back out of the engine and for read only purposes.

**Comment by Kefta** [comment]
https://github.com/Facepunch/garrysmod-requests/issues/646

**Comment by Kefta** [comment]
Also, I made a manual replacement here: https://github.com/Kefta/GSWeapons/blob/master/gsweapons_base/lua/includes/extensions/game.lua
