### ISSUE TITLE
Fix VoiceVolume not needing voice_loopback 1

### ISSUE THREAD

**Issue by TheMerkyShadow** [Facepunch/garrysmod-requests#862]
I want to be able to build voice visualizers and HUDS using the sound from peoples voices.
It does work. Only if people set voice_loopback to 1
And since voice_loopback is a blocked console command.
We can't override that on players. 
So i'm proposing someone unblocks that command.
Or fixes the issue all together.

[EDIT]: I've also theorized that this is the same reason why mouth animations don't work
either unless this is enabled.

https://wiki.garrysmod.com/page/GM/MouthMoveAnimation
https://wiki.garrysmod.com/page/Player/VoiceVolume

If someone sees another way of doing it then please tell me.

**Comment by Kefta** [comment]
voice_loopback should not be enabled for the obvious reason of the player not wanting to hear their own voice, but being able to get the volume of the player's own voice clientside would be very nice.

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/2315

**Comment by garryspins** [comment]
Is it really impossible to take the logic from voice_loopback and remove the actual audio emission unless the convar is enabled! Im not seeing much if any of a performance impact from voice_loopback being on, please.... im begging you.
