### ISSUE TITLE
Start at native aspect ratio & resolution

### ISSUE THREAD

**Issue by aStonedPenguin** [Facepunch/garrysmod-requests#863]
When you first launch garrysmod it starts at 4:3 on some terribly small resolution. Many people don't change the default settings making it incredibly damaging to users experiences and a headache for content creators.

**Comment by robotboy655** [comment]
Done

**Comment by uRandomAlex** [comment]
I'm surprised how this was not a default behaviour.

**Comment by thegrb93** [comment]
That's how original hl2 has always been.
