### ISSUE TITLE
Entity:SetNWColor() and Entity:GetNWColor()

### ISSUE THREAD

**Issue by markusmarkusz** [Facepunch/garrysmod-requests#864]
I don't know if this has ever been asked.
A Entity:SetNWColor() and Entity:GetNWColor() function would be nice.

I know that these functions could be easily made in Lua ([Just a example](https://gist.github.com/markusmarkusz/f9ac2caccda0908e006093f51b507ed1)) but I think doing this in the engine would be better.

What do you think about that?

**Comment by Kefta** [comment]
Color is in Lua, therefore, all color equivalent functions are in Lua as well (net.Read/WriteColor, IsColor). Here's a better way to do it: http://pastebin.com/Z3KvFXfY
