### ISSUE TITLE
ents.GetCount()

### ISSUE THREAD

**Issue by aStonedPenguin** [Facepunch/garrysmod-requests#867]
As with #751 it would be much faster than #ents.GetAll()

**Comment by Kefta** [comment]
In practice, this would be very efficient for weapons that do penetration by ignoring all entities except the one being penetrated.

**Comment by Kefta** [comment]
gEntList,NumberOfEntities() :wink:

**Comment by scottd564** [comment]
please

**Comment by jcwik223** [comment]
Would be much more efficient for looping over all entities!

**Comment by robotboy655** [comment]
Done

**Comment by jackson-c** [comment]
make a function that returns an iterator over the entities so we don't have to COPY
