### ISSUE TITLE
Add PhysObj:SetMassCenter()

### ISSUE THREAD

**Issue by ARitz-Cracker** [Facepunch/garrysmod-requests#870]
We have PhysObj:GetMassCenter(), why not SetMassCenter?

**Comment by robotboy655** [comment]
Because just like with rest of physics functions, Valve elected that they didn't need a SetMassCenter() function.

**Comment by Kefta** [comment]
I don't have access to the VPhysics source, but is the member variable where the mass centre stored public?

**Comment by Kefta** [comment]
There is a ``SetMassCenter`` but it only works for CPhysCollides. Just run ``CollideSetMassCenter`` with VPhysicsObject()->GetCollide().

**Comment by robotboy655** [comment]
Unfortunately that doesn't work as GetCollide() is a constant.

**Comment by Kefta** [comment]
F
