### ISSUE TITLE
system.ScrW() & system.ScrH()

### ISSUE THREAD

**Issue by aStonedPenguin** [Facepunch/garrysmod-requests#871]
It'd be useful, especially for bugging people to play at a more ideal resolution.

**Comment by Kefta** [comment]
You should only need the width and height of the window -- harassing people to play at a better resolution should not be the only reason you need these functions.

**Comment by aStonedPenguin** [comment]
It's just an example of a case it'd be useful.

**Comment by robotboy655** [comment]
uhhhhhhhhhhhhhhhhhhhhhhhhh Global.ScrW() Global.ScrH()?

**Comment by Kefta** [comment]
He was asking about getting the user's monitor resolution.
