### ISSUE TITLE
VPhysics Friction Snapshot

### ISSUE THREAD

**Issue by ZehMatt** [Facepunch/garrysmod-requests#876]
This would allow to get the contact points of other objects. Theres an example on how its used within physics_shared.cpp PhysComputeSlideDirection.

It would be enough to push all information onto a table as it may invalidate at any time a simulation is run.

Scripted entities would be able to easily determine who is in contact with their object and have the exact position.

**Comment by CapsAdmin** [comment]
This is something I've been wanting as well. It would be especially useful to figure out of a physics body is on ground. The current hacky way to do this is to use util.TraceLine on the nearest point downwards

**Comment by robotboy655** [comment]
Yay?
![image](https://user-images.githubusercontent.com/3299036/75483449-88f30c00-59af-11ea-8b8e-7e8604ed8992.png)

**Comment by Kefta** [comment]
I'm not a fan of the key names, even if they are like that in the vphysics interface. I think it should be like TraceResult where they're all upper-case with no ``duck_casing``.

**Comment by robotboy655** [comment]
FairEnough.

**Comment by robotboy655** [comment]
I guess you are not a big fan of this stuff then
https://wiki.facepunch.com/gmod/Structures/VehicleParamsAxle

**Comment by Kefta** [comment]
Yeah there's a lot of struct inconsistency in glua. I think upper camel case is the way the best standard to conform to though. Thanks for changing it

**Comment by ZehMatt** [comment]
How would I iterate the snapshot? It only gives me the result of a single contact where it may have multiple contacts with multiple objects.

See this example how its actually used:
```
static bool InContactWithHeavyObject( IPhysicsObject *pObject, float heavyMass )
{
	bool contact = false;
	IPhysicsFrictionSnapshot *pSnapshot = pObject->CreateFrictionSnapshot();
	while ( pSnapshot->IsValid() )
	{
		IPhysicsObject *pOther = pSnapshot->GetObject( 1 );
		if ( !pOther->IsMoveable() || pOther->GetMass() > heavyMass )
		{
			contact = true;
			break;
		}
		pSnapshot->NextFrictionData();
	}
	pObject->DestroyFrictionSnapshot( pSnapshot );
	return contact;
}
```
Getting only the first contact point is not exactly ideal.

**Comment by ZehMatt** [comment]
Great stuff, seems to be working nicely. Thanks!
