### ISSUE TITLE
Add Matrix copying through copy-constructor

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#880]
Just like vectors and angles. For example,
local mat=Matrix()
local copymat=Matrix(mat)

**Comment by jbuug** [comment]
Good idea

**Comment by bmwalters** [comment]
@jbuug In the future, you should just add a 👍  to an issue if it's one that you prioritize instead of commenting if your comment doesn't add any information about the issue. The maintainers of the game (and others) have expressed annoyance at comments like this being spammed across issues.

**Comment by jbuug** [comment]
sorry just new to this, tbh the only reason i am here is because i want to get ideas for coding. but im very bad at it

**Comment by robotboy655** [comment]
Added.
