### ISSUE TITLE
Add ply:SimulateUse() to get what a player would use if they hit +use

### ISSUE THREAD

**Issue by a1steaksa** [Facepunch/garrysmod-requests#883]
This would be very helpful for UI to be able to tell what a player would use. 

Aside from some hacky stuff involving forcing a +use call on the player and using PlayerUse to suppress it, then networking that entity back to the player, there isn't a way to do this clientside.

**Comment by thegrb93** [comment]
or ply:GetUseEntity()

**Comment by a1steaksa** [comment]
I prefer that, but if ply:SimulateGravGunDrop() and ply:SimulateGravGunPickup() are the new phrasing, I guess I can get with the times of having really long function names.

**Comment by ZehM4tt** [comment]
Thats not what SimulateGravGunDrop/SimulateGravGunPickup do by your example. And the whole thing works different in the first place. When using +use it just calls CPhysicsProp::Use which brings the player to picking it up. You are better off using a trace.

**Comment by a1steaksa** [comment]
You misunderstand my intention, I believe.

They were examples of the function name phrasing, not functionality.  I need to know which of the objects in front of the player they would use if they hit +use at a given time.  For instance which of two doors they would open given they are not looking directly at either. A trace won't give me that because you can use something you're not looking directly at.

**Comment by Kefta** [comment]
Normal use functionality uses a trace; the function you're asking for would just be a fancy trace.

**Comment by a1steaksa** [comment]
I want to know exactly which item someone would activate if they hit +use.  How do you propose I accomplish that without overriding default use functionality?

**Comment by Kefta** [comment]
You just fire a normal hull trace when you want to know what the player would use. There's no overriding needed.

**Comment by Kefta** [comment]
Here's the code for anyone curious: https://github.com/LestaD/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/se2007/game/shared/baseplayer_shared.cpp#L954

**Comment by robotboy655** [comment]
Added `Player.GetUseEntity()` - shared, returns the entity that would be used if the player would press their +use key, including `GM:FindUseEntity` results.

Please do keep in mind that the return value may differ between client/server, especially if `GM:FindUseEntity` is used only serverside, etc.
