### ISSUE TITLE
Add command for finding source of content

### ISSUE THREAD

**Issue by wouterpleizier** [Facepunch/garrysmod-requests#884]
I have a map on the workshop called [gm_fork](http://steamcommunity.com/sharedfiles/filedetails/?id=326332456). Almost every week, I get comments from people saying that they're experiencing broken/missing textures or models, even though I've made very sure to pack all of the non-stock content into the BSP or addon.

I always tell people to temporarily disable all other addons, and that usually fixes it. Sadly, there doesn't seem to be a way to find out which addon was the cause of the problem, aside from re-enabling them one by one until the issue occurs again. Would it be possible to add a console command that prints the name of the addon/game that a specified file (material, texture, model, etc.) originates from? It would be very helpful for troubleshooting these kinds of issues.

**Comment by robotboy655** [comment]
whereis <local filepath>

**Comment by wouterpleizier** [comment]
Thank you, that's perfect. I searched around the console command list but I hadn't found that one. Sorry for the bother.
