### ISSUE TITLE
Don't cache spawnicons for missing models

### ISSUE THREAD

**Issue by aStonedPenguin** [Facepunch/garrysmod-requests#886]
As the title says. If you use them anywhere in your UI and they player doesn't have the model it can be very annoying since most players don't know how to fix it.

**Comment by Kefta** [comment]
Maybe just add a way for servers to tell when it's an error? Problem is that constantly refreshing it when the player doesn't have the model is going to cause a hit every time the icon is loaded.

**Comment by jbuug** [comment]
This could save some memory for slower computers when loading the game good idea

**Comment by Jake3231** [comment]
I'd agree with jbuug and Kefta.  This would be a good way to reduce memory usage in certain cases as well as reduce the performance hit when loading icons for a model the player does not have.

**Comment by robotboy655** [comment]
Fairly certain this was already fixed last year or something.
