### ISSUE TITLE
Ability to tell when the engine is in prediction (CPrediction->InPrediction binding)

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#887]
I am doing predicted methods in Holster, but due to https://github.com/Facepunch/garrysmod-issues/issues/2854, I have to pcall GetCurrentCommand to tell if prediction is happening or not. If the method is added, then https://github.com/Facepunch/garrysmod-requests/issues/334 can be fulfilled and everyone is happy.

**Comment by neico** [comment]
http://wiki.garrysmod.com/page/Global/IsFirstTimePredicted doesn't solve this? (see [this](http://wiki.garrysmod.com/page/Prediction#There.E2.80.99s_a_function_called_IsFirstTimePredicted.2C_what_is_it.3F))

Or am I missing the point what exactly you mean?

**Comment by Kefta** [comment]
] lua_run print(IsFirstTimePredicted())
> print(IsFirstTimePredicted())...
true
] lua_run_cl print(IsFirstTimePredicted())
false

This doesn't say that the engine is not in a prediction state.

**Comment by ZehM4tt** [comment]
What Kefta wants is probably a binding for "bool CPrediction::InPrediction( void ) const"

**Comment by Kefta** [comment]
@ZehM4tt That's the one. I saw prediction->InPrediction around the engine a lot, but couldn't find the pointer definition anywhere. Thanks.

**Comment by Kefta** [comment]
Client prediction can be found with CurTime() ~= UnPredictedCurTime(), but there is still no way serverside.

**Comment by robotboy655** [comment]
Added GetPredictionPlayer() global
