### ISSUE TITLE
PANEL:OnSizeChanged(newWide, newTall)

### ISSUE THREAD

**Issue by KrakenZ** [Facepunch/garrysmod-requests#889]
The C++ function already exists. It just need the lua binding.

**Comment by robotboy655** [comment]
PerformLayout?

**Comment by KrakenZ** [comment]
The difference is that PerformLayout is called whenever the layout needs revalidation; this isn't only triggered by size changement; which mean it possibly does more calculation than needed.

Yes, you may see it as a micro optimization request, but it really isn't. At least for me.
This function would allow separating size management and whole layout validation.

For example: in a DScrollPanel, there is two things that doesn't need to be called every time the panel's layout is invalidated:
self:Rebuild() -> this calls self:GetCanvas():SizeToChildren(...). This isn't obligatory needed as the panel's size is probably unchanged; This should be in functions like OnChildAdded and OnSizeChanged.
self.VBar:SetUp(...) -> same. In this case, it should be in a OnSizeChanged function.

I want this function because I'm making a panel that needs to check if it has enough child panels based on the size of the canvas. The function is quite expensive (has some loops, etc). I don't really want to create a cache variable of the panel's height so I thought I'd make this simple request

**Comment by robotboy655** [comment]
Then do size comparisons and run code only if size has changed? You can even fire off your own callback from there.

**Comment by KrakenZ** [comment]
When I was talking about cache variable, that was what I meant.
This function (OnSizeChanged) already exists in the source code
[IPanel.h](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/public/vgui/IPanel.h#L103)
[EditablePanel.cpp](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/vgui2/vgui_controls/EditablePanel.cpp#L175)
[Panel.cpp](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/vgui2/vgui_controls/Panel.cpp#L1504)
It can be done by using a height cache variable as we both said; I just thought we could benefit from using the premade function.
It's not a big addition but it can help splitting and organizing code.

**Comment by robotboy655** [comment]
Added in Dev, PerformLayout is called too late in some cases.
