### ISSUE TITLE
Change server-side initialization file names on next major API update.

### ISSUE THREAD

**Issue by JamesxX** [Facepunch/garrysmod-requests#891]
Currently, there is no consistency between filenames over the realms. Server-side it is simple "init" with no prefix. Client-side it is "cl_init", and for shared it is simple "shared". However, when including minor files, developers tend to prefix their files with "sv", "sh" or "cl" for server-side, shared, and client-side respectively. 

I'm proposing that we rename "init.lua" to "sv_init.lua" so as to allow the files grouped for the same realm to have the same prefix. Equally, we should rename "shared.lua" to "sh_init.lua" for the same reason.

I understand this isn't a major issue, more of an inconvenience, but allowing this change would permit a lot more consistency.

**Comment by robotboy655** [comment]
IIRC no "shared.lua" is ever loaded automatically by the game, it is always included by init.lua and cl_init.lua manually.

As for renaming the file paths, that is a really terrible idea for obvious reasons.

I don't see any "next major API updates" in the future at all. Time for any of this is long gone.
