### ISSUE TITLE
SetGlobalState/GetGlobalState

### ISSUE THREAD

**Issue by ZehM4tt** [Facepunch/garrysmod-requests#892]
It would be handy to have access to those, they could be part of "game" library. env_global uses them to control various things such as if gordon can take damage or if the super gravity gun is enabled. They persist over changelevel.

This also allows mappers to communicate with lua even more easily.

Thanks.

**Comment by Kefta** [comment]
What did you use instead?

**Comment by robotboy655** [comment]
Added game.GetGlobalState(name), game.GetGlobalCounter(name), game.SetGlobalState(name, state) and game.SetGlobalCounter(name, value) to access global game states set by env_global (serverside only)

Added the following enums to Lua: GLOBAL_OFF, GLOBAL_ON, GLOBAL_DEAD

**Comment by robotboy655** [comment]
Documented here: http://wiki.garrysmod.com/page/Global_States

**Comment by thegrb93** [comment]
One step closer to super gravgun

**Comment by Kefta** [comment]
@thegrb93 It's now possible in Lua!

**Comment by robotboy655** [comment]
No steps closer to Super Grav Gun without mods. The issue is that the gravity gun GMod has is HL2:MP one, it works in multiplayer, not the HL2 which doesn't, but has Super Grav Gun
