### ISSUE TITLE
PreChatAddText

### ISSUE THREAD

**Issue by biorisk2** [Facepunch/garrysmod-requests#895]
There are a lot of adware addons on the gmod workshop, and despite reporting them, nothing happens.. ever.

----scummy code----
timer.Simple( 300, function() chat.AddText( Color(255,255,255), "Ad system modified by Servius from", Color(100,180,255), " Phenomenal Nations" ) end )
timer.Simple( 30, function() chat.AddText( col, message ) end )
----------------------

This is obnoxious, having a way to stop these  chat.AddTexts would benefit Garry's Mod quite a lot.

A way that I see possible is creating a client side function PreChatAddText(message) and having the ability to return true/false on wether or not the text goes to the chat box.

This not only stops the adware issue (atleast for people who create addons stopping these kinds of things) but it could very well be used inside of game modes and scripts.

**Comment by robotboy655** [comment]
So we should be adding hooks to disable all addon functions now?

Here's a suggestion: Don't encourage those addon authors by installing addons that do this.

Reporting won't do anything because adding text into ĉhat is not against the rules.

**Comment by Kefta** [comment]
Override chat.AddText or edit the addon.

**Comment by biorisk2** [comment]
Rubat, the issue is these addons have adware built into them,
It is software that plays an advertisement to online users, and these shitty people aren't nice about it, they spam it every 30 seconds per addon.

Also, editing and reuploading to the workshop is against the gm workshop rules.

Furthermore, uploading the addon to your private host can be a whole load of issues when these dickheads DMCA you when they're in the right or wrong, either way you're fucked on the situation.

Also, to comment on what you said, Rubat,
A simple console variable to not run the /lua/ folder of addons would actual be good, It would make servers safer from backdoored model, effect, material packs.

**Comment by robotboy655** [comment]
Adding text into chat is not adware. If you know of any actual adware addons, report them to robotboy655@facepunchstudios.com

**Comment by biorisk2** [comment]
So I can fill my addons with things that spam the chatbox of the downloader telling them to join my server, and that's not malicious or adware?

**Comment by biorisk2** [comment]
If so, is there a time limit between messages you'd reccomend?

**Comment by Kefta** [comment]
@biorisk2 No, but most sensible people would either:

**Comment by biorisk2** [comment]
Reupload your addon without all of the annoying ads
But this breaks the workshop terms of service, that is the issue at hand

**Comment by Kefta** [comment]
@biorisk2 Then don't reupload it to workshop. Or make a competing version without the ads. Either way, if you don't agree with the workshop terms of service or the Garry's Mod workshop moderation, you do not have to use it, or you can email Garry himself.

**Comment by biorisk2** [comment]
Every server/community that I have collaborated with would enjoy a no_addon_lua server setting, 99% of servers fear addons as they're backdoored, this is why everyone steals and reuploads addons in their own content packs, which is against the rules of the workshop.

**Comment by Kefta** [comment]
@biorisk2 Everyone I know does it to condense content downloads

**Comment by thegrb93** [comment]
I'd just mod the addon and put it in the server's addons folder.
