### ISSUE TITLE
Add +voicerecord to the list of blocked consolecommands

### ISSUE THREAD

**Issue by AC2github** [Facepunch/garrysmod-requests#896]
Pretty much what the title says,
this is being abused by server owners running lua to force the microphone on.

It also doesn't make sense that all the other voice options are already blocked and this isn't.
(voice_enable, voice_avggain, etc)

**Comment by robotboy655** [comment]
This will break TTT which is the only reason it isn't blocked yet.

**Comment by Kefta** [comment]
@robotbot655 How else are gamemodes supposed to do custom voice keys for chat channels? If there were an alternative then this could be blocked.

**Comment by bmwalters** [comment]
@Kefta alias the traitor chat key to both run `+voicerecord` and set a convar
on the server query the convar (in `Think` or something) then use it in `PlayerCanHearPlayersVoice`

**Comment by Kefta** [comment]
That would add a lot of work for the client, right?

**Comment by andreblue** [comment]
Why not add an option to simply state allow server to enable/disable mic with lua or something.

**Comment by Kefta** [comment]
@andreblue I would agree this would be a good alternative, but then users have to constantly enable/disable it for gamemodes like TTT that rely on it, and it's a method commonly used in that gamemode to detect ghosting. I personally am stumped on how voice channels could be handled without servers being able to enable voice or bind keys.

**Comment by sanny-io** [comment]
This is a pretty major privacy concern.

**Comment by TiberiumFusion** [comment]
> Why not add an option to simply state allow server to enable/disable mic with lua or something.

> I would agree this would be a good alternative, but then users have to constantly enable/disable it for gamemodes like TTT that rely on it, and it's a method commonly used in that gamemode to detect ghosting.

Use an approach similar to how browser and plugins handle this kind of privacy issue. Improve the client so the user actually has the choice to allow/deny specific servers from enabling voice chat without the user's consent.
[![flash site privacy settings](https://user-images.githubusercontent.com/6332277/130687843-1f9d4975-d170-4655-b31f-13ece48ff822.png)](http://www.macromedia.com/support/documentation/en/flashplayer/help/settings_manager06.html)

Default choice is "always allow forced mic access for all servers". People who play nothing but TTT won't even notice anything changed. Privacy-conscious players can switch to an "ask me for each server" or "always deny" mode, then add servers they trust to an allow list and servers they distrust to a deny list.  And presto, none of that "_constantly enable/disable it for gamemodes like TTT_" nonsense.

Of course this means actually doing some real work on gmod, which seems like too much for Facepunch these days. If a nice gui is beyond their abilities, then an ugly config file similar to `server_blacklist.txt` could be implemented instead. It would be better than the big fat nothing we have right now.

**Comment by mexikoedi** [comment]
This was implemented.
Can be closed.
