### ISSUE TITLE
Allow the calling of NextBot functions on player.CreateNextBots

### ISSUE THREAD

**Issue by maximlahaxim** [Facepunch/garrysmod-requests#897]
I'm not asking for full-on pathfinding/movement implementation (That's what I'm working on doing, and is also why I need this to be added), but just for bots created with [player.CreateNextBot](http://wiki.garrysmod.com/page/player/CreateNextBot) to be considered a "NextBot" by the Lua environment (so they can be passed to functions like [PathFollower:Compute](http://wiki.garrysmod.com/page/PathFollower/Compute), for example).

Without this, I'd have to rewrite the CNavPath code entirely in Lua, which'd be a massive headache.

**Comment by bmwalters** [comment]
#626 ?

**Comment by maximlahaxim** [comment]
@bmwalters Not necessarily the same here; that's requesting that they have their own movement system/other stuff built in. But that can easily be done in Lua (and is what I'm working on right now); all that's needed is for the NextBot functions to be added to the player bots.
