### ISSUE TITLE
Expose CBaseEntity::VPhysicsInitStatic to Lua

### ISSUE THREAD

**Issue by uRandomAlex** [Facepunch/garrysmod-requests#899]
Expose VPhysicsInitStatic to Lua. It's used in prop_dynamic internally and can be very useful for SENTs because it's cheaper. We already have VPhysicsInitNormal as Entity:PhysicsInit and VPhysicsInitShadow as Entity:PhysicsInitShadow, so why VPhysicsInitStatic is not available as, for example, Entity:PhysicsInitStatic?

**Comment by uRandomAlex** [comment]
When will this feature be done? I have some SENTs that don't need to move (furniture, street decorations), but they still use normal physics. I disabled its motion but it'd be shorter to use Entity:PhysicsInitStatic() and perhaps cheaper too.

**Comment by robotboy655** [comment]
http://wiki.garrysmod.com/page/Entity/PhysicsInitStatic
