### ISSUE TITLE
ApplyTorqueCenter Binding?

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-requests#904]
I always thought source didn't have this since it was never in gmod, but it's right here https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/public/vphysics_interface.h#L808

Lua binding please?

**Comment by jbuug** [comment]
virtual void			ApplyTorqueCenter( const AngularImpulse &torque ) = 0;

this string seems intresting to me

**Comment by Kefta** [comment]
It's called a method header..
