### ISSUE TITLE
Load addons into memory while in-game

### ISSUE THREAD

**Issue by jbuug** [Facepunch/garrysmod-requests#906]
Basically i had a idea. if you rember back in the toybox days.
addons would be loaded without having to restart
is  this possible with the workshop.
i think this would make eaisert .

**Comment by TheFreezebug** [comment]
https://wiki.garrysmod.com/page/game/MountGMA

**Comment by uRandomAlex** [comment]
@TheFreezebug This will work only with models and materials. Lua will not be loaded.

**Comment by thegrb93** [comment]
You can load it with include()

**Comment by uRandomAlex** [comment]
@thegrb93 This is a request to do this automatically.

**Comment by SamuelMoriarty** [comment]
It is rather trivial to write a wrapper around `game.MountGMA` that will include necessary lua files from the gma. Please, don't force this behaviour onto everyone, or at least make it toggleable with a flag.

**Comment by uRandomAlex** [comment]
@SamuelMoriarty ideally there should be an additional argument to specify does game need to include Lua from addon or not
