### ISSUE TITLE
Hook to modify or append to chat.AddText calls

### ISSUE THREAD

**Issue by boxama** [Facepunch/garrysmod-requests#907]
Making an addon, I needed to add chat tags for players, showing which group they belong to.
In a gamemode, this is simple enough, just create a GM:OnPlayerChat function server side.
Trying to use the same hook in an addon is significantly more difficult, since it will completely override the gamemode behaviour.
The only effective option is to override chat.AddText, calling the original that you've saved after you've finished your changes, which is quite messy, and may still be somewhat affected by the gamemode or other addon's behaviour. 
E.g. they might not keep the player object in the args to change the name that appears, making it near impossible identify where the player's name is in the args to add something before it.

I'd propose some sort of hook, like ModifyChatText or maybe PreAddChatText [as proposed in this issue](https://github.com/Facepunch/garrysmod-requests/issues/895).
It would ideally have some of the information given by OnPlayerChat, but for backwards compatibility I don't think the entire hook can be overridden.

This would ideally be how one would add the *DEAD* to player messages
```lua
hook.Add( "PreChatText", "AddDeadTag", function( ply, tab, plyIndex, teamChat, isDead ) 
  if not IsValid( ply ) or not isDead then return end
  
  -- plyIndex is where in the table the nickname or player object is
  table.insert( tab, plyIndex, "*DEAD* " )
  table.insert( tab, plyIndex, Color( 255, 0, 0 ) )

  return tab, plyIndex +2, teamChat, isDead
end )
```
The hook would allow you to modify the table, the playerIndex to compensate for any modifications made, and the teamChat and isDead bools to suppress other hooks from modifying messages for the same reason.

**Comment by robotboy655** [comment]
The problem with your idea is that chat.AddText does not have any of those arguments. There's no good solution for this as far as I am aware.

**Comment by boxama** [comment]
I was worried about that issue. chat.AddText and the OnPlayerChat not being in Lua certainly doesn't help with that.
Perhaps simply providing the arguments in the hook may be enough to avoid having to override chat.AddText in most cases.

**Comment by robotboy655** [comment]
What arguments, what hook?

There can be no hook for chat.AddText with any other arguments beside the stuff given to chat.AddText

**Comment by boxama** [comment]
I meant the proposed new hook, which could simply provide the arguments given to chat.AddText, allowing a modified table of arguments to be returned

**Comment by Kefta** [comment]
Why not just override chat.AddText, or modify the physical contents? This just sounds like a repeat of https://github.com/Facepunch/garrysmod-requests/issues/895

**Comment by boxama** [comment]
The reasoning was to allow for the chat contents to be modified as necessary, not just to try to filter things out.
I think requiring each addon to override chat.AddText if necessary is a messy solution. 
Ideally the hook would be also be more powerful by also providing some of the information given by OnPlayerChat (since it cannot be reliably used to build up additions to chat messages) as well as the position of the player name to help with that.
That last one may have been a bit too optimistic, since it'd probably require gamemodes and such to be rewritten to accommodate for it.
Overriding chat.AddText does not provide that functionality, but if there's no way to fit all of that information in a single hook I guess a hook with only chat.AddText's args wouldn't help that much.

**Comment by robotboy655** [comment]
It's not about fitting the information its about acquiring it. There's no way of doing it.
