### ISSUE TITLE
A function to override blend mode

### ISSUE THREAD

**Issue by CapsAdmin** [Facepunch/garrysmod-requests#909]
It would be nice to have something like render.SetBlendMode(source_flags, dest_flags) which could maybe use `void EnableAlphaBlending( ShaderBlendFactor_t src, ShaderBlendFactor_t dst );` in `public/shaderlib/BaseShader.h` (?)

Similar to how we have cam.IgnoreZ, render.SetColorModulation, render.SetBlend, etc.

One workaround right now is to set the additive flag in the material before drawing or create a new material with the additive flag.

**Comment by willox** [comment]
I think I tried this before when sorting out the rendering of Awesomium panels and there were just way too many calls to EnableAlphaBlending & friends to override anything sensibly.

What do you actually need this to achieve?

**Comment by thegrb93** [comment]
Isn't it just a call to IDirect3DDevice9::SetRenderState(D3DRS_SRCBLEND or D3DRS_DSTBLEND

**Comment by CapsAdmin** [comment]
It's mainly for convenience. I can work around this by copying materials and or changing the additive flag in most situations. Do you need to change EnableAlphaBlending to make gmod be able to override the current mode? Are you worried about performance?

@thegrb93 most likely

**Comment by willox** [comment]
```lua
render.OverrideBlendFunc( OverrideEnabled, SrcBlend, DestBlend, SrcBlendAlpha, DestBlendAlpha )
```

The blend parameters are only required when OverrideEnabled is true. The last two parameters can be omitted to not have a separate alpha blending mode.

```
BLEND_ZERO
BLEND_ONE
BLEND_DST_COLOR
BLEND_ONE_MINUS_DST_COLOR
BLEND_SRC_ALPHA
BLEND_ONE_MINUS_SRC_ALPHA
BLEND_DST_ALPHA
BLEND_ONE_MINUS_DST_ALPHA
BLEND_SRC_ALPHA_SATURATE
BLEND_SRC_COLOR
BLEND_ONE_MINUS_SRC_COLOR
```
