### ISSUE TITLE
Re-implement super physgun

### ISSUE THREAD

**Issue by samuelmaddock** [Facepunch/garrysmod-requests#91]
It would be nice to be able to toggle the super physgun functionality seen at the end of the Half-Life 2 campaign. I've searched through the source code and it seems like it would be a trivial fix, assuming the `weapon_physcannon` code hasn't been gutted. I've outlined a possible solution below:

``` c++
// 1. Move physcannon_mega_enabled convar
//  Source:         game\shared\hl2\hl2_gamerules.cpp:71
//  Destination:    game\server\hl2\weapon_physcannon.cpp:50
ConVar  physcannon_mega_enabled( "physcannon_mega_enabled", "0", FCVAR_CHEAT | FCVAR_REPLICATED );

// 2. Modify PlayerHasMegaPhysCannon in game\server\hl2\weapon_physcannon.cpp:1440
bool PlayerHasMegaPhysCannon()
{
    return ( physcannon_mega_enabled.GetBool() == true );
}
```

**Comment by neico** [comment]
There's actually 2 weapon_physcannon.cpp, one for hl2 (in server) and one for hl2mp (in shared), and I'm pretty sure that gmod uses the hl2mp one: https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/shared/hl2mp/weapon_physcannon.cpp#L102

so one would need to either comment out the hl2mp one and instead include the hl2 one or update the hl2mp code with the hl2 one.
Then check for the GameRules()->[MegaPhyscannonActive()](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/shared/hl2/hl2_gamerules.h#L87) which is also missing from the HL2MP GameRules (unless gmod's variant derives from the HL2 one), same goes for the rest of the mega physcannon logic.

If you'd only use what @samuelmaddock suggested then you'd still leave the hl2 maps broken.

The correct way to use it is to add the following code to the GameRules Think()
```cpp
	// If mega phycannon should be enabled.
	if( physcannon_mega_enabled.GetBool() == true )
	{
		m_bMegaPhysgun = true;
	}
	else
	{
		// FIXME: Is there a better place for this?
		m_bMegaPhysgun = ( GlobalEntity_GetState("super_phys_gun") == GLOBAL_ON );
	}
```

**Comment by kem008** [comment]
Sorry if I write but I just found this and it would be amazing if super gravity gun can work like in hl2 :D

**Comment by kem008** [comment]
+1

**Comment by besenyei** [comment]
Would be great to have this functionality.

**Comment by lubor-slusny** [comment]
Id love this functionality at least in some form either as a cvar/working global state/second swep. Having separate weapon would be best tho.

**Comment by Kefta** [comment]
6 years later...

**Comment by Shadowysn** [comment]
> 6 years later...

Yep, still a bit annoying to not have the actual super gravity gun.
I have barely any juice or ideas left on the SCGG addon in the workshop. And it's just... not perfect.

**Comment by robotboy655** [comment]
It was partially ported on Dev so you can actually pick it up and complete `d3_citadel_03`, it will be ported completely at a later date, all the effects and shit need lotsa work, and it requires networking changes.

**Comment by robotboy655** [comment]
This is now completely fulfilled. The effects will still not work because they require networking changes, but you should be able to force them on by setting `m_bPhyscannonState` to `true` clientside while having the mega gravity gun enabled. Once the update releases, that will no longer be necessary and will happen properly automatically, this is just so you can play on servers on the Dev beta.
