### ISSUE TITLE
Add ChatText type for FCVAR_NOTIFY convar messages

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#911]
https://wiki.garrysmod.com/page/GM/ChatText
Currently calls the hook with "none" requiring hacky message comparisons to detect if the message is from a convar change. Would also be nice to have some documentation on the possible types, as well.

**Comment by robotboy655** [comment]
They will appear under "servermsg" now, but there might be other messages there too. ( Entity.PrintMessage is not ). There isn't a way to make a FCVAR_NOTIFY one without doing something like an regexp, which you can do in Lua just as easily with Lua patterns.

**Comment by robotboy655** [comment]
Actually the only other hing in gmod that uses "servermsg" is clientside version of Entity.PrintMessage which I will change to none for consistency with the serverside methods, so you're all good if you only care about blocking them.

**Comment by Kefta** [comment]
Thanks!
