### ISSUE TITLE
Clientside Timeout hooks

### ISSUE THREAD

**Issue by MaxT09** [Facepunch/garrysmod-requests#914]
Add 2 new client side hooks one that is called when the client begins timing out and the other when/if they regain connection. This will be helpful as developers can accurately and efficiently know clientside when the client is timing out.

**Comment by Kefta** [comment]
Relevant code: https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/src_main/engine/cl_main.cpp#L1927-L1948

Bindings to CNetChan->IsTimingOut, GetTimeoutSeconds, and GetTimeSinceLastReceived would also be useful for those custom timeout screens without a bunch of extra and inaccurate Lua networking.

**Comment by VaasKahnGrim** [comment]
Would really love if these got added in on the next-next update. I'd imagine atleast the CNetChannel->IsTimingOut() one would be the most appreciated.

Been spending the last 10 minutes trying to find a way to get a timeout screen setup without having to involve shitty timers/networking/webservers/ect. Was about to make a request myself for it after digging through the source engine repo but looks like somebody already requested this being made available clientside.

**Comment by robotboy655** [comment]
Added GetTimeoutInfo() - returns bool IsTimingOut, float GetTimeSinceLastReceived
