### ISSUE TITLE
Stilling lua scripts from garrysmod/cache/lua

### ISSUE THREAD

**Issue by SNMetamorph** [Facepunch/garrysmod-requests#916]
Scripts just packed with LZMA, it so easy to unpack and very unsafe.
This action can be done with https://github.com/HandsomeMatt/glua-cache-extract

**Comment by Kefta** [comment]
What's your recommendation for a replacement?

**Comment by SNMetamorph** [comment]
Uploading scripts directly to RAM and execute scripts each time on connecting to server, of course I'm guessing it's slow because the developers could do so immediately. Or remodel scripts system to AMXX style (source -> compile -> file with bytecode)

**Comment by thegrb93** [comment]
The cache allows clients to not have to download all the lua each join. If you want DRM, make it yourself using the net or html library.

**Comment by SNMetamorph** [comment]
But what about the scripts that must be run directly from the client (e.g. custom HUD), or code that should be executed as often as possible (for example, think of a hook or other hooks related to graphics)?

**Comment by robotboy655** [comment]
```
But what about the scripts that must be run directly from the client (e.g. custom HUD), or code that should be executed as often as possible (for example, hook "Think" or other hooks related to graphics)?
```

Yes those scripts can never be safe, even "in RAM" because they still have to be ran on each client.
