### ISSUE TITLE
Bind Player->IsSprinting

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#919]
There is no current way shared to tell if the player is sprinting without checking the velocity and sprinting key state, which is all under the assumption that sprint is even enabled. m_fIsSprinting is available in the serverside savetable, but not clientside. This is an HL2 player method.

**Comment by robotboy655** [comment]
Added. I am not sure what's up with networking, it seems to work clientside in my test in local mp, for local player.
