### ISSUE TITLE
physprops->GetSurfaceData binding

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#923]
This method returns a lot of physics info of a surface relating to general properties, audio, and physical material. It is used at the core of many player movement and physics algorithms due to it having the most accurate information. My personal use case is player movement modification on rough surfaces, and more accurate texture-based bullet penetration.

Struct definition: https://github.com/LestaD/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/src_main/public/vphysics_interfaceV30.h#L866-L874

**Comment by Kefta** [comment]
Another use case: simulating physics impacts in Lua. The surface info contains the material sound.

**Comment by robotboy655** [comment]
Added
http://wiki.garrysmod.com/page/util/GetSurfaceData
