### ISSUE TITLE
Add Angle:Add, Mul, Sub, Div; and Vector:Div methods

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#925]
These are already binded on vectors. Using these methods instead of operations prevents creating another Angle object, and although these could easily be implemented in Lua, they would be slightly slower due to having to access and set userdata values 6-9 times.

Div method is missing on Vectors, as well.

**Comment by robotboy655** [comment]
Done.

**Comment by Kefta** [comment]
Thank you!
