### ISSUE TITLE
Make Player:ScreenFade() shared

### ISSUE THREAD

**Issue by jcwik223** [Facepunch/garrysmod-requests#926]
I know that UTIL_ScreenFade() is serverside only, but that seems to just be a leftover behaviour from HL/HL2 since those games being singleplayer didn't really matter on networking. In multiplayer, screenfade has to be called serverside, then networked to the specified client, which can cause a great amount of latency before the effect starts.

If the screenfade were to happen in response to the player zooming a weapon, it would take 2*ping for the key command to be sent to the server and the screenfade data to be sent back. In a 200 ping situation, that would almost be half a second before the screen fade actually starts. util.ScreenShake() and Player:SetFOV() are situations of methods that are shared so that they happen on the player immediately, but still maintain spectator and networking support. Player:ScreenFade() should also have this behaviour imo.

**Comment by Kefta** [comment]
The server doesn't even store the info or do anything special with the screen fade besides network it directly to the client. I don't know why this is serverside at all.

**Comment by Matsilagi** [comment]
I support of this.

**Comment by YuRaNnNzZZ** [comment]
Yeah, this definitely should happen.

**Comment by robotboy655** [comment]
Done
