### ISSUE TITLE
A new studiomdl command for including an entire model in-game

### ISSUE THREAD

**Issue by Zelpa** [Facepunch/garrysmod-requests#929]
Studiomdl has the $includemodel command which as the VDC says:

````
Adds a .mdl file that this .mdl will include at run-time, and all new sequences and animations will be appended to the model. Animations and sequences are processed in-order, and subsequent animations/sequences that have name conflicts will be ignored, and any references to .mdl local entry by the same name will be overwritten with the reference to a first one declared.

Included .mdl’s can have different bone ordering, but they need to have the same bone hierarchy and ikchain declarations. Currently there’s no run-time checking to verify they match.

Only animations and sequences are used from included .mdls. Currently models, textures, faces, attachments, etc. are ignored. 
````

I'm interested in the last line about only including animations and sequences. Would it be possible to create a new command called something like $includefullmodel which loads models, textures, etc. in game? An example where something like this is greatly needed is my Enhanced Citizens addon. Every male and female citizen uses the exact same torso, but I need to include that with every model. Instead I could have something like male_base.mdl and then simply $includefullmodel that in the subsequent models, which would cut down file sizes massively.

**Comment by Kefta** [comment]
That would require modellers to have the exact tri positions for the model base they are loading. I don't think it is worth it just to save the work of a little bit of body hacking.

**Comment by Zelpa** [comment]
Think of something like gun attachments, vertex alignment doesn't matter because you could just clip it into the body itself. Same for character models, really.

**Comment by Kefta** [comment]
Gun attachments should just be a separate model in that case, and attaching them to the gun should be done in the codebase

**Comment by robotboy655** [comment]
Just use bonemerging or body groups.

**Comment by Zelpa** [comment]
That's the issue, having to include the exact same bodygroups and skins in 11 different models seems kind of silly.
