### ISSUE TITLE
SENT Proxies

### ISSUE THREAD

**Issue by looterz** [Facepunch/garrysmod-requests#93]
From the thread on FP,

It would be nice if instead of overriding an entity in a map if you use its classname for a SENT, that you could set a bool on the SENT to be a proxy for that type of entity instead. For example, you could have a proxy prop_door_rotating, and instead of replacing every instance of prop_door_rotating it would have the entities in the map retain their source engine functionality but fire your proxy sents hooks as if it were a SENT. This way we could cleanly and efficiently manage data for doors in SetupDataTables, handle drawing over doors inside the entity, etc. without having to recreate the entities default functionality.

**Comment by robotboy655** [comment]
I don't think this is possible, this will require to edit every single entity in the engine to support this.

**Comment by looterz** [comment]
Yeah I believe it would, I'm going to close this request as it was pretty optimistic to begin with, there are bigger issues that need work.

**Comment by robotboy655** [comment]
To clarify, you can use SetupDataTables on engine entities with no problem by using Set/GetDT*, or jsut use Set/GetNW*.
