### ISSUE TITLE
GetParentToWorldTransform and EntityToWorldTransform bindings

### ISSUE THREAD

**Issue by jcwik223** [Facepunch/garrysmod-requests#930]
I'm currently making a vehicle system, and I am having difficulty in placing passengers and their vehicle exit points due to them being parented to an attachment. These methods would help correctly translate their space to accurate place them in the vehicle and leaving the vehicle.

**Comment by robotboy655** [comment]
Uh, WorldToLocal, LocalToWorld? there are globals, there are entity methods and I think even physobj methods with these names. Look it up on the wiki

**Comment by jcwik223** [comment]
They aren't the same. LocalToWorld/WorldToLocal just transform the position based on the angle and entity's world position while the specified methods take into account the move parent's transformation matrix and parent attachment. I specifically need the transformation matrix as the return.

**Comment by thegrb93** [comment]
There's GetBoneMatrix, but would need one for parent as well.

**Comment by Kefta** [comment]
The bone matrix isn't the same as what he's asking for

**Comment by Kefta** [comment]
https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/se2007/game/server/baseentity.h#L453-L465

**Comment by robotboy655** [comment]
Added Entity.GetParentToWorldTransformMatrix and Entity.GetEntityToWorldTransformMatrix, if you can think of a better name, do suggest.

Do note that they return 4x4 VMatrix while the data is a 3x4 matrix.

**Comment by robotboy655** [comment]
Scratch that second one, we already have it bound to https://wiki.garrysmod.com/page/Entity/GetWorldTransformMatrix
