### ISSUE TITLE
Allow trace filter to act as a whitelist

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#937]
At the suggestion of Willox; didn't even know this was possible to implement, but it would greatly improve a number of mechanics like bullet penetration and manual projectile collision testing.

**Comment by Kefta** [comment]
Note that this would eliminate the need for a functional filter in widgets along with https://github.com/Facepunch/garrysmod/pull/915

**Comment by zhne** [comment]
Any info on this request? Would be really useful.

**Comment by robotboy655** [comment]
Traces now have "whitelist" input property
This will turn the table filter into a whitelist, rather than ignore list. This will NOT affect function() filters
