### ISSUE TITLE
Implement the VMT parameter $phongalbedoboost

### ISSUE THREAD

**Issue by ghost** [Facepunch/garrysmod-requests#939]
For those of us making models for Garry's Mod, the VMTs are an extremely important area.  Both figuratively and literally, they are what really make the materials shine.  Albedotint is an important part of this, accurately representing the way metals tint reflections.  However, at the moment, this requires the creation of a separate $phongexponenttexture; if we had $phongalbedoboost, it would allow us to control the intensity of this tinting without the exponent texture, and also change it at runtime.

**Comment by robotboy655** [comment]
Added on `dev` beta.
