### ISSUE TITLE
Create IGmodAudioChannel from local files

### ISSUE THREAD

**Issue by looterz** [Facepunch/garrysmod-requests#94]
It would be nice if IGmodAudioChannel had a method similar to CSoundPatch's FadeOut.

Updated this issue in light of the upcoming patch to be a request for the ability to create IGmodAudioChannel's from local files rather than just files on the net.

**Comment by Grocel** [comment]
I think, it can be closed now. It got implemented a while ago as sound.PlayFile() (http://wiki.garrysmod.com/page/sound/PlayFile).
