### ISSUE TITLE
Make Entity.Remove queue removal in physics callbacks

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#940]
See here: https://facepunch.com/showthread.php?t=1537303&p=51983032&viewfull=1#post51983032

**Comment by Bo98** [comment]
This is already covered if we get #894.

**Comment by Kefta** [comment]
Doesn't it rely on the user to change their Remove code?

**Comment by Bo98** [comment]
Yes, but if you are going to change Entity:Remove's behaviour, then what about all the other functions that people may want to call post simulation?

Entity:Remove can be changed if it's really wanted but a solution for everything else is still needed.

**Comment by Kefta** [comment]
I was thinking of a convenience factor, but you are correct about it maintaining old addons.

**Comment by robotboy655** [comment]
`Entity.Remove` always queued its removals.
