### ISSUE TITLE
render.ViewDrawFade binding

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#942]
Used for the CS:S flash burn-in and fade effect

**Comment by robotboy655** [comment]
You can achieve it without any additional bindings tho?

**Comment by Kefta** [comment]
Partially, but I'm not sure on how to scale a render context or set it's orthogonal perspective projective-ly like the method does with the current bindings.

**Comment by Kefta** [comment]
It also draws a mesh onto the user's screen, which I'm not seeing a method to get the x/y coordinates of the screen in 3 space.

**Comment by robotboy655** [comment]
You are not getting what I am saying, you can use the Motion Blur's code to achieve similar if not the same effect.

**Comment by Kefta** [comment]
Motion blur is not the same thing. Concussion grenades leave a still-afterimage effect on the victim once their photorecepter cells have started to adjust to the light change. Think of an LED burn-in instead of motion artefacts which blur is more or less in the same vein of.

I just recreated the function with a misaligned orthogonal perspective. Good enough, I guess.

**Comment by robotboy655** [comment]
You can use Motion Blur's technique ( The Lua one ) to draw a single "still after-image" frame. Not suggesting replacing it with an actual full motion blur.
