### ISSUE TITLE
render.GetViewport binding or way to get render x,y coords

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#943]
The width and height of the viewport can already be retrieved from SrcW/SrcH, so adding a way to get the x, y coords modified by SetViewport is all that's really needed.

**Comment by robotboy655** [comment]
When do you ever need this?

**Comment by Kefta** [comment]
I was going to use it to move the user's screen to fix a world-aligned mesh, but I found a different way. Don't need this anymore.
