### ISSUE TITLE
PhysObj:GetShadowPosition

### ISSUE THREAD

**Issue by ZehMatt** [Facepunch/garrysmod-requests#944]
When shadow controllers are in use its not the same as GetPos, the function is required in order to get the real position of the moved object.

**Comment by thegrb93** [comment]
You tried both Entity.GetPos and PhysObj.GetPos right?

**Comment by ZehM4tt** [comment]
Its not the same thing, I wouldn't bother setting up this request if I didn't know better.

**Comment by robotboy655** [comment]
#998
