### ISSUE TITLE
Steam Cloud for saves/dupes

### ISSUE THREAD

**Issue by pugnaciousbear** [Facepunch/garrysmod-requests#947]
Is it possible make steam cloud synchronization work for dupes/saves? I have a few saves and having to copy them into my garrysmod saves file every time im using a different computer is getting a bit annoying.

Cheers,
runnerbeany

**Comment by robotboy655** [comment]
How often do you change your computer though. But yeah, it should be doable, along side custom spawnlists.

**Comment by runnerbeany** [comment]
I mean, i could be using my gaming desktop and later that evening I may want to use my laptop. This can be daily at times.

When you say doable, do you mean its already added or it should be?

**Comment by robotboy655** [comment]
You could set up some hack with dropbox and symlinks or whatever.

If it was already in the game, you'd be here asking for it now, would you? Or the issue would be closed.

**Comment by runnerbeany** [comment]
fair enough lol.

I do have a setup with onedrive, but it's just the copying can be a bit irritating. Does this sound like a good idea to you? :P

**Comment by thegrb93** [comment]
Don't know if having the data folder on the cloud is a good idea considering servers have access to it.

**Comment by runnerbeany** [comment]
In what way?

On 2 Apr 2017, at 23:54, thegrb93 <notifications@github.com<mailto:notifications@github.com>> wrote:


Don't know if having the data folder on the cloud is a good idea considering servers have access to it.

**Comment by KabusIblis** [comment]
You can write lots of garbage text files from a server to a clients data _(iirc)_

**Comment by robotboy655** [comment]
Saves (GMod ones not HL engine saves), Dupes, Demos (Gmod ones, not HL engine ones), Spawnlists and Toolgun Presets will now save on the cloud.

This change is live right now, not in the next update.
