### ISSUE TITLE
Add_Activity_Enum

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#950]
Some models use activity enums not defined in the codebase. Although this could be fixed by manually calling the sequence names (which might not always works if there are extra activity params/blending, or multiple sequences per activity) or recompiling the models, having a way to add custom activity enums or be a much cleaner and flexible solution. The naming comes from Add_NPC_Class.

**Comment by Luabee** [comment]
Hey yeah! This!

**Comment by LPDaVinci** [comment]
Yeah this -1 Appears on all Wiltos Anims as well 

https://steamcommunity.com/workshop/filedetails/?id=848978803

what causes this error?

**Comment by robotboy655** [comment]
https://wiki.facepunch.com/gmod/util.GetActivityIDByName

I think this solves this request.
