### ISSUE TITLE
GM:WeaponEquip hook is useless

### ISSUE THREAD

**Issue by uRandomAlex** [Facepunch/garrysmod-requests#951]
[GM:WeaponEquip](http://wiki.garrysmod.com/page/GM/WeaponEquip) hook is useless without player as an argument. You can supply player that picked up a weapon as the 2nd argument of the hook.

**Comment by fruitwasp** [comment]
Owner isn't set in the same frame. Put your code in a timer and call Weapon.GetOwner

**Comment by robotboy655** [comment]
Now its not?

http://wiki.garrysmod.com/page/GM/WeaponEquip
