### ISSUE TITLE
Add an option for uninstalling unsubbed addons

### ISSUE THREAD

**Issue by NewePone** [Facepunch/garrysmod-requests#952]
Addons slow down the game on launch, and they are not deleted when unsubbed to. It'd be great to have an option that checks the user's subscriptions, compares that list of addons with the installed ones and delete all those that are not present in the list of subbed addons

**Comment by Kefta** [comment]
Check console when you start up. There's a command called gma_cleanupunused or something like that

**Comment by Bo98** [comment]
There's the `menu_cleanupgmas` console command that should do what you want. Maybe it should be added to the UI.
