### ISSUE TITLE
Terminal window pops up every time a new CEF instance is created in dev branch.

### ISSUE THREAD

**Issue by ILOVEPIE** [Facepunch/garrysmod-requests#956]
This issue causes the mouse not to respond temporarily it's not a major problem but it is rather jarring.

**Comment by robotboy655** [comment]
Why are these in requests?

**Comment by ILOVEPIE** [comment]
oops sorry, my bad I put them in the wrong bugtracker do you want me to move them over to the other one?

**Comment by robotboy655** [comment]
Yes please.
