### ISSUE TITLE
A console command for refreshing models on runtime

### ISSUE THREAD

**Issue by Klizmotron** [Facepunch/garrysmod-requests#957]
I think it's self-explanatory, cached _materials_ and _sounds_ can be reloaded into the game on runtime, while _models_ are **not the case**. When you work on some models and check the results in-game it requires to restart the game, you can't flush the model and load a new one on it's place without restarting the game. Probably there is a reason behind it, but it would be sick to make something like _reloadmodel path/to/model.mdl_ which applies changes of both visual and physical meshes on runtime, since _hlmv.exe_ is an old and buggy piece of ~~_shit_~~ software

**Comment by Kefta** [comment]
Changing a model in realtime could cause its bone structure to change, and anything caching bones for drawing/manipulations could be fucked due to that.

**Comment by thegrb93** [comment]
There is a console command, I think it's something like r_flushdetail or r_refreshdetail and yeah it crashes if you decrease the number of bones.

**Comment by robotboy655** [comment]
its `r_flushlod` and it won't ever work properly, it doesn't reload the physics mesh due to `vphysics` complications.

**Comment by nikioto1** [comment]
note to everyone searching this: best closest thing to this we have is "reload" command
