### ISSUE TITLE
An ability to use multi-materials with IMesh

### ISSUE THREAD

**Issue by Klizmotron** [Facepunch/garrysmod-requests#958]
[IMesh](http://wiki.garrysmod.com/page/Global/Mesh) is an incredibly powerful tool which has limitless potential. I am working on a cool project using it at the moment, but I faced a small thing can be improved, and that is an ability to set material indexes for individual triangles of the mesh and then use [render.MaterialOverrideByIndex](http://wiki.garrysmod.com/page/render/MaterialOverrideByIndex) to set the materials. As for now I have to split my object into several separate meshes, one per material, that is not very optimal

You could add an additional field to [MeshVertex](http://wiki.garrysmod.com/page/Structures/MeshVertex) structire, something like **[number](http://wiki.garrysmod.com/page/Category:number) matindex=nil** which could be passed in a current vertex in the table to use this material ID for the current and the following triangles in the mesh until a new material ID is passed in another vertex. You could also make something like [mesh.MatIndex](http://wiki.garrysmod.com/page/mesh/MatIndex) which functions in a way similar to [mesh.Color](http://wiki.garrysmod.com/page/mesh/Color) or [mesh.Position](http://wiki.garrysmod.com/page/mesh/Position). Or maybe you could come up with something more clever

**Comment by thegrb93** [comment]
You have to group the faces with different materials into separate meshes and render each mesh with the material.

**Comment by thegrb93** [comment]
I think directx10 supports what you are suggesting, but not directx9

**Comment by Klizmotron** [comment]
@thegrb93 Yeah, that's what I'm doing at the moment

**Comment by robotboy655** [comment]
>You have to group the faces with different materials into separate meshes and render each mesh with the seperate material.

This is what you will have to do, that's what the engine does.
