### ISSUE TITLE
Ability to set NPC Gender rather than using global_actors.txt

### ISSUE THREAD

**Issue by Vinzuerio** [Facepunch/garrysmod-requests#965]
The new Garry's Mod did update and adds the health function to the npc_citizen (as well as other npcs) which is now worked properly.

Now, there is a thing called '[global_actors.txt](https://github.com/LestaD/SourceEngine2007/blob/master/src_main/soundemittersystem/soundemittersystembase.cpp#L596)', which it sets the npc (or player) gender based on their modelnames, and the npc will use whether it'll be male voice or female voice when interacting to the player (for example: Pressing E).
This especially set to npc_citizen if the keyvalue of citizentype set to 4 (Unique).

**However**, without having to modify global_actors.txt (which, also gmad doesn't allow custom global_actors.txt script) with a custom NPC models, they will use a random gender voices and they also not even talk when being interacted from the player, being attacked, and such (except if they were dying, and etc).

I've [tried this](https://gist.github.com/Vinzuerio/1f8f4171a991f484248b64630aebd853) as alternative but it seems nothing to work after the npc dies, or being attacked (because the entity become null after they died)

The request is, Is it possible or at least will be there an ability to set gender on NPC in lua environment or maybe another method? (like set based on modelnames)

**Comment by crestfall1117** [comment]
It would be nice if there's a new keyvalue to override their gender. Also 7 year bump...
