### ISSUE TITLE
Ability to get SurfaceProp/Mass from model

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#967]
Models have $surfaceprop and $mass (in the $collisionmodel structure) defined in their QC, but there is no way to retrieve these values from the Lua state. Two relevant functions are Studio_GetDefaultSurfaceProps and Studio_GetMass.

**Comment by robotboy655** [comment]
Does http://wiki.garrysmod.com/page/util/GetModelInfo not return those?

**Comment by Kefta** [comment]
It does -- forgot that function existed. Thanks
