### ISSUE TITLE
Disconnect messages

### ISSUE THREAD

**Issue by foresteam** [Facepunch/garrysmod-requests#970]
How to remove disconnect messages? (Like this: https://www.dropbox.com/s/1p0b7eo56xypnxz/20170521132102_1.jpg?dl=0 )

**Comment by Kefta** [comment]
Block the joinleave type here: http://wiki.garrysmod.com/page/GM/ChatText

In the future, post help threads here: http://facepunch.com/forumdisplay.php?f=65

**Comment by foresteam** [comment]
Thank you.
