### ISSUE TITLE
Metatable bug

### ISSUE THREAD

**Issue by StidOfficial** [Facepunch/garrysmod-requests#974]
I have a bug in lua, on serverside for player metatable.
If i initialize table variable in player metatable. The server copy table variable of last player connected for new player connection.
The table is replicated after clientsize InitPostEntity()

**Comment by Kefta** [comment]
Could you post example code of what you mean? Your English is a bit confusing

**Comment by StidOfficial** [comment]
`
-- Serverside
local PLAYER = FindMetaTable("Player")
PLAYER.List = {} -- If you remove this line, you doesn't have bug

function PLAYER:GetList()
	return self.List
end
util.AddNetworkString("Init")
net.Receive("Init", function(len, ply)
	print(ply)
	PrintTable(ply:GetList())
end)

-- Clientside
hook.Add("InitPostEntity", "Init", function()	
	net.Start("Init")
	net.SendToServer()
end)`

**Comment by bmwalters** [comment]
@StidOfficial https://guides.github.com/features/mastering-markdown/#Syntax%20highlighting then search the page for "Syntax highlighting"

**Comment by Kefta** [comment]
This is due to how the player __index method works. I requested it to be changed here: https://github.com/Facepunch/garrysmod-requests/issues/901

**Comment by bigdogmat** [comment]
Unless I'm misunderstanding the issue, the issue is both players are sharing the same list. If you want them to be separate then you should set/create the tables on player spawn.

**Comment by StidOfficial** [comment]
If the variable is initialized, gmod made memory copy relative of last player metatable created. But all work if you don't initialize the variable.

**Comment by Kefta** [comment]
It does not make a memory copy. It uses the table you are initialising in the metatable and uses it for all players. You have to set up the variable in an OnEntityCreated hook or something.

**Comment by StidOfficial** [comment]
Ha, if i initialize a variable in metatable. This variable is shared for all player, is not initialized for self player ?

**Comment by Kefta** [comment]
Your english is still very confusing

**Comment by bigdogmat** [comment]
If you initialize the variable in the player meta table then yes, it'll be shared for all players.

**Comment by StidOfficial** [comment]
okey, thanks
