### ISSUE TITLE
Make ConVar API 'more consistent and complete'

### ISSUE THREAD

**Issue by CaptainPRICE** [Facepunch/garrysmod-requests#975]
[ConVar wiki](https://wiki.garrysmod.com/page/Category:ConVar).

**Introduce new ConVar functions**:
- [ ] `AddFlags` (should only be available to ConVar created with GLua): [convar.h](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/public/tier1/convar.h#L344), [convar.cpp](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/tier1/convar.cpp#L709-L716)
- [x] `GetFlags`: [convar.h](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/public/tier1/convar.h#L389)
- [x] `GetMax`: [convar.h](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/public/tier1/convar.h#L369), [convar.cpp](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/tier1/convar.cpp#L1035-L1043)
- [x] `GetMin`: [convar.h](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/public/tier1/convar.h#L368), [convar.cpp](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/tier1/convar.cpp#L1024-L1034)
- [ ] `HasMax`: [convar.h](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/public/tier1/convar.h#L412)
- [ ] `HasMin`: [convar.h](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/public/tier1/convar.h#L410)
- [ ] `SetDefault` (should only be available to ConVar created with GLua): [convar.h](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/public/tier1/convar.h#L371), [convar.cpp](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/tier1/convar.cpp#L1054-L1058)
- [ ] `SetMax` (should only be available to ConVar created with GLua): [convar.h](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/public/tier1/convar.h#L413) (Remember to call <code><a href="https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/tier1/convar.cpp#L839-L859">ConVar::ClampValue</a></code> after changing `m_fMaxVal`. Perhaps return a boolean `true` for this function to indicate a value has been changed.)
- [ ] `SetMin` (should only be available to ConVar created with GLua): [convar.h](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/public/tier1/convar.h#L411) (Remember to call <code><a href="https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/tier1/convar.cpp#L839-L859">ConVar::ClampValue</a></code> after changing `m_fMinVal`. Perhaps return a boolean `true` for this function to indicate a value has been changed.)

**Optional enhancements**:
- Modify <code><a href="https://wiki.garrysmod.com/page/Global/CreateConVar">CreateConVar</a></code> function to allow setting of min/max values. ([Just for convenience](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/tier1/convar.cpp#L655-L658).)
- Introduce the <code><a href="https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/public/tier1/convar.h#L340">ConVar::IsFlagSet</a></code> function. ([Just for convenience](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/public/tier1/iconvar.h#L114), [convar.cpp](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/tier1/convar.cpp#L699-L702).)
- Allow `ConVar` created with GLua to be "reverted". ([Just for convenience](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/public/tier1/convar.h#L365), [convar.cpp](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/tier1/convar.cpp#L1014-L1022).)
- Allow `ConVar` created with GLua to be removed. (We can remove a `ConCommand`, but why not allow us to remove a `ConVar`? I think, since there is no builtin function, one way to accomplish removal would be to modify a linked-list to skip over a specific ConVar.)
- ~~Allow `Flags` to be excluded from a ConVar created with GLua.~~ (nope.)

**Comment by robotboy655** [comment]
Ok, so I don't mind adding the mix/max stuff, but the question is, what should GetMin do when it has no minimum set? Return nil? Return 2 values: hasMin, minIfExists?

**Comment by Kefta** [comment]
Returning nil when there's no min/max would suffice and remove the need HasMin/Max. Please add GetFlags along with those at least if you don't want to bother with making SetDefault/SetFlags only work with Lua cvars right now.

**Comment by robotboy655** [comment]
Added optional min and max arguments to Create(Client)ConVar
Added ConVar.GetFlags, IsFlagSet, GetMin and GetMax

I don't really see much use for the rest.

**Comment by Kefta** [comment]
Revert is the only other thing I see that useful here, which would simply convar callback bound checking code.

**Comment by robotboy655** [comment]
Right, I will add revert too.

**Comment by CaptainPRICE** [comment]
Good job.

(time to refactor Lua stuff.)
