### ISSUE TITLE
Implement particle rain/snow from Alien Swarm?

### ISSUE THREAD

**Issue by Havch1k92** [Facepunch/garrysmod-requests#976]
https://github.com/Sandern/aswscratch/blob/master/src/game/client/c_effects.cpp

**Comment by Kefta** [comment]
Similar to https://github.com/Facepunch/garrysmod-requests/issues/779

**Comment by robotboy655** [comment]
Not at all, duplicate of #809 really.

**Comment by Kefta** [comment]
Oh I didn't see his link, I thought it was an effect not an actual entity
