### ISSUE TITLE
Expand documentation on GetToolMenu on the Gmod Wiki

### ISSUE THREAD

**Issue by Servius** [Facepunch/garrysmod-requests#979]
Expand documentation on GetToolMenu on the Gmod Wiki. 
Trying to do some stuff with the Spawnmenu. Please help. 
http://wiki.garrysmod.com/page/spawnmenu/GetToolMenu

**Comment by robotboy655** [comment]
Done

**Comment by Kefta** [comment]
The return is still a bit hazy
