### ISSUE TITLE
Make a way to get guaranteed built-in functions

### ISSUE THREAD

**Issue by EstevanTH** [Facepunch/garrysmod-requests#983]
Hey there!

I'm working on DRMs and anti-theft scripts, and I have a request that will interest anybody interesting in making paid or safe code, without any risk of using altered functions, for code stealing purpose.

Here is my solution. I'm not interested in using Lua in my programs yet, so I may say mistakes in my ideas, but overall this should be feasible.

# Step 1:
Before running any editable Lua script, do a copy of all C-defined Lua functions into a table in a safe place (Lua registry or other). If possible, the table can be directly done or translated in C.

In addition, functions from Garry's Mod metatables can be copied.
```lua
local builtin = {}
local type_
local name
local processed = {_G}
local function makeList( tab, prefix )
	for k, v in pairs( tab ) do
		type_ = type( v )
		name = prefix and prefix.."."..k or k
		if type_=="function" then
			builtin[name] = v
		elseif type_=="table" and not processed[v] then
			processed[v] = true
			makeList( v, name )
		end
	end
end
makeList( _G )
```

## Result:
```lua
-- Content of builtin:
{
	["debug.getinfo"] = function: builtin#125,
	["HTTP"] = function: 0x34911ac8,
	["jit.util.funcinfo"] = function: builtin#141,
	["string.sub"] = function: builtin#76,
	["tostring"] = function: builtin#18,
	-- and so on...
}
```

# Step 2:
Whenever requested, the Lua keyword `GET_BUILTIN( "debug.getinfo" )` will return the function from the secret `builtin` table or make it available as `_builtin["debug.getinfo"]` or something.

The idea is inspired by the keyword [`DEFINE_BASECLASS()`](http://wiki.garrysmod.com/page/Global/DEFINE_BASECLASS) from Garry's Mod.

# Step 3:
If something is stored in the Lua registry then removing the function [`debug.getregistry()`](http://wiki.garrysmod.com/page/debug/getregistry) is necessary to avoid any illegal modifications.

# End of transmission
If you like the idea, please thumb up and encourage the passionate [willox](https://github.com/willox) to make this possible.

This message won't self-destroy. 😝

Love, Momo. ❤️

**Comment by Kefta** [comment]
A client could easily override this -- just use debug.getupvalue. Completely unnecessary

**Comment by EstevanTH** [comment]
Then let's remove the dangerous `debug.setupvalue()` as well! 😈

**Comment by neico** [comment]
In a perfect world the entire debug library wouldn't be exposed. (as it's only supposed to be used for debugging)

In practice it's are needed for many edge cases by now, and just for the purpose of making DRM stuff this all seems like a very weak reason.

if you want to protect your code use a private C++ Module...

in fact, if gmod weren't using LuaJIT and a more recent lua version you could easily implement this little code and protect things you feel need protecting (comes with a slight overhead of course): https://gitlab.com/yas-online/lua/commit/35ec23222aea258d71cb5f70ac898a51a2bc743e

**Comment by EstevanTH** [comment]
Thanks! 😄

And by the way, I cannot protect client Lua code with a binary module, so I need help from Lua only. 😛

My wish is turning into a dying dream. 😢

**Comment by EstevanTH** [comment]
Yipee, the beginning of a solution has been made!

The following functions have been removed from Garry's Mod:
- debug.setlocal()
- debug.setupvalue()
- debug.upvalueid()
- debug.upvaluejoin()

**Comment by Kefta** [comment]
glua.team will be appealing to John Lua and the grand JIT council about this unfortunate decision.

**Comment by meepdarknessmeep** [comment]
this is extremely retarded

**Comment by meepdarknessmeep** [comment]
they didn't remove those functions because of this post because this post is retarded

**Comment by EstevanTH** [comment]
Whether the removal has been made because of my post or not is not the question here.

I just told that it's a good news for safety in Lua anti-theft scripts.

**Comment by meepdarknessmeep** [comment]
if you think this helps anti theft at all you are retarded as well

**Comment by EstevanTH** [comment]
It actually does. It was a huge breach that could be used to modify decryption functions etc. and could easily be used to catch the key or decrypted content.

**Comment by meepdarknessmeep** [comment]
news flash: people who want to do this can just take it even if there was no way to inject lua

**Comment by EstevanTH** [comment]
Yes they can, but it's much more difficult.

**Comment by EgrOnWire** [comment]
Step 1. Hook gmod LUA factory and get code
Step 2. Deobfuscate
Step 3. ~~PROFIT~~ Stolen.

**Comment by EstevanTH** [comment]
Yep, not everyone is able to achieve this.

**Comment by EstevanTH** [comment]
I know that there is something to do. The only problem is that I always go round and round every time I find a solution to guarantee anything because:
- remove a function from your security, boom, error before any check
- modify a function that is required for check: boom, the check does not fail when it should

I agree that Garry's Mod is somehow about free content on the Workshop, but not only. Sometimes it's necessary to prevent script capture and script stealing.

Solving the problem by inserting some kind of backdoor and obfuscating is really bad in my opinion. I hate malicious scripts. Sometimes when you get a script, you do not even know that it's stolen! And it's no guarantee because there is a way to de-obfuscate and remove malicious content.

**Comment by EstevanTH** [comment]
Okay I have found a solution, finally.

To work around Lua code catching libraries, I'll do my client code in JavaScript instead of Lua. This way, no code will be captured. But still, this is not exactly safe in any way.
