### ISSUE TITLE
Prevent viewmodels getting rotated when zooming

### ISSUE THREAD

**Issue by Havch1k92** [Facepunch/garrysmod-requests#985]
In view.cpp search for m_View.fovViewmodel = g_pClientMode->GetViewModelFOV() - flFOVOffset;
Change it to m_View.fovViewmodel = abs(g_pClientMode->GetViewModelFOV() - flFOVOffset);
(Taken form VDC)

**Comment by willox** [comment]
I think this was fixed in the dev branch a couple of weeks ago. Did you try reproducing the bug there?
