### ISSUE TITLE
Update hlmv.exe

### ISSUE THREAD

**Issue by Tripperful** [Facepunch/garrysmod-requests#986]
Garry's Mod model viewer lacks some good features that are present in other Source games hlmv (I compared it to HL2:DM hlmv.exe)

I'm not sure which base hlmv gmod uses and if it's a newer or an older one, I'm just missing these features like multi weapons merging, origin axis and UV chart rendering and would love them to be added

![](http://i.imgur.com/H9QNwug.png)

**Comment by robotboy655** [comment]
Updated it to the latest version we can get, those features are in, but boneflexes are not. It'd need a lot of merging to accomplish and that's not a thing I'd want to do right before an update.

**Comment by Kefta** [comment]
Will they be added post-updated (specifically activity modifiers)?

**Comment by robotboy655** [comment]
Possibly, if we don't forget and merge upstream changes to the engine regarding model loading.
