### ISSUE TITLE
Turn on and turn off ProjectedTexture

### ISSUE THREAD

**Issue by CornerPin** [Facepunch/garrysmod-requests#987]
Request to add TurnOn and TurnOff methods to [ProjectedTexture](http://wiki.garrysmod.com/page/Global/ProjectedTexture).
It exists in **env_projectedtexture** inputs but not in **ProjectedTexture**. And it would be nice if you add Toggle.

**Comment by Jvs34** [comment]
TurnOn and TurnOff actually create or destroy the projected texture as there's no way to make it "dormant" or disabled, so there's really no "proper" way.

You could modify the brightness if you want it not to be removed.

**Comment by CornerPin** [comment]
In [env_projectedtexture.cpp](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/env_projectedtexture.cpp) it just sets **m_bState** to true or false.
```C++
void CEnvProjectedTexture::InputTurnOn( inputdata_t &inputdata )
{
	m_bState = true;
}

void CEnvProjectedTexture::InputTurnOff( inputdata_t &inputdata )
{
	m_bState = false;
}
```

**Comment by willox** [comment]
Yeah, that'll still cause what @Jvs34 stated to happen on the client. I don't think I'll be implementing this.

**Comment by Kefta** [comment]
You can always use SetSaveValue for m_bState anyway since it's a defined field.
