### ISSUE TITLE
Add Entity.IsScripted

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#990]
To differentiate between engine ents and SENTs, just like Weapon.IsScripted.

**Comment by robotboy655** [comment]
I guess you could use ```Entity.Type != nil``` as a substitute for now ( or any other autoset/guaranteed field )

**Comment by Kefta** [comment]
Yeah, I am doing that with .Base right now

**Comment by robotboy655** [comment]
Done
