### ISSUE TITLE
New command to Sandbox

### ISSUE THREAD

**Issue by Perkzitos** [Facepunch/garrysmod-requests#995]
Create a new command, **sbox_thirdperson**! It's like **sbox_noclip**, when 1 you are able to use the **thirdperson** command without sv_cheats 1 and when 0 all players that are using thirdperson will back to firstperson. This command no have any difference if sbox_thirdperson and sv_cheats are 1 when use thirdperson command.

**Comment by robotboy655** [comment]
This something a mod is supposed to do.
