### ISSUE TITLE
Allow physgun beam colour to be set independently of the physgun

### ISSUE THREAD

**Issue by LuaTenshi** [Facepunch/garrysmod-requests#996]
Add a command like cl_weaponcolor that will allow users to set the colour of their physgun **beam** separately from the players Weapon Color. I think `cl_beamcolor` would be a good name for this.

I've been trying to find a way to do this myself but had no luck with any of my attempts the sprites used don't seem to have a "PlayerWeaponColor" proxy like the physgun does.

If I figure this out before you do, I'll post it here. If anyone has any tips for this please let me know.

**Comment by Electfried** [comment]
Personally, I like being able to mess up my physgun color. Maybe make it a feature so you can either do the original cl_weaponcolor where you can mess things up and toggle beam color if you want to.
